### ISSUE TITLE
`cask update` is blocked by git merge conflicts

### ISSUE THREAD

**Issue by adamtait** [caskroom/homebrew-cask#10037]
I haven't looked into what cask is actually trying to do here, or why it would fail. Here's the error; it's a persistent problem and not related to permissions.

```bash
❯ brew cask update
error: Your local changes to the following files would be overwritten by merge:
	Library/Contributions/brew_fish_completion.fish
	Library/Contributions/brew_zsh_completion.zsh
	Library/Contributions/example-formula.rb
	Library/ENV/4.3/bsdmake
	Library/Formula/abcde.rb
	Library/Formula/abcm2ps.rb
	Library/Formula/abcmidi.rb
	Library/Formula/abnfgen.rb
	Library/Formula/ace.rb
	Library/Formula/acme.rb
	Library/Formula/acpica.rb
	Library/Formula/activemq-cpp.rb
	Library/Formula/adns.rb
	Library/Formula/adobe-air-sdk.rb
	Library/Formula/aescrypt.rb
	Library/Formula/afflib.rb
	Library/Formula/afsctool.rb
	Library/Formula/aget.rb
	Library/Formula/aha.rb
	Library/Formula/akka.rb
	Library/Formula/align.rb
	Library/Formula/alpine.rb
	Library/Formula/amap.rb
	Library/Formula/analog.rb
	Library/Formula/android-ndk.rb
	Library/Formula/android-platform-tools.rb
	Library/Formula/android-sdk.rb
	Library/Formula/ansible.rb
	Library/Formula/ansifilter.rb
	Library/Formula/apache-spark.rb
	Library/Formula/ape.rb
	Library/Formula/apib.rb
	Library/Formula/app-engine-java-sdk.rb
	Library/Formula/appscale-tools.rb
	Library/Formula/arangodb.rb
	Library/Formula/argus-clients.rb
	Library/Formula/argus.rb
	Library/Formula/aria2.rb
	Library/Formula/arp-scan.rb
	Library/Formula/artifactory.rb
	Library/Formula/asn1c.rb
	Library/Formula/aspell.rb
	Library/Formula/assimp.rb
	Library/Formula/astyle.rb
	Library/Formula/at-spi2-atk.rb
	Library/Formula/at-spi2-core.rb
	Library/Formula/atomicparsley.rb
	Library/Formula/ats2-postiats.rb
	Library/Formula/aubio.rb
	Library/Formula/auctex.rb
	Library/Formula/augeas.rb
	Library/Formula/autoconf-archive.rb
	Library/Formula/autoenv.rb
	Library/Formula/avfs.rb
	Library/Formula/avian.rb
	Library/Formula/avra.rb
	Library/Formula/aws-elasticbeanstalk.rb
	Library/Formula/aws-sns-cli.rb
	Library/Formula/awscli.rb
	Library/Formula/bacula-fd.rb
	Library/Formula/bash-git-prompt.rb
	Library/Formula/bazaar.rb
	Library/Formula/beecrypt.rb
	Library/Formula/betty.rb
	Library/Formula/bfg.rb
	Library/Formula/bibtex2html.rb
	Library/Formula/bind.rb
	Library/Formula/binwalk.rb
	Library/Formula/bitlbee.rb
	Library/Formula/blitz.rb
	Library/Formula/boost.rb
	Library/Formula/boot2docker.rb
	Library/Formula/boxes.rb
	Library/Formula/bpm-tools.rb
	Library/Formula/bsdiff.rb
	Library/Formula/bup.rb
	Library/Formula/burp.rb
	Library/Formula/cabextract.rb
	Library/Formula/cairo.rb
	Library/Formula/cairomm.rb
	Library/Formula/capstone.rb
	Library/Formula/cardpeek.rb
	Library/Formula/cassandra.rb
	Library/Formula/caudec.rb
	Library/Formula/cc65.rb
	Library/Formula/ccache.rb
	Library/Formula/ccm.rb
	Library/Formula/cdparanoia.rb
	Library/Formula/cfengine.rb
	Library/Formula/cgal.rb
	Library/Formula/cgrep.rb
	Library/Formula/cheat.rb
	Library/Formula/cherokee.rb
	Library/Formula/chibi-scheme.rb
	Library/Formula/chktex.rb
	Library/Formula/chromedriver.rb
	Library/Formula/chruby.rb
	Library/Formula/chuck.rb
	Library/Formula/clamav.rb
	Library/Formula/clib.rb
	Library/Formula/cliclick.rb
	Library/Formula/closure-compiler.rb
	Library/Formula/clutter-gtk.rb
	Library/Formula/clutter.rb
	Library/Formula/cmake.rb
	Library/Formula/cocot.rb
	Library/Formula/cogl.rb
	Library/Formula/cookiecutter.rb
	Library/Formula/coq.rb
	Library/Formula/corkscrew.rb
	Library/Formula/couchpotatoserver.rb
	Library/Formula/cpanminus.rb
	Library/Formula/cpmtools.rb
	Library/Formula/cppunit.rb
	Library/Formula/cpputest.rb
	Library/Formula/cracklib-words.rb
	Library/Formula/cracklib.rb
	Library/Formula/crosstool-ng.rb
	Library/Formula/ctags.rb
	Library/Formula/ctail.rb
	Library/Formula/cuetools.rb
	Library/Formula/curl.rb
	Library/Formula/cvs.rb
	Library/Formula/d-bus.rb
	Library/Formula/dante.rb
	Library/Formula/daq.rb
	Library/Formula/dar.rb
	Library/Formula/dash.rb
	Library/Formula/datomic.rb
	Library/Formula/davix.rb
	Library/Formula/dcmtk.rb
	Library/Formula/dfu-util.rb
	Library/Formula/dgtal.rb
	Library/Formula/direnv.rb
	Library/Formula/disco.rb
	Library/Formula/dnscrypt-proxy.rb
	Library/Formula/dnsmasq.rb
	Library/Formula/docker.rb
	Library/Formula/dockutil.rb
	Library/Form
error: The following untracked working tree files would be overwritten by merge:
	Library/Aliases/actor-framework
	Library/ENV/pkgconfig/10.10/sqlite3.pc
	Library/ENV/pkgconfig/10.10/zlib.pc
	Library/ENV/pkgconfig/10.6/sqlite3.pc
	Library/ENV/pkgconfig/10.6/zlib.pc
	Library/ENV/pkgconfig/10.7/sqlite3.pc
	Library/ENV/pkgconfig/10.7/zlib.pc
	Library/ENV/pkgconfig/10.8/sqlite3.pc
	Library/ENV/pkgconfig/10.8/zlib.pc
	Library/ENV/pkgconfig/10.9/sqlite3.pc
	Library/ENV/pkgconfig/10.9/zlib.pc
	Library/Formula/aescrypt-packetizer.rb
	Library/Formula/afl-fuzz.rb
	Library/Formula/aptly.rb
	Library/Formula/arpon.rb
	Library/Formula/blucat.rb
	Library/Formula/bwctl.rb
	Library/Formula/chinadns-c.rb
	Library/Formula/closure-linter.rb
	Library/Formula/ctunnel.rb
	Library/Formula/deis.rb
	Library/Formula/dsd.rb
	Library/Formula/ebook-tools.rb
	Library/Formula/epeg.rb
	Library/Formula/euler-py.rb
	Library/Formula/ffts.rb
	Library/Formula/flow.rb
	Library/Formula/gammaray.rb
	Library/Formula/gdnsd.rb
	Library/Formula/gifify.rb
	Library/Formula/git-review.rb
	Library/Formula/glbinding.rb
	Library/Formula/gnatsd.rb
	Library/Formula/hardlink-osx.rb
	Library/Formula/hh.rb
	Library/Formula/i2util.rb
	Library/Formula/icdiff.rb
	Library/Formula/idris.rb
	Library/Formula/jooby-bootstrap.rb
	Library/Formula/kore.rb
	Library/Formula/libbpg.rb
	Library/Formula/libiomp.rb
	Library/Formula/libpointing.rb
	Library/Formula/libsoxr.rb
	Library/Formula/lsh.rb
	Library/Formula/makefile2graph.rb
	Library/Formula/megatools.rb
	Library/Formula/mitie.rb
	Library/Formula/mvnvm.rb
	Library/Formula/mysql-sandbox.rb
	Library/Formula/nailgun.rb
	Library/Formula/odo.rb
	Library/Formula/odt2txt.rb
	Library/Formula/open-zwave.rb
	Library/Formula/openh264.rb
	Library/Formula/osquery.rb
	Library/Formula/pcsc-lite.rb
	Library/Formula/queequeg.rb
	Library/Formula/rbenv-bundle-exec.rb
	Library/Formula/rbenv-bundler-ruby-version.rb
	Library/Formula/restund.rb
	Library/Formula/rocket.rb
	Library/Formula/simple-amqp-client.rb
	Library/Formula/smali.rb
	Library/Formula/snow.rb
	Library/Formula/stlink.rb
	Library/Formula/stoken.rb
	Library/Formula/synscan.rb
	Library/Formula/tippecanoe.rb
	Library/Formula/ucommon.rb
	Library/Formula/vnu.rb
	Library/Formula/wakatime-cli.rb
	Library/Formula/with-readline.rb
	Library/Homebrew/requirements/tuntap_dependency.rb
Please move or remove them before you can merge.
Aborting
Error: Failure while executing: git pull -q origin refs/heads/master:refs/remotes/origin/master
Please report this bug:
    https://github.com/caskroom/homebrew-cask/issues
/usr/local/Library/Homebrew/utils.rb:134:in `safe_system'
/usr/local/Library/Homebrew/cmd/update.rb:159:in `block in pull!'
/usr/local/Library/Homebrew/cmd/update.rb:165:in `block in reset_on_interrupt'
/usr/local/Library/Homebrew/utils.rb:240:in `ignore_interrupts'
/usr/local/Library/Homebrew/cmd/update.rb:165:in `reset_on_interrupt'
/usr/local/Library/Homebrew/cmd/update.rb:159:in `pull!'
/usr/local/Library/Homebrew/cmd/update.rb:29:in `update'
/usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/cli/update.rb:5:in `run'
/usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/cli.rb:81:in `run_command'
/usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/cli.rb:121:in `process'
/usr/local/bin/brew-cask.rb:42:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:59:in `require?'
/usr/local/Library/brew.rb:142:in `<main>'
```

**Comment by adamtait** [comment]
Here's my install info:
```
❯ brew cask doctor
==> OS X Version:
10.10.2
==> Hardware Architecture:
intel-64
==> Ruby Version:
2.0.0-p481
==> Ruby Path:
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
==> Homebrew Version:
0.9.5
==> Homebrew Executable Path:
/usr/local/bin/brew
==> Homebrew Cellar Path:
/usr/local/Cellar
==> Homebrew Repository Path:
/usr/local
==> Homebrew Origin:
https://github.com/Homebrew/homebrew
==> Homebrew-cask Version:
0.46.0
==> Homebrew-cask Install Location:
/usr/local/Cellar/brew-cask/0.46.0
==> Homebrew-cask Staging Location:
/opt/homebrew-cask/Caskroom (error: not writable by current user)
==> Homebrew-cask Cached Downloads:
/Library/Caches/Homebrew
/Library/Caches/Homebrew/Casks
0 files
0.00 megs
==> Homebrew-cask Default Tap Path:
/usr/local/Library/Taps/caskroom/homebrew-cask
==> Homebrew-cask Alternate Cask Taps:
<NONE>
==> Homebrew-cask Default Tap Cask Count:
2015
==> Contents of $LOAD_PATH:
/usr/local/Cellar/brew-cask/0.46.0/rubylib
/usr/local/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin14
/Library/Ruby/Site/2.0.0/universal-darwin14
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin14
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin14
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin14
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin14
==> Contents of $RUBYLIB Environment Variable:
<NONE>
==> Contents of $RUBYOPT Environment Variable:
<NONE>
==> Contents of $RUBYPATH Environment Variable:
<NONE>
==> Contents of $RBENV_VERSION Environment Variable:
<NONE>
==> Contents of $CHRUBY_VERSION Environment Variable:
<NONE>
==> Contents of $GEM_HOME Environment Variable:
<NONE>
==> Contents of $GEM_PATH Environment Variable:
<NONE>
==> Contents of $BUNDLE_PATH Environment Variable:
<NONE>
==> Contents of $PATH Environment Variable:
PATH="/Users/atait1/.dotfiles/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/texbin:/Users/atait1/.dev-scripts/bin:/usr/local/heroku/bin:/usr/local/Library/ENV/scm"
==> Contents of $SHELL Environment Variable:
SHELL="/bin/zsh"
==> Contents of Locale Environment Variables:
LANG="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
==> Running As Privileged User:
No
```

**Comment by vitorgalvao** [comment]
You’re using an old version of homebrew-cask. Please `brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup` and try again.

Please [always do this before opening new issues](https://github.com/caskroom/homebrew-cask#reporting-bugs).
