### ISSUE TITLE
Wrong number of arguments in basictex formula

### ISSUE THREAD

**Issue by cubranic** [caskroom/homebrew-cask#10150]
```
$ brew cask list
Error: wrong number of arguments (1 for 0) while loading '/usr/local/Library/Taps/caskroom/homebrew-cask/Casks/basictex.rb'
Please report this bug:
    https://github.com/caskroom/homebrew-cask/issues
<main>:6:in `name'
<main>:6:in `<class:Basictex>'
<main>:in `<main>'
/usr/local/Cellar/brew-cask/0.43.1/rubylib/cask/source/path_base.rb:55:in `eval'
/usr/local/Cellar/brew-cask/0.43.1/rubylib/cask/source/path_base.rb:55:in `rescue in load'
/usr/local/Cellar/brew-cask/0.43.1/rubylib/cask/source/path_base.rb:52:in `load'
/usr/local/Cellar/brew-cask/0.43.1/rubylib/cask.rb:120:in `load'
/usr/local/Cellar/brew-cask/0.43.1/rubylib/cask/scopes.rb:55:in `block in installed'
/usr/local/Cellar/brew-cask/0.43.1/rubylib/cask/scopes.rb:49:in `map'
/usr/local/Cellar/brew-cask/0.43.1/rubylib/cask/scopes.rb:49:in `installed'
/usr/local/Cellar/brew-cask/0.43.1/rubylib/cask/cli/list.rb:52:in `list_installed'
/usr/local/Cellar/brew-cask/0.43.1/rubylib/cask/cli/list.rb:10:in `run'
/usr/local/Cellar/brew-cask/0.43.1/rubylib/cask/cli.rb:81:in `run_command'
/usr/local/Cellar/brew-cask/0.43.1/rubylib/cask/cli.rb:121:in `process'
/usr/local/bin/brew-cask.rb:42:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:58:in `require?'
/usr/local/Library/brew.rb:141:in `<main>'
```

**Comment by phinze** [comment]
Hey there!

Good news - all you have to do is upgrade:

```
brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup
```

**Comment by phinze** [comment]
Retroactively marking this as a dup of #10224
