### ISSUE TITLE
"wrong number of arguments" when getting info on Duet Cask

### ISSUE THREAD

**Issue by peterhajas** [caskroom/homebrew-cask#10538]
Tried to get info on the Duet cask:

```
phajas ▶ brew cask info duet
Error: wrong number of arguments (1 for 0) while loading '/usr/local/Library/Taps/caskroom/homebrew-cask/Casks/duet.rb'
Please report this bug:
    https://github.com/caskroom/homebrew-cask/issues
<main>:6:in `name'
<main>:6:in `<class:Duet>'
<main>:in `<main>'
/usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/source/path_base.rb:55:in `eval'
/usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/source/path_base.rb:55:in `rescue in load'
/usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/source/path_base.rb:52:in `load'
/usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/source/tapped.rb:28:in `load'
/usr/local/Cellar/brew-cask/0.46.0/rubylib/cask.rb:124:in `load'
/usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/cli/info.rb:7:in `block in run'
/usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/cli/info.rb:5:in `each'
/usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/cli/info.rb:5:in `run'
/usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/cli.rb:81:in `run_command'
/usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/cli.rb:121:in `process'
/usr/local/bin/brew-cask.rb:42:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:58:in `require?'
/usr/local/Library/brew.rb:141:in `<main>'
```

**Comment by radeksimko** [comment]
Hi!
Please see https://github.com/caskroom/homebrew-cask/issues/10224 and reopen this issue if the problem still persists.
