### ISSUE TITLE
Pewrmission denied: symlink RStudio to Applications folder

### ISSUE THREAD

**Issue by carltonlee37** [caskroom/homebrew-cask#10865]
MAC OSX 10.10.3
Have had no luck getting RStudio to work when installed with Mac installer, so am trying homebrew cask. I know there's something wring with my permissions, but have not been able to figure out what.

```
==> Symlinking App 'RStudio.app' to '/Users/carlmckinney/Applications/RStudio.ap
Error: Permission denied - /Users/carlmckinney/Applications

  Most likely, this means you have an outdated version of homebrew-cask. Please run:

      brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup

  If this doesn’t fix the problem, please report this bug:

      https://github.com/caskroom/homebrew-cask/issues

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:245:in `mkdir'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:245:in `fu_mkdir'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:219:in `block (2 levels) in mkdir_p'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:217:in `reverse_each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:217:in `block in mkdir_p'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:203:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:203:in `mkdir_p'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:556:in `mkpath'
/usr/local/Cellar/brew-cask/0.53.3/rubylib/hbc/artifact/symlinked.rb:11:in `create_filesystem_link'
/usr/local/Cellar/brew-cask/0.53.3/rubylib/hbc/artifact/symlinked.rb:64:in `link'
/usr/local/Cellar/brew-cask/0.53.3/rubylib/hbc/artifact/symlinked.rb:87:in `block in install_phase'
/usr/local/Cellar/brew-cask/0.53.3/rubylib/hbc/artifact/symlinked.rb:87:in `each'
/usr/local/Cellar/brew-cask/0.53.3/rubylib/hbc/artifact/symlinked.rb:87:in `install_phase'
/usr/local/Cellar/brew-cask/0.53.3/rubylib/hbc/installer.rb:119:in `block in install_artifacts'
/usr/local/Cellar/brew-cask/0.53.3/rubylib/hbc/installer.rb:117:in `each'
/usr/local/Cellar/brew-cask/0.53.3/rubylib/hbc/installer.rb:117:in `install_artifacts'
/usr/local/Cellar/brew-cask/0.53.3/rubylib/hbc/installer.rb:66:in `install'
/usr/local/Cellar/brew-cask/0.53.3/rubylib/hbc/cli/install.rb:20:in `block in install_casks'
/usr/local/Cellar/brew-cask/0.53.3/rubylib/hbc/cli/install.rb:17:in `each'
/usr/local/Cellar/brew-cask/0.53.3/rubylib/hbc/cli/install.rb:17:in `install_casks'
/usr/local/Cellar/brew-cask/0.53.3/rubylib/hbc/cli/install.rb:6:in `run'
/usr/local/Cellar/brew-cask/0.53.3/rubylib/hbc/cli.rb:79:in `run_command'
/usr/local/Cellar/brew-cask/0.53.3/rubylib/hbc/cli.rb:119:in `process'
/usr/local/Cellar/brew-cask/0.53.3/rubylib/brew-cask-cmd.rb:18:in `<main>'
```

**Comment by vitorgalvao** [comment]
> Have had no luck getting RStudio to work when installed with Mac installer

That means the issue is with your particular configuration, or RStudio itself, not with us. Please try their support first.

Just to see if it isn’t an obvious problem, though, what are the outputs of

```
whoami
echo "$HOMEBREW_CASK_OPTS"
ls -l "${HOME}" | grep 'Applications'
```

Also, read [what to do before opening new issues](https://github.com/caskroom/homebrew-cask#reporting-bugs).
