### ISSUE TITLE
brew cask install microsoft-lync

### ISSUE THREAD

**Issue by kawamanza** [caskroom/homebrew-cask#11211]
```
$ brew cask install microsoft-lync
Error: wrong number of arguments (1 for 0) while loading '/usr/local/Library/Taps/caskroom/homebrew-cask/Casks/microsoft-lync.rb'
Please report this bug:
    https://github.com/caskroom/homebrew-cask/issues
<main>:5:in `name'
<main>:5:in `<class:MicrosoftLync>'
<main>:in `<main>'
/usr/local/Cellar/brew-cask/0.41.1/rubylib/cask/source/path_base.rb:55:in `eval'
/usr/local/Cellar/brew-cask/0.41.1/rubylib/cask/source/path_base.rb:55:in `rescue in load'
/usr/local/Cellar/brew-cask/0.41.1/rubylib/cask/source/path_base.rb:52:in `load'
/usr/local/Cellar/brew-cask/0.41.1/rubylib/cask/source/tapped.rb:28:in `load'
/usr/local/Cellar/brew-cask/0.41.1/rubylib/cask.rb:120:in `load'
/usr/local/Cellar/brew-cask/0.41.1/rubylib/cask/cli/install.rb:19:in `block in install_casks'
/usr/local/Cellar/brew-cask/0.41.1/rubylib/cask/cli/install.rb:17:in `each'
/usr/local/Cellar/brew-cask/0.41.1/rubylib/cask/cli/install.rb:17:in `install_casks'
/usr/local/Cellar/brew-cask/0.41.1/rubylib/cask/cli/install.rb:6:in `run'
/usr/local/Cellar/brew-cask/0.41.1/rubylib/cask/cli.rb:80:in `run_command'
/usr/local/Cellar/brew-cask/0.41.1/rubylib/cask/cli.rb:120:in `process'
/usr/local/bin/brew-cask.rb:42:in `<top (required)>'
```

**Comment by vitorgalvao** [comment]
You’re using an old version of homebrew-cask. Please `brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup` and try again.

Please [always do this before opening new issues](https://github.com/caskroom/homebrew-cask#reporting-bugs).

See also #10224.
