### ISSUE TITLE
Unexpected method 'destination_path', undefined method `join'

### ISSUE THREAD

**Issue by amavilla** [caskroom/homebrew-cask#11225]
The following warning and error are happened. Are they well-known?

```
$ brew cask install parallels9
```

```
Warning: Unexpected method 'destination_path' called during postflight on Cask parallels9.

  Most likely, this means you have an outdated version of homebrew-cask. Please run:

      brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup

  If this doesn’t fix the problem, please report this bug:

      https://github.com/caskroom/homebrew-cask/issues

Error: undefined method `join' for nil:NilClass

  Most likely, this means you have an outdated version of homebrew-cask. Please run:

      brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup

  If this doesn’t fix the problem, please report this bug:

      https://github.com/caskroom/homebrew-cask/issues

<main>:12:in `block in <class:KlassPrefixParallels9>'
/usr/local/Cellar/brew-cask/0.54.0/rubylib/hbc/artifact/postflight_block.rb:9:in `instance_eval'
/usr/local/Cellar/brew-cask/0.54.0/rubylib/hbc/artifact/postflight_block.rb:9:in `block in install_phase'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/set.rb:232:in `each_key'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/set.rb:232:in `each'
/usr/local/Cellar/brew-cask/0.54.0/rubylib/hbc/artifact/postflight_block.rb:8:in `install_phase'
/usr/local/Cellar/brew-cask/0.54.0/rubylib/hbc/installer.rb:119:in `block in install_artifacts'
/usr/local/Cellar/brew-cask/0.54.0/rubylib/hbc/installer.rb:117:in `each'
/usr/local/Cellar/brew-cask/0.54.0/rubylib/hbc/installer.rb:117:in `install_artifacts'
/usr/local/Cellar/brew-cask/0.54.0/rubylib/hbc/installer.rb:66:in `install'
/usr/local/Cellar/brew-cask/0.54.0/rubylib/hbc/cli/install.rb:20:in `block in install_casks'
/usr/local/Cellar/brew-cask/0.54.0/rubylib/hbc/cli/install.rb:17:in `each'
/usr/local/Cellar/brew-cask/0.54.0/rubylib/hbc/cli/install.rb:17:in `install_casks'
/usr/local/Cellar/brew-cask/0.54.0/rubylib/hbc/cli/install.rb:6:in `run'
/usr/local/Cellar/brew-cask/0.54.0/rubylib/hbc/cli.rb:79:in `run_command'
/usr/local/Cellar/brew-cask/0.54.0/rubylib/hbc/cli.rb:119:in `process'
/usr/local/Cellar/brew-cask/0.54.0/rubylib/brew-cask-cmd.rb:18:in `<main>
```

**Comment by vitorgalvao** [comment]
Should be fixed. Please `brew upgrade` and try again.

**Comment by amavilla** [comment]
```
brew update
brew upgrade --all
```
then fixed. Thanks, vitorgalvao!!
