### ISSUE TITLE
Installing licecap hangs

### ISSUE THREAD

**Issue by raszi** [caskroom/homebrew-cask#11651]
```
$ brew update && brew upgrade brew-cask
Already up-to-date.
Error: caskroom/cask/brew-cask 0.54.0 already installed

$ brew cleanup && brew cask cleanup
==> Removing dead symlinks
Nothing to do
==> Removing cached downloads
Nothing to do

$ brew cask install --force --verbose licecap
==> Downloading http://www.cockos.com/licecap/licecap125.dmg
/usr/bin/curl -fLA Homebrew-cask v0.51+ (Ruby 2.0.0-481) http://www.cockos.com/licecap/licecap125.dmg -C 0 -o /Library/Caches/Homebrew/licecap-1.25.dmg.incomplete
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  699k  100  699k    0     0   240k      0  0:00:02  0:00:02 --:--:--  240k
```

**Comment by vitorgalvao** [comment]
Can’t reproduce, and there’s nothing wrong with the cask. This is clearly an issue on your end.

Can you reproduce it with other casks? Do you have a custom `.curlrc`?

**Comment by raszi** [comment]
I have no curlrc and I can reproduce this error all the time. I cannot reproduce this error with Xee22 for example:

```
$ brew cask install xee22
==> Downloading https://xee.googlecode.com/files/Xee2.2.zip
######################################################################## 100.0%
==> Symlinking App 'Xee.app' to '/Users/ikaraszi/Applications/Xee.app'
🍺  xee22 staged at '/opt/homebrew-cask/Caskroom/xee22/2.2' (228 files, 11M)
```

**Comment by raszi** [comment]
Nor with firefox:

```
$ brew cask install firefox
==> Downloading https://ftp.mozilla.org/pub/firefox/releases/38.0.5/mac/en-US/Firefox%2038.0.5.dmg
######################################################################## 100.0%
==> Symlinking App 'Firefox.app' to '/Users/ikaraszi/Applications/Firefox.app'
🍺  firefox staged at '/opt/homebrew-cask/Caskroom/firefox/38.0.5' (115 files, 167M)
```

**Comment by vitorgalvao** [comment]
But you can reproduce it consistently with `licecap`? What about after `m -rf "$(brew --cache)"`?

**Comment by raszi** [comment]
Yes, same thing. :(

**Comment by raszi** [comment]
I was able to create a stack trace:

```
==> Downloading http://www.cockos.com/licecap/licecap125.dmg
/usr/bin/curl -fLA Homebrew-cask v0.51+ (Ruby 2.0.0-481) http://www.cockos.com/licecap/licecap125.dmg -C 0 -o /Library/Caches/Homebrew/licecap-1.25.dmg.incomplete
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  699k  100  699k    0     0  90246      0  0:00:07  0:00:07 --:--:--  111k
^C/usr/local/Cellar/brew-cask/0.54.0/rubylib/hbc/system_command.rb:18:in `gets': Interrupt
	from /usr/local/Cellar/brew-cask/0.54.0/rubylib/hbc/system_command.rb:18:in `run'
	from /usr/local/Cellar/brew-cask/0.54.0/rubylib/hbc/container/dmg.rb:34:in `mount!'
	from /usr/local/Cellar/brew-cask/0.54.0/rubylib/hbc/container/dmg.rb:13:in `extract'
	from /usr/local/Cellar/brew-cask/0.54.0/rubylib/hbc/installer.rb:110:in `extract_primary_container'
	from /usr/local/Cellar/brew-cask/0.54.0/rubylib/hbc/installer.rb:65:in `install'
	from /usr/local/Cellar/brew-cask/0.54.0/rubylib/hbc/cli/install.rb:20:in `block in install_casks'
	from /usr/local/Cellar/brew-cask/0.54.0/rubylib/hbc/cli/install.rb:17:in `each'
	from /usr/local/Cellar/brew-cask/0.54.0/rubylib/hbc/cli/install.rb:17:in `install_casks'
	from /usr/local/Cellar/brew-cask/0.54.0/rubylib/hbc/cli/install.rb:6:in `run'
	from /usr/local/Cellar/brew-cask/0.54.0/rubylib/hbc/cli.rb:79:in `run_command'
	from /usr/local/Cellar/brew-cask/0.54.0/rubylib/hbc/cli.rb:119:in `process'
	from /usr/local/Cellar/brew-cask/0.54.0/rubylib/brew-cask-cmd.rb:18:in `<main>'
```

**Comment by vitorgalvao** [comment]
Is this still an issue? Can you follow [these procedures](https://github.com/caskroom/homebrew-cask#reporting-bugs)?
