### ISSUE TITLE
More graceful interrupt handling

### ISSUE THREAD

**Issue by fgimian** [caskroom/homebrew-cask#12002]
Hey there folks, absolutely love cask.  I noticed that it doesn't deal so nicely with Ctrl+C (Keyboard Interrupts).

```bash
fots ⚛ fotsies-mac ~ ✗ 11:45 pm
➔ brew cask install blu-ray-player
==> Downloading http://www.macblurayplayer.com/user/download/Mac_Bluray_Player.dmg
                                                                           0.9%^C/usr/local/Cellar/brew-cask/0.54.1/rubylib/vendor/homebrew-fork/utils.rb:12:in `wait': Interrupt
  from /usr/local/Cellar/brew-cask/0.54.1/rubylib/vendor/homebrew-fork/utils.rb:12:in `homebrew_fork_system'
  from /usr/local/Cellar/brew-cask/0.54.1/rubylib/vendor/homebrew-fork/utils.rb:18:in `safe_system'
  from /usr/local/Cellar/brew-cask/0.54.1/rubylib/vendor/homebrew-fork/utils.rb:44:in `curl'
  from /usr/local/Cellar/brew-cask/0.54.1/rubylib/vendor/homebrew-fork/download_strategy.rb:100:in `curl'
  from /usr/local/Cellar/brew-cask/0.54.1/rubylib/hbc/download_strategy.rb:36:in `_fetch'
  from /usr/local/Cellar/brew-cask/0.54.1/rubylib/vendor/homebrew-fork/download_strategy.rb:65:in `fetch'
  from /usr/local/Cellar/brew-cask/0.54.1/rubylib/hbc/download_strategy.rb:40:in `fetch'
  from /usr/local/Cellar/brew-cask/0.54.1/rubylib/hbc/download.rb:23:in `perform'
  from /usr/local/Cellar/brew-cask/0.54.1/rubylib/hbc/installer.rb:89:in `download'
  from /usr/local/Cellar/brew-cask/0.54.1/rubylib/hbc/installer.rb:63:in `install'
  from /usr/local/Cellar/brew-cask/0.54.1/rubylib/hbc/cli/install.rb:20:in `block in install_casks'
  from /usr/local/Cellar/brew-cask/0.54.1/rubylib/hbc/cli/install.rb:17:in `each'
  from /usr/local/Cellar/brew-cask/0.54.1/rubylib/hbc/cli/install.rb:17:in `install_casks'
  from /usr/local/Cellar/brew-cask/0.54.1/rubylib/hbc/cli/install.rb:6:in `run'
  from /usr/local/Cellar/brew-cask/0.54.1/rubylib/hbc/cli.rb:79:in `run_command'
  from /usr/local/Cellar/brew-cask/0.54.1/rubylib/hbc/cli.rb:119:in `process'
  from /usr/local/Cellar/brew-cask/0.54.1/rubylib/brew-cask-cmd.rb:18:in `<main>'
```

Perhaps this may be worth checking out.  The main brew install command doesn't seem to suffer this problem.

Cheers
Fotis

**Comment by pynixwang** [comment]
no one care?

**Comment by vitorgalvao** [comment]
@pynixwang We’re all volunteers and the projects itself has other priorities. You’re welcome to submit a PR.

**Comment by pynixwang** [comment]
@vitorgalvao I will try.

**Comment by vitorgalvao** [comment]
Closed in favour of https://github.com/caskroom/homebrew-cask/pull/13567.
