### ISSUE TITLE
Error: wrong number of arguments (1 for 0) when listing casks

### ISSUE THREAD

**Issue by simaofreitas** [caskroom/homebrew-cask#12603]
Hi,

When trying to run `brew cask list` I get the following error:

```
Error: wrong number of arguments (1 for 0) while loading '/usr/local/Library/Taps/caskroom/homebrew-cask/Casks/dash.rb'
Please report this bug:
    https://github.com/caskroom/homebrew-cask/issues
<main>:6:in `name'
<main>:6:in `<class:Dash>'
<main>:in `<main>'
/usr/local/Cellar/brew-cask/HEAD/rubylib/cask/source/path_base.rb:55:in `eval'
/usr/local/Cellar/brew-cask/HEAD/rubylib/cask/source/path_base.rb:55:in `rescue in load'
/usr/local/Cellar/brew-cask/HEAD/rubylib/cask/source/path_base.rb:52:in `load'
/usr/local/Cellar/brew-cask/HEAD/rubylib/cask.rb:124:in `load'
/usr/local/Cellar/brew-cask/HEAD/rubylib/cask/scopes.rb:55:in `block in installed'
/usr/local/Cellar/brew-cask/HEAD/rubylib/cask/scopes.rb:49:in `map'
/usr/local/Cellar/brew-cask/HEAD/rubylib/cask/scopes.rb:49:in `installed'
/usr/local/Cellar/brew-cask/HEAD/rubylib/cask/cli/list.rb:52:in `list_installed'
/usr/local/Cellar/brew-cask/HEAD/rubylib/cask/cli/list.rb:10:in `run'
/usr/local/Cellar/brew-cask/HEAD/rubylib/cask/cli.rb:81:in `run_command'
/usr/local/Cellar/brew-cask/HEAD/rubylib/cask/cli.rb:121:in `process'
/usr/local/bin/brew-cask.rb:42:in `<top (required)>'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/Library/brew.rb:58:in `require?'
/usr/local/Library/brew.rb:130:in `<main>'
```

With `--verbose`
```
brew cask list --verbose                                                                                               
Error: No available Cask for --verbose
Kernel.exit
```

Running `brew cask uninstall dash` hangs and doesn't do anything.

Tried to remove the file `dash.rb` but then I just get the same error but for another file (dropbox.rb, firefox.rb and so on)

Output for trying to update/doctor:

```
/u/l/L/T/c/h/Casks git:master ❯❯❯ brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup
Already up-to-date.
Error: caskroom/cask/brew-cask HEAD already installed
```

`brew cask doctor` output:

```
==> OS X Version:
10.10.4
==> Hardware Architecture:
intel-64
==> Ruby Version:
2.0.0-p481
==> Ruby Path:
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
==> Homebrew Version:
0.9.5
==> Homebrew Executable Path:
/usr/local/bin/brew
==> Homebrew Cellar Path:
/usr/local/Cellar
==> Homebrew Repository Path:
/usr/local
==> Homebrew Origin:
https://github.com/Homebrew/homebrew
==> Homebrew-cask Version:
0.46.0
==> Homebrew-cask Install Location:
/usr/local/Cellar/brew-cask/HEAD (error: old version. Run "brew cleanup".)
==> Homebrew-cask Staging Location:
/opt/homebrew-cask/Caskroom
==> Homebrew-cask Cached Downloads:
/Library/Caches/Homebrew
/Library/Caches/Homebrew/Casks
0 files
0.00 megs
==> Homebrew-cask Default Tap Path:
/usr/local/Library/Taps/caskroom/homebrew-cask
==> Homebrew-cask Alternate Cask Taps:
/usr/local/Library/Taps/caskroom/homebrew-fonts
/usr/local/Library/Taps/caskroom/homebrew-versions
==> Homebrew-cask Default Tap Cask Count:
2628
==> Contents of $LOAD_PATH:
/usr/local/Cellar/brew-cask/HEAD/rubylib
/usr/local/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin14
/Library/Ruby/Site/2.0.0/universal-darwin14
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin14
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin14
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin14
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin14
==> Contents of $RUBYLIB Environment Variable:
<NONE>
==> Contents of $RUBYOPT Environment Variable:
<NONE>
==> Contents of $RUBYPATH Environment Variable:
<NONE>
==> Contents of $RBENV_VERSION Environment Variable:
<NONE>
==> Contents of $CHRUBY_VERSION Environment Variable:
<NONE>
==> Contents of $GEM_HOME Environment Variable:
<NONE>
==> Contents of $GEM_PATH Environment Variable:
<NONE>
==> Contents of $BUNDLE_PATH Environment Variable:
<NONE>
==> Contents of $PATH Environment Variable:
PATH="/Users/simaofreitas/.rbenv/shims:/usr/local/bin:/usr/local/sbin:.git/safe/../../bin:/Users/simaofreitas/.bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Users/simaofreitas/go/bin:/usr/local/Library/ENV/scm"
==> Contents of $SHELL Environment Variable:
SHELL="/bin/zsh"
==> Contents of Locale Environment Variables:
LANG="en_US.UTF-8"
LC_CTYPE="UTF-8"
==> Running As Privileged User:
No
```

I also ran `brew cleanup` as reported by the doctor command. Output:

```
Warning: Skipping git: most recent version 2.4.5 not installed
```

Anyone with the same problem? Thanks

**Comment by vitorgalvao** [comment]
[Reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs).

**Comment by simaofreitas** [comment]
I updated the card with all the output according to the link provided. My bad.

**Comment by vitorgalvao** [comment]
```
==> Homebrew-cask Version:
0.46.0
```

You’re using an old version of homebrew-cask. Please `brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup` and try again.

Please [always do this before opening new issues](https://github.com/caskroom/homebrew-cask#reporting-bugs).

See also #10224.

**Comment by simaofreitas** [comment]
@vitorgalvao I did that. The output is in the description.

**Comment by vitorgalvao** [comment]
See my comment (I updated it right after posting).

**Comment by vitorgalvao** [comment]
The issue seems t stem from the fact you installed the HEAD version (which you shouldn’t have).
