### ISSUE TITLE
Error installing cask for VirtualBox 

### ISSUE THREAD

**Issue by gudstrand** [caskroom/homebrew-cask#13076]
Output is below, tried recommended fixes and still get the same error.

$ brew cask install virtualbox
==> Downloading http://download.virtualbox.org/virtualbox/5.0.0/VirtualBox-5.0.0-101573-OSX.dm
Already downloaded: /Library/Caches/Homebrew/virtualbox-5.0.0-101573.dmg
Error: Permission denied - /etc/Caskroom/virtualbox

  Most likely, this means you have an outdated version of homebrew-cask. Please run:

      brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup

  If this doesn’t fix the problem, please report this bug:

      https://github.com/caskroom/homebrew-cask/issues

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:245:in `mkdir'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:245:in `fu_mkdir'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:219:in `block (2 levels) in mkdir_p'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:217:in `reverse_each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:217:in `block in mkdir_p'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:203:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:203:in `mkdir_p'
/usr/local/Cellar/brew-cask/0.56.0/rubylib/hbc/installer.rb:100:in `extract_primary_container'
/usr/local/Cellar/brew-cask/0.56.0/rubylib/hbc/installer.rb:65:in `install'
/usr/local/Cellar/brew-cask/0.56.0/rubylib/hbc/cli/install.rb:20:in `block in install_casks'
/usr/local/Cellar/brew-cask/0.56.0/rubylib/hbc/cli/install.rb:17:in `each'
/usr/local/Cellar/brew-cask/0.56.0/rubylib/hbc/cli/install.rb:17:in `install_casks'
/usr/local/Cellar/brew-cask/0.56.0/rubylib/hbc/cli/install.rb:6:in `run'
/usr/local/Cellar/brew-cask/0.56.0/rubylib/hbc/cli.rb:79:in `run_command'
/usr/local/Cellar/brew-cask/0.56.0/rubylib/hbc/cli.rb:119:in `process'
/usr/local/Cellar/brew-cask/0.56.0/rubylib/brew-cask-cmd.rb:18:in `<main>'

**Comment by gudstrand** [comment]
Clue was in the ouput :+1: 
Error: Permission denied - /etc/Caskroom/virtualbox

Not sure how the Caskroom came to be set to /etc/ but I changed it to /opt/brew-cask/Caskroom and installed just fine.
