### ISSUE TITLE
Error: Execution of 'brew cask install atom --appdir=/Applications' returned 1

### ISSUE THREAD

**Issue by charleshbaker** [caskroom/homebrew-cask#13315]
This error happens when trying to install atom via boxen which in turn calls brew cask. Can I provide any further information?
```
Error: Execution of 'brew cask install atom --appdir=/Applications' returned 1: ==> Satisfying dependencies
complete
==> Downloading https://github.com/atom/atom/releases/download/v1.0.7/atom-mac.zip
Already downloaded: /Library/Caches/Homebrew/atom-1.0.7.zip
==> Symlinking App 'Atom.app' to '/Applications/Atom.app'
Error: Permission denied - /usr/local/bin
==> Symlinking Binary 'apm' to '/usr/local/bin/apm'

  Most likely, this means you have an outdated version of homebrew-cask. Please run:

      brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup

  If this doesn’t fix the problem, please report this bug:

      https://github.com/caskroom/homebrew-cask/issues

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:245:in `mkdir'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:245:in `fu_mkdir'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:219:in `block (2 levels) in mkdir_p'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:217:in `reverse_each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:217:in `block in mkdir_p'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:203:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:203:in `mkdir_p'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:556:in `mkpath'
/opt/boxen/homebrew/Cellar/brew-cask/0.56.0/rubylib/hbc/artifact/symlinked.rb:11:in `create_filesystem_link'
/opt/boxen/homebrew/Cellar/brew-cask/0.56.0/rubylib/hbc/artifact/symlinked.rb:68:in `link'
/opt/boxen/homebrew/Cellar/brew-cask/0.56.0/rubylib/hbc/artifact/symlinked.rb:91:in `block in install_phase'
/opt/boxen/homebrew/Cellar/brew-cask/0.56.0/rubylib/hbc/artifact/symlinked.rb:91:in `each'
/opt/boxen/homebrew/Cellar/brew-cask/0.56.0/rubylib/hbc/artifact/symlinked.rb:91:in `install_phase'
/opt/boxen/homebrew/Cellar/brew-cask/0.56.0/rubylib/hbc/artifact/binary.rb:3:in `install_phase'
/opt/boxen/homebrew/Cellar/brew-cask/0.56.0/rubylib/hbc/installer.rb:119:in `block in install_artifacts'
/opt/boxen/homebrew/Cellar/brew-cask/0.56.0/rubylib/hbc/installer.rb:117:in `each'
/opt/boxen/homebrew/Cellar/brew-cask/0.56.0/rubylib/hbc/installer.rb:117:in `install_artifacts'
/opt/boxen/homebrew/Cellar/brew-cask/0.56.0/rubylib/hbc/installer.rb:66:in `install'
/opt/boxen/homebrew/Cellar/brew-cask/0.56.0/rubylib/hbc/cli/install.rb:20:in `block in install_casks'
/opt/boxen/homebrew/Cellar/brew-cask/0.56.0/rubylib/hbc/cli/install.rb:17:in `each'
/opt/boxen/homebrew/Cellar/brew-cask/0.56.0/rubylib/hbc/cli/install.rb:17:in `install_casks'
/opt/boxen/homebrew/Cellar/brew-cask/0.56.0/rubylib/hbc/cli/install.rb:6:in `run'
/opt/boxen/homebrew/Cellar/brew-cask/0.56.0/rubylib/hbc/cli.rb:79:in `run_command'
/opt/boxen/homebrew/Cellar/brew-cask/0.56.0/rubylib/hbc/cli.rb:119:in `process'
/opt/boxen/homebrew/Cellar/brew-cask/0.56.0/rubylib/brew-cask-cmd.rb:18:in `<main>'
Error: /Stage[main]/Atom/Package[atom]/ensure: change from absent to present failed: Execution of 'brew cask install atom --appdir=/Applications' returned 1: ==> Satisfying dependencies
complete
==> Downloading https://github.com/atom/atom/releases/download/v1.0.7/atom-mac.zip
Already downloaded: /Library/Caches/Homebrew/atom-1.0.7.zip
==> Symlinking App 'Atom.app' to '/Applications/Atom.app'
Error: Permission denied - /usr/local/bin
==> Symlinking Binary 'apm' to '/usr/local/bin/apm'

  Most likely, this means you have an outdated version of homebrew-cask. Please run:

      brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup

  If this doesn’t fix the problem, please report this bug:

      https://github.com/caskroom/homebrew-cask/issues

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:245:in `mkdir'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:245:in `fu_mkdir'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:219:in `block (2 levels) in mkdir_p'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:217:in `reverse_each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:217:in `block in mkdir_p'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:203:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:203:in `mkdir_p'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:556:in `mkpath'
/opt/boxen/homebrew/Cellar/brew-cask/0.56.0/rubylib/hbc/artifact/symlinked.rb:11:in `create_filesystem_link'
/opt/boxen/homebrew/Cellar/brew-cask/0.56.0/rubylib/hbc/artifact/symlinked.rb:68:in `link'
/opt/boxen/homebrew/Cellar/brew-cask/0.56.0/rubylib/hbc/artifact/symlinked.rb:91:in `block in install_phase'
/opt/boxen/homebrew/Cellar/brew-cask/0.56.0/rubylib/hbc/artifact/symlinked.rb:91:in `each'
/opt/boxen/homebrew/Cellar/brew-cask/0.56.0/rubylib/hbc/artifact/symlinked.rb:91:in `install_phase'
/opt/boxen/homebrew/Cellar/brew-cask/0.56.0/rubylib/hbc/artifact/binary.rb:3:in `install_phase'
/opt/boxen/homebrew/Cellar/brew-cask/0.56.0/rubylib/hbc/installer.rb:119:in `block in install_artifacts'
/opt/boxen/homebrew/Cellar/brew-cask/0.56.0/rubylib/hbc/installer.rb:117:in `each'
/opt/boxen/homebrew/Cellar/brew-cask/0.56.0/rubylib/hbc/installer.rb:117:in `install_artifacts'
/opt/boxen/homebrew/Cellar/brew-cask/0.56.0/rubylib/hbc/installer.rb:66:in `install'
/opt/boxen/homebrew/Cellar/brew-cask/0.56.0/rubylib/hbc/cli/install.rb:20:in `block in install_casks'
/opt/boxen/homebrew/Cellar/brew-cask/0.56.0/rubylib/hbc/cli/install.rb:17:in `each'
/opt/boxen/homebrew/Cellar/brew-cask/0.56.0/rubylib/hbc/cli/install.rb:17:in `install_casks'
/opt/boxen/homebrew/Cellar/brew-cask/0.56.0/rubylib/hbc/cli/install.rb:6:in `run'
/opt/boxen/homebrew/Cellar/brew-cask/0.56.0/rubylib/hbc/cli.rb:79:in `run_command'
/opt/boxen/homebrew/Cellar/brew-cask/0.56.0/rubylib/hbc/cli.rb:119:in `process'
/opt/boxen/homebrew/Cellar/brew-cask/0.56.0/rubylib/brew-cask-cmd.rb:18:in `<main>'
```

**Comment by charleshbaker** [comment]
There was no /usr/local/bin directory in my Yosemite install. I created it with sudo. It is owned by root:wheel. I added myself to the wheel group. Logged out and back in and now I get:

```
Error: Execution of 'brew cask install atom --appdir=/Applications' returned 1: ==> Satisfying dependencies
complete
==> Downloading https://github.com/atom/atom/releases/download/v1.0.7/atom-mac.zip
Already downloaded: /Library/Caches/Homebrew/atom-1.0.7.zip
==> Symlinking App 'Atom.app' to '/Applications/Atom.app'
==> Symlinking Binary 'apm' to '/usr/local/bin/apm'
Error: Command failed to execute!

==> Failed command:
["/bin/ln", "-hfs", "--", "#<Pathname:/opt/homebrew-cask/Caskroom/atom/1.0.7/Atom.app/Contents/Resources/app/apm/node_modules/.bin/apm>", "#<Pathname:/usr/local/bin/apm>"]

==> Output of failed command:


==> Exit status of failed command:
#<Process::Status: pid 55725 exit 1>
==> ln: /usr/local/bin/apm: Permission denied
Error: /Stage[main]/Atom/Package[atom]/ensure: change from absent to present failed: Execution of 'brew cask install atom --appdir=/Applications' returned 1: ==> Satisfying dependencies
complete
==> Downloading https://github.com/atom/atom/releases/download/v1.0.7/atom-mac.zip
Already downloaded: /Library/Caches/Homebrew/atom-1.0.7.zip
==> Symlinking App 'Atom.app' to '/Applications/Atom.app'
==> Symlinking Binary 'apm' to '/usr/local/bin/apm'
Error: Command failed to execute!

==> Failed command:
["/bin/ln", "-hfs", "--", "#<Pathname:/opt/homebrew-cask/Caskroom/atom/1.0.7/Atom.app/Contents/Resources/app/apm/node_modules/.bin/apm>", "#<Pathname:/usr/local/bin/apm>"]

==> Output of failed command:


==> Exit status of failed command:
#<Process::Status: pid 55725 exit 1>
==> ln: /usr/local/bin/apm: Permission denied
```

**Comment by Ngrd** [comment]
It's still a permissions issue. Try running:
```bash
sudo chown -R $(whoami) /usr/local/bin
```
and then try installation again.

**Comment by charleshbaker** [comment]
Yeah, I didn't really add myself to wheel. I edited /etc/group. I forget sometimes how different Mac OS X is from traditional UNIX or even linux. I had to do 
```
sudo dseditgroup -o edit -a usernametoadd -t user wheel
```
