### ISSUE TITLE
Error installing casks that print EULA during dmg mounting: invalid byte sequence in UTF-8

### ISSUE THREAD

**Issue by zmwangx** [caskroom/homebrew-cask#13402]
**Update.** The problem isn't really a problem of non-ASCII artifacts. Rather, it's the problem of EULA being printed during mounting. See https://github.com/caskroom/homebrew-cask/issues/13402#issuecomment-136195788 for diagnostics.

---

I've always had the same issue as #7303, but the issue (being old) was closed last month, so I'm opening a new one. The error occurs to me whenever there are paths containing non-ASCII characters, e.g., with `baiducloud`, `sogouinput`, etc.

Curiously, whenever I install the same problematic cask twice in succession, the first attempt will fail with "invalid byte sequence in UTF-8", but the second attempt will succeed. Debug output is given below.

Note that the only relevant locale bit in my env is `LC_ALL=en_US.UTF-8`, but it doesn't really matter. I can unset `LC_ALL` and still reproduce the exact same issue. And I can reproduce on vanilla installs of OS X 10.9 (if memory serves, this one has been a while), 10.10, and 10.11.

```
> brew cask install --debug baiducloud
==> Creating directories
==> Loading Cask definitions
==> Translating 'baiducloud' into a valid Cask source
==> Testing source class Hbc::Source::URI
==> Testing source class Hbc::Source::PathSlashRequired
==> Testing source class Hbc::Source::TappedQualified
==> Testing source class Hbc::Source::UntappedQualified
==> Testing source class Hbc::Source::Tapped
==> Success! Using source class Hbc::Source::Tapped
==> Resolved Cask URI or file source to '/usr/local/Library/Taps/caskroom/homebrew-cask/Casks/baiducloud.rb'
==> Cask instance dumps in YAML:
==> Cask instance toplevel:
--- !ruby/object:KlassPrefixBaiducloud
sourcefile_path: !ruby/object:Pathname
  path: /usr/local/Library/Taps/caskroom/homebrew-cask/Casks/baiducloud.rb
token: baiducloud
==> Cask instance method 'name':

---
- 百度云同步盘
- Baidu Yun Tong Bu Pan
- Baigu Cloud
==> Cask instance method 'homepage':
--- http://pan.baidu.com
...
==> Cask instance method 'url':
--- !ruby/object:Hbc::URL
uri: !ruby/object:URI::HTTP
  scheme: http
  user: 
  password: 
  host: bcscdn.baidu.com
  port: 80
  path: /netdisk/BaiduYun_2.4.4.dmg
  query: 
  opaque: 
  registry: 
  fragment: 
  parser: 
user_agent: 
cookies: 
referer: 
using: 
revision: 
trust_cert: 
data: 
==> Cask instance method 'appcast':
--- 
...
==> Cask instance method 'version':
--- 2.4.4
...
==> Cask instance method 'license':
--- !ruby/object:Hbc::DSL::License
value: :gratis
==> Cask instance method 'tags':
--- 
...
==> Cask instance method 'sha256':
--- 0a1a438f9ab69d67f0d53d585f0a8c5db7fdbb84ab0c0df55fc06068a67b8149
...
==> Cask instance method 'artifacts':

---
:app: !ruby/object:Set
  hash:
    ? - 百度云同步盘.app
    : true
:uninstall: !ruby/object:Set
  hash:
    ? :quit: com.baidu.netdiskmac
    : true
:zap: !ruby/object:Set
  hash:
    ? :delete:
      - ~/Library/Application Support/百度云同步盘
      - ~/Library/Preferences/com.baidu.netdiskmac.plist
      - ~/Library/Caches/com.baidu.netdiskmac
    : true
==> Cask instance method 'caveats':
--- []
==> Cask instance method 'depends_on':
--- 
...
==> Cask instance method 'conflicts_with':
--- 
...
==> Cask instance method 'container':
--- 
...
==> Cask instance method 'gpg':
--- 
...
==> Cask instance method 'accessibility_access':
--- 
...
==> Hbc::Installer.install
==> Printing caveats
==> Downloading
==> Downloading http://bcscdn.baidu.com/netdisk/BaiduYun_2.4.4.dmg
Already downloaded: /Library/Caches/Homebrew/baiducloud-2.4.4.dmg
==> SHA256 checksums match
==> Downloaded to -> /Library/Caches/Homebrew/baiducloud-2.4.4.dmg
==> SHA256 checksums match
==> Extracting primary container
==> Determining which containers to use based on filetype
==> Checking container class Hbc::Container::Pkg
==> Checking container class Hbc::Container::Ttf
==> Checking container class Hbc::Container::Otf
==> Checking container class Hbc::Container::Air
==> Checking container class Hbc::Container::Cab
==> Executing: ["/usr/bin/file", "-Izb", "--", "#<Pathname:/Library/Caches/Homebrew/baiducloud-2.4.4.dmg>"]
==> Checking container class Hbc::Container::Dmg
==> Executing: ["/usr/bin/hdiutil", "imageinfo", "#<Pathname:/Library/Caches/Homebrew/baiducloud-2.4.4.dmg>"]
==> Using container class Hbc::Container::Dmg for /Library/Caches/Homebrew/baiducloud-2.4.4.dmg
==> Executing: ["/usr/bin/hdiutil", "mount", "-plist", "-nobrowse", "-readonly", "-noidme", "-mountrandom", "/tmp", "#<Pathname:/Library/Caches/Homebrew/baiducloud-2.4.4.dmg>"]
==> Purging files for version 2.4.4 of Cask baiducloud
Error: invalid byte sequence in UTF-8

  Most likely, this means you have an outdated version of homebrew-cask. Please run:

      brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup

  If this doesn’t fix the problem, please report this bug:

      https://github.com/caskroom/homebrew-cask/issues

/usr/local/Cellar/brew-cask/0.56.0/rubylib/hbc/system_command.rb:98:in `_parse_plist'
/usr/local/Cellar/brew-cask/0.56.0/rubylib/hbc/system_command.rb:73:in `plist'
/usr/local/Cellar/brew-cask/0.56.0/rubylib/hbc/container/dmg.rb:38:in `mount!'
/usr/local/Cellar/brew-cask/0.56.0/rubylib/hbc/container/dmg.rb:13:in `extract'
/usr/local/Cellar/brew-cask/0.56.0/rubylib/hbc/installer.rb:110:in `extract_primary_container'
/usr/local/Cellar/brew-cask/0.56.0/rubylib/hbc/installer.rb:65:in `install'
/usr/local/Cellar/brew-cask/0.56.0/rubylib/hbc/cli/install.rb:20:in `block in install_casks'
/usr/local/Cellar/brew-cask/0.56.0/rubylib/hbc/cli/install.rb:17:in `each'
/usr/local/Cellar/brew-cask/0.56.0/rubylib/hbc/cli/install.rb:17:in `install_casks'
/usr/local/Cellar/brew-cask/0.56.0/rubylib/hbc/cli/install.rb:6:in `run'
/usr/local/Cellar/brew-cask/0.56.0/rubylib/hbc/cli.rb:79:in `run_command'
/usr/local/Cellar/brew-cask/0.56.0/rubylib/hbc/cli.rb:119:in `process'
/usr/local/Cellar/brew-cask/0.56.0/rubylib/brew-cask-cmd.rb:18:in `<main>'
```

Second try:

```
> brew cask install --debug baiducloud
==> Creating directories
==> Loading Cask definitions
==> Translating 'baiducloud' into a valid Cask source
==> Testing source class Hbc::Source::URI
==> Testing source class Hbc::Source::PathSlashRequired
==> Testing source class Hbc::Source::TappedQualified
==> Testing source class Hbc::Source::UntappedQualified
==> Testing source class Hbc::Source::Tapped
==> Success! Using source class Hbc::Source::Tapped
==> Resolved Cask URI or file source to '/usr/local/Library/Taps/caskroom/homebrew-cask/Casks/baiducloud.rb'
==> Cask instance dumps in YAML:
==> Cask instance toplevel:
--- !ruby/object:KlassPrefixBaiducloud
sourcefile_path: !ruby/object:Pathname
  path: /usr/local/Library/Taps/caskroom/homebrew-cask/Casks/baiducloud.rb
token: baiducloud
==> Cask instance method 'name':

---
- 百度云同步盘
- Baidu Yun Tong Bu Pan
- Baigu Cloud
==> Cask instance method 'homepage':
--- http://pan.baidu.com
...
==> Cask instance method 'url':
--- !ruby/object:Hbc::URL
uri: !ruby/object:URI::HTTP
  scheme: http
  user: 
  password: 
  host: bcscdn.baidu.com
  port: 80
  path: /netdisk/BaiduYun_2.4.4.dmg
  query: 
  opaque: 
  registry: 
  fragment: 
  parser: 
user_agent: 
cookies: 
referer: 
using: 
revision: 
trust_cert: 
data: 
==> Cask instance method 'appcast':
--- 
...
==> Cask instance method 'version':
--- 2.4.4
...
==> Cask instance method 'license':
--- !ruby/object:Hbc::DSL::License
value: :gratis
==> Cask instance method 'tags':
--- 
...
==> Cask instance method 'sha256':
--- 0a1a438f9ab69d67f0d53d585f0a8c5db7fdbb84ab0c0df55fc06068a67b8149
...
==> Cask instance method 'artifacts':

---
:app: !ruby/object:Set
  hash:
    ? - 百度云同步盘.app
    : true
:uninstall: !ruby/object:Set
  hash:
    ? :quit: com.baidu.netdiskmac
    : true
:zap: !ruby/object:Set
  hash:
    ? :delete:
      - ~/Library/Application Support/百度云同步盘
      - ~/Library/Preferences/com.baidu.netdiskmac.plist
      - ~/Library/Caches/com.baidu.netdiskmac
    : true
==> Cask instance method 'caveats':
--- []
==> Cask instance method 'depends_on':
--- 
...
==> Cask instance method 'conflicts_with':
--- 
...
==> Cask instance method 'container':
--- 
...
==> Cask instance method 'gpg':
--- 
...
==> Cask instance method 'accessibility_access':
--- 
...
==> Hbc::Installer.install
==> Printing caveats
==> Downloading
==> Downloading http://bcscdn.baidu.com/netdisk/BaiduYun_2.4.4.dmg
Already downloaded: /Library/Caches/Homebrew/baiducloud-2.4.4.dmg
==> SHA256 checksums match
==> Downloaded to -> /Library/Caches/Homebrew/baiducloud-2.4.4.dmg
==> SHA256 checksums match
==> Extracting primary container
==> Determining which containers to use based on filetype
==> Checking container class Hbc::Container::Pkg
==> Checking container class Hbc::Container::Ttf
==> Checking container class Hbc::Container::Otf
==> Checking container class Hbc::Container::Air
==> Checking container class Hbc::Container::Cab
==> Executing: ["/usr/bin/file", "-Izb", "--", "#<Pathname:/Library/Caches/Homebrew/baiducloud-2.4.4.dmg>"]
==> Checking container class Hbc::Container::Dmg
==> Executing: ["/usr/bin/hdiutil", "imageinfo", "#<Pathname:/Library/Caches/Homebrew/baiducloud-2.4.4.dmg>"]
==> Using container class Hbc::Container::Dmg for /Library/Caches/Homebrew/baiducloud-2.4.4.dmg
==> Executing: ["/usr/bin/hdiutil", "mount", "-plist", "-nobrowse", "-readonly", "-noidme", "-mountrandom", "/tmp", "#<Pathname:/Library/Caches/Homebrew/baiducloud-2.4.4.dmg>"]
==> Executing: ["/usr/bin/ditto", "--", "/private/tmp/dmg.8goCsO", "#<Pathname:/opt/homebrew-cask/Caskroom/baiducloud/2.4.4>"]
==> Executing: ["/usr/sbin/diskutil", "eject", "#<Pathname:/private/tmp/dmg.8goCsO>"]
==> Installing artifacts
==> Determining which artifacts are present in Cask baiducloud
==> Checking for artifact class Hbc::Artifact::PreflightBlock
==> Checking for artifact class Hbc::Artifact::NestedContainer
==> Checking for artifact class Hbc::Artifact::Installer
==> Checking for artifact class Hbc::Artifact::App
==> Checking for artifact class Hbc::Artifact::Suite
==> Checking for artifact class Hbc::Artifact::Artifact
==> Checking for artifact class Hbc::Artifact::Colorpicker
==> Checking for artifact class Hbc::Artifact::Pkg
==> Checking for artifact class Hbc::Artifact::Prefpane
==> Checking for artifact class Hbc::Artifact::Qlplugin
==> Checking for artifact class Hbc::Artifact::Font
==> Checking for artifact class Hbc::Artifact::Service
==> Checking for artifact class Hbc::Artifact::StageOnly
==> Checking for artifact class Hbc::Artifact::Binary
==> Checking for artifact class Hbc::Artifact::InputMethod
==> Checking for artifact class Hbc::Artifact::InternetPlugin
==> Checking for artifact class Hbc::Artifact::ScreenSaver
==> Checking for artifact class Hbc::Artifact::Uninstall
==> Checking for artifact class Hbc::Artifact::PostflightBlock
==> Checking for artifact class Hbc::Artifact::Zap
==> 3 artifact/s defined
Hbc::Artifact::App
Hbc::Artifact::Uninstall
Hbc::Artifact::Zap
==> Installing artifact of class Hbc::Artifact::App
==> Symlinking App '百度云同步盘.app' to '/Applications/百度云同步盘.app'
==> Executing: ["/bin/ln", "-hfs", "--", "#<Pathname:/opt/homebrew-cask/Caskroom/baiducloud/2.4.4/百度云同步盘.app>", "#<Pathname:/Applications/百度云同步盘.app>"]
==> Installing artifact of class Hbc::Artifact::Uninstall
==> Nothing to do. The uninstall artifact has no install phase.
==> Installing artifact of class Hbc::Artifact::Zap
==> Nothing to do. The zap artifact has no install phase.
==> Creating metadata directory /opt/homebrew-cask/Caskroom/baiducloud/.metadata/2.4.4/20150824053746.549
==> Creating metadata subdirectory /opt/homebrew-cask/Caskroom/baiducloud/.metadata/2.4.4/20150824053746.549/Casks
==> Executing: ["/usr/bin/find", "#<Pathname:/opt/homebrew-cask/Caskroom/baiducloud/2.4.4>", "-type", "f", "-not", "-name", ".DS_Store", "-print0"]
==> Executing: ["/usr/bin/du", "-hs", "--", "#<Pathname:/opt/homebrew-cask/Caskroom/baiducloud/2.4.4>"]
🍺  baiducloud staged at '/opt/homebrew-cask/Caskroom/baiducloud/2.4.4' (118 files, 7.5M)
```

---

Update: `brew doctor` and `brew cask doctor` output: https://gist.github.com/zmwangx/c5605892a4f990bf37f9.

**Comment by Ngrd** [comment]
This is actually quite interesting. I don't get any errors when trying to install the same casks even on the first attempt. Does anybody else have the same problem? It's definitely a bug in my opinion, but I'm not sure yet.

**Comment by vitorgalvao** [comment]
@zmwangx Please update your top post with the outputs of `brew doctor` and `brew cask doctor`.

**Comment by vitorgalvao** [comment]
I also cannot reproduce, even with clean VMs. @zmwangx Please update your top post with the outputs of `brew doctor` and `brew cask doctor`, and report back. It looks like we may not be able to fix, this, though.

**Comment by zmwangx** [comment]
@vitorgalvao Updated. Gist: https://gist.github.com/zmwangx/c5605892a4f990bf37f9.

> I also cannot reproduce, even with clean VMs.

That's really weird. I'll try to spin up a clean VM, install nothing other than Homebrew and Homebrew-Cask base system, and see if I still have the same problem in a couple of days.

**Comment by zmwangx** [comment]
Okay, actually I think I might have tracked down the issue. The problem turns out to be due to license agreement printed during mounting the disk image.

Simply try

```
/usr/bin/hdiutil mount -plist -nobrowse -readonly -noidme -mountrandom /tmp /Library/Caches/Homebrew/baiducloud-2.4.4.dmg
```

when the disk image is detached (use `hdiutil detach <identifier>` if already attached), and you'll be greeted with an interactive prompt for license agreement:

```
本协议系由北京百度网讯科技有限公司及其关联<E5>
<85><AC>司（以下简称“百度”）与所有使用百度云服务的主体（<E5><8C>
<85>括但不限于个人、团队等）（以下简称“用户”）对百度云服务的使用及相<E5>
... (a million lines omitted)
Agree Y/N?
```

And unfortunately the license agreement is also printed to stdout as is with the plist output, muddling everything.

What I don't get is: why only I (along with some others in #7303) get the license agreement?

---

How I discovered the issue:

I simply dropped some debug printings to `hbc/system_command.rb`, specifically

```diff
diff --git a/lib/hbc/system_command.rb b/lib/hbc/system_command.rb
index edd0346..238eec2 100644
--- a/lib/hbc/system_command.rb
+++ b/lib/hbc/system_command.rb
@@ -70,6 +70,8 @@ class Hbc::SystemCommand::Result
   end

   def plist
+    puts @command.join(" ")
+    puts @stdout.dup
     @plist ||= self.class._parse_plist(@command, @stdout.dup)
   end
```

Here's the output on the first run: https://gist.github.com/zmwangx/e99395755798c0777598#file-first-run-log . You see the license agreement in the output, with non UTF-8 characters (doesn't really matter — a plist parser won't be able to parse it even if everything is valid UTF-8).

And the second run: https://gist.github.com/zmwangx/e99395755798c0777598#file-second-run-log . This time the disk image is already attached (presumably because the previous run exited early without `hdiutil detach`), so no license agreement is printed, and everything is fine.

**Comment by zmwangx** [comment]
Ping.

(Maybe the "waiting user reply" label isn't appropriate anymore. Or I'm happy to provide more info.)

**Comment by vitorgalvao** [comment]
You’re quite right, @zmwangx, apologies. Removed the label. Also pinging in addition @jawshooah @ndr-qef @radeksimko, in case some of them has some insight.

**Comment by zmwangx** [comment]
I just did some research on this issue, and found [this solution](http://superuser.com/a/250624/184182) on SuperUser that works correctly on Yosemite with `baiducloud` and `sogouinput` (both of which failed previously). The workaround for bypassing the EULA is to quietly convert the dmg to UDTO format first, then mount from there:

```xml
> /usr/bin/hdiutil convert -quiet /Library/Caches/Homebrew/baiducloud-2.4.4.dmg -format UDTO -o /tmp/baiducloud-2.4.4
> /usr/bin/hdiutil mount -plist -nobrowse -readonly -noidme -mountrandom /tmp /tmp/baiducloud-2.4.4.cdr
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>system-entities</key>
	<array>
		<dict>
			<key>content-hint</key>
			<string>Apple_partition_map</string>
			<key>dev-entry</key>
			<string>/dev/disk3s1</string>
			<key>potentially-mountable</key>
			<false/>
			<key>unmapped-content-hint</key>
			<string>Apple_partition_map</string>
		</dict>
		<dict>
			<key>content-hint</key>
			<string>Apple_HFS</string>
			<key>dev-entry</key>
			<string>/dev/disk3s2</string>
			<key>mount-point</key>
			<string>/private/tmp/dmg.ucMfZH</string>
			<key>potentially-mountable</key>
			<true/>
			<key>unmapped-content-hint</key>
			<string>Apple_HFS</string>
			<key>volume-kind</key>
			<string>hfs</string>
		</dict>
		<dict>
			<key>content-hint</key>
			<string>Apple_partition_scheme</string>
			<key>dev-entry</key>
			<string>/dev/disk3</string>
			<key>potentially-mountable</key>
			<false/>
			<key>unmapped-content-hint</key>
			<string>Apple_partition_scheme</string>
		</dict>
	</array>
</dict>
</plist>
```

If this workaround is acceptable, then some changes need to be implemented in the core to allow for special treatment of some problematic dmgs.

**Comment by vitorgalvao** [comment]
That is great! Thank you for continuing to look for it and finding the issue and solution.

From the top of my head, I’m thinking something (to quickly handle this) like `container :type => :bad_dmg`. What do you all think? Any other suggestion?

**Comment by zmwangx** [comment]
LGTM :+1: But of course I have no say on this.

**Comment by vitorgalvao** [comment]
> LGTM :+1: But of course I have no say on this.

Sure you do. User ideas are very much valued. We maintainers might have the advantage of knowing the project’s inner workings and history, which makes us capable of guiding the concept of someone who doesn’t closer to what will actually work, but outside ideas are a really good thing.
