### ISSUE TITLE
`brew cask list` Returns Error

### ISSUE THREAD

**Issue by rcuza** [caskroom/homebrew-cask#13676]
I got a syntax error while running `brew cask list`. I ran the commands that the error said to run and got the same error afterwards. I'm following the instructions and reporting this issue. Not sure what other information to provide. 

```
01:34:43 ~$ brew cask list
Error: <main>:5: syntax error, unexpected <<
<<<<<<< Updated upstream
  ^
<main>:8: syntax error, unexpected ===, expecting keyword_end
=======
   ^
<main>:14: syntax error, unexpected >>, expecting keyword_end
>>>>>>> Stashed changes
  ^ while loading '/usr/local/Library/Taps/caskroom/homebrew-cask/Casks/calibre.rb'

  Most likely, this means you have an outdated version of homebrew-cask. Please run:

      brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup

  If this doesn’t fix the problem, please report this bug:

      https://github.com/caskroom/homebrew-cask/issues

/usr/local/Cellar/brew-cask/0.56.0/rubylib/hbc/source/path_base.rb:72:in `eval'
/usr/local/Cellar/brew-cask/0.56.0/rubylib/hbc/source/path_base.rb:72:in `rescue in load'
/usr/local/Cellar/brew-cask/0.56.0/rubylib/hbc/source/path_base.rb:69:in `load'
/usr/local/Cellar/brew-cask/0.56.0/rubylib/hbc.rb:85:in `load'
/usr/local/Cellar/brew-cask/0.56.0/rubylib/hbc/scopes.rb:55:in `block in installed'
/usr/local/Cellar/brew-cask/0.56.0/rubylib/hbc/scopes.rb:49:in `map'
/usr/local/Cellar/brew-cask/0.56.0/rubylib/hbc/scopes.rb:49:in `installed'
/usr/local/Cellar/brew-cask/0.56.0/rubylib/hbc/cli/list.rb:53:in `list_installed'
/usr/local/Cellar/brew-cask/0.56.0/rubylib/hbc/cli/list.rb:11:in `run'
/usr/local/Cellar/brew-cask/0.56.0/rubylib/hbc/cli.rb:79:in `run_command'
/usr/local/Cellar/brew-cask/0.56.0/rubylib/hbc/cli.rb:119:in `process'
/usr/local/Cellar/brew-cask/0.56.0/rubylib/brew-cask-cmd.rb:18:in `<main>'
01:34:55 ~$ brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup
Stashing your changes:
UU Casks/calibre.rb
Casks/calibre.rb: needs merge
Casks/calibre.rb: needs merge
Casks/calibre.rb: unmerged (e38a4ab77d5304eea4f076cd5f84c080eae1f195)
Casks/calibre.rb: unmerged (299dfa61db02011e17cda18e052b6a5b12913f5e)
Casks/calibre.rb: unmerged (92bf56e7e97aabeeef5a8c1eb1d789a5f551edcf)
fatal: git-write-tree: error building trees
Cannot save the current index state
Error: Failed to update tap: caskroom/cask
Already up-to-date.
Error: caskroom/cask/brew-cask 0.56.0 already installed
01:35:32 ~$ brew cask list
Error: <main>:5: syntax error, unexpected <<
<<<<<<< Updated upstream
  ^
<main>:8: syntax error, unexpected ===, expecting keyword_end
=======
   ^
<main>:14: syntax error, unexpected >>, expecting keyword_end
>>>>>>> Stashed changes
  ^ while loading '/usr/local/Library/Taps/caskroom/homebrew-cask/Casks/calibre.rb'

  Most likely, this means you have an outdated version of homebrew-cask. Please run:

      brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup

  If this doesn’t fix the problem, please report this bug:

      https://github.com/caskroom/homebrew-cask/issues

/usr/local/Cellar/brew-cask/0.56.0/rubylib/hbc/source/path_base.rb:72:in `eval'
/usr/local/Cellar/brew-cask/0.56.0/rubylib/hbc/source/path_base.rb:72:in `rescue in load'
/usr/local/Cellar/brew-cask/0.56.0/rubylib/hbc/source/path_base.rb:69:in `load'
/usr/local/Cellar/brew-cask/0.56.0/rubylib/hbc.rb:85:in `load'
/usr/local/Cellar/brew-cask/0.56.0/rubylib/hbc/scopes.rb:55:in `block in installed'
/usr/local/Cellar/brew-cask/0.56.0/rubylib/hbc/scopes.rb:49:in `map'
/usr/local/Cellar/brew-cask/0.56.0/rubylib/hbc/scopes.rb:49:in `installed'
/usr/local/Cellar/brew-cask/0.56.0/rubylib/hbc/cli/list.rb:53:in `list_installed'
/usr/local/Cellar/brew-cask/0.56.0/rubylib/hbc/cli/list.rb:11:in `run'
/usr/local/Cellar/brew-cask/0.56.0/rubylib/hbc/cli.rb:79:in `run_command'
/usr/local/Cellar/brew-cask/0.56.0/rubylib/hbc/cli.rb:119:in `process'
/usr/local/Cellar/brew-cask/0.56.0/rubylib/brew-cask-cmd.rb:18:in `<main>'
```

**Comment by rcuza** [comment]
Here is the full `/usr/local/Library/Taps/caskroom/homebrew-cask/Casks/calibre.rb` in case it is useful:

```
01:41:31 ~$ cat   /usr/local/Library/Taps/caskroom/homebrew-cask/Casks/calibre.rb
cask :v1 => 'calibre' do
  if MacOS.release < :mountain_lion
    version '1.48.0'
    sha256 '0533283965fbc9a6618d0b27c85bdf3671fe75ff0e89eeff406fe1457ee61b14'
  else
<<<<<<< Updated upstream
    version '2.37.1'
    sha256 '8cee654804704f6b0e031aec0d2f800d5ac033581a32156c35b736476d3d3e99'
=======
    version '2.36.0'
    sha256 '2ab762f4d2829116bd0860b551f141ca5f20a7ff26ec8ab6e4b66dc59c210b61'

    # github.com is an official download host per the vendor homepage, and a faster mirror than the main one
    url "https://github.com/kovidgoyal/calibre/releases/download/v#{version}/calibre-#{version}.dmg"
>>>>>>> Stashed changes
    appcast 'https://github.com/kovidgoyal/calibre/releases.atom'
  end

  url "http://download.calibre-ebook.com/#{version}/calibre-#{version}.dmg"
  name 'calibre'
  homepage 'http://calibre-ebook.com/'
  license :gpl

  app 'calibre.app'
  binary 'calibre.app/Contents/MacOS/calibre'
  binary 'calibre.app/Contents/MacOS/calibre-complete'
  binary 'calibre.app/Contents/MacOS/calibre-customize'
  binary 'calibre.app/Contents/MacOS/calibre-debug'
  binary 'calibre.app/Contents/MacOS/calibre-parallel'
  binary 'calibre.app/Contents/MacOS/calibre-server'
  binary 'calibre.app/Contents/MacOS/calibre-smtp'
  binary 'calibre.app/Contents/MacOS/calibredb'
  binary 'calibre.app/Contents/MacOS/ebook-convert'
  binary 'calibre.app/Contents/MacOS/ebook-device'
  binary 'calibre.app/Contents/MacOS/ebook-edit'
  binary 'calibre.app/Contents/MacOS/ebook-meta'
  binary 'calibre.app/Contents/MacOS/ebook-polish'
  binary 'calibre.app/Contents/MacOS/ebook-viewer'
  binary 'calibre.app/Contents/MacOS/fetch-ebook-metadata'
  binary 'calibre.app/Contents/MacOS/lrf2lrs'
  binary 'calibre.app/Contents/MacOS/lrfviewer'
  binary 'calibre.app/Contents/MacOS/lrs2lrf'
  binary 'calibre.app/Contents/MacOS/markdown-calibre'
  binary 'calibre.app/Contents/MacOS/web2disk'
end
```

**Comment by vitorgalvao** [comment]
That calibre file has conflicts. `cd "$(brew --prefix)/Library/Taps/caskroom/homebrew-cask"` and try `git reset HEAD --hard`.

**Comment by rcuza** [comment]
/me doh

I forgot I was hot to upgrade calibre before the upstream file was updated.

@vitorgalvao, Thank you.

**Comment by sebma** [comment]
@vitorgalvao Hi,
I had the same pb., It's now solved :)

B.T.W. : The directory is NOT `"$(brew --prefix)/Library/Taps/caskroom/homebrew-cask"` but `"$(brew --prefix)/Homebrew/Library/Taps/caskroom/homebrew-cask"`

**Comment by vitorgalvao** [comment]
@sebma It’s been 2 years. The directory was that one at the time.
