### ISSUE TITLE
Error: wrong number of arguments (1 for 0) while loading '/usr/local/Library/Taps/caskroom/homebrew-cask/Casks/dropbox.rb'

### ISSUE THREAD

**Issue by ilanbiala** [caskroom/homebrew-cask#13743]
I tried to run `brew cask uninstall dropbox`, but I got this error:

```
<main>:5:in `name'
<main>:5:in `<class:Dropbox>'
<main>:in `<main>'
/usr/local/Cellar/brew-cask/0.42.0/rubylib/cask/source/path_base.rb:55:in `eval'
/usr/local/Cellar/brew-cask/0.42.0/rubylib/cask/source/path_base.rb:55:in `rescue in load'
/usr/local/Cellar/brew-cask/0.42.0/rubylib/cask/source/path_base.rb:52:in `load'
/usr/local/Cellar/brew-cask/0.42.0/rubylib/cask/source/tapped.rb:28:in `load'
/usr/local/Cellar/brew-cask/0.42.0/rubylib/cask.rb:120:in `load'
/usr/local/Cellar/brew-cask/0.42.0/rubylib/cask/cli/uninstall.rb:8:in `block in run'
/usr/local/Cellar/brew-cask/0.42.0/rubylib/cask/cli/uninstall.rb:6:in `each'
/usr/local/Cellar/brew-cask/0.42.0/rubylib/cask/cli/uninstall.rb:6:in `run'
/usr/local/Cellar/brew-cask/0.42.0/rubylib/cask/cli.rb:81:in `run_command'
/usr/local/Cellar/brew-cask/0.42.0/rubylib/cask/cli.rb:121:in `process'
/usr/local/bin/brew-cask.rb:42:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:60:in `require?'
/usr/local/Library/brew.rb:139:in `<main>'
```

**Comment by vitorgalvao** [comment]
You’re using an old version of homebrew-cask. Please `brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup` and try again.

Please [always do this before opening new issues](https://github.com/caskroom/homebrew-cask#reporting-bugs).

Also, please do a search before opening issues, this one is extremely common (and the cause is always a very old version of homebrew-cask).
