### ISSUE TITLE
Hardlinks fail if destination folder is on a different device

### ISSUE THREAD

**Issue by tresni** [caskroom/homebrew-cask#13767]
So maybe I'm really weird, but I have my home (actually all /Users) directories on a different hard drive.

This means that anything with a `font` stanza will fail as you can not hard link across devices (for obvious reasons.)  It would be nice if I could still install things with `font` stanza and it either (a) copied when it got a `Cross-device link` error or (b) told me it couldn't do the link but allowed me to figure out how I want to copy things over.

```
Documents/Projects ●» brew cask install --verbose --debug --force font-droid-serif
==> Creating directories
==> Loading Cask definitions
==> Translating 'font-droid-serif' into a valid Cask source
==> Testing source class Hbc::Source::URI
==> Testing source class Hbc::Source::PathSlashRequired
==> Testing source class Hbc::Source::TappedQualified
==> Testing source class Hbc::Source::UntappedQualified
==> Testing source class Hbc::Source::Tapped
==> Success! Using source class Hbc::Source::Tapped
==> Resolved Cask URI or file source to '/usr/local/Library/Taps/caskroom/homebrew-fonts/Casks/font-droid-serif.rb'
==> Cask instance dumps in YAML:
==> Cask instance toplevel:
--- !ruby/object:KlassPrefixFontDroidSerif
sourcefile_path: !ruby/object:Pathname
  path: /usr/local/Library/Taps/caskroom/homebrew-fonts/Casks/font-droid-serif.rb
token: font-droid-serif
==> Cask instance method 'name':
--- []
==> Cask instance method 'homepage':
--- http://www.google.com/fonts/specimen/Droid%20Serif
...
==> Cask instance method 'url':
--- !ruby/object:Hbc::URL
uri: !ruby/object:URI::HTTPS
  scheme: https
  user:
  password:
  host: github.com
  port: 443
  path: /google/fonts/trunk/apache/droidserif
  query:
  opaque:
  registry:
  fragment:
  parser:
user_agent:
cookies:
referer:
using: :svn
revision: '50'
trust_cert: true
data:
==> Cask instance method 'appcast':
---
...
==> Cask instance method 'version':
--- :latest
...
==> Cask instance method 'license':
--- !ruby/object:Hbc::DSL::License
value: :apache
==> Cask instance method 'tags':
---
...
==> Cask instance method 'sha256':
--- :no_check
...
==> Cask instance method 'artifacts':
---
:font: !ruby/object:Set
  hash:
    ? - DroidSerif-Bold.ttf
    : true
    ? - DroidSerif-BoldItalic.ttf
    : true
    ? - DroidSerif-Italic.ttf
    : true
    ? - DroidSerif.ttf
    : true
==> Cask instance method 'caveats':
--- []
==> Cask instance method 'depends_on':
---
...
==> Cask instance method 'conflicts_with':
---
...
==> Cask instance method 'container':
---
...
==> Cask instance method 'gpg':
---
...
==> Cask instance method 'accessibility_access':
---
...
==> Hbc::Installer.install
==> Printing caveats
==> Downloading
Already downloaded: /Library/Caches/Homebrew/font-droid-serif--svn-latest.tar
==> Downloaded to -> /Library/Caches/Homebrew/font-droid-serif--svn-latest.tar
==> Extracting primary container
==> Determining which containers to use based on filetype
==> Checking container class Hbc::Container::Pkg
==> Checking container class Hbc::Container::Ttf
==> Checking container class Hbc::Container::Otf
==> Checking container class Hbc::Container::Air
==> Checking container class Hbc::Container::Cab
==> Executing: ["/usr/bin/file", "-Izb", "--", "#<Pathname:/Library/Caches/Homebrew/font-droid-serif--svn-latest.tar>"]
==> Checking container class Hbc::Container::Dmg
==> Executing: ["/usr/bin/hdiutil", "imageinfo", "#<Pathname:/Library/Caches/Homebrew/font-droid-serif--svn-latest.tar>"]
==> Checking container class Hbc::Container::SevenZip
==> Checking container class Hbc::Container::Sit
==> Checking container class Hbc::Container::Tar
==> Using container class Hbc::Container::Tar for /Library/Caches/Homebrew/font-droid-serif--svn-latest.tar
==> Executing: ["/usr/bin/tar", "xf", "#<Pathname:/Library/Caches/Homebrew/font-droid-serif--svn-latest.tar>", "-C", "/var/folders/gf/jnzchlkd573f43krqmy4tpxm0000gn/T/d20150914-16457-19ico10"]
==> Executing: ["/usr/bin/ditto", "--", "/var/folders/gf/jnzchlkd573f43krqmy4tpxm0000gn/T/d20150914-16457-19ico10", "#<Pathname:/opt/homebrew-cask/Caskroom/font-droid-serif/latest>"]
==> Installing artifacts
==> Determining which artifacts are present in Cask font-droid-serif
==> Checking for artifact class Hbc::Artifact::PreflightBlock
==> Checking for artifact class Hbc::Artifact::NestedContainer
==> Checking for artifact class Hbc::Artifact::Installer
==> Checking for artifact class Hbc::Artifact::App
==> Checking for artifact class Hbc::Artifact::Suite
==> Checking for artifact class Hbc::Artifact::Artifact
==> Checking for artifact class Hbc::Artifact::Colorpicker
==> Checking for artifact class Hbc::Artifact::Pkg
==> Checking for artifact class Hbc::Artifact::Prefpane
==> Checking for artifact class Hbc::Artifact::Qlplugin
==> Checking for artifact class Hbc::Artifact::Font
==> Checking for artifact class Hbc::Artifact::Service
==> Checking for artifact class Hbc::Artifact::StageOnly
==> Checking for artifact class Hbc::Artifact::Binary
==> Checking for artifact class Hbc::Artifact::InputMethod
==> Checking for artifact class Hbc::Artifact::InternetPlugin
==> Checking for artifact class Hbc::Artifact::ScreenSaver
==> Checking for artifact class Hbc::Artifact::Uninstall
==> Checking for artifact class Hbc::Artifact::PostflightBlock
==> Checking for artifact class Hbc::Artifact::Zap
==> 1 artifact/s defined
Hbc::Artifact::Font
==> Installing artifact of class Hbc::Artifact::Font
==> Hardlinking Font 'DroidSerif-Bold.ttf' to '/Volumes/Home/bhartvigsen/Library/Fonts/DroidSerif-Bold.ttf'
==> Executing: ["/bin/ln", "-hf", "--", "#<Pathname:/opt/homebrew-cask/Caskroom/font-droid-serif/latest/DroidSerif-Bold.ttf>", "#<Pathname:/Volumes/Home/bhartvigsen/Library/Fonts/DroidSerif-Bold.ttf>"]
==> ln: /Volumes/Home/bhartvigsen/Library/Fonts/DroidSerif-Bold.ttf: Cross-device link
==> Purging files for version latest of Cask font-droid-serif
Error: Command failed to execute!

==> Failed command:
["/bin/ln", "-hf", "--", "#<Pathname:/opt/homebrew-cask/Caskroom/font-droid-serif/latest/DroidSerif-Bold.ttf>", "#<Pathname:/Volumes/Home/bhartvigsen/Library/Fonts/DroidSerif-Bold.ttf>"]

==> Output of failed command:


==> Exit status of failed command:
#<Process::Status: pid 16554 exit 1>
/usr/local/Cellar/brew-cask/0.56.0/rubylib/hbc/system_command.rb:56:in `_assert_success'
/usr/local/Cellar/brew-cask/0.56.0/rubylib/hbc/system_command.rb:33:in `run'
/usr/local/Cellar/brew-cask/0.56.0/rubylib/hbc/system_command.rb:39:in `run!'
/usr/local/Cellar/brew-cask/0.56.0/rubylib/hbc/artifact/hardlinked.rb:13:in `create_filesystem_link'
/usr/local/Cellar/brew-cask/0.56.0/rubylib/hbc/artifact/symlinked.rb:68:in `link'
/usr/local/Cellar/brew-cask/0.56.0/rubylib/hbc/artifact/symlinked.rb:91:in `block in install_phase'
/usr/local/Cellar/brew-cask/0.56.0/rubylib/hbc/artifact/symlinked.rb:91:in `each'
/usr/local/Cellar/brew-cask/0.56.0/rubylib/hbc/artifact/symlinked.rb:91:in `install_phase'
/usr/local/Cellar/brew-cask/0.56.0/rubylib/hbc/installer.rb:119:in `block in install_artifacts'
/usr/local/Cellar/brew-cask/0.56.0/rubylib/hbc/installer.rb:117:in `each'
/usr/local/Cellar/brew-cask/0.56.0/rubylib/hbc/installer.rb:117:in `install_artifacts'
/usr/local/Cellar/brew-cask/0.56.0/rubylib/hbc/installer.rb:66:in `install'
/usr/local/Cellar/brew-cask/0.56.0/rubylib/hbc/cli/install.rb:20:in `block in install_casks'
/usr/local/Cellar/brew-cask/0.56.0/rubylib/hbc/cli/install.rb:17:in `each'
/usr/local/Cellar/brew-cask/0.56.0/rubylib/hbc/cli/install.rb:17:in `install_casks'
/usr/local/Cellar/brew-cask/0.56.0/rubylib/hbc/cli/install.rb:6:in `run'
/usr/local/Cellar/brew-cask/0.56.0/rubylib/hbc/cli.rb:79:in `run_command'
/usr/local/Cellar/brew-cask/0.56.0/rubylib/hbc/cli.rb:119:in `process'
/usr/local/Cellar/brew-cask/0.56.0/rubylib/brew-cask-cmd.rb:18:in `<main>'
```

**Comment by vitorgalvao** [comment]
[Won’t be a problem in the future](https://github.com/caskroom/homebrew-cask/issues/13201).

**Comment by fgimian** [comment]
Hi guys, I'm still having this problem, my home directory is on a different volume:

``` fots  /  Users  brew cask install font-sauce-code-powerline
==> Checking out https://github.com/powerline/fonts/trunk/SourceCodePro
==> No checksum defined for Cask font-sauce-code-powerline, skipping verification
==> Hardlinking Font 'Sauce Code Powerline Black.otf' to '/Volumes/Data/fots/Library/Fonts/Sauce Code Powe
==> ln: /Volumes/Data/fots/Library/Fonts/Sauce Code Powerline Black.otf: Cross-device link
Error: Command failed to execute!

==> Failed command:
["/bin/ln", "-hf", "--", "#<Pathname:/opt/homebrew-cask/Caskroom/font-sauce-code-powerline/latest/Sauce Code Powerline Black.otf>", "#<Pathname:/Volumes/Data/fots/Library/Fonts/Sauce Code Powerline Black.otf>"]

==> Output of failed command:


==> Exit status of failed command:
#<Process::Status: pid 750 exit 1>
 fots  /  Users  ls -ld ~
drwxr-xr-x+ 56 fots  staff  1904 13 Mar 15:46 /Volumes/Data/fots
 fots  /  Users  brew doctor --verbose
Your system is ready to brew.
 fots  /  Users  brew cask doctor --verbose
==> OS X Release:
10.11
==> OS X Release with Patchlevel:
10.11.3
==> Hardware Architecture:
intel-64
==> Ruby Version:
2.0.0-p645
==> Ruby Path:
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
==> Homebrew Version:
Homebrew 0.9.5 (git revision 4b30df; last commit 2016-03-12)
==> Homebrew Executable Path:
/usr/local/bin/brew
==> Homebrew Cellar Path:
/usr/local/Cellar
==> Homebrew Repository Path:
/usr/local
==> Homebrew Origin:
https://github.com/Homebrew/homebrew.git
==> Homebrew-cask Version:
0.60.0 (git revision 4afbb; last commit 5 hours ago)
==> Homebrew-cask Install Location:
/usr/local/Cellar/brew-cask/0.60.1 (error: legacy install. Run "brew uninstall --force brew-cask".)
==> Homebrew-cask Staging Location:
/opt/homebrew-cask/Caskroom
==> Homebrew-cask Cached Downloads:
/Library/Caches/Homebrew
/Library/Caches/Homebrew/Casks
4 files, 15.9M (warning: run "brew cask cleanup")
==> Homebrew-cask Default Tap Path:
/usr/local/Library/Taps/caskroom/homebrew-cask
==> Homebrew-cask Alternate Cask Taps:
/usr/local/Library/Taps/caskroom/homebrew-fonts
/usr/local/Library/Taps/caskroom/homebrew-versions
==> Homebrew-cask Default Tap Cask Count:
3013
==> Contents of $LOAD_PATH:
/usr/local/Library/Taps/caskroom/homebrew-cask/lib
/usr/local/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin15
/Library/Ruby/Site/2.0.0/universal-darwin15
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15
==> Contents of $RUBYLIB Environment Variable:
<NONE>
==> Contents of $RUBYOPT Environment Variable:
<NONE>
==> Contents of $RUBYPATH Environment Variable:
<NONE>
==> Contents of $RBENV_VERSION Environment Variable:
<NONE>
==> Contents of $CHRUBY_VERSION Environment Variable:
<NONE>
==> Contents of $GEM_HOME Environment Variable:
<NONE>
==> Contents of $GEM_PATH Environment Variable:
<NONE>
==> Contents of $BUNDLE_PATH Environment Variable:
<NONE>
==> Contents of $PATH Environment Variable:
PATH="/Volumes/Data/fots/.rbenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/lib/go/bin:/usr/local/Library/Taps/caskroom/homebrew-cask/cmd:/usr/local/Library/ENV/scm"
==> Contents of $SHELL Environment Variable:
SHELL="/bin/bash"
==> Contents of Locale Environment Variables:
LANG="en_AU.UTF-8"
==> Running As Privileged User:
No
```

Any ideas?
Fotis

**Comment by fgimian** [comment]
I guess this is due to the reasons explained in the [FAQ](https://github.com/caskroom/homebrew-fonts/blob/master/FAQ.md).  I'll just install my fonts manually :smile:
