### ISSUE TITLE
Error: undefined method `find_formula' 

### ISSUE THREAD

**Issue by logston** [caskroom/homebrew-cask#14405]
```
➜  ~  brew cask install vienna
==> Removing legacy Tap
Error: undefined method `find_formula' for #<Pathname:/usr/local/Library/Taps/phinze/homebrew-cask>
Please report this bug:
    https://github.com/caskroom/homebrew-cask/issues
/usr/local/Cellar/brew-cask/0.45.0/rubylib/cask.rb:110:in `set_up_taps'
/usr/local/Cellar/brew-cask/0.45.0/rubylib/cask.rb:50:in `init'
/usr/local/Cellar/brew-cask/0.45.0/rubylib/cask/cli.rb:119:in `process'
/usr/local/bin/brew-cask.rb:42:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:60:in `require?'
/usr/local/Library/brew.rb:139:in `<main>'
```

**Comment by vitorgalvao** [comment]
You’re using an old version of homebrew-cask. Please `brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup` and try again.

Please [always do this before opening new issues](https://github.com/caskroom/homebrew-cask#reporting-bugs).

**Comment by logston** [comment]
Got it. Will do. Thx.
