### ISSUE TITLE
Permission denied - /opt/homebrew-cask

### ISSUE THREAD

**Issue by ado1** [caskroom/homebrew-cask#14496]
brew cask install is not working --> Permission denied - /opt/homebrew-cask

history
osx 10.10
install brew
brew works
upgrade to osx 10.11
install brew cask 
--> cask nor working

here the console log with the state and the error
```
imac4ado:sync ado$ brew cask doctor
==> We need to make Caskroom for the first time at /opt/homebrew-cask/Caskroom
==> We'll set permissions properly so we won't need sudo in the future
==> OS X Release:
10.11
==> OS X Release with Patchlevel:
10.11
==> Hardware Architecture:
intel-64
==> Ruby Version:
2.0.0-p645
==> Ruby Path:
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
==> Homebrew Version:
0.9.5 (git revision 142f61; last commit 2015-10-17)
==> Homebrew Executable Path:
/usr/local/bin/brew
==> Homebrew Cellar Path:
/usr/local/Cellar
==> Homebrew Repository Path:
/usr/local
==> Homebrew Origin:
https://github.com/Homebrew/homebrew
==> Homebrew-cask Version:
0.58.0
==> Homebrew-cask Install Location:
/usr/local/Cellar/brew-cask/0.58.0
==> Homebrew-cask Staging Location:
/opt/homebrew-cask/Caskroom (error: path does not exist)
==> Homebrew-cask Cached Downloads:
/Library/Caches/Homebrew
/Library/Caches/Homebrew/Casks
2 files (warning: run "brew cask cleanup")
1.12 megs (warning: run "brew cask cleanup")
==> Homebrew-cask Default Tap Path:
/usr/local/Library/Taps/caskroom/homebrew-cask
==> Homebrew-cask Alternate Cask Taps:
<NONE>
==> Homebrew-cask Default Tap Cask Count:
2806
==> Contents of $LOAD_PATH:
/usr/local/Cellar/brew-cask/0.58.0/rubylib
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin15
/Library/Ruby/Site/2.0.0/universal-darwin15
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15
==> Contents of $RUBYLIB Environment Variable:
<NONE>
==> Contents of $RUBYOPT Environment Variable:
<NONE>
==> Contents of $RUBYPATH Environment Variable:
<NONE>
==> Contents of $RBENV_VERSION Environment Variable:
<NONE>
==> Contents of $CHRUBY_VERSION Environment Variable:
<NONE>
==> Contents of $GEM_HOME Environment Variable:
<NONE>
==> Contents of $GEM_PATH Environment Variable:
<NONE>
==> Contents of $BUNDLE_PATH Environment Variable:
<NONE>
==> Contents of $PATH Environment Variable:
PATH="/~/sync:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/local/sbin:/usr/local/mysql/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Server.app/Contents/ServerRoot/usr/bin:/Applications/Server.app/Contents/ServerRoot/usr/sbin:/usr/local/Library/ENV/scm"
==> Contents of $SHELL Environment Variable:
SHELL="/bin/bash"
==> Contents of Locale Environment Variables:
LANG="de_DE.UTF-8"
==> Running As Privileged User:
No
imac4ado:sync ado$ brew cask instal supaview
==> We need to make Caskroom for the first time at /opt/homebrew-cask/Caskroom
==> We'll set permissions properly so we won't need sudo in the future
==> Downloading http://twinside.free.fr/supaview/SupaView.1.3.2.zip
Already downloaded: /Library/Caches/Homebrew/supaview-1.3.2.zip
Error: Permission denied - /opt/homebrew-cask
  Most likely, this means you have an outdated version of homebrew-cask. Please run:
      brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup
  If this doesn’t fix the problem, please report this bug:
      https://github.com/caskroom/homebrew-cask/issues
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:245:in `mkdir'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:245:in `fu_mkdir'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:219:in `block (2 levels) in mkdir_p'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:217:in `reverse_each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:217:in `block in mkdir_p'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:203:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:203:in `mkdir_p'
/usr/local/Cellar/brew-cask/0.58.0/rubylib/hbc/installer.rb:100:in `extract_primary_container'
/usr/local/Cellar/brew-cask/0.58.0/rubylib/hbc/installer.rb:65:in `install'
/usr/local/Cellar/brew-cask/0.58.0/rubylib/hbc/cli/install.rb:20:in `block in install_casks'
/usr/local/Cellar/brew-cask/0.58.0/rubylib/hbc/cli/install.rb:17:in `each'
/usr/local/Cellar/brew-cask/0.58.0/rubylib/hbc/cli/install.rb:17:in `install_casks'
/usr/local/Cellar/brew-cask/0.58.0/rubylib/hbc/cli/install.rb:6:in `run'
/usr/local/Cellar/brew-cask/0.58.0/rubylib/hbc/cli.rb:79:in `run_command'
/usr/local/Cellar/brew-cask/0.58.0/rubylib/hbc/cli.rb:119:in `process'
/usr/local/Cellar/brew-cask/0.58.0/rubylib/brew-cask-cmd.rb:19:in `<main>'
imac4ado:sync ado$ brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup
Updated Homebrew from 142f61a6 to 25f3f43f.
==> Updated Formulae
deis                        deisctl                     gauge                       redis                     
Error: caskroom/cask/brew-cask 0.58.0 already installed
imac4ado:sync ado$ brew cask instal supaview
==> We need to make Caskroom for the first time at /opt/homebrew-cask/Caskroom
==> We'll set permissions properly so we won't need sudo in the future
==> Downloading http://twinside.free.fr/supaview/SupaView.1.3.2.zip
Already downloaded: /Library/Caches/Homebrew/supaview-1.3.2.zip
Error: Permission denied - /opt/homebrew-cask
  Most likely, this means you have an outdated version of homebrew-cask. Please run:
      brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup
  If this doesn’t fix the problem, please report this bug:
      https://github.com/caskroom/homebrew-cask/issues
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:245:in `mkdir'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:245:in `fu_mkdir'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:219:in `block (2 levels) in mkdir_p'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:217:in `reverse_each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:217:in `block in mkdir_p'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:203:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:203:in `mkdir_p'
/usr/local/Cellar/brew-cask/0.58.0/rubylib/hbc/installer.rb:100:in `extract_primary_container'
/usr/local/Cellar/brew-cask/0.58.0/rubylib/hbc/installer.rb:65:in `install'
/usr/local/Cellar/brew-cask/0.58.0/rubylib/hbc/cli/install.rb:20:in `block in install_casks'
/usr/local/Cellar/brew-cask/0.58.0/rubylib/hbc/cli/install.rb:17:in `each'
/usr/local/Cellar/brew-cask/0.58.0/rubylib/hbc/cli/install.rb:17:in `install_casks'
/usr/local/Cellar/brew-cask/0.58.0/rubylib/hbc/cli/install.rb:6:in `run'
/usr/local/Cellar/brew-cask/0.58.0/rubylib/hbc/cli.rb:79:in `run_command'
/usr/local/Cellar/brew-cask/0.58.0/rubylib/hbc/cli.rb:119:in `process'
/usr/local/Cellar/brew-cask/0.58.0/rubylib/brew-cask-cmd.rb:19:in `<main>'
imac4ado:sync ado$ 
```

'brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup'
does not solve the problem

here the current permissions:
```
imac4ado:sync ado$ sudo ls -arlt /opt/homebrew-cask
total 0
drwxr-xr-x  2 ado       staff   68 17 Okt 19:28 Caskroom
drwx------@ 4 macports  staff  136 17 Okt 19:28 ..
drwxr-xr-x  3 ado       staff  102 17 Okt 19:28 .
```

**Comment by vitorgalvao** [comment]
[Reporting Bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs).

Your report is really hard to read, as it is.

**Comment by samer** [comment]
Same problem over here.
```
➜  ~  brew cask install shady --verbose
==> Downloading http://instinctivecode.com/shady/shady_1.0.3.zip
Already downloaded: /Library/Caches/Homebrew/shady-1.0.3.zip
==> Symlinking App 'Shady.app' to '/Users/user/Applications/Shady.app'
==> ln: /Users/user/Applications/Shady.app: Permission denied
Error: Command failed to execute!

==> Failed command:
["/bin/ln", "-hfs", "--", "#<Pathname:/opt/homebrew-cask/Caskroom/shady/1.0.3/Shady.app>", "#<Pathname:/Users/user/Applications/Shady.app>"]

==> Output of failed command:


==> Exit status of failed command:
#<Process::Status: pid 48341 exit 1>
```

Here's the output for brew cask doctor:
```
➜  ~  brew cask doctor
==> OS X Release:
10.10
==> OS X Release with Patchlevel:
10.10.4
==> Hardware Architecture:
intel-64
==> Ruby Version:
2.0.0-p481
==> Ruby Path:
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
==> Homebrew Version:
0.9.5 (git revision 0deb; last commit 2015-10-18)
==> Homebrew Executable Path:
/usr/local/bin/brew
==> Homebrew Cellar Path:
/usr/local/Cellar
==> Homebrew Repository Path:
/usr/local
==> Homebrew Origin:
https://github.com/Homebrew/homebrew
==> Homebrew-cask Version:
0.58.0
==> Homebrew-cask Install Location:
/usr/local/Cellar/brew-cask/0.58.0
==> Homebrew-cask Staging Location:
/opt/homebrew-cask/Caskroom
==> Homebrew-cask Cached Downloads:
/Library/Caches/Homebrew
/Library/Caches/Homebrew/Casks
==> Homebrew-cask Default Tap Path:
/usr/local/Library/Taps/caskroom/homebrew-cask
==> Homebrew-cask Alternate Cask Taps:
/usr/local/Library/Taps/caskroom/homebrew-versions
==> Homebrew-cask Default Tap Cask Count:
2807
==> Contents of $LOAD_PATH:
/usr/local/Cellar/brew-cask/0.58.0/rubylib
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin14
/Library/Ruby/Site/2.0.0/universal-darwin14
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin14
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin14
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin14
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin14
==> Contents of $RUBYLIB Environment Variable:
<NONE>
==> Contents of $RUBYOPT Environment Variable:
<NONE>
==> Contents of $RUBYPATH Environment Variable:
<NONE>
==> Contents of $RBENV_VERSION Environment Variable:
<NONE>
==> Contents of $CHRUBY_VERSION Environment Variable:
<NONE>
==> Contents of $GEM_HOME Environment Variable:
<NONE>
==> Contents of $GEM_PATH Environment Variable:
<NONE>
==> Contents of $BUNDLE_PATH Environment Variable:
<NONE>
==> Contents of $PATH Environment Variable:
PATH="/Users/user/.nvm/versions/node/v0.12.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Library/ENV/scm"
==> Contents of $SHELL Environment Variable:
SHELL="/bin/zsh"
==> Contents of Locale Environment Variables:
LC_CTYPE="UTF-8"
==> Running As Privileged User:
No
```

**Comment by adityadalal924** [comment]
Can you run `brew doctor` and see if following those directions fixes permissions? (or paste the output here and we can go from there)

**Comment by ado1** [comment]
Hi I have already done this see top of the terminal excerpt. I do not get over the point 
```
imac4ado:sync ado$ brew cask doctor
==> We need to make Caskroom for the first time at /opt/homebrew-cask/Caskroom
==> We'll set permissions properly so we won't need sudo in the future
```
means doctor ask for password i enter this. everythink look fine. I run doctor again. It again ask for the pw to fix the problem. 

folde permissions see ls at the end of my first post

BTW - Thank you for the quick response

**Comment by vitorgalvao** [comment]
Does

```bash
sudo mkdir -p /opt/homebrew-cask/Caskroom
sudo chown -R ${USER}:staff /opt/homebrew-cask
```

work?

**Comment by ado1** [comment]
unfortunally not
```
brew cask doctor
```
still tells
```==> Homebrew-cask Staging Location:
/opt/homebrew-cask/Caskroom (error: path does not exist)```

and the permissions look fine as well
````imac4ado:sync ado$ sudo ls -arlt /opt/homebrew-cask
total 0
drwxr-xr-x  2 ado       staff   68 17 Okt 19:28 Caskroom
drwx------@ 4 macports  staff  136 17 Okt 19:28 ..
drwxr-xr-x  3 ado       staff  102 17 Okt 19:28 .
```

**Comment by vitorgalvao** [comment]
@samer Your issue is likely unrelated. Your issue problem is with your `~/Applications` directory.

Unfortunately, not really sure what to tell you there, @ado1. Let’s try this:

```bash
brew uninstall brew-cask
brew untap caskroom/cask
sudo rm -rf '/opt'
brew install caskroom/cask/brew-cask
```

**Comment by samer** [comment]
@vitorgalvao true, something must have changed the permissions of ~/Applications to root:staff instead of user:staff. It works now. Sorry for hijacking the thread.

**Comment by ado1** [comment]
@vitorgalvao uninstall and install like as you stated has worked feels a little bit like a MS solutions :-)
But It works now Thank you

**Comment by vitorgalvao** [comment]
> Sorry for hijacking the thread.

@samer No worries.

> like a MS solutions :-)

@ado1 I agree, [it does](https://youtu.be/p85xwZ_OLX0).

**Comment by DanMeltz** [comment]
Thank you, @vitorgalvao, your suggestion (re-quoted below) fixed the same problem for me.

```
brew uninstall brew-cask
brew untap caskroom/cask
sudo rm -rf '/opt'
brew install caskroom/cask/brew-cask
```

**Comment by vitorgalvao** [comment]
`brew install caskroom/cask/brew-cask` is no longer valid and should not be used. Homebrew-cask is installed on-demand by homebrew.

**Comment by DanMeltz** [comment]
Should I uninstall and then let homebrew do it's on-demand thing?

**Comment by vitorgalvao** [comment]
Should work as is.

**Comment by tcender** [comment]
This worked for me. 'brew search' answered my question.


`brew search cuda`
caskroom/drivers/cuda                    caskroom/cask/cuda-z
caskroom/versions/cuda-z-beta

If you meant "cuda" specifically:
It was migrated from caskroom/cask to caskroom/drivers.
You can access it again by running:
  brew tap caskroom/drivers_
`brew tap caskroom/drivers`
`brew cask install cuda`
==> Satisfying dependencies
==> Downloading ...
