### ISSUE TITLE
Error running brew cask list

### ISSUE THREAD

**Issue by ahmedelgabri** [caskroom/homebrew-cask#14805]
```shell
$ brew cask list --verbose
Error: <main>:2: syntax error, unexpected tIDENTIFIER, expecting keyword_end
...b5241e28c533b39e46f319735106faa'
...                               ^
<main>:5: syntax error, unexpected tCONSTANT, expecting keyword_end
  name 'WebKit Nightly'
              ^
<main>:6: syntax error, unexpected tIDENTIFIER, expecting keyword_end
  homepage 'http://nightly.webkit.org/'
                ^
<main>:6: unknown regexp options - ghtly
<main>:9: syntax error, unexpected tCONSTANT, expecting keyword_end
  app 'WebKit.app'
             ^
<main>:9: unterminated string meets end of file
<main>:9: syntax error, unexpected end-of-input, expecting keyword_end while loading '/usr/local/Library/Taps/caskroom/homebrew-versions/Casks/webkit-nightly.rb'

  Most likely, this means you have an outdated version of homebrew-cask. Please run:

      brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup

  If this doesn’t fix the problem, please report this bug:

      https://github.com/caskroom/homebrew-cask/issues

/usr/local/Cellar/brew-cask/0.59.0/rubylib/hbc/source/path_base.rb:72:in `eval'
/usr/local/Cellar/brew-cask/0.59.0/rubylib/hbc/source/path_base.rb:72:in `rescue in load'
/usr/local/Cellar/brew-cask/0.59.0/rubylib/hbc/source/path_base.rb:69:in `load'
/usr/local/Cellar/brew-cask/0.59.0/rubylib/hbc.rb:85:in `load'
/usr/local/Cellar/brew-cask/0.59.0/rubylib/hbc/scopes.rb:55:in `block in installed'
/usr/local/Cellar/brew-cask/0.59.0/rubylib/hbc/scopes.rb:49:in `map'
/usr/local/Cellar/brew-cask/0.59.0/rubylib/hbc/scopes.rb:49:in `installed'
/usr/local/Cellar/brew-cask/0.59.0/rubylib/hbc/cli/list.rb:53:in `list_installed'
/usr/local/Cellar/brew-cask/0.59.0/rubylib/hbc/cli/list.rb:11:in `run'
/usr/local/Cellar/brew-cask/0.59.0/rubylib/hbc/cli.rb:78:in `run_command'
/usr/local/Cellar/brew-cask/0.59.0/rubylib/hbc/cli.rb:118:in `process'
/usr/local/Cellar/brew-cask/0.59.0/rubylib/brew-cask-cmd.rb:19:in `<main>'
```

I tried running `brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup` and it always say that I'm running the latest brew cask 

```
$ brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup
Already up-to-date.
Error: caskroom/cask/brew-cask 0.59.0 already installed
```
I even reinstalled brew cask but still it didn't fix the problem.

**Comment by vitorgalvao** [comment]
Fixed. Just `brew update`.

**Comment by ahmedelgabri** [comment]
Thanks @vitorgalvao
