### ISSUE TITLE
Can't install things to /Applications on El Capitan

### ISSUE THREAD

**Issue by jackhooper** [caskroom/homebrew-cask#14904]
I'm getting the following error:

```
Error: Permission denied - /etc/Caskroom/lighttable
Please report this bug:
    https://github.com/caskroom/homebrew-cask/issues
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:245:in `mkdir'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:245:in `fu_mkdir'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:219:in `block (2 levels) in mkdir_p'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:217:in `reverse_each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:217:in `block in mkdir_p'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:203:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:203:in `mkdir_p'
/usr/local/Cellar/brew-cask/0.50.0/rubylib/cask/installer.rb:90:in `extract_primary_container'
/usr/local/Cellar/brew-cask/0.50.0/rubylib/cask/installer.rb:60:in `install'
/usr/local/Cellar/brew-cask/0.50.0/rubylib/cask/cli/install.rb:20:in `block in install_casks'
/usr/local/Cellar/brew-cask/0.50.0/rubylib/cask/cli/install.rb:17:in `each'
/usr/local/Cellar/brew-cask/0.50.0/rubylib/cask/cli/install.rb:17:in `install_casks'
/usr/local/Cellar/brew-cask/0.50.0/rubylib/cask/cli/install.rb:6:in `run'
/usr/local/Cellar/brew-cask/0.50.0/rubylib/cask/cli.rb:81:in `run_command'
/usr/local/Cellar/brew-cask/0.50.0/rubylib/cask/cli.rb:121:in `process'
/usr/local/bin/brew-cask.rb:42:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:72:in `require?'
/usr/local/Library/brew.rb:152:in `<main>'
```

I'm running OS X 10.11, and I also have the following in my bash profile:
```bash
export HOMEBREW_CASK_OPTS="--appdir=/Applications --caskroom=/etc/Caskroom"
```

The problem goes away if I remove that line from my bash profile, but then apps are symlinked to ~/Applications rather than /Applications, which is far less useful to me. 

Is there any way to fix this?

**Comment by vitorgalvao** [comment]
You’re using an old version of homebrew-cask. Please `brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup` and try again.

Please [always do this before opening new issues](https://github.com/caskroom/homebrew-cask#reporting-bugs).

**Comment by jackhooper** [comment]
Sorry about the outdated version. Still, I've done what you suggested, and I'm still having problems:

```
Error: Permission denied - /etc/Caskroom/lighttable

  Most likely, this means you have an outdated version of homebrew-cask. Please run:

      brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup

  If this doesn’t fix the problem, please report this bug:

      https://github.com/caskroom/homebrew-cask/issues

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:245:in `mkdir'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:245:in `fu_mkdir'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:219:in `block (2 levels) in mkdir_p'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:217:in `reverse_each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:217:in `block in mkdir_p'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:203:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:203:in `mkdir_p'
/usr/local/Cellar/brew-cask/0.59.0/rubylib/hbc/installer.rb:100:in `extract_primary_container'
/usr/local/Cellar/brew-cask/0.59.0/rubylib/hbc/installer.rb:65:in `install'
/usr/local/Cellar/brew-cask/0.59.0/rubylib/hbc/cli/install.rb:20:in `block in install_casks'
/usr/local/Cellar/brew-cask/0.59.0/rubylib/hbc/cli/install.rb:17:in `each'
/usr/local/Cellar/brew-cask/0.59.0/rubylib/hbc/cli/install.rb:17:in `install_casks'
/usr/local/Cellar/brew-cask/0.59.0/rubylib/hbc/cli/install.rb:6:in `run'
/usr/local/Cellar/brew-cask/0.59.0/rubylib/hbc/cli.rb:78:in `run_command'
/usr/local/Cellar/brew-cask/0.59.0/rubylib/hbc/cli.rb:118:in `process'
/usr/local/Cellar/brew-cask/0.59.0/rubylib/brew-cask-cmd.rb:19:in `<main>'
```

I've tried updated to OS X 10.11.1, and have also run ```bash
brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup
``` a couple times just to make sure.

**Comment by jawshooah** [comment]
Does your user have write permissions in `/etc` and `/Applications`? If not, you'll have to either change your `appdir` and `caskroom` settings, add your user to the `admin` group, or modify the permissions on those directories.

See #14382.

**Comment by jackhooper** [comment]
I'm not sure. How do I find out?

**Comment by jawshooah** [comment]
Try this:

```
sudo mkdir -p /etc/Caskroom
sudo chown -R "${USER}:staff" /etc/Caskroom
```

You'll have to enter your admin password. If you're not an admin, you'll have to either get an admin to set up the permissions and ownership for you, or pick different locations for your caskroom and appdir.

**Comment by jackhooper** [comment]
@jawshooah Thanks! That fixed it. Everything is working as it should be now.
