### ISSUE TITLE
Failed to build gem native extension: Your version of gcc is too old. You need at least version 4.2

### ISSUE THREAD

**Issue by atomantic** [caskroom/homebrew-cask#15017]
Setting up a fresh install of El Capitan.
I get this error whenever I try to run brew cask.

```
⚡⇒  brew cask --config
Error: ERROR: Failed to build gem native extension.

    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby extconf.rb 
-> sh /Library/Ruby/Gems/2.0.0/gems/dep-selector-libgecode-1.0.2/ext/libgecode3/vendor/gecode-3.7.3/configure --prefix=/Library/Ruby/Gems/2.0.0/gems/dep-selector-libgecode-1.0.2/lib/dep-selector-libgecode/vendored-gecode --disable-doc-dot --disable-doc-search --disable-doc-tagfile --disable-doc-chm --disable-doc-docset --disable-qt --disable-examples --disable-flatzinc
checking for the host operating system... Darwin
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for gcc... /usr/bin/gcc-4.2
checking whether we are using the GNU C compiler... no
checking whether /usr/bin/gcc-4.2 accepts -g... no
checking for /usr/bin/gcc-4.2 option to accept ISO C89... unsupported
checking for ranlib... ranlib
checking for diff... ok
checking for tar... ok
checking for make... ok
checking for sed... ok
checking for perl... ok
checking how to run the C++ preprocessor... g++ -E
configure: error: Your version of gcc is too old. You need at least version 4.2.
extconf.rb:98:in `block in run': Failed to build gecode library. (GecodeBuild::BuildError)
	from extconf.rb:97:in `chdir'
	from extconf.rb:97:in `run'
	from extconf.rb:104:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /Library/Ruby/Gems/2.0.0/gems/dep-selector-libgecode-1.0.2 for inspection.
Results logged to /Library/Ruby/Gems/2.0.0/extensions/universal-darwin-15/2.0.0/dep-selector-libgecode-1.0.2/gem_make.out
```

I've tried updating gcc:

```
⚡⇒  gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/local/Cellar/gcc/5.2.0/libexec/gcc/x86_64-apple-darwin15.0.0/5.2.0/lto-wrapper
Target: x86_64-apple-darwin15.0.0
Configured with: ../configure --build=x86_64-apple-darwin15.0.0 --prefix=/usr/local/Cellar/gcc/5.2.0 --libdir=/usr/local/Cellar/gcc/5.2.0/lib/gcc/5 --enable-languages=c,c++,objc,obj-c++,fortran --program-suffix=-5 --with-gmp=/usr/local/opt/gmp --with-mpfr=/usr/local/opt/mpfr --with-mpc=/usr/local/opt/libmpc --with-isl=/usr/local/opt/isl --with-system-zlib --enable-libstdcxx-time=yes --enable-stage1-checking --enable-checking=release --enable-lto --with-build-config=bootstrap-debug --disable-werror --with-pkgversion='Homebrew gcc 5.2.0' --with-bugurl=https://github.com/Homebrew/homebrew/issues --enable-plugin --disable-nls --enable-multilib
Thread model: posix
gcc version 5.2.0 (Homebrew gcc 5.2.0)
```

**Comment by jawshooah** [comment]
Are you sure this is related to `brew cask`? What about just `brew`?

Also, there is no `brew cask --config`. Not sure where you got that from.

**Comment by atomantic** [comment]
ugh, never mind, I had a rogue ENV var setting gcc to 4.2 for rvm. Going to purge my rvm in favor of rbenv and start over.

**Comment by atomantic** [comment]
Not sure what's messed up here..

```
antic@antic:~/.dotfiles|atomantic⚡⇒  rvm use ruby-2.2.1
Using /Users/antic/.rvm/gems/ruby-2.2.1
antic@antic:~/.dotfiles|atomantic⚡⇒  brew doctor
Your system is ready to brew.
antic@antic:~/.dotfiles|atomantic⚡⇒  brew cask list

Error: ERROR: Failed to build gem native extension.

    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby extconf.rb 
/Library/Ruby/Site/2.0.0/rubygems/ext/builder.rb:89:in `run': ERROR: Failed to build gem native extension. (Gem::Ext::BuildError)

    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby extconf.rb 
/Library/Ruby/Site/2.0.0/rubygems/ext/builder.rb:89:in `run': ERROR: Failed to build gem native extension. (Gem::Ext::BuildError)

    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby extconf.rb 
/Library/Ruby/Site/2.0.0/rubygems/ext/builder.rb:89:in `run': ERROR: Failed to build gem native extension. (Gem::Ext::BuildError)

    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby extconf.rb 
/Library/Ruby/Site/2.0.0/rubygems/ext/builder.rb:89:in `run': ERROR: Failed to build gem native extension. (Gem::Ext::BuildError)
```

^^ repeats that about 50 times...

then starts repeating this:

```
extconf failed, exit code 128

Gem files will remain installed in /Library/Ruby/Gems/2.0.0/gems/ffi-yajl-1.1.0 for inspection.
Results logged to /Library/Ruby/Gems/2.0.0/extensions/universal-darwin-15/2.0.0/ffi-yajl-1.1.0/gem_make.out
	from /Library/Ruby/Site/2.0.0/rubygems/ext/ext_conf_builder.rb:37:in `block in build'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tempfile.rb:324:in `open'
	from /Library/Ruby/Site/2.0.0/rubygems/ext/ext_conf_builder.rb:17:in `build'
	from /Library/Ruby/Site/2.0.0/rubygems/ext/builder.rb:161:in `block (2 levels) in build_extension'
	from /Library/Ruby/Site/2.0.0/rubygems/ext/builder.rb:160:in `chdir'
	from /Library/Ruby/Site/2.0.0/rubygems/ext/builder.rb:160:in `block in build_extension'
	from /Library/Ruby/Site/2.0.0/rubygems/ext/builder.rb:159:in `synchronize'
	from /Library/Ruby/Site/2.0.0/rubygems/ext/builder.rb:159:in `build_extension'
	from /Library/Ruby/Site/2.0.0/rubygems/ext/builder.rb:198:in `block in build_extensions'
	from /Library/Ruby/Site/2.0.0/rubygems/ext/builder.rb:195:in `each'
	from /Library/Ruby/Site/2.0.0/rubygems/ext/builder.rb:195:in `build_extensions'
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:1436:in `block in build_extensions'
	from /Library/Ruby/Site/2.0.0/rubygems/user_interaction.rb:45:in `use_ui'
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:1434:in `build_extensions'
	from /Library/Ruby/Site/2.0.0/rubygems/stub_specification.rb:60:in `build_extensions'
	from /Library/Ruby/Site/2.0.0/rubygems/basic_specification.rb:56:in `contains_requirable_file?'
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:925:in `block in find_inactive_by_path'
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:924:in `each'
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:924:in `find'
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:924:in `find_inactive_by_path'
	from /Library/Ruby/Site/2.0.0/rubygems.rb:185:in `try_activate'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:132:in `rescue in require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
	from extconf.rb:3:in `<main>'

extconf failed, exit code 1

```

**Comment by atomantic** [comment]
ok, if anyone gets an issue like this, for some reason I had a bunch of old gems installed that needed cleaning. I purged (killed all of my installed gems):
```
sudo gem uninstall -aIx
gem cleanup 
```

and now `brew cask` commands are happy

**Comment by kevinpapst** [comment]
@atomantic you are my official hero of the day ;-) 
I had troubles for hours getting cask up and running. Seems there was a gem installed that messed brews ruby environment  up. Pretty sure I will run into more troubles as my dev environment is now broken, but hey, at least cask is finally running...
