### ISSUE TITLE
Perssion Denied - brew cask install Cheatsheet -/opt/homebrew-cask/Caskroom/cheatsheet

### ISSUE THREAD

**Issue by rickdgit** [caskroom/homebrew-cask#15202]
Hi 
I follow the instruction from brew to report this bug

I was hoping to install cheatsheet on my Mac 
Therefore i type 'brew cask install cheatsheet'
I got the report as follow:
==> Downloading http://mediaatelier.com/CheatSheet/CheatSheet_1.2.2.zip
######################################################################## 100.0%
Error: Permission denied - /opt/homebrew-cask/Caskroom/cheatsheet

  Most likely, this means you have an outdated version of homebrew-cask. Please run:

      brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup

  If this doesn’t fix the problem, please report this bug:

      https://github.com/caskroom/homebrew-cask/issues

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:245:in `mkdir'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:245:in `fu_mkdir'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:219:in `block (2 levels) in mkdir_p'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:217:in `reverse_each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:217:in `block in mkdir_p'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:203:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:203:in `mkdir_p'
/usr/local/Cellar/brew-cask/0.59.0/rubylib/hbc/installer.rb:100:in `extract_primary_container'
/usr/local/Cellar/brew-cask/0.59.0/rubylib/hbc/installer.rb:65:in `install'
/usr/local/Cellar/brew-cask/0.59.0/rubylib/hbc/cli/install.rb:20:in `block in install_casks'
/usr/local/Cellar/brew-cask/0.59.0/rubylib/hbc/cli/install.rb:17:in `each'
/usr/local/Cellar/brew-cask/0.59.0/rubylib/hbc/cli/install.rb:17:in `install_casks'
/usr/local/Cellar/brew-cask/0.59.0/rubylib/hbc/cli/install.rb:6:in `run'
/usr/local/Cellar/brew-cask/0.59.0/rubylib/hbc/cli.rb:78:in `run_command'
/usr/local/Cellar/brew-cask/0.59.0/rubylib/hbc/cli.rb:118:in `process'
/usr/local/Cellar/brew-cask/0.59.0/rubylib/brew-cask-cmd.rb:19:in `<main>'

then i tried 'brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup'
and the response was 

Already up-to-date.
Error: caskroom/cask/brew-cask 0.59.0 already installed 

Hope it helps

**Comment by rickdgit** [comment]
Oh I got 
The main problem is /opt/homebrew-cask/Caskroom is belongs to another user 
Sorry for wasting your time for reading
