### ISSUE TITLE
Error not a directory @ dir_s_rmdir CASKNAME

### ISSUE THREAD

**Issue by thepahtmaster** [caskroom/homebrew-cask#15217]
Hi there,

I've been using Homebrew to install packages sucessfully and thought I'd try casks.

My first cask was to be chromium to test it.

I first got a permissions error (similar to the above) and fixed it with chown (making "myself":staff the owner). Now I have the following error:

```
==> Downloading https://download-chromium.appspot.com/dl/Mac
Already downloaded: /Library/Caches/Homebrew/chromium-latest
Error: Not a directory @ dir_s_rmdir - /opt/homebrew-cask/Caskroom/chromium/.metadata/latest

  Most likely, this means you have an outdated version of homebrew-cask. Please run:

      brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup

  If this doesn’t fix the problem, please report this bug:

      https://github.com/caskroom/homebrew-cask/issues

/usr/local/Cellar/brew-cask/0.59.0/rubylib/hbc/utils.rb:147:in `rmdir'
/usr/local/Cellar/brew-cask/0.59.0/rubylib/hbc/utils.rb:147:in `rmdir'
/usr/local/Cellar/brew-cask/0.59.0/rubylib/hbc/utils.rb:147:in `rmdir_if_possible'
/usr/local/Cellar/brew-cask/0.59.0/rubylib/hbc/installer.rb:354:in `purge_versioned_files'
/usr/local/Cellar/brew-cask/0.59.0/rubylib/hbc/installer.rb:70:in `rescue in install'
/usr/local/Cellar/brew-cask/0.59.0/rubylib/hbc/installer.rb:61:in `install'
/usr/local/Cellar/brew-cask/0.59.0/rubylib/hbc/cli/install.rb:20:in `block in install_casks'
/usr/local/Cellar/brew-cask/0.59.0/rubylib/hbc/cli/install.rb:17:in `each'
/usr/local/Cellar/brew-cask/0.59.0/rubylib/hbc/cli/install.rb:17:in `install_casks'
/usr/local/Cellar/brew-cask/0.59.0/rubylib/hbc/cli/install.rb:6:in `run'
/usr/local/Cellar/brew-cask/0.59.0/rubylib/hbc/cli.rb:78:in `run_command'
/usr/local/Cellar/brew-cask/0.59.0/rubylib/hbc/cli.rb:118:in `process'
/usr/local/Cellar/brew-cask/0.59.0/rubylib/brew-cask-cmd.rb:19:in `<main>'
```

I think this may be a ruby issue - but I don't know ruby. 

Output from cask doctor:

```
brew cask doctor==> OS X Release:
10.5
==> OS X Release with Patchlevel:
10.5.4
==> Hardware Architecture:
intel-32
==> Ruby Version:
2.2.3-p173
==> Ruby Path:
/usr/local/Cellar/ruby/2.2.3/bin/ruby
==> Homebrew Version:
0.9.5 (no git repository)
==> Homebrew Executable Path:
/usr/local/bin/brew
==> Homebrew Cellar Path:
/usr/local/Cellar
==> Homebrew Repository Path:
/usr/local
==> Homebrew Origin:
<NONE> (Error)
==> Homebrew-cask Version:
0.59.0
==> Homebrew-cask Install Location:
/usr/local/Cellar/brew-cask/0.59.0
==> Homebrew-cask Staging Location:
/opt/homebrew-cask/Caskroom
==> Homebrew-cask Cached Downloads:
/Library/Caches/Homebrew
/Library/Caches/Homebrew/Casks
2 files (warning: run "brew cask cleanup")
128.02 megs (warning: run "brew cask cleanup")
==> Homebrew-cask Default Tap Path:
/usr/local/Library/Taps/caskroom/homebrew-cask
==> Homebrew-cask Alternate Cask Taps:
<NONE>
==> Homebrew-cask Default Tap Cask Count:
2857
==> Contents of $LOAD_PATH:
/usr/local/Cellar/brew-cask/0.59.0/rubylib
/usr/local/lib/ruby/site_ruby/2.2.0
/usr/local/lib/ruby/site_ruby/2.2.0/i386-darwin9.0
/usr/local/lib/ruby/site_ruby
/usr/local/lib/ruby/vendor_ruby/2.2.0
/usr/local/lib/ruby/vendor_ruby/2.2.0/i386-darwin9.0
/usr/local/lib/ruby/vendor_ruby
/usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0
/usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/i386-darwin9.0
==> Contents of $RUBYLIB Environment Variable:
<NONE>
==> Contents of $RUBYOPT Environment Variable:
<NONE>
==> Contents of $RUBYPATH Environment Variable:
<NONE>
==> Contents of $RBENV_VERSION Environment Variable:
<NONE>
==> Contents of $CHRUBY_VERSION Environment Variable:
<NONE>
==> Contents of $GEM_HOME Environment Variable:
<NONE>
==> Contents of $GEM_PATH Environment Variable:
<NONE>
==> Contents of $BUNDLE_PATH Environment Variable:
<NONE>
==> Contents of $PATH Environment Variable:
PATH="/usr/local/sbin:/usr/local/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/local/sbin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/Library/ENV/scm"
==> Contents of $SHELL Environment Variable:
SHELL="/bin/bash"
==> Contents of Locale Environment Variables:
LANG="en_GB.UTF-8"
==> Running As Privileged User:
No
```

Kind regards,

Steve

**Comment by vitorgalvao** [comment]
[Reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs).

**Comment by thepahtmaster** [comment]
Apologies - thanks for the pointer (and the fenced code blocks)

For further info --verbose flag is the same output as supplied above.

Homebrew version 0.9.5 (no git repository)
brew-cask version 0.59.0

**Comment by thepahtmaster** [comment]
Thanks - I think there is an errant ' at the end of those commands...

Brew doctor output below - no errors but a few warnings:

```
$ brew doctor
Please note that these warnings are just used to help the Tigerbrew maintainers
with debugging if you file an issue. If everything you use Tigerbrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Tigerbrew formulae, and may need to be deleted.

Unexpected dylibs:
    /usr/local/lib/libblkid.2.0.dylib
    /usr/local/lib/libcom_err.1.1.dylib
    /usr/local/lib/libe2p.2.1.dylib
    /usr/local/lib/libext2fs.2.1.dylib
    /usr/local/lib/libfuse.0.dylib
    /usr/local/lib/liblzma.5.dylib
    /usr/local/lib/libss.1.0.dylib
    /usr/local/lib/libulockmgr.0.dylib
    /usr/local/lib/libuuid.1.1.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Tigerbrew formulae, and may need to be deleted.

Unexpected header files:
    /usr/local/include/ulockmgr.h

Warning: Unbrewed .la files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Tigerbrew formulae, and may need to be deleted.

Unexpected .la files:
    /usr/local/lib/libulockmgr.la

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Tigerbrew formulae, and may need to be deleted.

Unexpected static libraries:
    /usr/local/lib/libfuse.a
    /usr/local/lib/libulockmgr.a

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
    xz
```
I tried `brew link` on xz but it says it's already linked:

```
$ brew link xz
Linking /usr/local/Cellar/xz/5.2.1... 
Error: Could not symlink bin/xzmore
Target /usr/local/bin/xzmore
already exists. You may want to remove it:
  rm '/usr/local/bin/xzmore'

To force the link and overwrite all conflicting files:
  brew link --overwrite xz

To list all files that would be deleted:
  brew link --overwrite --dry-run xz

```

Is that all ok - shall i try to add the tap now?

**Comment by thepahtmaster** [comment]
Sorry think I ran the wrong doctor

Cask doctor has errors:

```
brew cask doctor
==> OS X Release:
10.5
==> OS X Release with Patchlevel:
10.5.4
==> Hardware Architecture:
intel-32
==> Ruby Version:
2.2.3-p173
==> Ruby Path:
/usr/local/Cellar/ruby/2.2.3/bin/ruby
==> Homebrew Version:
0.9.5 (git revision b76c7; last commit 2015-10-31)
==> Homebrew Executable Path:
/usr/local/bin/brew
==> Homebrew Cellar Path:
/usr/local/Cellar
==> Homebrew Repository Path:
/usr/local
==> Homebrew Origin:
https://github.com/mistydemeo/tigerbrew.git (warning: nonstandard origin)
==> Homebrew-cask Version:
0.59.0
==> Homebrew-cask Install Location:
/usr/local/Cellar/brew-cask/0.59.0
==> Homebrew-cask Staging Location:
/opt/homebrew-cask/Caskroom
==> Homebrew-cask Cached Downloads:
/Library/Caches/Homebrew
/Library/Caches/Homebrew/Casks
0 files
0.00 megs
==> Homebrew-cask Default Tap Path:
/usr/local/Library/Taps/caskroom/homebrew-cask
==> Homebrew-cask Alternate Cask Taps:
<NONE>
==> Homebrew-cask Default Tap Cask Count:
0 (Error reading /usr/local/Library/Taps/caskroom/homebrew-cask)
==> Contents of $LOAD_PATH:
/usr/local/Cellar/brew-cask/0.59.0/rubylib
/usr/local/lib/ruby/site_ruby/2.2.0
/usr/local/lib/ruby/site_ruby/2.2.0/i386-darwin9.0
/usr/local/lib/ruby/site_ruby
/usr/local/lib/ruby/vendor_ruby/2.2.0
/usr/local/lib/ruby/vendor_ruby/2.2.0/i386-darwin9.0
/usr/local/lib/ruby/vendor_ruby
/usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0
/usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/i386-darwin9.0
==> Contents of $RUBYLIB Environment Variable:
<NONE>
==> Contents of $RUBYOPT Environment Variable:
<NONE>
==> Contents of $RUBYPATH Environment Variable:
<NONE>
==> Contents of $RBENV_VERSION Environment Variable:
<NONE>
==> Contents of $CHRUBY_VERSION Environment Variable:
<NONE>
==> Contents of $GEM_HOME Environment Variable:
<NONE>
==> Contents of $GEM_PATH Environment Variable:
<NONE>
==> Contents of $BUNDLE_PATH Environment Variable:
<NONE>
==> Contents of $PATH Environment Variable:
PATH="/usr/local/sbin:/usr/local/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/local/sbin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/Library/ENV/scm"
==> Contents of $SHELL Environment Variable:
SHELL="/bin/bash"
==> Contents of Locale Environment Variables:
LANG="en_GB.UTF-8"
==> Running As Privileged User:
No
```

**Comment by adityadalal924** [comment]
It seems that you are running OS X 10.5, and it looks like Chromium deprecated support for that OS version [back in 2012](https://groups.google.com/a/chromium.org/forum/#!topic/chromium-dev/3nUlhuHbf0Q).

Unfortunately, many applications have done the same, so it is out of our hands; we only provide easy install/packaging and don't touch the actual application.

This [StackOverflow post](http://apple.stackexchange.com/questions/82764/is-there-a-web-browser-i-can-use-safely-on-mac-os-10-5-8) states that you should be able to get Opera 12 working, however.

**Comment by thepahtmaster** [comment]
I thought Homebrew allowed me to complie the source to run on my system (or use a Linux version).

Chromium was an example - the issues were installing anything with cask

**Comment by vitorgalvao** [comment]
To add, we don’t really support anything that far back. If it works, great, but we won’t be shy about breaking it and not fixing it.

> I thought Homebrew allowed me to complie the source to run on my system (or use a Linux version).

We’re not homebrew, we’re something different. We do not compile anything.
