### ISSUE TITLE
Brackets - wrong number of arguments

### ISSUE THREAD

**Issue by lauhakari** [caskroom/homebrew-cask#15341]
When runnning 'list', or even trying to uninstall brackets, get the following

```bash
Error: wrong number of arguments (1 for 0) while loading '/usr/local/Library/Taps/caskroom/homebrew-cask/Casks/brackets.rb'
Please report this bug:
    https://github.com/caskroom/homebrew-cask/issues
<main>:6:in `name'
<main>:6:in `<class:Brackets>'
<main>:in `<main>'
/usr/local/Cellar/brew-cask/0.42.0/rubylib/cask/source/path_base.rb:55:in `eval'
/usr/local/Cellar/brew-cask/0.42.0/rubylib/cask/source/path_base.rb:55:in `rescue in load'
/usr/local/Cellar/brew-cask/0.42.0/rubylib/cask/source/path_base.rb:52:in `load'
/usr/local/Cellar/brew-cask/0.42.0/rubylib/cask/source/tapped.rb:28:in `load'
/usr/local/Cellar/brew-cask/0.42.0/rubylib/cask.rb:120:in `load'
/usr/local/Cellar/brew-cask/0.42.0/rubylib/cask/cli/home.rb:9:in `block in run'
/usr/local/Cellar/brew-cask/0.42.0/rubylib/cask/cli/home.rb:7:in `each'
/usr/local/Cellar/brew-cask/0.42.0/rubylib/cask/cli/home.rb:7:in `run'
/usr/local/Cellar/brew-cask/0.42.0/rubylib/cask/cli.rb:81:in `run_command'
/usr/local/Cellar/brew-cask/0.42.0/rubylib/cask/cli.rb:121:in `process'
/usr/local/bin/brew-cask.rb:42:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:72:in `require?'
/usr/local/Library/brew.rb:152:in `<main>'
´´´

**Comment by lauhakari** [comment]
A **simple brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup**  seems to have solved it.
