### ISSUE TITLE
Bug report: Commands won't work; Linux Ubuntu.

### ISSUE THREAD

**Issue by calebkleveter** [caskroom/homebrew-cask#16835]
(Remember to run `brew update; brew cleanup; brew cask cleanup` before reporting your issue. It usually fixes things!)

### Description of issue

I am doing some development in a [cloud IDE](https://c9.io/?redirect=0) that runs an Ubuntu VM. I installed Linux Brew, then I tried to install Cask. The brew commands work, but cask doesn't. I have tried running the commands that are listed, but they don't help. I am trying to run `brew cask search android`.

### Output of `brew cask <command> --verbose`

```
Error: Permission denied @ dir_s_mkdir - /Library
  Most likely, this means you have an outdated version of homebrew-cask. Please run:

      brew uninstall --force brew-cask; brew untap phinze/cask; brew update; brew cleanup; brew cask cleanup

  If this doesn’t fix the problem, please report this bug:

      https://github.com/caskroom/homebrew-cask#reporting-bugs

/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:252:in `mkdir'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:252:in `fu_mkdir'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:226:in `block (2 levels) in mkdir_p'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:224:in `reverse_each'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:224:in `block in mkdir_p'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:210:in `each'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:210:in `mkdir_p'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/pathname.rb:564:in `mkpath'
/home/ubuntu/.linuxbrew/Library/Taps/caskroom/homebrew-cask/lib/vendor/homebrew-fork/global.rb:18:in `mkpath'
/home/ubuntu/.linuxbrew/Library/Taps/caskroom/homebrew-cask/lib/hbc.rb:57:in `init'
/home/ubuntu/.linuxbrew/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli.rb:114:in `process'
/home/ubuntu/.linuxbrew/Library/Taps/caskroom/homebrew-cask/cmd/brew-cask.rb:26:in `<top (required)>'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/home/ubuntu/.linuxbrew/Library/brew.rb:69:in `require?'
/home/ubuntu/.linuxbrew/Library/brew.rb:149:in `<main>'
Error: Kernel.exit
```

### Output of `brew doctor`

```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: /tmp is world-writable but does not have the sticky bit set.
Please run "Repair Disk Permissions" in Disk Utility.

Warning: You have a non-Homebrew 'pkg-config' in your PATH:
  /usr/bin/pkg-config

`./configure` may have problems finding brew-installed packages using
this other pkg-config.
```

### Output of `brew cask doctor`

```
Error: Permission denied @ dir_s_mkdir - /Library
  Most likely, this means you have an outdated version of homebrew-cask. Please run:

      brew uninstall --force brew-cask; brew untap phinze/cask; brew update; brew cleanup; brew cask cleanup

  If this doesn’t fix the problem, please report this bug:

      https://github.com/caskroom/homebrew-cask#reporting-bugs

/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:252:in `mkdir'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:252:in `fu_mkdir'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:226:in `block (2 levels) in mkdir_p'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:224:in `reverse_each'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:224:in `block in mkdir_p'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:210:in `each'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:210:in `mkdir_p'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/pathname.rb:564:in `mkpath'
/home/ubuntu/.linuxbrew/Library/Taps/caskroom/homebrew-cask/lib/vendor/homebrew-fork/global.rb:18:in `mkpath'
/home/ubuntu/.linuxbrew/Library/Taps/caskroom/homebrew-cask/lib/hbc.rb:57:in `init'
/home/ubuntu/.linuxbrew/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli.rb:114:in `process'
/home/ubuntu/.linuxbrew/Library/Taps/caskroom/homebrew-cask/cmd/brew-cask.rb:26:in `<top (required)>'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/home/ubuntu/.linuxbrew/Library/brew.rb:69:in `require?'
/home/ubuntu/.linuxbrew/Library/brew.rb:149:in `<main>'
```

**Comment by jawshooah** [comment]
`brew-cask` is exclusively for OSX
