### ISSUE TITLE
Casks fail to install

### ISSUE THREAD

**Issue by anthonygreen** [caskroom/homebrew-cask#17071]
I'm getting repeated variations of issue #16475 not just with java but other packages too

ex:

    failed: [venus] => (item=firefox) => {"failed": true, "item": "firefox"}
    msg: Error: Permission denied - (/Library/Caches/Homebrew/firefox-43.0.4.dmg, /Library/Caches/Homebrew/Casks/firefox-43.0.4.dmg)
      Most likely, this means you have an outdated version of homebrew-cask. Please run:

          brew uninstall --force brew-cask; brew untap phinze/cask; brew update; brew cleanup; brew cask cleanup

      If this doesn’t fix the problem, please report this bug:

          https://github.com/caskroom/homebrew-cask#reporting-bugs

    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:349:in `symlink'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:349:in `block in ln_s'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1568:in `fu_each_src_dest0'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:347:in `ln_s'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:370:in `ln_sf'
    /usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/download.rb:45:in `create_cache_symlink'
    /usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/download.rb:15:in `perform'
    /usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/installer.rb:94:in `download'
    /usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/installer.rb:68:in `install'
    /usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/install.rb:20:in `block in install_casks'
    /usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/install.rb:17:in `each'
    /usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/install.rb:17:in `install_casks'
    /usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/install.rb:6:in `run'
    /usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli.rb:78:in `run_command'
    /usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli.rb:116:in `process'
    /usr/local/Library/Taps/caskroom/homebrew-cask/cmd/brew-cask.rb:26:in `<top (required)>'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    /usr/local/Library/brew.rb:69:in `require?'
    /usr/local/Library/brew.rb:149:in `<main>'

**Comment by anthonygreen** [comment]
sudo chown -R $USER /Library/Caches/Homebrew/ 

Is Stackoverflow's suggested fix
