### ISSUE TITLE
Bug report: Error: undefined method `join' for "/usr/local/Cellar":String

### ISSUE THREAD

**Issue by agsimeonov** [caskroom/homebrew-cask#17356]
### Description of issue

Brew cask seems to run fine however I have the following issue.

When I run brew cask doctor I get the following error:

```
Error: undefined method `join' for "/usr/local/Cellar":String
```

This is a fresh install on a new system so it doesn't have the old tap installed.  Running:

```
 brew uninstall --force brew-cask; brew untap phinze/cask; brew update; brew cleanup; brew cask cleanup
```

Does not fix the issue.

### Output of `brew cask doctor`

```
==> OS X Release:
10.11
==> OS X Release with Patchlevel:
10.11.3
==> Hardware Architecture:
intel-64
==> Ruby Version:
2.0.0-p645
==> Ruby Path:
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
==> Homebrew Version:
Homebrew 0.9.5 (git revision c8de; last commit 2016-01-19)
==> Homebrew Executable Path:
/usr/local/bin/brew
==> Homebrew Cellar Path:
/usr/local/Cellar
==> Homebrew Repository Path:
/usr/local
==> Homebrew Origin:
https://github.com/Homebrew/homebrew
==> Homebrew-cask Version:
0.60.0 (git revision 6c20; last commit 65 minutes ago)
Error: undefined method `join' for "/usr/local/Cellar":String
  Most likely, this means you have an outdated version of homebrew-cask. Please run:

      brew uninstall --force brew-cask; brew untap phinze/cask; brew update; brew cleanup; brew cask cleanup

  If this doesn’t fix the problem, please report this bug:

      https://github.com/caskroom/homebrew-cask#reporting-bugs

/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/doctor.rb:186:in `render_install_location'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/doctor.rb:15:in `run'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli.rb:79:in `run_command'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli.rb:117:in `process'
/usr/local/Library/Taps/caskroom/homebrew-cask/cmd/brew-cask.rb:26:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:28:in `require?'
/usr/local/Library/brew.rb:94:in `<main>'
```

**Comment by agsimeonov** [comment]
I was able to resolve the issue by creating the the folder Cellar in /usr/local/ since this is a fresh install /usr/local/Cellar did not exist.
