### ISSUE TITLE
Bug report:

### ISSUE THREAD

**Issue by napaxton** [caskroom/homebrew-cask#17544]
I'm trying to create a new cask, for the binary [PanConvert](http://panconvert.sourceforge.net). I have followed the instructions on the adding_a_cask.md page.

Here is the *.rb create file:

```
cask 'panconvert' do
  version :latest
  sha256 :no_check

  url "http://sourceforge.net/projects/panconvert/files/latest/download?source=files"
  appcast 'https://github.com/apaeffgen/PanConvert/blob/master/docs/changelog.md'
      checkpoint: 'e2333a9cd663739863c8306193960401977aaa88'
  name 'PanConvert'
  homepage 'http://panconvert.sourceforge.net'
  license :gpl
  
  app 'PanConvert-v#{version}.app'
end
```

### Description of issue
Here is the output of 

`
$ brew cask install pan convert
`

```
brew cask install panconvert
Error: /usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/source/path_base.rb:40: syntax error, unexpected ':', expecting keyword_end
      checkpoint: 'e2333a9cd663739863c8306193960401977aaa88'
                 ^ while loading '/usr/local/Library/Taps/caskroom/homebrew-cask/Casks/panconvert.rb'
  Most likely, this means you have an outdated version of homebrew-cask. Please run:

      brew uninstall --force brew-cask; brew untap phinze/cask; brew update; brew cleanup; brew cask cleanup

  If this doesn’t fix the problem, please report this bug:

      https://github.com/caskroom/homebrew-cask#reporting-bugs

/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/source/path_base.rb:37:in `rescue in load_cask'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/source/path_base.rb:34:in `load_cask'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/source/path_base.rb:23:in `load'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/source/tapped.rb:28:in `load'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc.rb:85:in `load'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/install.rb:19:in `block in install_casks'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/install.rb:17:in `each'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/install.rb:17:in `install_casks'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/install.rb:6:in `run'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli.rb:79:in `run_command'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli.rb:117:in `process'
/usr/local/Library/Taps/caskroom/homebrew-cask/cmd/brew-cask.rb:26:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:23:in `require?'
/usr/local/Library/brew.rb:89:in `<main>'
```

### Output of `brew cask <command> --verbose`

```
$ brew cask install panconvert --verbose
Error: /usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/source/path_base.rb:40: syntax error, unexpected ':', expecting keyword_end
      checkpoint: 'e2333a9cd663739863c8306193960401977aaa88'
                 ^ while loading '/usr/local/Library/Taps/caskroom/homebrew-cask/Casks/panconvert.rb'
  Most likely, this means you have an outdated version of homebrew-cask. Please run:

      brew uninstall --force brew-cask; brew untap phinze/cask; brew update; brew cleanup; brew cask cleanup

  If this doesn’t fix the problem, please report this bug:

      https://github.com/caskroom/homebrew-cask#reporting-bugs

/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/source/path_base.rb:37:in `rescue in load_cask'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/source/path_base.rb:34:in `load_cask'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/source/path_base.rb:23:in `load'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/source/tapped.rb:28:in `load'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc.rb:85:in `load'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/install.rb:19:in `block in install_casks'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/install.rb:17:in `each'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/install.rb:17:in `install_casks'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/install.rb:6:in `run'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli.rb:79:in `run_command'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli.rb:117:in `process'
/usr/local/Library/Taps/caskroom/homebrew-cask/cmd/brew-cask.rb:26:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:23:in `require?'
/usr/local/Library/brew.rb:89:in `<main>'
Error: Kernel.exit
```

### Output of `brew doctor`

```
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
    /usr/local/lib/libjags.3.dylib
    /usr/local/lib/libjrmath.0.dylib
    /usr/local/lib/libtcl8.6.dylib
    /usr/local/lib/libtk8.6.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
    /usr/local/include/aspell.h
    /usr/local/include/autosprintf.h
    /usr/local/include/autotrace/autotrace.h
    /usr/local/include/autotrace/exception.h
    /usr/local/include/autotrace/input.h
    /usr/local/include/autotrace/output.h
    /usr/local/include/autotrace/types.h
    /usr/local/include/bitio.h
    /usr/local/include/colorname.h
    /usr/local/include/fakemysql.h
    /usr/local/include/fakepq.h
    /usr/local/include/fakesql.h
    /usr/local/include/fftw3.h
    /usr/local/include/fontforge/autowidth.h
    /usr/local/include/fontforge/baseviews.h
    /usr/local/include/fontforge/basics.h
    /usr/local/include/fontforge/bezctx_ff.h
    /usr/local/include/fontforge/bitmapcontrol.h
    /usr/local/include/fontforge/chardata.h
    /usr/local/include/fontforge/charset.h
    /usr/local/include/fontforge/config.h
    /usr/local/include/fontforge/configure-pfaedit.h
    /usr/local/include/fontforge/dynamic.h
    /usr/local/include/fontforge/edgelist.h
    /usr/local/include/fontforge/edgelist2.h
    /usr/local/include/fontforge/encoding.h
    /usr/local/include/fontforge/fffreetype.h
    /usr/local/include/fontforge/ffpython.h
    /usr/local/include/fontforge/fileutil.h
    /usr/local/include/fontforge/fontforgevw.h
    /usr/local/include/fontforge/fvmetrics.h
    /usr/local/include/fontforge/gdraw.h
    /usr/local/include/fontforge/gfile.h
    /usr/local/include/fontforge/ggadget.h
    /usr/local/include/fontforge/gicons.h
    /usr/local/include/fontforge/gimage.h
    /usr/local/include/fontforge/gio.h
    /usr/local/include/fontforge/gkeysym.h
    /usr/local/include/fontforge/gprogress.h
    /usr/local/include/fontforge/gresource.h
    /usr/local/include/fontforge/groups.h
    /usr/local/include/fontforge/gwidget.h
    /usr/local/include/fontforge/gwwiconv.h
    /usr/local/include/fontforge/import.h
    /usr/local/include/fontforge/intl.h
    /usr/local/include/fontforge/libffstamp.h
    /usr/local/include/fontforge/lookups.h
    /usr/local/include/fontforge/mm.h
    /usr/local/include/fontforge/nonlineartrans.h
    /usr/local/include/fontforge/ofl.h
    /usr/local/include/fontforge/pfaedit.h
    /usr/local/include/fontforge/PfEd.h
    /usr/local/include/fontforge/plugins.h
    /usr/local/include/fontforge/print.h
    /usr/local/include/fontforge/psfont.h
    /usr/local/include/fontforge/savefont.h
    /usr/local/include/fontforge/scriptfuncs.h
    /usr/local/include/fontforge/scripting.h
    /usr/local/include/fontforge/sd.h
    /usr/local/include/fontforge/search.h
    /usr/local/include/fontforge/sfd1.h
    /usr/local/include/fontforge/sflayoutP.h
    /usr/local/include/fontforge/splinefont.h
    /usr/local/include/fontforge/stemdb.h
    /usr/local/include/fontforge/ttf.h
    /usr/local/include/fontforge/ttfinstrs.h
    /usr/local/include/fontforge/uiinterface.h
    /usr/local/include/fontforge/unicoderange.h
    /usr/local/include/fontforge/ustring.h
    /usr/local/include/fontforge/utype.h
    /usr/local/include/freetype2/freetype/config/ftconfig.h
    /usr/local/include/freetype2/freetype/config/ftheader.h
    /usr/local/include/freetype2/freetype/config/ftmodule.h
    /usr/local/include/freetype2/freetype/config/ftoption.h
    /usr/local/include/freetype2/freetype/config/ftstdlib.h
    /usr/local/include/freetype2/freetype/freetype.h
    /usr/local/include/freetype2/freetype/ftbbox.h
    /usr/local/include/freetype2/freetype/ftbdf.h
    /usr/local/include/freetype2/freetype/ftbitmap.h
    /usr/local/include/freetype2/freetype/ftcache.h
    /usr/local/include/freetype2/freetype/ftchapters.h
    /usr/local/include/freetype2/freetype/fterrdef.h
    /usr/local/include/freetype2/freetype/fterrors.h
    /usr/local/include/freetype2/freetype/ftgasp.h
    /usr/local/include/freetype2/freetype/ftglyph.h
    /usr/local/include/freetype2/freetype/ftgxval.h
    /usr/local/include/freetype2/freetype/ftgzip.h
    /usr/local/include/freetype2/freetype/ftimage.h
    /usr/local/include/freetype2/freetype/ftincrem.h
    /usr/local/include/freetype2/freetype/ftlcdfil.h
    /usr/local/include/freetype2/freetype/ftlist.h
    /usr/local/include/freetype2/freetype/ftlzw.h
    /usr/local/include/freetype2/freetype/ftmac.h
    /usr/local/include/freetype2/freetype/ftmm.h
    /usr/local/include/freetype2/freetype/ftmodapi.h
    /usr/local/include/freetype2/freetype/ftmoderr.h
    /usr/local/include/freetype2/freetype/ftotval.h
    /usr/local/include/freetype2/freetype/ftoutln.h
    /usr/local/include/freetype2/freetype/ftpfr.h
    /usr/local/include/freetype2/freetype/ftrender.h
    /usr/local/include/freetype2/freetype/ftsizes.h
    /usr/local/include/freetype2/freetype/ftsnames.h
    /usr/local/include/freetype2/freetype/ftstroke.h
    /usr/local/include/freetype2/freetype/ftsynth.h
    /usr/local/include/freetype2/freetype/ftsystem.h
    /usr/local/include/freetype2/freetype/fttrigon.h
    /usr/local/include/freetype2/freetype/fttypes.h
    /usr/local/include/freetype2/freetype/ftwinfnt.h
    /usr/local/include/freetype2/freetype/ftxf86.h
    /usr/local/include/freetype2/freetype/t1tables.h
    /usr/local/include/freetype2/freetype/ttnameid.h
    /usr/local/include/freetype2/freetype/tttables.h
    /usr/local/include/freetype2/freetype/tttags.h
    /usr/local/include/freetype2/freetype/ttunpat.h
    /usr/local/include/ft2build.h
    /usr/local/include/gettext-po.h
    /usr/local/include/ImageMagick/magick/animate.h
    /usr/local/include/ImageMagick/magick/annotate.h
    /usr/local/include/ImageMagick/magick/api.h
    /usr/local/include/ImageMagick/magick/artifact.h
    /usr/local/include/ImageMagick/magick/blob.h
    /usr/local/include/ImageMagick/magick/cache-view.h
    /usr/local/include/ImageMagick/magick/cache.h
    /usr/local/include/ImageMagick/magick/cipher.h
    /usr/local/include/ImageMagick/magick/client.h
    /usr/local/include/ImageMagick/magick/coder.h
    /usr/local/include/ImageMagick/magick/color.h
    /usr/local/include/ImageMagick/magick/colorspace.h
    /usr/local/include/ImageMagick/magick/compare.h
    /usr/local/include/ImageMagick/magick/composite.h
    /usr/local/include/ImageMagick/magick/compress.h
    /usr/local/include/ImageMagick/magick/configure.h
    /usr/local/include/ImageMagick/magick/constitute.h
    /usr/local/include/ImageMagick/magick/decorate.h
    /usr/local/include/ImageMagick/magick/delegate.h
    /usr/local/include/ImageMagick/magick/deprecate.h
    /usr/local/include/ImageMagick/magick/display.h
    /usr/local/include/ImageMagick/magick/distort.h
    /usr/local/include/ImageMagick/magick/draw.h
    /usr/local/include/ImageMagick/magick/effect.h
    /usr/local/include/ImageMagick/magick/enhance.h
    /usr/local/include/ImageMagick/magick/exception.h
    /usr/local/include/ImageMagick/magick/fx.h
    /usr/local/include/ImageMagick/magick/gem.h
    /usr/local/include/ImageMagick/magick/geometry.h
    /usr/local/include/ImageMagick/magick/hashmap.h
    /usr/local/include/ImageMagick/magick/identify.h
    /usr/local/include/ImageMagick/magick/image.h
    /usr/local/include/ImageMagick/magick/ImageMagick.h
    /usr/local/include/ImageMagick/magick/layer.h
    /usr/local/include/ImageMagick/magick/list.h
    /usr/local/include/ImageMagick/magick/locale_.h
    /usr/local/include/ImageMagick/magick/log.h
    /usr/local/include/ImageMagick/magick/magic.h
    /usr/local/include/ImageMagick/magick/magick-config.h
    /usr/local/include/ImageMagick/magick/magick-type.h
    /usr/local/include/ImageMagick/magick/magick.h
    /usr/local/include/ImageMagick/magick/MagickCore.h
    /usr/local/include/ImageMagick/magick/matrix.h
    /usr/local/include/ImageMagick/magick/memory_.h
    /usr/local/include/ImageMagick/magick/methods.h
    /usr/local/include/ImageMagick/magick/mime.h
    /usr/local/include/ImageMagick/magick/module.h
    /usr/local/include/ImageMagick/magick/monitor.h
    /usr/local/include/ImageMagick/magick/montage.h
    /usr/local/include/ImageMagick/magick/option.h
    /usr/local/include/ImageMagick/magick/paint.h
    /usr/local/include/ImageMagick/magick/pixel.h
    /usr/local/include/ImageMagick/magick/prepress.h
    /usr/local/include/ImageMagick/magick/PreRvIcccm.h
    /usr/local/include/ImageMagick/magick/profile.h
    /usr/local/include/ImageMagick/magick/property.h
    /usr/local/include/ImageMagick/magick/quantize.h
    /usr/local/include/ImageMagick/magick/quantum.h
    /usr/local/include/ImageMagick/magick/random_.h
    /usr/local/include/ImageMagick/magick/registry.h
    /usr/local/include/ImageMagick/magick/resample.h
    /usr/local/include/ImageMagick/magick/resize.h
    /usr/local/include/ImageMagick/magick/resource_.h
    /usr/local/include/ImageMagick/magick/segment.h
    /usr/local/include/ImageMagick/magick/semaphore.h
    /usr/local/include/ImageMagick/magick/shear.h
    /usr/local/include/ImageMagick/magick/signature.h
    /usr/local/include/ImageMagick/magick/splay-tree.h
    /usr/local/include/ImageMagick/magick/statistic.h
    /usr/local/include/ImageMagick/magick/stream.h
    /usr/local/include/ImageMagick/magick/string_.h
    /usr/local/include/ImageMagick/magick/threshold.h
    /usr/local/include/ImageMagick/magick/timer.h
    /usr/local/include/ImageMagick/magick/token.h
    /usr/local/include/ImageMagick/magick/transform.h
    /usr/local/include/ImageMagick/magick/type.h
    /usr/local/include/ImageMagick/magick/utility.h
    /usr/local/include/ImageMagick/magick/version.h
    /usr/local/include/ImageMagick/magick/widget.h
    /usr/local/include/ImageMagick/magick/xml-tree.h
    /usr/local/include/ImageMagick/magick/xwindow.h
    /usr/local/include/ImageMagick/Magick++/Blob.h
    /usr/local/include/ImageMagick/Magick++/CoderInfo.h
    /usr/local/include/ImageMagick/Magick++/Color.h
    /usr/local/include/ImageMagick/Magick++/Drawable.h
    /usr/local/include/ImageMagick/Magick++/Exception.h
    /usr/local/include/ImageMagick/Magick++/Geometry.h
    /usr/local/include/ImageMagick/Magick++/Image.h
    /usr/local/include/ImageMagick/Magick++/Include.h
    /usr/local/include/ImageMagick/Magick++/Montage.h
    /usr/local/include/ImageMagick/Magick++/Pixels.h
    /usr/local/include/ImageMagick/Magick++/STL.h
    /usr/local/include/ImageMagick/Magick++/TypeMetric.h
    /usr/local/include/ImageMagick/Magick++.h
    /usr/local/include/ImageMagick/wand/animate.h
    /usr/local/include/ImageMagick/wand/compare.h
    /usr/local/include/ImageMagick/wand/composite.h
    /usr/local/include/ImageMagick/wand/conjure.h
    /usr/local/include/ImageMagick/wand/convert.h
    /usr/local/include/ImageMagick/wand/deprecate.h
    /usr/local/include/ImageMagick/wand/display.h
    /usr/local/include/ImageMagick/wand/drawing-wand.h
    /usr/local/include/ImageMagick/wand/identify.h
    /usr/local/include/ImageMagick/wand/import.h
    /usr/local/include/ImageMagick/wand/magick-image.h
    /usr/local/include/ImageMagick/wand/magick-property.h
    /usr/local/include/ImageMagick/wand/magick-wand.h
    /usr/local/include/ImageMagick/wand/magick_wand.h
    /usr/local/include/ImageMagick/wand/MagickWand.h
    /usr/local/include/ImageMagick/wand/mogrify.h
    /usr/local/include/ImageMagick/wand/montage.h
    /usr/local/include/ImageMagick/wand/pixel-iterator.h
    /usr/local/include/ImageMagick/wand/pixel-wand.h
    /usr/local/include/ImageMagick/wand/stream.h
    /usr/local/include/itcl.h
    /usr/local/include/itcl2TclOO.h
    /usr/local/include/itclDecls.h
    /usr/local/include/itclInt.h
    /usr/local/include/itclIntDecls.h
    /usr/local/include/itclMigrate2TclCore.h
    /usr/local/include/itclTclIntStubsFcn.h
    /usr/local/include/JAGS/compiler/Compiler.h
    /usr/local/include/JAGS/compiler/ConstantFactory.h
    /usr/local/include/JAGS/compiler/Counter.h
    /usr/local/include/JAGS/compiler/CounterTab.h
    /usr/local/include/JAGS/compiler/LogicalFactory.h
    /usr/local/include/JAGS/compiler/MixtureFactory.h
    /usr/local/include/JAGS/compiler/NodeFactory.h
    /usr/local/include/JAGS/compiler/ObsFuncTab.h
    /usr/local/include/JAGS/compiler/ParseTree.h
    /usr/local/include/JAGS/Console.h
    /usr/local/include/JAGS/distribution/ArrayDist.h
    /usr/local/include/JAGS/distribution/DistError.h
    /usr/local/include/JAGS/distribution/DistPtr.h
    /usr/local/include/JAGS/distribution/Distribution.h
    /usr/local/include/JAGS/distribution/DistScalar.h
    /usr/local/include/JAGS/distribution/DistScalarRmath.h
    /usr/local/include/JAGS/distribution/DistTab.h
    /usr/local/include/JAGS/distribution/RmathRNG.h
    /usr/local/include/JAGS/distribution/RNG.h
    /usr/local/include/JAGS/distribution/RNGFactory.h
    /usr/local/include/JAGS/distribution/ScalarDist.h
    /usr/local/include/JAGS/distribution/VectorDist.h
    /usr/local/include/JAGS/function/ArrayFunction.h
    /usr/local/include/JAGS/function/FuncError.h
    /usr/local/include/JAGS/function/FuncTab.h
    /usr/local/include/JAGS/function/Function.h
    /usr/local/include/JAGS/function/FunctionPtr.h
    /usr/local/include/JAGS/function/InverseLinkFunc.h
    /usr/local/include/JAGS/function/LinkFunction.h
    /usr/local/include/JAGS/function/ScalarFunc.h
    /usr/local/include/JAGS/function/ScalarFunction.h
    /usr/local/include/JAGS/function/VectorFunction.h
    /usr/local/include/JAGS/graph/AggNode.h
    /usr/local/include/JAGS/graph/ArrayLogicalNode.h
    /usr/local/include/JAGS/graph/ArrayStochasticNode.h
    /usr/local/include/JAGS/graph/ConstantNode.h
    /usr/local/include/JAGS/graph/DeterministicNode.h
    /usr/local/include/JAGS/graph/DevianceNode.h
    /usr/local/include/JAGS/graph/Graph.h
    /usr/local/include/JAGS/graph/GraphMarks.h
    /usr/local/include/JAGS/graph/LinkNode.h
    /usr/local/include/JAGS/graph/LogicalNode.h
    /usr/local/include/JAGS/graph/MixtureNode.h
    /usr/local/include/JAGS/graph/Node.h
    /usr/local/include/JAGS/graph/NodeError.h
    /usr/local/include/JAGS/graph/ScalarLogicalNode.h
    /usr/local/include/JAGS/graph/ScalarStochasticNode.h
    /usr/local/include/JAGS/graph/StochasticNode.h
    /usr/local/include/JAGS/graph/VectorLogicalNode.h
    /usr/local/include/JAGS/graph/VectorStochasticNode.h
    /usr/local/include/JAGS/graph/VSLogicalNode.h
    /usr/local/include/JAGS/JRmath.h
    /usr/local/include/JAGS/model/BUGSModel.h
    /usr/local/include/JAGS/model/Model.h
    /usr/local/include/JAGS/model/Monitor.h
    /usr/local/include/JAGS/model/MonitorControl.h
    /usr/local/include/JAGS/model/MonitorFactory.h
    /usr/local/include/JAGS/model/MonitorInfo.h
    /usr/local/include/JAGS/model/NodeArray.h
    /usr/local/include/JAGS/model/SymTab.h
    /usr/local/include/JAGS/module/ModuleError.h
    /usr/local/include/JAGS/Module.h
    /usr/local/include/JAGS/rng/RmathRNG.h
    /usr/local/include/JAGS/rng/RNG.h
    /usr/local/include/JAGS/rng/RNGFactory.h
    /usr/local/include/JAGS/rng/TruncatedNormal.h
    /usr/local/include/JAGS/sampler/DensityMethod.h
    /usr/local/include/JAGS/sampler/DensitySampler.h
    /usr/local/include/JAGS/sampler/GraphView.h
    /usr/local/include/JAGS/sampler/Linear.h
    /usr/local/include/JAGS/sampler/Metropolis.h
    /usr/local/include/JAGS/sampler/ParallelSampler.h
    /usr/local/include/JAGS/sampler/RWMetropolis.h
    /usr/local/include/JAGS/sampler/SampleMethod.h
    /usr/local/include/JAGS/sampler/Sampler.h
    /usr/local/include/JAGS/sampler/SamplerFactory.h
    /usr/local/include/JAGS/sampler/SingletonFactory.h
    /usr/local/include/JAGS/sampler/Slicer.h
    /usr/local/include/JAGS/sampler/StepAdapter.h
    /usr/local/include/JAGS/sampler/TemperedMetropolis.h
    /usr/local/include/JAGS/sarray/Range.h
    /usr/local/include/JAGS/sarray/RangeIterator.h
    /usr/local/include/JAGS/sarray/SArray.h
    /usr/local/include/JAGS/util/dim.h
    /usr/local/include/JAGS/util/integer.h
    /usr/local/include/JAGS/util/logical.h
    /usr/local/include/JAGS/util/nainf.h
    /usr/local/include/JAGS/version.h
    /usr/local/include/libpng12/png.h
    /usr/local/include/libpng12/pngconf.h
    /usr/local/include/libwmf/gd/gd.h
    /usr/local/include/libwmf/gd/gd_clip.h
    /usr/local/include/libwmf/gd/gd_io.h
    /usr/local/include/libwmf/gd/gdcache.h
    /usr/local/include/libwmf/gd/gdfontg.h
    /usr/local/include/libwmf/gd/gdfontl.h
    /usr/local/include/libwmf/gd/gdfontmb.h
    /usr/local/include/libwmf/gd/gdfonts.h
    /usr/local/include/libwmf/gd/gdfontt.h
    /usr/local/include/mallocvar.h
    /usr/local/include/mysqlStubs.h
    /usr/local/include/nstring.h
    /usr/local/include/odbcStubs.h
    /usr/local/include/pam.h
    /usr/local/include/pammap.h
    /usr/local/include/pbm.h
    /usr/local/include/pbmfont.h
    /usr/local/include/pgm.h
    /usr/local/include/pm.h
    /usr/local/include/pm_config.h
    /usr/local/include/pm_gamma.h
    /usr/local/include/pm_system.h
    /usr/local/include/pnm.h
    /usr/local/include/ppm.h
    /usr/local/include/ppmcmap.h
    /usr/local/include/ppmfloyd.h
    /usr/local/include/pqStubs.h
    /usr/local/include/pspell/pspell.h
    /usr/local/include/shhopt.h
    /usr/local/include/tcl.h
    /usr/local/include/tclDecls.h
    /usr/local/include/tclOO.h
    /usr/local/include/tclOODecls.h
    /usr/local/include/tclPlatDecls.h
    /usr/local/include/tclThread.h
    /usr/local/include/tclTomMath.h
    /usr/local/include/tclTomMathDecls.h
    /usr/local/include/tdbc.h
    /usr/local/include/tdbcDecls.h
    /usr/local/include/tdbcInt.h
    /usr/local/include/tk.h
    /usr/local/include/tkDecls.h
    /usr/local/include/tkPlatDecls.h
    /usr/local/include/uninameslist.h

Warning: Unbrewed .la files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .la files:
    /usr/local/lib/libaspell.la
    /usr/local/lib/libasprintf.la
    /usr/local/lib/libautotrace.la
    /usr/local/lib/libfftw3.la
    /usr/local/lib/libfontconfig.la
    /usr/local/lib/libfontforge.la
    /usr/local/lib/libfreetype.la
    /usr/local/lib/libgdraw.la
    /usr/local/lib/libgettextlib.la
    /usr/local/lib/libgettextpo.la
    /usr/local/lib/libgettextsrc.la
    /usr/local/lib/libgfortran.la
    /usr/local/lib/libgioftp.la
    /usr/local/lib/libgunicode.la
    /usr/local/lib/libgutils.la
    /usr/local/lib/libintl.la
    /usr/local/lib/libjags.la
    /usr/local/lib/libjrmath.la
    /usr/local/lib/libMagick++.la
    /usr/local/lib/libMagickCore.la
    /usr/local/lib/libMagickWand.la
    /usr/local/lib/libpspell.la
    /usr/local/lib/libsamplerate.la
    /usr/local/lib/libsvn_client-1.la
    /usr/local/lib/libsvn_delta-1.la
    /usr/local/lib/libsvn_diff-1.la
    /usr/local/lib/libsvn_fs-1.la
    /usr/local/lib/libsvn_fs_fs-1.la
    /usr/local/lib/libsvn_ra-1.la
    /usr/local/lib/libsvn_ra_local-1.la
    /usr/local/lib/libsvn_ra_svn-1.la
    /usr/local/lib/libsvn_repos-1.la
    /usr/local/lib/libsvn_subr-1.la
    /usr/local/lib/libsvn_wc-1.la
    /usr/local/lib/libuninameslist-fr.la
    /usr/local/lib/libuninameslist.la
    /usr/local/lib/libwmf.la
    /usr/local/lib/libwmflite.la

Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .pc files:
    /usr/local/lib/pkgconfig/autotrace.pc
    /usr/local/lib/pkgconfig/fftw3.pc
    /usr/local/lib/pkgconfig/fontforge.pc
    /usr/local/lib/pkgconfig/jags.pc
    /usr/local/lib/pkgconfig/libpng12.pc
    /usr/local/lib/pkgconfig/tcl.pc
    /usr/local/lib/pkgconfig/tk.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
    /usr/local/lib/libasprintf.a
    /usr/local/lib/libautotrace.a
    /usr/local/lib/libfftw3.a
    /usr/local/lib/libfontconfig.a
    /usr/local/lib/libgettextpo.a
    /usr/local/lib/libgfortran.a
    /usr/local/lib/libintl.a
    /usr/local/lib/libMagick++.a
    /usr/local/lib/libMagickCore.a
    /usr/local/lib/libMagickWand.a
    /usr/local/lib/libnetpbm.a
    /usr/local/lib/libpng12.a
    /usr/local/lib/libsamplerate.a
    /usr/local/lib/libtclstub8.4.a
    /usr/local/lib/libtclstub8.5.a
    /usr/local/lib/libtclstub8.6.a
    /usr/local/lib/libtkstub8.4.a
    /usr/local/lib/libtkstub8.5.a
    /usr/local/lib/libtkstub8.6.a
    /usr/local/lib/libuninameslist-fr.a
    /usr/local/lib/libuninameslist.a
    /usr/local/lib/libwmf.a
    /usr/local/lib/libwmflite.a
```

### Output of `brew cask doctor`

```
$ brew cask doctor
==> OS X Release:
10.9
==> OS X Release with Patchlevel:
10.9.5
==> Hardware Architecture:
intel-64
==> Ruby Version:
2.0.0-p481
==> Ruby Path:
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
==> Homebrew Version:
Homebrew 0.9.5 (git revision 7d3a0; last commit 2016-01-28)
==> Homebrew Executable Path:
/usr/local/bin/brew
==> Homebrew Cellar Path:
/usr/local/Cellar
==> Homebrew Repository Path:
/usr/local
==> Homebrew Origin:
https://github.com/Homebrew/homebrew.git
==> Homebrew-cask Version:
0.60.0 (git revision 22e098; last commit 2 hours ago)
==> Homebrew-cask Install Location:
<NONE>
==> Homebrew-cask Staging Location:
/opt/homebrew-cask/Caskroom
==> Homebrew-cask Cached Downloads:
/Library/Caches/Homebrew
/Library/Caches/Homebrew/Casks
0 files, 0B
==> Homebrew-cask Default Tap Path:
/usr/local/Library/Taps/caskroom/homebrew-cask
==> Homebrew-cask Alternate Cask Taps:
<NONE>
==> Homebrew-cask Default Tap Cask Count:
2956
==> Contents of $LOAD_PATH:
/usr/local/Library/Taps/caskroom/homebrew-cask/lib
/usr/local/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin13
/Library/Ruby/Site/2.0.0/universal-darwin13
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin13
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin13
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin13
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin13
==> Contents of $RUBYLIB Environment Variable:
<NONE>
==> Contents of $RUBYOPT Environment Variable:
<NONE>
==> Contents of $RUBYPATH Environment Variable:
<NONE>
==> Contents of $RBENV_VERSION Environment Variable:
<NONE>
==> Contents of $CHRUBY_VERSION Environment Variable:
<NONE>
==> Contents of $GEM_HOME Environment Variable:
<NONE>
==> Contents of $GEM_PATH Environment Variable:
<NONE>
==> Contents of $BUNDLE_PATH Environment Variable:
<NONE>
==> Contents of $PATH Environment Variable:
PATH="/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/MacGPG2/bin:/Library/TeX/texbin:/usr/local/Library/Taps/caskroom/homebrew-cask/cmd:/usr/local/Library/ENV/scm"
==> Contents of $SHELL Environment Variable:
SHELL="/bin/bash"
==> Contents of Locale Environment Variables:
LANG="en_US.UTF-8"
==> Running As Privileged User:
No
```

**Comment by jawshooah** [comment]
You're missing a comma at the end of the `appcast` line.

Also, in the future, please fill in the issue title template. We'd rather you didn't leave it at just "Bug Report: " :wink:
