### ISSUE TITLE
Bug report: programmer-dvorak - Permission denied - /System/Library/Caches/com.apple.IntlDataCache.le

### ISSUE THREAD

**Issue by GabLeRoux** [caskroom/homebrew-cask#19069]
### Description of issue

I want to try `programmer-dvorak` and brew cask won't let me do this. (maybe it's a good thing ahah)

I searched for dvorak, maybe #4409 is related.

```
ls -la /System/Library/Caches/com.apple.IntlDataCache.le
-rw-r--r--  1 root  wheel  8820 15 déc 00:26 /System/Library/Caches/com.apple.IntlDataCache.le
```

### Output of `brew cask programmer-dvorak --verbose`

```
==> Downloading http://www.kaufmann.no/downloads/macos/ProgrammerDvorak-1_2b9.pkg.zip
/usr/bin/curl -fLA Homebrew-cask v0.51+ (Ruby 2.0.0-645) http://www.kaufmann.no/downloads/macos/ProgrammerDvorak-1_2b9.pkg.zip -C 0 -o /Library/Caches/Homebrew/programmer-dvorak-1.2b9.zip.incomplete
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 12226  100 12226    0     0  27009      0 --:--:-- --:--:-- --:--:-- 27048
==> Verifying checksum for Cask programmer-dvorak
==> Running installer for programmer-dvorak; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
==> installer: Package name is Programmer Dvorak
==> installer: Upgrading at base path /
==> installer:PHASE:Préparation à l’installation…
==> installer:PHASE:Préparation du disque…
==> installer:PHASE:Préparation de Programmer Dvorak…
==> installer:PHASE:Attente de la fin des autres installations…
==> installer:PHASE:Configuration de l’installation…
==> installer:STATUS:
==> installer:%2.229250
==> installer:PHASE:Validation des paquets…
==> installer:%97.750000
==> installer:STATUS:
==> installer:PHASE:Fin de l’installation…
==> installer:STATUS:
==> installer:%100.000000
==> installer:PHASE:Le logiciel a été installé avec succès.
==> installer: The upgrade was successful.
Error: Permission denied - /System/Library/Caches/com.apple.IntlDataCache.le
  Most likely, this means you have an outdated version of homebrew-cask. Please run:

      brew uninstall --force brew-cask; brew untap phinze/cask; brew update; brew cleanup; brew cask cleanup

  If this doesn’t fix the problem, please report this bug:

      https://github.com/caskroom/homebrew-cask#reporting-bugs

/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/source/path_base.rb:48:in `delete'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/source/path_base.rb:48:in `block (2 levels) in load_cask'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/artifact/postflight_block.rb:9:in `instance_eval'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/artifact/postflight_block.rb:9:in `block in install_phase'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/set.rb:232:in `each_key'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/set.rb:232:in `each'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/artifact/postflight_block.rb:8:in `install_phase'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/installer.rb:124:in `block in install_artifacts'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/installer.rb:122:in `each'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/installer.rb:122:in `install_artifacts'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/installer.rb:71:in `install'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/install.rb:20:in `block in install_casks'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/install.rb:17:in `each'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/install.rb:17:in `install_casks'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/install.rb:6:in `run'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli.rb:83:in `run_command'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli.rb:121:in `process'
/usr/local/Library/Taps/caskroom/homebrew-cask/cmd/brew-cask.rb:26:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:21:in `require?'
/usr/local/Library/brew.rb:89:in `<main>'
Error: Kernel.exit
```

### Output of `brew doctor`

```
Your system is ready to brew.
```

### Output of `brew cask doctor`

```
==> OS X Release:
10.11
==> OS X Release with Patchlevel:
10.11.2
==> Hardware Architecture:
intel-64
==> Ruby Version:
2.0.0-p645
==> Ruby Path:
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
==> Homebrew Version:
Homebrew 0.9.5 (git revision e900; last commit 2016-02-19)
==> Homebrew Executable Path:
/usr/local/bin/brew
==> Homebrew Cellar Path:
/usr/local/Cellar
==> Homebrew Repository Path:
/usr/local
==> Homebrew Origin:
https://github.com/Homebrew/homebrew
==> Homebrew-cask Version:
0.60.0 (git revision 9131a; last commit 54 minutes ago)
==> Homebrew-cask Install Location:
<NONE>
==> Homebrew-cask Staging Location:
/opt/homebrew-cask/Caskroom
==> Homebrew-cask Cached Downloads:
/Library/Caches/Homebrew
/Library/Caches/Homebrew/Casks
2 files, 23.9K (warning: run "brew cask cleanup")
==> Homebrew-cask Default Tap Path:
/usr/local/Library/Taps/caskroom/homebrew-cask
==> Homebrew-cask Alternate Cask Taps:
/usr/local/Library/Taps/caskroom/homebrew-versions
/usr/local/Library/Taps/gableroux/homebrew-cask
==> Homebrew-cask Default Tap Cask Count:
2977
==> Contents of $LOAD_PATH:
/usr/local/Library/Taps/caskroom/homebrew-cask/lib
/usr/local/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin15
/Library/Ruby/Site/2.0.0/universal-darwin15
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15
==> Contents of $RUBYLIB Environment Variable:
<NONE>
==> Contents of $RUBYOPT Environment Variable:
<NONE>
==> Contents of $RUBYPATH Environment Variable:
<NONE>
==> Contents of $RBENV_VERSION Environment Variable:
<NONE>
==> Contents of $CHRUBY_VERSION Environment Variable:
<NONE>
==> Contents of $GEM_HOME Environment Variable:
<NONE>
==> Contents of $GEM_PATH Environment Variable:
<NONE>
==> Contents of $BUNDLE_PATH Environment Variable:
<NONE>
==> Contents of $PATH Environment Variable:
PATH="/usr/local/sbin:/Users/gableroux/go//bin:/Users/gableroux/local/lib/node_modules:/Users/gableroux/.gem/bin:/Users/gableroux/.composer/vendor/bin:/Users/gableroux/perl5/bin:/Users/gableroux/bin:/usr/local/sbin:/Users/gableroux/local/bin:/Users/gableroux/bin:/Developer/android-sdk/platform-tools:/Users/gableroux/Library/Android/sdk/platform-tools:/Users/gableroux/Library/Android/sdk/build-tools/21.1.2:/usr/local/opt/ruby/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/gableroux/.composer/vendor/bin:/Users/gableroux/.rvm/bin:/usr/local/Library/Taps/caskroom/homebrew-cask/cmd:/usr/local/Library/ENV/scm"
==> Contents of $SHELL Environment Variable:
SHELL="/bin/zsh"
==> Contents of Locale Environment Variables:
LANG="fr_CA.UTF-8"
LC_CTYPE="fr_CA.UTF-8"
==> Running As Privileged User:
No
```

**Comment by adidalal** [comment]
Sorry for the delay.

Unfortunately, can't even seem to get the Cask working, and it looks like a sudo issue.You can try sudo-ing something right before running the cask (https://github.com/caskroom/homebrew-cask/issues/19180 may be of interest) or installing manually.
If you manually install and clear out the cache (see the website), things should work.

Thanks for the report!
