### ISSUE TITLE
Bug report: brew cask

### ISSUE THREAD

**Issue by MaximDaBoss** [caskroom/homebrew-cask#19789]
(Remember to run `brew update; brew cleanup; brew cask cleanup` before reporting your issue. It usually fixes things!)

### Description of issue
tried doing brew cask cleanup, this popped up

### Output of `brew cask <command> --verbose`

```
brew cask cleanup
==> Tapping caskroom/cask
Cloning into '/usr/local/Library/Taps/caskroom/homebrew-cask'...
remote: Counting objects: 3510, done.
remote: Compressing objects: 100% (3455/3455), done.
remote: Total 3510 (delta 55), reused 747 (delta 33), pack-reused 0
Receiving objects: 100% (3510/3510), 5.91 MiB | 380.00 KiB/s, done.
Resolving deltas: 100% (55/55), done.
Checking connectivity... done.
Checking out files: 100% (3456/3456), done.
Tapped 1 formula (3,476 files, 13.4M)
Error: No such file or directory - /Library/Caches/Homebrew/Casks
  Most likely, this means you have an outdated version of homebrew-cask. Please run:

      brew uninstall --force brew-cask; brew untap phinze/cask; brew update; brew cleanup; brew cask cleanup

  If this doesn’t fix the problem, please report this bug:

      https://github.com/caskroom/homebrew-cask#reporting-bugs

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:425:in `open'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:425:in `foreach'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:425:in `children'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/cleanup.rb:33:in `cache_symlinks'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/cleanup.rb:41:in `cache_incompletes'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/cleanup.rb:70:in `all_cache_files'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/cleanup.rb:74:in `disk_cleanup_size'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/cleanup.rb:10:in `run'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli.rb:83:in `run_command'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli.rb:121:in `process'
/usr/local/Library/Taps/caskroom/homebrew-cask/cmd/brew-cask.rb:26:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:21:in `require?'
/usr/local/Library/brew.rb:89:in `<main>'

```

### Output of `brew doctor`

```
Your system is ready to brew.
```

### Output of `brew cask doctor`

```
brew cask doctor
==> OS X Release:
10.11
==> OS X Release with Patchlevel:
10.11.3
==> Hardware Architecture:
intel-64
==> Ruby Version:
2.0.0-p645
==> Ruby Path:
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
==> Homebrew Version:
Homebrew 0.9.5 (git revision 4b30; last commit 2016-03-12)
==> Homebrew Executable Path:
/usr/local/bin/brew
==> Homebrew Cellar Path:
/usr/local/Cellar
==> Homebrew Repository Path:
/usr/local
==> Homebrew Origin:
https://github.com/Homebrew/homebrew
==> Homebrew-cask Version:
0.60.0 (git revision 67ce; last commit 3 hours ago)
==> Homebrew-cask Install Location:
<NONE>
==> Homebrew-cask Staging Location:
/opt/homebrew-cask/Caskroom
Error: No such file or directory - /Library/Caches/Homebrew/Casks
  Most likely, this means you have an outdated version of homebrew-cask. Please run:

      brew uninstall --force brew-cask; brew untap phinze/cask; brew update; brew cleanup; brew cask cleanup

  If this doesn’t fix the problem, please report this bug:

      https://github.com/caskroom/homebrew-cask#reporting-bugs

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:425:in `open'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:425:in `foreach'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:425:in `children'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/cleanup.rb:33:in `cache_symlinks'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/cleanup.rb:41:in `cache_incompletes'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/cleanup.rb:70:in `all_cache_files'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/doctor.rb:220:in `render_cached_downloads'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/doctor.rb:17:in `run'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli.rb:83:in `run_command'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli.rb:121:in `process'
/usr/local/Library/Taps/caskroom/homebrew-cask/cmd/brew-cask.rb:26:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:21:in `require?'
/usr/local/Library/brew.rb:89:in `<main>'

```

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/issues/18606
