### ISSUE TITLE
Bug report: uninstall delete: not passing audit

### ISSUE THREAD

**Issue by liljenstolpe** [caskroom/homebrew-cask#19877]
### Description of issue

Trying to do an audit of a new cask is failing when I call uninstall delete:

### Output of `brew cask <command> --verbose`

```
brew cask audit --verbose chronycontrol
Error: /usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/source/path_base.rb:48: syntax error, unexpected ':', expecting keyword_end
            delete: [ '/var/db/chrony',
                   ^ while loading '/usr/local/Library/Taps/caskroom/homebrew-cask/Casks/chronycontrol.rb'
  Most likely, this means you have an outdated version of homebrew-cask. Please run:

      brew uninstall --force brew-cask; brew untap phinze/cask; brew update; brew cleanup; brew cask cleanup

  If this doesn’t fix the problem, please report this bug:

      https://github.com/caskroom/homebrew-cask#reporting-bugs

/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/source/path_base.rb:37:in `rescue in load_cask'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/source/path_base.rb:34:in `load_cask'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/source/path_base.rb:23:in `load'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/source/tapped.rb:28:in `load'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc.rb:82:in `load'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/audit.rb:42:in `block in casks_to_audit'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/audit.rb:42:in `map'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/audit.rb:42:in `casks_to_audit'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/audit.rb:23:in `run'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/audit.rb:7:in `run'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli.rb:83:in `run_command'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli.rb:121:in `process'
/usr/local/Library/Taps/caskroom/homebrew-cask/cmd/brew-cask.rb:26:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:21:in `require?'
/usr/local/Library/brew.rb:89:in `<main>'
Error: Kernel.exit
```

### Output of `brew doctor`

```
brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Some directories in /usr/local/share/man aren't writable.
This can happen if you "sudo make install" software that isn't managed
by Homebrew. If a brew tries to add locale information to one of these
directories, then the install will fail during the link step.

You should probably `sudo chown -R $(whoami)` them:
    /usr/local/share/man/de
    /usr/local/share/man/de/man1

Warning: A .pydistutils.cfg file was found in $HOME, which may cause Python
builds to fail. See:
  https://bugs.python.org/issue6138
  https://bugs.python.org/issue4655

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
    dirmngr
    gnupg2
    gpg-agent
```

### Output of `brew cask doctor`

```
brew cask doctor
==> OS X Release:
10.10
==> OS X Release with Patchlevel:
10.10.5
==> Hardware Architecture:
intel-64
==> Ruby Version:
2.0.0-p481
==> Ruby Path:
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
==> Homebrew Version:
Homebrew 0.9.5 (git revision 9eba; last commit 2016-03-16)
==> Homebrew Executable Path:
/usr/local/bin/brew
==> Homebrew Cellar Path:
/usr/local/Cellar
==> Homebrew Repository Path:
/usr/local
==> Homebrew Origin:
https://github.com/Homebrew/homebrew
==> Homebrew-cask Version:
0.60.0 (git revision 4243; last commit 5 hours ago)
==> Homebrew-cask Install Location:
<NONE>
==> Homebrew-cask Staging Location:
/opt/homebrew-cask/Caskroom
==> Homebrew-cask Cached Downloads:
/Library/Caches/Homebrew
/Library/Caches/Homebrew/Casks
0 files, 0B
==> Homebrew-cask Default Tap Path:
/usr/local/Library/Taps/caskroom/homebrew-cask
==> Homebrew-cask Alternate Cask Taps:
/usr/local/Library/Taps/caskroom/homebrew-fonts
==> Homebrew-cask Default Tap Cask Count:
3019
==> Contents of $LOAD_PATH:
/usr/local/Library/Taps/caskroom/homebrew-cask/lib
/usr/local/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin14
/Library/Ruby/Site/2.0.0/universal-darwin14
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin14
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin14
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin14
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin14
==> Contents of $RUBYLIB Environment Variable:
<NONE>
==> Contents of $RUBYOPT Environment Variable:
<NONE>
==> Contents of $RUBYPATH Environment Variable:
<NONE>
==> Contents of $RBENV_VERSION Environment Variable:
<NONE>
==> Contents of $CHRUBY_VERSION Environment Variable:
<NONE>
==> Contents of $GEM_HOME Environment Variable:
<NONE>
==> Contents of $GEM_PATH Environment Variable:
<NONE>
==> Contents of $BUNDLE_PATH Environment Variable:
<NONE>
==> Contents of $PATH Environment Variable:
PATH="//Users/cdl/bin://Users/cdl/gocode/bin:/usr/local/MacGPG2/bin:/usr/local/bin:/usr/texbin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Library/Taps/caskroom/homebrew-cask/cmd:/usr/local/Library/ENV/scm"
==> Contents of $SHELL Environment Variable:
SHELL="/bin/zsh"
==> Contents of Locale Environment Variables:
LANG="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
==> Running As Privileged User:
No
```

**Comment by vitorgalvao** [comment]
Unless you actually post your cask, we can’t help.

**Comment by liljenstolpe** [comment]
Here's the cask.

```
cask 'chronycontrol' do
  version '1.1.2'
  sha256 'b171c2a201f3b9455668d2b283f5a7746b082ef28fcd04cc3aa266302606926c'

  url 'https://www.whatroute.net/software/chronycontrol-1.1.2.zip'
  name 'ChronyControl'
  homepage 'https://whatroute.net/chronycontrol.html'
  license :unknown

  app 'ChronyControl.app'

  uninstall launchctl: [ 'org.tuxfamily.chronyd',
                         'org.tuxfamily.chronyc'
                       ]
            delete: [ '/var/db/chrony',
                      '/Library/LaunchDaemons/org.tuxfamily.chronyd',
                      '/Library/LaunchDaemons/org.tuxfamily.chronyc'
                    ]

  zap delete: '/var/log/chrony'
end
```

**Comment by vitorgalvao** [comment]
You’re missing a comma after the closing brace of `launchctl`.
