### ISSUE TITLE
brew cask list  => Error: undefined method `dumpcask'

### ISSUE THREAD

**Issue by kkdd** [caskroom/homebrew-cask#20600]
Hello,
```brew cask list``` causes the following error:

```
$ brew update
Updated Homebrew from a8be17d to 8e42077.
Updated 2 taps (caskroom/cask, homebrew/core).
 :
 :
$ brew doctor
Your system is ready to brew.
$ brew cask list
Error: undefined method `dumpcask' for #<Array:0x007fb42d8e2ea0>
  Most likely, this means you have an outdated version of homebrew-cask. Please run:

      brew uninstall --force brew-cask; brew untap phinze/cask; brew update; brew cleanup; brew cask cleanup

  If this doesn’t fix the problem, please report this bug:

      https://github.com/caskroom/homebrew-cask#reporting-bugs

/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc.rb:83:in `load'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/scopes.rb:59:in `block in installed'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/scopes.rb:51:in `map'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/scopes.rb:51:in `installed'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/list.rb:53:in `list_installed'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/list.rb:11:in `run'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli.rb:83:in `run_command'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli.rb:121:in `process'
/usr/local/Library/Taps/caskroom/homebrew-cask/cmd/brew-cask.rb:26:in `<top (required)>'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/Library/brew.rb:22:in `require?'
/usr/local/Library/brew.rb:103:in `<main>'
$ 
$ grep dumpcask /usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cask.rb
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cask.rb:  def dumpcask
$ 
$ brew cask doctor
==> OS X Release:
10.11
==> OS X Release with Patchlevel:
10.11.4
==> Hardware Architecture:
intel-64
==> Ruby Version:
2.0.0-p648
==> Ruby Path:
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
==> Homebrew Version:
Homebrew 0.9.9 (git revision 8e4207; last commit 2016-04-17)
Homebrew/homebrew-core (git revision 5700; last commit 2016-04-16)
==> Homebrew Executable Path:
/usr/local/bin/brew
==> Homebrew Cellar Path:
/usr/local/Cellar
==> Homebrew Repository Path:
/usr/local
==> Homebrew Origin:
https://github.com/Homebrew/brew.git
==> Homebrew-cask Version:
0.60.0 (git revision 85fad; last commit 2 hours ago)
==> Homebrew-cask Install Location:
<NONE>
==> Homebrew-cask Staging Location:
/opt/homebrew-cask/Caskroom
==> Homebrew-cask Cached Downloads:
/Library/Caches/Homebrew
/Library/Caches/Homebrew/Casks
0 files, 0B
==> Homebrew-cask Default Tap Path:
/usr/local/Library/Taps/caskroom/homebrew-cask
==> Homebrew-cask Alternate Cask Taps:
<NONE>
==> Homebrew-cask Default Tap Cask Count:
3081
==> Contents of $LOAD_PATH:
/usr/local/Library/Taps/caskroom/homebrew-cask/lib
/usr/local/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin15
/Library/Ruby/Site/2.0.0/universal-darwin15
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15
==> Contents of $RUBYLIB Environment Variable:
<NONE>
==> Contents of $RUBYOPT Environment Variable:
<NONE>
==> Contents of $RUBYPATH Environment Variable:
<NONE>
==> Contents of $RBENV_VERSION Environment Variable:
<NONE>
==> Contents of $CHRUBY_VERSION Environment Variable:
<NONE>
==> Contents of $GEM_HOME Environment Variable:
<NONE>
==> Contents of $GEM_PATH Environment Variable:
<NONE>
==> Contents of $BUNDLE_PATH Environment Variable:
<NONE>
==> Contents of $PATH Environment Variable:
PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/TeX/texbin:/usr/local/sbin:/usr/local/cuda/bin:/usr/local/Library/Taps/caskroom/homebrew-cask/cmd:/usr/local/Library/ENV/scm"
==> Contents of $SHELL Environment Variable:
SHELL="/bin/bash"
==> Contents of Locale Environment Variables:
LANG="ja_JP.UTF-8"
==> Running As Privileged User:
No
$  brew --config
HOMEBREW_VERSION: 0.9.9
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: a8be17df575e829b5bd37927ea5bfc0601cf6f49
Last commit: 17 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 21760af4556e317f89cc327b3a4872ed583f1e42
Core tap last commit: 19 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: 8-core 64-bit haswell
OS X: 10.11.4-x86_64
Xcode: 7.3
CLT: 7.3.0.0.1.1457485338
Clang: 7.3 build 703
X11: 2.7.8 => /opt/X11
System Ruby: 2.0.0-p648
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
% brew tap
caskroom/cask
homebrew/core
homebrew/python
homebrew/science
homebrew/versions
$ brew info brew-cask
caskroom/cask/brew-cask: stable 0.60.1
https://github.com/caskroom/homebrew-cask/
Not installed
From: https://github.com/caskroom/homebrew-cask/blob/master/brew-cask.rb
==> Caveats
You must uninstall this formula. It is no longer needed to stay up to date,
as Homebrew now takes care of that automatically.
$ 
```

**Comment by vitorgalvao** [comment]
Please *always* follow the [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) guide. To do so, edit the top post and then comment after this one so I can check back.

Closing in the meantime, because a number of people never report back and it’s useless to keep the issue open in that case and without all the required information.
