### ISSUE TITLE
`brew cask style` fails because of dependencies on rubocop versions.

### ISSUE THREAD

**Issue by toonetown** [caskroom/homebrew-cask#20806]
When I try to run `brew cask style`, I get the following errors:

```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:2007:in `raise_if_conflicts': Unable to activate rubocop-cask-0.5.0, because rubocop-0.39.0 conflicts with rubocop (~> 0.37.0) (Gem::LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1176:in `activate'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems.rb:186:in `rescue in try_activate'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems.rb:183:in `try_activate'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:132:in `rescue in require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
	from /Users/ntoone/.gem/ruby/2.0.0/gems/rubocop-0.39.0/lib/rubocop/config_loader_resolver.rb:16:in `block in resolve_requires'
	from /Users/ntoone/.gem/ruby/2.0.0/gems/rubocop-0.39.0/lib/rubocop/config_loader_resolver.rb:12:in `each'
	from /Users/ntoone/.gem/ruby/2.0.0/gems/rubocop-0.39.0/lib/rubocop/config_loader_resolver.rb:12:in `resolve_requires'
	from /Users/ntoone/.gem/ruby/2.0.0/gems/rubocop-0.39.0/lib/rubocop/config_loader.rb:39:in `load_file'
	from /Users/ntoone/.gem/ruby/2.0.0/gems/rubocop-0.39.0/lib/rubocop/config_store.rb:24:in `options_config='
	from /Users/ntoone/.gem/ruby/2.0.0/gems/rubocop-0.39.0/lib/rubocop/cli.rb:64:in `act_on_options'
	from /Users/ntoone/.gem/ruby/2.0.0/gems/rubocop-0.39.0/lib/rubocop/cli.rb:25:in `run'
	from /Users/ntoone/.gem/ruby/2.0.0/gems/rubocop-0.39.0/bin/rubocop:14:in `block in <top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/benchmark.rb:296:in `realtime'
	from /Users/ntoone/.gem/ruby/2.0.0/gems/rubocop-0.39.0/bin/rubocop:13:in `<top (required)>'
	from /Users/ntoone/.gem/ruby/2.0.0/bin/rubocop:23:in `load'
	from /Users/ntoone/.gem/ruby/2.0.0/bin/rubocop:23:in `<main>'
Error: style check failed
```

It looks like there is a different dependency between rubocop-cask (which depends on rubocop 37) and what the base home-brew depends upon (rubocop 39).

**Comment by adidalal** [comment]
https://github.com/caskroom/homebrew-cask/pull/20897
