### ISSUE TITLE
bitcoin-core 0.12.1 error "permission denied" at "moving app" stage

### ISSUE THREAD

**Issue by mathiashro** [caskroom/homebrew-cask#22081]
### Description of issue

During cask install of bitcoin-core (0.12.1) I've got following error message:
Error: Permission denied - (/usr/local/Caskroom/bitcoin-core/0.12.1/Bitcoin-Qt.app, /Applications/Bitcoin Core.app)

I've followed the procedures to update / cleanup / doctor.

### Output of `brew cask <command> --verbose`

```
$ brew cask install --debug bitcoin-core
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15/rbconfig.rb:213: warning: Insecure world writable dir /usr/local/sbin in PATH, mode 040777
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15/rbconfig.rb:213: warning: Insecure world writable dir /usr/local/sbin in PATH, mode 040777
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15/rbconfig.rb:213: warning: Insecure world writable dir /usr/local/sbin in PATH, mode 040777
==> Creating directories
==> Loading Cask definitions
==> Translating 'bitcoin-core' into a valid Cask source
==> Testing source class Hbc::Source::URI
==> Testing source class Hbc::Source::PathSlashRequired
==> Testing source class Hbc::Source::TappedQualified
==> Testing source class Hbc::Source::UntappedQualified
==> Testing source class Hbc::Source::Tapped
==> Success! Using source class Hbc::Source::Tapped
==> Resolved Cask URI or file source to '/usr/local/Library/Taps/caskroom/homebrew-cask/Casks/bitcoin-core.rb'
==> Cask instance dumps in YAML:
==> Cask instance toplevel:
--- !ruby/object:Hbc::Cask
token: bitcoin-core
sourcefile_path: !ruby/object:Pathname
  path: /usr/local/Library/Taps/caskroom/homebrew-cask/Casks/bitcoin-core.rb
dsl: !ruby/object:Hbc::DSL
  token: bitcoin-core
  version: !ruby/string:Hbc::DSL::Version
    str: !binary |-
      MC4xMi4x
    raw_version: 0.12.1
  sha256: e1bc86d24dd978d64b511ada68be31057c20789fb9a6a86c40043a32bf77cb05
  url: !ruby/object:Hbc::URL
    uri: !ruby/object:URI::HTTPS
      scheme: https
      user: 
      password: 
      host: bitcoin.org
      port: 443
      path: /bin/bitcoin-core-0.12.1/bitcoin-0.12.1-osx.dmg
      query: 
      opaque: 
      registry: 
      fragment: 
      parser: 
    user_agent: 
    cookies: 
    referer: 
    using: 
    revision: 
    trust_cert: 
    data: 
  name:
  - Bitcoin Core
  homepage: https://bitcoin.org/
  license: !ruby/object:Hbc::DSL::License
    value: :mit
  conflicts_with: !ruby/object:Hbc::DSL::ConflictsWith
    pairs:
      :cask: bitcoin-xt
    cask: bitcoin-xt
  artifacts:
    :app: !ruby/object:Set
      hash:
        ? - Bitcoin-Qt.app
          - :target: Bitcoin Core.app
        : true
    :zap: !ruby/object:Set
      hash:
        ? :delete:
          - ~/Library/Preferences/org.bitcoin.Bitcoin-Qt.plist
        : true
==> Cask instance method 'name':
---
- Bitcoin Core
==> Cask instance method 'homepage':
--- https://bitcoin.org/
...
==> Cask instance method 'url':
--- !ruby/object:Hbc::URL
uri: !ruby/object:URI::HTTPS
  scheme: https
  user: 
  password: 
  host: bitcoin.org
  port: 443
  path: /bin/bitcoin-core-0.12.1/bitcoin-0.12.1-osx.dmg
  query: 
  opaque: 
  registry: 
  fragment: 
  parser: 
user_agent: 
cookies: 
referer: 
using: 
revision: 
trust_cert: 
data: 
==> Cask instance method 'appcast':
--- 
...
==> Cask instance method 'version':
--- !ruby/string:Hbc::DSL::Version
str: !binary |-
  MC4xMi4x
raw_version: 0.12.1
==> Cask instance method 'license':
--- !ruby/object:Hbc::DSL::License
value: :mit
==> Cask instance method 'sha256':
--- e1bc86d24dd978d64b511ada68be31057c20789fb9a6a86c40043a32bf77cb05
...
==> Cask instance method 'artifacts':
---
:app: !ruby/object:Set
  hash:
    ? - Bitcoin-Qt.app
      - :target: Bitcoin Core.app
    : true
:zap: !ruby/object:Set
  hash:
    ? :delete:
      - ~/Library/Preferences/org.bitcoin.Bitcoin-Qt.plist
    : true
==> Cask instance method 'caveats':
--- []
==> Cask instance method 'depends_on':
--- 
...
==> Cask instance method 'conflicts_with':
---
:cask: bitcoin-xt
==> Cask instance method 'container':
--- 
...
==> Cask instance method 'gpg':
--- 
...
==> Cask instance method 'accessibility_access':
--- 
...
==> Cask instance method 'auto_updates':
--- 
...
==> Hbc::Installer.install
==> Printing caveats
==> Downloading
==> Downloading https://bitcoin.org/bin/bitcoin-core-0.12.1/bitcoin-0.12.1-osx.dmg
==> Calling curl with args ["https://bitcoin.org/bin/bitcoin-core-0.12.1/bitcoin-0.12.1-osx.dmg", "-C", "0", "-o", "#<Pathname:/Users/mat/Library/Caches/Homebrew/bitcoin-core-0.12.1.dmg.incomplete>"]
######################################################################## 100,0%
==> Downloaded to -> /Users/mat/Library/Caches/Homebrew/bitcoin-core-0.12.1.dmg
==> Verifying download
==> Determining which verifications to run for Cask bitcoin-core
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask bitcoin-core
==> SHA256 checksums match
==> Extracting primary container
==> Determining which containers to use based on filetype
==> Checking container class Hbc::Container::Pkg
==> Checking container class Hbc::Container::Ttf
==> Checking container class Hbc::Container::Otf
==> Checking container class Hbc::Container::Air
==> Checking container class Hbc::Container::Cab
==> Executing: ["/usr/bin/file", "-Izb", "--", "/Users/mat/Library/Caches/Homebrew/bitcoin-core-0.12.1.dmg"]
==> Checking container class Hbc::Container::Dmg
==> Executing: ["/usr/bin/hdiutil", "imageinfo", "/Users/mat/Library/Caches/Homebrew/bitcoin-core-0.12.1.dmg"]
==> Using container class Hbc::Container::Dmg for /Users/mat/Library/Caches/Homebrew/bitcoin-core-0.12.1.dmg
==> Executing: ["/usr/bin/hdiutil", "mount", "-plist", "-nobrowse", "-readonly", "-noidme", "-mountrandom", "/tmp", "/Users/mat/Library/Caches/Homebrew/bitcoin-core-0.12.1.dmg"]
==> Executing: ["/usr/bin/ditto", "--", "/private/tmp/dmg.tSkTDd", "/usr/local/Caskroom/bitcoin-core/0.12.1"]
==> Executing: ["/usr/sbin/diskutil", "eject", "/private/tmp/dmg.tSkTDd"]
==> Installing artifacts
==> Determining which artifacts are present in Cask bitcoin-core
==> Checking for artifact class Hbc::Artifact::PreflightBlock
==> Checking for artifact class Hbc::Artifact::NestedContainer
==> Checking for artifact class Hbc::Artifact::Installer
==> Checking for artifact class Hbc::Artifact::App
==> Checking for artifact class Hbc::Artifact::Suite
==> Checking for artifact class Hbc::Artifact::Artifact
==> Checking for artifact class Hbc::Artifact::Colorpicker
==> Checking for artifact class Hbc::Artifact::Pkg
==> Checking for artifact class Hbc::Artifact::Prefpane
==> Checking for artifact class Hbc::Artifact::Qlplugin
==> Checking for artifact class Hbc::Artifact::Font
==> Checking for artifact class Hbc::Artifact::Service
==> Checking for artifact class Hbc::Artifact::StageOnly
==> Checking for artifact class Hbc::Artifact::Binary
==> Checking for artifact class Hbc::Artifact::InputMethod
==> Checking for artifact class Hbc::Artifact::InternetPlugin
==> Checking for artifact class Hbc::Artifact::AudioUnitPlugin
==> Checking for artifact class Hbc::Artifact::VstPlugin
==> Checking for artifact class Hbc::Artifact::Vst3Plugin
==> Checking for artifact class Hbc::Artifact::ScreenSaver
==> Checking for artifact class Hbc::Artifact::Uninstall
==> Checking for artifact class Hbc::Artifact::PostflightBlock
==> Checking for artifact class Hbc::Artifact::Zap
==> 2 artifact/s defined
Hbc::Artifact::App
Hbc::Artifact::Zap
==> Installing artifact of class Hbc::Artifact::App
==> Moving App 'Bitcoin-Qt.app' to '/Applications/Bitcoin Core.app'
==> Purging files for version 0.12.1 of Cask bitcoin-core
==> Executing: ["/usr/bin/chflags", "-R", "--", "000", "/usr/local/Caskroom/bitcoin-core/0.12.1"]
==> Executing: ["/bin/chmod", "-R", "--", "u+rwx", "/usr/local/Caskroom/bitcoin-core/0.12.1"]
==> Executing: ["/bin/chmod", "-R", "-N", "/usr/local/Caskroom/bitcoin-core/0.12.1"]
Error: Permission denied - (/usr/local/Caskroom/bitcoin-core/0.12.1/Bitcoin-Qt.app, /Applications/Bitcoin Core.app)
  Most likely, this means you have an outdated version of homebrew-cask. Please run:

      brew uninstall --force brew-cask; brew untap phinze/cask; brew update; brew cleanup; brew cask cleanup

  If this doesn’t fix the problem, please report this bug:

      https://github.com/caskroom/homebrew-cask#reporting-bugs

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:519:in `rename'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:519:in `block in mv'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1558:in `block in fu_each_src_dest'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1574:in `fu_each_src_dest0'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1556:in `fu_each_src_dest'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:508:in `mv'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/artifact/moved.rb:50:in `move'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/artifact/moved.rb:26:in `block in install_phase'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/artifact/moved.rb:43:in `block in each_artifact'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/artifact/moved.rb:42:in `each'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/artifact/moved.rb:42:in `each_artifact'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/artifact/moved.rb:22:in `install_phase'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/installer.rb:129:in `block in install_artifacts'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/installer.rb:126:in `each'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/installer.rb:126:in `install_artifacts'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/installer.rb:75:in `install'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/install.rb:21:in `block in install_casks'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/install.rb:18:in `each'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/install.rb:18:in `install_casks'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/install.rb:7:in `run'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli.rb:83:in `run_command'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli.rb:121:in `process'
/usr/local/Library/Taps/caskroom/homebrew-cask/cmd/brew-cask.rb:26:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:22:in `require?'
/usr/local/Library/brew.rb:93:in `<main>'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli.rb:132:in `exit'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli.rb:132:in `rescue in process'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli.rb:117:in `process'
/usr/local/Library/Taps/caskroom/homebrew-cask/cmd/brew-cask.rb:26:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:22:in `require?'
/usr/local/Library/brew.rb:93:in `<main>'
```

### Output of `brew doctor`

```
$ brew doctor
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15/rbconfig.rb:213: warning: Insecure world writable dir /usr/local/sbin in PATH, mode 040777
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15/rbconfig.rb:213: warning: Insecure world writable dir /usr/local/sbin in PATH, mode 040777
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15/rbconfig.rb:213: warning: Insecure world writable dir /usr/local/sbin in PATH, mode 040777
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
    /usr/local/include/node/ares.h
    /usr/local/include/node/ares_version.h
    /usr/local/include/node/nameser.h
    /usr/local/include/node/node.h
    /usr/local/include/node/node_buffer.h
    /usr/local/include/node/node_internals.h
    /usr/local/include/node/node_object_wrap.h
    /usr/local/include/node/node_version.h
    /usr/local/include/node/openssl/opensslconf.h
    /usr/local/include/node/uv-private/ngx-queue.h
    /usr/local/include/node/uv-private/stdint-msvc2008.h
    /usr/local/include/node/uv-private/tree.h
    /usr/local/include/node/uv-private/uv-bsd.h
    /usr/local/include/node/uv-private/uv-darwin.h
    /usr/local/include/node/uv-private/uv-linux.h
    /usr/local/include/node/uv-private/uv-sunos.h
    /usr/local/include/node/uv-private/uv-unix.h
    /usr/local/include/node/uv-private/uv-win.h
    /usr/local/include/node/uv.h
    /usr/local/include/node/v8-debug.h
    /usr/local/include/node/v8-preparser.h
    /usr/local/include/node/v8-profiler.h
    /usr/local/include/node/v8-testing.h
    /usr/local/include/node/v8.h
    /usr/local/include/node/v8stdint.h
    /usr/local/include/node/zconf.h
    /usr/local/include/node/zlib.h
    /usr/local/include/sane/sane.h
    /usr/local/include/sane/saneopts.h
```

**Comment by vitorgalvao** [comment]
Closing in favour of https://github.com/caskroom/homebrew-cask/issues/22098.

**Comment by mathiashro** [comment]
Reason: #22248
