### ISSUE TITLE
Old command in error message?

### ISSUE THREAD

**Issue by Numbermaniac** [caskroom/homebrew-cask#22295]
This is probably a stupid question, but oh well. After messing something up, I got this error message:

```
Error: undefined method `latest?' for nil:NilClass
  Most likely, this means you have an outdated version of homebrew-cask. Please run:

      brew uninstall --force brew-cask; brew untap phinze/cask; brew update; brew cleanup; brew cask cleanup
```

I've fixed it, but isn't `brew uninstall --force brew-cask` the old way cask was implemented? Again, apologies if I'm being a complete idiot.

**Comment by vitorgalvao** [comment]
You don’t install or uninstall `brew-cask` anymore. Homebrew downloads us automatically when needed.

**Comment by Numbermaniac** [comment]
@vitorgalvao Exactly, so does the error message need to be changed?

**Comment by vitorgalvao** [comment]
No, because the message does not tell you to install anything. It’s a bit of a nuclear solution to make sure you untapped all the old stuff.

That said, we should hopefully be able to remove that soon.

**Comment by jawshooah** [comment]
> does the error message need to be changed?

No. It's likely that there are still users out there who have a lingering legacy install. Including the `uninstall` command covers our bases.

**Comment by charlax** [comment]
I am having this issue - tried the command above to no avail.

```
% brew cask install --force $(brew cask list)
==> Downloading https://download.docker.com/mac/stable/1.13.0.15072/Docker.dmg
######################################################################## 100.0%
==> Verifying checksum for Cask docker
Warning: It seems there is already an App at '/Applications/Docker.app'; overwriting.
==> Removing App: '/Applications/Docker.app'
==> Moving App 'Docker.app' to '/Applications/Docker.app'
🍺  docker was successfully installed!
Error: undefined method `latest?' for nil:NilClass
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/pre_bug_report.md

If this doesn’t fix the problem, please report this bug:
  https://github.com/caskroom/homebrew-cask#reporting-bugs

/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/download.rb:36:in `clear_cache'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/download.rb:14:in `perform'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:101:in `download'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:62:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:85:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:25:in `block in install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:19:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:19:in `install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:10:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:111:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:150:in `process'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/brew-cask.rb:8:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/brew.rb:24:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

```
% brew cask doctor
==> macOS Release:
10.12.3
==> Hardware Architecture:
intel-64
==> Ruby Version:
2.0.0-p648
==> Ruby Path:
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
==> Homebrew Version:
Homebrew 1.1.8
Homebrew/homebrew-core (git revision e5a9; last commit 2017-01-25)
==> Homebrew Executable Path:
/usr/local/bin/brew
==> Homebrew Cellar Path:
/usr/local/Cellar
==> Homebrew Repository Path:
/usr/local/Homebrew
==> Homebrew Origin:
https://github.com/Homebrew/brew
==> Homebrew-Cask Version:
Homebrew-Cask 1.1.8
caskroom/homebrew-cask (git revision 7548b; last commit 2017-01-25)
==> Homebrew-Cask Install Location:
<NONE>
==> Homebrew-Cask Staging Location:
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads:
/Users/ca/Library/Caches/Homebrew/Cask
1 files, 104.2M (warning: run "brew cask cleanup")
==> Homebrew-Cask Default Tap Path:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask
==> Homebrew-Cask Alternate Cask Taps:
/usr/local/Homebrew/Library/Taps/uber/homebrew-alt
==> Homebrew-Cask Default Tap Cask Count:
3537
==> Contents of $LOAD_PATH:
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Contents of $RUBYLIB Environment Variable:
<NONE>
==> Contents of $RUBYOPT Environment Variable:
<NONE>
==> Contents of $RUBYPATH Environment Variable:
<NONE>
==> Contents of $RBENV_VERSION Environment Variable:
<NONE>
==> Contents of $CHRUBY_VERSION Environment Variable:
<NONE>
==> Contents of $GEM_HOME Environment Variable:
<NONE>
==> Contents of $GEM_PATH Environment Variable:
<NONE>
==> Contents of $BUNDLE_PATH Environment Variable:
<NONE>
==> Contents of $PATH Environment Variable:
PATH="/Users/ca/.rbenv/shims:/usr/local/bin:/usr/local/sbin:/Users/ca/.dotfiles/bin:/Users/ca/.nvm/v0.10.32/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/munki:/Library/TeX/texbin:/Users/ca/bin:/Users/ca/golang/bin:/usr/local/opt/fzf/bin:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-boneyard/cmd:/usr/local/Homebrew/Library/Homebrew/cask/cmd:/usr/local/Homebrew/Library/Homebrew/shims/scm"
==> Contents of $SHELL Environment Variable:
SHELL="/usr/local/bin/zsh"
==> Contents of Locale Environment Variables:
LANG="en_US.UTF-8"
```
This happened after I upgraded a bunch of stuff and moved the cask folder. My installation was pretty old.

**Comment by miccal** [comment]
@charlax can you try running the command `brew untap caskroom/cask; brew cleanup; brew cask cleanup; brew update` and then trying again.

**Comment by charlax** [comment]
Thanks for your help. Still getting the same error.

```
% brew cask install --force $(brew cask list)
==> Downloading https://download.docker.com/mac/stable/1.13.0.15072/Docker.dmg
######################################################################## 100.0%
==> Verifying checksum for Cask docker
Warning: It seems there is already an App at '/Applications/Docker.app'; overwriting.
==> Removing App: '/Applications/Docker.app'
==> Moving App 'Docker.app' to '/Applications/Docker.app'
🍺  docker was successfully installed!
Error: undefined method `latest?' for nil:NilClass
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/pre_bug_report.md

If this doesn’t fix the problem, please report this bug:
  https://github.com/caskroom/homebrew-cask#reporting-bugs

/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/download.rb:36:in `clear_cache'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/download.rb:14:in `perform'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:101:in `download'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:62:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:85:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:25:in `block in install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:19:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:19:in `install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:10:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:111:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:150:in `process'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/brew-cask.rb:8:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/brew.rb:24:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

**Comment by miccal** [comment]
@charlax please open a new issue, ensuring you follow the [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) instructions, so we can try and figure out what is going on.

**Comment by charlax** [comment]
Done in #29397.
