### ISSUE TITLE
Weird permission denies when installing hyperdock

### ISSUE THREAD

**Issue by binarykitchen** [caskroom/homebrew-cask#22312]
This says it all

```
~/C/abc-ui ❯❯❯ brew cask install hyperdock                                                              feature/mailboxes-actions ✱
==> Tapping caskroom/cask
Cloning into '/usr/local/Library/Taps/caskroom/homebrew-cask'...
remote: Counting objects: 3708, done.
remote: Compressing objects: 100% (3656/3656), done.
remote: Total 3708 (delta 65), reused 619 (delta 32), pack-reused 0
Receiving objects: 100% (3708/3708), 6.48 MiB | 4.62 MiB/s, done.
Resolving deltas: 100% (65/65), done.
Checking connectivity... done.
Tapped 1 formula (3,676 files, 15.3M)
==> Downloading https://bahoom.com/hyperdock/1.6.0.1/HyperDock-1.6.0.1.dmg
######################################################################## 100.0%
==> Verifying checksum for Cask hyperdock
==> Moving Preference Pane 'HyperDock.prefpane' to '/Library/PreferencePanes/HyperDock.prefpane'
Error: Permission denied - (/usr/local/Caskroom/hyperdock/1.6.0.1/HyperDock.prefpane, /Library/PreferencePanes/HyperDock.prefpane)
  Most likely, this means you have an outdated version of homebrew-cask. Please run:

      brew uninstall --force brew-cask; brew untap phinze/cask; brew update; brew cleanup; brew cask cleanup

  If this doesn’t fix the problem, please report this bug:

      https://github.com/caskroom/homebrew-cask#reporting-bugs

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:519:in `rename'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:519:in `block in mv'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1558:in `block in fu_each_src_dest'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1574:in `fu_each_src_dest0'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1556:in `fu_each_src_dest'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:508:in `mv'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/artifact/moved.rb:50:in `move'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/artifact/moved.rb:26:in `block in install_phase'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/artifact/moved.rb:43:in `block in each_artifact'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/artifact/moved.rb:42:in `each'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/artifact/moved.rb:42:in `each_artifact'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/artifact/moved.rb:22:in `install_phase'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/installer.rb:129:in `block in install_artifacts'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/installer.rb:126:in `each'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/installer.rb:126:in `install_artifacts'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/installer.rb:75:in `install'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/install.rb:21:in `block in install_casks'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/install.rb:18:in `each'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/install.rb:18:in `install_casks'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/install.rb:7:in `run'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli.rb:83:in `run_command'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli.rb:121:in `process'
/usr/local/Library/Taps/caskroom/homebrew-cask/cmd/brew-cask.rb:26:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:22:in `require?'
/usr/local/Library/brew.rb:93:in `<main>'
```

I already did the recommendations and ran `brew uninstall --force brew-cask; brew untap phinze/cask; brew update; brew cleanup; brew cask cleanup`. Yet, the above error still happens. Any clues?

**Comment by vitorgalvao** [comment]
Use `--force` when installing.

**Comment by vitorgalvao** [comment]
Also, it should not be linking to `/Library/`, which means you likely set that as an option.

**Comment by binarykitchen** [comment]
the --force option does not make any difference

**Comment by vitorgalvao** [comment]
Like I said

> Also, it should not be linking to `/Library/`, which means you likely set that as an option.

Check your [options](https://github.com/caskroom/homebrew-cask/blob/master/USAGE.md#options).

**Comment by binarykitchen** [comment]
hmmm, sudo worked for me
