### ISSUE TITLE
Bug report: Installation of MacDown fails

### ISSUE THREAD

**Issue by fuerst** [caskroom/homebrew-cask#22335]
Note: run `brew update; brew cleanup; brew cask cleanup`.

### Description of issue

Installation of MacDown fails:

### Output of `brew cask install macdown --verbose`

```
==> Downloading https://github.com/uranusjr/macdown/releases/download/v0.6/MacDown.app.zip
Already downloaded: /Users/fuerst/Library/Caches/Homebrew/macdown-0.6.zip
==> Verifying checksum for Cask macdown
==> Moving App 'MacDown.app' to '/Applications/MacDown.app'
Error: Permission denied - (/usr/local/Caskroom/macdown/0.6/MacDown.app, /Applications/MacDown.app)
  Most likely, this means you have an outdated version of homebrew-cask. Please run:

      brew uninstall --force brew-cask; brew untap phinze/cask; brew update; brew cleanup; brew cask cleanup

  If this doesn’t fix the problem, please report this bug:

      https://github.com/caskroom/homebrew-cask#reporting-bugs

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:519:in `rename'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:519:in `block in mv'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1558:in `block in fu_each_src_dest'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1574:in `fu_each_src_dest0'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1556:in `fu_each_src_dest'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:508:in `mv'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/artifact/moved.rb:50:in `move'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/artifact/moved.rb:26:in `block in install_phase'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/artifact/moved.rb:43:in `block in each_artifact'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/artifact/moved.rb:42:in `each'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/artifact/moved.rb:42:in `each_artifact'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/artifact/moved.rb:22:in `install_phase'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/installer.rb:129:in `block in install_artifacts'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/installer.rb:126:in `each'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/installer.rb:126:in `install_artifacts'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/installer.rb:75:in `install'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/install.rb:21:in `block in install_casks'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/install.rb:18:in `each'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/install.rb:18:in `install_casks'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/install.rb:7:in `run'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli.rb:83:in `run_command'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli.rb:121:in `process'
/usr/local/Library/Taps/caskroom/homebrew-cask/cmd/brew-cask.rb:26:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:22:in `require?'
/usr/local/Library/brew.rb:93:in `<main>'
Error: Kernel.exit
```

### Output of `brew doctor`

```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Your XQuartz (2.7.8) is outdated
Please install XQuartz 2.7.9:
  https://xquartz.macosforge.org

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
    /usr/local/lib/libtliadjust50.dylib
    /usr/local/lib/libtlImageIO.dylib

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
    libsoup
    openssl098
```

### Output of `brew cask doctor`

```
==> macOS Release:
10.11
==> macOS Release with Patchlevel:
10.11.5
==> Hardware Architecture:
intel-64
==> Ruby Version:
2.0.0-p648
==> Ruby Path:
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
==> Homebrew Version:
Homebrew 0.9.9 (git revision 05649c; last commit 2016-06-23)
Homebrew/homebrew-core (git revision 2cc26; last commit 2016-06-23)
==> Homebrew Executable Path:
/usr/local/bin/brew
==> Homebrew Cellar Path:
/usr/local/Cellar
==> Homebrew Repository Path:
/usr/local
==> Homebrew Origin:
https://github.com/Homebrew/brew.git
==> Homebrew-cask Version:
0.60.0 (git revision b1a3e; last commit 36 minutes ago)
==> Homebrew-cask Install Location:
<NONE>
==> Homebrew-cask Staging Location:
/usr/local/Caskroom
==> Homebrew-cask Cached Downloads:
/Users/fuerst/Library/Caches/Homebrew
/Users/fuerst/Library/Caches/Homebrew/Casks
2 files, 15.5M (warning: run "brew cask cleanup")
==> Homebrew-cask Default Tap Path:
/usr/local/Library/Taps/caskroom/homebrew-cask
==> Homebrew-cask Alternate Cask Taps:
<NONE>
==> Homebrew-cask Default Tap Cask Count:
3196
==> Contents of $LOAD_PATH:
/usr/local/Library/Taps/caskroom/homebrew-cask/lib
/usr/local/Library/Homebrew
/Library/Ruby/Gems/2.0.0/gems/psych-2.0.6/lib
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin15
/Library/Ruby/Site/2.0.0/universal-darwin15
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15
==> Contents of $RUBYLIB Environment Variable:
<NONE>
==> Contents of $RUBYOPT Environment Variable:
<NONE>
==> Contents of $RUBYPATH Environment Variable:
<NONE>
==> Contents of $RBENV_VERSION Environment Variable:
<NONE>
==> Contents of $CHRUBY_VERSION Environment Variable:
<NONE>
==> Contents of $GEM_HOME Environment Variable:
<NONE>
==> Contents of $GEM_PATH Environment Variable:
<NONE>
==> Contents of $BUNDLE_PATH Environment Variable:
<NONE>
==> Contents of $PATH Environment Variable:
PATH="/Users/fuerst/.composer/vendor/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/MacGPG2/bin:/Library/TeX/texbin:/Users/fuerst/bin:/Users/fuerst/.rvm/bin:/usr/local/Library/Taps/caskroom/homebrew-cask/cmd:/usr/local/Library/ENV/scm"
==> Contents of $SHELL Environment Variable:
SHELL="/bin/bash"
==> Contents of Locale Environment Variables:
LANG="de_DE.UTF-8"
==> Running As Privileged User:
No
```

**Comment by victorpopkov** [comment]
This is a permissions issue and there is nothing wrong with the cask itself.

Since previous versions of Homebrew-Cask used the `~/Applications` directory by default (that is located in your `$HOME`). Now it uses `/Applications` by default. You can use `--appdir=~/Applications` to bring back that old behaviour. For example to install `macdown` run:
```bash
brew cask install macdown --appdir=~/Applications
```

For permanent effect try fixing the permissions for directory `/Applications` (without `~`) or you could [follow the _Options_ section in USAGE.md](https://github.com/caskroom/homebrew-cask/blob/1de4657a0ed35463602b31061b0c16dc9078b8a0/USAGE.md#options).

**Comment by fuerst** [comment]
Understand that. My user is configured as _Standard_ user so I do not have write access to `/Applications`. I do prefere to have `brew cask` to install there though. Is there a way `brew cask` can use `sudo` for moving applications to `/Applications`?

**Comment by victorpopkov** [comment]
I'm afraid it's not possible if you are a _Standard_ user. At least I can't suggest any good solution for that without completely overriding owner permissions for `/Applications` directory which shouldn't be done. 

The best approach here would be to set the environment variable `HOMEBREW_CASK_OPTS ` to point to your user specific applications directory instead.

**Comment by vitorgalvao** [comment]
Closing as solved.

**Comment by ckotte** [comment]
This issue is closed, but.. I had to type in my admin credentials during install of an(y) application(s) some time ago. Did you introduce sudo and then removed it again or is this application specific? It should be easy to implement to check the user permissions before moving the app to /Applications and just do a sudo before...

**Comment by robindegen** [comment]
@ckotte Indeed this used to work with a sudo kind of thing before. Now it just fails...

**Comment by vitorgalvao** [comment]
> Using --appdir worked as a workaround, but that's not a great solution.

It’s not a workaround, it is the official solution. Most people prefer to install to `/Applications` and have permissions to do it, since it’s the default.

If you chose to run as a limited user, you need to install to a different directory, there’s no way to do it.

**Comment by robindegen** [comment]
What's wrong with sudo? Ask the user to elevate it's permissions by providing an administrator password when trying to write to ```/Applications```. This is what the finder does too when I attempt to write to this folder. This is also common for other package managers.

**Comment by vitorgalvao** [comment]
@robindegen No quarrel with that. I’d be fine with a PR to add that functionality.

**Comment by robindegen** [comment]
touche 😄 I'll see what I can do.

**Comment by vitorgalvao** [comment]
I only mentioned a PR because this is an extremely low priority thing, as it affects a tiny amount of users. As such, it’s unlikely the core team will spend time on it, and you’d have a better change of seeing it happen with a PR.
