### ISSUE TITLE
Cask has stopped working

### ISSUE THREAD

**Issue by behrangsa** [caskroom/homebrew-cask#22414]
OS: Mac OS X El Capitan 10.11.4

Before raising this ticket, I uninstalled homebrew from my system and installed homebrew and cask anew.

`brew cask install freemind` and other DMG based apps fail to install. Without sudo:

```
$ brew cask install freemind
==> Downloading http://downloads.sourceforge.net/project/freemind/freemind/1.0.1/FreeMind_1.0.1.dmg
Already downloaded: /Users/grey.behrangs/Library/Caches/Homebrew/freemind-1.0.1.dmg
Error: File exists - (/Users/grey.behrangs/Library/Caches/Homebrew/freemind-1.0.1.dmg, /Users/grey.behrangs/Library/Caches/Homebrew/Casks/freemind-1.0.1.dmg)
  Most likely, this means you have an outdated version of homebrew-cask. Please run:

      brew uninstall --force brew-cask; brew untap phinze/cask; brew update; brew cleanup; brew cask cleanup

  If this doesn’t fix the problem, please report this bug:

      https://github.com/caskroom/homebrew-cask#reporting-bugs

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:349:in `symlink'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:349:in `block in ln_s'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1574:in `fu_each_src_dest0'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:347:in `ln_s'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:370:in `ln_sf'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/download.rb:45:in `create_cache_symlink'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/download.rb:15:in `perform'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/installer.rb:99:in `download'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/installer.rb:73:in `install'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/install.rb:21:in `block in install_casks'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/install.rb:18:in `each'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/install.rb:18:in `install_casks'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/install.rb:7:in `run'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli.rb:83:in `run_command'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli.rb:121:in `process'
/usr/local/Library/Taps/caskroom/homebrew-cask/cmd/brew-cask.rb:26:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:22:in `require?'
/usr/local/Library/brew.rb:93:in `<main>'
```

With sudo:

```
$ sudo brew cask install freemind
==> Downloading http://downloads.sourceforge.net/project/freemind/freemind/1.0.1/FreeMind_1.0.1.dmg
######################################################################## 100.0%
==> Verifying checksum for Cask freemind
==> hdiutil: mount failed - no mountable file systems
Error: Empty plist input
```

Any ideas what could be the problem?

**Comment by vitorgalvao** [comment]
Please *always* follow the [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) guide. To do so, edit the top post and then comment after this one so I can check back.

Closing in the meantime, because a number of people never report back and it’s useless to keep the issue open in that case and without all the required information.

Few things you can try. Start by removing the cache directory `rm -rf "$(brew --cache)"`. Then, try installing with `--force`.
