### ISSUE TITLE
brew cask style --fix fails with frozen String

### ISSUE THREAD

**Issue by bric3** [caskroom/homebrew-cask#22598]
#### Description of issue

Upon a new pull request on https://github.com/caskroom/homebrew-versions, I needed to perform some checks before doing the PR. One this step was to run this command (note the `cask_file` is irrelevant to the problem) :

```shell
brew cask style --fix {{cask_file}}
```

However it failed because some _frozen String cannot be modified_. The error message invite me to run

```shell
brew uninstall --force brew-cask; brew untap phinze/cask; brew update; brew cleanup; brew cask 
```

Which I did but the error don't go away. And by the way the error is almost the same with the `--verbose` option.

<details><summary>Output of `brew cask style --fix {{cask_file}} --verbose`</summary>

```
Error: can't modify frozen String
  Most likely, this means you have an outdated version of homebrew-cask. Please run:

      brew uninstall --force brew-cask; brew untap phinze/cask; brew update; brew cleanup; brew cask cleanup

  If this doesn’t fix the problem, please report this bug:

      https://github.com/caskroom/homebrew-cask#reporting-bugs

/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/locations.rb:129:in `sub!'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/locations.rb:129:in `path'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/style.rb:36:in `block in cask_paths'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/style.rb:36:in `map'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/style.rb:36:in `cask_paths'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/style.rb:20:in `run'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/style.rb:9:in `run'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli.rb:83:in `run_command'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli.rb:121:in `process'
/usr/local/Library/Taps/caskroom/homebrew-cask/cmd/brew-cask.rb:26:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:22:in `require?'
/usr/local/Library/brew.rb:93:in `<main>'
Error: Kernel.exit
```
</details>

<details><summary>Output of `brew doctor`</summary>

```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Your Xcode (7.3) is outdated
Please update to Xcode 7.3.1.
Xcode can be updated from the App Store.
```
</details>

<details><summary>Output of `brew cask doctor`</summary>

```
==> macOS Release:
10.11
==> macOS Release with Patchlevel:
10.11.5
==> Hardware Architecture:
intel-64
==> Ruby Version:
2.0.0-p648
==> Ruby Path:
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
==> Homebrew Version:
Homebrew 0.9.9 (git revision f518; last commit 2016-07-05)
Homebrew/homebrew-core (git revision 6f4a; last commit 2016-07-05)
==> Homebrew Executable Path:
/usr/local/bin/brew
==> Homebrew Cellar Path:
/usr/local/Cellar
==> Homebrew Repository Path:
/usr/local
==> Homebrew Origin:
https://github.com/Homebrew/brew.git
==> Homebrew-cask Version:
0.60.0 (git revision b3ee3; last commit 46 minutes ago)
==> Homebrew-cask Install Location:
<NONE>
==> Homebrew-cask Staging Location:
/usr/local/Caskroom
==> Homebrew-cask Cached Downloads:
/Users/brice/Library/Caches/Homebrew
/Users/brice/Library/Caches/Homebrew/Casks
0 files, 0B
==> Homebrew-cask Default Tap Path:
/usr/local/Library/Taps/caskroom/homebrew-cask
==> Homebrew-cask Alternate Cask Taps:
<NONE>
==> Homebrew-cask Default Tap Cask Count:
3218
==> Contents of $LOAD_PATH:
/usr/local/Library/Taps/caskroom/homebrew-cask/lib
/usr/local/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin15
/Library/Ruby/Site/2.0.0/universal-darwin15
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15
==> Contents of $RUBYLIB Environment Variable:
<NONE>
==> Contents of $RUBYOPT Environment Variable:
<NONE>
==> Contents of $RUBYPATH Environment Variable:
<NONE>
==> Contents of $RBENV_VERSION Environment Variable:
<NONE>
==> Contents of $CHRUBY_VERSION Environment Variable:
<NONE>
==> Contents of $GEM_HOME Environment Variable:
<NONE>
==> Contents of $GEM_PATH Environment Variable:
<NONE>
==> Contents of $BUNDLE_PATH Environment Variable:
<NONE>
==> Contents of $PATH Environment Variable:
PATH="/Users/brice/.jenv/shims:/Users/brice/.cabal/bin:/usr/local/texlive/2012basic/bin/universal-darwin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/brice/.rvm/bin:/usr/local/Library/Taps/caskroom/homebrew-cask/cmd:/usr/local/Library/ENV/scm"
==> Contents of $SHELL Environment Variable:
SHELL="/bin/zsh"
==> Contents of Locale Environment Variables:
LANG="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
LC_CTYPE="UTF-8"
==> Running As Privileged User:
No
```
</details>

#### Pre bug just in case

<details><summary>Pre bug report</summary>

```shell
$ brew update; brew cleanup; brew cask cleanup
Updated 1 tap (homebrew/core).
==> Updated Formulae
yle-dl
==> Removing dead symlinks
Nothing to do
==> Removing cached downloads
Nothing to do


$ brew uninstall --force brew-cask; brew update
Already up-to-date.


$ brew untap phinze/cask; brew untap caskroom/cask; brew update
Error: No available tap phinze/cask.
Untapping caskroom/cask... (4,373 files, 95.6M)
Untapped 1 formula
Already up-to-date.


$ brew cask style --fix opera --verbose
/usr/local/bin/brew tap caskroom/cask
==> Tapping caskroom/cask
Cloning into '/usr/local/Library/Taps/caskroom/homebrew-cask'...
remote: Counting objects: 3755, done.
remote: Compressing objects: 100% (3699/3699), done.
remote: Total 3755 (delta 76), reused 611 (delta 35), pack-reused 0
Receiving objects: 100% (3755/3755), 6.50 MiB | 10.40 MiB/s, done.
Resolving deltas: 100% (76/76), done.
Checking connectivity... done.
Tapped 1 formula (3,722 files, 15.4M)
Error: can't modify frozen String
  Most likely, this means you have an outdated version of homebrew-cask. Please run:

      brew uninstall --force brew-cask; brew untap phinze/cask; brew update; brew cleanup; brew cask cleanup

  If this doesn’t fix the problem, please report this bug:

      https://github.com/caskroom/homebrew-cask#reporting-bugs

/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/locations.rb:129:in `sub!'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/locations.rb:129:in `path'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/style.rb:36:in `block in cask_paths'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/style.rb:36:in `map'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/style.rb:36:in `cask_paths'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/style.rb:20:in `run'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/style.rb:9:in `run'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli.rb:83:in `run_command'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli.rb:121:in `process'
/usr/local/Library/Taps/caskroom/homebrew-cask/cmd/brew-cask.rb:26:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:22:in `require?'
/usr/local/Library/brew.rb:93:in `<main>'
Error: Kernel.exit


$ brew uninstall --force brew-cask; brew untap phinze/cask; brew update; brew cleanup; brew cask cleanup
Error: No available tap phinze/cask.
Already up-to-date.
==> Removing dead symlinks
Nothing to do
==> Removing cached downloads
Nothing to do


$ brew cask style --fix opera --verbose
Error: can't modify frozen String
  Most likely, this means you have an outdated version of homebrew-cask. Please run:

      brew uninstall --force brew-cask; brew untap phinze/cask; brew update; brew cleanup; brew cask cleanup

  If this doesn’t fix the problem, please report this bug:

      https://github.com/caskroom/homebrew-cask#reporting-bugs

/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/locations.rb:129:in `sub!'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/locations.rb:129:in `path'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/style.rb:36:in `block in cask_paths'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/style.rb:36:in `map'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/style.rb:36:in `cask_paths'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/style.rb:20:in `run'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/style.rb:9:in `run'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli.rb:83:in `run_command'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli.rb:121:in `process'
/usr/local/Library/Taps/caskroom/homebrew-cask/cmd/brew-cask.rb:26:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:22:in `require?'
/usr/local/Library/brew.rb:93:in `<main>'
Error: Kernel.exit
```

</details>

**Comment by adidalal** [comment]
I can reproduce, tracking at https://github.com/caskroom/rubocop-cask/issues/27
