### ISSUE TITLE
`brew cask audit` failed

### ISSUE THREAD

**Issue by sivabudh** [caskroom/homebrew-cask#23423]
```
 ~ ruby --version                                                                                                                                                                                  ⏎
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]

 ~ brew cask audit
audit for 010-editor: passed
audit for 0ad: passed
audit for 0xed: passed
audit for 115browser: passed
audit for 1clipboard: passed
audit for 1password: passed
audit for 33-rpm: passed
audit for 4k-stogram: passed
audit for 4k-video-downloader: passed
audit for 4k-youtube-to-mp3: passed
audit for 4peaks: passed
audit for 5iler: passed
audit for 5kplayer: passed
audit for 8tracksradiohelper: passed
audit for a-better-finder-attributes: passed
audit for a-better-finder-rename: passed
audit for a-slower-speed-of-light: passed
audit for abgx360: passed
audit for ableton-live: passed
audit for abricotine: passed
audit for abscissa: passed
audit for abyss: passed
audit for accessmenubarapps: passed
audit for acorn: passed
audit for acquia-dev-desktop: passed
audit for across-lite: passed
audit for acslogo: passed
audit for actions-server: passed
audit for activity-audit: passed
audit for actotracker: passed
audit for actprinter: passed
audit for actual-odbc-pack: passed
audit for adafruit-arduino: passed
audit for adapter: passed
audit for adguard: passed
audit for adium: passed
audit for adobe-acrobat: passed
audit for adobe-air: passed
audit for adobe-animate-cc: passed
audit for adobe-arh: passed
audit for adobe-bloodhound: passed
audit for adobe-bridge-cc: passed
audit for adobe-creative-cloud-cleaner-tool: passed
audit for adobe-creative-cloud: passed
audit for adobe-digital-editions: passed
audit for adobe-dng-converter: passed
audit for adobe-illustrator-cc: passed
audit for adobe-indesign-cc: passed
audit for adobe-photoshop-cc: passed
audit for adobe-photoshop-lightroom: passed
audit for adobe-reader: passed
audit for adpassmon: passed
audit for adventure: passed
audit for adware-removal-tool: passed
audit for aegisub: passed
audit for aerial: passed
audit for aether: passed
audit for affinic-debugger-gui: passed
audit for after-dark-classic: passed
audit for aimersoft-video-converter-ultimate: passed
audit for air-connect: passed
audit for air-video-server-hd: passed
audit for airdisplay: passed
audit for airdroid: passed
audit for airfile: passed
audit for airflick: passed
audit for airflow: passed
audit for airfoil: passed
audit for airmedia: passed
audit for airparrot: passed
audit for airserver: passed
audit for airstream: passed
audit for airtame: passed
audit for airtool: passed
audit for airvpn: passed
audit for airy: passed
audit for aja-system-test: passed
audit for aladin: passed
audit for alarm-clock: passed
audit for alcatraz: passed
audit for alchemy: passed
audit for alfred: passed
audit for algodoo: passed
audit for alib1: passed
audit for alice: passed
audit for aliedit: passed
audit for alinof-timer: passed
audit for aliwangwang: passed
audit for aliworkbench: passed
audit for alternote: passed
audit for amadeus-pro: passed
audit for amazon-drive: passed
audit for amazon-music: passed
audit for amazon-workdocs: passed
audit for amazon-workspaces: passed
audit for amethyst: passed
audit for amidst: passed
audit for ammonite: passed
audit for ampps: passed
audit for anaconda: passed
audit for anatine: passed
audit for android-file-transfer: passed
audit for android-studio: passed
audit for androidtool: passed
audit for andy: passed
audit for angband: passed
audit for angry-ip-scanner: passed
audit for animated-gif-quicklook: passed
audit for anki: passed
audit for anonvpn: passed
audit for anonym: passed
audit for antconc: passed
audit for antetype: passed
audit for antfileconverter: passed
audit for antpconc: passed
audit for antwordprofiler: passed
audit for anvil: passed
audit for anybar: passed
audit for anyipsum: passed
audit for anylist: passed
audit for anylogic: passed
audit for anypass: passed
audit for anytrans: passed
audit for apache-couchdb: passed
audit for apache-directory-studio: passed
audit for apm-planner: passed
audit for apogee-duet: passed
audit for app-tamer: passed
audit for appcleaner: passed
audit for appcode: passed
audit for appdelete: passed
audit for appearin: passed
audit for appfresh: passed
audit for appium: passed
audit for applepi-baker: passed
audit for application-loader: passed
audit for apppolice: passed
audit for appserver: passed
audit for appstore-quickview: passed
audit for apptivate: passed
audit for apptrans: passed
audit for apptrap: passed
audit for appzapper: passed
audit for aptanastudio: passed
audit for aqua-data-studio: passed
audit for aquamacs: passed
audit for aquaskk: passed
audit for aquaterm: passed
audit for araxis-merge: passed
audit for archi: passed
audit for archiver: passed
audit for arduino: passed
audit for argouml: passed
audit for aria-maestosa: passed
audit for armitage: passed
audit for armory: passed
audit for arq: passed
audit for arranger: passed
audit for arrsync: passed
audit for art-directors-toolkit: passed
audit for art-of-illusion: passed
audit for ascension: passed
audit for aseprite: passed
audit for asepsis: passed
audit for astah-community: passed
audit for astah-professional: passed
audit for astah-sysml: passed
audit for astrill: passed
audit for astropad: passed
audit for atext: passed
audit for atlantis: passed
audit for atlauncher: passed
audit for atom: passed
audit for atraci: passed
audit for au-lab: passed
audit for audacity-lame-library: passed
Error: undefined method `[]' for nil:NilClass
  Most likely, this means you have an outdated version of homebrew-cask. Please run:

      brew uninstall --force brew-cask; brew untap phinze/cask; brew untap caskroom/cask; brew update; brew cleanup; brew cask cleanup

  If this doesn’t fix the problem, please report this bug:

      https://github.com/caskroom/homebrew-cask#reporting-bugs

/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/source/path_base.rb:44:in `block (3 levels) in load_cask'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:153:in `open_uri'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:689:in `open'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:34:in `open'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/source/path_base.rb:42:in `block (2 levels) in load_cask'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/url.rb:13:in `call'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/url.rb:13:in `block in from'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/dsl/stanza_proxy.rb:6:in `block in once'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/dsl/stanza_proxy.rb:19:in `call'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/dsl/stanza_proxy.rb:19:in `to_s'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/audit.rb:150:in `bad_url_format?'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/audit.rb:155:in `bad_sourceforge_url?'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/audit.rb:142:in `check_download_url_format'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/audit.rb:137:in `check_url'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/audit.rb:21:in `run!'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/auditor.rb:5:in `audit'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/audit.rb:29:in `audit'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/audit.rb:22:in `block in run'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/audit.rb:21:in `each'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/audit.rb:21:in `run'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/audit.rb:7:in `run'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli.rb:110:in `run_command'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli.rb:148:in `process'
/usr/local/Library/Taps/caskroom/homebrew-cask/cmd/brew-cask.rb:23:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/Homebrew/brew.rb:22:in `require?'
/usr/local/Library/Homebrew/brew.rb:93:in `<main>'
```

**Comment by jawshooah** [comment]
Please *always* follow the [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) guide. When you opened this issue, the template in place urged you to do so and gave you the relevant links. In fact, the very error message you reported directed you to the relevant instructions:

```
If this doesn’t fix the problem, please report this bug:

      https://github.com/caskroom/homebrew-cask#reporting-bugs
```

In the meantime, this issue will be closed, as many users don't bother to report back.
