### ISSUE TITLE
`brew cask _stanza url audacity.rb` fails

### ISSUE THREAD

**Issue by vszakats** [caskroom/homebrew-cask#23463]
AFAICS this is the single formula the triggers this (or any other) error, possibly because of the tricky way the URL is formed in this particular formula.

Here's the error:
```
Error: undefined method `[]' for nil:NilClass
  Most likely, this means you have an outdated version of homebrew-cask. Please run:

      brew uninstall --force brew-cask; brew untap phinze/cask; brew untap caskroom/cask; brew update; brew cleanup; brew cask cleanup

  If this doesn’t fix the problem, please report this bug:

      https://github.com/caskroom/homebrew-cask#reporting-bugs

/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/source/path_base.rb:44:in `block (3 levels) in load_cask'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:153:in `open_uri'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:689:in `open'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:34:in `open'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/source/path_base.rb:42:in `block (2 levels) in load_cask'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/url.rb:13:in `call'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/url.rb:13:in `block in from'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/dsl/stanza_proxy.rb:6:in `block in once'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/dsl/stanza_proxy.rb:19:in `call'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/dsl/stanza_proxy.rb:19:in `to_s'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/internal_stanza.rb:116:in `block in print_stanzas'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/internal_stanza.rb:78:in `each'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/internal_stanza.rb:78:in `print_stanzas'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/internal_stanza.rb:59:in `run'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli.rb:108:in `run_command'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli.rb:146:in `process'
/usr/local/Library/Taps/caskroom/homebrew-cask/cmd/brew-cask.rb:23:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/Homebrew/brew.rb:22:in `require?'
/usr/local/Library/Homebrew/brew.rb:93:in `<main>'
```

**Comment by reitermarkus** [comment]
> possibly because of the tricky way the URL is formed

Yes. See https://github.com/caskroom/homebrew-cask/pull/23442.
