### ISSUE TITLE
Bug report: No such file or directory - /usr/local/Library/Taps/caskroom/homebrew-cask

### ISSUE THREAD

**Issue by ericbn** [caskroom/homebrew-cask#23940]
Already followed the [pre bug report](https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/pre_bug_report.md) guide. Also did `$ brew uninstall --force brew-cask; brew untap phinze/cask; brew untap caskroom/cask; brew update; brew cleanup; brew cask cleanup` as instructed by `brew cask doctor`.

#### Description of issue

I get "No such file or directory - /usr/local/Library/Taps/caskroom/homebrew-cask" error with `brew cask doctor`, `brew cask list` gives me a `(!)` after each installed cask, and `brew cask search` gives me nothing. Also impossible to install a cask.

Complete outputs below.

<details><summary>Output of `brew cask list --verbose`</summary>

```
android-file-transfer (!)                firefox (!)                              itau (!)                                 skype (!)                                vagrant (!)
atom (!)                                 flux (!)                                 iterm2 (!)                               slack (!)                                virtualbox (!)
dash (!)                                 gimp (!)                                 java (!)                                 the-unarchiver (!)                       virtualbox-extension-pack (!)
docker (!)                               gitkraken (!)                            keeweb (!)                               tunnelblick (!)                          vlc (!)
eclipse-java (!)                         google-chrome (!)                        racket (!)                               utorrent (!)                             webex-nbr-player (!)
```
</details>

<details><summary>Output of `brew cask search text --verbose`</summary>

```
No Cask found for "text".
```
</details>

<details><summary>Output of `brew doctor`</summary>

```
Your system is ready to brew.
```
</details>

<details><summary>Output of `brew cask doctor`</summary>

```
==> macOS Release:
10.11.6
==> Hardware Architecture:
intel-64
==> Ruby Version:
2.0.0-p648
==> Ruby Path:
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
==> Homebrew Version:
Homebrew 0.9.9 (git revision 7395f; last commit 2016-08-19)
Homebrew/homebrew-core (git revision 5301; last commit 2016-08-20)
==> Homebrew Executable Path:
/usr/local/bin/brew
==> Homebrew Cellar Path:
/usr/local/Cellar
==> Homebrew Repository Path:
/usr/local
==> Homebrew Origin:
https://github.com/Homebrew/brew
Error: No such file or directory - /usr/local/Library/Taps/caskroom/homebrew-cask
  Most likely, this means you have an outdated version of Homebrew-Cask. Please run:

      brew uninstall --force brew-cask; brew untap phinze/cask; brew untap caskroom/cask; brew update; brew cleanup; brew cask cleanup

  If this doesn’t fix the problem, please report this bug:

      https://github.com/caskroom/homebrew-cask#reporting-bugs

/usr/local/Library/Homebrew/cask/lib/hbc/version.rb:6:in `chdir'
/usr/local/Library/Homebrew/cask/lib/hbc/version.rb:6:in `full_version'
/usr/local/Library/Homebrew/cask/lib/hbc/cli/doctor.rb:13:in `run'
/usr/local/Library/Homebrew/cask/lib/hbc/cli.rb:108:in `run_command'
/usr/local/Library/Homebrew/cask/lib/hbc/cli.rb:146:in `process'
/usr/local/Library/Homebrew/cask/cmd/brew-cask.rb:8:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/Homebrew/brew.rb:19:in `require?'
/usr/local/Library/Homebrew/brew.rb:93:in `<main>'
```
</details>

**Comment by ericbn** [comment]
Looks like there's a different copy o this repo inside https://github.com/Homebrew/brew/tree/master/Library/Homebrew/cask and that's all I have installed now. Should I still do `$ brew tap caskroom/cask`?

**Comment by adidalal** [comment]
Can you try `cd $(brew --repo); git fetch; git reset --hard origin/master; brew update` and then retry cask-related commands?

**Comment by reitermarkus** [comment]
> Looks like there's a different copy of this repo inside https://github.com/Homebrew/brew/tree/master/Library/Homebrew/cask and that's all I have installed now. Should I still do `$ brew tap caskroom/cask`?

The core has been move to the `Homebrew/brew` repo, the casks are still in the `caskroom/cask` tap.

**Comment by ericbn** [comment]
@adidalal, my `$(brew --repo)` was already at master and clean. Running the git commands above gave me

    HEAD is now at 7395ff2 Merge pull request #758 from reitermarkus/cask-dev-scripts
    Already up-to-date.

and running the brew cask commands above gave me the same output as I reported earlier.

@reitermarkus, so one still needs to do `$ brew tap caskroom/cask` to get the casks? Doing so gives me a "should be descendant of Homebrew taps directory" warning in `brew cask doctor`.

<details><summary>Output of `brew cask doctor`</summary>

```
==> macOS Release:
10.11.6
==> Hardware Architecture:
intel-64
==> Ruby Version:
2.0.0-p648
==> Ruby Path:
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
==> Homebrew Version:
Homebrew 0.9.9 (git revision 7395f; last commit 2016-08-19)
Homebrew/homebrew-core (git revision 5301; last commit 2016-08-20)
==> Homebrew Executable Path:
/usr/local/bin/brew
==> Homebrew Cellar Path:
/usr/local/Cellar
==> Homebrew Repository Path:
/usr/local
==> Homebrew Origin:
https://github.com/Homebrew/brew
==> Homebrew-Cask Version:
0.60.0 (git revision 326e; last commit 70 minutes ago)
==> Homebrew-Cask Install Location:
<NONE>
==> Homebrew-Cask Staging Location:
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads:
/Users/eric/Library/Caches/Homebrew/Cask
0 files, 0B
==> Homebrew-Cask Default Tap Path:
/usr/local/Library/Taps/caskroom/homebrew-cask
==> Homebrew-Cask Alternate Cask Taps:
==> Homebrew-Cask Default Tap Cask Count:
3270
==> Contents of $LOAD_PATH:
/usr/local/Library/Homebrew/cask/lib (error: should be descendant of Homebrew taps directory)
/usr/local/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin15
/Library/Ruby/Site/2.0.0/universal-darwin15
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15
==> Contents of $RUBYLIB Environment Variable:
<NONE>
==> Contents of $RUBYOPT Environment Variable:
<NONE>
==> Contents of $RUBYPATH Environment Variable:
<NONE>
==> Contents of $RBENV_VERSION Environment Variable:
<NONE>
==> Contents of $CHRUBY_VERSION Environment Variable:
<NONE>
==> Contents of $GEM_HOME Environment Variable:
<NONE>
==> Contents of $GEM_PATH Environment Variable:
<NONE>
==> Contents of $BUNDLE_PATH Environment Variable:
<NONE>
==> Contents of $PATH Environment Variable:
PATH="/Users/eric/.rbenv/shims:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Library/Homebrew/cask/cmd:/usr/local/Library/Homebrew/shims/scm"
==> Contents of $SHELL Environment Variable:
SHELL="/usr/local/bin/zsh"
==> Contents of Locale Environment Variables:
LANG="en_US.UTF-8"
==> Running As Privileged User:
No
```
</details>

**Comment by adidalal** [comment]
Yeh, probably https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cask/lib/hbc/cli/doctor.rb#L190 needs an update - HBC should work just fine, though.

**Comment by jawshooah** [comment]
@adidalal Confirmed this is a bug. We're not auto-tapping `caskroom/cask` anymore, which breaks assumptions elsewhere in the core code that we have the repo tapped.

To reproduce:

```
$ brew untap caskroom/cask
Untapping caskroom/cask... (7,517 files, 141.9M)
Untapped 0 formulae

$ brew cask list
1password (!)                cocoscreator (!)             font-fontawesome             grandperspective (!)         lastpass (!)                 slack (!)                    visual-studio-code (!)
adobe-air (!)                diffmerge (!)                font-hack                    intellij-idea (!)            launchcontrol (!)            sourcetree (!)               vlc (!)
atom (!)                     dropbox (!)                  font-source-code-pro         iterm2 (!)                   osxfuse (!)                  spectacle (!)                xfinity-wifi (!)
audacity (!)                 filezilla (!)                fuse (!)                     java (!)                     postgres (!)                 spotifree (!)                xquartz (!)
bartender (!)                flash (!)                    gitkraken (!)                java6                        postman (!)                  spotify (!)                  yakyak (!)
beardedspice (!)             flux (!)                     goofy (!)                    java7                        quickjson (!)                sublime-text (!)
box-edit (!)                 font-consolas-for-powerline  google-drive (!)             kindle (!)                   quip (!)                     virtualbox (!)

$ brew cask doctor
==> macOS Release:
10.11.6
==> Hardware Architecture:
intel-64
==> Ruby Version:
2.0.0-p648
==> Ruby Path:
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
==> Homebrew Version:
Homebrew 0.9.9 (git revision 5d60; last commit 2016-08-19)
Homebrew/homebrew-core (git revision efc271; last commit 2016-08-19)
==> Homebrew Executable Path:
/usr/local/bin/brew
==> Homebrew Cellar Path:
/usr/local/Cellar
==> Homebrew Repository Path:
/usr/local
==> Homebrew Origin:
https://github.com/Homebrew/brew
Error: No such file or directory - /usr/local/Library/Taps/caskroom/homebrew-cask
  Most likely, this means you have an outdated version of Homebrew-Cask. Please run:

      brew uninstall --force brew-cask; brew untap phinze/cask; brew untap caskroom/cask; brew update; brew cleanup; brew cask cleanup

  If this doesn’t fix the problem, please report this bug:

      https://github.com/caskroom/homebrew-cask#reporting-bugs

/usr/local/Library/Homebrew/cask/lib/hbc/version.rb:6:in `chdir'
/usr/local/Library/Homebrew/cask/lib/hbc/version.rb:6:in `full_version'
/usr/local/Library/Homebrew/cask/lib/hbc/cli/doctor.rb:13:in `run'
/usr/local/Library/Homebrew/cask/lib/hbc/cli.rb:108:in `run_command'
/usr/local/Library/Homebrew/cask/lib/hbc/cli.rb:146:in `process'
/usr/local/Library/Homebrew/cask/cmd/brew-cask.rb:8:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/Homebrew/brew.rb:19:in `require?'
/usr/local/Library/Homebrew/brew.rb:93:in `<main>'
```

**Comment by adidalal** [comment]
Looks to be solved, auto-tap was readded and updated pre bug report directions
