### ISSUE TITLE
Bug report: cask install adobe-photoshop-lighroom fails

### ISSUE THREAD

**Issue by kventil** [caskroom/homebrew-cask#24357]
Remember to follow the [pre bug report](https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/pre_bug_report.md) guide beforehand. Failure to do so might get your issue closed.

#### Description of issue

brew cask install adobe-photoshop-lighroom fails. 

<details><summary>Output of `brew cask install adobe-photoshop-lightroom --verbose`</summary>

```
➜  ~ brew cask install adobe-photoshop-lightroom --verbose
==> Caveats
Installation or Uninstallation may fail with Exit Code 19 (Conflicting Processes running) if Browsers, Safari Notification Service or SIMBL Services are running or Adobe Creative Cloud or any other Adobe Products are already installed. See Logs in /Library/Logs/Adobe/Installers if Installation or Uninstallation fails, to identify the conflicting processes.

==> Satisfying dependencies
==> Installing Cask dependencies: caskroom/versions/adobe-photoshop-lightroom600
Error: undefined method `join' for nil:NilClassMost likely, this means you have an outdated version of Homebrew-Cask. Please run:

    brew uninstall --force brew-cask; brew untap phinze/cask; brew untap caskroom/cask; brew update; brew cleanup; brew cask cleanup

If this doesn’t fix the problem, please report this bug:

    https://github.com/caskroom/homebrew-cask#reporting-bugs

/usr/local/Library/Homebrew/cask/lib/hbc/source/tapped_qualified.rb:10:in `path_for_query'
/usr/local/Library/Homebrew/cask/lib/hbc/source/tapped_qualified.rb:5:in `me?'
/usr/local/Library/Homebrew/cask/lib/hbc/source.rb:29:in `block in for_query'
/usr/local/Library/Homebrew/cask/lib/hbc/source.rb:27:in `each'
/usr/local/Library/Homebrew/cask/lib/hbc/source.rb:27:in `find'
/usr/local/Library/Homebrew/cask/lib/hbc/source.rb:27:in `for_query'
/usr/local/Library/Homebrew/cask/lib/hbc.rb:57:in `load'
/usr/local/Library/Homebrew/cask/lib/hbc/cask_dependencies.rb:17:in `block (2 levels) in graph_dependencies'
/usr/local/Library/Homebrew/cask/lib/hbc/cask_dependencies.rb:15:in `each'
/usr/local/Library/Homebrew/cask/lib/hbc/cask_dependencies.rb:15:in `block in graph_dependencies'
/usr/local/Library/Homebrew/cask/lib/hbc/cask_dependencies.rb:24:in `call'
/usr/local/Library/Homebrew/cask/lib/hbc/cask_dependencies.rb:24:in `graph_dependencies'
/usr/local/Library/Homebrew/cask/lib/hbc/cask_dependencies.rb:8:in `initialize'
/usr/local/Library/Homebrew/cask/lib/hbc/installer.rb:207:in `new'
/usr/local/Library/Homebrew/cask/lib/hbc/installer.rb:207:in `cask_dependencies'
/usr/local/Library/Homebrew/cask/lib/hbc/installer.rb:148:in `satisfy_dependencies'
/usr/local/Library/Homebrew/cask/lib/hbc/installer.rb:69:in `install'
/usr/local/Library/Homebrew/cask/lib/hbc/cli/install.rb:24:in `block in install_casks'
/usr/local/Library/Homebrew/cask/lib/hbc/cli/install.rb:18:in `each'
/usr/local/Library/Homebrew/cask/lib/hbc/cli/install.rb:18:in `install_casks'
/usr/local/Library/Homebrew/cask/lib/hbc/cli/install.rb:9:in `run'
/usr/local/Library/Homebrew/cask/lib/hbc/cli.rb:108:in `run_command'
/usr/local/Library/Homebrew/cask/lib/hbc/cli.rb:147:in `process'
/usr/local/Library/Homebrew/cask/cmd/brew-cask.rb:8:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/Homebrew/brew.rb:23:in `require?'
/usr/local/Library/Homebrew/brew.rb:97:in `<main>'
Error: Kernel.exit
```
</details>

<details><summary>Output of `brew doctor`</summary>

```
lease note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Some directories in /usr/local/share/man aren't writable.
This can happen if you "sudo make install" software that isn't managed
by Homebrew. If a brew tries to add locale information to one of these
directories, then the install will fail during the link step.

You should `sudo chown -R $(whoami)` them:
    /usr/local/share/man/de
    /usr/local/share/man/de/man1
```
</details>

<details><summary>Output of `brew cask doctor`</summary>

```
==> macOS Release:
10.11.6
==> Hardware Architecture:
intel-64
==> Ruby Version:
2.0.0-p648
==> Ruby Path:
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
==> Homebrew Version:
Homebrew 0.9.9 (git revision 1d66; last commit 2016-09-09)
Homebrew/homebrew-core (git revision 087c; last commit 2016-09-09)
==> Homebrew Executable Path:
/usr/local/bin/brew
==> Homebrew Cellar Path:
/usr/local/Cellar
==> Homebrew Repository Path:
/usr/local
==> Homebrew Origin:
https://github.com/Homebrew/brew
==> Homebrew-Cask Version:
0.60.0 (git revision 47b7; last commit 21 hours ago)
==> Homebrew-Cask Install Location:
<NONE>
==> Homebrew-Cask Staging Location:
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads:
/Users/robert/Library/Caches/Homebrew/Cask
6 files, 70.5M (warning: run "brew cask cleanup")
==> Homebrew-Cask Default Tap Path:
/usr/local/Library/Taps/caskroom/homebrew-cask
==> Homebrew-Cask Alternate Cask Taps:
==> Homebrew-Cask Default Tap Cask Count:
3295
==> Contents of $LOAD_PATH:
/usr/local/Library/Homebrew/cask/lib
/usr/local/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin15
/Library/Ruby/Site/2.0.0/universal-darwin15
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15
==> Contents of $RUBYLIB Environment Variable:
<NONE>
==> Contents of $RUBYOPT Environment Variable:
<NONE>
==> Contents of $RUBYPATH Environment Variable:
<NONE>
==> Contents of $RBENV_VERSION Environment Variable:
<NONE>
==> Contents of $CHRUBY_VERSION Environment Variable:
<NONE>
==> Contents of $GEM_HOME Environment Variable:
<NONE>
==> Contents of $GEM_PATH Environment Variable:
<NONE>
==> Contents of $BUNDLE_PATH Environment Variable:
<NONE>
==> Contents of $PATH Environment Variable:
PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/Library/TeX/texbin:/usr/local/Library/Homebrew/cask/cmd:/usr/local/Library/Homebrew/shims/scm"
==> Contents of $SHELL Environment Variable:
SHELL="/bin/zsh"
==> Contents of Locale Environment Variables:
LANG="en_CA.UTF-8"
LC_CTYPE="en_CA.UTF-8"
==> Running As Privileged User:
No

```
</details>

**Comment by vitorgalvao** [comment]
@fanquake Have you tried the command and have it fail on your system? Until we confirm it, it should not be labeled as a bug, as it may just be a problem in the user’s system.

**Comment by vitorgalvao** [comment]
The error is unrelated to the cask. Will open a new issue. For now, @kventil, run `brew tap `caskroom/versions` and then run the install command.
