### ISSUE TITLE
homebrew cask suddenly is detecting the wrong folder as the staging location

### ISSUE THREAD

**Issue by TheZoc** [caskroom/homebrew-cask#24664]
Hello,

I'm searching for a solution for 2~3 hours now, and I can't find anything specific like this on the web, nor a local solution.

It started when I installed a homebrew (not cask) package. I don't think I did anything other than that, that could affect homebrew cask. (the package was zsh-completions).

```
❯❯❯ cask doctor
==> macOS Release:
10.12
==> Hardware Architecture:
intel-64
==> Ruby Version:
2.0.0-p648
==> Ruby Path:
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
==> Homebrew Version:
Homebrew 0.9.9 (git revision f6fe; last commit 2016-09-20)
Homebrew/homebrew-core (git revision f58f; last commit 2016-09-20)
==> Homebrew Executable Path:
/usr/local/bin/brew
==> Homebrew Cellar Path:
/usr/local/Cellar
==> Homebrew Repository Path:
/usr/local/Homebrew
==> Homebrew Origin:
https://github.com/Homebrew/brew
==> Homebrew-Cask Version:
0.60.0 (git revision 2fcd; last commit 2 hours ago)
==> Homebrew-Cask Install Location:
<NONE>
==> Homebrew-Cask Staging Location:
/usr/local/Caskroom (error: path does not exist)}
==> Homebrew-Cask Cached Downloads:
/Users/zoc/Library/Caches/Homebrew/Cask
5 files, 111.4M (warning: run "brew cask cleanup")
==> Homebrew-Cask Default Tap Path:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask
==> Homebrew-Cask Alternate Cask Taps:
==> Homebrew-Cask Default Tap Cask Count:
3313
==> Contents of $LOAD_PATH:
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Contents of $RUBYLIB Environment Variable:
<NONE>
==> Contents of $RUBYOPT Environment Variable:
<NONE>
==> Contents of $RUBYPATH Environment Variable:
<NONE>
==> Contents of $RBENV_VERSION Environment Variable:
<NONE>
==> Contents of $CHRUBY_VERSION Environment Variable:
<NONE>
==> Contents of $GEM_HOME Environment Variable:
<NONE>
==> Contents of $GEM_PATH Environment Variable:
<NONE>
==> Contents of $BUNDLE_PATH Environment Variable:
<NONE>
==> Contents of $PATH Environment Variable:
PATH="/Users/zoc/.rbenv/shims:/Users/zoc/.rbenv/shims:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/cask/cmd:/usr/local/Homebrew/Library/Homebrew/shims/scm"
==> Contents of $SHELL Environment Variable:
SHELL="/usr/local/bin/zsh"
==> Contents of Locale Environment Variables:
LANG="en_US.UTF-8"
LC_CTYPE="UTF-8"
==> Running As Privileged User:
No
```

attempt to cleanup
```
❯❯❯ cask cleanup
==> Moving Caskroom from HOMEBREW_REPOSITORY to HOMEBREW_PREFIX
Error: Permission denied - (/usr/local/Homebrew/Caskroom, /usr/local/Caskroom)Most likely, this means you have an outdated version of Homebrew-Cask. Please run:

    brew uninstall --force brew-cask; brew untap phinze/cask; brew untap caskroom/cask; brew update; brew cleanup; brew cask cleanup

If this doesn’t fix the problem, please report this bug:

    https://github.com/caskroom/homebrew-cask#reporting-bugs

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:519:in `rename'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:519:in `block in mv'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1558:in `block in fu_each_src_dest'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1574:in `fu_each_src_dest0'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1556:in `fu_each_src_dest'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:508:in `mv'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/caskroom.rb:8:in `migrate_caskroom_from_repo_to_prefix'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc.rb:52:in `init'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:146:in `process'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/brew-cask.rb:8:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/brew.rb:23:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:105:in `<main>'
```

Permissions os `/usr/local/Homebrew/Caskroom`. The programs installed are still inside that directory.
```
 ❯❯❯ ls -la /usr/local/Homebrew/
total 80
drwxrwxr-x  18 zoc   admin   612 Sep 20 18:29 .
drwxr-xr-x  13 root  wheel   442 Sep 20 18:08 ..
-rw-r--r--@  1 zoc   admin  6148 Sep 20 18:29 .DS_Store
drwxr-xr-x  15 zoc   admin   510 Sep 20 18:44 .git
drwxr-xr-x   4 zoc   admin   136 Sep 20 17:31 .github
-rw-r--r--   1 zoc   admin  1023 Sep 20 17:31 .gitignore
-rw-r--r--   1 zoc   admin   154 Sep 16 19:43 .travis.yml
-rw-r--r--   1 zoc   admin   291 Sep 11 15:59 .yardopts
-rw-r--r--   1 zoc   admin  3161 Sep 11 15:59 CODEOFCONDUCT.md
-rw-r--r--   1 zoc   admin   697 Sep 20 17:31 CONTRIBUTING.md
drwxrwxr-x  17 zoc   admin   578 Sep 20 18:29 Caskroom
-rw-r--r--   1 zoc   admin  1241 Sep 11 15:59 LICENSE.txt
drwxr-xr-x   9 zoc   admin   306 Sep 20 17:31 Library
-rw-r--r--   1 zoc   admin  5765 Sep 20 17:31 README.md
drwxr-xr-x   3 zoc   admin   102 Sep 11 15:59 bin
drwxr-xr-x   4 zoc   admin   136 Sep 20 17:31 completions
drwxr-xr-x  39 zoc   admin  1326 Sep 20 17:31 docs
drwxr-xr-x   4 zoc   admin   136 Sep 20 17:31 manpages
```

Listing of `/usr/local`. There is no `Caskroom` there. I guess it was never meant to be there.

```
 ❯❯❯ ls -la /usr/local
total 0
drwxr-xr-x   13 root  wheel   442 Sep 20 18:08 .
drwxr-xr-x@  11 root  wheel   374 Sep 11 15:55 ..
drwxrwxr-x   56 zoc   admin  1904 Sep 20 17:57 Cellar
drwxrwxr-x    3 zoc   admin   102 Sep 12 04:18 Frameworks
drwxrwxr-x   18 zoc   admin   612 Sep 20 18:29 Homebrew
drwxrwxr-x  202 zoc   admin  6868 Sep 20 17:57 bin
drwxr-xr-x    9 zoc   admin   306 Sep 17 03:18 etc
drwxrwxr-x   73 zoc   admin  2482 Sep 20 17:57 include
drwxrwxr-x  202 zoc   admin  6868 Sep 20 17:57 lib
drwxrwxr-x   56 zoc   admin  1904 Sep 20 17:57 opt
drwxrwxr-x    6 zoc   admin   204 Sep 13 06:22 sbin
drwxr-xr-x   25 zoc   admin   850 Sep 20 17:50 share
drwxrwxr-x    3 zoc   admin   102 Sep 20 17:31 var
```

output of `brew --repository`
```
 ❯❯❯ brew --repository
/usr/local/Homebrew
```

Attempting to follow the instructions of `brew cask cleanup`
```
brew uninstall --force brew-cask; brew untap phinze/cask; brew untap caskroom/cask; brew update; brew cleanup; brew cask cleanup
Error: No available tap phinze/cask.
Untapping caskroom/cask... (3,431 files, 3.6M)
Untapped 0 formulae
Already up-to-date.
Warning: Skipping aria2: most recent version 1.27.1 not installed
Warning: Skipping pkg-config: most recent version 0.29.1_2 not installed
Warning: Skipping x264: most recent version r2699 not installed
==> Tapping caskroom/cask
Cloning into '/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask'...
remote: Counting objects: 3423, done.
remote: Compressing objects: 100% (3404/3404), done.
remote: Total 3423 (delta 37), reused 451 (delta 13), pack-reused 0
Receiving objects: 100% (3423/3423), 1.15 MiB | 613.00 KiB/s, done.
Resolving deltas: 100% (37/37), done.
Tapped 0 formulae (3,431 files, 3.6M)
==> Moving Caskroom from HOMEBREW_REPOSITORY to HOMEBREW_PREFIX
Error: Permission denied - (/usr/local/Homebrew/Caskroom, /usr/local/Caskroom)Most likely, this means you have an outdated version of Homebrew-Cask. Please run:

    brew uninstall --force brew-cask; brew untap phinze/cask; brew untap caskroom/cask; brew update; brew cleanup; brew cask cleanup

If this doesn’t fix the problem, please report this bug:

    https://github.com/caskroom/homebrew-cask#reporting-bugs

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:519:in `rename'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:519:in `block in mv'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1558:in `block in fu_each_src_dest'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1574:in `fu_each_src_dest0'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1556:in `fu_each_src_dest'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:508:in `mv'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/caskroom.rb:8:in `migrate_caskroom_from_repo_to_prefix'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc.rb:52:in `init'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:146:in `process'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/brew-cask.rb:8:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/brew.rb:23:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:105:in `<main>'
>>> elapsed time 30s                       
```

I've tried to adjust the path manually like this:
```
❯❯❯ export HOMEBREW_CASK_OPTS='--appdir=/Applications --caskroom=$(brew --repository)/Caskroom'
```

but I get

```
❯❯❯ brew cask doctor
Error: wrong number of arguments (1 for 0)Most likely, this means you have an outdated version of Homebrew-Cask. Please run:

    brew uninstall --force brew-cask; brew untap phinze/cask; brew untap caskroom/cask; brew update; brew cleanup; brew cask cleanup

If this doesn’t fix the problem, please report this bug:

    https://github.com/caskroom/homebrew-cask#reporting-bugs

/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/doctor.rb:2:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:108:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:147:in `process'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/brew-cask.rb:8:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/brew.rb:23:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:105:in `<main>'
```

So I just reverted it.

What should I do to fix this? :(

**Comment by TheZoc** [comment]
After posting, I saw the issue #24663, posted a couple minutes before mine. It is probably the same issue.

**Comment by victorpopkov** [comment]
Yes, it's the same issue that was first described in https://github.com/caskroom/homebrew-cask/issues/24638.

Try temporary setting owning permissions to current user in the `/usr/local` directory and then update Homebrew:
```bash
sudo chown -R $USER /usr/local
brew update --force
```

**Comment by TheZoc** [comment]
@victorpopkov  Thank you!
Doing that (the -R flag was **not** needed) and running `cask list` did the trick (`cask doctor` alone doesn't work).

I expect more of this issue being opened since there is no sticky or instructions regarding this change.

Thank you very much again!
