### ISSUE TITLE
Permission denied OSX Sierra

### ISSUE THREAD

**Issue by danielgomezrico** [caskroom/homebrew-cask#24772]
Versions:
```
$ brew --version
Homebrew >1.0.0 (no git repository)
Homebrew/homebrew-core (git revision 643a; last commit 2016-09-23)

$ brew cask --version
0.60.0 (git revision 508c; last commit 26 minutes ago)
```

OSX Version: `10.12`

When I try to install any cask I get permission error:

```
$ brew install sourcetree
==> brew cask install Caskroom/cask/sourcetree
Error: Permission denied - /Users/danielgomez22Most likely, this means you have an outdated version of Homebrew-Cask. Please run:

    brew uninstall --force brew-cask; brew untap phinze/cask; brew untap caskroom/cask; brew update; brew cleanup; brew cask cleanup

If this doesn’t fix the problem, please report this bug:

    https://github.com/caskroom/homebrew-cask#reporting-bugs

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:245:in `mkdir'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:245:in `fu_mkdir'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:219:in `block (2 levels) in mkdir_p'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:217:in `reverse_each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:217:in `block in mkdir_p'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:203:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:203:in `mkdir_p'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:559:in `mkpath'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cache.rb:7:in `ensure_cache_exists'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc.rb:49:in `init'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:146:in `process'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/brew-cask.rb:8:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/brew.rb:23:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:105:in `<main>'
```

Already tried with 
```
$ export HOMEBREW_CASK_OPTS="--appdir=~/Applications --caskroom=~/Caskroom"
``` 

and 

```
    brew uninstall --force brew-cask; brew untap phinze/cask; brew untap caskroom/cask; brew update; brew cleanup; brew cask cleanup
```

but still got error...

What is happening?

**Comment by danielgomezrico** [comment]
Just uninstall brew and install again and it works now

```
$ /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)"
$ /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
```

Maybe something happened on install and I didnt notice

**Comment by danielgomezrico** [comment]
But it fails here

```
==> Moving App 'SourceTree.app' to '/Users/danielgomez22/Applications/SourceTree.app'
```

Full trace:
```
$ brew install Caskroom/cask/sourcetree
==> Tapping caskroom/cask
Cloning into '/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask'...
remote: Counting objects: 3437, done.
remote: Compressing objects: 100% (3418/3418), done.
remote: Total 3437 (delta 37), reused 460 (delta 13), pack-reused 0
Receiving objects: 100% (3437/3437), 1.16 MiB | 889.00 KiB/s, done.
Resolving deltas: 100% (37/37), done.
Checking connectivity... done.
Tapped 0 formulae (3,445 files, 3.6M)
==> brew cask install Caskroom/cask/sourcetree
==> Creating Caskroom at /Users/danielgomez22/Caskroom/usr/bin/ruby
==> We'll set permissions properly so we won't need sudo in the future
Password:
==> Caveats
Cask sourcetree installs files under "/usr/local". The presence of such
files can cause warnings when running "brew doctor", which is considered
to be a bug in Homebrew-Cask.

==> Downloading https://downloads.atlassian.com/software/sourcetree/SourceTree_2.3.1.zip
######################################################################## 100.0%
==> Verifying checksum for Cask sourcetree
==> Moving App 'SourceTree.app' to '/Users/danielgomez22/Applications/SourceTree.app'
Error: Permission denied - /Users/danielgomez22/ApplicationsMost likely, this means you have an outdated version of Homebrew-Cask. Please run:

    brew uninstall --force brew-cask; brew untap phinze/cask; brew untap caskroom/cask; brew update; brew cleanup; brew cask cleanup

If this doesn’t fix the problem, please report this bug:

    https://github.com/caskroom/homebrew-cask#reporting-bugs

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:245:in `mkdir'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:245:in `fu_mkdir'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:219:in `block (2 levels) in mkdir_p'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:217:in `reverse_each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:217:in `block in mkdir_p'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:203:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:203:in `mkdir_p'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:559:in `mkpath'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/moved.rb:36:in `move'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/moved.rb:13:in `block in install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/moved.rb:30:in `block in each_artifact'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/moved.rb:29:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/moved.rb:29:in `each_artifact'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/moved.rb:9:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:134:in `block in install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:131:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:131:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:74:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:24:in `block in install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:18:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:18:in `install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:9:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:108:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:147:in `process'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/brew-cask.rb:8:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/brew.rb:23:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:105:in `<main>'
```

**Comment by vitorgalvao** [comment]
Please follow the [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) guide. There’s missing information we need, that the guide presents.
