### ISSUE TITLE
HBC errors out when trying to install a non-existing cask via a full name (caskroom/cask/something)

### ISSUE THREAD

**Issue by 9lkd** [caskroom/homebrew-cask#25095]
#### Description of issue

I installed the brew-cask before, and reinstall the homebrew, but didn't uninstall the brew-cask.
When I install the cask using ‘brew install caskroom/cask/brew-cask’, It returns this:

```
192% brew install caskroom/cask/brew-cask
==> brew cask install caskroom/cask/brew-cask
Warning: The default Caskroom location has moved to /usr/local/Caskroom.

Please migrate your Casks to the new location and delete /opt/homebrew-cask/Caskroom,
or if you would like to keep your Caskroom at /opt/homebrew-cask/Caskroom, add the
following to your HOMEBREW_CASK_OPTS:

  --caskroom=/opt/homebrew-cask/Caskroom

For more details on each of those options, see https://github.com/caskroom/homebrew-cask/issues/21913.
Error: Tap caskroom/cask already tapped.
Most likely, this means you have an outdated version of Homebrew-Cask. Please run:

    brew uninstall --force brew-cask; brew untap phinze/cask; brew untap caskroom/cask; brew update; brew cleanup; brew cask cleanup

If this doesn’t fix the problem, please report this bug:

    https://github.com/caskroom/homebrew-cask#reporting-bugs

/usr/local/Homebrew/Library/Homebrew/tap.rb:189:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/source/untapped_qualified.rb:9:in `me?'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/source.rb:28:in `block in for_query'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/source.rb:26:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/source.rb:26:in `find'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/source.rb:26:in `for_query'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc.rb:58:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:21:in `block in install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:19:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:19:in `install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:10:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:107:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:146:in `process'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/brew-cask.rb:8:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/brew.rb:23:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:105:in `<main>'
```

<details><summary>

Output of `brew cask <command> --verbose`</summary>

```
192% brew cask <command> --verbose
zsh: no such file or directory: command
```

</details>

<details><summary>

Output of `brew doctor`</summary>

```
192% brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Python is installed at /Library/Frameworks/Python.framework

Homebrew only supports building against the System-provided Python or a
brewed Python. In particular, Pythons installed to /Library can interfere
with other software installs.

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.zshrc
```

</details>

<details><summary>

Output of `brew cask doctor`</summary>

```
192% brew cask doctor
==> Tapping caskroom/cask
Cloning into '/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask'...
fatal: unable to access 'https://github.com/caskroom/homebrew-cask/': Could not resolve host: github.com
Error: Failure while executing: git clone https://github.com/caskroom/homebrew-cask /usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask --depth=1Most likely, this means you have an outdated version of Homebrew-Cask. Please run:

    brew uninstall --force brew-cask; brew untap phinze/cask; brew untap caskroom/cask; brew update; brew cleanup; brew cask cleanup

If this doesn’t fix the problem, please report this bug:

    https://github.com/caskroom/homebrew-cask#reporting-bugs

/usr/local/Homebrew/Library/Homebrew/utils.rb:360:in `safe_system'
/usr/local/Homebrew/Library/Homebrew/tap.rb:216:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:144:in `process'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/brew-cask.rb:8:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/brew.rb:23:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:105:in `<main>'
```

</details>

**Comment by Numbermaniac** [comment]
Did you do the commands it told you to?

**Comment by reitermarkus** [comment]
First of all, you don't need to install `brew-cask` anymore, since it is now integrated in Homebrew. So if you have `brew`, you also have `brew cask`.

Anyway, thanks for pointing out this bug. This will happen if you try to install a cask by passing a full name (`caskroom/cask/something`) and the cask doesn't exist.
