### ISSUE TITLE
Can't uninstall intel-haxm (ruby exception)

### ISSUE THREAD

**Issue by hraban** [caskroom/homebrew-cask#25479]
```
Hrabans-MacBook-Pro:~ hraban$ brew cask uninstall intel-haxm
==> Running uninstall process for intel-haxm; your password may be necessary
==> Running uninstall script silent_install.sh
Password:
==> HAXM silent installation only support mac OS X from 10.8 to 10.10 !
Error: no implicit conversion of Array into String
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/exceptions.rb:71:in `concat'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/exceptions.rb:71:in `to_s'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:150:in `message'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:150:in `rescue in process'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:143:in `process'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/brew-cask.rb:8:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/brew.rb:24:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

```
Hrabans-MacBook-Pro:~ hraban$ brew cask install intel-haxm
Warning: A Cask for intel-haxm is already installed.

To re-install intel-haxm, run:
  brew cask uninstall --force intel-haxm && brew cask install intel-haxm
```

```
Hrabans-MacBook-Pro:~ hraban$ brew cask uninstall  --force intel-haxm
==> Running uninstall process for intel-haxm; your password may be necessary
==> Running uninstall script silent_install.sh
==> HAXM silent installation only support mac OS X from 10.8 to 10.10 !
Error: no implicit conversion of Array into String
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/exceptions.rb:71:in `concat'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/exceptions.rb:71:in `to_s'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:150:in `message'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:150:in `rescue in process'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:143:in `process'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/brew-cask.rb:8:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/brew.rb:24:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

**Comment by hraban** [comment]
Information about my system:

```
Hrabans-MacBook-Pro:~ hraban$ brew --version
Homebrew 1.0.7
Homebrew/homebrew-core (git revision 59d7; last commit 2016-10-11)
```

```
Hrabans-MacBook-Pro:~ hraban$ uname -a
Darwin Hrabans-MacBook-Pro.local 15.6.0 Darwin Kernel Version 15.6.0: Mon Aug 29 20:21:34 PDT 2016; root:xnu-3248.60.11~1/RELEASE_X86_64 x86_64
```

``` 
Hrabans-MacBook-Pro:~ hraban$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.11.6
BuildVersion:	15G1004
```

**Comment by reitermarkus** [comment]
Actually, the exception isn't really helpful because there actually is an error in the exception itself. But the error is pretty obvious:

```
HAXM silent installation only support mac OS X from 10.8 to 10.10 !
```

Try `brew cask install --force intel-haxm; brew cask uninstall --force intel-haxm`.

**Comment by hraban** [comment]
Thanks, brew install --force works. But doesn't this leave artifacts of
intel-haxm 1.0.4 lying around? How can I check for that, and optionally
delete those? (I was trying to update to v6, btw, so I'm leaving off the
uninstall).

**Comment by reitermarkus** [comment]
> But doesn't this leave artifacts of intel-haxm 1.0.4 lying around?

Yes, that's why i suggested `brew cask uninstall --force intel-haxm` (before then again running `brew cask install`). This removes all versions from the Caskroom (note that only the most recent version of the uninstall script is used, so there is no guarantee that all files that were installed with the old version are removed).

**Comment by hraban** [comment]
Perfect, will do. Thanks!
