### ISSUE TITLE
permission bug

### ISSUE THREAD

**Issue by palindrom615** [caskroom/homebrew-cask#25548]
permission message when I install a cask, like this:
`brew cask install vlc`

and this is the output.
```
==> Downloading https://get.videolan.org/vlc/2.2.4/macosx/vlc-2.2.4.dmg
Error: Download failed on Cask 'vlc' with message: Permission denied - /Users/palindrom615/Library/Caches/Homebrew/Cask/vlc--2.2.4.dmg.incomplete
```

I untabbed and reinstalled brew-cask a few times and nothing changed. both brew and brew cask are already-updated. nothing special on brew doctor and here's what brew cask doctor

```
==> macOS Release:
10.12
==> Hardware Architecture:
intel-64
==> Ruby Version:
2.0.0-p648
==> Ruby Path:
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
==> Homebrew Version:
Homebrew 1.0.7
Homebrew/homebrew-core (git revision 552e; last commit 2016-10-16)
==> Homebrew Executable Path:
/usr/local/bin/brew
==> Homebrew Cellar Path:
/usr/local/Cellar
==> Homebrew Repository Path:
/usr/local/Homebrew
==> Homebrew Origin:
https://github.com/Homebrew/brew
==> Homebrew-Cask Version:
Homebrew-Cask 1.0.7
caskroom/homebrew-cask (git revision 8697; last commit 2016-10-16)
==> Homebrew-Cask Install Location:
<NONE>
==> Homebrew-Cask Staging Location:
/Users/palindrom615/Caskroom
==> Homebrew-Cask Cached Downloads:
/Users/palindrom615/Library/Caches/Homebrew/Cask
10 files, 7M (warning: run "brew cask cleanup")
==> Homebrew-Cask Default Tap Path:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask
==> Homebrew-Cask Alternate Cask Taps:
==> Homebrew-Cask Default Tap Cask Count:
3390
==> Contents of $LOAD_PATH:
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Contents of $RUBYLIB Environment Variable:
<NONE>
==> Contents of $RUBYOPT Environment Variable:
<NONE>
==> Contents of $RUBYPATH Environment Variable:
<NONE>
==> Contents of $RBENV_VERSION Environment Variable:
<NONE>
==> Contents of $CHRUBY_VERSION Environment Variable:
<NONE>
==> Contents of $GEM_HOME Environment Variable:
<NONE>
==> Contents of $GEM_PATH Environment Variable:
<NONE>
==> Contents of $BUNDLE_PATH Environment Variable:
<NONE>
==> Contents of $PATH Environment Variable:
PATH="/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Applications/Server.app/Contents/ServerRoot/usr/bin:/Applications/Server.app/Contents/ServerRoot/usr/sbin:/usr/local/Homebrew/Library/Homebrew/cask/cmd:/usr/local/Homebrew/Library/Homebrew/shims/scm"
==> Contents of $SHELL Environment Variable:
SHELL="/bin/zsh"
==> Contents of Locale Environment Variables:
LANG="ko_KR.UTF-8"
LC_ALL="ko_KR.UTF-8"
==> Running As Privileged User:
No
```

and `brew cask cleanup` just say permission denied again. `brew cleanup` work though.
here's what they say.

```
==> Removing cached downloads
/Users/palindrom615/Library/Caches/Homebrew/Cask/betterzipql--latest.zip
Error: Permission denied - /Users/palindrom615/Library/Caches/Homebrew/Cask/betterzipql--latest.zipMost likely, this means you have an outdated version of Homebrew-Cask. Please run:
  brew uninstall --force brew-cask; brew untap phinze/cask; brew untap caskroom/cask; brew update; brew cleanup; brew cask cleanup

If this doesn’t fix the problem, please report this bug:
  https://github.com/caskroom/homebrew-cask#reporting-bugs

/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/cleanup.rb:100:in `unlink'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/cleanup.rb:100:in `unlink'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/cleanup.rb:100:in `block in delete_paths'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/cleanup.rb:90:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/cleanup.rb:90:in `delete_paths'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/cleanup.rb:84:in `remove_cache_files'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/cleanup.rb:34:in `cleanup!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/cleanup.rb:17:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:109:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:148:in `process'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/brew-cask.rb:8:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/brew.rb:24:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```
I copied and pasted that `brew uninstall --force brew-cask; brew untap phinze/cask; brew untap caskroom/cask; brew update; brew cleanup; brew cask cleanup` a few times but every time `brew cask cleanup ` stuck with the message permission denied.

sure, I wrote `export HOMEBREW_CASK_OPTS="--appdir=~/Applications"` on my ~/.zshrc and `source .zshrc`ed and tried with quite many casks(not every, though :) ), and googled with  keyword 'brew cask permission' things and I found that they were quite outdated.

terribly sorry for being duplicated with [https://github.com/caskroom/homebrew-cask/issues/25547](https://github.com/caskroom/homebrew-cask/issues/25547), I just pressed return key by mistake before I wrote anything, and after writing the issue already closed.

**Comment by adidalal** [comment]
Looks solved? https://github.com/caskroom/homebrew-cask/issues/25547#issuecomment-254062976
