### ISSUE TITLE
Bug report: brew cask info dropbox

### ISSUE THREAD

**Issue by miccal** [caskroom/homebrew-cask#25611]
#### Description of issue

Within the last 24 hours, running the `brew cask info dropbox` command reports that `Error: File '/Users/$USER/dropbox' is not a plain file`.

I have checked this on two machines, and they both are reporting this.

<details><summary>Output of `brew cask <command> --verbose`</summary>

```
-bash-4.4.0- /Users/$USER [> brew cask info dropbox --verbose
Error: File '/Users/$USER/dropbox' is not a plain file
Error: Kernel.exit
```
</details>

<details><summary>Output of `brew doctor`</summary>

```
-bash-4.4.0- /Users/$USER [> brew doctor
Your system is ready to brew.
```
</details>

<details><summary>Output of `brew cask doctor`</summary>

```
-bash-4.4.0- /Users/$USER [> brew cask doctor
==> macOS Release:
10.12
==> Hardware Architecture:
intel-64
==> Ruby Version:
2.0.0-p648
==> Ruby Path:
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
==> Homebrew Version:
Homebrew 1.0.8
Homebrew/homebrew-core (git revision 4b1c4; last commit 2016-10-17)
==> Homebrew Executable Path:
/usr/local/bin/brew
==> Homebrew Cellar Path:
/usr/local/Cellar
==> Homebrew Repository Path:
/usr/local/Homebrew
==> Homebrew Origin:
https://github.com/Homebrew/brew
==> Homebrew-Cask Version:
Homebrew-Cask 1.0.8
caskroom/homebrew-cask (git revision 9c4ba; last commit 2016-10-18)
==> Homebrew-Cask Install Location:
<NONE>
==> Homebrew-Cask Staging Location:
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads:
/Users/$USER/Library/Caches/Homebrew/Cask
0 files, 0B
==> Homebrew-Cask Default Tap Path:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask
==> Homebrew-Cask Alternate Cask Taps:
==> Homebrew-Cask Default Tap Cask Count:
3394
==> Contents of $LOAD_PATH:
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Contents of $RUBYLIB Environment Variable:
<NONE>
==> Contents of $RUBYOPT Environment Variable:
<NONE>
==> Contents of $RUBYPATH Environment Variable:
<NONE>
==> Contents of $RBENV_VERSION Environment Variable:
<NONE>
==> Contents of $CHRUBY_VERSION Environment Variable:
<NONE>
==> Contents of $GEM_HOME Environment Variable:
<NONE>
==> Contents of $GEM_PATH Environment Variable:
<NONE>
==> Contents of $BUNDLE_PATH Environment Variable:
<NONE>
==> Contents of $PATH Environment Variable:
PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/TeX/texbin:/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/cmd:/usr/local/Homebrew/Library/Homebrew/cask/cmd:/usr/local/Homebrew/Library/Homebrew/shims/scm"
==> Contents of $SHELL Environment Variable:
SHELL="/usr/local/bin/bash"
==> Contents of Locale Environment Variables:
LANG="en_AU.UTF-8"
==> Running As Privileged User:
No
```
</details>

**Comment by jawshooah** [comment]
Can you show me the output of `brew cask info dropbox --debug`?

**Comment by miccal** [comment]
As requested:

```
-bash-4.4.0- /Users/$USER [> brew cask info dropbox --debug
==> Getting info for Cask dropbox
==> Loading Cask definitions
==> Translating 'dropbox' into a valid Cask source
==> Testing source class Hbc::Source::URI
==> Testing source class Hbc::Source::PathSlashRequired
==> Testing source class Hbc::Source::TappedQualified
==> Testing source class Hbc::Source::UntappedQualified
==> Testing source class Hbc::Source::Tapped
==> Success! Using source class Hbc::Source::Tapped
==> Resolved Cask URI or file source to '/Users/$USER/dropbox'
Error: File '/Users/$USER/dropbox' is not a plain file/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:6:in `load_from_file'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/source/path_base.rb:20:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/source/tapped.rb:15:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc.rb:57:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/info.rb:9:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/info.rb:7:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/info.rb:7:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:109:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:148:in `process'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/brew-cask.rb:8:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/brew.rb:24:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:153:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:153:in `rescue in process'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:143:in `process'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/brew-cask.rb:8:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/brew.rb:24:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

**Comment by jawshooah** [comment]
I can reproduce. When there is a file named `dropbox` (or whatever the name of the Cask is) in the current working directory, `Hbc.path` attempts to read it in as the Cask file. In this particular case, I was able to reproduce by creating a `dropbox` symlink in my CWD. Thanks for the bug report!

**Comment by miccal** [comment]
You're welcome. I run `brew cu` to update my casks regularly (a `tap` of `buo/cask-upgrade`) and running it today showed this error.

**Comment by jawshooah** [comment]
Opened a PR with the fix: https://github.com/Homebrew/brew/issues/1315

**Comment by miccal** [comment]
Thanks @jawshooah.

**Comment by jawshooah** [comment]
Closed in favor of Homebrew/brew#1315.

**Comment by miccal** [comment]
Hello @jawshooah, I noticed that [Homebrew/brew#1315](https://github.com/Homebrew/brew/pull/1315) has been merged, but the problem is still persisting.

**Comment by adidalal** [comment]
@miccal I think a new brew release needs to be cut (tagged) for the changes to actually be pushed out.

**Comment by miccal** [comment]
Ah, I forgot about that, thanks @adidalal.

**Comment by jawshooah** [comment]
@miccal If you don't want to wait, you could just manually `cd "$(brew --repository)" && git fetch origin master:master && git checkout master`

**Comment by miccal** [comment]
Thanks @jawshooah.

**Comment by RJHsiao** [comment]
Just notice that: not only dropbox, but also megasync had same issue.

**Comment by jawshooah** [comment]
@RJHsiao Yes, as would any cask that happens to share a name with a file in current working directory :wink:

**Comment by RJHsiao** [comment]
👍
