### ISSUE TITLE
Bug report: uninstalling terminology fails

### ISSUE THREAD

**Issue by Eitot** [caskroom/homebrew-cask#26029]
Uninstallation fails with this message (replaced my username with `[username]`). I also tried the suggested fix.

<details><summary>Output of `brew cask uninstall terminology --verbose`</summary>
```
==> Running uninstall process for terminology; your password may be necessary
==> Removing files: ["#<Pathname:/Users/[username]/Library/Dictionaries/Terminology.dictionary>"]
Error: undefined method `start_with?' for #<Pathname:0x007fd6fd8c9e08>Most likely, this means you have an outdated version of Homebrew-Cask. Please run:

    brew uninstall --force brew-cask; brew untap phinze/cask; brew untap caskroom/cask; brew update; brew cleanup; brew cask cleanup

If this doesn’t fix the problem, please report this bug:

    https://github.com/caskroom/homebrew-cask#reporting-bugs

/Users/[username]/.homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:32:in `block in expand_path_strings'
/Users/[username]/.homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:31:in `map'
/Users/[username]/.homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:31:in `expand_path_strings'
/Users/[username]/.homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:219:in `block in uninstall_delete'
/Users/[username]/.homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:217:in `each_slice'
/Users/[username]/.homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:217:in `uninstall_delete'
/Users/[username]/.homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:76:in `block (2 levels) in dispatch_uninstall_directives'
/Users/[username]/.homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:73:in `each'
/Users/[username]/.homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:73:in `block in dispatch_uninstall_directives'
/Users/[username]/.homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:72:in `each'
/Users/[username]/.homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:72:in `dispatch_uninstall_directives'
/Users/[username]/.homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:61:in `uninstall_phase'
/Users/[username]/.homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:301:in `block in uninstall_artifacts'
/Users/[username]/.homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:298:in `each'
/Users/[username]/.homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:298:in `uninstall_artifacts'
/Users/[username]/.homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:289:in `uninstall'
/Users/[username]/.homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:26:in `block in run'
/Users/[username]/.homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:9:in `each'
/Users/[username]/.homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:9:in `run'
/Users/[username]/.homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:107:in `run_command'
/Users/[username]/.homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:146:in `process'
/Users/[username]/.homebrew/Library/Homebrew/cask/cmd/brew-cask.rb:8:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Users/[username]/.homebrew/Library/Homebrew/brew.rb:23:in `require?'
/Users/[username]/.homebrew/Library/Homebrew/brew.rb:105:in `<main>'
Error: Kernel.exit
```
</details>

<details><summary>Output of `brew doctor`</summary>

```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Your Homebrew is not installed to /usr/local
You can install Homebrew anywhere you want but some bottles (binary
packages) can only be used in /usr/local and some formulae (packages)
may not build correctly unless you install in /usr/local. Sorry!
```
</details>

<details><summary>Output of `brew cask doctor`</summary>

```
==> macOS Release:
10.11.6
==> Hardware Architecture:
intel-64
==> Ruby Version:
2.0.0-p648
==> Ruby Path:
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
==> Homebrew Version:
Homebrew 1.0.4
Homebrew/homebrew-core (git revision f9a5c; last commit 2016-10-22)
==> Homebrew Executable Path:
/Users/[username]/.homebrew/bin/brew
==> Homebrew Cellar Path:
/Users/[username]/.homebrew/Cellar
==> Homebrew Repository Path:
/Users/[username]/.homebrew
==> Homebrew Origin:
https://github.com/Homebrew/brew
==> Homebrew-Cask Version:
0.60.0 (git revision 7df9; last commit 16 minutes ago)
==> Homebrew-Cask Install Location:
<NONE>
==> Homebrew-Cask Staging Location:
/Users/[username]/.homebrew/Caskroom
==> Homebrew-Cask Cached Downloads:
/Users/[username]/Library/Caches/Homebrew/Cask
0 files, 0B
==> Homebrew-Cask Default Tap Path:
/Users/[username]/.homebrew/Library/Taps/caskroom/homebrew-cask
==> Homebrew-Cask Alternate Cask Taps:
==> Homebrew-Cask Default Tap Cask Count:
3406
==> Contents of $LOAD_PATH:
/Users/[username]/.homebrew/Library/Homebrew/cask/lib
/Users/[username]/.homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin15
/Library/Ruby/Site/2.0.0/universal-darwin15
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15
==> Contents of $RUBYLIB Environment Variable:
<NONE>
==> Contents of $RUBYOPT Environment Variable:
<NONE>
==> Contents of $RUBYPATH Environment Variable:
<NONE>
==> Contents of $RBENV_VERSION Environment Variable:
<NONE>
==> Contents of $CHRUBY_VERSION Environment Variable:
<NONE>
==> Contents of $GEM_HOME Environment Variable:
<NONE>
==> Contents of $GEM_PATH Environment Variable:
<NONE>
==> Contents of $BUNDLE_PATH Environment Variable:
<NONE>
==> Contents of $PATH Environment Variable:
PATH="/Users/[username]/.homebrew/bin:/Users/[username]/.homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/Library/TeX/texbin:/Users/[username]/.homebrew/Library/Homebrew/cask/cmd:/Users/[username]/.homebrew/Library/Homebrew/shims/scm"
==> Contents of $SHELL Environment Variable:
SHELL="/bin/bash"
==> Contents of Locale Environment Variables:
LC_CTYPE="UTF-8"
==> Running As Privileged User:
No
```
</details>

**Comment by Eitot** [comment]
@adidalal: I’ve updated my local repo with your fix and the error is the same.

**Comment by adidalal** [comment]
Your Homebrew cask is out of date. Can you follow the pre bug report directions in the readme

**Comment by adidalal** [comment]
(We deprecated license).

**Comment by Eitot** [comment]
I thought I did follow the instructions. Anyway, I cannot uninstall this with a standard user account. I will supply a fix to use a generic artifact instead.

**Comment by adidalal** [comment]
Your homebrew is outdated. Once that is fixed, we can work from there.
`cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update`

Should be:
```
==> Homebrew Version:
Homebrew 1.0.8
Homebrew/homebrew-core (git revision 88b8; last commit 2016-10-22)
```

**Comment by Eitot** [comment]
My problem is already solved. A hard reset of the Homebrew repo resolved the issue. Nevertheless, I submitted a PR to address the permission problem.

**Comment by adidalal** [comment]
Yep, thanks!
