### ISSUE TITLE
Bug report: uninitialized constant Hbc::QualifiedToken::HOMEBREW_TAP_CASK_REGEX

### ISSUE THREAD

**Issue by AlmightyOatmeal** [caskroom/homebrew-cask#26559]
#### Description of issue

Attempting to install `brew install --verbose Caskroom/cask/handbrakecli` fails with `Error: uninitialized constant Hbc::QualifiedToken::HOMEBREW_TAP_CASK_REGEX`.

<details><summary>Output of `brew cask install Caskroom/cask/handbrakecli --verbose`</summary>

```
==> brew cask install Caskroom/cask/handbrakecli --verbose
brew cask install Caskroom/cask/handbrakecli --verbose
Error: uninitialized constant Hbc::QualifiedToken::HOMEBREW_TAP_CASK_REGEX
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/pre_bug_report.md

If this doesn’t fix the problem, please report this bug:
  https://github.com/caskroom/homebrew-cask#reporting-bugs

/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/qualified_token.rb:5:in `parse'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/source/tapped_qualified.rb:13:in `tap_for_query'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/source/tapped_qualified.rb:7:in `me?'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/source.rb:28:in `block in for_query'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/source.rb:26:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/source.rb:26:in `find'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/source.rb:26:in `for_query'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc.rb:57:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:21:in `block in install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:19:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:19:in `install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:10:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:110:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:149:in `process'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/brew-cask.rb:8:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/Homebrew/brew.rb:23:in `require?'
/usr/local/Library/Homebrew/brew.rb:99:in `<main>'
Error: Kernel.exit
```
</details>

<details><summary>Output of `brew doctor`</summary>

```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Some frameworks can be picked up by CMake's build system and likely
cause the build to fail. To compile CMake, you may wish to move these
out of the way:
  /Library/Frameworks/libcurl.framework

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libltdl.7.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/libltdl/lt_dlloader.h
  /usr/local/include/libltdl/lt_error.h
  /usr/local/include/libltdl/lt_system.h
  /usr/local/include/ltdl.h
  /usr/local/include/node/android-ifaddrs.h
  /usr/local/include/node/ares.h
  /usr/local/include/node/ares_version.h
  /usr/local/include/node/libplatform/libplatform.h
  /usr/local/include/node/nameser.h
  /usr/local/include/node/node.h
  /usr/local/include/node/node_buffer.h
  /usr/local/include/node/node_internals.h
  /usr/local/include/node/node_object_wrap.h
  /usr/local/include/node/node_version.h
  /usr/local/include/node/openssl/aes.h
  /usr/local/include/node/openssl/archs/aix-gcc/opensslconf.h
  /usr/local/include/node/openssl/archs/aix64-gcc/opensslconf.h
  /usr/local/include/node/openssl/archs/BSD-x86/opensslconf.h
  /usr/local/include/node/openssl/archs/BSD-x86_64/opensslconf.h
  /usr/local/include/node/openssl/archs/darwin-i386-cc/opensslconf.h
  /usr/local/include/node/openssl/archs/darwin64-x86_64-cc/opensslconf.h
  /usr/local/include/node/openssl/archs/linux-aarch64/opensslconf.h
  /usr/local/include/node/openssl/archs/linux-armv4/opensslconf.h
  /usr/local/include/node/openssl/archs/linux-elf/opensslconf.h
  /usr/local/include/node/openssl/archs/linux-ppc/opensslconf.h
  /usr/local/include/node/openssl/archs/linux-ppc64/opensslconf.h
  /usr/local/include/node/openssl/archs/linux-x32/opensslconf.h
  /usr/local/include/node/openssl/archs/linux-x86_64/opensslconf.h
  /usr/local/include/node/openssl/archs/solaris-x86-gcc/opensslconf.h
  /usr/local/include/node/openssl/archs/solaris64-x86_64-gcc/opensslconf.h
  /usr/local/include/node/openssl/archs/VC-WIN32/opensslconf.h
  /usr/local/include/node/openssl/archs/VC-WIN64A/opensslconf.h
  /usr/local/include/node/openssl/asn1.h
  /usr/local/include/node/openssl/asn1_mac.h
  /usr/local/include/node/openssl/asn1t.h
  /usr/local/include/node/openssl/bio.h
  /usr/local/include/node/openssl/blowfish.h
  /usr/local/include/node/openssl/bn.h
  /usr/local/include/node/openssl/buffer.h
  /usr/local/include/node/openssl/camellia.h
  /usr/local/include/node/openssl/cast.h
  /usr/local/include/node/openssl/cmac.h
  /usr/local/include/node/openssl/cms.h
  /usr/local/include/node/openssl/comp.h
  /usr/local/include/node/openssl/conf.h
  /usr/local/include/node/openssl/conf_api.h
  /usr/local/include/node/openssl/crypto.h
  /usr/local/include/node/openssl/des.h
  /usr/local/include/node/openssl/des_old.h
  /usr/local/include/node/openssl/dh.h
  /usr/local/include/node/openssl/dsa.h
  /usr/local/include/node/openssl/dso.h
  /usr/local/include/node/openssl/dtls1.h
  /usr/local/include/node/openssl/e_os2.h
  /usr/local/include/node/openssl/ebcdic.h
  /usr/local/include/node/openssl/ec.h
  /usr/local/include/node/openssl/ecdh.h
  /usr/local/include/node/openssl/ecdsa.h
  /usr/local/include/node/openssl/engine.h
  /usr/local/include/node/openssl/err.h
  /usr/local/include/node/openssl/evp.h
  /usr/local/include/node/openssl/hmac.h
  /usr/local/include/node/openssl/idea.h
  /usr/local/include/node/openssl/krb5_asn.h
  /usr/local/include/node/openssl/kssl.h
  /usr/local/include/node/openssl/lhash.h
  /usr/local/include/node/openssl/md4.h
  /usr/local/include/node/openssl/md5.h
  /usr/local/include/node/openssl/mdc2.h
  /usr/local/include/node/openssl/modes.h
  /usr/local/include/node/openssl/obj_mac.h
  /usr/local/include/node/openssl/objects.h
  /usr/local/include/node/openssl/ocsp.h
  /usr/local/include/node/openssl/opensslconf.h
  /usr/local/include/node/openssl/opensslv.h
  /usr/local/include/node/openssl/ossl_typ.h
  /usr/local/include/node/openssl/pem.h
  /usr/local/include/node/openssl/pem2.h
  /usr/local/include/node/openssl/pkcs12.h
  /usr/local/include/node/openssl/pkcs7.h
  /usr/local/include/node/openssl/pqueue.h
  /usr/local/include/node/openssl/rand.h
  /usr/local/include/node/openssl/rc2.h
  /usr/local/include/node/openssl/rc4.h
  /usr/local/include/node/openssl/ripemd.h
  /usr/local/include/node/openssl/rsa.h
  /usr/local/include/node/openssl/safestack.h
  /usr/local/include/node/openssl/seed.h
  /usr/local/include/node/openssl/sha.h
  /usr/local/include/node/openssl/srp.h
  /usr/local/include/node/openssl/srtp.h
  /usr/local/include/node/openssl/ssl.h
  /usr/local/include/node/openssl/ssl2.h
  /usr/local/include/node/openssl/ssl23.h
  /usr/local/include/node/openssl/ssl3.h
  /usr/local/include/node/openssl/stack.h
  /usr/local/include/node/openssl/symhacks.h
  /usr/local/include/node/openssl/tls1.h
  /usr/local/include/node/openssl/ts.h
  /usr/local/include/node/openssl/txt_db.h
  /usr/local/include/node/openssl/ui.h
  /usr/local/include/node/openssl/ui_compat.h
  /usr/local/include/node/openssl/whrlpool.h
  /usr/local/include/node/openssl/x509.h
  /usr/local/include/node/openssl/x509_vfy.h
  /usr/local/include/node/openssl/x509v3.h
  /usr/local/include/node/pthread-fixes.h
  /usr/local/include/node/stdint-msvc2008.h
  /usr/local/include/node/tree.h
  /usr/local/include/node/uv-aix.h
  /usr/local/include/node/uv-bsd.h
  /usr/local/include/node/uv-darwin.h
  /usr/local/include/node/uv-errno.h
  /usr/local/include/node/uv-linux.h
  /usr/local/include/node/uv-sunos.h
  /usr/local/include/node/uv-threadpool.h
  /usr/local/include/node/uv-unix.h
  /usr/local/include/node/uv-version.h
  /usr/local/include/node/uv-win.h
  /usr/local/include/node/uv.h
  /usr/local/include/node/v8-debug.h
  /usr/local/include/node/v8-platform.h
  /usr/local/include/node/v8-profiler.h
  /usr/local/include/node/v8-testing.h
  /usr/local/include/node/v8-util.h
  /usr/local/include/node/v8-version.h
  /usr/local/include/node/v8.h
  /usr/local/include/node/v8config.h
  /usr/local/include/node/zconf.h
  /usr/local/include/node/zlib.h

Warning: Unbrewed .la files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .la files:
  /usr/local/lib/libltdl.la
  /usr/local/lib/psqlodbcw.la

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libltdl.a

Warning: You have a curlrc file
If you have trouble downloading packages with Homebrew, then maybe this
is the problem? If the following command doesn't work, then try removing
your curlrc:
  curl https://github.com
Warning: Use homebrew/boneyard/pyside instead of deprecated homebrew/core/pyside
Warning: Use homebrew/boneyard/shiboken instead of deprecated homebrew/core/shiboken
```
</details>

<details><summary>Output of `brew cask doctor`</summary>

```
==> macOS Release:
10.12.1
==> Hardware Architecture:
intel-64
==> Ruby Version:
2.0.0-p648
==> Ruby Path:
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
==> Homebrew Version:
Homebrew >1.0.0 (no git repository)
Homebrew/homebrew-core (git revision b9d8; last commit 2016-09-13)
==> Homebrew Executable Path:
/usr/local/bin/brew
==> Homebrew Cellar Path:
/usr/local/Cellar
==> Homebrew Repository Path:
/usr/local
==> Homebrew Origin:
<NONE> (Error)
==> Homebrew-Cask Version:
Homebrew-Cask >1.0.0 (no git repository)
caskroom/homebrew-cask (git revision a513; last commit 2016-11-07)
==> Homebrew-Cask Install Location:
<NONE>
==> Homebrew-Cask Staging Location:
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads:
/Users/jamie/Library/Caches/Homebrew/Cask
0 files, 0B
==> Homebrew-Cask Default Tap Path:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask
==> Homebrew-Cask Alternate Cask Taps:
==> Homebrew-Cask Default Tap Cask Count:
3432
==> Contents of $LOAD_PATH:
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Contents of $RUBYLIB Environment Variable:
<NONE>
==> Contents of $RUBYOPT Environment Variable:
<NONE>
==> Contents of $RUBYPATH Environment Variable:
<NONE>
==> Contents of $RBENV_VERSION Environment Variable:
<NONE>
==> Contents of $CHRUBY_VERSION Environment Variable:
<NONE>
==> Contents of $GEM_HOME Environment Variable:
<NONE>
==> Contents of $GEM_PATH Environment Variable:
<NONE>
==> Contents of $BUNDLE_PATH Environment Variable:
<NONE>
==> Contents of $PATH Environment Variable:
PATH="/Users/jamie/perl5/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:~/src/arc/arcanist/bin:Library/Python/2.7/bin:/Applications/010 Editor.app/Contents/CmdLine:/Users/jamie/Dropbox/data.Go.GOPATH/bin:/usr/local/Homebrew/Library/Taps/boxen/homebrew-brews/cmd:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-boneyard/cmd:/usr/local/Homebrew/Library/Homebrew/cask/cmd:/usr/local/Homebrew/Library/Homebrew/shims/scm"
==> Contents of $SHELL Environment Variable:
SHELL="/bin/zsh"
==> Contents of Locale Environment Variables:
LANG="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
==> Running As Privileged User:
No
```
</details>

#### Troubleshooting Steps

Troubleshooting steps were followed from [https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/pre_bug_report.md](https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/pre_bug_report.md):
* `$ cd $(brew --repo); git fetch; git reset --hard origin/master`
^- `brew --repo` takes me to `/usr/local` but there is no `.git` directory so the subsequent commands fail. I executed the remaining commands from within `/usr/local/Homebrew` which was successful.

<details><summary>Output of `brew untap phinze/cask; brew untap caskroom/cask; brew uninstall --force brew-cask`</summary>

```
Warning: Use homebrew/boneyard/pyside instead of deprecated homebrew/core/pyside
Warning: Use homebrew/boneyard/shiboken instead of deprecated homebrew/core/shiboken
Warning: Skipping binwalk: most recent version 2.1.1_2 not installed
Warning: Skipping boost: most recent version 1.62.0 not installed
Warning: Skipping curl: most recent version 7.51.0 not installed
Warning: Skipping ffmpeg: most recent version 3.2 not installed
Warning: Skipping fontconfig: most recent version 2.12.1_2 not installed
Warning: Skipping freetds: most recent version 1.00.16 not installed
Warning: Skipping freetype: most recent version 2.7 not installed
Removing: /usr/local/Cellar/gcc/6.1.0... (1,435 files, 289M)
Removing: /usr/local/Cellar/gdbm/1.11... (18 files, 486.7K)
Removing: /usr/local/Cellar/gettext/0.19.7... (1,934 files, 16.7M)
Warning: Skipping glib: most recent version 2.50.1 not installed
Removing: /usr/local/Cellar/gmp/6.1.0... (17 files, 3.2M)
Warning: Skipping gnu-tar: most recent version 1.29_1 not installed
Warning: Skipping go: most recent version 1.7.3 not installed
Warning: Skipping gobject-introspection: most recent version 1.50.0 not installed
Warning: Skipping harfbuzz: most recent version 1.3.3_1 not installed
Removing: /usr/local/Cellar/htop/2.0.1_1... (10 files, 182.4K)
Warning: Skipping icu4c: most recent version 58.1 not installed
Warning: Skipping irssi: most recent version 0.8.20 not installed
Removing: /usr/local/Cellar/isl/0.15... (70 files, 3.6M)
Removing: /usr/local/Cellar/libiodbc/3.52.10... (34 files, 1.7M)
Warning: Skipping libmongoclient: most recent version 2.6.12 not installed
Warning: Skipping libpng: most recent version 1.6.26 not installed
Warning: Skipping libtiff: most recent version 4.0.6_3 not installed
Warning: Skipping libyaml: most recent version 0.1.7 not installed
Warning: Skipping mercurial: most recent version 4.0 not installed
Warning: Skipping mongodb: most recent version 3.2.10 not installed
Warning: Skipping mpfr: most recent version 3.1.5 not installed
Warning: Skipping nmap: most recent version 7.31 not installed
Warning: Skipping oniguruma: most recent version 6.1.1_1 not installed
Warning: Skipping openssl: most recent version 1.0.2j not installed
Removing: /usr/local/Cellar/p7zip/15.14.1_1... (103 files, 4.7M)
Warning: Skipping pango: most recent version 1.40.3 not installed
Removing: /usr/local/Cellar/pcre/8.38... (203 files, 5.4M)
Warning: Skipping pkg-config: most recent version 0.29.1_2 not installed
Warning: Skipping postgresql: most recent version 9.5.5 not installed
Warning: Skipping python: most recent version 2.7.12_2 not installed
Warning: Skipping readline: most recent version 7.0 not installed
Removing: /usr/local/Cellar/rrdtool/1.5.5... (152 files, 3.6M)
Warning: Skipping ruby: most recent version 2.3.1_2 not installed
Warning: Skipping selenium-server-standalone: most recent version 3.0.1 not installed
Warning: Skipping sqlite: most recent version 3.15.1 not installed
Warning: Skipping tmux: most recent version 2.3_1 not installed
Removing: /usr/local/Cellar/wget/1.17.1... (9 files, 1.5M)
Warning: Skipping wxmac: most recent version 3.0.2_4 not installed
Warning: Skipping x264: most recent version r2699 not installed
==> This operation has freed approximately 330.2M of disk space.
==> Tapping caskroom/cask
Cloning into '/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask'...
remote: Counting objects: 3535, done.
remote: Compressing objects: 100% (3519/3519), done.
remote: Total 3535 (delta 31), reused 145 (delta 12), pack-reused 0
Receiving objects: 100% (3535/3535), 1.14 MiB | 144.00 KiB/s, done.
Resolving deltas: 100% (31/31), done.
Checking connectivity... done.
Tapped 0 formulae (3,543 files, 3.5M)
==> Removing cached downloads
Nothing to do
Already up-to-date.
```
</details>

<details><summary>Output of `brew cleanup; brew cask cleanup; brew update`</summary>

```
Warning: Use homebrew/boneyard/pyside instead of deprecated homebrew/core/pyside
Warning: Use homebrew/boneyard/shiboken instead of deprecated homebrew/core/shiboken
Warning: Skipping binwalk: most recent version 2.1.1_2 not installed
Warning: Skipping boost: most recent version 1.62.0 not installed
Warning: Skipping curl: most recent version 7.51.0 not installed
Warning: Skipping ffmpeg: most recent version 3.2 not installed
Warning: Skipping fontconfig: most recent version 2.12.1_2 not installed
Warning: Skipping freetds: most recent version 1.00.16 not installed
Warning: Skipping freetype: most recent version 2.7 not installed
Removing: /usr/local/Cellar/gcc/6.1.0... (1,435 files, 289M)
Removing: /usr/local/Cellar/gdbm/1.11... (18 files, 486.7K)
Removing: /usr/local/Cellar/gettext/0.19.7... (1,934 files, 16.7M)
Warning: Skipping glib: most recent version 2.50.1 not installed
Removing: /usr/local/Cellar/gmp/6.1.0... (17 files, 3.2M)
Warning: Skipping gnu-tar: most recent version 1.29_1 not installed
Warning: Skipping go: most recent version 1.7.3 not installed
Warning: Skipping gobject-introspection: most recent version 1.50.0 not installed
Warning: Skipping harfbuzz: most recent version 1.3.3_1 not installed
Removing: /usr/local/Cellar/htop/2.0.1_1... (10 files, 182.4K)
Warning: Skipping icu4c: most recent version 58.1 not installed
Warning: Skipping irssi: most recent version 0.8.20 not installed
Removing: /usr/local/Cellar/isl/0.15... (70 files, 3.6M)
Removing: /usr/local/Cellar/libiodbc/3.52.10... (34 files, 1.7M)
Warning: Skipping libmongoclient: most recent version 2.6.12 not installed
Warning: Skipping libpng: most recent version 1.6.26 not installed
Warning: Skipping libtiff: most recent version 4.0.6_3 not installed
Warning: Skipping libyaml: most recent version 0.1.7 not installed
Warning: Skipping mercurial: most recent version 4.0 not installed
Warning: Skipping mongodb: most recent version 3.2.10 not installed
Warning: Skipping mpfr: most recent version 3.1.5 not installed
Warning: Skipping nmap: most recent version 7.31 not installed
Warning: Skipping oniguruma: most recent version 6.1.1_1 not installed
Warning: Skipping openssl: most recent version 1.0.2j not installed
Removing: /usr/local/Cellar/p7zip/15.14.1_1... (103 files, 4.7M)
Warning: Skipping pango: most recent version 1.40.3 not installed
Removing: /usr/local/Cellar/pcre/8.38... (203 files, 5.4M)
Warning: Skipping pkg-config: most recent version 0.29.1_2 not installed
Warning: Skipping postgresql: most recent version 9.5.5 not installed
Warning: Skipping python: most recent version 2.7.12_2 not installed
Warning: Skipping readline: most recent version 7.0 not installed
Removing: /usr/local/Cellar/rrdtool/1.5.5... (152 files, 3.6M)
Warning: Skipping ruby: most recent version 2.3.1_2 not installed
Warning: Skipping selenium-server-standalone: most recent version 3.0.1 not installed
Warning: Skipping sqlite: most recent version 3.15.1 not installed
Warning: Skipping tmux: most recent version 2.3_1 not installed
Removing: /usr/local/Cellar/wget/1.17.1... (9 files, 1.5M)
Warning: Skipping wxmac: most recent version 3.0.2_4 not installed
Warning: Skipping x264: most recent version r2699 not installed
==> This operation has freed approximately 330.2M of disk space.
==> Tapping caskroom/cask
Cloning into '/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask'...
remote: Counting objects: 3535, done.
remote: Compressing objects: 100% (3519/3519), done.
remote: Total 3535 (delta 31), reused 145 (delta 12), pack-reused 0
Receiving objects: 100% (3535/3535), 1.14 MiB | 144.00 KiB/s, done.
Resolving deltas: 100% (31/31), done.
Checking connectivity... done.
Tapped 0 formulae (3,543 files, 3.5M)
==> Removing cached downloads
Nothing to do
Already up-to-date.
```
</details>

**Comment by miccal** [comment]
Can you try just `brew cask install --verbose handbrakecli`.

**Comment by reitermarkus** [comment]
```
==> Homebrew Version:
Homebrew >1.0.0 (no git repository)
```

Seems like your installation is outdated, the latest version is `Homebrew 1.1.0`,  try running `brew update --force`.

**Comment by AlmightyOatmeal** [comment]
@miccal,

That is not what I was instructed to run. My terminal buffers have since expired the original output but looking at it now:
```
$ brew search handbrake
Caskroom/cask/handbrake                        Caskroom/cask/handbrakebatch                   Caskroom/cask/handbrakecli                     Caskroom/versions/handbrakecli-nightly
```
There is no reason to run what you requested as it deviates from the original problem. By changing the scope of action then you introduce additional variables which leave the original issue at hand.

@reitermarkus,

If you read my original post then you would have seen the reason for `Homebrew >1.0.0 (no git repository)` and you would have known that I followed specific steps and I did in-fact update home-brew.

**Comment by miccal** [comment]
Besides the fact that your installation appear outdate as @reitermarkus mentions, it seems that this may be part of the problem:
```
==> Homebrew Repository Path:
/usr/local
==> Homebrew Origin:
<NONE> (Error)
```
as for a standard install it should say:
```
==> Homebrew Repository Path:
/usr/local/Homebrew
==> Homebrew Origin:
https://github.com/Homebrew/brew
```

**Comment by adidalal** [comment]
@AlmightyOatmeal 

That's a Homebrew issue, looks like. 
```
Homebrew >1.0.0 (no git repository)
Homebrew/homebrew-core (git revision b9d8; last commit 2016-09-13)
```
There was a homebrew update bug. Try `cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update` or check out https://github.com/Homebrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting

----

Also,

`brew install Caskroom/cask/handbrakecli` and `brew cask install handbrakecli` *should be identical, FWIW. If the two don't error out in the same way that would give us a clue as to what's going on. Do this after your Homebrew install is sorted out.

**Comment by AlmightyOatmeal** [comment]
My installation is *not* outdated, how many times do I need to say this?

**Comment by Numbermaniac** [comment]
So you have updated to 1.1.0 since making this post, then?

**Comment by AlmightyOatmeal** [comment]
My god. This is worse than having a conversation with a brick wall.
