### ISSUE TITLE
Exception installing anything

### ISSUE THREAD

**Issue by mafrosis** [caskroom/homebrew-cask#26817]
On a fresh install os OSX:

1. install Homebrew
2. install any cask

Output:

    $ brew cask install calibre
    ==> Tapping caskroom/cask
    Cloning into '/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask'...
    remote: Counting objects: 3530, done.
    remote: Compressing objects: 100% (3515/3515), done.
    remote: Total 3530 (delta 31), reused 166 (delta 11), pack-reused 0
    Receiving objects: 100% (3530/3530), 1.14 MiB | 0 bytes/s, done.
    Resolving deltas: 100% (31/31), done.
    Checking connectivity... done.
    Error: Invalid formula: /usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask/metagrowler.rb
    undefined method `cask' for Formulary::FormulaNamespace0a3fc67eb7f20792f6a4ee633903a783:Module
    Error: Cannot tap caskroom/cask: invalid syntax in tap!
    Follow the instructions here:
      https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/pre_bug_report.md

    If this doesn’t fix the problem, please report this bug:
      https://github.com/caskroom/homebrew-cask#reporting-bugs

    /usr/local/Homebrew/Library/Homebrew/tap.rb:226:in `install'
    /usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:147:in `process'
    /usr/local/Homebrew/Library/Homebrew/cask/cmd/brew-cask.rb:8:in `<top (required)>'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    /usr/local/Homebrew/Library/Homebrew/brew.rb:24:in `require?'
    /usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>

**Comment by mafrosis** [comment]
Closing as reported with better infos in #26815
