### ISSUE TITLE
Bug report: wrong number of arguments when installing Lightroom 6.7

### ISSUE THREAD

**Issue by nathany** [caskroom/homebrew-cask#27804]
Remember to follow the [pre bug report](https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/pre_bug_report.md) guide beforehand. Failure to do so might get your issue closed.

Yes, I did all that after the first time I saw this failure. 

```
❯ cd $(brew --repo); git fetch; git reset --hard origin/master
❯ brew untap phinze/cask; brew untap caskroom/cask; brew uninstall --force brew-cask
❯ brew cleanup; brew cask cleanup; brew update
```

#### Description of issue

I'm installing on a new machine that has never had Lightroom or Adobe Creative Cloud installed. It fails with a Ruby stacktrace as shown in the output below.

<details><summary>Output of `brew cask <command> --verbose`</summary>

```
❯ brew cask install adobe-photoshop-lightroom --verbose
==> Caveats
Installation or Uninstallation may fail with Exit Code 19 (Conflicting Processes running) if Browsers, Safari Notification Service or SIMBL Services are running or Adobe Creative Cloud or any other Adobe Products are already installed. See Logs in /Library/Logs/Adobe/Installers if Installation or Uninstallation fails, to identify the conflicting processes.

==> Satisfying dependencies
==> Installing Cask dependencies: caskroom/versions/adobe-photoshop-lightroom600
caskroom/versions/adobe-photoshop-lightroom600 ...
==> Caveats
Installation or Uninstallation may fail with Exit Code 19 (Conflicting Processes running) if Browsers, Safari Notification Service or SIMBL Services are running or Adobe Creative Cloud or any other Adobe Products are already installed. See Logs in /Library/Logs/Adobe/Installers if Installation or Uninstallation fails, to identify the conflicting processes.

==> Downloading http://trials3.adobe.com/AdobeProducts/LTRM/6/osx10/Lightroom_6_LS11.dmg
/usr/bin/curl --fail --remote-time --location --user-agent Homebrew/1.1.4-2-g9cd5a21b (Macintosh; Intel macOS 10.12.2) curl/7.51.0 http://trials3.adobe.com/AdobeProducts/LTRM/6/osx10/Lightroom_6_LS11.dmg -C 0 -o /Users/nathany/Library/Caches/Homebrew/Cask/adobe-photoshop-lightroom600--6.0.dmg.incomplete -A Mozilla/5.0 (Macintosh; Intel Mac OS X 10) http://caskroom.io -b MM_TRIALS=1234
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  726M  100  726M    0     0   975k      0  0:12:43  0:12:43 --:--:--  915k
==> Verifying checksum for Cask adobe-photoshop-lightroom600
No matching processes belonging to you were found
Password:
Starting Installer... In Silent mode.
Begin Adobe Setup
UI mode: Silent
100.00%
End Adobe Setup.  Exit code: 0
Installation successful.
Exiting Installer with Code: 0
🍺  adobe-photoshop-lightroom600 was successfully installed!
done
complete
==> Downloading http://swupdl.adobe.com/updates/oobe/aam20/mac/AdobeLightroom-6.0/6.7/setup.dmg
/usr/bin/curl --fail --remote-time --location --user-agent Homebrew/1.1.4-2-g9cd5a21b (Macintosh; Intel macOS 10.12.2) curl/7.51.0 http://swupdl.adobe.com/updates/oobe/aam20/mac/AdobeLightroom-6.0/6.7/setup.dmg -C 0 -o /Users/nathany/Library/Caches/Homebrew/Cask/adobe-photoshop-lightroom--6.7.dmg.incomplete
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  414M  100  414M    0     0   904k      0  0:07:49  0:07:49 --:--:--  982k
==> Verifying checksum for Cask adobe-photoshop-lightroom
==> No matching processes belonging to you were found
Error: Command failed to execute!

==> Failed command:
/usr/bin/killall -kill SafariNotificationAgent

==> Standard Output of failed command:


==> Standard Error of failed command:
No matching processes belonging to you were found


==> Exit status of failed command:
#<Process::Status: pid 47855 exit 1>
==> No matching processes belonging to you were found
Password:
==> Starting Installer... In Silent mode.
==> Installation successful.
==> Exiting Installer with Code: 0
Error: wrong number of arguments (1 for 4)
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/pre_bug_report.md

If this doesn’t fix the problem, please report this bug:
  https://github.com/caskroom/homebrew-cask#reporting-bugs

/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/exceptions.rb:60:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:156:in `exception'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:156:in `raise'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:156:in `rescue in install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:135:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:87:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:25:in `block in install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:19:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:19:in `install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:10:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:110:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:149:in `process'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/brew-cask.rb:8:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/brew.rb:24:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
Error: Kernel.exit
```
</details>

<details><summary>Output of `brew doctor`</summary>

```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Applications/Postgres.app/Contents/Versions/latest/bin/gdal-config
```
</details>

<details><summary>Output of `brew cask doctor`</summary>

```
❯ brew cask doctor
==> macOS Release:
10.12.2
==> Hardware Architecture:
intel-64
==> Ruby Version:
2.0.0-p648
==> Ruby Path:
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
==> Homebrew Version:
Homebrew 1.1.4-2-g9cd5a21b
Homebrew/homebrew-core (git revision 90d2; last commit 2016-12-14)
==> Homebrew Executable Path:
/usr/local/bin/brew
==> Homebrew Cellar Path:
/usr/local/Cellar
==> Homebrew Repository Path:
/usr/local/Homebrew
==> Homebrew Origin:
https://github.com/Homebrew/brew
==> Homebrew-Cask Version:
Homebrew-Cask 1.1.4-2-g9cd5a21b
caskroom/homebrew-cask (git revision 09b3; last commit 2016-12-15)
==> Homebrew-Cask Install Location:
<NONE>
==> Homebrew-Cask Staging Location:
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads:
/Users/nathany/Library/Caches/Homebrew/Cask
2 files, 1.1G (warning: run "brew cask cleanup")
==> Homebrew-Cask Default Tap Path:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask
==> Homebrew-Cask Alternate Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions
==> Homebrew-Cask Default Tap Cask Count:
3485
==> Contents of $LOAD_PATH:
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Contents of $RUBYLIB Environment Variable:
<NONE>
==> Contents of $RUBYOPT Environment Variable:
<NONE>
==> Contents of $RUBYPATH Environment Variable:
<NONE>
==> Contents of $RBENV_VERSION Environment Variable:
<NONE>
==> Contents of $CHRUBY_VERSION Environment Variable:
<NONE>
==> Contents of $GEM_HOME Environment Variable:
<NONE>
==> Contents of $GEM_PATH Environment Variable:
<NONE>
==> Contents of $BUNDLE_PATH Environment Variable:
<NONE>
==> Contents of $PATH Environment Variable:
PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Postgres.app/Contents/Versions/latest/bin:/Users/nathany/src/go.googlesource.com/go/bin:/Users/nathany/bin:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/cmd:/usr/local/Homebrew/Library/Homebrew/cask/cmd:/usr/local/Homebrew/Library/Homebrew/shims/scm"
==> Contents of $SHELL Environment Variable:
SHELL="/bin/zsh"
==> Contents of Locale Environment Variables:
LANG="en_CA.UTF-8"
LC_CTYPE="en_CA.UTF-8"
```
</details>

**Comment by Numbermaniac** [comment]
Affected cask: https://github.com/caskroom/homebrew-cask/blob/master/Casks/adobe-photoshop-lightroom.rb

**Comment by miccal** [comment]
Here is what the `preflight` stanza was before the implementation of `system_command`:
```
  preflight do
    system '/usr/bin/killall', '-kill', 'SafariNotificationAgent'
    system '/usr/bin/sudo', '-E', '--', "#{staged_path}/AdobePatchInstaller.app/Contents/MacOS/AdobePatchInstaller", '--mode=silent'
  end
```

Ping @reitermarkus.

**Comment by nathany** [comment]
fyi, this was on macOS Sierra 10.12.2 on a 13" MacBook Pro (2016) w/Touch Bar.

**Comment by cldsnchz** [comment]
I've got exactly the same error installing skype-for-business. 
I just mention this here just in case the cause is a more general thing than something related to the cask.

**Comment by miccal** [comment]
@cldsnchz I do not think your issue is related to this one, as [`Skype-for-business.rb`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/skype-for-business.rb) does not use `system_command`.

Would you mind following the instructions [here](https://github.com/caskroom/homebrew-cask#reporting-bugs) and submitting a separate issue?

**Comment by reitermarkus** [comment]
Ah, yes, this is because `system_command` defaults to `must_succeed: true`, while `system` doesn't raise an exception if the exit code is non-zero.

**Comment by miccal** [comment]
@nathany would you mind reinstalling `adobe-photoshop-lightroom.rb` via the command `brew cask install https://raw.githubusercontent.com/reitermarkus/homebrew-cask/496208073a784eafd2f6654f049d4a7d9fdfaf1d/Casks/adobe-photoshop-lightroom.rb` and let us know if PR [#27884](https://github.com/caskroom/homebrew-cask/pull/27884) fixes your problem?

**Comment by nathany** [comment]
Thanks Markus. 👍
