### ISSUE TITLE
Bug report: wrong number of arguments when installing Skype for Business 16.1.0.456

### ISSUE THREAD

**Issue by cldsnchz** [caskroom/homebrew-cask#27880]
#### Description of issue

I'm installing Skype for Business for the first time and it fails with a Ruby stacktrace as shown in the output below.

Affected cask: https://github.com/caskroom/homebrew-cask/blob/master/Casks/skype-for-business.rb

<details><summary>Output of `brew cask <command> --verbose`</summary>

```
> brew cask install skype-for-business --verbose
==> Downloading https://download.microsoft.com/download/D/0/5/D055DA17-C7B8-4257-89A1-78E7BBE3833F/SkypeForBusinessInstaller-16.1.0.456.pkg
/usr/bin/curl --fail --remote-time --location --user-agent Homebrew/1.1.4-2-g9cd5a21b4 (Macintosh; Intel macOS 10.10.5) curl/7.43.0 https://download.microsoft.com/download/D/0/5/D055DA17-C7B8-4257-89A1-78E7BBE3833F/SkypeForBusinessInstaller-16.1.0.456.pkg -C 0 -o /Users/claudio/Library/Caches/Homebrew/Cask/skype-for-business--16.1.0.456.pkg.incomplete
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 30.5M  100 30.5M    0     0   917k      0  0:00:34  0:00:34 --:--:-- 1317k
==> Verifying checksum for Cask skype-for-business
==> Running installer for skype-for-business; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
Password:
==> installer: Error -
Error: Command failed to execute!

==> Failed command:
/usr/bin/sudo -E -- /usr/sbin/installer -pkg #<Pathname:/usr/local/Caskroom/skype-for-business/16.1.0.456/SkypeForBusinessInstaller-16.1.0.456.pkg> -target / -verboseR

==> Standard Output of failed command:


==> Standard Error of failed command:
installer: Error -


==> Exit status of failed command:
#<Process::Status: pid 55793 exit 1>
Error: wrong number of arguments (1 for 4)
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/pre_bug_report.md

If this doesn’t fix the problem, please report this bug:
  https://github.com/caskroom/homebrew-cask#reporting-bugs

/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/exceptions.rb:60:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:156:in `exception'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:156:in `raise'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:156:in `rescue in install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:135:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:87:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:25:in `block in install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:19:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:19:in `install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:10:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:110:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:149:in `process'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/brew-cask.rb:8:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/brew.rb:24:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
Error: Kernel.exit
[1]    55667 exit 1     brew cask install skype-for-business --verbose
```
</details>

<details><summary>Output of `brew doctor`</summary>

```
Your system is ready to brew.
```
</details>

<details><summary>Output of `brew cask doctor`</summary>

```
==> macOS Release:
10.10.5
==> Hardware Architecture:
intel-64
==> Ruby Version:
2.0.0-p481
==> Ruby Path:
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
==> Homebrew Version:
Homebrew 1.1.4-2-g9cd5a21b4
Homebrew/homebrew-core (git revision afd46; last commit 2016-12-16)
==> Homebrew Executable Path:
/usr/local/bin/brew
==> Homebrew Cellar Path:
/usr/local/Cellar
==> Homebrew Repository Path:
/usr/local/Homebrew
==> Homebrew Origin:
https://github.com/Homebrew/brew.git
==> Homebrew-Cask Version:
Homebrew-Cask 1.1.4-2-g9cd5a21b4
caskroom/homebrew-cask (git revision ed93; last commit 2016-12-16)
==> Homebrew-Cask Install Location:
<NONE>
==> Homebrew-Cask Staging Location:
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads:
/Users/claudio/Library/Caches/Homebrew/Cask
1 files, 30.6M (warning: run "brew cask cleanup")
==> Homebrew-Cask Default Tap Path:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask
==> Homebrew-Cask Alternate Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions
==> Homebrew-Cask Default Tap Cask Count:
3486
==> Contents of $LOAD_PATH:
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin14
/Library/Ruby/Site/2.0.0/universal-darwin14
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin14
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin14
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin14
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin14
==> Contents of $RUBYLIB Environment Variable:
<NONE>
==> Contents of $RUBYOPT Environment Variable:
<NONE>
==> Contents of $RUBYPATH Environment Variable:
<NONE>
==> Contents of $RBENV_VERSION Environment Variable:
<NONE>
==> Contents of $CHRUBY_VERSION Environment Variable:
<NONE>
==> Contents of $GEM_HOME Environment Variable:
<NONE>
==> Contents of $GEM_PATH Environment Variable:
<NONE>
==> Contents of $BUNDLE_PATH Environment Variable:
<NONE>
==> Contents of $PATH Environment Variable:
PATH="/usr/local/bin:/usr/local/sbin:/Users/claudio/.dotfiles/scripts:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/cask/cmd:/usr/local/Homebrew/Library/Homebrew/shims/scm"
==> Contents of $SHELL Environment Variable:
SHELL="/usr/local/bin/zsh"
==> Contents of Locale Environment Variables:
LANG="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
```
</details>

**Comment by reitermarkus** [comment]
I cannot reproduce this. Does installing it manually work?

**Comment by cldsnchz** [comment]
I should have tried that before creating the ticket. 
I got this message when installing manually: 

`Please upgrade to Mac OS X 10.11 or above to use this version of Skype for Business.`

Just for curiosity, have the cask definition something to define the required version of OS X?

**Comment by miccal** [comment]
> Just for curiosity, have the cask definition something to define the required version of OS X?

Yes, we have `depends_on macos: '>= :el_capitan'`.

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/pull/27890.
