### ISSUE TITLE
Bug report: Error: No such file or directory - getcwd

### ISSUE THREAD

**Issue by spdv123** [caskroom/homebrew-cask#28031]
Error occured while doing
```
brew cask install xquartz
```

System: OSX 10.11.6

```
Error: No such file or directory - getcwd
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/pre_bug_report.md

If this doesn’t fix the problem, please report this bug:
  https://github.com/caskroom/homebrew-cask#reporting-bugs

/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/container/dmg.rb:81:in `chdir'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/container/dmg.rb:81:in `bom_filelist_from_path'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/container/dmg.rb:71:in `block (2 levels) in extract_mount'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tempfile.rb:324:in `open'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/container/dmg.rb:70:in `block in extract_mount'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tempfile.rb:324:in `open'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/container/dmg.rb:67:in `extract_mount'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/container/dmg.rb:63:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/container/dmg.rb:63:in `extract_mounts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/container/dmg.rb:25:in `extract'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:131:in `extract_primary_container'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:69:in `stage'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:86:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:25:in `block in install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:19:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:19:in `install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:10:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:110:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:149:in `process'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/brew-cask.rb:8:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/brew.rb:24:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

**Comment by jimhester** [comment]
For anyone else who ends up here, this typically happens when your current working directory is in a cask, and you try to reinstall it (http://stackoverflow.com/questions/9243548/no-such-file-or-directory-getcwd-error-on-rubygems-on-mac-os-lion#comment18051135_9375700).
