### ISSUE TITLE
Bug report: Error: undefined method `latest?' for nil:NilClass while installing app

### ISSUE THREAD

**Issue by charlax** [caskroom/homebrew-cask#29397]
#### Description of issue

*Note: this is a follow up from #22295*

Getting the following error while trying to install Docker:

```
% brew cask install --force $(brew cask list)
==> Downloading https://download.docker.com/mac/stable/1.13.0.15072/Docker.dmg
######################################################################## 100.0%
==> Verifying checksum for Cask docker
Warning: It seems there is already an App at '/Applications/Docker.app'; overwriting.
==> Removing App: '/Applications/Docker.app'
==> Moving App 'Docker.app' to '/Applications/Docker.app'
🍺  docker was successfully installed!
Error: undefined method `latest?' for nil:NilClass
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/pre_bug_report.md

If this doesn’t fix the problem, please report this bug:
  https://github.com/caskroom/homebrew-cask#reporting-bugs

/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/download.rb:36:in `clear_cache'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/download.rb:14:in `perform'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:101:in `download'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:62:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:85:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:25:in `block in install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:19:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:19:in `install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:10:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:111:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:150:in `process'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/brew-cask.rb:8:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/brew.rb:24:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

The following commands have been tried but did not solve the issue:

* `brew uninstall --force brew-cask; brew untap phinze/cask; brew update; brew cleanup; brew cask cleanup`
* `brew untap caskroom/cask; brew cleanup; brew cask cleanup; brew update`

<details><summary>Output of `brew cask <command> --verbose`</summary>

```
% brew cask install --force $(brew cask list) --verbose
==> Downloading https://download.docker.com/mac/stable/1.13.0.15072/Docker.dmg
Already downloaded: /Users/ca/Library/Caches/Homebrew/Cask/docker--1.13.0.15072.dmg
==> Verifying checksum for Cask docker
Warning: It seems there is already an App at '/Applications/Docker.app'; overwriting.
==> Removing App: '/Applications/Docker.app'
==> Moving App 'Docker.app' to '/Applications/Docker.app'
🍺  docker was successfully installed!
Error: undefined method `latest?' for nil:NilClass
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/pre_bug_report.md

If this doesn’t fix the problem, please report this bug:
  https://github.com/caskroom/homebrew-cask#reporting-bugs

/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/download.rb:36:in `clear_cache'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/download.rb:14:in `perform'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:101:in `download'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:62:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:85:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:25:in `block in install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:19:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:19:in `install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:10:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:111:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:150:in `process'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/brew-cask.rb:8:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/brew.rb:24:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
Error: Kernel.exit
```
</details>

<details><summary>Output of `brew doctor`</summary>

```
% brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  glide
  postgresql
Warning: Use vagrant-completion instead of deprecated homebrew/completions/vagrant-completion
Warning: Use vagrant-completion instead of deprecated homebrew/completions/vagrant-completion
```
</details>

<details><summary>Output of `brew cask doctor`</summary>

```
% brew cask doctor
==> macOS Release:
10.12.3
==> Hardware Architecture:
intel-64
==> Ruby Version:
2.0.0-p648
==> Ruby Path:
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
==> Homebrew Version:
Homebrew 1.1.8
Homebrew/homebrew-core (git revision 5daf; last commit 2017-01-25)
==> Homebrew Executable Path:
/usr/local/bin/brew
==> Homebrew Cellar Path:
/usr/local/Cellar
==> Homebrew Repository Path:
/usr/local/Homebrew
==> Homebrew Origin:
https://github.com/Homebrew/brew
==> Homebrew-Cask Version:
Homebrew-Cask 1.1.8
caskroom/homebrew-cask (git revision a4d4; last commit 2017-01-25)
==> Homebrew-Cask Install Location:
<NONE>
==> Homebrew-Cask Staging Location:
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads:
/Users/ca/Library/Caches/Homebrew/Cask
1 files, 104.2M (warning: run "brew cask cleanup")
==> Homebrew-Cask Default Tap Path:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask
==> Homebrew-Cask Alternate Cask Taps:
/usr/local/Homebrew/Library/Taps/uber/homebrew-alt
==> Homebrew-Cask Default Tap Cask Count:
3538
==> Contents of $LOAD_PATH:
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Contents of $RUBYLIB Environment Variable:
<NONE>
==> Contents of $RUBYOPT Environment Variable:
<NONE>
==> Contents of $RUBYPATH Environment Variable:
<NONE>
==> Contents of $RBENV_VERSION Environment Variable:
<NONE>
==> Contents of $CHRUBY_VERSION Environment Variable:
<NONE>
==> Contents of $GEM_HOME Environment Variable:
<NONE>
==> Contents of $GEM_PATH Environment Variable:
<NONE>
==> Contents of $BUNDLE_PATH Environment Variable:
<NONE>
==> Contents of $PATH Environment Variable:
PATH="/Users/ca/.rbenv/shims:/usr/local/bin:/usr/local/sbin:/Users/ca/.dotfiles/bin:/Users/ca/.nvm/v0.10.32/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/munki:/Library/TeX/texbin:/Users/ca/bin:/Users/ca/golang/bin:/usr/local/opt/fzf/bin:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-boneyard/cmd:/usr/local/Homebrew/Library/Homebrew/cask/cmd:/usr/local/Homebrew/Library/Homebrew/shims/scm"
==> Contents of $SHELL Environment Variable:
SHELL="/usr/local/bin/zsh"
==> Contents of Locale Environment Variables:
LANG="en_US.UTF-8"
```
</details>

**Comment by miccal** [comment]
Can you  provide the output of your `$(brew cask list)` please.

**Comment by charlax** [comment]
Yeah actually I can reproduce the issue with just `% brew cask install --force puppet`.

```
% brew cask install --force puppet
Error: undefined method `latest?' for nil:NilClass
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/pre_bug_report.md

If this doesn’t fix the problem, please report this bug:
  https://github.com/caskroom/homebrew-cask#reporting-bugs

/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/download.rb:36:in `clear_cache'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/download.rb:14:in `perform'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:101:in `download'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:62:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:85:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:25:in `block in install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:19:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:19:in `install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:10:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:111:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:150:in `process'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/brew-cask.rb:8:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/brew.rb:24:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

**Comment by charlax** [comment]
This looks like a custom recipe. Might close this ticket then.

**Comment by miccal** [comment]
Related: https://github.com/caskroom/homebrew-cask/pull/21882

The Cask `puppet` has been removed, that is why you are getting this error.

**Comment by charlax** [comment]
Perhaps it'd be nice to have a clearer error message?

**Comment by miccal** [comment]
[We are working on it.](https://github.com/caskroom/homebrew-cask/issues/25523)
