### ISSUE TITLE
question cask: "Error: ERROR: Failed to build gem native extension." with "Permission denied - Makefile"

### ISSUE THREAD

**Issue by cometsong** [caskroom/homebrew-cask#29404]
#### Description of issue

Ruby `"Error: ERROR: Failed to build gem native extension."` with `"Permission denied - Makefile (Errno::EACCES)"` error on installing or running `brew cask`.  Where is it trying to create the `Makefile`

I did follow all the commands listed on the [pre bug report](https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/pre_bug_report.md) page, even before I read that page.  :)

##### Main question:
Is this cask related or some other `ruby` issue?  
`brew` works perfectly fine on its own.  
This behavior started a few days ago.  
I upgraded OSX to Sierra a couple weeks ago.  
I uninstalled and then re-installed homebrew completely yesterday.  
Same behaviour as before.  

Ideas on where to look next?

<details><summary>Output of `brew cask <command> --verbose`</summary>

```
=> brew cask --verbose
Error: ERROR: Failed to build gem native extension.

    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby extconf.rb
checking for ruby/st.h... yes
checking for st.h... yes
checking for rb_str_replace() in ruby.h... yes
creating Makefile
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/mkmf.rb:2125:in `initialize': Permission denied - Makefile (Errno::EACCES)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/mkmf.rb:2125:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/mkmf.rb:2125:in `create_makefile'
	from extconf.rb:24:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /Library/Ruby/Gems/2.0.0/gems/msgpack-0.5.8 for inspection.
Results logged to /Library/Ruby/Gems/2.0.0/extensions/universal-darwin-16/2.0.0/msgpack-0.5.8/gem_make.out
```
</details>
<details><summary>Output of `brew install caskroom/cask/brew-cask`</summary>

```
=> brew install caskroom/cask/brew-cask
==> Tapping caskroom/cask
Cloning into '/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask'...
remote: Counting objects: 3645, done.
remote: Compressing objects: 100% (3631/3631), done.
remote: Total 3645 (delta 32), reused 287 (delta 10), pack-reused 0
Receiving objects: 100% (3645/3645), 1.21 MiB | 0 bytes/s, done.
Resolving deltas: 100% (32/32), done.
Tapped 0 formulae (3,649 files, 3.8M)
==> brew cask install caskroom/cask/brew-cask
Error: ERROR: Failed to build gem native extension.

    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby extconf.rb
checking for ruby/st.h... yes
checking for st.h... yes
checking for rb_str_replace() in ruby.h... yes
creating Makefile
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/mkmf.rb:2125:in `initialize': Permission denied - Makefile (Errno::EACCES)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/mkmf.rb:2125:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/mkmf.rb:2125:in `create_makefile'
	from extconf.rb:24:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /Library/Ruby/Gems/2.0.0/gems/msgpack-0.5.8 for inspection.
Results logged to /Library/Ruby/Gems/2.0.0/extensions/universal-darwin-16/2.0.0/msgpack-0.5.8/gem_make.out
```
</details>

<details><summary>Output of `brew doctor`</summary>

```
=> brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Putting non-prefixed coreutils in your path can cause gmp builds to fail.
```
</details>

<details><summary>Output of `brew cask doctor`</summary>

Same as all `brew cask` with or without subcommands appended.
</details>

<details><summary>Extra  Facts</summary>

```
=> brew --version
Homebrew 1.1.8-2562-g1f97e318
Homebrew/homebrew-core (git revision d52f; last commit 2017-01-25)
```
```
=> gem list
*** LOCAL GEMS ***
bigdecimal (default: 1.3.0)
did_you_mean (1.1.0)
io-console (default: 0.4.6)
json (default: 2.0.2)
minitest (5.10.1)
msgpack (1.0.2)
neovim (0.3.1)
net-telnet (0.1.1)
openssl (default: 2.0.2)
power_assert (0.4.1)
psych (default: 2.2.2)
rake (12.0.0)
rdoc (default: 5.0.0)
test-unit (3.2.3)
xmlrpc (0.2.1)
```
</details>

**Comment by vitorgalvao** [comment]
> `brew install caskroom/cask/brew-cask`

You’re not supposed to do that. That’s not how HBC is installed. It is automatically installed the first time you run any `brew cask` command. Uninstall that and try again.

**Comment by cometsong** [comment]
I did initially do this by using:
```
brew tap caskroom/cask
brew cask install [...]
```
The single line above I got from an SO answer.  
The output of `brew cask info alfred` is identical to the above error.
```
=> brew cask info alfred
Error: ERROR: Failed to build gem native extension.

    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby extconf.rb
checking for ruby/st.h... yes
checking for st.h... yes
checking for rb_str_replace() in ruby.h... yes
creating Makefile
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/mkmf.rb:2125:in `initialize': Permission denied - Makefile (Errno::EACCES)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/mkmf.rb:2125:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/mkmf.rb:2125:in `create_makefile'
	from extconf.rb:24:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /Library/Ruby/Gems/2.0.0/gems/msgpack-0.5.8 for inspection.
Results logged to /Library/Ruby/Gems/2.0.0/extensions/universal-darwin-16/2.0.0/msgpack-0.5.8/gem_make.out
```

**Comment by commitay** [comment]
@vitorgalvao Okay to close this?

**Comment by cometsong** [comment]
Yeah I did complete overhaul and I still have no idea what caused this before.  Close is good.
