### ISSUE TITLE
Bug report: [cannot uninstall utorrent]

### ISSUE THREAD

**Issue by jasonhemann** [caskroom/homebrew-cask#29829]
Remember to follow the [pre bug report](https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/pre_bug_report.md) guide beforehand. Failure to do so might get your issue closed.

#### Description of issue

[utorrent is proving difficult to uninstall, reinstall. brew cask uninstall utorrent, brew cask reinstall utorrent  both fail]

<details><summary>Output of `brew cask <command> --verbose`</summary>

```
$ brew cask uninstall Caskroom/cask/utorrent --verbose
Error: Tap caskroom/cask already tapped.

Follow the instructions here:
  https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/pre_bug_report.md

If this doesn’t fix the problem, please report this bug:
  https://github.com/caskroom/homebrew-cask#reporting-bugs

/usr/local/Homebrew/Library/Homebrew/tap.rb:196:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/source/untapped_qualified.rb:9:in `me?'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/source.rb:28:in `block in for_query'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/source.rb:26:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/source.rb:26:in `find'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/source.rb:26:in `for_query'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc.rb:58:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:11:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:9:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:9:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:111:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:154:in `process'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/brew-cask.rb:8:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/brew.rb:24:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
Error: Kernel.exit
```
</details>

<details><summary>Output of `brew doctor`</summary>

```
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  android-sdk

Warning: Broken symlinks were found. Remove them with `brew prune`:
  /usr/local/share/ghostscript/9.10/Resource/Font/logo10.pfb
  /usr/local/share/ghostscript/9.10/Resource/Font/logo8.pfb
  /usr/local/share/ghostscript/9.10/Resource/Font/logo9.pfb
  /usr/local/share/ghostscript/9.10/Resource/Font/logobf10.pfb
  /usr/local/share/ghostscript/9.10/Resource/Font/logod10.pfb
  /usr/local/share/ghostscript/9.10/Resource/Font/logosl10.pfb
  /usr/local/share/ghostscript/9.10/Resource/Font/logosl8.pfb
  /usr/local/share/ghostscript/9.10/Resource/Font/logosl9.pfb
  /usr/local/share/ghostscript/9.10/Resource/Font/manfnt.pfb
  /usr/local/share/ghostscript/9.10/Resource/Font/wasy10.pfb
  /usr/local/share/ghostscript/9.10/Resource/Font/wasy5.pfb
  /usr/local/share/ghostscript/9.10/Resource/Font/wasy6.pfb
  /usr/local/share/ghostscript/9.10/Resource/Font/wasy7.pfb
  /usr/local/share/ghostscript/9.10/Resource/Font/wasy8.pfb
  /usr/local/share/ghostscript/9.10/Resource/Font/wasy9.pfb
  /usr/local/share/ghostscript/9.10/Resource/Font/wasyb10.pfb
```
</details>

<details><summary>Output of `brew cask doctor`</summary>

```
$ brew cask doctor
==> macOS Release:
10.10.5
==> Hardware Architecture:
intel-64
==> Ruby Version:
2.0.0-p481
==> Ruby Path:
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
==> Homebrew Version:
Homebrew 1.1.9-24-g33fa80944e
Homebrew/homebrew-core (git revision f205a; last commit 2017-02-04)
==> Homebrew Executable Path:
/usr/local/bin/brew
==> Homebrew Cellar Path:
/usr/local/Cellar
==> Homebrew Repository Path:
/usr/local/Homebrew
==> Homebrew Origin:
https://github.com/Homebrew/brew.git
==> Homebrew-Cask Version:
Homebrew-Cask 1.1.9-24-g33fa80944e
caskroom/homebrew-cask (git revision 3a84; last commit 2017-02-04)
==> Homebrew-Cask Install Location:
<NONE>
==> Homebrew-Cask Staging Location:
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads:
/Users/me/Library/Caches/Homebrew/Cask
0 files, 0B
==> Homebrew-Cask Default Tap Path:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask
==> Homebrew-Cask Alternate Cask Taps:
/usr/local/Homebrew/Library/Taps/railwaycat/homebrew-emacsmacport
==> Homebrew-Cask Default Tap Cask Count:
3531
==> Contents of $LOAD_PATH:
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin14
/Library/Ruby/Site/2.0.0/universal-darwin14
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin14
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin14
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin14
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin14
==> Contents of $RUBYLIB Environment Variable:
<NONE>
==> Contents of $RUBYOPT Environment Variable:
<NONE>
==> Contents of $RUBYPATH Environment Variable:
<NONE>
==> Contents of $RBENV_VERSION Environment Variable:
<NONE>
==> Contents of $CHRUBY_VERSION Environment Variable:
<NONE>
==> Contents of $GEM_HOME Environment Variable:
<NONE>
==> Contents of $GEM_PATH Environment Variable:
<NONE>
==> Contents of $BUNDLE_PATH Environment Variable:
<NONE>
==> Contents of $PATH Environment Variable:
PATH="/Users/me/Library/Haskell/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Library/TeX/texbin:/Applications/Racket v6.5/bin:/Users/me/perl5/bin:/Users/me/FlameGraph:/usr/local/Homebrew/Library/Homebrew/cask/cmd:/usr/local/Homebrew/Library/Homebrew/shims/scm"
==> Contents of $SHELL Environment Variable:
SHELL="/bin/bash"
==> Contents of Locale Environment Variables:
LANG="en_US.UTF-8"
```
</details>

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/pull/29748

Uninstall with `--force`.

**Comment by jasonhemann** [comment]
@vitorgalvao 

I don't believe that worked on my system

````
$ brew cask uninstall utorrent --force
Error: No available Cask for utorrent
$ brew cask install Caskroom/cask/utorrent
Error: Tap caskroom/cask already tapped.

Follow the instructions here:
  https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/pre_bug_report.md

If this doesn’t fix the problem, please report this bug:
  https://github.com/caskroom/homebrew-cask#reporting-bugs

/usr/local/Homebrew/Library/Homebrew/tap.rb:196:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/source/untapped_qualified.rb:9:in `me?'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/source.rb:28:in `block in for_query'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/source.rb:26:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/source.rb:26:in `find'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/source.rb:26:in `for_query'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc.rb:58:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:21:in `block in install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:19:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:19:in `install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:10:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:111:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:154:in `process'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/brew-cask.rb:8:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/brew.rb:24:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
````

**Comment by miccal** [comment]
@jasonhemann the command should be `brew cask uninstall --force utorrent`.

**Comment by jasonhemann** [comment]
@miccal, that didn't seem to produce a different outcome, although thanks. 

````
$ brew cask uninstall --force utorrent
Error: No available Cask for utorrent
````

**Comment by vitorgalvao** [comment]
@jasonhemann That means it was already uninstalled. As for the app itself, you’ll have to delete it yourself. That’s the whole reason the cask was removed: the uninstall didn’t remove it.

**Comment by jasonhemann** [comment]
@vitorgalvao Ah. Alright then. That explains that. Problem solved.
