### ISSUE TITLE
Bug Report: uninstalling keybase causing exception

### ISSUE THREAD

**Issue by sashkab** [caskroom/homebrew-cask#30145]
Looks like cask left some leftovers from keybase when I tried to install/uninstall it earlier, so this time I tried to install it and then uninstall for full cleanup action. Oh well, that didn't work and here the exception.

Following troubleshooting steps didn't help, so here is output. 

```
 brew untap caskroom/cask; brew cleanup; brew cask cleanup; brew update

Untapping caskroom/cask... (6,117 files, 132.1M)
Untapped 0 formulae
==> Tapping caskroom/cask
Cloning into '/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask'...
remote: Counting objects: 3657, done.
remote: Compressing objects: 100% (3642/3642), done.
remote: Total 3657 (delta 32), reused 318 (delta 11), pack-reused 0
Receiving objects: 100% (3657/3657), 1.22 MiB | 0 bytes/s, done.
Resolving deltas: 100% (32/32), done.
Tapped 0 formulae (3,666 files, 3.8M)
==> Removing cached downloads
/Users/XXX/Library/Caches/Homebrew/Cask/atom--1.14.1.zip
/Users/XXX/Library/Caches/Homebrew/Cask/keybase--1.0.18-20170209165653,17b641d.dmg
/Users/XXX/Library/Caches/Homebrew/Cask/visual-studio-code--1.9.0,27240e71ef390bf2d66307e677c2a333cebf75af.zip
==> This operation has freed approximately 210.5M of disk space.
Already up-to-date.
```

And failure:

```bash
 $ brew cask remove keybase
Error: No such file or directory - /Applications/Keybase.app/Contents/SharedSupport/bin/keybase
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/pre_bug_report.md

If this doesn’t fix the problem, please report this bug:
  https://github.com/caskroom/homebrew-cask#reporting-bugs

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open3.rb:211:in `spawn'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open3.rb:211:in `popen_run'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open3.rb:99:in `popen3'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:79:in `each_output_line'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:24:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:13:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:17:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/dsl/base.rb:14:in `system_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:42:in `block (2 levels) in load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_flight_block.rb:35:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_flight_block.rb:35:in `block in abstract_phase'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/set.rb:232:in `each_key'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/set.rb:232:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_flight_block.rb:34:in `abstract_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_flight_block.rb:28:in `uninstall_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:325:in `block in uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:322:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:322:in `uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:313:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:26:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:9:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:9:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:111:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:154:in `process'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/brew-cask.rb:8:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/brew.rb:24:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
(3) b@b-imac /usr/local/Homebrew (master) $ ls -la /Applications/Keybase.app/Contents/SharedSupport/bin/keybase
ls: /Applications/Keybase.app/Contents/SharedSupport/bin/keybase: No such file or directory
```

**Comment by sashkab** [comment]
Probably related to the #29956.

**Comment by adidalal** [comment]
Child issue of https://github.com/caskroom/homebrew-cask/issues/30142 - track updates there

**Comment by joshka** [comment]
Given that I can comment out the flight stanzas on the keybase cask #30142. This seems unrelated. I have a fix for this, but not #30142 yet.

**Comment by sashkab** [comment]
I'm somewhat confused: despite opening multiple issues and merge requests, keybase still doesn't uninstalls and still generates same exception.

Oh well... Will figure out how to uninstall it manually.

**Comment by joshka** [comment]
From the looks of things the desired way forward for the homebrew cask devs is to fix an underlying problem with hbc. The PR I referenced above is on hold while that process and the conversation needed takes place.

From a manual uninstall perspective, keybase installs a bunch of things. Your error above indicates that you've possibly removed the keybase from your applications folder and then tried to run brew uninstall keybase. A bug in the uninstall method for keybase's cask means this won't work. To get around this install keybase again and then uninstall.
You can do this either via HBC `brew install keybase; brew uninstall keybase` or manually following the instructions at keybase.io/download then running `keybase uninstall` prior to deleting the app from your Applications folder.

**Comment by sashkab** [comment]
@joshka `brew install keybase` and `brew reinstall keybase` were failing (install suggested to use reinstall, which crashed), but `brew install keybase --force` and followed by `brew uninstall keybase` fixed issue. But it left a lot of junk on disk, which required manual uninstall (or does cask uninstalls things from Library, etc)?

**Comment by vitorgalvao** [comment]
> despite opening multiple issues and merge requests, keybase still doesn't uninstalls and still generates same exception.

Because the code isn’t yet live. You’ll need to wait until the next HB release for it to work.

**Comment by sashkab** [comment]
> Because the code isn’t yet live. You’ll need to wait until the next HB release for it to work.

That might explain few things :-)

**Comment by joshka** [comment]
Can you please post details of what's left on disk for keybase when you do the uninstall? It would be a great help for those that come along after. I thought the uninstall process got most of it.
