### ISSUE TITLE
Bug report: Installation behavior for existing manually installed apps

### ISSUE THREAD

**Issue by joshka** [caskroom/homebrew-cask#30142]
#### Description of issue

When an application previously installed manually exists at /Applications, `brew install ...` should not delete the app unless `--force` is specified. This was reported by @gabriel as part of testing the keybase cask at https://github.com/caskroom/homebrew-cask/pull/29956#discussion_r101410551

It seems that the logic wants to both remove the existing app and fail to do so...

Repro steps. install keybase manually from https://keybase.io/docs/the_app/install_macos and then from cask using `brew cask install keybase`

<details><summary>Output of `brew cask install keybase`</summary>

```
$ brew cask install keybase
==> Downloading https://prerelease.keybase.io/darwin/Keybase-1.0.18-20170209165653%2B17b641d.dmg
Already downloaded: /Users/joshka/Library/Caches/Homebrew/Cask/keybase--1.0.18-20170209165653,17b641d.dmg
==> Verifying checksum for Cask keybase
==> Removing App: '/Applications/Keybase.app'
Error: It seems there is already an App at '/Applications/Keybase.app'.
Error: nothing to install
```
</details>

**Comment by vitorgalvao** [comment]
> When an application previously installed manually exists at /Applications, `brew install ...` should not delete the app unless `--force` is specified.

And it doesn’t. I can’t reproduce this with other casks and won’t try with this one because I don’t have an available VM. Please try with other casks first.

**Comment by joshka** [comment]
I thought at first it was due to the commands in the cask's preflight / postflight stanza, but commenting those stanzas out completely gives the same error.

<details><summary>Full output of `brew cask install --debug keybase`</summary>

```
$ brew cask install --debug keybase
==> Loading Cask definitions
==> Translating 'keybase' into a valid Cask source
==> Testing source class Hbc::Source::URI
==> Testing source class Hbc::Source::PathSlashRequired
==> Testing source class Hbc::Source::TappedQualified
==> Testing source class Hbc::Source::UntappedQualified
==> Testing source class Hbc::Source::Tapped
==> Success! Using source class Hbc::Source::Tapped
==> Resolved Cask URI or file source to '/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask/Casks/keybase.rb'
==> Cask instance dumps in YAML:
Warning: Unexpected method 'encode_with' called on Cask keybase.
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/pre_bug_report.md

If this doesn’t fix the problem, please report this bug:
  https://github.com/caskroom/homebrew-cask#reporting-bugs

==> Cask instance toplevel:
--- !ruby/object:Hbc::Cask
token: keybase
sourcefile_path: !ruby/object:Pathname
  path: /usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask/Casks/keybase.rb
dsl: !ruby/object:Hbc::DSL {}
==> Cask instance method 'name':
---
- Keybase
==> Cask instance method 'homepage':
--- https://keybase.io/
...
==> Cask instance method 'url':
--- !ruby/object:Hbc::URL
uri: !ruby/object:URI::HTTPS
  scheme: https
  user:
  password:
  host: prerelease.keybase.io
  port: 443
  path: /darwin/Keybase-1.0.18-20170209165653%2B17b641d.dmg
  query:
  opaque:
  registry:
  fragment:
  parser:
user_agent:
cookies:
referer:
using:
revision:
trust_cert:
data:
==> Cask instance method 'appcast':
---
- !ruby/object:URI::HTTPS
  scheme: https
  user:
  password:
  host: prerelease.keybase.io
  port: 443
  path: /update-darwin-prod-v2.json
  query:
  opaque:
  registry:
  fragment:
  parser:
- :checkpoint: 37f720c5a5c9be9cbf429c0b755a4b024ab900f5758f64b195bdf00c672634b4
==> Cask instance method 'version':
--- !ruby/string:Hbc::DSL::Version
str: !binary |-
  MS4wLjE4LTIwMTcwMjA5MTY1NjUzLDE3YjY0MWQ=
raw_version: 1.0.18-20170209165653,17b641d
==> Cask instance method 'sha256':
--- a5a974089e94e68ac3a5113570e903d0b88fe243d04474107645a5c792d13693
...
==> Cask instance method 'artifacts':
---
:app: !ruby/object:Set
  hash:
    ? - Keybase.app
    : true
:postflight: !ruby/object:Set
  hash:
    !ruby/object:Proc {}: true
:uninstall_preflight: !ruby/object:Set
  hash:
    !ruby/object:Proc {}: true
==> Cask instance method 'caveats':
--- []
==> Cask instance method 'depends_on':
---
...
==> Cask instance method 'conflicts_with':
---
...
==> Cask instance method 'container':
---
...
==> Cask instance method 'gpg':
---
...
==> Cask instance method 'accessibility_access':
---
...
==> Cask instance method 'auto_updates':
--- true
...
==> Hbc::Installer#install
==> Printing caveats
==> Hbc::Installer#fetch
==> Downloading
==> Downloading https://prerelease.keybase.io/darwin/Keybase-1.0.18-20170209165653%2B17b641d.dmg
Already downloaded: /Users/joshka/Library/Caches/Homebrew/Cask/keybase--1.0.18-20170209165653,17b641d.dmg
==> Downloaded to -> /Users/joshka/Library/Caches/Homebrew/Cask/keybase--1.0.18-20170209165653,17b641d.dmg
==> Verifying download
==> Determining which verifications to run for Cask keybase
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask keybase
==> SHA256 checksums match
==> Hbc::Installer#stage
==> Extracting primary container
==> Determining which containers to use based on filetype
==> Checking container class Hbc::Container::Pkg
==> Checking container class Hbc::Container::Ttf
==> Checking container class Hbc::Container::Otf
==> Checking container class Hbc::Container::Air
==> Checking container class Hbc::Container::Cab
==> Checking container class Hbc::Container::Dmg
==> Executing: ["/usr/bin/hdiutil", "imageinfo", "/Users/joshka/Library/Caches/Homebrew/Cask/keybase--1.0.18-20170209165653,17b641d.dmg"]
==> Using container class Hbc::Container::Dmg for /Users/joshka/Library/Caches/Homebrew/Cask/keybase--1.0.18-20170209165653,17b641d.dmg
==> Executing: ["/usr/bin/hdiutil", "mount", "-plist", "-nobrowse", "-readonly", "-noidme", "-mountrandom", "/tmp", "/Users/joshka/Library/Caches/Homebrew/Cask/keybase--1.0.18-20170209165653,17b641d.dmg"]
==> Executing: ["/usr/bin/mkbom", "-s", "-i", "/var/folders/qy/vftdx05n0rl4mxvp33zrt3l00000gn/T/20170216-29786-oxhelx.list", "--", "/var/folders/qy/vftdx05n0rl4mxvp33zrt3l00000gn/T/20170216-29786-x1vw5o.bom"]
==> Executing: ["/usr/bin/ditto", "--bom", "/var/folders/qy/vftdx05n0rl4mxvp33zrt3l00000gn/T/20170216-29786-x1vw5o.bom", "--", "/private/tmp/dmg.huaKMn", "/usr/local/Caskroom/keybase/1.0.18-20170209165653,17b641d"]
==> Executing: ["/usr/sbin/diskutil", "eject", "/private/tmp/dmg.huaKMn"]
==> Creating metadata directory /usr/local/Caskroom/keybase/.metadata/1.0.18-20170209165653,17b641d/20170216083206.906
==> Creating metadata subdirectory /usr/local/Caskroom/keybase/.metadata/1.0.18-20170209165653,17b641d/20170216083206.906/Casks
==> Installing artifacts
==> Determining which artifacts are present in Cask keybase
==> Checking for artifact class Hbc::Artifact::PreflightBlock
==> Checking for artifact class Hbc::Artifact::NestedContainer
==> Checking for artifact class Hbc::Artifact::Installer
==> Checking for artifact class Hbc::Artifact::App
==> Checking for artifact class Hbc::Artifact::Suite
==> Checking for artifact class Hbc::Artifact::Artifact
==> Checking for artifact class Hbc::Artifact::Colorpicker
==> Checking for artifact class Hbc::Artifact::Pkg
==> Checking for artifact class Hbc::Artifact::Prefpane
==> Checking for artifact class Hbc::Artifact::Qlplugin
==> Checking for artifact class Hbc::Artifact::Dictionary
==> Checking for artifact class Hbc::Artifact::Font
==> Checking for artifact class Hbc::Artifact::Service
==> Checking for artifact class Hbc::Artifact::StageOnly
==> Checking for artifact class Hbc::Artifact::Binary
==> Checking for artifact class Hbc::Artifact::InputMethod
==> Checking for artifact class Hbc::Artifact::InternetPlugin
==> Checking for artifact class Hbc::Artifact::AudioUnitPlugin
==> Checking for artifact class Hbc::Artifact::VstPlugin
==> Checking for artifact class Hbc::Artifact::Vst3Plugin
==> Checking for artifact class Hbc::Artifact::ScreenSaver
==> Checking for artifact class Hbc::Artifact::Uninstall
==> Checking for artifact class Hbc::Artifact::PostflightBlock
==> Checking for artifact class Hbc::Artifact::Zap
==> 3 artifact/s defined
Hbc::Artifact::PreflightBlock
Hbc::Artifact::App
Hbc::Artifact::PostflightBlock
==> Installing artifact of class Hbc::Artifact::PreflightBlock
==> Installing artifact of class Hbc::Artifact::App
==> Reverting installation of artifact of class Hbc::Artifact::App
==> Removing App: '/Applications/Keybase.app'
==> Reverting installation of artifact of class Hbc::Artifact::PreflightBlock
==> Executing: ["launchctl", "list"]
==> Purging files for version 1.0.18-20170209165653,17b641d of Cask keybase
Error: It seems there is already an App at '/Applications/Keybase.app'.
Error: nothing to install/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:13:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:110:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:149:in `process'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/brew-cask.rb:8:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/brew.rb:24:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:154:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:154:in `rescue in process'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:144:in `process'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/brew-cask.rb:8:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/brew.rb:24:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'

```
</details>

---

Note in particular the following lines:

```
==> 3 artifact/s defined
Hbc::Artifact::PreflightBlock
Hbc::Artifact::App
Hbc::Artifact::PostflightBlock
==> Installing artifact of class Hbc::Artifact::PreflightBlock
==> Installing artifact of class Hbc::Artifact::App
==> Reverting installation of artifact of class Hbc::Artifact::App
==> Removing App: '/Applications/Keybase.app'
==> Reverting installation of artifact of class Hbc::Artifact::PreflightBlock
==> Executing: ["launchctl", "list"]
==> Purging files for version 1.0.18-20170209165653,17b641d of Cask keybase
Error: It seems there is already an App at '/Applications/Keybase.app'.
Error: nothing to install/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:13:in `run'
...
```
This is where I start to lose understanding of what should be happening, but the app definitely gets deleted after this. I'm definitely not passing `--force`. Reading the code, it suggests that the moved.uninstall_phase is being called which does not check for `--force`.

I wonder if this is due to the keybase formula previously being a  formula and now only available as a cask? (See https://github.com/Homebrew/homebrew-core/pull/9852)

**Comment by vitorgalvao** [comment]
Like I said, please try with **other** casks, to narrow down the problem first.

**Comment by reitermarkus** [comment]
What `brew --version` are you running?

**Comment by joshka** [comment]
Homebrew 1.1.10-10-g5a2a06380
Homebrew/homebrew-core (git revision 6407; last commit 2017-02-10)

**Comment by joshka** [comment]
I tried this with the zulip cask and the issue didn't trigger, but it also no longer removes the app when I try this with keybase. That said there's another problem happening now.

What I think I was seeing is:
1. install starts, gets to the point where the app artifact would install, hits an app already there error
2. starts uninstall process to revert installation, which removes the .app file installed manually

What I'm currently seeing.
1. as above
2. as above, but runs the uninstall preflight which breaks an installation that brew doesn't own when considering the command uninstalls the extra stuff that keybase installs (keybase-cli, kbfs, privileged helpers etc.)

<details><summary>brew cask install keybase --debug</summary>

```
$ brew cask install keybase --debug
==> Loading Cask definitions
==> Translating 'keybase' into a valid Cask source
==> Testing source class Hbc::Source::URI
==> Testing source class Hbc::Source::PathSlashRequired
==> Testing source class Hbc::Source::TappedQualified
==> Testing source class Hbc::Source::UntappedQualified
==> Testing source class Hbc::Source::Tapped
==> Success! Using source class Hbc::Source::Tapped
==> Resolved Cask URI or file source to '/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask/Casks/keybase.rb'
==> Cask instance dumps in YAML:
Warning: Unexpected method 'encode_with' called on Cask keybase.
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/pre_bug_report.md

If this doesn’t fix the problem, please report this bug:
  https://github.com/caskroom/homebrew-cask#reporting-bugs

==> Cask instance toplevel:
--- !ruby/object:Hbc::Cask
token: keybase
sourcefile_path: !ruby/object:Pathname
  path: /usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask/Casks/keybase.rb
dsl: !ruby/object:Hbc::DSL {}
==> Cask instance method 'name':
---
- Keybase
==> Cask instance method 'homepage':
--- https://keybase.io/
...
==> Cask instance method 'url':
--- !ruby/object:Hbc::URL
uri: !ruby/object:URI::HTTPS
  scheme: https
  user:
  password:
  host: prerelease.keybase.io
  port: 443
  path: /darwin/Keybase-1.0.18-20170209165653%2B17b641d.dmg
  query:
  opaque:
  registry:
  fragment:
  parser:
user_agent:
cookies:
referer:
using:
revision:
trust_cert:
data:
==> Cask instance method 'appcast':
---
- !ruby/object:URI::HTTPS
  scheme: https
  user:
  password:
  host: prerelease.keybase.io
  port: 443
  path: /update-darwin-prod-v2.json
  query:
  opaque:
  registry:
  fragment:
  parser:
- :checkpoint: 37f720c5a5c9be9cbf429c0b755a4b024ab900f5758f64b195bdf00c672634b4
==> Cask instance method 'version':
--- !ruby/string:Hbc::DSL::Version
str: !binary |-
  MS4wLjE4LTIwMTcwMjA5MTY1NjUzLDE3YjY0MWQ=
raw_version: 1.0.18-20170209165653,17b641d
==> Cask instance method 'sha256':
--- a5a974089e94e68ac3a5113570e903d0b88fe243d04474107645a5c792d13693
...
==> Cask instance method 'artifacts':
---
:app: !ruby/object:Set
  hash:
    ? - Keybase.app
    : true
:postflight: !ruby/object:Set
  hash:
    !ruby/object:Proc {}: true
:uninstall_preflight: !ruby/object:Set
  hash:
    !ruby/object:Proc {}: true
==> Cask instance method 'caveats':
--- []
==> Cask instance method 'depends_on':
---
...
==> Cask instance method 'conflicts_with':
---
...
==> Cask instance method 'container':
---
...
==> Cask instance method 'gpg':
---
...
==> Cask instance method 'accessibility_access':
---
...
==> Cask instance method 'auto_updates':
--- true
...
==> Hbc::Installer#install
==> Printing caveats
==> Hbc::Installer#fetch
==> Downloading
==> Downloading https://prerelease.keybase.io/darwin/Keybase-1.0.18-20170209165653%2B17b641d.dmg
Already downloaded: /Users/joshka/Library/Caches/Homebrew/Cask/keybase--1.0.18-20170209165653,17b641d.dmg
==> Downloaded to -> /Users/joshka/Library/Caches/Homebrew/Cask/keybase--1.0.18-20170209165653,17b641d.dmg
==> Verifying download
==> Determining which verifications to run for Cask keybase
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask keybase
==> SHA256 checksums match
==> Hbc::Installer#stage
==> Extracting primary container
==> Determining which containers to use based on filetype
==> Checking container class Hbc::Container::Pkg
==> Checking container class Hbc::Container::Ttf
==> Checking container class Hbc::Container::Otf
==> Checking container class Hbc::Container::Air
==> Checking container class Hbc::Container::Cab
==> Checking container class Hbc::Container::Dmg
==> Executing: ["/usr/bin/hdiutil", "imageinfo", "/Users/joshka/Library/Caches/Homebrew/Cask/keybase--1.0.18-20170209165653,17b641d.dmg"]
==> Using container class Hbc::Container::Dmg for /Users/joshka/Library/Caches/Homebrew/Cask/keybase--1.0.18-20170209165653,17b641d.dmg
==> Executing: ["/usr/bin/hdiutil", "mount", "-plist", "-nobrowse", "-readonly", "-noidme", "-mountrandom", "/tmp", "/Users/joshka/Library/Caches/Homebrew/Cask/keybase--1.0.18-20170209165653,17b641d.dmg"]
==> Executing: ["/usr/bin/mkbom", "-s", "-i", "/var/folders/qy/vftdx05n0rl4mxvp33zrt3l00000gn/T/20170216-55997-151dycv.list", "--", "/var/folders/qy/vftdx05n0rl4mxvp33zrt3l00000gn/T/20170216-55997-nz30ce.bom"]
==> Executing: ["/usr/bin/ditto", "--bom", "/var/folders/qy/vftdx05n0rl4mxvp33zrt3l00000gn/T/20170216-55997-nz30ce.bom", "--", "/private/tmp/dmg.GDkBji", "/usr/local/Caskroom/keybase/1.0.18-20170209165653,17b641d"]
==> Executing: ["/usr/sbin/diskutil", "eject", "/private/tmp/dmg.GDkBji"]
==> Creating metadata directory /usr/local/Caskroom/keybase/.metadata/1.0.18-20170209165653,17b641d/20170216234052.243
==> Creating metadata subdirectory /usr/local/Caskroom/keybase/.metadata/1.0.18-20170209165653,17b641d/20170216234052.243/Casks
==> Installing artifacts
==> Determining which artifacts are present in Cask keybase
==> 3 artifact/s defined
#<Hbc::Artifact::PreflightBlock:0x007fb552a902e0>
#<Hbc::Artifact::App:0x007fb552a90268>
#<Hbc::Artifact::PostflightBlock:0x007fb552a901f0>
==> Installing artifact of class Hbc::Artifact::PreflightBlock
==> Installing artifact of class Hbc::Artifact::App
==> Reverting installation of artifact of class Hbc::Artifact::PreflightBlock
==> Executing: ["launchctl", "list"]
==> Executing: ["/Applications/Keybase.app/Contents/SharedSupport/bin/keybase", "uninstall"]
==> 2017-02-16T17:40:52.274194 ▶ [INFO keybase launchd.go:291] 001 Removing /Users/joshka/Library/LaunchAgents/keybase.kbfs.plist
==> 2017-02-16T17:40:52.277914 ▶ [INFO keybase launchd.go:217] 002 Waiting for keybase.kbfs to exit...
==> 2017-02-16T17:40:52.486961 ▶ [INFO keybase launchd.go:160] 003 Stopped keybase.kbfs
==> 2017-02-16T17:40:52.491151 ▶ [INFO keybase mounter_nix.go:29] 004 Trying to unmount: /keybase
==> 2017-02-16T17:40:52.499879 ▶ [INFO keybase launchd.go:291] 005 Removing /Users/joshka/Library/LaunchAgents/keybase.service.plist
==> 2017-02-16T17:40:52.504451 ▶ [INFO keybase launchd.go:217] 006 Waiting for keybase.service to exit...
==> 2017-02-16T17:40:52.718048 ▶ [INFO keybase launchd.go:160] 007 Stopped keybase.service
==> 2017-02-16T17:40:52.722273 ▶ [INFO keybase launchd.go:291] 008 Removing /Users/joshka/Library/LaunchAgents/keybase.updater.plist
==> 2017-02-16T17:40:52.726265 ▶ [INFO keybase launchd.go:217] 009 Waiting for keybase.updater to exit...
==> 2017-02-16T17:40:52.939543 ▶ [INFO keybase launchd.go:160] 00a Stopped keybase.updater
==> 2017-02-16T17:40:53.024266 ▶ [INFO keybase install_osx.go:694] 00b Removing KBFuse
==> 2017-02-16T17:40:53.127623 ▶ [INFO keybase install_osx.go:699] 00c Removing privileged helper tool
==> 2017-02-16T17:40:53.230287 ▶ [INFO keybase install.go:222] 00d Removing /usr/local/bin/keybase
==> Purging files for version 1.0.18-20170209165653,17b641d of Cask keybase
Error: It seems there is already an App at '/Applications/Keybase.app'.
Error: nothing to install/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:13:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:111:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:154:in `process'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/brew-cask.rb:8:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/brew.rb:24:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:159:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:159:in `rescue in process'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:145:in `process'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/brew-cask.rb:8:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/brew.rb:24:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```
</details>

**Comment by weingart** [comment]
I came back from vacation and did a "brew update", and surprisingly, it basically installed keybase (said it was moved from the old location to Casks/keybase.rb), which ended up replacing a CLI program with something that want's root to install a system fuse filesystem.

I always thought that "brew update" was largely safe, and "brew upgrade" was where the bad things would end up happening, if anything...

**Comment by vitorgalvao** [comment]
@weingart That has noting to do with this issue.

There’s already an issue open for that problem (in https://github.com/Homebrew/brew/, I think).

**Comment by vitorgalvao** [comment]
We have already fixed this and narrowed the issue at the time to keybase, right?
