### ISSUE TITLE
Dead app: zooom/2

### ISSUE THREAD

**Issue by brother** [caskroom/homebrew-cask#30281]
* [`zooom/2`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/zooom.rb)
* http://www.coderage-software.com/index.html

```
brother@baikonur:~$ brew install --debug Caskroom/cask/zooom
==> brew cask install Caskroom/cask/zooom --debug
==> Loading Cask definitions
==> Translating 'Caskroom/cask/zooom' into a valid Cask source
==> Testing source class Hbc::Source::URI
==> Testing source class Hbc::Source::PathSlashRequired
==> Testing source class Hbc::Source::TappedQualified
==> [user, repo, token] might be [caskroom, cask, zooom]
==> Success! Using source class Hbc::Source::TappedQualified
==> Resolved Cask URI or file source to '/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask/Casks/zooom.rb'
==> Cask instance dumps in YAML:
Warning: Unexpected method 'encode_with' called on Cask zooom.
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/pre_bug_report.md

If this doesn’t fix the problem, please report this bug:
  https://github.com/caskroom/homebrew-cask#reporting-bugs

==> Cask instance toplevel:
--- !ruby/object:Hbc::Cask
token: zooom
sourcefile_path: !ruby/object:Pathname
  path: /usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask/Casks/zooom.rb
dsl: !ruby/object:Hbc::DSL {}
==> Cask instance method 'name':
---
- Zooom/2
==> Cask instance method 'homepage':
--- https://coderage-software.com/zooom/
...
==> Cask instance method 'url':
--- !ruby/object:Hbc::URL
uri: !ruby/object:URI::HTTP
  scheme: http
  user:
  password:
  host: software.coderage-software.com
  port: 80
  path: /zooom/Zooom_Latest.dmg
  query:
  opaque:
  registry:
  fragment:
  parser:
user_agent:
cookies:
referer:
using:
revision:
trust_cert:
data:
==> Cask instance method 'appcast':
---
...
==> Cask instance method 'version':
--- !ruby/string:Hbc::DSL::Version
str: !binary |-
  bGF0ZXN0
raw_version: :latest
==> Cask instance method 'sha256':
--- :no_check
...
==> Cask instance method 'artifacts':
---
:pkg: !ruby/object:Set
  hash:
    ? - Zooom2.pkg
    : true
:uninstall: !ruby/object:Set
  hash:
    ? :pkgutil: com.coderage.pkg.Zooom2
    : true
==> Cask instance method 'caveats':
---
- !ruby/object:Hbc::Caveats
  block: !ruby/object:Proc {}
==> Cask instance method 'depends_on':
---
:macos:
- - :>=
  - !ruby/object:Gem::Version
    version: '10.9'
==> Cask instance method 'conflicts_with':
---
...
==> Cask instance method 'container':
---
...
==> Cask instance method 'gpg':
---
...
==> Cask instance method 'accessibility_access':
---
...
==> Cask instance method 'auto_updates':
---
...
==> Hbc::Installer#install
==> Printing caveats
==> Caveats
There are known issues with installing this package, so if installation fails you may need to run the installer at /usr/local/Caskroom/zooom/latest/Zooom2.pkg manually.

==> Hbc::Installer#fetch
==> Satisfying dependencies
complete
==> Downloading
==> Downloading http://software.coderage-software.com/zooom/Zooom_Latest.dmg
==> Calling curl with args ["http://software.coderage-software.com/zooom/Zooom_Latest.dmg", "-C", "0", "-o", "#<Pathname:/Users/brother/Library/Caches/Homebrew/Cask/zooom--latest.dmg.incomplete>"]

curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'zooom' with message: Download failed: http://software.coderage-software.com/zooom/Zooom_Latest.dmg
The incomplete download is cached at /Users/brother/Library/Caches/Homebrew/Cask/zooom--latest.dmg.incomplete
Error: nothing to install/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:13:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:111:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:154:in `process'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/brew-cask.rb:8:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/brew.rb:24:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:159:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:159:in `rescue in process'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:145:in `process'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/brew-cask.rb:8:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/brew.rb:24:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

**Comment by vitorgalvao** [comment]
Closing in favour of #30282.
