### ISSUE TITLE
Bug report: jdownloader cask is broken

### ISSUE THREAD

**Issue by yurikoles** [caskroom/homebrew-cask#30606]
Remember to follow the [pre bug report](https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/pre_bug_report.md) guide beforehand. Failure to do so might get your issue closed.

#### Description of issue
<details><summary>Output of `brew cask <command> --verbose`</summary>

```
$ brew cask install jdownloader --verbose
==> Caveats
jdownloader requires Java. You can install the latest version with

  brew cask install java

==> Downloading http://installer.jdownloader.org/clean/JD2Setup.dmg
/usr/bin/curl --remote-time --location --user-agent Homebrew/1.1.10-3220-g45f52f77 (Macintosh; Intel macOS 10.12.3) curl/7.51.0 --fail http://installer.jdownloader.org/clean/JD2Setup.dmg -C 0 -o /Users/yurikoles/Library/Caches/Homebrew/Cask/jdownloader--latest.dmg.incomplete -A Mozilla/5.0 (Macintosh; Intel Mac OS X 10) http://caskroom.io
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 5454k  100 5454k    0     0  2865k      0  0:00:01  0:00:01 --:--:-- 2864k
==> No checksum defined for Cask jdownloader, skipping verification
Error: Command failed to execute!

==> Failed command:
/usr/local/Caskroom/jdownloader/latest/JDownloader Installer.app/Contents/MacOS/JavaApplicationStub -dir /usr/local/Caskroom/jdownloader/latest -q -Dinstall4j.suppressStdout=true -Dinstall4j.debug=false -VcreateDesktopLinkAction\\$Boolean=false -VaddToDockAction\\$Boolean=false

==> Standard Output of failed command:


==> Standard Error of failed command:
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=lcd_vbgr -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel


==> Exit status of failed command:
#<Process::Status: pid 7147 exit 1>
Error: nothing to install
Error: Kernel.exit
```
</details>

<details><summary>Output of `brew doctor`</summary>

```
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: python is symlinked to python3
This will confuse build scripts and in general lead to subtle breakage.

Warning: Putting non-prefixed coreutils in your path can cause gmp builds to fail.
```
</details>

<details><summary>Output of `brew cask doctor`</summary>

```
$ brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.1.10-3220-g45f52f77
caskroom/homebrew-cask (git revision fb85; last commit 2017-02-26)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (11 files, 995.8MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3573 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-drivers (43 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-eid (7 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-fonts (1111 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (171 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Environment Variables
LANG="uk_UA.UTF-8"
PATH="~/Gentoo/usr/bin:~/Gentoo/bin:~/Gentoo/tmp/usr/bin:~/Gentoo/tmp/bin:/usr/local/opt/coreutils/libexec/gnubin:/usr/local/sbin:~/.rvm/bin:~/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:~/.rvm/bin:~/go/bin:/ndk-bundle:~/.node_modules/bin:~/Library/Android/sdk/ndk-bundle:/usr/local/opt/jboss-as/libexec/bin:~/bin/depot-tools:/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/cmd:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-aliases/cmd:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-boneyard/cmd:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/cmd:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-command-not-found/cmd:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-dev-tools/cmd:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-emacs/cmd:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-portable/cmd:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/cmd:/usr/local/Homebrew/Library/Homebrew/cask/cmd:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/usr/local/bin/bash"
```
</details>

<details><summary>Output of manual execution of setup command</summary>

```
$ /Volumes/jd2/JDownloader\ Installer.app/Contents/MacOS/JavaApplicationStub 
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=lcd_vbgr -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.install4j.runtime.installer.Installer.getScreenExecutor(Unknown Source)
	at com.install4j.runtime.installer.Installer.runInProcess(Unknown Source)
	at com.install4j.runtime.installer.Installer.main(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.exe4j.runtime.LauncherEngine.launch(Unknown Source)
	at com.install4j.runtime.launcher.MacLauncher.main(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
	at java.awt.EventQueue.invokeAndWait(EventQueue.java:1321)
	at java.awt.EventQueue.invokeAndWait(EventQueue.java:1296)
	at javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1348)
	... 9 more
Caused by: java.lang.Error: Cannot load com.sun.java.swing.plaf.gtk.GTKLookAndFeel
	at javax.swing.UIManager.initializeDefaultLAF(UIManager.java:1351)
	at javax.swing.UIManager.initialize(UIManager.java:1459)
	at javax.swing.UIManager.maybeInitialize(UIManager.java:1426)
	at javax.swing.UIManager.getUI(UIManager.java:1006)
	at javax.swing.JPanel.updateUI(JPanel.java:126)
	at javax.swing.JPanel.<init>(JPanel.java:86)
	at javax.swing.JPanel.<init>(JPanel.java:109)
	at javax.swing.JPanel.<init>(JPanel.java:117)
	at com.install4j.runtime.wizard.WizardBase.<init>(Unknown Source)
	at com.install4j.runtime.installer.frontend.WizardScreenExecutor.<init>(Unknown Source)
	at com.install4j.runtime.installer.frontend.InstallerWizardScreenExecutor.<init>(Unknown Source)
	at com.install4j.runtime.installer.Installer$1.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Could not display the GUI. This application needs access to an X Server.
*******************************************************************
You can also run this application in console mode without
access to an X server by passing the argument -c
*******************************************************************
```
</details>

**Comment by gobinathm** [comment]
Seems to be Working for me ...

```
brew cask install jdownloader --verbose
==> Caveats
jdownloader requires Java. You can install the latest version with

  brew cask install java

==> Downloading http://installer.jdownloader.org/clean/JD2Setup.dmg
/usr/bin/curl --remote-time --location --user-agent Homebrew/1.1.10 (Macintosh; Intel macOS 10.12.3) curl/7.51.0 --fail http://installer.jdownloader.org/clean/JD2Setup.dmg -C 0 -o /Users/gobinathm/Library/Caches/Homebrew/Cask/jdownloader--latest.dmg.incomplete -A Mozilla/5.0 (Macintosh; Intel Mac OS X 10) http://caskroom.io
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 5454k  100 5454k    0     0  3483k      0  0:00:01  0:00:01 --:--:-- 3482k
==> No checksum defined for Cask jdownloader, skipping verification
🍺  jdownloader was successfully installed!
```

**Comment by miccal** [comment]
@yurikoles please post the output of `brew config`.

**Comment by yurikoles** [comment]
<details><summary>Output of brew config</summary>

```
$ brew config
HOMEBREW_VERSION: 1.1.10-3230-gd0c5aec9
ORIGIN: https://github.com/Homebrew/brew
HEAD: d0c5aec9ea80f418c222eb99fe71cbe1e10927d2
Last commit: 14 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 61d247c8931c0d552fba562f71f54d4b9bd3337e
Core tap last commit: 15 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.12.0 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/bin/python3.6
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.0/bin/ruby
Java: 1.8.0_121
macOS: 10.12.3-x86_64
Xcode: 8.2.1
CLT: 8.2.0.0.1.1480973914
X11: 2.7.11 => /opt/X11
```
</details>

**Comment by miccal** [comment]
@gobinathm to help me diagnose this problem, would you mind posting your output of `brew config`?

**Comment by gobinathm** [comment]
brew config output 

```
HOMEBREW_VERSION: 1.1.10
ORIGIN: https://github.com/Homebrew/brew
HEAD: 69d1cedd12d37d6a9535fbba17d2129b165c08f8
Last commit: 3 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 7640dd8823b9ef1f2533beb9524925406d8153c0
Core tap last commit: 81 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit skylake
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.12.0 => /usr/local/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.24.1/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.0/bin/ruby
Java: 1.8.0_121
macOS: 10.12.3-x86_64
Xcode: 8.2.1
CLT: 8.2.0.0.1.1480973914
X11: 2.7.11 => /opt/X11
```

**Comment by neutric** [comment]
Working fine for me with the following config:

```
HOMEBREW_VERSION: 1.1.10-496-g1959cc3f2
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 1959cc3f2df6287467d90242fc6dee41398a5731
Last commit: 3 hours ago
Core tap ORIGIN: ssh://git@github.com/Homebrew/homebrew-core.git
Core tap HEAD: 68d658a67d31b516807d38f2bf8c72cb7b213a65
Core tap last commit: 4 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit sandybridge
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.11.1 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_20
macOS: 10.11.6-x86_64
Xcode: 8.2.1
CLT: 8.2.0.0.1.1480973914
X11: 2.7.11 => /opt/X11
```

**Comment by miccal** [comment]
Thanks @gobinathm and @neutric. I can also confirm it is working fine for me.

@yurikoles this must be an issue with your setup and not with Cask.

**Comment by wickles** [comment]
FWIW I found that this cask was linking to the staging area (Caskroom) (deprecated behavior), when I installed on January 8. I believe it worked before, but I was also not able to upgrade/reinstall the current/latest version, it hangs after launching the installer and nothing happens.
