### ISSUE TITLE
Bug report: VLC-Nightly Redirection Forbidden

### ISSUE THREAD

**Issue by teddy-error** [caskroom/homebrew-cask#30835]
Remember to follow the [pre bug report](https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/pre_bug_report.md) guide beforehand. Failure to do so might get your issue closed.

#### Description of issue

When attempting to install VLC nightly, Homebrew fails to fetch the download due to a URL redirect

<details><summary>Output of `brew cask <command> --verbose`</summary>

```
Error: redirection forbidden: https://nightlies.videolan.org/build/macosx-intel/last -> http://nightlies.videolan.org/build/macosx-intel/last/
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/pre_bug_report.md

If this doesn’t fix the problem, please report this bug:
  https://github.com/caskroom/homebrew-cask#reporting-bugs

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:223:in `open_loop'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:149:in `open_uri'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:689:in `open'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:34:in `open'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:26:in `block (2 levels) in load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/url.rb:14:in `call'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/url.rb:14:in `block in from'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/dsl/stanza_proxy.rb:8:in `block in once'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/dsl/stanza_proxy.rb:32:in `call'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/dsl/stanza_proxy.rb:32:in `method_missing'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/download.rb:25:in `downloader'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/download.rb:36:in `clear_cache'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/download.rb:14:in `perform'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:101:in `download'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:62:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:85:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:25:in `block in install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:19:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:19:in `install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:10:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:114:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:157:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
Error: Kernel.exit
```
</details>

<details><summary>Output of `brew doctor`</summary>

```
Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Users/teddy/.pyenv/shims/python-config
  /Users/teddy/.pyenv/shims/python3-config
  /Users/teddy/.pyenv/shims/python3.6-config
  /Users/teddy/.pyenv/shims/python3.6m-config

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/python2.7/greenlet/greenlet.h
  /usr/local/include/python3.5m/greenlet/greenlet.h

Warning: Some keg-only formula are linked into the Cellar.
Linking a keg-only formula, such as gettext, into the cellar with
`brew link <formula>` will cause other formulae to detect them during
the `./configure` step. This may cause problems when compiling those
other formulae.

Binaries provided by keg-only formulae may override system binaries
with other strange results.

You may wish to `brew unlink` these brews:
  libxml2
  libxslt
```
</details>

<details><summary>Output of `brew cask doctor`</summary>

```
==> Homebrew-Cask Version
Homebrew-Cask 1.1.11-51-gb3679de3
caskroom/homebrew-cask (git revision 77de; last commit 2017-03-12)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3600 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-fonts (1110 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (171 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Environment Variables
LANG="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
PATH="~/.pyenv/plugins/pyenv-virtualenv/shims:~/.pyenv/shims:~/.pyenv/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/zsh"
```
</details>

**Comment by miccal** [comment]
Confirmed.

**Comment by vitorgalvao** [comment]
Pinging @claui. This is a `url do` cask.

**Comment by claui** [comment]
The PR should fix this. I have also talked to one of the upstream sysadmins; they’re also going to fix it server-side.

Thanks for the heads up @teddy-error! ❤️
