### ISSUE TITLE
Bug report: reinstall logitech-control-center fails

### ISSUE THREAD

**Issue by sheim** [caskroom/homebrew-cask#30901]
#### Cannot uninstall or reinstall logitech-control-center

I'm on macOS 10.12.3 (16D32).  
Both "reinstall" and "uninstall" result in the same error:

<details><summary>`brew cask uninstall logitech-control-center --verbose`</summary>

```
==> Downloading https://www.logitech.com/pub/techsupport/mouse/mac/lcc3.9.5.66.zip
Already downloaded: /Users/sheim/Library/Caches/Homebrew/Cask/logitech-control-center--3.9.5.66.zip
==> Verifying checksum for Cask logitech-control-center
==> Running uninstall process for logitech-control-center; your password may be necessary
==> Running uninstall script LCC Installer.app/Contents/Resources/LCC Uninstaller Tool
==> 2017-03-14 15:41:50.249 LCC Uninstaller Tool[7986:123550] Running LCC Uninstall tool. Arguments = (
==>     "/usr/local/Caskroom/logitech-control-center/3.9.5.66/LCC Installer.app/Contents/Resources/LCC Uninstaller Tool"
==> )
==> Uninstalling packages:
com.Logitech.Control Center.pkg
Error: incompatible encoding regexp match (UTF-8 regexp with ASCII-8BIT string)
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/pre_bug_report.md

If this doesn’t fix the problem, please report this bug:
  https://github.com/caskroom/homebrew-cask#reporting-bugs

/usr/local/Homebrew/Library/Homebrew/vendor/plist/plist/parser.rb:91:in `scan'
/usr/local/Homebrew/Library/Homebrew/vendor/plist/plist/parser.rb:91:in `parse'
/usr/local/Homebrew/Library/Homebrew/vendor/plist/plist/parser.rb:29:in `parse_xml'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:160:in `_parse_plist'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:131:in `plist'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/pkg.rb:75:in `info'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/pkg.rb:66:in `pkgutil_bom_all'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/pkg.rb:54:in `pkgutil_bom_files'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/pkg.rb:17:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:191:in `block (2 levels) in uninstall_pkgutil'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:189:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:189:in `block in uninstall_pkgutil'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:188:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:188:in `uninstall_pkgutil'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:34:in `block (2 levels) in dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:32:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:32:in `block in dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:31:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:31:in `dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall.rb:7:in `uninstall_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:330:in `block in uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:327:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:327:in `uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:312:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/reinstall.rb:27:in `block in install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/reinstall.rb:6:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/reinstall.rb:6:in `install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:10:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:114:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:157:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
Error: Kernel.exit
```
</details>

<details><summary>Output of `brew doctor`</summary>

```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libgepetto-viewer-corba.dylib
  /usr/local/lib/libgepetto-viewer.dylib
  /usr/local/lib/libosgQt.3.5.5.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/gepetto/viewer/blender-geom-writer.h
  /usr/local/include/gepetto/viewer/config-osg.h
  /usr/local/include/gepetto/viewer/config.h
  /usr/local/include/gepetto/viewer/group-node.h
  /usr/local/include/gepetto/viewer/leaf-node-arrow.h
  /usr/local/include/gepetto/viewer/leaf-node-box.h
  /usr/local/include/gepetto/viewer/leaf-node-capsule.h
  /usr/local/include/gepetto/viewer/leaf-node-collada.h
  /usr/local/include/gepetto/viewer/leaf-node-cone.h
  /usr/local/include/gepetto/viewer/leaf-node-cylinder.h
  /usr/local/include/gepetto/viewer/leaf-node-face.h
  /usr/local/include/gepetto/viewer/leaf-node-ground.h
  /usr/local/include/gepetto/viewer/leaf-node-light.h
  /usr/local/include/gepetto/viewer/leaf-node-line.h
  /usr/local/include/gepetto/viewer/leaf-node-mesh.h
  /usr/local/include/gepetto/viewer/leaf-node-sphere.h
  /usr/local/include/gepetto/viewer/leaf-node-xyzaxis.h
  /usr/local/include/gepetto/viewer/macros.h
  /usr/local/include/gepetto/viewer/node-rod.h
  /usr/local/include/gepetto/viewer/node-visitor.h
  /usr/local/include/gepetto/viewer/node.h
  /usr/local/include/gepetto/viewer/OSGManipulator/keyboard-manipulator.h
  /usr/local/include/gepetto/viewer/roadmap-viewer.h
  /usr/local/include/gepetto/viewer/transform-writer.h
  /usr/local/include/gepetto/viewer/urdf-parser.h
  /usr/local/include/gepetto/viewer/window-manager.h

Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .pc files:
  /usr/local/lib/pkgconfig/gepetto-viewer-corba.pc
  /usr/local/lib/pkgconfig/gepetto-viewer.pc
  /usr/local/lib/pkgconfig/openscenegraph-osgQt.pc```
</details>

<details><summary>Output of `brew cask doctor`</summary>

```
==> Homebrew-Cask Version
Homebrew-Cask 1.1.11-73-gb6d10769
caskroom/homebrew-cask (git revision a331; last commit 2017-03-14)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (1 files, 16.6MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3606 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-fonts (1110 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (171 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Environment Variables
LANG="en_US.UTF-8"
PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/TeX/texbin:~/Repositories/AMD2/workspace/src/catkin/robots/hopperUser/x86_64mac:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/usr/local/bin/fish"```
</details>

**Comment by miccal** [comment]
I cannot test this as I can't even install it:
```
-bash-4.4.12- /Users/miccal [> brew cask install logitech-control-center
==> Downloading https://www.logitech.com/pub/techsupport/mouse/mac/lcc3.9.5.66.zip
######################################################################## 100.0%
==> Verifying checksum for Cask logitech-control-center
==> Running installer for logitech-control-center; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
Password:
```
I left it for an hour and nothing happened, so forced quit. Then:
```
-bash-4.4.12- /Users/miccal [> brew cask install logitech-control-center
Warning: A Cask for logitech-control-center is already installed.

To re-install logitech-control-center, run:
  brew cask reinstall logitech-control-center
```
Tried reinstalling:
```
-bash-4.4.12- /Users/miccal [> brew cask reinstall logitech-control-center
==> Downloading https://www.logitech.com/pub/techsupport/mouse/mac/lcc3.9.5.66.zip
Already downloaded: /Users/miccal/Library/Caches/Homebrew/Cask/logitech-control-center--3.9.5.66.zip
==> Verifying checksum for Cask logitech-control-center
==> Running uninstall process for logitech-control-center; your password may be necessary
==> Running uninstall script LCC Installer.app/Contents/Resources/LCC Uninstaller Tool
Password:
```
I left it for another hour and nothing happened, so forced quit. Then:
```
-bash-4.4.12- /Users/miccal [> brew cask zap logitech-control-center
==> Implied "brew cask uninstall logitech-control-center"
==> Running uninstall process for logitech-control-center; your password may be necessary
==> Running uninstall script LCC Installer.app/Contents/Resources/LCC Uninstaller Tool
==> 2017-03-15 07:53:59.284 LCC Uninstaller Tool[62516:2513600] Running LCC Uninstall tool. Arguments = (
==>     "/usr/local/Caskroom/logitech-control-center/3.9.5.66/LCC Installer.app/Contents/Resources/LCC Uninstaller Tool"
==> )
==> Removing files from pkgutil Bill-of-Materials
Warning: No zap stanza present for Cask 'logitech-control-center'
==> Removing all staged versions of Cask 'logitech-control-center'
```

**Comment by gobinathm** [comment]
Same issue.. tried multiple time & Multiple Macs .. same problem every where

**Comment by adidalal** [comment]
Can't install it either - candidate for removal, I'd say.

**Comment by Macxim** [comment]
Hi! I was about to add a new cask for logitech-control-center when I realised there was already one... but deleted.

Installation is working fine here (the cask I just created at least). Maybe something changed on Logitech's side?

```bash
❯❯ brew cask install logitech-control-center
❯ Installing logitech-control-center (logitech-control-center) into /Applications...
==> Caveats
You must reboot for the installation of logitech-control-center to take effect.

==> Downloading https://download01.logi.com/web/ftp/pub/techsupport/mouse/mac/lcc3.9.5.66.zip
######################################################################## 100.0%
==> Verifying checksum for Cask logitech-control-center
==> Running installer for logitech-control-center; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
Password:
==> installer: Package name is Logitech Control Center
==> installer: Upgrading at base path /
==> installer: The upgrade was successful.
==> installer: The install requires restarting now.
🍺  logitech-control-center was successfully installed!
```

```bash
❯ brew cask audit logitech-control-center --download
==> Downloading https://download01.logi.com/web/ftp/pub/techsupport/mouse/mac/lcc3.9.5.66.zip
Already downloaded: /Users/macxim/Library/Caches/Homebrew/Cask/logitech-control-center--3.9.5.66.zip
==> Verifying checksum for Cask logitech-control-center
audit for logitech-control-center: passed
```

**Comment by gobinathm** [comment]
@Macxim there is no ```logitech-control-center``` anymore. 

Ref #30938

**Comment by miccal** [comment]
@Macxim feel free to open a PR it it is indeed working now.

**Comment by Macxim** [comment]
@gobinathm I can see that. I was creating it when I saw the related issue and PR.
@miccal Will definitely do.

**Comment by phantomwhale** [comment]
Hmm - I'm getting the "hanging after password" issue myself now (using the restored `logitech-control-center` package from @Macxim (using Sierra)
