### ISSUE TITLE
Bug report: `brew cask install macvim` fails.

### ISSUE THREAD

**Issue by dkim** [caskroom/homebrew-cask#30953]
#### Description of issue

`brew cask install macvim` fails with `Error: comparison of Array with Array failed`. The #9227 issue might be related to this.

<details><summary>Output of `brew cask install --verbose macvim`</summary>

```
==> Satisfying dependencies
complete
==> Downloading https://github.com/macvim-dev/macvim/releases/download/snapshot-127/MacVim.dmg
Already downloaded: /Users/dkim/Library/Caches/Homebrew/Cask/macvim--8.0.127.dmg
==> Verifying checksum for Cask macvim
==> Moving App 'MacVim.app' to '/Applications/MacVim.app'.
==> Removing App '/Applications/MacVim.app'.
Error: comparison of Array with Array failed
Error: Kernel.exit
```
</details>

<details><summary>Output of `brew doctor`</summary>

```
Your system is ready to brew.
```
</details>

<details><summary>Output of `brew cask doctor`</summary>

```
==> Homebrew-Cask Version
Homebrew-Cask 1.1.11-88-g4d88cc4c4
caskroom/homebrew-cask (git revision f6749f; last commit 2017-03-15)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (1 files, 16.9MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3609 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-fonts (1110 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Environment Variables
LANG="en_US.UTF-8"
PATH="~/bin:/usr/local/bin:/usr/bin:/Library/TeX/texbin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```
</details>

**Comment by gobinathm** [comment]
Seems to be working...  I don't see this issue.

@dkim  can you post you  ```brew config``` output

<details><summary>Output of `brew cask install --verbose macvim`</summary>

```
==> Satisfying dependencies
complete
==> Downloading https://github.com/macvim-dev/macvim/releases/download/snapshot-127/MacVim.dmg
/usr/bin/curl --remote-time --location --user-agent Homebrew/1.1.11 (Macintosh; Intel macOS 10.12.3) curl/7.51.0 --fail https://github.com/macvim-dev/macvim/releases/download/snapshot-127/MacVim.dmg -C 0 -o /Users/gobinathm/Library/Caches/Homebrew/Cask/macvim--8.0.127.dmg.incomplete
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   586    0   586    0     0   1960      0 --:--:-- --:--:-- --:--:--  1966
100 16.9M  100 16.9M    0     0  7366k      0  0:00:02  0:00:02 --:--:-- 10.2M
==> Verifying checksum for Cask macvim
==> Moving App 'MacVim.app' to '/Applications/MacVim.app'
==> Symlinking Binary 'mvim' to '/usr/local/bin/gview'
==> Symlinking Binary 'mvim' to '/usr/local/bin/gvim'
==> Symlinking Binary 'mvim' to '/usr/local/bin/gvimdiff'
==> Symlinking Binary 'mvim' to '/usr/local/bin/gvimex'
==> Symlinking Binary 'mvim' to '/usr/local/bin/mview'
==> Symlinking Binary 'mvim' to '/usr/local/bin/mvim'
==> Symlinking Binary 'mvim' to '/usr/local/bin/mvimdiff'
==> Symlinking Binary 'mvim' to '/usr/local/bin/mvimex'
🍺  macvim was successfully installed!
```
</details>

<details><summary>Output of `brew doctor`</summary>

```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  php70
```
</details>

<details><summary>Output of `brew cask doctor`</summary>

```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  php70

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.bash_profile
  Gobinaths-MacBook-Pro:Casks gobinathm$ brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.1.11
caskroom/homebrew-cask (git revision f6749f; last commit 2017-03-15)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (354 files, 30.7GB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3609 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-drivers (45 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-eid (7 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-fonts (1110 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (171 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Environment Variables
LANG="en_US.UTF-8"
PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/cmd:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/usr/local/bin/bash"
```
</details>

<details><summary>Output of `brew config`</summary>

```
HOMEBREW_VERSION: 1.1.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: 394f9fa0aaa5854aa52bc589708a079665dcf462
Last commit: 9 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: acd630df256446f20819f29aec6d570f93b712c2
Core tap last commit: 6 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit skylake
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.12.0 => /usr/local/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.24.1/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.0/bin/ruby
Java: 1.8.0_121
macOS: 10.12.3-x86_64
Xcode: 8.2.1
CLT: 8.2.0.0.1.1480973914
X11: 2.7.11 => /opt/X11
```
</details>

**Comment by dkim** [comment]
@gobinathm Thank you for looking into this issue. Here is my `brew config` output:
```
$ brew config
HOMEBREW_VERSION: 1.1.11-88-g4d88cc4c4
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 4d88cc4c41113be2d5bf11c11fa671c763705a64
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 064379f86e23fe646c25bfe9052a9570f01c3df3
Core tap last commit: 2 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.12.0 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_121, 1.8.0_92, 1.8.0_91, 1.8.0_77, 1.8.0_74, 1.8.0_72, 1.8.0_71, 1.8.0_66, 1.8.0_60, 1.8.0_51, 1.8.0_45, 1.8.0_40, 1.8.0_31, 1.8.0_25, 1.8.0_20, 1.8.0_11
macOS: 10.12.3-x86_64
Xcode: 8.2.1
CLT: N/A
X11: 2.7.11 => /opt/X11
```
In addition, the output from `brew cask install --verbose --debug macvim` is as follows:
```
$ brew cask install --verbose --debug macvim
==> Loading Cask definitions
==> Translating 'macvim' into a valid Cask source
==> Testing source class Hbc::Source::URI
==> Testing source class Hbc::Source::PathSlashRequired
==> Testing source class Hbc::Source::TappedQualified
==> Testing source class Hbc::Source::UntappedQualified
==> Testing source class Hbc::Source::Tapped
==> Success! Using source class Hbc::Source::Tapped
==> Resolved Cask URI or file source to '/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask/Casks/macvim.rb'
==> Cask instance dumps in YAML:
Warning: Unexpected method 'encode_with' called on Cask macvim.
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/pre_bug_report.md

If this doesn’t fix the problem, please report this bug:
  https://github.com/caskroom/homebrew-cask#reporting-bugs

==> Cask instance toplevel:
--- !ruby/object:Hbc::Cask
token: macvim
sourcefile_path: !ruby/object:Pathname
  path: /usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask/Casks/macvim.rb
dsl: !ruby/object:Hbc::DSL {}
==> Cask instance method 'name':
---
- MacVim
==> Cask instance method 'homepage':
--- https://github.com/macvim-dev/macvim
...
==> Cask instance method 'url':
--- !ruby/object:Hbc::URL
uri: !ruby/object:URI::HTTPS
  scheme: https
  user:
  password:
  host: github.com
  port: 443
  path: /macvim-dev/macvim/releases/download/snapshot-127/MacVim.dmg
  query:
  opaque:
  registry:
  fragment:
  parser:
user_agent:
cookies:
referer:
using:
revision:
trust_cert:
data:
==> Cask instance method 'appcast':
---
- !ruby/object:URI::HTTPS
  scheme: https
  user:
  password:
  host: github.com
  port: 443
  path: /macvim-dev/macvim/releases.atom
  query:
  opaque:
  registry:
  fragment:
  parser:
- :checkpoint: 3b1212138bd21f5ce427abc371d728281e649d43742381b814463e9e680bfba7
==> Cask instance method 'version':
--- !ruby/string:Hbc::DSL::Version
str: !binary |-
  OC4wLjEyNw==
raw_version: 8.0.127
==> Cask instance method 'sha256':
--- 95ac1e407bf64902be1905239e7269394d58e5c0b7765d73a6b49547b97b19f4
...
==> Cask instance method 'artifacts':
---
:app: !ruby/object:Set
  hash:
    ? - MacVim.app
    : true
:binary: !ruby/object:Set
  hash:
    ? - mvim
      - :target: gview
    : true
    ? - mvim
      - :target: gvim
    : true
    ? - mvim
      - :target: gvimdiff
    : true
    ? - mvim
      - :target: gvimex
    : true
    ? - mvim
      - :target: mview
    : true
    ? - mvim
      - :target: mvim
    : true
    ? - mvim
      - :target: mvimdiff
    : true
    ? - mvim
      - :target: mvimex
    : true
:zap: !ruby/object:Set
  hash:
    ? :delete:
      - ~/Library/Caches/org.vim.MacVim
      - ~/Library/Preferences/org.vim.MacVim.LSSharedFileList.plist
      - ~/Library/Preferences/org.vim.MacVim.plist
    : true
==> Cask instance method 'caveats':
--- []
==> Cask instance method 'depends_on':
---
:macos:
- - :>=
  - !ruby/object:Gem::Version
    version: '10.8'
==> Cask instance method 'conflicts_with':
---
:formula: macvim
==> Cask instance method 'container':
---
...
==> Cask instance method 'gpg':
---
...
==> Cask instance method 'accessibility_access':
---
...
==> Cask instance method 'auto_updates':
---
...
==> Hbc::Installer#install
==> Printing caveats
==> Hbc::Installer#fetch
==> Satisfying dependencies
complete
==> Downloading
==> Downloading https://github.com/macvim-dev/macvim/releases/download/snapshot-127/MacVim.dmg
Already downloaded: /Users/XXX/Library/Caches/Homebrew/Cask/macvim--8.0.127.dmg
==> Downloaded to -> /Users/XXX/Library/Caches/Homebrew/Cask/macvim--8.0.127.dmg
==> Verifying download
==> Determining which verifications to run for Cask macvim
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask macvim
==> SHA256 checksums match
==> Hbc::Installer#stage
==> Extracting primary container
==> Determining which containers to use based on filetype
==> Checking container class Hbc::Container::Pkg
==> Checking container class Hbc::Container::Ttf
==> Checking container class Hbc::Container::Otf
==> Checking container class Hbc::Container::Air
==> Checking container class Hbc::Container::Cab
==> Checking container class Hbc::Container::Dmg
==> Executing: ["/usr/bin/hdiutil", "imageinfo", "/Users/XXX/Library/Caches/Homebrew/Cask/macvim--8.0.127.dmg"]
==> Using container class Hbc::Container::Dmg for /Users/XXX/Library/Caches/Homebrew/Cask/macvim--8.0.127.dmg
==> Executing: ["/usr/bin/hdiutil", "mount", "-plist", "-nobrowse", "-readonly", "-noidme", "-mountrandom", "/tmp", "/Users/XXX/Library/Caches/Homebrew/Cask/macvim--8.0.127.dmg"]
==> Executing: ["/usr/bin/mkbom", "-s", "-i", "/var/folders/b9/d4kf_lyj18b1b1ng9fjhldkm0000gn/T/20170315-17176-1xc2xej.list", "--", "/var/folders/b9/d4kf_lyj18b1b1ng9fjhldkm0000gn/T/20170315-17176-j0a1dq.bom"]
==> Executing: ["/usr/bin/ditto", "--bom", "/var/folders/b9/d4kf_lyj18b1b1ng9fjhldkm0000gn/T/20170315-17176-j0a1dq.bom", "--", "/private/tmp/dmg.zBX7b2", "/usr/local/Caskroom/macvim/8.0.127"]
==> Executing: ["/usr/sbin/diskutil", "eject", "/private/tmp/dmg.zBX7b2"]
==> Creating metadata directory /usr/local/Caskroom/macvim/.metadata/8.0.127/20170315173452.928
==> Creating metadata subdirectory /usr/local/Caskroom/macvim/.metadata/8.0.127/20170315173452.928/Casks
==> Installing artifacts
==> Determining which artifacts are present in Cask macvim
==> 3 artifact/s defined
#<Hbc::Artifact::App:0x007f83a0e55968>
#<Hbc::Artifact::Binary:0x007f83a0e558f0>
#<Hbc::Artifact::Zap:0x007f83a0e55878>
==> Installing artifact of class Hbc::Artifact::App
==> Moving App 'MacVim.app' to '/Applications/MacVim.app'.
==> Installing artifact of class Hbc::Artifact::Binary
==> Reverting installation of artifact of class Hbc::Artifact::App
==> Removing App '/Applications/MacVim.app'.
==> Purging files for version 8.0.127 of Cask macvim
Error: comparison of Array with Array failed/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/relocated.rb:47:in `sort'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/relocated.rb:47:in `each_artifact'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/symlinked.rb:15:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/binary.rb:7:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:144:in `block in install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:141:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:141:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:87:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:25:in `block in install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:19:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:19:in `install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:10:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:114:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:157:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:162:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:162:in `rescue in process'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:148:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
```

**Comment by dkim** [comment]
I have reinstalled my Xcode command line tools because the `brew config` output above indicated that it could not find the tools for some reason:
```
$ xcode-select --install
```

```
$ brew config
HOMEBREW_VERSION: 1.1.11-88-g4d88cc4c4
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 4d88cc4c41113be2d5bf11c11fa671c763705a64
Last commit: 3 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 7eb8889e1ee07dc9cf988ea96105fde07c094a6e
Core tap last commit: 30 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.12.0 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_121, 1.8.0_92, 1.8.0_91, 1.8.0_77, 1.8.0_74, 1.8.0_72, 1.8.0_71, 1.8.0_66, 1.8.0_60, 1.8.0_51, 1.8.0_45, 1.8.0_40, 1.8.0_31, 1.8.0_25, 1.8.0_20, 1.8.0_11
macOS: 10.12.3-x86_64
Xcode: 8.2.1
CLT: 8.2.0.0.1.1480973914
X11: 2.7.11 => /opt/X11
```
However, `brew cask install macvim` still fails with the same error.
