### ISSUE TITLE
Bug report: Problem uninstalling the wireshark cask

### ISSUE THREAD

**Issue by alireza** [caskroom/homebrew-cask#31694]
Hi. I have followed the [pre bug report](https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/pre_bug_report.md) but that didn't help. I've also looked up the issue online and found https://github.com/caskroom/homebrew-cask/issues/27070 but the solution in there didn't work for me.

#### Description of issue

I had Wireshark installed with homebrew cask a while ago. It was a version that used XQuartz. Today, I saw there has been a new macOS native version out, so I tried to uninstall the old version but I get this error.

<details><summary>Output of `brew cask uninstall wireshark --verbose`</summary>

```
==> Running uninstall process for wireshark; your password may be necessary
==> Running uninstall script /usr/sbin/dseditgroup
==> Group not found.
Error: Command failed to execute!

==> Failed command:
/usr/bin/sudo -E -- #<Pathname:/usr/sbin/dseditgroup> -o delete access_bpf

==> Standard Output of failed command:


==> Standard Error of failed command:
Group not found.


==> Exit status of failed command:
#<Process::Status: pid 3916 exit 64>
Error: Kernel.exit
```
</details>

<details><summary>Output of `brew doctor`</summary>

```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  docutils
```
</details>

<details><summary>Output of `brew cask doctor`</summary>

```
==> Homebrew-Cask Version
Homebrew-Cask 1.1.11-205-g80b39bb
caskroom/homebrew-cask (git revision 1781; last commit 2017-03-31)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3620 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-boneyard (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-dupes (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-fuse (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-head-only (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-python (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-science (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-versions (0 casks)
/usr/local/Homebrew/Library/Taps/neovim/homebrew-neovim (0 casks)
/usr/local/Homebrew/Library/Taps/universal-ctags/homebrew-universal-ctags (0 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Gems/2.0.0/gems/json-1.8.3/lib
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Environment Variables
LANG="en_US.UTF-8"
PATH="/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Wireshark.app/Contents/MacOS:/usr/local/sbin:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-boneyard/cmd:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/cmd:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/usr/local/bin/bash"

```
</details>

<br>
I appreciate any help.
Thanks!

**Comment by vitorgalvao** [comment]
`brew cask uninstall --force wireshark`

**Comment by alireza** [comment]
Thanks for the response. Tried your suggestion. I still get the same output:

```
↦ brew cask uninstall --force wireshark
==> Running uninstall process for wireshark; your password may be necessary
==> Running uninstall script /usr/sbin/dseditgroup
==> Group not found.
Error: Command failed to execute!

==> Failed command:
/usr/bin/sudo -E -- #<Pathname:/usr/sbin/dseditgroup> -o delete access_bpf

==> Standard Output of failed command:


==> Standard Error of failed command:
Group not found.


==> Exit status of failed command:
#<Process::Status: pid 9019 exit 64>
```

**Comment by vitorgalvao** [comment]
`brew cask install --force wireshark`.

It seems the group wasn’t created (or was deleted after by something else), so try forcing installing over and then uninstalling.

**Comment by blogabe** [comment]
I'm experiencing the same issue with a different cask.  @vitorgalvao I tried your suggestion, but it doesn't work.  Please advise if I should create a new issue.
```
$ brew cask uninstall --force adobe-air
==> Running uninstall process for adobe-air; your password may be necessary
==> Running uninstall script Adobe AIR Installer.app/Contents/MacOS/Adobe AIR Installer
==> Uninstalling Adobe AIR (all versions)
==> failed (consult log)
Error: Command failed to execute!

==> Failed command:
#<Pathname:/usr/local/Caskroom/adobe-air/25.0/Adobe AIR Installer.app/Contents/MacOS/Adobe AIR Installer> -uninstall

==> Standard Output of failed command:
Uninstalling Adobe AIR (all versions)
failed (consult log)


==> Standard Error of failed command:


==> Exit status of failed command:
#<Process::Status: pid 34754 exit 7>
$ brew cask install --force adobe-air
==> Downloading https://airdownload.adobe.com/air/mac/download/25.0/AdobeAIR.dmg
######################################################################## 100.0%
==> No checksum defined for Cask adobe-air, skipping verification
==> Running installer script Adobe AIR Installer.app/Contents/MacOS/Adobe AIR Installer
Password:
==> Version 25.0.0.134 is current; no actions to take
==> done
🍺  adobe-air was successfully installed!
$ brew cask uninstall --force adobe-air
==> Running uninstall process for adobe-air; your password may be necessary
==> Running uninstall script Adobe AIR Installer.app/Contents/MacOS/Adobe AIR Installer
==> Uninstalling Adobe AIR (all versions)
==> failed (consult log)
Error: Command failed to execute!

==> Failed command:
#<Pathname:/usr/local/Caskroom/adobe-air/25.0/Adobe AIR Installer.app/Contents/MacOS/Adobe AIR Installer> -uninstall

==> Standard Output of failed command:
Uninstalling Adobe AIR (all versions)
failed (consult log)


==> Standard Error of failed command:


==> Exit status of failed command:
#<Process::Status: pid 34881 exit 7>
```

**Comment by vitorgalvao** [comment]
@blogabe Yes, please create a new issue. Your problem is not at all the same.

**Comment by alireza** [comment]
Okay. There is some progress. It installed correctly:

<details>
<summary> brew cask install --force wireshark </summary>

==> Satisfying dependencies
complete
==> Downloading https://www.wireshark.org/download/osx/Wireshark%202.2.5%20Intel%2064.dmg
######################################################################## 100.0%
==> Verifying checksum for Cask wireshark
==> Running installer for wireshark; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
Password:
Password:==> Sorry, try again.

==> installer: Package name is Wireshark 2.2.5 Intel 64
==> installer: Upgrading at base path /
==> installer: The upgrade was successful.
🍺  wireshark was successfully installed!

</details>

<br>
Uninstalling now give a different error:

<br>

```
↦ brew cask uninstall --force wireshark
==> Running uninstall process for wireshark; your password may be necessary
==> Running uninstall script /usr/sbin/dseditgroup
==> Group record below will be deleted:
==> dsAttrTypeStandard:GeneratedUID -
==>             92BEB512-E2E8-4E96-92D3-1BF11F129737
==> dsAttrTypeStandard:RecordName -
==>             access_bpf
==> dsAttrTypeStandard:AppleMetaNodeLocation -
==>             /Local/Default
==> dsAttrTypeStandard:GroupMembers -                                                                                                        [0/912]
==>             FFFFEEEE-DDDD-CCCC-BBBB-AAAA00000000
==>             A7B27E50-1187-4202-9372-51284F70342D
==> dsAttrTypeStandard:PrimaryGroupID -
==>             502
==> dsAttrTypeStandard:RecordType -
==>             dsRecTypeStandard:Groups
==> dsAttrTypeStandard:GroupMembership -
==>             root
==>             alireza
==> Uninstalling packages:
org.wireshark.ChmodBPF.pkg
Error: Permission denied - /Library/Application Support/Wireshark
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/pre_bug_report.md

If this doesn’t fix the problem, please report this bug:
  https://github.com/caskroom/homebrew-cask#reporting-bugs

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:425:in `open'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:425:in `foreach'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:425:in `children'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/pkg.rb:85:in `rmdir'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/pkg.rb:42:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:191:in `block (2 levels) in uninstall_pkgutil'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:189:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:189:in `block in uninstall_pkgutil'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:188:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:188:in `uninstall_pkgutil'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:34:in `block (2 levels) in dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:32:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:32:in `block in dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:31:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:31:in `dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall.rb:7:in `uninstall_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:330:in `block in uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:327:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:327:in `uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:312:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:26:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:9:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:9:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:115:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:158:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
```

**Comment by vitorgalvao** [comment]
@alireza `brew update` and try again. A recent addition might fix that.

**Comment by thehunmonkgroup** [comment]
@vitorgalvao same issue reported in @alireza's last comment. Digging a bit further:
```
sudo ls -al /Library/Application\ Support/Wireshark/
total 0
drwx------   3 504   wheel  102 Nov 18 15:21 .
drwxr-xr-x  24 root  admin  816 Apr  4 13:43 ..
drwxrwxr-x   4 504   staff  136 Apr  6 13:50 ChmodBPF
```
this complete sequence resulted in a successful uninstall:
```
sudo chown root:wheel /Library/Application\ Support/Wireshark
sudo chmod 755 /Library/Application\ Support/Wireshark
brew cask install --force wireshark
brew cask uninstall --force wireshark
```

**Comment by informaterian** [comment]
I added a `brew cask install --force wireshark` before the sequence of @thehunmonkgroup  because the directory in Application Support was not found. 
That worked well for me.
> sudo chown root:wheel /Library/Application\ Support/Wireshark
sudo chmod 755 /Library/Application\ Support/Wireshark
brew cask install --force wireshark
brew cask uninstall --force wireshark

**Comment by jottr** [comment]
I'm seeing this issue as well. 
@thehunmonkgroups [solution](https://github.com/caskroom/homebrew-cask/issues/31694#issuecomment-292317776) did not work for me:

```shell
# ls -lahc /Library/Application\ Support/Wireshark
total 0
drwx------  3 root wheel  102 Apr 10 15:14 ./
drwxr-xr-x 33 root admin 1122 Apr 10 15:14 ../
drwxrwxr-x  4  504 staff  136 Mär  3 22:04 ChmodBPF/
```

After trying to `--force` uninstall still didn't work, I  recursively changed the group ownership : 

```shell
# chown -Rv root:wheel /Library/Application\ Support/Wireshark

# ls -lach  /Library/Application\ Support/Wireshark                                                                                                         

total 0
drwx------  3 root wheel  102 Apr 10 15:18 .
drwxr-xr-x 33 root admin 1,1K Apr 10 15:14 ..
drwxrwxr-x  4 root wheel  136 Apr 10 15:18 ChmodBPF
```

`Group not found.`-issue remains:

```shell
$ brew cask uninstall --force wireshark
==> Running uninstall process for wireshark; your password may be necessary
==> Running uninstall script /usr/sbin/dseditgroup
==> Group not found.
Error: Command failed to execute!

==> Failed command:
/usr/bin/sudo -E -- #<Pathname:/usr/sbin/dseditgroup> -o delete access_bpf

==> Standard Output of failed command:


==> Standard Error of failed command:
Group not found.


==> Exit status of failed command:
#<Process::Status: pid 75882 exit 64>
```

**Comment by thehunmonkgroup** [comment]
@jottr you can try setting it to a different group, 'staff' is probably better, so i've edited my above comment to reflect that.

**Comment by jottr** [comment]
Thx @thehunmonkgroup  your updated sequence above fixed it.

**Comment by drkibitz** [comment]
Same issue, thanks @thehunmonkgroup, that worked.

**Comment by vitorgalvao** [comment]
Anyone that has already fixed the issue. Can you now:

1. Completely uninstall `wireshark`.
2. `brew cask install https://raw.githubusercontent.com/caskroom/homebrew-cask/c06fcfef7811792206c6057df30aa1dfa8903073/Casks/wireshark.rb`
3. `brew cask uninstall https://raw.githubusercontent.com/caskroom/homebrew-cask/c06fcfef7811792206c6057df30aa1dfa8903073/Casks/wireshark.rb`

And say if everything works fine?

I’d do it but I still don’t have access to a VM (Veertu is months behind on delivering macOS guest support).

**Comment by thehunmonkgroup** [comment]
doesn't look like it:
```
[hunmonk:~] 6s $ brew cask install https://raw.githubusercontent.com/caskroom/homebrew-cask/c06fcfef7811792206c6057df30aa1dfa8903073/Casks/wireshark.rb
==> Downloading https://raw.githubusercontent.com/caskroom/homebrew-cask/c06fcfef7811792206c6057df30aa1dfa8903073/Casks/wires
######################################################################## 100.0%
==> Satisfying dependencies
complete
==> Downloading https://www.wireshark.org/download/osx/Wireshark%202.2.5%20Intel%2064.dmg
Already downloaded: /Users/hunmonk/Library/Caches/Homebrew/Cask/wireshark--2.2.5.dmg
==> Verifying checksum for Cask wireshark
==> Running installer for wireshark; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
==> installer: Package name is Wireshark 2.2.5 Intel 64
==> installer: Installing at base path /
==> installer: The install was successful.
🍺  wireshark was successfully installed!
[hunmonk:~] 7s $ brew cask uninstall https://raw.githubusercontent.com/caskroom/homebrew-cask/c06fcfef7811792206c6057df30aa1dfa8903073/Casks/wireshark.rb
==> Downloading https://raw.githubusercontent.com/caskroom/homebrew-cask/c06fcfef7811792206c6057df30aa1dfa8903073/Casks/wires
######################################################################## 100.0%
==> Running uninstall process for wireshark; your password may be necessary
==> Uninstalling packages:
org.wireshark.ChmodBPF.pkg
Error: Permission denied - /Library/Application Support/Wireshark
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask#reporting-bugs
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:425:in `open'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:425:in `foreach'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:425:in `children'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/pkg.rb:85:in `rmdir'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/pkg.rb:42:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:191:in `block (2 levels) in uninstall_pkgutil'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:189:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:189:in `block in uninstall_pkgutil'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:188:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:188:in `uninstall_pkgutil'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:34:in `block (2 levels) in dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:32:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:32:in `block in dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:31:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:31:in `dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall.rb:7:in `uninstall_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:330:in `block in uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:327:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:327:in `uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:312:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:26:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:9:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:9:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:115:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:158:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
```

**Comment by vitorgalvao** [comment]
What about:

1. `brew cask install https://raw.githubusercontent.com/caskroom/homebrew-cask/968035375841770a961c8c16ee49db6fce88db51/Casks/wireshark.rb`
2. `brew cask uninstall https://raw.githubusercontent.com/caskroom/homebrew-cask/968035375841770a961c8c16ee49db6fce88db51/Casks/wireshark.rb`

**Comment by commitay** [comment]
@vitorgalvao I've tried this in a VM, it looks like `uninstall_preflight` doesn't run before `uninstall pkgutil:`

```
brew cask uninstall https://raw.githubusercontent.com/caskroom/homebrew-cask/968035375841770a961c8c16ee49db6fce88db51/Casks/wireshark.rb --verbose --debug
==> Uninstalling Cask https://raw.githubusercontent.com/caskroom/homebrew-cask/968035375841770a961c8c16ee49db6fce88db51/Casks/wireshark.rb
==> Downloading https://raw.githubusercontent.com/caskroom/homebrew-cask/968035375841770a961c8c16ee49db6fce88db51/Casks/wireshark.rb.
/usr/bin/curl --remote-time --location --user-agent Homebrew/1.1.12 (Macintosh; Intel macOS 10.12.4) curl/7.51.0 --fail https://raw.githubusercontent.com/caskroom/homebrew-cask/968035375841770a961c8c16ee49db6fce88db51/Casks/wireshark.rb -o /Users/commitay/Library/Caches/Homebrew/Cask/wireshark.rb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1761  100  1761    0     0    450      0  0:00:03  0:00:03 --:--:--   450
==> Hbc::Installer#uninstall
==> Un-installing artifacts
==> Determining which artifacts are present in Cask wireshark
==> 4 artifact/s defined
#<Hbc::Artifact::Uninstall:0x007fbabdfb9648>
#<Hbc::Artifact::PreflightBlock:0x007fbabdfb9738>
#<Hbc::Artifact::Pkg:0x007fbabdfb96c0>
#<Hbc::Artifact::PostflightBlock:0x007fbabdfb95d0>
==> Un-installing artifact of class Hbc::Artifact::Uninstall
==> Running uninstall process for wireshark; your password may be necessary
==> Uninstalling packages:
==> Executing: ["/usr/sbin/pkgutil", "--pkgs=org.wireshark.*"]
org.wireshark.ChmodBPF.pkg
==> Executing: ["/usr/sbin/pkgutil", "--export-plist", "org.wireshark.ChmodBPF.pkg"]
Error: Permission denied - /Library/Application Support/Wireshark
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask#reporting-bugs
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:425:in `open'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:425:in `foreach'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:425:in `children'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/pkg.rb:85:in `rmdir'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/pkg.rb:42:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:191:in `block (2 levels) in uninstall_pkgutil'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:189:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:189:in `block in uninstall_pkgutil'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:188:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:188:in `uninstall_pkgutil'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:34:in `block (2 levels) in dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:32:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:32:in `block in dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:31:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:31:in `dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall.rb:7:in `uninstall_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:330:in `block in uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:327:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:327:in `uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:312:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:26:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:9:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:9:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:115:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:158:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:169:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:169:in `rescue in process'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:149:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
```

**Comment by vitorgalvao** [comment]
@commitay Indeed the `preflight` block seems to want to run after the `uninstall` block, which defeats the purpose.

@reitermarkus Does that look normal to you?

**Comment by commitay** [comment]
I can confirm `uninstall_preflight` runs after `uninstall` with other casks.

```
brew cask uninstall whatsyoursign --verbose --debug
==> Uninstalling Cask whatsyoursign
==> Hbc::Installer#uninstall
==> Un-installing artifacts
==> Determining which artifacts are present in Cask whatsyoursign
==> 3 artifact/s defined
#<Hbc::Artifact::Uninstall:0x007fbb17a74ae8>
#<Hbc::Artifact::Installer:0x007fbb17a74b60>
#<Hbc::Artifact::PreflightBlock:0x007fbb17a74bd8>
==> Un-installing artifact of class Hbc::Artifact::Uninstall
==> Running uninstall process for whatsyoursign; your password may be necessary
==> Removing files:
/Applications/WhatsYourSign.app
==> Executing: ["/usr/bin/sudo", "-E", "--", "/usr/bin/xargs", "-0", "--", "/bin/rm", "-r", "-f", "--"]
~/Library/Application Scripts/com.objective-see.WhatsYourSignExt.FinderSync
==> Executing: ["/usr/bin/sudo", "-E", "--", "/usr/bin/xargs", "-0", "--", "/bin/rm", "-r", "-f", "--"]
~/Library/Containers/com.objective-see.WhatsYourSignExt.FinderSync
==> Executing: ["/usr/bin/sudo", "-E", "--", "/usr/bin/xargs", "-0", "--", "/bin/rm", "-r", "-f", "--"]
==> Un-installing artifact of class Hbc::Artifact::PreflightBlock
==> Executing: ["/usr/bin/pluginkit", "-r", "/Applications/WhatsYourSign.app/Contents/PlugIns/WhatsYourSign.appex"]
==> remove: no plugin at /Applications/WhatsYourSign.app/Contents/PlugIns/WhatsYourSign.appex
Error: Command failed to execute!

==> Failed command:
/usr/bin/pluginkit -r /Applications/WhatsYourSign.app/Contents/PlugIns/WhatsYourSign.appex

==> Standard Output of failed command:


==> Standard Error of failed command:
remove: no plugin at /Applications/WhatsYourSign.app/Contents/PlugIns/WhatsYourSign.appex


==> Exit status of failed command:
#<Process::Status: pid 3431 exit 1>
```

- I've done a PR for `wireshark` to work around this for now.  #32292
- Should we move discussion for `uninstall_preflight` to a new issue?

**Comment by echo1937** [comment]
it helps.
