### ISSUE TITLE
No way to install android-sdk

### ISSUE THREAD

**Issue by GeoffreyPlitt** [caskroom/homebrew-cask#31727]
Latest Mac OS X, brew.

Until today, the following worked:
```brew install android-sdk```

Today, it fails and recommends this:
```brew cask install Caskroom/cask/android-sdk ``` which also doesn't work:
```
Geoffs-MacBook-Pro:stardust-backend giro$ brew cask install Caskroom/cask/android-sdk
Error: Tap caskroom/cask already tapped.

Follow the instructions here:
  https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/pre_bug_report.md

If this doesn’t fix the problem, please report this bug:
  https://github.com/caskroom/homebrew-cask#reporting-bugs

/usr/local/Homebrew/Library/Homebrew/tap.rb:196:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/source/untapped_qualified.rb:9:in `me?'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/source.rb:28:in `block in for_query'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/source.rb:26:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/source.rb:26:in `find'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/source.rb:26:in `for_query'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc.rb:56:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:21:in `block in install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:19:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:19:in `install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:10:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:101:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:144:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
```

Please advise, thanks.

**Comment by miccal** [comment]
https://github.com/caskroom/homebrew-cask/pull/31598
