### ISSUE TITLE
`audit` with no arguments is broken

### ISSUE THREAD

**Issue by vitorgalvao** [caskroom/homebrew-cask#31784]
`brew cask audit` with no arguments should audit every cask (as it used to) but instead errors out.

```
$ brew cask audit
Error: cannot load such file -- caskroom/cask/010-editor
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/scopes.rb:10:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/scopes.rb:10:in `block in all'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/scopes.rb:10:in `map'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/scopes.rb:10:in `all'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/audit.rb:41:in `casks_to_audit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/audit.rb:20:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/audit.rb:9:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:115:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:158:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
```

Refs https://github.com/caskroom/homebrew-cask/issues/31317. Pinging @reitermarkus.

**Comment by giannitm** [comment]
I have also been having this issue for just over a week.

**Comment by vitorgalvao** [comment]
Also pinging @claui and @mwean in case any of them want to tackle it.

**Comment by mwean** [comment]
I probably won't have time to take a look until this weekend.
