### ISSUE TITLE
Android SDK Install Fails

### ISSUE THREAD

**Issue by datwheat** [caskroom/homebrew-cask#31797]
#### Description of issue

I'm trying to install android-sdk with the new Cask, but it fails because of sqlite3.

#### Output of your command with `--verbose --debug`

```
brew cask reinstall android-sdk --verbose --debug
==> Printing caveats
==> Caveats
We will install android-sdk-tools, platform-tools, and build-tools for you.
You can control android sdk packages via the sdkmanager command.
You may want to add to your profile:
  'export ANDROID_HOME=/usr/local/share/android-sdk'

==> Hbc::Installer#fetch
==> Downloading
==> Downloading https://dl.google.com/android/repository/tools_r25.2.3-macosx.zip
Already downloaded: /Users/datwheat/Library/Caches/Homebrew/Cask/android-sdk--25.2.3.zip
==> Downloaded to -> /Users/datwheat/Library/Caches/Homebrew/Cask/android-sdk--25.2.3.zip
==> Verifying download
==> Determining which verifications to run for Cask android-sdk
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask android-sdk
==> SHA256 checksums match
==> Hbc::Installer#uninstall
==> Un-installing artifacts
==> Determining which artifacts are present in Cask android-sdk
==> 3 artifact/s defined
#<Hbc::Artifact::PreflightBlock:0x007f84d98e5c78>
#<Hbc::Artifact::Binary:0x007f84d98e5b10>
#<Hbc::Artifact::PostflightBlock:0x007f84d98e5a48>
==> Un-installing artifact of class Hbc::Artifact::PreflightBlock
==> Un-installing artifact of class Hbc::Artifact::Binary
==> Un-installing artifact of class Hbc::Artifact::PostflightBlock
==> Purging files for version 25.2.3 of Cask android-sdk
==> Purging all staged versions of Cask android-sdk
==> Hbc::Installer#stage
==> Extracting primary container
==> Determining which containers to use based on filetype
==> Checking container class Hbc::Container::Pkg
==> Checking container class Hbc::Container::Ttf
==> Checking container class Hbc::Container::Otf
==> Checking container class Hbc::Container::Air
==> Checking container class Hbc::Container::Cab
==> Checking container class Hbc::Container::Dmg
==> Executing: ["/usr/bin/hdiutil", "imageinfo", "/Users/datwheat/Library/Caches/Homebrew/Cask/android-sdk--25.2.3.zip"]
==> Checking container class Hbc::Container::SevenZip
==> Checking container class Hbc::Container::Sit
==> Checking container class Hbc::Container::Rar
==> Checking container class Hbc::Container::Zip
==> Using container class Hbc::Container::Zip for /Users/datwheat/Library/Caches/Homebrew/Cask/android-sdk--25.2.3.zip
==> Executing: ["/usr/bin/ditto", "-x", "-k", "--", "/Users/datwheat/Library/Caches/Homebrew/Cask/android-sdk--25.2.3.zip", "/var/folders/49/y98zqmnn16d1ddflc35rrbr40000gn/T/d20170403-15714-1tkg7u4"]
==> Creating metadata directory /usr/local/Caskroom/android-sdk/.metadata/25.2.3/20170403111037.744
==> Creating metadata subdirectory /usr/local/Caskroom/android-sdk/.metadata/25.2.3/20170403111037.744/Casks
==> Installing artifacts
==> Determining which artifacts are present in Cask android-sdk
==> 3 artifact/s defined
#<Hbc::Artifact::PreflightBlock:0x007f84dacb4998>
#<Hbc::Artifact::Binary:0x007f84dacb4920>
#<Hbc::Artifact::PostflightBlock:0x007f84dacb48a8>
==> Installing artifact of class Hbc::Artifact::PreflightBlock
==> Executing: ["/usr/local/Caskroom/android-sdk/25.2.3/tools/bin/sdkmanager", "tools", "platform-tools", "build-tools;25.0.2"]
==> Installing artifact of class Hbc::Artifact::Binary
==> Linking Binary 'aapt' to '/usr/local/bin/aapt'.
==> Executing: ["/bin/ln", "-h", "-f", "-s", "--", "/usr/local/Caskroom/android-sdk/25.2.3/build-tools/25.0.2/aapt", "/usr/local/bin/aapt"]
==> Linking Binary 'aapt2' to '/usr/local/bin/aapt2'.
==> Executing: ["/bin/ln", "-h", "-f", "-s", "--", "/usr/local/Caskroom/android-sdk/25.2.3/build-tools/25.0.2/aapt2", "/usr/local/bin/aapt2"]
==> Linking Binary 'aidl' to '/usr/local/bin/aidl'.
==> Executing: ["/bin/ln", "-h", "-f", "-s", "--", "/usr/local/Caskroom/android-sdk/25.2.3/build-tools/25.0.2/aidl", "/usr/local/bin/aidl"]
==> Linking Binary 'apksigner' to '/usr/local/bin/apksigner'.
==> Executing: ["/bin/ln", "-h", "-f", "-s", "--", "/usr/local/Caskroom/android-sdk/25.2.3/build-tools/25.0.2/apksigner", "/usr/local/bin/apksigner"]
==> Linking Binary 'dexdump' to '/usr/local/bin/dexdump'.
==> Executing: ["/bin/ln", "-h", "-f", "-s", "--", "/usr/local/Caskroom/android-sdk/25.2.3/build-tools/25.0.2/dexdump", "/usr/local/bin/dexdump"]
==> Linking Binary 'dx' to '/usr/local/bin/dx'.
==> Executing: ["/bin/ln", "-h", "-f", "-s", "--", "/usr/local/Caskroom/android-sdk/25.2.3/build-tools/25.0.2/dx", "/usr/local/bin/dx"]
==> Linking Binary 'llvm-rs-cc' to '/usr/local/bin/llvm-rs-cc'.
==> Executing: ["/bin/ln", "-h", "-f", "-s", "--", "/usr/local/Caskroom/android-sdk/25.2.3/build-tools/25.0.2/llvm-rs-cc", "/usr/local/bin/llvm-rs-cc"]
==> Linking Binary 'zipalign' to '/usr/local/bin/zipalign'.
==> Executing: ["/bin/ln", "-h", "-f", "-s", "--", "/usr/local/Caskroom/android-sdk/25.2.3/build-tools/25.0.2/zipalign", "/usr/local/bin/zipalign"]
==> Linking Binary 'emulator' to '/usr/local/bin/emulator'.
==> Executing: ["/bin/ln", "-h", "-f", "-s", "--", "/usr/local/Caskroom/android-sdk/25.2.3/emulator/emulator", "/usr/local/bin/emulator"]
==> Linking Binary 'emulator-check' to '/usr/local/bin/emulator-check'.
==> Executing: ["/bin/ln", "-h", "-f", "-s", "--", "/usr/local/Caskroom/android-sdk/25.2.3/emulator/emulator-check", "/usr/local/bin/emulator-check"]
==> Linking Binary 'emulator64-arm' to '/usr/local/bin/emulator64-arm'.
==> Executing: ["/bin/ln", "-h", "-f", "-s", "--", "/usr/local/Caskroom/android-sdk/25.2.3/emulator/emulator64-arm", "/usr/local/bin/emulator64-arm"]
==> Linking Binary 'emulator64-mips' to '/usr/local/bin/emulator64-mips'.
==> Executing: ["/bin/ln", "-h", "-f", "-s", "--", "/usr/local/Caskroom/android-sdk/25.2.3/emulator/emulator64-mips", "/usr/local/bin/emulator64-mips"]
==> Linking Binary 'emulator64-x86' to '/usr/local/bin/emulator64-x86'.
==> Executing: ["/bin/ln", "-h", "-f", "-s", "--", "/usr/local/Caskroom/android-sdk/25.2.3/emulator/emulator64-x86", "/usr/local/bin/emulator64-x86"]
==> Linking Binary 'adb' to '/usr/local/bin/adb'.
==> Executing: ["/bin/ln", "-h", "-f", "-s", "--", "/usr/local/Caskroom/android-sdk/25.2.3/platform-tools/adb", "/usr/local/bin/adb"]
==> Linking Binary 'dmtracedump' to '/usr/local/bin/dmtracedump'.
==> Executing: ["/bin/ln", "-h", "-f", "-s", "--", "/usr/local/Caskroom/android-sdk/25.2.3/platform-tools/dmtracedump", "/usr/local/bin/dmtracedump"]
==> Linking Binary 'etc1tool' to '/usr/local/bin/etc1tool'.
==> Executing: ["/bin/ln", "-h", "-f", "-s", "--", "/usr/local/Caskroom/android-sdk/25.2.3/platform-tools/etc1tool", "/usr/local/bin/etc1tool"]
==> Linking Binary 'fastboot' to '/usr/local/bin/fastboot'.
==> Executing: ["/bin/ln", "-h", "-f", "-s", "--", "/usr/local/Caskroom/android-sdk/25.2.3/platform-tools/fastboot", "/usr/local/bin/fastboot"]
==> Linking Binary 'hprof-conv' to '/usr/local/bin/hprof-conv'.
==> Executing: ["/bin/ln", "-h", "-f", "-s", "--", "/usr/local/Caskroom/android-sdk/25.2.3/platform-tools/hprof-conv", "/usr/local/bin/hprof-conv"]
==> Reverting installation of artifact of class Hbc::Artifact::PreflightBlock
==> Purging files for version 25.2.3 of Cask android-sdk
Error: It seems there is already a Binary at '/usr/local/bin/sqlite3'; not linking./usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/symlinked.rb:30:in `link'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/binary.rb:11:in `link'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/relocated.rb:48:in `block in each_artifact'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/set.rb:232:in `each_key'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/set.rb:232:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/relocated.rb:46:in `each_artifact'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/symlinked.rb:15:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/binary.rb:7:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:144:in `block in install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:141:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:141:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/reinstall.rb:31:in `block in install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/reinstall.rb:6:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/reinstall.rb:6:in `install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:10:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:115:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:158:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:163:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:163:in `rescue in process'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:149:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
```

#### Output of `brew cask doctor`

```
brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.1.12
caskroom/homebrew-cask (git revision ce9e8; last commit 2017-04-03)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (1 files, 191.2MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3630 casks)
/usr/local/Homebrew/Library/Taps/cloudfoundry/homebrew-tap (0 casks)
/usr/local/Homebrew/Library/Taps/d12frosted/homebrew-emacs-plus (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-dupes (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services (0 casks)
/usr/local/Homebrew/Library/Taps/neovim/homebrew-neovim (0 casks)
/usr/local/Homebrew/Library/Taps/oarrabi/homebrew-tap (1 cask)
/usr/local/Homebrew/Library/Taps/pebble/homebrew-pebble-sdk (0 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Environment Variables
LANG="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
PATH="/usr/local/opt/sqlite/bin:~/.nvm/versions/node/v7.6.0/bin:~/.cargo/bin:~/.rvm/gems/ruby-2.3.1/bin:~/.rvm/gems/ruby-2.3.1@global/bin:~/.rvm/rubies/ruby-2.3.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:~/.rvm/bin:~/.rvm/bin:/usr/local/Cellar/node/7.6.0/bin:/usr/local/Cellar/node/7.6.0/bin:~/.rvm/bin:~/.nvm/versions/node/v7.6.0/bin:~/.fzf/bin:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/zsh"
```

https://github.com/caskroom/homebrew-cask/blob/master/Casks/android-sdk.rb#L32

**Comment by victorpopkov** [comment]
Have you installed `sqlite` using Homebrew before? If yes you can try unlinking it before installing android-sdk and then relinking it again:

```bash
brew unlink sqlite
brew cask install android-sdk
brew link --force --overwrite sqlite
```

Most likely there is a need to remove sqlite binary linking from `android-sdk.rb` or add a `conflicts_with formula: 'sqlite'`.
