### ISSUE TITLE
visual-paradigm doesn't download at install

### ISSUE THREAD

**Issue by korthout** [caskroom/homebrew-cask#31807]
#### Description of issue

Tried to install visual-paradigm, but it fails. `curl` says:  
> The requested URL returned error: 404 Not Found

#### Output of your command with `--verbose --debug`

```
brew cask install visual-paradigm --verbose --debug
==> Hbc::Installer#install
==> Printing caveats
==> Hbc::Installer#fetch
==> Downloading
==> Downloading https://eu6.visual-paradigm.com/visual-paradigm/vp14.0/20170302/Visual_Paradigm_14_0_20170302_OSX_WithJRE.dmg
==> Calling curl with args ["https://eu6.visual-paradigm.com/visual-paradigm/vp14.0/20170302/Visual_Paradigm_14_0_20170302_OSX_WithJRE.dmg", "-C", "0", "-o", "#<Pathname:/Users/nicokorthout/Library/Caches/Homebrew/Cask/visual-paradigm--14.0,20170302.dmg.incomplete>"]
/usr/bin/curl --remote-time --location --user-agent Homebrew/1.1.12 (Macintosh; Intel macOS 10.12.3) curl/7.51.0 --fail https://eu6.visual-paradigm.com/visual-paradigm/vp14.0/20170302/Visual_Paradigm_14_0_20170302_OSX_WithJRE.dmg -C 0 -o /Users/nicokorthout/Library/Caches/Homebrew/Cask/visual-paradigm--14.0,20170302.dmg.incomplete
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'visual-paradigm' with message: Download failed: https://eu6.visual-paradigm.com/visual-paradigm/vp14.0/20170302/Visual_Paradigm_14_0_20170302_OSX_WithJRE.dmg
The incomplete download is cached at /Users/nicokorthout/Library/Caches/Homebrew/Cask/visual-paradigm--14.0,20170302.dmg.incomplete
Error: nothing to install/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:13:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:115:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:158:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:163:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:163:in `rescue in process'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:149:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
```

#### Output of `brew cask doctor`

```
brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.1.12
caskroom/homebrew-cask (git revision f23e3; last commit 2017-04-03)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (1 files, 0B)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3630 casks)
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-dupes (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-versions (0 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Environment Variables
LC_CTYPE="UTF-8"
PATH="/Library/PostgreSQL/9.4/bin:/usr/local/mysql/bin:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/bin:/usr/local/opt/ruby/bin:~/.node/bin:~/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/TeX/texbin:/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/cmd:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/usr/local/bin/bash"
```

**Comment by vitorgalvao** [comment]
> [If you ignore this guide, your issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

Also note from that document:

> If the maintainer was wrong in closing your issue, please do reply stating why! Closing an issue does not mean the conversation is over. If the guides themselves were unclear, help us improve them! Open *first* an issue or pull request stating what you found confusing *and only then* your other issue.

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/pull/31810

**Comment by korthout** [comment]
Thank you for the effort. Much appreciated.
