### ISSUE TITLE
Bug report: dwarf-fortress installation fails

### ISSUE THREAD

**Issue by sandlst** [caskroom/homebrew-cask#31813]
#### General troubleshooting steps

- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

I had the old home-brew version of dwarf-fortress installed (not cask) and tried to 'upgrade' to cask version; I got no errors on upgrading but it would not run (complained about SDL errors).  So I completely removed it and tried to install fresh from cask instead (and got this error).  It seems to be trying to back up my saves even though I don't have any since the game isn't installed yet...

#### Output of your command with `--verbose --debug`

```
==> Hbc::Installer#install
==> Printing caveats
==> Caveats
During uninstall, your save data will be copied to /tmp/dwarf-fortress-save

==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Installing Cask dependencies: sdl-framework, sdl-ttf-framework
sdl-framework ...
already installed
sdl-ttf-framework ...
already installed
complete
==> Downloading
==> Downloading http://www.bay12games.com/dwarves/df_43_05_osx.tar.bz2
Already downloaded: /Users/sandlst/Library/Caches/Homebrew/Cask/dwarf-fortress--0.43.05.tar.bz2
==> Downloaded to -> /Users/sandlst/Library/Caches/Homebrew/Cask/dwarf-fortress--0.43.05.tar.bz2
==> Verifying download
==> Determining which verifications to run for Cask dwarf-fortress
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask dwarf-fortress
==> SHA256 checksums match
==> Hbc::Installer#stage
==> Extracting primary container
==> Determining which containers to use based on filetype
==> Checking container class Hbc::Container::Pkg
==> Checking container class Hbc::Container::Ttf
==> Checking container class Hbc::Container::Otf
==> Checking container class Hbc::Container::Air
==> Checking container class Hbc::Container::Cab
==> Checking container class Hbc::Container::Dmg
==> Executing: ["/usr/bin/hdiutil", "imageinfo", "/Users/sandlst/Library/Caches/Homebrew/Cask/dwarf-fortress--0.43.05.tar.bz2"]
==> Checking container class Hbc::Container::SevenZip
==> Checking container class Hbc::Container::Sit
==> Checking container class Hbc::Container::Rar
==> Checking container class Hbc::Container::Zip
==> Checking container class Hbc::Container::Xar
==> Checking container class Hbc::Container::Tar
==> Using container class Hbc::Container::Tar for /Users/sandlst/Library/Caches/Homebrew/Cask/dwarf-fortress--0.43.05.tar.bz2
==> Executing: ["/usr/bin/tar", "-x", "-f", "/Users/sandlst/Library/Caches/Homebrew/Cask/dwarf-fortress--0.43.05.tar.bz2", "-C", "/var/folders/9k/trvx5bm93xg9cb06227fbnxh0000gn/T/d20170403-9557-ol3u5w"]
==> Executing: ["/usr/bin/ditto", "--", "/var/folders/9k/trvx5bm93xg9cb06227fbnxh0000gn/T/d20170403-9557-ol3u5w", "/usr/local/Caskroom/dwarf-fortress/0.43.05"]
==> Creating metadata directory /usr/local/Caskroom/dwarf-fortress/.metadata/0.43.05/20170403153417.301
==> Creating metadata subdirectory /usr/local/Caskroom/dwarf-fortress/.metadata/0.43.05/20170403153417.301/Casks
==> Installing artifacts
==> Determining which artifacts are present in Cask dwarf-fortress
==> 3 artifact/s defined
#<Hbc::Artifact::PreflightBlock:0x007fb0a5289350>
#<Hbc::Artifact::Binary:0x007fb0a5289210>
#<Hbc::Artifact::PostflightBlock:0x007fb0a52890d0>
==> Installing artifact of class Hbc::Artifact::PreflightBlock
==> Installing artifact of class Hbc::Artifact::Binary
==> Linking Binary 'df.wrapper.sh' to '/usr/local/bin/dwarf-fortress'.
==> Executing: ["/bin/ln", "-h", "-f", "-s", "--", "/usr/local/Caskroom/dwarf-fortress/0.43.05/df_osx/df.wrapper.sh", "/usr/local/bin/dwarf-fortress"]
==> Adding com.apple.metadata:kMDItemAlternateNames metadata
==> Executing: ["/usr/bin/xattr", "-p", "com.apple.metadata:kMDItemAlternateNames", "/usr/local/Caskroom/dwarf-fortress/0.43.05/df_osx/df.wrapper.sh"]
==> Existing metadata is: ''
==> Executing: ["/bin/chmod", "--", "u+rw", "/usr/local/Caskroom/dwarf-fortress/0.43.05/df_osx/df.wrapper.sh", "/usr/local/Caskroom/dwarf-fortress/0.43.05/df_osx/df.wrapper.sh"]
==> Executing: ["/usr/bin/xattr", "-w", "com.apple.metadata:kMDItemAlternateNames", "(\\\"dwarf-fortress\\\")", "/usr/local/Caskroom/dwarf-fortress/0.43.05/df_osx/df.wrapper.sh"]
==> Installing artifact of class Hbc::Artifact::PostflightBlock
==> Reverting installation of artifact of class Hbc::Artifact::Binary
==> Unlinking Binary '/usr/local/bin/dwarf-fortress'.
==> Reverting installation of artifact of class Hbc::Artifact::PreflightBlock
==> Executing: ["/bin/cp", "-rf", "/usr/local/Caskroom/dwarf-fortress/0.43.05/df_osx/data/save", "/tmp/dwarf-fortress-save/"]
==> cp: directory /tmp/dwarf-fortress-save does not exist
==> Purging files for version 0.43.05 of Cask dwarf-fortress
Error: private method `load' called for Hbc:Module
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:39:in `block (4 levels) in load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:36:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:36:in `block (3 levels) in load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:32:in `chdir'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:32:in `block (2 levels) in load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_flight_block.rb:35:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_flight_block.rb:35:in `block in abstract_phase'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/set.rb:232:in `each_key'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/set.rb:232:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_flight_block.rb:34:in `abstract_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_flight_block.rb:24:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:144:in `block in install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:141:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:141:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:87:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:25:in `block in install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:19:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:19:in `install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:10:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:115:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:158:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:169:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:169:in `rescue in process'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:149:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
```

#### Output of `brew cask doctor`
```
==> Homebrew-Cask Version
Homebrew-Cask 1.1.12-2-g5ab904ed
caskroom/homebrew-cask (git revision 7ccc4; last commit 2017-04-03)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (2 files, 155.1MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3630 casks)
/usr/local/Homebrew/Library/Taps/cartr/homebrew-qt4 (0 casks)
/usr/local/Homebrew/Library/Taps/goldcaddy77/homebrew-firefox (16 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-command-not-found (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-dupes (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-fuse (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-games (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-versions (0 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Environment Variables
LANG="en_US.UTF-8"
PATH="~/Qt5.5.1/5.5/clang_64/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/share/dotnet:/Library/Frameworks/Mono.framework/Versions/Current/Commands:~/.bin:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/cmd:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-command-not-found/cmd:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/usr/local/bin/zsh"
```

**Comment by miccal** [comment]
Verified:
```
-bash-4.4.12- /Users/miccal [> brew cask install dwarf-fortress
==> Caveats
During uninstall, your save data will be copied to /tmp/dwarf-fortress-save

==> Satisfying dependencies
==> Installing Cask dependencies: sdl-framework, sdl-ttf-framework
sdl-framework ...
==> Downloading https://www.libsdl.org/release/SDL2-2.0.5.dmg
######################################################################## 100.0%
==> Verifying checksum for Cask sdl-framework
🍺  sdl-framework was successfully installed!
done
sdl-ttf-framework ...
==> Downloading https://www.libsdl.org/projects/SDL_ttf/release/SDL_ttf-2.0.11.dmg
######################################################################## 100.0%
==> Verifying checksum for Cask sdl-ttf-framework
🍺  sdl-ttf-framework was successfully installed!
done
complete
==> Downloading http://www.bay12games.com/dwarves/df_43_05_osx.tar.bz2
Already downloaded: /Users/miccal/Library/Caches/Homebrew/Cask/dwarf-fortress--0.43.05.tar.bz2
==> Verifying checksum for Cask dwarf-fortress
==> Linking Binary 'df.wrapper.sh' to '/usr/local/bin/dwarf-fortress'.
==> Unlinking Binary '/usr/local/bin/dwarf-fortress'.
==> cp: directory /tmp/dwarf-fortress-save does not exist
Error: private method `load' called for Hbc:Module
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:39:in `block (4 levels) in load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:36:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:36:in `block (3 levels) in load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:32:in `chdir'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:32:in `block (2 levels) in load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_flight_block.rb:35:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_flight_block.rb:35:in `block in abstract_phase'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/set.rb:232:in `each_key'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/set.rb:232:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_flight_block.rb:34:in `abstract_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_flight_block.rb:24:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:144:in `block in install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:141:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:141:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:87:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:25:in `block in install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:19:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:19:in `install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:10:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:115:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:158:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
```

**Comment by jottr** [comment]
Pinging @brewingcode.

**Comment by vitorgalvao** [comment]
Will be fixed in https://github.com/caskroom/homebrew-cask/pull/31856.

**Comment by brewingcode** [comment]
@vitorgalvao This bug is due to the `/tmp/dwarf-fortress-save` directory not existing when `cp` tries to copy to it. I saw caskroom/homebrew-cask#31862 to fix this, and I think a good addition to that PR would be and additional `mkdir -p` command:

```
 uninstall_preflight do
+    system_command '/bin/mkdir', args: ['-p', '/tmp/dwarf-fortress-save']
-    system_command '/bin/cp', args: ['-rf', "#{staged_path}/df_osx/data/save", '/tmp/dwarf-fortress-save/']
+    system_command '/bin/cp', args: ['-rf', "#{staged_path}/df_osx/data/save", '/tmp/dwarf-fortress-save/'] if File.exist?("#{staged_path}/df_osx/data/save")
```

**Comment by vitorgalvao** [comment]
> This bug is due to the `/tmp/dwarf-fortress-save` directory not existing when `cp` tries to copy to it.

That is incorrect. That copy only tries to happen at uninstall time, so it has no bearing on installation. What happens is that `Hbc.load` in the `postflight` is no longer valid (needs to be `Hbc::CaskLoader.load`) and as such fails. When it does, the casks tries to reverse the installation, which is why that copy is tried at all.

In addition, creating the directory on purpose just so it can be moved is a weird solution. It’s best to just check first if it exists and only try to copy it in that case.

As mentioned, I already have an open PR that fixes those issue.

**Comment by brewingcode** [comment]
Whoops, right you are.

Thanks for fixing it. :)

**Comment by vitorgalvao** [comment]
Forgot to mention that for anyone in a hurry, `brew cask install https://raw.githubusercontent.com/caskroom/homebrew-cask/297ca740ec0b42fcbf7e6deb8528875e88cd1780/Casks/dwarf-fortress.rb` will get you setup.
