### ISSUE TITLE
Cannot uninstall mactex

### ISSUE THREAD

**Issue by raxod502** [caskroom/homebrew-cask#31888]
#### General troubleshooting steps

- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Running `brew cask uninstall mactex` fails.

#### Output of your command with `--verbose --debug`

```
==> Uninstalling Cask mactex
==> Hbc::Installer#uninstall
==> Un-installing artifacts
==> Determining which artifacts are present in Cask mactex
==> 3 artifact/s defined
#<Hbc::Artifact::Uninstall:0x007f9212c20910>
#<Hbc::Artifact::Pkg:0x007f9212c20988>
#<Hbc::Artifact::Zap:0x007f9212c20898>
==> Un-installing artifact of class Hbc::Artifact::Uninstall
==> Running uninstall process for mactex; your password may be necessary
==> Uninstalling packages:
==> Executing: ["/usr/sbin/pkgutil", "--pkgs=org.tug.mactex.ghostscript9.19"]
==> Executing: ["/usr/sbin/pkgutil", "--pkgs=org.tug.mactex.gui2016"]
org.tug.mactex.gui2016
==> Executing: ["/usr/sbin/pkgutil", "--export-plist", "org.tug.mactex.gui2016"]
Error: incompatible encoding regexp match (UTF-8 regexp with ASCII-8BIT string)
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/vendor/plist/plist/parser.rb:91:in `scan'
/usr/local/Homebrew/Library/Homebrew/vendor/plist/plist/parser.rb:91:in `parse'
/usr/local/Homebrew/Library/Homebrew/vendor/plist/plist/parser.rb:29:in `parse_xml'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:160:in `_parse_plist'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:131:in `plist'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/pkg.rb:75:in `info'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/pkg.rb:66:in `pkgutil_bom_all'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/pkg.rb:54:in `pkgutil_bom_files'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/pkg.rb:17:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:191:in `block (2 levels) in uninstall_pkgutil'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:189:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:189:in `block in uninstall_pkgutil'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:188:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:188:in `uninstall_pkgutil'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:34:in `block (2 levels) in dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:32:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:32:in `block in dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:31:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:31:in `dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall.rb:7:in `uninstall_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:330:in `block in uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:327:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:327:in `uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:312:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:26:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:9:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:9:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:115:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:158:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:169:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:169:in `rescue in process'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:149:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
```

#### Output of `brew cask doctor`

```
% brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.1.12-8-gecd81198f
caskroom/homebrew-cask (git revision 4a0dd; last commit 2017-04-05)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (5 files, 3GB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3629 casks)
/usr/local/Homebrew/Library/Taps/derekkwok/homebrew-python (0 casks)
/usr/local/Homebrew/Library/Taps/discoteq/homebrew-discoteq (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-boneyard (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-dupes (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-emacs (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-php (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-science (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-versions (0 casks)
/usr/local/Homebrew/Library/Taps/neovim/homebrew-neovim (0 casks)
/usr/local/Homebrew/Library/Taps/raxod502/homebrew-radian (0 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin15
/Library/Ruby/Site/2.0.0/universal-darwin15
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15
==> Environment Variables
LANG="en_US.UTF-8"
PATH="~/.cargo/bin:/usr/local/opt/gpg-agent/bin:/usr/local/opt/gnupg@2.0/bin:/usr/local/Cellar/zplug/HEAD-c6dd31f/bin:/usr/local/opt/zplug/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/git/bin:/Developer/Panda3D/bin:/Library/TeX/texbin:~/.cargo/bin:/usr/local/opt/gpg-agent/bin:/usr/local/opt/gnupg@2.0/bin:/usr/local/sbin:/usr/local/sbin:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/cmd:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-emacs/cmd:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/usr/local/bin/zsh"
```

#### Output of `brew doctor`

```
% brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Some keg-only formula are linked into the Cellar.
Linking a keg-only formula, such as gettext, into the cellar with
`brew link <formula>` will cause other formulae to detect them during
the `./configure` step. This may cause problems when compiling those
other formulae.

Binaries provided by keg-only formulae may override system binaries
with other strange results.

You may wish to `brew unlink` these brews:
  openssl
```

**Comment by miccal** [comment]
If you run the command `pkgutil --pkgs`, can you confirm that you have the following in the list:
```
org.tug.mactex.ghostscript9.19
org.tug.mactex.gui2016
org.tug.mactex.texlive2016
```

**Comment by raxod502** [comment]
Not quite; I have `ghostscript9.16` rather than `ghostscript9.19`:

```
% pkgutil --pkgs | grep mactex
org.tug.mactex.basictex2016
org.tug.mactex.ghostscript9.10
org.tug.mactex.ghostscript9.16
org.tug.mactex.gui2014
org.tug.mactex.gui2015
org.tug.mactex.gui2016
org.tug.mactex.texlive2014
org.tug.mactex.texlive2015
org.tug.mactex.texlive2016
```

**Comment by miccal** [comment]
That is probably the problem - if you edit your local copy of `mactex.rb` in `/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask/Casks/mactex.rb` and change `ghostscript9.19` to `ghostscript9.16` in the `uninstall pkgutil:` stanza, does it uninstall correctly?

**Comment by raxod502** [comment]
Unfortunately, no. Here is my copy of the file, with `s/9.19/9.16/`:

```
% cat /usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask/Casks/mactex.rb
cask 'mactex' do
  version '20161009'
  sha256 'b44873d445881900401d0e0eddccc78140b9ed51b538364889eb8529350d5bd7'

  # mirror.ctan.org/systems/mac/mactex was verified as official when first introduced to the cask
  url "http://mirror.ctan.org/systems/mac/mactex/mactex-#{version}.pkg"
  appcast 'https://www.tug.org/mactex/downloading.html',
          checkpoint: 'dba7dc2fba9b2dd846cfba460f1121162c4f68d580dd2a485f7f929a1d7ec6be'
  name 'MacTeX'
  homepage 'https://www.tug.org/mactex/'

  pkg "mactex-#{version}.pkg"

  uninstall pkgutil: [
                       'org.tug.mactex.ghostscript9.16',
                       'org.tug.mactex.gui2016',
                       'org.tug.mactex.texlive2016',
                     ],
            delete:  [
                       '/usr/local/texlive/2016',
                       '/Applications/TeX',
                       '/Library/PreferencePanes/TeXDistPrefPane.prefPane',
                       '/etc/paths.d/TeX',
                       '/etc/manpaths.d/TeX',
                     ]

  zap delete: [
                '/usr/local/texlive/texmf-local',
                '~/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/texshop.sfl',
                '~/Library/Application Support/BibDesk',
                '~/Library/Application Support/TeXShop',
                '~/Library/Application Support/TeX Live Utility',
                '~/Library/Caches/com.apple.helpd/SDMHelpData/Other/English/HelpSDMIndexFile/TeXShop.help',
                '~/Library/Caches/com.apple.helpd/SDMHelpData/Other/English/HelpSDMIndexFile/edu.ucsd.cs.mmccrack.bibdesk.help',
                '~/Library/Caches/edu.ucsd.cs.mmccrack.bibdesk',
                '~/Library/Caches/fr.chachatelier.pierre.LaTeXiT',
                '~/Library/Caches/TeXShop',
                '~/Library/Preferences/edu.ucsd.cs.mmccrack.bibdesk.plist',
                '~/Library/Preferences/Excalibur Preferences',
                '~/Library/Preferences/fr.chachatelier.pierre.LaTeXiT.plist',
                '~/Library/Preferences/TeXShop.plist',
                '~/Library/Saved Application State/edu.bucknell.Excalibur.savedState',
                '~/Library/texlive/2016',
                '~/Library/TeXShop',
              ],
      rmdir:  [
                '/usr/local/texlive',
                '~/Library/texlive',
              ]
end
```

I still get:

```
% brew cask uninstall mactex
==> Running uninstall process for mactex; your password may be necessary
==> Uninstalling packages:
org.tug.mactex.gui2016
Error: incompatible encoding regexp match (UTF-8 regexp with ASCII-8BIT string)
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/vendor/plist/plist/parser.rb:91:in `scan'
/usr/local/Homebrew/Library/Homebrew/vendor/plist/plist/parser.rb:91:in `parse'
/usr/local/Homebrew/Library/Homebrew/vendor/plist/plist/parser.rb:29:in `parse_xml'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:160:in `_parse_plist'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:131:in `plist'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/pkg.rb:75:in `info'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/pkg.rb:66:in `pkgutil_bom_all'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/pkg.rb:54:in `pkgutil_bom_files'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/pkg.rb:17:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:191:in `block (2 levels) in uninstall_pkgutil'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:189:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:189:in `block in uninstall_pkgutil'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:188:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:188:in `uninstall_pkgutil'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:34:in `block (2 levels) in dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:32:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:32:in `block in dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:31:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:31:in `dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall.rb:7:in `uninstall_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:330:in `block in uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:327:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:327:in `uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:312:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:26:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:9:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:9:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:115:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:158:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
```

**Comment by colindunn** [comment]
I am getting this issue with a number of casks that I'm attempting to update. `lightkey` and `resolume-avenue` are two examples.

I've noticed this happening since upgrade to 10.12.4 but haven't managed to correlate this to anything. Just wanted to get a comment in here as well though so that it's known that it's not just this package.

**Comment by numbermaniac** [comment]
FYI @miccal I believe that the hidden `.metadata` folder may be the one used for uninstalling; for example, with `sublime-text`, there's a `/usr/local/Caskroom/sublime-text/.metadata/3126/20160930022608.851/Casks/sublime-text.rb` file present.

**Comment by miccal** [comment]
@numbermanic good point, I forgot about that. @raxod502 go to `/usr/local/Caskroom/mactex/.metadata` and edit the `mactex.rb` file as I suggested above.

**Comment by jasperzs** [comment]
My output of running the command "pkgutil --pkgs" is exactly the same as @miccal you mentioned above, but I also see this issue....  cannot uninstall mactex
org.tug.mactex.ghostscript9.19
org.tug.mactex.gui2016
org.tug.mactex.texlive2016

I realized the problem is with uninstalling "org.tug.mactex.gui2016" becauses as soon as I uninstalled this pkg using another tool uninstallPKG. The brew cask uninstall mactex reports no error and the uninstallation continues. However, it is indeed slow. Now 20 minutes has past, the uninstallation is still doing its thing.

**Comment by vitorgalvao** [comment]
I haven’t read the full thread, but a <kbd>⌘</kbd><kbd>F</kbd> didn’t show it. Did anybody try to uninstall with `--force`?

**Comment by jasperzs** [comment]
I did but same problem

**Comment by raxod502** [comment]
@miccal I modified the `.metadata/.../mactex.rb` file, and this time Cask attempted (and succeeded) to uninstall `org.tug.mactex.ghostscript9.16`, rather than silently skipping it as before.

However, the same error as before happens when it subsequently attempts to uninstall `org.tug.mactex.gui2016`. I think we can be pretty sure the problem is with the latter package, rather than the former, as other commenters have pointed out.

**Comment by miccal** [comment]
It seems that the problem lies in `org.tug.mactex.gui2016`, and is not something we can fix in Cask. Mactex will be updates soon to 2017, so in the meantime the only way to completely uninstall Mactex 2016 is manually.

**Comment by raxod502** [comment]
@miccal That's entirely reasonable, but I'm curious—what is the problem in `org.tug.mactex.gui2016`?

**Comment by miccal** [comment]
I have no idea, most likely something to do with an update to macOS that the Mactex developers will fix when Mactex 2017 is released.

**Comment by adidalal** [comment]
fyi mactex 2017 is planned to release on june 1

**Comment by vitorgalvao** [comment]
Is anyone not able to uninstall *and not on* Sierra `10.12.4`?

**Comment by jasperzs** [comment]
yes... I am on Mavericks 10.9.5

**Comment by vitorgalvao** [comment]
> yes... I am on Mavericks 10.9.5

Thank you. Just checking since at least two tools I use regularly broke severely with `10.12.4` for different reasons (they have since been fixed). This might’ve been another “victim”.

**Comment by raxod502** [comment]
I'm on El Capitan 10.11.6.
