### ISSUE TITLE
Java cask has strange deprecation warning about using `MacOS.release`

### ISSUE THREAD

**Issue by apetresc** [caskroom/homebrew-cask#31968]
#### General troubleshooting steps

- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

When reinstalling the `java` cask, I get a strange error complaining about a deprecated use of `MacOS.release` as opposed to `MacOS.version`:

```
$ brew cask reinstall java
==> Caveats
This Cask makes minor modifications to the JRE to prevent issues with
packaged applications, as discussed here:

  https://bugs.eclipse.org/bugs/show_bug.cgi?id=411361

If your Java application still asks for JRE installation, you might need
to reboot or logout/login.

Installing this Cask means you have AGREED to the Oracle Binary Code
License Agreement for Java SE at

  https://www.oracle.com/technetwork/java/javase/terms/license/index.html

==> Downloading http://download.oracle.com/otn-pub/java/jdk/8u121-b13/e9e7ea248e2c4826b92b3f075a80e441/jdk-8u121-macosx-x64.dmg
Already downloaded: /Users/apetresc/Library/Caches/Homebrew/Cask/java--1.8.0_121-b13,e9e7ea248e2c4826b92b3f075a80e441.dmg
==> Verifying checksum for Cask java
Error: Calling MacOS.release is deprecated!
Use MacOS.version instead.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:63:in `block in load'

Follow the instructions here:
  https://github.com/caskroom/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/utils.rb:96:in `odeprecated'
/usr/local/Homebrew/Library/Homebrew/compat/macos.rb:142:in `release'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:63:in `block in load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask.rb:15:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask.rb:15:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:51:in `new'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:51:in `cask'
/usr/local/Homebrew/Library/Homebrew/compat/hbc/cask_loader.rb:10:in `cask'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:9:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:9:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:9:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:41:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:116:in `load_from_file'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/reinstall.rb:23:in `block in install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/reinstall.rb:6:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/reinstall.rb:6:in `install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:10:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:115:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:158:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>
```
(Because I'm in developer mode, this deprecation becomes an error. I know I could turn that off, but I think this might be a legitimate problem).

What's super-strange about this is that nothing in that stack trace that I can find actually *does* use `MacOS.release`. The recipe itself certainly doesn't. It has two instances of `MacOS.version` but 0 of `MacOS.release` so I'm not sure where this error message is coming from.

#### Output of your command with `--verbose --debug`

```
==> Printing caveats
==> Caveats
This Cask makes minor modifications to the JRE to prevent issues with
packaged applications, as discussed here:

  https://bugs.eclipse.org/bugs/show_bug.cgi?id=411361

If your Java application still asks for JRE installation, you might need
to reboot or logout/login.

Installing this Cask means you have AGREED to the Oracle Binary Code
License Agreement for Java SE at

  https://www.oracle.com/technetwork/java/javase/terms/license/index.html

==> Hbc::Installer#fetch
==> Downloading
==> Downloading http://download.oracle.com/otn-pub/java/jdk/8u121-b13/e9e7ea248e2c4826b92b3f075a80e441/jdk-8u121-macosx-x64.dmg
Already downloaded: /Users/apetresc/Library/Caches/Homebrew/Cask/java--1.8.0_121-b13,e9e7ea248e2c4826b92b3f075a80e441.dmg
==> Downloaded to -> /Users/apetresc/Library/Caches/Homebrew/Cask/java--1.8.0_121-b13,e9e7ea248e2c4826b92b3f075a80e441.dmg
==> Verifying download
==> Determining which verifications to run for Cask java
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask java
==> SHA256 checksums match
Error: Calling MacOS.release is deprecated!
Use MacOS.version instead.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:63:in `block in load'

Follow the instructions here:
  https://github.com/caskroom/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/utils.rb:96:in `odeprecated'
/usr/local/Homebrew/Library/Homebrew/compat/macos.rb:142:in `release'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:63:in `block in load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask.rb:15:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask.rb:15:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:51:in `new'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:51:in `cask'
/usr/local/Homebrew/Library/Homebrew/compat/hbc/cask_loader.rb:10:in `cask'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:9:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:9:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:9:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:41:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:116:in `load_from_file'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/reinstall.rb:23:in `block in install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/reinstall.rb:6:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/reinstall.rb:6:in `install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:10:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:115:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:158:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:169:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:169:in `rescue in process'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:149:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew-Cask Version
Homebrew-Cask 1.1.12-24-gd84655efb
caskroom/homebrew-cask (git revision ea1ce; last commit 2017-04-06)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (7 files, 489MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3629 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-fonts (1103 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (178 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-boneyard (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-dupes (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-games (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-python (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-science (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-versions (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-x11 (0 casks)
/usr/local/Homebrew/Library/Taps/vitorgalvao/homebrew-tiny-scripts (0 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Environment Variables
LANG="en_CA.UTF-8"
LC_CTYPE="en_CA.UTF-8"
PATH="~/perl5/bin:~/.nvm/versions/node/v6.2.2/bin:/usr/local/lib/dnx/runtimes/dnx-coreclr-darwin-x64.1.0.0-rc1-update1/bin:~/.dnx/bin:~/.rbenv/shims:~/.rbenv/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/texlive/2013/bin/x86_64-darwin:/opt/storm/bin:~/bin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/zsh"
```

**Comment by miccal** [comment]
Ping @reitermarkus.

**Comment by apetresc** [comment]
Thanks @vitorgalvao, editing the `.metadata` file did indeed do it.

It seems strange to me that Homebrew would enforce deprecation warnings on cached `.metadata` files which may have been sitting around since long before the deprecation occurred, and there is no real way (other than directly editing their source) to "fix" besides upgrading them, which the deprecation error prevents...

**Comment by vitorgalvao** [comment]
> Thanks @vitorgalvao, editing the `.metadata` file did indeed do it.

So `--force` wasn’t enough?

> It seems strange to me that Homebrew would enforce deprecation warnings on cached `.metadata` files which may have been sitting around since long before the deprecation occurred

We don’t really treat `.metadata` as special (just another cask). I don’t think we thought about this case. It’s rare enough that it doesn’t warrant fixing, though, since it’ll go away on its own with time.

> and there is no real way (other than directly editing their source) to "fix" besides upgrading them, which the deprecation error prevents...

Well, to be fair, you answered it before:

> Because I'm in developer mode, this deprecation becomes an error.

You’re not exactly supposed to stay developer mode. When you are, you are expected to know what you are doing and how to fix the problems. That’s the tradeoff: you can do more, but might also need to do your own fixing.

**Comment by jordigg** [comment]
Could this be related to the issue I'm just having that `brew cask install java` hangs because it can't download the file via wget? Seems the link on the formula requires to accept the licence somehow to enable the file to be downloaded download.

**Comment by apetresc** [comment]
> So --force wasn’t enough?

Oh, maybe it would've been. I just didn't want to use `--force` since it might skip over other warnings/errors that might've showed up after this one.

> You’re not exactly supposed to stay developer mode. When you are, you are expected to know what you are doing and how to fix the problems. That’s the tradeoff: you can do more, but might also need to do your own fixing.

Okay, fair enough :)

**Comment by apetresc** [comment]
@jordigg: Nope, definitely not related.

**Comment by jordigg** [comment]
It did work after a while maybe an intermittent issue on the java servers, sorry about that!
