### ISSUE TITLE
Cannot uninstall mactex (incompatible encoding regexp match)

### ISSUE THREAD

**Issue by linkyndy** [caskroom/homebrew-cask#32073]
#### General troubleshooting steps

- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

I have installed `mactex` and now I cannot uninstall it.

#### Output of your command with `--verbose --debug`

```
==> Uninstalling Cask mactex
==> Hbc::Installer#uninstall
==> Un-installing artifacts
==> Determining which artifacts are present in Cask mactex
==> 3 artifact/s defined
#<Hbc::Artifact::Uninstall:0x007fbdb4a99268>
#<Hbc::Artifact::Pkg:0x007fbdb4a99448>
#<Hbc::Artifact::Zap:0x007fbdb4a991f0>
==> Un-installing artifact of class Hbc::Artifact::Uninstall
==> Running uninstall process for mactex; your password may be necessary
==> Uninstalling packages:
==> Executing: ["/usr/sbin/pkgutil", "--pkgs=org.tug.mactex.ghostscript9.19"]
==> Executing: ["/usr/sbin/pkgutil", "--pkgs=org.tug.mactex.gui2016"]
org.tug.mactex.gui2016
==> Executing: ["/usr/sbin/pkgutil", "--export-plist", "org.tug.mactex.gui2016"]
Error: incompatible encoding regexp match (UTF-8 regexp with ASCII-8BIT string)
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/vendor/plist/plist/parser.rb:91:in `scan'
/usr/local/Homebrew/Library/Homebrew/vendor/plist/plist/parser.rb:91:in `parse'
/usr/local/Homebrew/Library/Homebrew/vendor/plist/plist/parser.rb:29:in `parse_xml'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:160:in `_parse_plist'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:131:in `plist'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/pkg.rb:75:in `info'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/pkg.rb:66:in `pkgutil_bom_all'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/pkg.rb:54:in `pkgutil_bom_files'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/pkg.rb:17:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:191:in `block (2 levels) in uninstall_pkgutil'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:189:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:189:in `block in uninstall_pkgutil'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:188:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:188:in `uninstall_pkgutil'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:34:in `block (2 levels) in dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:32:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:32:in `block in dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:31:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:31:in `dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall.rb:7:in `uninstall_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:330:in `block in uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:327:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:327:in `uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:312:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:26:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:9:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:9:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:115:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:158:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:169:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:169:in `rescue in process'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:149:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew-Cask Version
Homebrew-Cask 1.1.12-24-gd84655efb9
caskroom/homebrew-cask (git revision 39d5; last commit 2017-04-07)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (1 files, 2.7GB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3626 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-science (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-versions (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-x11 (0 casks)
/usr/local/Homebrew/Library/Taps/thoughtbot/homebrew-formulae (0 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Environment Variables
LC_CTYPE="UTF-8"
PATH="/usr/local/Cellar/pyenv-virtualenv/1.0.0/shims:~/.pyenv/shims:~/.rbenv/shims:~/.rbenv/bin:~/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/git/bin:/Library/TeX/texbin:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/cmd:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/zsh"
```

**Comment by miccal** [comment]
If you run the command `pkgutil --pkgs | grep mactex`, can you confirm that you have the following in the list:
```
org.tug.mactex.ghostscript9.19
org.tug.mactex.gui2016
org.tug.mactex.texlive2016
```

**Comment by linkyndy** [comment]
This is the output:

```
$ pkgutil --pkgs | grep mactex
org.tug.mactex.gui2016
org.tug.mactex.texlive2016
```

**Comment by jasperzs** [comment]
I have this issue right now as well. Really need some help here!!!

**Comment by miccal** [comment]
It seems that the problem lies in `org.tug.mactex.gui2016`, and is not something we can fix in Cask. Mactex will be updates soon to 2017, so in the meantime the only way to completely uninstall Mactex 2016 is manually.

**Comment by linkyndy** [comment]
Thank you for your input. Are there any steps provided in order to properly uninstall it?

**Comment by jasperzs** [comment]
well, I used a third party tool together with homebrew cask uninstall command. The steps are as this: 1. use "UninstallPKG" app to uninstall "org.tug.mactex.gui2016" package 2. run "brew cask uninstall mactex" and this time the uninstallation will continue.
[Note]: UninstallPKG is not free, but a trial version allows you to uninstall 3 packages, thus in our case it is sufficient.

**Comment by linkyndy** [comment]
Worked great, thank you!
