### ISSUE TITLE
Cannot uninstall etcher... but it's not installed...

### ISSUE THREAD

**Issue by domoritz** [caskroom/homebrew-cask#32381]
#### Description of issue

![screen shot 2017-04-14 at 18 51 42](https://cloud.githubusercontent.com/assets/589034/25059866/6fd09258-2143-11e7-8b36-3dce0832442f.png)

#### Output of your command with `--verbose --debug`

```
$ brew cask remove etcher --verbose --debug                                                                                                                                                           2396ms
==> Uninstalling Cask etcher
Error: etcher is not installed/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:13:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:9:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:9:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:115:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:158:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:163:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:163:in `rescue in process'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:149:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew-Cask Version
Homebrew-Cask 1.1.12
caskroom/homebrew-cask (git revision bf560; last commit 2017-04-15)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (1 files, 0B)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3634 casks)
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade (0 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (177 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-completions (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-fuse (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-python (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-science (0 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Environment Variables
LANG="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
PATH="~/bin:~/Developer/git/nanocube/build/bin:~/.cargo/bin:~/Developer/go/bin:~/.yarn/bin:/opt/X11/bin:/Library/TeX/texbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/cmd:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/usr/local/bin/fish"
```

**Comment by miccal** [comment]
It seems the download links are down, so I suggest we wait a few days and see if they start working.

**Comment by domoritz** [comment]
I actually want to uninstall etcher. Notice how `brew cask list` shows etcher but then `brew uninstall etcher` does not work.

**Comment by vitorgalvao** [comment]
@domoritz Do `brew cask unintall --force etcher`.

If that doesn’t work, seeing as it only installs an `app` bundle, delete it manually (likely from `/Applications`) and delete the `$(brew --prefix)/Caskroom/etcher` (likely `/usr/local/Caskroom/etcher`) directory.

**Comment by domoritz** [comment]
That works. Thank you @vitorgalvao. I wonder if brew cask could show a hint when you try to uninstall an app that is not installed ("Looks like you are uninstalling an app that is not installed. Try --force if you think that is a mistake.").

**Comment by vitorgalvao** [comment]
@domoritz This is a rare occurrence and `brew cask list` is broken itself, so it’s not worth it to put effort into it. It’ll likely be solved when other things are fixed as well.
