### ISSUE TITLE
cask install adobe-photoshop-cc with an error of undefined

### ISSUE THREAD

**Issue by stefor22** [caskroom/homebrew-cask#32439]
#### General troubleshooting steps

- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
- [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

I've install or cask install other files before, and it works find. 
But got an error when i cask install photoshop. 

#### Output of brew cask install adobe-photoshop-cc with `--verbose --debug`

```
Error: undefined method `call' for nil:NilClass
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/dsl.rb:136:in `language_eval'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask.rb:16:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:51:in `new'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:51:in `cask'
/usr/local/Homebrew/Library/Homebrew/compat/hbc/cask_loader.rb:10:in `cask'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:9:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:9:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:9:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:41:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:128:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:21:in `block in install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:19:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:19:in `install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:10:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:115:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:158:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:169:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:169:in `rescue in process'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:149:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew-Cask Version
Homebrew-Cask 1.1.12-40-g02f01893
caskroom/homebrew-cask (git revision 06de0; last commit 2017-04-16)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (2 files, 5.5MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3633 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-apache (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-dupes (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-php (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-versions (0 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Environment Variables
LANG="zh_CN.UTF-8"
LC_CTYPE="zh_CN.UTF-8"
PATH="/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/zsh"
```

**Comment by numbermaniac** [comment]
link to cask: https://github.com/caskroom/homebrew-cask/blob/master/Casks/adobe-photoshop-cc.rb

**Comment by miccal** [comment]
Cannot reproduce:
```
-bash-4.4.12- /Users/miccal [> brew cask install adobe-photoshop-cc
==> Downloading http://trials3.adobe.com/AdobeProducts/PHSP/16/osx10/Photoshop_16_LS20.dmg
######################################################################## 100.0%
==> Verifying checksum for Cask adobe-photoshop-cc
Password:
==> Starting Installer... In Silent mode.
==> Installation successful.
==> Exiting Installer with Code: 0
🍺  adobe-photoshop-cc was successfully installed!
```

**Comment by stefor22** [comment]
@numbermaniac ,thanks for the reply, i have try the link you give https://github.com/caskroom/homebrew-cask/blob/master/Casks/adobe-photoshop-cc.rb 
and it reports another error
```
> $ brew cask install https://github.com/caskroom/homebrew-cask/blob/master/Casks/adobe-photoshop-cc.rb
==> Downloading https://github.com/caskroom/homebrew-cask/blob/master/Casks/adob
######################################################################## 100.0%
Error: /usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:15: syntax error, unexpected '<'
<!DOCTYPE html>
 ^
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:16: syntax error, unexpected '<'
<html lang="en">
 ^
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:17: syntax error, unexpected '<'
  <head>
   ^
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:22: syntax error, unexpected '<'
  <link crossorigin="anonymous" ...
   ^
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:22: syntax error, unexpected tIDENTIFIER, expecting end-of-input
...nk crossorigin="anonymous" href="https://assets-cdn.github.c...
...                               ^
```

**Comment by numbermaniac** [comment]
@stefor22 Saving the page I linked would've downloaded the whole page, not just the code, so Ruby is trying to parse the HTML of the rest of the page. That link was more for any maintainer that wanted to look at it; if you've done `brew update`, the Ruby code on that page is the same file that is read when you did `brew cask install adobe-photoshop-cc`.

If you _really_ want to try the online version, you can do `brew cask install https://raw.githubusercontent.com/caskroom/homebrew-cask/master/Casks/adobe-photoshop-cc.rb`, but I don't think that will help.

**Comment by wouterds** [comment]
Where did `adobe-photoshop-cc` go?
