### ISSUE TITLE
Cannot uninstall adobe-air

### ISSUE THREAD

**Issue by loranger** [caskroom/homebrew-cask#32513]
#### General troubleshooting steps

- [X] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
- [X] None of the templates was appropriate for my issue, or I’m not sure.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Uninstalling adobe-air exits with an error

#### Output of your command with `--verbose --debug`

<details>
  <summary>$ brew cask remove adobe-air --verbose --debug</summary>

```shell
==> Uninstalling Cask adobe-air
==> Hbc::Installer#uninstall
==> Un-installing artifacts
==> Determining which artifacts are present in Cask adobe-air
==> 3 artifact/s defined
#<Hbc::Artifact::Uninstall:0x007feacc09fa10>
#<Hbc::Artifact::Installer:0x007feacc09fc68>
#<Hbc::Artifact::Zap:0x007feacc09f8a8>
==> Un-installing artifact of class Hbc::Artifact::Uninstall
==> Running uninstall process for adobe-air; your password may be necessary
==> Running uninstall script Adobe AIR Installer.app/Contents/MacOS/Adobe AIR Installer
==> Executing: ["/bin/chmod", "--", "+x", "/usr/local/Caskroom/adobe-air/23.0/Adobe AIR Installer.app/Contents/MacOS/Adobe AIR Installer"]
==> Executing: ["/usr/local/Caskroom/adobe-air/23.0/Adobe AIR Installer.app/Contents/MacOS/Adobe AIR Installer", "-uninstall"]
==> Uninstalling Adobe AIR (all versions)
==> failed (consult log)
Error: Command failed to execute!

==> Failed command:
#<Pathname:/usr/local/Caskroom/adobe-air/23.0/Adobe AIR Installer.app/Contents/MacOS/Adobe AIR Installer> -uninstall

==> Standard Output of failed command:
Uninstalling Adobe AIR (all versions)
failed (consult log)


==> Standard Error of failed command:


==> Exit status of failed command:
#<Process::Status: pid 93676 exit 7>
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:65:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:36:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:182:in `uninstall_script'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:34:in `block (2 levels) in dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:32:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:32:in `block in dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:31:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:31:in `dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall.rb:7:in `uninstall_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:330:in `block in uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:327:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:327:in `uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:312:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:26:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:9:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:9:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:115:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:158:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:163:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:163:in `rescue in process'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:149:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
```

</details>

#### Output of `brew cask doctor`
<details>
  <summary>$ brew cask doctor</summary>

```shell
==> Homebrew-Cask Version
Homebrew-Cask 1.1.13-19-g55c02ae774
caskroom/homebrew-cask (git revision c24a6; last commit 2017-04-18)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (2 files, 47.2MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3632 casks)
/usr/local/Homebrew/Library/Taps/argon/homebrew-mas (0 casks)
/usr/local/Homebrew/Library/Taps/blackfireio/homebrew-blackfire (0 casks)
/usr/local/Homebrew/Library/Taps/dart-lang/homebrew-dart (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-binary (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-dupes (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-php (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-python (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-science (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-x11 (0 casks)
/usr/local/Homebrew/Library/Taps/ravenac95/homebrew-sudolikeaboss (0 casks)
/usr/local/Homebrew/Library/Taps/thoughtbot/homebrew-formulae (0 casks)
/usr/local/Homebrew/Library/Taps/tobli/homebrew-browsertime (0 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Gems/2.0.0/gems/json-2.0.3/lib
/Library/Ruby/Gems/2.0.0/extensions/universal-darwin-16/2.0.0/json-2.0.3
/Library/Ruby/Gems/2.0.0/gems/psych-2.2.4/lib
/Library/Ruby/Gems/2.0.0/extensions/universal-darwin-16/2.0.0/psych-2.2.4
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Environment Variables
LANG="fr_FR.UTF-8"
PATH="/usr/local/bin:/usr/local/sbin:/usr/local/share/npm/bin:/usr/local/opt/go/libexec/bin:~/.composer/vendor/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/MacGPG2/bin:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/cmd:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/zsh"
```

</details>

<details>
  <summary>$ brew doctor</summary>

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Some keg-only formula are linked into the Cellar.
Linking a keg-only formula, such as gettext, into the cellar with
`brew link <formula>` will cause other formulae to detect them during
the `./configure` step. This may cause problems when compiling those
other formulae.

Binaries provided by keg-only formulae may override system binaries
with other strange results.

You may wish to `brew unlink` these brews:
  curl
```

</details>

**Comment by MTCoster** [comment]
Can you provide the log file referenced on lines 15 and 23 of the output of `brew cask remove adobe-air --verbose --debug`?

**Comment by miccal** [comment]
Confirmed:
```
-bash-4.4.12- /Users/miccal [> brew cask zap adobe-air
==> Implied "brew cask uninstall adobe-air"
==> Running uninstall process for adobe-air; your password may be necessary
==> Running uninstall script Adobe AIR Installer.app/Contents/MacOS/Adobe AIR Installer
==> Uninstalling Adobe AIR (all versions)
==> failed (consult log)
Error: Command failed to execute!
==> Failed command:
#<Pathname:/usr/local/Caskroom/adobe-air/25.0/Adobe AIR Installer.app/Contents/MacOS/Adobe AIR Installer> -uninstall
==> Standard Output of failed command:
Uninstalling Adobe AIR (all versions)
failed (consult log)
==> Standard Error of failed command:
==> Exit status of failed command:
#<Process::Status: pid 19760 exit 7>
```

**Comment by loranger** [comment]
@MTCoster I'd like to provide those logs, but I don't even know which log file it is and where they are located 😕

**Comment by commitay** [comment]
@loranger Please try this:
```
https://raw.githubusercontent.com/commitay/homebrew-cask/620cba080c0c005253c354a3ef0ef8d00407ee05/Casks/adobe-air.rb
```

I've added sudo to the uninstall.

**Comment by loranger** [comment]
It seems the error has moved a little :

```shell
$ brew cask uninstall https://raw.githubusercontent.com/commitay/homebrew-cask/620cba080c0c005253c354a3ef0ef8d00407ee05/Casks/adobe-air.rb
==> Downloading https://raw.githubusercontent.com/commitay/homebrew-cask/620cba080c0c005253c354a3ef0ef8d0
######################################################################## 100,0%
==> Running uninstall process for adobe-air; your password may be necessary
==> Running uninstall script Adobe AIR Installer.app/Contents/MacOS/Adobe AIR Installer
Error: uninstall script Adobe AIR Installer.app/Contents/MacOS/Adobe AIR Installer does not exist.
```

**Comment by commitay** [comment]
Please try `brew cask install adobe-air --force` and then the `brew cask uninstall` I posted.

**Comment by loranger** [comment]
... And it worked !

```shell
$ brew cask uninstall --force https://raw.githubusercontent.com/commitay/homebrew-cask/620cba080c0c005253c354a3ef0ef8d00407ee05/Casks/adobe-air.rb
==> Downloading https://raw.githubusercontent.com/commitay/homebrew-cask/620cba080c0c005253c354a3ef0ef8d0
######################################################################## 100,0%
==> Running uninstall process for adobe-air; your password may be necessary
==> Running uninstall script Adobe AIR Installer.app/Contents/MacOS/Adobe AIR Installer
==> Uninstalling Adobe AIR (all versions)
==> done
==> Removing directories if empty:
/Applications/Adobe/Flash Player/AddIns
/Applications/Adobe/Flash Player
/Applications/Adobe
```

No more Adobe Air for me, thank you so much @commitay !

**Comment by commitay** [comment]
No problem @loranger , happy to help.
