### ISSUE TITLE
virtualbox-extension-pack 5.1.20-114628 will not install

### ISSUE THREAD

**Issue by colindunn** [caskroom/homebrew-cask#32560]
#### General troubleshooting steps

- [X] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [X] None of the templates was appropriate for my issue, or I’m not sure.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

It appears that the latest version of VBoxManage required a response to the license question even in non-interactive mode and so it fails to install because the license hasn't been accepted. 

Appears to be an issue after the latest update #32528. Would fix it, but can't seem to find an accept option. Might need to be an expect script or something? Any ideas?

#### Output of your command with `--verbose --debug`

```
$ brew cask install virtualbox-extension-pack --verbose --debug
==> Hbc::Installer#install
==> Printing caveats
==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Installing Cask dependencies: virtualbox
virtualbox ...
already installed
complete
==> Downloading
==> Downloading http://download.virtualbox.org/virtualbox/5.1.20/Oracle_VM_VirtualBox_Extension_Pack-5.1.20-114628.vbox-extpack
Already downloaded: /Users/dunnc/Library/Caches/Homebrew/Cask/virtualbox-extension-pack--5.1.20-114628.vbox-extpack
==> Downloaded to -> /Users/dunnc/Library/Caches/Homebrew/Cask/virtualbox-extension-pack--5.1.20-114628.vbox-extpack
==> Verifying download
==> Determining which verifications to run for Cask virtualbox-extension-pack
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask virtualbox-extension-pack
==> SHA256 checksums match
==> Hbc::Installer#stage
==> Extracting primary container
==> Determining which containers to use based on 'container :type'
==> Using container class Hbc::Container::Naked for /Users/dunnc/Library/Caches/Homebrew/Cask/virtualbox-extension-pack--5.1.20-114628.vbox-extpack
==> Executing: ["/usr/bin/ditto", "--", "/Users/dunnc/Library/Caches/Homebrew/Cask/virtualbox-extension-pack--5.1.20-114628.vbox-extpack", "/usr/local/Caskroom/virtualbox-extension-pack/5.1.20-114628/Oracle_VM_VirtualBox_Extension_Pack-5.1.20-114628.vbox-extpack"]
==> Creating metadata directory /usr/local/Caskroom/virtualbox-extension-pack/.metadata/5.1.20-114628/20170419044053.974
==> Creating metadata subdirectory /usr/local/Caskroom/virtualbox-extension-pack/.metadata/5.1.20-114628/20170419044053.974/Casks
==> Installing artifacts
==> Determining which artifacts are present in Cask virtualbox-extension-pack
==> 2 artifact/s defined
#<Hbc::Artifact::StageOnly:0x007f9378131218>
#<Hbc::Artifact::PostflightBlock:0x007f9378130fe8>
==> Installing artifact of class Hbc::Artifact::PostflightBlock
==> Executing: ["/usr/bin/sudo", "-E", "--", "/usr/local/bin/VBoxManage", "extpack", "install", "--replace", "/usr/local/Caskroom/virtualbox-extension-pack/5.1.20-114628/Oracle_VM_VirtualBox_Extension_Pack-5.1.20-114628.vbox-extpack"]
==> Purging files for version 5.1.20-114628 of Cask virtualbox-extension-pack
Error: Command failed to execute!

==> Failed command:
/usr/bin/sudo -E -- /usr/local/bin/VBoxManage extpack install --replace /usr/local/Caskroom/virtualbox-extension-pack/5.1.20-114628/Oracle_VM_VirtualBox_Extension_Pack-5.1.20-114628.vbox-extpack

==> Standard Output of failed command:
VirtualBox Personal Use and Evaluation License (PUEL)

License version 9, 17 November 2016

ORACLE AMERICA, INC. ("ORACLE") IS WILLING TO LICENSE THE PRODUCT DEFINED
IN SECTION 1 BELOW ONLY ON THE CONDITION THAT YOU ACCEPT ALL OF THE TERMS
CONTAINED IN THIS VIRTUALBOX PERSONAL USE AND EVALUATION LICENSE AGREEMENT
("AGREEMENT").

IF YOU ARE AGREEING TO THIS LICENSE ON BEHALF OF AN ENTITY (RATHER THAN
AS AN INDIVIDUAL HUMAN BEING), YOU REPRESENT THAT YOU HAVE THE APPROPRIATE
AUTHORITY TO ACCEPT THESE TERMS AND CONDITIONS ON BEHALF OF SUCH ENTITY.

1 SUBJECT OF AGREEMENT. This Agreement governs your use of the binary
software package called "Oracle VM VirtualBox Extension Pack" (the
"Product"), which contains a set of Enterprise Features for "Oracle VM
VirtualBox" that allows multiple virtual computers ("Guest Computers")
to exist on a single physical computer ("Host Computer"). The Product
consists of executable files in machine code, data files, and all
documentation and updates provided to You by Oracle.

2 GRANT OF LICENSE. Oracle grants you a personal, non-exclusive,
non-transferable, limited license without fees to reproduce, install,
execute, and use internally the Product on Host Computers for your
Personal Use, Educational Use, or Evaluation. "Personal Use" is use
solely by the person downloading the Product from Oracle on a single
Host Computer, provided that no more than one client or remote computer
is connected to that Host Computer and that client or remote computer
is used solely to remotely view the Guest Computers. "Educational Use"
is any use by teachers or students in an academic institution (schools,
colleges and universities) as part of the institutions educational
curriculum. "Evaluation" means testing the Product for up to thirty
(30) days; after expiry of that term, you are no longer permitted to
use the Product.

All rights not expressly licensed by Oracle are hereby reserved.

3 RESTRICTIONS AND RESERVATION OF RIGHTS. (1) The Product and copies
thereof provided to you under this Agreement are copyrighted and licensed,
not sold, to you by Oracle.

(2) You may not do any of the following: (a) modify any part of the
Product, except to the extent allowed in the documentation accompanying
the Product; (b) rent, lease, lend or encumber the Product; (c) remove
or alter any proprietary legends or notices contained in the Product;
or (d) decompile, or reverse engineer the Product (except to the extent
permitted by applicable law).

(3) The Product is not designed, licensed or intended for use in the
design, construction, operation or maintenance of any nuclear facility
and Oracle and its licensors disclaim any express or implied warranty
of fitness for such uses.

(4) No right, title or interest in or to any trademark, service mark, logo
or trade name of Oracle or its licensors is granted under this Agreement.

4 TERMINATION. The Agreement is effective on the date you receive the
Product and remains effective until terminated. Your rights under this
Agreement will terminate immediately without notice from Oracle if
you materially breach it or take any action in derogation of Oracle's
and/or its licensors' rights to Product. Oracle may terminate this
Agreement should any part of the Product become or in Oracle's reasonable
opinion likely to become the subject of a claim of intellectual property
infringement or trade secret misappropriation. Upon termination, you will
cease use of and destroy all copies of the Product under your control
and confirm compliance in writing to Oracle. Sections 3-9, inclusive,
will survive termination of the Agreement.

5 DISCLAIMER OF WARRANTY. TO THE EXTENT NOT PROHIBITED BY APPLICABLE
LAW, ORACLE PROVIDES THE PRODUCT "AS IS" WITHOUT WARRANTY OF ANY KIND,
EITHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR
NON-INFRINGEMENT, EXCEPT TO THE EXTENT THAT THESE DISCLAIMERS ARE HELD TO
BE LEGALLY INVALID. The entire risk as to the quality and performance of
the Product is with you. Should it prove defective, you assume the cost
of all necessary servicing, repair, or correction. In addition, Oracle
shall be allowed to provide updates to the Product in urgent cases. You
are then obliged to install such updates. Such an urgent case includes,
but is not limited to, a claim of rights to the Product by a third party.

6 LIMITATION OF LIABILITY. TO THE EXTENT NOT PROHIBITED BY APPLICABLE LAW,
IN NO EVENT WILL ORACLE OR ITS LICENSORS BE LIABLE FOR ANY LOST REVENUE,
PROFIT OR DATA, OR FOR SPECIAL, INDIRECT, CONSEQUENTIAL, INCIDENTAL OR
PUNITIVE DAMAGES, HOWEVER CAUSED REGARDLESS OF THE THEORY OF LIABILITY,
ARISING OUT OF OR RELATED TO THE USE OF OR INABILITY TO USE PRODUCT,
EVEN IF ORACLE HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. In
no event will Oracle's liability to you, whether in contract, tort
(including negligence), or otherwise, exceed the amount paid by you for
Product under this Agreement. Some states do not allow the exclusion of
incidental or consequential damages, so some of the terms above may not
be applicable to you.

7 THIRD PARTY CODE. Portions of Product may be provided with notices and
open source licenses from communities and third parties that govern the
use of those portions, and any licenses granted hereunder do not alter
any rights and obligations You may have under such open source licenses,
however, the disclaimer of warranty and limitation of liability provisions
in this Agreement will apply to all of the Product.

8 EXPORT REGULATIONS. All Product, documents, technical data, and any
other materials delivered under this Agreement are subject to U.S. export
control laws and may be subject to export or import regulations in other
countries. You agree to comply strictly with these laws and regulations
and acknowledge that you have the responsibility to obtain any licenses
to export, re-export, or import as may be required after delivery to you.

9 U.S. GOVERNMENT END USERS. If the Product or related documentation is
delivered to the U.S. Government or anyone licensing it on behalf of the
U.S. Government, then the following notice applies: Oracle programs,
including any operating system, integrated software, any programs
installed on hardware, and/or documentation, delivered to U.S. Government
end users are "commercial computer software" pursuant to the applicable
Federal Acquisition Regulation and agency-specific supplemental
regulations. As such, use, duplication, disclosure, modification, and
adaptation of the programs, including any operating system, integrated
software, any programs installed on the hardware, and/or documentation,
shall be subject to license terms and license restrictions applicable
to the programs. No other rights are granted to the U.S. Government.

10 MISCELLANEOUS. This Agreement is the entire agreement between you
and Oracle relating to its subject matter. It supersedes all prior or
contemporaneous oral or written communications, proposals, representations
and warranties and prevails over any conflicting or additional terms
of any quote, order, acknowledgment, or other communication between
the parties relating to its subject matter during the term of this
Agreement. No modification of this Agreement will be binding, unless in
writing and signed by an authorized representative of each party. If any
provision of this Agreement is held to be unenforceable, this Agreement
will remain in effect with the provision omitted, unless omission would
frustrate the intent of the parties, in which case this Agreement will
immediately terminate. Course of dealing and other standard business
conditions of the parties or the industry shall not apply. This Agreement
is governed by the substantive and procedural laws of the State of
California, USA, and you and Oracle agree to submit to the exclusive
jurisdiction of, and venue in, the courts of San Francisco or Santa
Clara counties in California in any dispute arising out of or relating
to this Agreement.

Do you agree to these license terms and conditions (y/n)?
Installation of "Oracle VM VirtualBox Extension Pack" aborted.


==> Standard Error of failed command:


==> Exit status of failed command:
#<Process::Status: pid 45582 exit 1>
Error: nothing to install/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:13:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:115:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:158:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:163:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:163:in `rescue in process'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:149:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
```

#### Output of `brew cask doctor`

```
$ brew doctor
Your system is ready to brew.
```

**Comment by commitay** [comment]
Tried installing manually and found this at the end of the license agreement:
```
Do you agree to these license terms and conditions (y/n)? y

License accepted. For batch installaltion add
--accept-license=715c7246dc0f779ceab39446812362b2f9bf64a55ed5d3a905f053cfab36da9e
to the VBoxManage command line.
```
Added to the cask it works, but I don't know if this will work for everyone. 
```
  postflight do
    system_command '/usr/local/bin/VBoxManage',
                   args: [
                           'extpack', 'install',
                           '--replace', "#{staged_path}/Oracle_VM_VirtualBox_Extension_Pack-#{version}.vbox-extpack",
                           '--accept-license=715c7246dc0f779ceab39446812362b2f9bf64a55ed5d3a905f053cfab36da9e'
                         ],
                   sudo: true
  end
```

@colindunn Could you please try installing manually with `sudo VBoxManage extpack install --replace /path/to/extpack.vbox-extpack` and see if you get a different license code?

I'll reload a VM and do a fresh install of virtualbox to see if I can reuse the same code.

**Comment by colindunn** [comment]
Same code @commitay 

```
--accept-license=715c7246dc0f779ceab39446812362b2f9bf64a55ed5d3a905f053cfab36da9e
```

Well.... won't that be painful to update!

**Comment by colindunn** [comment]
Checked the previous version and it errors out with that option added. Personally I'd say add that embedded and then we'll find out if it's static between versions or not with the next release?

**Comment by commitay** [comment]
Thanks for checking that @colindunn.

> Well.... won't that be painful to update!

I hadn't even thought of that yet, new code with every version!

**Comment by victorpopkov** [comment]
> Maintainers: Is it okay to drop lion and mountain lion versions from virtualbox and virtualbox-extension-pack?

Yes. Unless nobody is against it. I, personally, think that those should be removed.

**Comment by vitorgalvao** [comment]
We officially support only the current stable macOS version and one behind, so everything before El Capitan can go away.

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/pull/32599#pullrequestreview-33607472

**Comment by commitay** [comment]
Sorry for commenting on a closed issue.

> We officially support only the current stable macOS version and one behind, so everything before El Capitan can go away.

@vitorgalvao Should I start removing old `versions` from casks?

**Comment by vitorgalvao** [comment]
> @vitorgalvao Should I start removing old `versions` from casks?

No need. Saying we only officially support those versions means we’ll spend our time fixing those. So if older versions break, we might just remove them, but if they work there’s no harm in leaving them.

The exception is anything lower than Snow Leopard. That can definitely be removed. But we already remove most if not all of those.
