### ISSUE TITLE
kextunload issue in digital-power-station

### ISSUE THREAD

**Issue by colindunn** [caskroom/homebrew-cask#32723]
#### General troubleshooting steps

- [X] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [X] None of the templates was appropriate for my issue, or I’m not sure.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Looks like kextunload might not be waiting for the kext to exit before trying to remove it but not sure. The first execution of the uninstall for `digital-power-station` fails with `kext is in use or retained` as an error. Running the uninstall again works fine so that's why I concluded that it's not waiting for an exit. Happy to troubleshoot here, just let me know how to proceed. 

#### Output of your command with `--verbose --debug`

```
$ brew cask uninstall digital-power-station --verbose --debug
==> Uninstalling Cask digital-power-station
==> Hbc::Installer#uninstall
==> Un-installing artifacts
==> Determining which artifacts are present in Cask digital-power-station
==> 2 artifact/s defined
#<Hbc::Artifact::Uninstall:0x007fe8149d3380>
#<Hbc::Artifact::Pkg:0x007fe8149d33f8>
==> Un-installing artifact of class Hbc::Artifact::Uninstall
==> Running uninstall process for digital-power-station; your password may be necessary
==> Unloading kernel extension com.bongiovi.DPSReflector
==> Executing: ["/usr/bin/sudo", "-E", "--", "/usr/sbin/kextstat", "-l", "-b", "com.bongiovi.DPSReflector"]
==> Executing: ["/usr/bin/sudo", "-E", "--", "/sbin/kextunload", "-b", "com.bongiovi.DPSReflector"]
==> (kernel) Can't unload kext com.bongiovi.DPSReflector; classes have instances:
==> (kernel)     Kext com.bongiovi.DPSReflector class com_bongiovi_DPSReflectorDevice has 1 instance.
==> (kernel)     Kext com.bongiovi.DPSReflector class DPSReflectorEngine has 1 instance.
==> Failed to unload com.bongiovi.DPSReflector - (libkern/kext) kext is in use or retained (cannot unload).
Error: Command failed to execute!

==> Failed command:
/usr/bin/sudo -E -- /sbin/kextunload -b com.bongiovi.DPSReflector

==> Standard Output of failed command:


==> Standard Error of failed command:
(kernel) Can't unload kext com.bongiovi.DPSReflector; classes have instances:
(kernel)     Kext com.bongiovi.DPSReflector class com_bongiovi_DPSReflectorDevice has 1 instance.
(kernel)     Kext com.bongiovi.DPSReflector class DPSReflectorEngine has 1 instance.
Failed to unload com.bongiovi.DPSReflector - (libkern/kext) kext is in use or retained (cannot unload).


==> Exit status of failed command:
#<Process::Status: pid 13543 exit 3>
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:65:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:36:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:18:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:152:in `block in uninstall_kext'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:148:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:148:in `uninstall_kext'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:34:in `block (2 levels) in dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:32:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:32:in `block in dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:31:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall_base.rb:31:in `dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall.rb:7:in `uninstall_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:330:in `block in uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:327:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:327:in `uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:312:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:26:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:9:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:9:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:115:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:158:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:163:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:163:in `rescue in process'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:149:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
```

#### Output of `brew cask doctor`

```
$ brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.1.13
caskroom/homebrew-cask (git revision 07376; last commit 2017-04-21)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (47 files, 3.6GB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3638 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core (0 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

**Comment by commitay** [comment]
@colindunn I'm afraid I cannot reproduce this from a clean install in a VM.

```
brew cask uninstall digital-power-station --verbose --debug
==> Uninstalling Cask digital-power-station
==> Hbc::Installer#uninstall
==> Un-installing artifacts
==> Determining which artifacts are present in Cask digital-power-station
==> 2 artifact/s defined
#<Hbc::Artifact::Uninstall:0x007f8e27335d58>
#<Hbc::Artifact::Pkg:0x007f8e27335dd0>
==> Un-installing artifact of class Hbc::Artifact::Uninstall
==> Running uninstall process for digital-power-station; your password may be necessary
==> Unloading kernel extension com.bongiovi.DPSReflector
==> Executing: ["/usr/bin/sudo", "-E", "--", "/usr/sbin/kextstat", "-l", "-b", "com.bongiovi.DPSReflector"]
Password:
==> Executing: ["/usr/bin/sudo", "-E", "--", "/sbin/kextunload", "-b", "com.bongiovi.DPSReflector"]
==> Executing: ["/usr/bin/sudo", "-E", "--", "/usr/sbin/kextfind", "-b", "com.bongiovi.DPSReflector"]
==> Removing kernel extension /Library/Extensions/DPSReflector.kext
==> Executing: ["/usr/bin/sudo", "-E", "--", "/bin/rm", "-rf", "/Library/Extensions/DPSReflector.kext"]
==> Uninstalling packages:
==> Executing: ["/usr/sbin/pkgutil", "--pkgs=com.bongiovi.pkg.BongioviDPS.*"]
com.bongiovi.pkg.BongioviDPS.Applications.pkg
==> Executing: ["/usr/sbin/pkgutil", "--export-plist", "com.bongiovi.pkg.BongioviDPS.Applications.pkg"]
==> Deleting pkg files
```

I updated the uninstall yesterday in https://github.com/caskroom/homebrew-cask/pull/32617. I was just testing to see if the `.app` bundle was removed. Taking another look at this it seems to need an `uninstall quit: 'com.bongiovi.DPS20'` if the app is running but I can't get the `kext` to error with or without the `uninstall quit`.

**Comment by colindunn** [comment]
Thanks @commitray.
This is in a clean VM, vagrant via VirtualBox. What are you using out of interest?

**Comment by commitay** [comment]
> What are you using out of interest?

Fusion Pro 8.5.6

> This is in a clean VM

Is there any particular settings you have enabled in the app or MacOS that I can try to see if I can reproduce this?

**Comment by colindunn** [comment]
Not that I can see.

Trying the install directly on my machine to test.

**Comment by colindunn** [comment]
Works fine on my actual machine rather than VM, so definitely a VM issue.

Found this problem while doing an updated, so will continue the update after #32727 gets merged.
