### ISSUE TITLE
Reinstalling OpenZFS with imported zpools fails

### ISSUE THREAD

**Issue by simt2** [caskroom/homebrew-cask#32769]
#### Description of issue
Trying to reinstall OpenZFS with a new versions removes the current version and then fails installing the new one when a zpool is still imported. Now it's impossible to export the zpool because no zfs utils are not installed anymore. 

#### Output of your command with `--verbose --debug`

Actual command that led to the removal
```
 brew cask reinstall openzfs                                                                          12:51:53
==> Satisfying dependencies
complete
==> Downloading https://openzfsonosx.org/w/images/f/f8/OpenZFS_on_OS_X_1.6.1.dmg
######################################################################## 100.0%
==> Verifying checksum for Cask openzfs
==> Running uninstall process for openzfs; your password may be necessary
==> Uninstalling packages:
net.lundman.openzfs.1011.pkg
Password:
==> rm: /etc: Operation not permitted
==> Running installer for openzfs; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
==> Mounted ZFS file system(s) check
==> installer: Error - You must export all imported pools before proceeding.
Error: Command failed to execute!

==> Failed command:
/usr/bin/sudo -E -- /usr/sbin/installer -pkg #<Pathname:/usr/local/Caskroom/openzfs/1.6.1,f8/OpenZFS on OS X 1.6.1 El Capitan.pkg> -target /

==> Standard Output of failed command:
Mounted ZFS file system(s) check


==> Standard Error of failed command:
installer: Error - You must export all imported pools before proceeding.


==> Exit status of failed command:
#<Process::Status: pid 36946 exit 1>
```

Now failing installation: 
```
 brew cask install openzfs --verbose --debug                                                          13:07:39
==> Hbc::Installer#install
==> Printing caveats
==> Hbc::Installer#fetch
==> Satisfying dependencies
complete
==> Downloading
==> Downloading https://openzfsonosx.org/w/images/f/f8/OpenZFS_on_OS_X_1.6.1.dmg
Already downloaded: /Users/simt/Library/Caches/Homebrew/Cask/openzfs--1.6.1,f8.dmg
==> Downloaded to -> /Users/simt/Library/Caches/Homebrew/Cask/openzfs--1.6.1,f8.dmg
==> Verifying download
==> Determining which verifications to run for Cask openzfs
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask openzfs
==> SHA256 checksums match
==> Hbc::Installer#stage
==> Extracting primary container
==> Determining which containers to use based on filetype
==> Checking container class Hbc::Container::Pkg
==> Checking container class Hbc::Container::Ttf
==> Checking container class Hbc::Container::Otf
==> Checking container class Hbc::Container::Air
==> Checking container class Hbc::Container::Cab
==> Checking container class Hbc::Container::Dmg
==> Executing: ["/usr/bin/hdiutil", "imageinfo", "/Users/simt/Library/Caches/Homebrew/Cask/openzfs--1.6.1,f8.dmg"]
==> Using container class Hbc::Container::Dmg for /Users/simt/Library/Caches/Homebrew/Cask/openzfs--1.6.1,f8.dmg
==> Executing: ["/usr/bin/hdiutil", "mount", "-plist", "-nobrowse", "-readonly", "-noidme", "-mountrandom", "/tmp", "/Users/simt/Library/Caches/Homebrew/Cask/openzfs--1.6.1,f8.dmg"]
==> Executing: ["/usr/bin/mkbom", "-s", "-i", "/var/folders/rx/g83lv0x57955xjhb_dn_3c640000gn/T/20170421-41507-1vtty9t.list", "--", "/var/folders/rx/g83lv0x57955xjhb_dn_3c640000gn/T/20170421-41507-zf87bm.bom"]
==> Executing: ["/usr/bin/ditto", "--bom", "/var/folders/rx/g83lv0x57955xjhb_dn_3c640000gn/T/20170421-41507-zf87bm.bom", "--", "/private/tmp/dmg.KGKaU6", "/usr/local/Caskroom/openzfs/1.6.1,f8"]
==> Executing: ["/usr/sbin/diskutil", "eject", "/private/tmp/dmg.KGKaU6"]
==> Creating metadata directory /usr/local/Caskroom/openzfs/.metadata/1.6.1,f8/20170421110749.125
==> Creating metadata subdirectory /usr/local/Caskroom/openzfs/.metadata/1.6.1,f8/20170421110749.125/Casks
==> Installing artifacts
==> Determining which artifacts are present in Cask openzfs
==> 2 artifact/s defined
#<Hbc::Artifact::Pkg:0x007f8f03a52320>
#<Hbc::Artifact::Uninstall:0x007f8f03a52230>
==> Installing artifact of class Hbc::Artifact::Pkg
==> Running installer for openzfs; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
==> Executing: ["/usr/bin/sudo", "-E", "--", "/usr/sbin/installer", "-pkg", "/usr/local/Caskroom/openzfs/1.6.1,f8/OpenZFS on OS X 1.6.1 El Capitan.pkg", "-target", "/", "-verboseR"]
==> Mounted ZFS file system(s) check
==> installer: Error - You must export all imported pools before proceeding.
==> Purging files for version 1.6.1,f8 of Cask openzfs
Error: Command failed to execute!

==> Failed command:
/usr/bin/sudo -E -- /usr/sbin/installer -pkg #<Pathname:/usr/local/Caskroom/openzfs/1.6.1,f8/OpenZFS on OS X 1.6.1 El Capitan.pkg> -target / -verboseR

==> Standard Output of failed command:
Mounted ZFS file system(s) check


==> Standard Error of failed command:
installer: Error - You must export all imported pools before proceeding.


==> Exit status of failed command:
#<Process::Status: pid 41654 exit 1>
Error: nothing to install/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:13:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:115:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:158:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:163:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:163:in `rescue in process'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:149:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew-Cask Version
Homebrew-Cask 1.1.13-36-g2be799987
caskroom/homebrew-cask (git revision 10bc3; last commit 2017-04-21)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (1 files, 31.0MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3637 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-fonts (1105 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (160 casks)
/usr/local/Homebrew/Library/Taps/esphen/homebrew-wsta (0 casks)
/usr/local/Homebrew/Library/Taps/fisherman/homebrew-tap (0 casks)
/usr/local/Homebrew/Library/Taps/go-delve/homebrew-delve (0 casks)
/usr/local/Homebrew/Library/Taps/go-swagger/homebrew-go-swagger (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-binary (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-boneyard (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-dupes (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-php (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-versions (0 casks)
/usr/local/Homebrew/Library/Taps/kaos/homebrew-shell (0 casks)
/usr/local/Homebrew/Library/Taps/koekeishiya/homebrew-formulae (0 casks)
/usr/local/Homebrew/Library/Taps/neovim/homebrew-neovim (0 casks)
/usr/local/Homebrew/Library/Taps/redspread/homebrew-spread (0 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin15
/Library/Ruby/Site/2.0.0/universal-darwin15
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15
==> Environment Variables
LANG="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
PATH="~/perl5/bin:/opt/homebrew-cask/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:~/bin:~/.captain/bin:~/src/go/bin:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/usr/local/bin/fish"
```

**Comment by reitermarkus** [comment]
Does it also fail when running the installer manually?

**Comment by simt2** [comment]
Yes it does. But the installer would not uninstall it beforehand.
