### ISSUE TITLE
Problem installing karabiner

### ISSUE THREAD

**Issue by mec07** [caskroom/homebrew-cask#32765]
#### General troubleshooting steps

- [x ] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x ] None of the templates was appropriate for my issue, or I’m not sure.
- [ x] I ran `brew update-reset && brew update` and retried my command.
- [x ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [ x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue
I tried to install karabiner using brew but it failed. The command was
```
brew install Caskroom/cask/karabiner
```
The result was ```Error: Operation not permitted - /Applications/Karabiner.app/Contents/Library/bin/karabiner```

#### Output of your command with `--verbose --debug`

```
==> brew cask install Caskroom/cask/karabiner --debug --verbose
brew cask install Caskroom/cask/karabiner --debug --verbose
==> Hbc::Installer#install
==> Printing caveats
==> Hbc::Installer#fetch
==> Downloading
==> Downloading https://pqrs.org/osx/karabiner/files/Karabiner-10.22.0.dmg
Already downloaded: /Users/mcoury/Library/Caches/Homebrew/Cask/karabiner--10.22.0.dmg
==> Downloaded to -> /Users/mcoury/Library/Caches/Homebrew/Cask/karabiner--10.22.0.dmg
==> Verifying download
==> Determining which verifications to run for Cask karabiner
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask karabiner
==> SHA256 checksums match
==> Hbc::Installer#stage
==> Extracting primary container
==> Determining which containers to use based on filetype
==> Checking container class Hbc::Container::Pkg
==> Checking container class Hbc::Container::Ttf
==> Checking container class Hbc::Container::Otf
==> Checking container class Hbc::Container::Air
==> Checking container class Hbc::Container::Cab
==> Checking container class Hbc::Container::Dmg
==> Executing: ["/usr/bin/hdiutil", "imageinfo", "/Users/mcoury/Library/Caches/Homebrew/Cask/karabiner--10.22.0.dmg"]
==> Using container class Hbc::Container::Dmg for /Users/mcoury/Library/Caches/Homebrew/Cask/karabiner--10.22.0.dmg
==> Executing: ["/usr/bin/hdiutil", "mount", "-plist", "-nobrowse", "-readonly", "-noidme", "-mountrandom", "/tmp", "/Users/mcoury/Library/Caches/Homebrew/Cask/karabiner--10.22.0.dmg"]
==> Executing: ["/usr/bin/mkbom", "-s", "-i", "/var/folders/39/t4scc0hj27bbf00j7lrtsc800000gn/T/20170421-63860-119t9b9.list", "--", "/var/folders/39/t4scc0hj27bbf00j7lrtsc800000gn/T/20170421-63860-ttnlcn.bom"]
==> Executing: ["/usr/bin/ditto", "--bom", "/var/folders/39/t4scc0hj27bbf00j7lrtsc800000gn/T/20170421-63860-ttnlcn.bom", "--", "/private/tmp/dmg.hEHkkz", "/usr/local/Caskroom/karabiner/10.22.0"]
==> Executing: ["/usr/sbin/diskutil", "eject", "/private/tmp/dmg.hEHkkz"]
==> Creating metadata directory /usr/local/Caskroom/karabiner/.metadata/10.22.0/20170421062443.758
==> Creating metadata subdirectory /usr/local/Caskroom/karabiner/.metadata/10.22.0/20170421062443.758/Casks
==> Installing artifacts
==> Determining which artifacts are present in Cask karabiner
==> 4 artifact/s defined
#<Hbc::Artifact::Pkg:0x007feaf2847f80>
#<Hbc::Artifact::Binary:0x007feaf2847f30>
#<Hbc::Artifact::Uninstall:0x007feaf2847eb8>
#<Hbc::Artifact::Zap:0x007feaf2847e40>
==> Installing artifact of class Hbc::Artifact::Pkg
==> Running installer for karabiner; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
==> Executing: ["/usr/bin/sudo", "-E", "--", "/usr/sbin/installer", "-pkg", "/usr/local/Caskroom/karabiner/10.22.0/Karabiner.sparkle_guided.pkg", "-target", "/", "-verboseR"]
==> installer: Package name is Karabiner 10.22.0
==> installer: Upgrading at base path /
==> installer:PHASE:Preparing for installation…
==> installer:PHASE:Preparing the disk…
==> installer:PHASE:Preparing Karabiner 10.22.0…
==> installer:PHASE:Waiting for other installations to complete…
==> installer:PHASE:Configuring the installation…
==> installer:STATUS:
==> installer:%35.062531
==> installer:PHASE:Running package scripts…
==> installer:%37.010585
==> installer:PHASE:Running package scripts…
==> installer:%38.601496
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:%81.810676
==> installer:PHASE:Running package scripts…
==> installer:%83.768596
==> installer:PHASE:Running package scripts…
==> installer:%85.381549
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Validating packages…
==> installer:%97.262500
==> installer:PHASE:Registering updated applications…
==> installer:%97.750000
==> installer:STATUS:Running installer actions…
==> installer:STATUS:
==> installer:PHASE:Finishing the Installation…
==> installer:STATUS:
==> installer:%100.000000
==> installer:PHASE:The software was successfully installed.
==> installer: The upgrade was successful.
==> Installing artifact of class Hbc::Artifact::Binary
==> Linking Binary 'karabiner' to '/usr/local/bin/karabiner'.
==> Executing: ["/bin/ln", "-h", "-f", "-s", "--", "/Applications/Karabiner.app/Contents/Library/bin/karabiner", "/usr/local/bin/karabiner"]
==> Purging files for version 10.22.0 of Cask karabiner
Error: Operation not permitted - /Applications/Karabiner.app/Contents/Library/bin/karabiner
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask#reporting-bugs
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1333:in `chmod'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1333:in `chmod'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:975:in `block in chmod'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:974:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:974:in `chmod'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/binary.rb:12:in `link'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/relocated.rb:48:in `block in each_artifact'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/set.rb:232:in `each_key'
System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/set.rb:232:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/relocated.rb:46:in `each_artifact'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/symlinked.rb:15:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/binary.rb:7:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:144:in `block in install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:141:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:141:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:87:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:25:in `block in install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:19:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:19:in `install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:10:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:115:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:158:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:169:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:169:in `rescue in process'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:149:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew-Cask Version
Homebrew-Cask 1.1.13-36-g2be79998
caskroom/homebrew-cask (git revision 3f1de3; last commit 2017-04-21)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (1 files, 4.2MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3637 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (160 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-versions (0 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Environment Variables
LANG="en_GB.UTF-8"
PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:~/bin:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

**Comment by commitay** [comment]
Please try:
```
brew cask install karabiner --no-binaries
```
https://github.com/caskroom/homebrew-cask/issues/31874

**Comment by mec07** [comment]
That worked!  :)
