### ISSUE TITLE
Problem installing a cask, got error regarding stashed changes.

### ISSUE THREAD

**Issue by AAlakkad** [caskroom/homebrew-cask#32874]
#### General troubleshooting steps

- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
- [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Every time I try to install cask `phpstorm-eap` using the command `brew cask install phpstorm-eap`  I get an error (listed below).
```

I opened the file to see if there are such characters, the file was very clear, it looks like:
```ruby
module Hbc
  module CaskLoader
    class FromContentLoader
      def initialize(content)
        @content = content
      end

      def load
        instance_eval(@content.force_encoding("UTF-8"), __FILE__, __LINE__)
      end

      private

      def cask(header_token, &block)
        Cask.new(header_token, &block)
      end
    end

    class FromPathLoader < FromContentLoader
      def self.can_load?(ref)
        path = Pathname.new(ref)
        path.extname == ".rb" && path.expand_path.exist?
      end

      attr_reader :token, :path

      def initialize(path)
        path = Pathname.new(path).expand_path

        @token = path.basename(".rb").to_s
        @path = path
      end

      def load
        raise CaskError, "'#{@path}' does not exist."  unless @path.exist?
        raise CaskError, "'#{@path}' is not readable." unless @path.readable?
        raise CaskError, "'#{@path}' is not a file."   unless @path.file?

        @content = IO.read(@path)

        super
      end

      private

      def cask(header_token, &block)
        if @token != header_token
          raise CaskTokenDoesNotMatchError.new(@token, header_token)
        end

        Cask.new(header_token, sourcefile_path: @path, &block)
      end
    end

    class FromURILoader < FromPathLoader
      def self.can_load?(ref)
        !(ref.to_s !~ ::URI.regexp)
      end

      def initialize(url)
        @url = url
        uri = URI(url)
        super Hbc.cache/File.basename(uri.path)
      end

      def load
        Hbc.cache.mkpath
        FileUtils.rm_f @path

        begin
          ohai "Downloading #{@url}."
          curl @url, "-o", @path
        rescue ErrorDuringExecution
          raise CaskUnavailableError, @url
        end

        super
      end
    end

    class FromTapLoader < FromPathLoader
      def self.can_load?(ref)
        !(ref.to_s !~ HOMEBREW_TAP_CASK_REGEX)
      end

      def initialize(tapped_name)
        user, repo, token = tapped_name.split("/", 3).map(&:downcase)
        @tap = Tap.fetch(user, repo)

        super @tap.cask_dir/"#{token}.rb"
      end

      def load
        @tap.install unless @tap.installed?

        super
      end
    end

    class NullLoader < FromPathLoader
      def self.can_load?(*)
        true
      end

      def initialize(ref)
        @token = File.basename(ref, ".rb")
        super CaskLoader.default_path(@token)
      end

      def load
        raise CaskUnavailableError, @token
      end
    end

    def self.load_from_file(path)
      FromPathLoader.new(path).load
    end

    def self.load_from_string(content)
      FromContentLoader.new(content).load
    end

    def self.path(ref)
      self.for(ref).path
    end

    def self.load(ref)
      self.for(ref).load
    end

    def self.for(ref)
      [
        FromURILoader,
        FromTapLoader,
        FromPathLoader,
      ].each do |loader_class|
        return loader_class.new(ref) if loader_class.can_load?(ref)
      end

      if FromPathLoader.can_load?(default_path(ref))
        return FromPathLoader.new(default_path(ref))
      end

      possible_tap_casks = tap_paths(ref)
      if possible_tap_casks.count == 1
        possible_tap_cask = possible_tap_casks.first
        return FromPathLoader.new(possible_tap_cask)
      end

      possible_installed_cask = Cask.new(ref)
      if possible_installed_cask.installed?
        return FromPathLoader.new(possible_installed_cask.installed_caskfile)
      end

      NullLoader.new(ref)
    end

    def self.default_path(token)
      Hbc.default_tap.cask_dir/"#{token.to_s.downcase}.rb"
    end

    def self.tap_paths(token)
      Tap.map { |t| t.cask_dir/"#{token.to_s.downcase}.rb" }
         .select(&:exist?)
    end
  end
end
```

#### Output of your command with `--verbose --debug`

```
Error: /usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:10: syntax error, unexpected <<
<<<<<<< Updated upstream
  ^
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:13: syntax error, unexpected ===, expecting keyword_end
=======
   ^
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:17: syntax error, unexpected ===, expecting keyword_end
=======
   ^
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:21: syntax error, unexpected ===, expecting keyword_end
=======
   ^
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:24: syntax error, unexpected >>, expecting keyword_end
>>>>>>> Stashed changes
  ^
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:25: syntax error, unexpected >>, expecting keyword_end
>>>>>>> Stashed changes
  ^
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:26: syntax error, unexpected >>, expecting keyword_end
>>>>>>> Stashed changes
  ^
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:9:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:9:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:41:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:128:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:21:in `block in install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:19:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:19:in `install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:10:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:115:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:158:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:169:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:169:in `rescue in process'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:149:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew-Cask Version
Homebrew-Cask 1.1.13-88-gcb17a8057
caskroom/homebrew-cask (git revision 48fba; last commit 2017-04-23)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (44 files, 3.2GB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3636 casks)
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade (0 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (161 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-dupes (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-fuse (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-php (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-versions (0 casks)
/usr/local/Homebrew/Library/Taps/koekeishiya/homebrew-formulae (0 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Environment Variables
LANG="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
PATH="/usr/local/Cellar/node/7.1.0/bin/:/usr/local/sbin:~/.yarn/bin:/usr/local/heroku/bin:/usr/local/sbin:/usr/local/opt/coreutils/libexec/gnubin:~/.composer/vendor/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:~/.composer/vendor/bin:/usr/local/Cellar/node/7.9.0/bin:/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/cmd:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/zsh"
```

**Comment by AAlakkad** [comment]
I've `cd` into the folder, it was on master and I run `git checkout -- .` to make sure nothing stashed or out of sync, nothing changed.

**Comment by vitorgalvao** [comment]
`phpstorm-eap` is no longer a cask. It has been removed. Does this happen with any other casks?

**Comment by AAlakkad** [comment]
No, this happens only with `phpstorm-eap`, when I saw the error I thought there was something else.

Sadly I'm not good with Ruby, I'd have submitted a pull request to show a user-friendly error message, so people don't get confused.

Thanks!
