### ISSUE TITLE
Microsoft Office install fails

### ISSUE THREAD

**Issue by yurikoles** [caskroom/homebrew-cask#33030]
#### General troubleshooting steps

- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue
Microsoft Office install fails
#### Output of your command with `--verbose --debug`

```
$ LC_ALL=C cask install microsoft-office --verbose --debug
==> Hbc::Installer#install
==> Printing caveats
==> Hbc::Installer#fetch
==> Downloading
==> Downloading https://officecdn.microsoft.com/pr/C1297A47-86C4-4C1F-97FA-950631F94777/OfficeMac/Microsoft_Office_2016_15.33.17040900_Installer.pkg
Already downloaded: /Users/yurikoles/Library/Caches/Homebrew/Cask/microsoft-office--15.33.17040900.pkg
==> Downloaded to -> /Users/yurikoles/Library/Caches/Homebrew/Cask/microsoft-office--15.33.17040900.pkg
==> Verifying download
==> Determining which verifications to run for Cask microsoft-office
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask microsoft-office
==> SHA256 checksums match
==> Installing Cask microsoft-office
==> Hbc::Installer#stage
==> Extracting primary container
==> Determining which containers to use based on filetype
==> Checking container class Hbc::Container::Pkg
==> Using container class Hbc::Container::Pkg for /Users/yurikoles/Library/Caches/Homebrew/Cask/microsoft-office--15.33.17040900.pkg
==> Executing: ["/usr/bin/ditto", "--", "/Users/yurikoles/Library/Caches/Homebrew/Cask/microsoft-office--15.33.17040900.pkg", "/usr/local/Caskroom/microsoft-office/15.33.17040900/Microsoft_Office_2016_15.33.17040900_Installer.pkg"]
==> Creating metadata directory /usr/local/Caskroom/microsoft-office/.metadata/15.33.17040900/20170427111426.103.
==> Creating metadata subdirectory /usr/local/Caskroom/microsoft-office/.metadata/15.33.17040900/20170427111426.103/Casks.
==> Installing artifacts
==> Determining which artifacts are present in Cask microsoft-office
==> 3 artifact/s defined
#<Hbc::Artifact::Pkg:0x007fe51c2b07d8>
#<Hbc::Artifact::Uninstall:0x007fe51c2b0760>
#<Hbc::Artifact::Zap:0x007fe51c2b06c0>
==> Installing artifact of class Hbc::Artifact::Pkg
==> Running installer for microsoft-office; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
==> Executing: ["/usr/bin/sudo", "-E", "--", "/usr/sbin/installer", "-pkg", "/usr/local/Caskroom/microsoft-office/15.33.17040900/Microsoft_Office_2016_15.33.17040900_Installer.pkg", "-target", "/", "-verboseR"]
==> installer: Package name is Microsoft Office 2016 для Mac
==> installer: Installing at base path /
==> installer:PHASE:Подготовка к установке…
==> installer:PHASE:Подготовка диска…
==> installer:PHASE:Подготовка Microsoft Office 2016 для Mac…
==> installer: The install failed.
==> Purging files for version 15.33.17040900 of Cask microsoft-office
Error: Command failed to execute!

==> Failed command:
/usr/bin/sudo -E -- /usr/sbin/installer -pkg #<Pathname:/usr/local/Caskroom/microsoft-office/15.33.17040900/Microsoft_Office_2016_15.33.17040900_Installer.pkg> -target / -verboseR

==> Standard Output of failed command:
installer: Package name is Microsoft Office 2016 для Mac
installer: Installing at base path /
installer:PHASE:Подготовка к установке…
installer:PHASE:Подготовка диска…
installer:PHASE:Подготовка Microsoft Office 2016 для Mac…
installer: The install failed.


==> Standard Error of failed command:


==> Exit status of failed command:
#<Process::Status: pid 14852 exit 1>
Error: nothing to install/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:13:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:115:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:158:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:90:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:163:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:163:in `rescue in process'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:149:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:90:in `<main>'
```

#### Output of `brew cask doctor`

```
$ brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask >1.1.0 (no git repository)
caskroom/homebrew-cask (git revision 9f94aa; last commit 2017-04-27)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (19 files, 3.3GB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3648 casks)
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade (0 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-drivers (48 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-eid (7 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-fonts (1105 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (161 casks)
/usr/local/Homebrew/Library/Taps/haraldf/homebrew-kf5 (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-aliases (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-apache (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-binary (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-boneyard (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-command-not-found (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-completions (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-dev-tools (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-devel-only (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-dupes (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-emacs (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-fuse (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-games (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-gui (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-head-only (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-nginx (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-php (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-portable (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-python (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-science (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-tex (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-x11 (0 casks)
/usr/local/Homebrew/Library/Taps/jeffreywildman/homebrew-virt-manager (0 casks)
/usr/local/Homebrew/Library/Taps/vitorgalvao/homebrew-tiny-scripts (0 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Environment Variables
LANG="uk_UA.UTF-8"
PATH="/usr/local/opt/gettext:~/Gentoo/usr/bin:~/Gentoo/bin:~/Gentoo/tmp/usr/bin:~/Gentoo/tmp/bin:/usr/local/opt/coreutils/libexec/gnubin:/usr/local/sbin:~/.rvm/bin:~/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:~/.rvm/bin:~/go/bin:/ndk-bundle:~/.node_modules/bin:/usr/local/opt/jboss-as/libexec/bin:~/bin/depot-tools:/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/cmd:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-aliases/cmd:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/cmd:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-command-not-found/cmd:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-dev-tools/cmd:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-emacs/cmd:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-portable/cmd:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/cmd:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"

```

**Comment by yurikoles** [comment]
It installs fine by GUI.

**Comment by commitay** [comment]
Cannot reproduce.

@yurikoles Does this occur with any other `.pkg` casks or only `microsoft-office`?
