### ISSUE TITLE
auristor-client: `brew cask audit --download` fails

### ISSUE THREAD

**Issue by giannitm** [caskroom/homebrew-cask#33173]
#### General troubleshooting steps

- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Whenever I run `brew cask audit --download auristor-client`, it fails with the error message `exception while auditing auristor-client: invalid byte sequence in UTF-8`. I tried running `brew cask style --fix auristor-client` but this returned no styling errors. I've not tried installing this cask because of the warning comment in the cask file saying that it can, in unusual cases, be dangerous to run on "the next release of macOS" – I know that probably doesn't apply to me, but I'm not prepared to take that risk anyway.

#### Output of your command with `--verbose --debug`

```
$ brew cask audit --download --verbose --debug auristor-client
==> Auditing Cask auristor-client
==> Auditing required stanzas
==> Verifying version :latest does not appear as a string ('latest')
==> Verifying version does not contain '/'
==> Verifying sha256 :no_check with version :latest
==> Verifying sha256 string is a legal SHA-256 digest
==> Verifying sha256 is not a known invalid value
==> Auditing appcast
==> Verifying appcast has :checkpoint key
==> Verifying appcast :checkpoint string is a legal SHA-256 digest
==> Verifying appcast :checkpoint is not a known invalid value
==> Verifying appcast returns 200 HTTP response code
==> Executing: ["/usr/bin/curl", "--compressed", "--location", "--user-agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10) https://caskroom.github.io", "--output", "/dev/null", "--write-out", "%{http_code}", "https://www.auristor.com/filesystem/client-installer/"]
==> Verifying appcast checkpoint is accurate
==> Executing: ["/usr/bin/curl", "--compressed", "--location", "--user-agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10) https://caskroom.github.io", "https://www.auristor.com/filesystem/client-installer/"]
==> invalid byte sequence in UTF-8
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/dsl/appcast.rb:18:in `gsub'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/dsl/appcast.rb:18:in `calculate_checkpoint'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/audit.rb:136:in `check_appcast_checkpoint_accuracy'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/audit.rb:115:in `check_appcast'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/audit.rb:26:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/auditor.rb:54:in `audit_cask_instance'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/auditor.rb:27:in `audit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/auditor.rb:4:in `audit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/audit.rb:27:in `audit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/audit.rb:21:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/audit.rb:20:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/audit.rb:20:in `each_with_object'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/audit.rb:20:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/audit.rb:9:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:115:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:158:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:90:in `<main>'
audit for auristor-client: failed
 - exception while auditing auristor-client: invalid byte sequence in UTF-8
Error: audit failed for casks: auristor-client/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/audit.rb:11:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:115:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:158:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:90:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:163:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:163:in `rescue in process'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:149:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:90:in `<main>'
```

#### Output of `brew cask doctor`

```
$ brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.1.12-3668-gb067700f
caskroom/homebrew-cask (git revision d3afe; last commit 2017-04-29)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (1 files, 60.8MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3650 casks)
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree (0 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-drivers (48 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-eid (7 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-fonts (1105 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (161 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core (0 casks)
/usr/local/Homebrew/Library/Taps/vitorgalvao/homebrew-tiny-scripts (0 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Environment Variables
LANG="en_GB.UTF-8"
PATH="/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

**Comment by vitorgalvao** [comment]
I’ve seen this happen before. It’s the `appcast` causing the trouble. Run `brew cask _appcast_checkpoint --calculate https://www.auristor.com/filesystem/client-installer/` (which `audit --download` also does) and you’ll see.

For now, let’s remove the `appcast`.

@reitermarkus I’m guessing this happens due to something on the webpage. Is there a way we can avoid it?

**Comment by giannitm** [comment]
I've just experienced the same issue with another cask, [`brushviewql`](Casks/brushviewql.rb), and the appcast looks very strange when it `curl` fetches it:

<img width="832" alt="screen shot 2017-04-29 at 19 55 03" src="https://cloud.githubusercontent.com/assets/25732197/25558009/c5043daa-2d15-11e7-944a-356202a7ad83.png">

I assume whoever/whatever created this document did not format it or style it correctly.

@vitorgalvao Do you want me to remove appcasts like this?

**Comment by vitorgalvao** [comment]
@giannitm That one is completely wrong: [it’s a zip file](https://github.com/caskroom/homebrew-cask/blob/7945f8be99138166dbe9b73418aeb3287c9d6bf0/Casks/brushviewql.rb#L6).

**Comment by giannitm** [comment]
@vitorgalvao I'll create a pull request using the cask's homepage as the appcast. That has the versioned download links on it (the text for the links is versioned, not the links themselves), and doesn't look like it will change regularly otherwise.

**Comment by vitorgalvao** [comment]
That one is from sourceforge, so it should have a proper appcast. See https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md.

**Comment by giannitm** [comment]
#33203 Sorry, I should have checked the appcast documentation. Thanks for the help @vitorgalvao.

**Comment by vitorgalvao** [comment]
Thank you for being so fast.
