### ISSUE TITLE
brew cask commands do not work due to "Error: No available Cask"

### ISSUE THREAD

**Issue by hanxue** [caskroom/homebrew-cask#33520]
#### Description of issue

Whenever I run any `brew cask` commands, I get the output:

```Error: No available Cask for aimersoft-youtube-downloader```

#### Output of your command with `--verbose --debug`

```
$ brew cask list --verbose --debug
Error: No available Cask for aimersoft-youtube-downloader/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:111:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:128:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/scopes.rb:40:in `block in installed'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/scopes.rb:30:in `map'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/scopes.rb:30:in `installed'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/list.rb:63:in `list_installed'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/list.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:115:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:158:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:92:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:163:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:163:in `rescue in process'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:149:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:92:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew-Cask Version
Homebrew-Cask 1.2.0-46-g93d4fdf938
caskroom/homebrew-cask (git revision 09e5b; last commit 2017-05-05)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (1 files, 0B)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3613 casks)
/usr/local/Homebrew/Library/Taps/aspnet/homebrew-dnx (0 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-drivers (90 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-fonts (1106 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (161 casks)
/usr/local/Homebrew/Library/Taps/chilledheart/homebrew-seafile (0 casks)
/usr/local/Homebrew/Library/Taps/clockworknet/homebrew-cmc (0 casks)
/usr/local/Homebrew/Library/Taps/codeclimate/homebrew-formulae (0 casks)
/usr/local/Homebrew/Library/Taps/darinmorrison/homebrew-haskell (0 casks)
/usr/local/Homebrew/Library/Taps/dart-lang/homebrew-dart (0 casks)
/usr/local/Homebrew/Library/Taps/gbeine/homebrew-java (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-apache (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-boneyard (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-completions (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-dupes (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-fuse (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-headonly (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-php (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-python (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-science (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-versions (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-x11 (0 casks)
/usr/local/Homebrew/Library/Taps/mcuadros/homebrew-hhvm (0 casks)
/usr/local/Homebrew/Library/Taps/mopidy/homebrew-mopidy (0 casks)
/usr/local/Homebrew/Library/Taps/nwoolls/homebrew-xgminer (0 casks)
/usr/local/Homebrew/Library/Taps/petere/homebrew-postgresql (0 casks)
/usr/local/Homebrew/Library/Taps/saerdnaer/homebrew-osmium (0 casks)
/usr/local/Homebrew/Library/Taps/telemachus/homebrew-desc (0 casks)
/usr/local/Homebrew/Library/Taps/thoughtbot/homebrew-formulae (0 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin14
/Library/Ruby/Site/2.0.0/universal-darwin14
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin14
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin14
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin14
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin14
==> Environment Variables
LANG="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
LC_CTYPE="UTF-8"
PATH="~/.jenv/shims:~/.cabal/bin:/usr/local/var/rbenv/shims:/usr/local/bin:/usr/local/sbin:/opt/local/bin:/opt/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/MacGPG2/bin:~/Github/depot_tools:~/Source/google-cloud-sdk/bin:~/Code/Go/bin:~/.composer/vendor/bin:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd:/usr/local/Homebrew/Library/Taps/telemachus/homebrew-desc/cmd:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"

```

**Comment by miccal** [comment]
Please run the command:
```
cd "$(brew --repository)"; git fetch; git reset --hard origin/master; brew update
```
which should fix your issue.

**Comment by rattigan** [comment]
I have a similar issue with the wacom-tablet cask. The command above did not fix the issue.

**Comment by rattigan** [comment]
deleting the wacom-tablet directory from the staging location (/usr/local/Caskrooom) seems to have solved the problem

**Comment by vitorgalvao** [comment]
Closing due to no reply.
