### ISSUE TITLE
anaconda installed as root

### ISSUE THREAD

**Issue by xanderdunn** [caskroom/homebrew-cask#33904]
#### General troubleshooting steps
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.

#### Description of issue
Mac OSX 10.12.4.  `brew cask install anaconda`.  It installed anaconda 4.3.1.  Then I added to my ~/.profile: `export PATH=$PATH:/usr/local/anaconda3/bin`.  

If I attempt to run conda:
```
$ conda
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 573, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/conda/cli/main.py", line 85, in _main
    from ..base.context import context
  File "/usr/local/anaconda3/lib/python3.6/site-packages/conda/base/context.py", line 19, in <module>
    from .._vendor.auxlib.path import expand
  File "/usr/local/anaconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/path.py", line 8, in <module>
    import pkg_resources
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "/usr/local/anaconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2985, in <module>
  File "/usr/local/anaconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2971, in _call_aside
  File "/usr/local/anaconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2998, in _initialize_master_working_set
  File "/usr/local/anaconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 651, in _build_master
  File "/usr/local/anaconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 644, in __init__
  File "/usr/local/anaconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 700, in add_entry
  File "/usr/local/anaconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 1990, in find_on_path
  File "/usr/local/anaconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2399, in from_location
  File "/usr/local/anaconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2740, in _reload_version
  File "/usr/local/anaconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2364, in _version_from_file
  File "/usr/local/anaconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2532, in _get_metadata
  File "/usr/local/anaconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 1472, in get_metadata_lines
  File "/usr/local/anaconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 1468, in get_metadata
  File "/usr/local/anaconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 1577, in _get
PermissionError: [Errno 13] Permission denied: '/usr/local/anaconda3/lib/python3.6/site-packages/llvmlite-0.15.0-py3.6.egg-info/PKG-INFO'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/anaconda3/bin/conda", line 6, in <module>
    sys.exit(conda.cli.main())
  File "/usr/local/anaconda3/lib/python3.6/site-packages/conda/cli/main.py", line 164, in main
    return conda_exception_handler(_main, *args)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 589, in conda_exception_handler
    print_unexpected_error_message(e)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 526, in print_unexpected_error_message
    from conda.base.context import context
  File "/usr/local/anaconda3/lib/python3.6/site-packages/conda/base/context.py", line 19, in <module>
    from .._vendor.auxlib.path import expand
  File "/usr/local/anaconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/path.py", line 8, in <module>
    import pkg_resources
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "/usr/local/anaconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2985, in <module>
  File "/usr/local/anaconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2971, in _call_aside
  File "/usr/local/anaconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2998, in _initialize_master_working_set
  File "/usr/local/anaconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 651, in _build_master
  File "/usr/local/anaconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 644, in __init__
  File "/usr/local/anaconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 700, in add_entry
  File "/usr/local/anaconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 1990, in find_on_path
  File "/usr/local/anaconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2399, in from_location
  File "/usr/local/anaconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2740, in _reload_version
  File "/usr/local/anaconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2364, in _version_from_file
  File "/usr/local/anaconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2532, in _get_metadata
  File "/usr/local/anaconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 1472, in get_metadata_lines
  File "/usr/local/anaconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 1468, in get_metadata
  File "/usr/local/anaconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 1577, in _get
PermissionError: [Errno 13] Permission denied: '/usr/local/anaconda3/lib/python3.6/site-packages/llvmlite-0.15.0-py3.6.egg-info/PKG-INFO'
```

#### Output of `brew cask doctor`

```
brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask >1.2.0 (no git repository)
caskroom/homebrew-cask (git revision d8152; last commit 2017-05-12)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (9 files, 641.5MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3619 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services (0 casks)
/usr/local/Homebrew/Library/Taps/neovim/homebrew-neovim (0 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Environment Variables
LANG="en_US.UTF-8"
PATH="~/mongodb/bin:/usr/local/bin:/usr/local/sbin:~/.gem/bin:/usr/local/Cellar/llvm/3.6.2/lib/llvm-3.6/bin:~/.local/bin:/usr/local/opt/ruby/bin:/usr/bin:/bin:/usr/sbin:/sbin:~/.rvm/bin:~/nim/bin:~/go/bin:/usr/local/anaconda3/bin:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

When I look at the output of permissions in /usr/local:
```
$ l /usr/local/
total 0
drwxrwxr-x  10 xander  admin   340B May 11 20:56 Caskroom
drwxrwxr-x  20 xander  admin   680B May 11 18:59 Cellar
drwxrwxr-x   2 xander  admin    68B May 11 16:00 Frameworks
drwxrwxr-x  17 xander  admin   578B May 11 20:55 Homebrew
drwxr-xr-x  23 root    wheel   782B May 11 20:58 anaconda3
drwxrwxr-x  49 xander  admin   1.6K May 11 18:59 bin
drwxrwxr-x   6 xander  admin   204B May 11 18:53 etc
drwxrwxr-x  20 xander  admin   680B May 11 18:59 include
drwxrwxr-x  27 xander  admin   918B May 11 18:59 lib
drwxrwxr-x  28 xander  admin   952B May 11 18:59 opt
drwxr-xr-x   3 root    wheel   102B Mar  6 11:10 remotedesktop
drwxrwxr-x   2 xander  admin    68B May 11 16:00 sbin
drwxrwxr-x  23 xander  admin   782B May 11 16:24 share
drwxrwxr-x   6 xander  admin   204B May 11 18:53 var
```

Why is anaconda installed as root while everything else is my user?  Manually changing the permissions myself fixes the problem: `sudo chown -R xander:admin /usr/local/anaconda3`, but I'd expect brew cask to install it with the necessary permissions?

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/33905

**Comment by commitay** [comment]
@xanderdunn Please fill out the issue template properly next time.

**Comment by xanderdunn** [comment]
@commitay What did I miss?

**Comment by commitay** [comment]
```

- [ ] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [ ] None of the templates was appropriate for my issue, or I’m not sure.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [ ] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
```

**Comment by xanderdunn** [comment]
I checked the middle two.  The top two and the last one didn't seem to convey any information.  Thanks for working on the fix.

**Comment by commitay** [comment]
> ### I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

The last one is there because people don't fill out the template properly.

**Comment by vitorgalvao** [comment]
> The top two and the last one didn't seem to convey any information. 

Respectfully, that is not your call to make. Those are in fact *the* most important ones because they are the ones that have a higher chance of making you resolve your issue without our help. Even if you don’t do some step, it’s more helpful to leave them unchecked (so we know what you already did) than deleting them (which is the only time where it conveys no information).

@commitay is correct. That last one is there precisely so you take a hard look at the myriad of help resources we already poured our time into, instead of filling a duplicate issue (which is a real time sink).
