### ISSUE TITLE
Cask adobe-photoshop-lightroom fails on install

### ISSUE THREAD

**Issue by zeillemaker** [caskroom/homebrew-cask#33956]
#### General troubleshooting steps

- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

When trying to install the cask adobe-photoshop-lightroom, the installation repeatedly fails on the same point (see also the output below).

A message of a failed command '/usr/bin/killall -kill SafariNotificationAgent' is given.
This seems to be the same problem as was reposted in bug report #27804. The fix provided by #27884 does not seem to have fixed this issue.

When checking, the SafariNotificationAgent daemon does not seem to be running.
`-	0	com.apple.SafariNotificationAgent`

Is this a problem with checking if the SafariNotificationAgent is active?

#### Output of your command with `--verbose --debug`

```
brew cask install adobe-photoshop-lightroom --verbose --debug
==> Hbc::Installer#install
==> Printing caveats
==> Caveats
Installation or Uninstallation may fail with Exit Code 19 (Conflicting Processes running) if Browsers, Safari Notification Service or SIMBL Services are running or Adobe Creative Cloud or any other Adobe Products are already installed. See Logs in /Library/Logs/Adobe/Installers if Installation or Uninstallation fails, to identify the conflicting processes.

==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Installing Cask dependencies: caskroom/versions/adobe-photoshop-lightroom600
caskroom/versions/adobe-photoshop-lightroom600 ...
==> Hbc::Installer#install
==> Printing caveats
==> Caveats
Installation or Uninstallation may fail with Exit Code 19 (Conflicting Processes running) if Browsers, Safari Notification Service or SIMBL Services are running or Adobe Creative Cloud or any other Adobe Products are already installed. See Logs in /Library/Logs/Adobe/Installers if Installation or Uninstallation fails, to identify the conflicting processes.

==> Hbc::Installer#fetch
==> Downloading
==> Downloading http://trials3.adobe.com/AdobeProducts/LTRM/6/osx10/Lightroom_6_LS11.dmg
Already downloaded: /Users/zeillemaker/Library/Caches/Homebrew/Cask/adobe-photoshop-lightroom600--6.0.dmg
==> Downloaded to -> /Users/zeillemaker/Library/Caches/Homebrew/Cask/adobe-photoshop-lightroom600--6.0.dmg
==> Verifying download
==> Determining which verifications to run for Cask adobe-photoshop-lightroom600
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask adobe-photoshop-lightroom600
==> SHA256 checksums match
==> Installing Cask adobe-photoshop-lightroom600
==> Hbc::Installer#stage
==> Extracting primary container
==> Determining which containers to use based on filetype
==> Checking container class Hbc::Container::Pkg
==> Checking container class Hbc::Container::Ttf
==> Checking container class Hbc::Container::Otf
==> Checking container class Hbc::Container::Air
==> Checking container class Hbc::Container::Cab
==> Checking container class Hbc::Container::Dmg
==> Executing: ["/usr/bin/hdiutil", "imageinfo", "/Users/zeillemaker/Library/Caches/Homebrew/Cask/adobe-photoshop-lightroom600--6.0.dmg"]
==> Using container class Hbc::Container::Dmg for /Users/zeillemaker/Library/Caches/Homebrew/Cask/adobe-photoshop-lightroom600--6.0.dmg
==> Executing: ["/usr/bin/hdiutil", "mount", "-plist", "-nobrowse", "-readonly", "-noidme", "-mountrandom", "/tmp", "/Users/zeillemaker/Library/Caches/Homebrew/Cask/adobe-photoshop-lightroom600--6.0.dmg"]
==> Executing: ["/usr/bin/mkbom", "-s", "-i", "/var/folders/mm/23yws5y54r95pbbh9gtsk_tw0000gn/T/20170512-5337-1eos7x5.list", "--", "/var/folders/mm/23yws5y54r95pbbh9gtsk_tw0000gn/T/20170512-5337-12i8x6w.bom"]
==> Executing: ["/usr/bin/ditto", "--bom", "/var/folders/mm/23yws5y54r95pbbh9gtsk_tw0000gn/T/20170512-5337-12i8x6w.bom", "--", "/private/tmp/dmg.WyqWba", "/usr/local/Caskroom/adobe-photoshop-lightroom600/6.0"]
==> Executing: ["/usr/sbin/diskutil", "eject", "/private/tmp/dmg.WyqWba"]
==> Creating metadata directory /usr/local/Caskroom/adobe-photoshop-lightroom600/.metadata/6.0/20170512203420.403.
==> Creating metadata subdirectory /usr/local/Caskroom/adobe-photoshop-lightroom600/.metadata/6.0/20170512203420.403/Casks.
==> Installing artifacts
==> Determining which artifacts are present in Cask adobe-photoshop-lightroom600
==> 3 artifact/s defined
#<Hbc::Artifact::PreflightBlock:0x007fd5b38f4f68>
#<Hbc::Artifact::Uninstall:0x007fd5b38f4ea0>
#<Hbc::Artifact::Zap:0x007fd5b38f4e00>
==> Installing artifact of class Hbc::Artifact::PreflightBlock
==> Executing: ["/usr/bin/killall", "-kill", "SafariNotificationAgent"]
==> No matching processes belonging to you were found
==> Purging files for version 6.0 of Cask adobe-photoshop-lightroom600
Error: Command failed to execute!

==> Failed command:
/usr/bin/killall -kill SafariNotificationAgent

==> Standard Output of failed command:


==> Standard Error of failed command:
No matching processes belonging to you were found


==> Exit status of failed command:
#<Process::Status: pid 5487 exit 1>
Error: nothing to install/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:13:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:115:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:158:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:92:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:163:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:163:in `rescue in process'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:149:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:92:in `<main>'
```

#### Output of `brew cask doctor`

```
brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.2.0-66-g459fef3
caskroom/homebrew-cask (git revision d4a42; last commit 2017-05-12)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (6 files, 970.3MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3620 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (161 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core (0 casks)
/usr/local/Homebrew/Library/Taps/vitorgalvao/homebrew-tiny-scripts (0 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Environment Variables
LC_CTYPE="UTF-8"
PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

**Comment by commitay** [comment]
Looks like the problem is with the `preflight` for [`adobe-photoshop-lightroom600`](https://github.com/caskroom/homebrew-versions/blob/f6878e12f0102b6a4846349a3f2a650df3959af9/Casks/adobe-photoshop-lightroom600.rb).

https://github.com/caskroom/homebrew-versions/issues/3827

**Comment by zeillemaker** [comment]
I didn't see the difference between the lightroom & lightroom600 preflight.
Works like a charm, thanks!
