### ISSUE TITLE
brew cask info adobe-reader error

### ISSUE THREAD

**Issue by tiiiecherle** [caskroom/homebrew-cask#34153]
adobe-reader cask is installed

`brew cask info adobe-reader `

shows the following errors

```
Error: Invalid tap name '/'
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/tap.rb:29:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/info.rb:55:in `repo_info'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/info.rb:23:in `info'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/info.rb:11:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/info.rb:7:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/info.rb:7:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:115:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:158:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:90:in `<main>'
```

thanks for fixing in advance

**Comment by vitorgalvao** [comment]
It’s been renamed to `adobe-acrobat-reader`.

We’re planning a more robust approach to when casks are renamed. Currently it’s a bit lackluster, for cases like this.
