### ISSUE TITLE
Cannot install octave

### ISSUE THREAD

**Issue by sebma** [caskroom/homebrew-cask#34363]
#### General troubleshooting steps

- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

I cannot install octave

#### Output of your command with `--verbose --debug`

```
$ brew cask install xoctave --verbose --debug 
==> Hbc::Installer#install
==> Printing caveats
==> Hbc::Installer#fetch
==> Downloading
==> Downloading http://www.xoctave.com/demo/xoctave%20demo.dmg
==> Calling curl with args ["http://www.xoctave.com/demo/xoctave%20demo.dmg", "-C", "0", "-o", "#<Pathname:/Users/mansfeld/Library/Caches/Homebrew/Cask/xoctave--latest.dmg.incomplete>"]
/usr/bin/curl --remote-time --location --user-agent Homebrew/1.2.1-3564-gf0dc1d96 (Macintosh; Intel Mac OS X 10.12.4) curl/7.51.0 --fail http://www.xoctave.com/demo/xoctave%20demo.dmg -C 0 -o /Users/mansfeld/Library/Caches/Homebrew/Cask/xoctave--latest.dmg.incomplete
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 406 Not Acceptable
Error: Download failed on Cask 'xoctave' with message: Download failed: http://www.xoctave.com/demo/xoctave%20demo.dmg
The incomplete download is cached at /Users/mansfeld/Library/Caches/Homebrew/Cask/xoctave--latest.dmg.incomplete
Error: nothing to install/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:13:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:115:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:158:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:92:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:163:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:163:in `rescue in process'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:149:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:92:in `<main>'
```

#### Output of `brew cask doctor`

```
$ brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.2.1-3564-gf0dc1d96
caskroom/homebrew-cask (git revision 9f709; last commit 2017-05-18)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (1 files, 0B)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3622 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (162 casks)
/usr/local/Homebrew/Library/Taps/cavaliercoder/homebrew-dmidecode (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-boneyard (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-science (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-tex (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-versions (0 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Environment Variables
LC_CTYPE="UTF-8"
PATH="/opt/local/bin:/opt/local/sbin:~/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/TeX/texbin:/Applications/Wireshark.app/Contents/MacOS:~/shl:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/usr/local/bin/bash"
```

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/pull/34364

**Comment by sebma** [comment]
The pb. here is not related to the URL of the latest version of xoctave but to the user agent is containing "curl", therefore the download is rejected : 

```
$ curl -#OA "curl" --fail "http://www.xoctave.com/demo/xoctave%20demo.dmg"

curl: (22) The requested URL returned error: 406 Not Acceptable
$ curl -#OA "Homebrew" --fail "http://www.xoctave.com/demo/xoctave%20demo.dmg"
######################################################################## 100.0%
$
```

**Comment by vitorgalvao** [comment]
Please do not repeat your posts in multiple issues. It only fragments the discussion and annoys.

As stated in the PR, the fix solves the issue. I tested it beforehand.
