### ISSUE TITLE
Having Error when trying to brew cask install android-sdk on mac os x

### ISSUE THREAD

**Issue by HudsonAfonso** [caskroom/homebrew-cask#34368]
#### General troubleshooting steps

- [ ] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [ ] None of the templates was appropriate for my issue, or I’m not sure.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [ ] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Tried to run:
$brew cask install android-sdk

#### Output of your command with `--verbose --debug`

```
$ brew cask install android-sdk --verbose --debug
==> Hbc::Installer#install
==> Printing caveats
==> Caveats
We will install android-sdk-tools, platform-tools, and build-tools for you.
You can control android sdk packages via the sdkmanager command.
You may want to add to your profile:
  'export ANDROID_SDK_ROOT=/usr/local/share/android-sdk'

This operation may take up to 10 minutes depending on your internet connection.
Please, be patient.

==> Hbc::Installer#fetch
==> Downloading
==> Downloading https://dl.google.com/android/repository/tools_r25.2.3-macosx.zip
Already downloaded: /Users/hafonso/Library/Caches/Homebrew/Cask/android-sdk--25.2.3.zip
==> Downloaded to -> /Users/hafonso/Library/Caches/Homebrew/Cask/android-sdk--25.2.3.zip
==> Verifying download
==> Determining which verifications to run for Cask android-sdk
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask android-sdk
==> SHA256 checksums match
==> Installing Cask android-sdk
==> Hbc::Installer#stage
==> Extracting primary container
==> Determining which containers to use based on filetype
==> Checking container class Hbc::Container::Pkg
==> Checking container class Hbc::Container::Ttf
==> Checking container class Hbc::Container::Otf
==> Checking container class Hbc::Container::Air
==> Checking container class Hbc::Container::Cab
==> Checking container class Hbc::Container::Dmg
==> Executing: ["/usr/bin/hdiutil", "imageinfo", "/Users/hafonso/Library/Caches/Homebrew/Cask/android-sdk--25.2.3.zip"]
==> Checking container class Hbc::Container::SevenZip
==> Checking container class Hbc::Container::Sit
==> Checking container class Hbc::Container::Rar
==> Checking container class Hbc::Container::Zip
==> Using container class Hbc::Container::Zip for /Users/hafonso/Library/Caches/Homebrew/Cask/android-sdk--25.2.3.zip
==> Executing: ["/usr/bin/ditto", "-x", "-k", "--", "/Users/hafonso/Library/Caches/Homebrew/Cask/android-sdk--25.2.3.zip", "/var/folders/fv/ybc1939142v07032hw4k8tw00000gn/T/d20170518-28422-22l4sd"]
==> Creating metadata directory /usr/local/Caskroom/android-sdk/.metadata/25.2.3/20170518181201.812.
==> Creating metadata subdirectory /usr/local/Caskroom/android-sdk/.metadata/25.2.3/20170518181201.812/Casks.
==> Installing artifacts
==> Determining which artifacts are present in Cask android-sdk
==> 3 artifact/s defined
#<Hbc::Artifact::PreflightBlock:0x007fce539da200>
#<Hbc::Artifact::Binary:0x007fce539da110>
#<Hbc::Artifact::PostflightBlock:0x007fce539da098>
==> Installing artifact of class Hbc::Artifact::PreflightBlock
==> Executing: ["/usr/local/Caskroom/android-sdk/25.2.3/tools/bin/sdkmanager", "tools", "platform-tools", "build-tools;25.0.2"]
==> Warning: File /Users/hafonso/.android/repositories.cfg could not be loaded.
==> Warning: java.net.SocketException: java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)
==> Warning: Failed to download any source lists!
==> Error: Failed to find package tools
==> Purging files for version 25.2.3 of Cask android-sdk
Error: Command failed to execute!

==> Failed command:
/usr/local/Caskroom/android-sdk/25.2.3/tools/bin/sdkmanager tools platform-tools build-tools;25.0.2

==> Standard Output of failed command:


==> Standard Error of failed command:
Warning: File /Users/hafonso/.android/repositories.cfg could not be loaded.
Warning: java.net.SocketException: java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)
Warning: Failed to download any source lists!
Error: Failed to find package tools


==> Exit status of failed command:
#<Process::Status: pid 28548 exit 1>
Error: nothing to install/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:13:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:115:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:158:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:92:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:163:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:163:in `rescue in process'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:149:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:92:in `<main>'
```

#### Output of `brew cask doctor`

```
$ brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.2.1
caskroom/homebrew-cask (git revision 6a0bb; last commit 2017-05-18)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (1 files, 191.2MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3622 casks)
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree (0 casks)
/usr/local/Homebrew/Library/Taps/cartr/homebrew-qt4 (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-binary (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-dupes (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-php (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-python (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-science (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-versions (0 casks)
/usr/local/Homebrew/Library/Taps/manastech/homebrew-crystal (0 casks)
/usr/local/Homebrew/Library/Taps/tsuru/homebrew-tsuru (0 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Environment Variables
LC_CTYPE="UTF-8"
PATH="~/.rvm/gems/ruby-2.3.0/bin:~/.rvm/gems/ruby-2.3.0@global/bin:~/.rvm/rubies/ruby-2.3.0/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/local/sbin:~/bin:~/Downloads/axis2-1.6.2/bin:~/Library/Android/sdk/platform-tools:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/go/bin:/usr/local/share/npm/bin:~/.rvm/bin:/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/cmd:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

**Comment by commitay** [comment]
I cannot reproduce this.

> ==> Warning: java.net.SocketException: java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)

@HudsonAfonso I'd suggest investigating the cause of this java error as this does not seem to be an issue with the cask.

**Comment by miccal** [comment]
@HudsonAfonso please post the output of `brew config`.

**Comment by HudsonAfonso** [comment]
@miccal 
```
$ brew config
HOMEBREW_VERSION: 1.2.1
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: ea8be174f6009bc9bdec67b13ca501b5b83fc4b8
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b39cdd5b5f0acda2aa9ca2a27af4e1772b9d4611
Core tap last commit: 8 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.11.0 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/hafonso/.rvm/rubies/ruby-2.3.0/bin/ruby
Java: 1.8.0_60, 1.7.0_71, 1.6.0_65-b14-468
macOS: 10.12.5-x86_64
Xcode: 8.3.2
CLT: 8.3.2.0.1.1492020469
X11: 2.7.11 => /opt/X11
```

**Comment by miccal** [comment]
Thanks @HudsonAfonso, but this definitely seems to be a problem with your multiple Java versions, and not something we can fix in Cask.
