### ISSUE TITLE
paraview cannot be installed

### ISSUE THREAD

**Issue by jiaor** [caskroom/homebrew-cask#34728]
#### General troubleshooting steps

- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

the downloaded .dmg file cannot be unpacked.

==> Installing Cask paraview
Error: Uh oh, could not figure out how to unpack '/Users/jiaor/Library/Caches/Homebrew/Cask/paraview--5.4.0.dmg'
Error: nothing to install

### Output of your command with `--verbose --debug`

```
==> Hbc::Installer#install
==> Printing caveats
==> Hbc::Installer#fetch
==> Downloading
==> Downloading http://www.paraview.org/paraview-downloads/download.php?submit=Download&version=v5.4&type=binary&os=osx&downloadFile=ParaView-5.4.0-Qt5-OpenGL2-MPI-OSX10.8-64bit.dmg
Already downloaded: /Users/jiaor/Library/Caches/Homebrew/Cask/paraview--5.4.0.dmg
==> Downloaded to -> /Users/jiaor/Library/Caches/Homebrew/Cask/paraview--5.4.0.dmg
==> Verifying download
==> Determining which verifications to run for Cask paraview
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask paraview
==> SHA256 checksums match
==> Installing Cask paraview
==> Hbc::Installer#stage
==> Extracting primary container
==> Determining which containers to use based on filetype
==> Checking container class Hbc::Container::Pkg
==> Checking container class Hbc::Container::Ttf
==> Checking container class Hbc::Container::Otf
==> Checking container class Hbc::Container::Air
==> Checking container class Hbc::Container::Cab
==> Checking container class Hbc::Container::Dmg
==> Executing: ["/usr/bin/hdiutil", "imageinfo", "/Users/jiaor/Library/Caches/Homebrew/Cask/paraview--5.4.0.dmg"]
==> Checking container class Hbc::Container::SevenZip
==> Checking container class Hbc::Container::Sit
==> Checking container class Hbc::Container::Rar
==> Checking container class Hbc::Container::Zip
==> Checking container class Hbc::Container::Xar
==> Checking container class Hbc::Container::Tar
==> Checking container class Hbc::Container::Bzip2
==> Checking container class Hbc::Container::Gzip
==> Checking container class Hbc::Container::Lzma
==> Checking container class Hbc::Container::Xz
==> Checking container class Hbc::Container::Gpg
==> Checking container class Hbc::Container::Executable
==> Purging files for version 5.4.0 of Cask paraview
Error: Uh oh, could not figure out how to unpack '/Users/jiaor/Library/Caches/Homebrew/Cask/paraview--5.4.0.dmg'
Error: nothing to install/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:13:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:115:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:158:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:163:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:163:in `rescue in process'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:149:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew-Cask Version
Homebrew-Cask 1.2.1-40-gdd5d4880d
caskroom/homebrew-cask (git revision 47f8a; last commit 2017-05-22)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (2 files, 254.5KB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3615 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-boneyard (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-dupes (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-python (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-science (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-x11 (0 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Environment Variables
LANG="en_GB.UTF-8"
PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

**Comment by MTCoster** [comment]
The download link appears to be broken - `http://www.paraview.org/paraview-downloads/download.php?submit=Download&version=v5.4&type=binary&os=osx&downloadFile=ParaView-5.4.0-Qt5-OpenGL2-MPI-OSX10.8-64bit.dmg` returns a 404 error for me

**Comment by giannitm** [comment]
The download works for me. Perhaps it was a temporary issue with the server?

```
1 file inspected, no offenses detected
==> Downloading http://www.paraview.org/paraview-downloads/download.php?submit=Download&version=v5.4&type=binary&os=osx&downloadFile=ParaView-5.4.0-Qt5-OpenGL2-MPI-OSX10.8-64bit.dmg
######################################################################## 100.0%
==> Verifying checksum for Cask paraview
audit for paraview: warning
 - appcast checkpoint mismatch
Expected: 971c7202a3757ada059550673c3c7fe0be7193592ef6c933507e83993f099cfa
Actual: a8988baf9122d1327ebec216cc9334fddc824614ef4c667943900fd818083f9b
Error: audit failed for casks: paraview
```

**Comment by MTCoster** [comment]
Their download server appears to not utilise HTTP status codes correctly - it returns a 200 (OK) status, but the response body is simply the following (a 'soft' 404):

    <b>404 File not found!</b><br>/projects/FTP/pub/paraview/v5.4/ParaView-5.4.0-Qt5-OpenGL2-MPI-OSX10.8-64bit.dmg

**Comment by giannitm** [comment]
@MTCoster I see what you mean – I just tried to open the .dmg file it downloaded, but it is unreadable according to Finder. 

Also, I tried using `curl` to fetch Paraview version 5.3, and the file would not download. The download seems to work fine when I use Safari, though.

**Comment by MTCoster** [comment]
Since they use the following language on their homepage, I think we should stick to 5.3 for now:

>**Download Latest Release**
>ParaView version 5.3.0 is now available for download.

**Comment by commitay** [comment]
> Also, I tried using curl to fetch Paraview version 5.3, and the file would not download. The download seems to work fine when I use Safari, though.

@giannitm Reverting to `5.3.0` and adding `user_agent: :fake` allows the cask to be installed.

I haven't tested the other `version`s, so I don't know if they also require `user_agent: :fake`.

```
  else
    version '5.3.0'
    sha256 '75b385dcf244f3942cb74eeed8e593d6744a330f1f97ae1301c6584da8d607c0'
    url "http://www.paraview.org/paraview-downloads/download.php?submit=Download&version=v#{version.major_minor}&type=binary&os=osx&downloadFile=ParaView-#{version}-Qt5-OpenGL2-MPI-OSX10.8-64bit.dmg",
        user_agent: :fake
    app "Paraview-#{version}.app"
  end
```

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/34782

**Comment by jiaor** [comment]
thank you guys. I sort of knew the problem, but wasn't sure how to make the change.
