### ISSUE TITLE
Outdated cask: Paste

### ISSUE THREAD

**Issue by sholladay** [caskroom/homebrew-cask#34868]
Running `brew cask install paste` fails due to `curl` receiving a 404 Not Found when attempting to fetch the download URL in [the cask](https://github.com/caskroom/homebrew-cask/blob/master/Casks/paste.rb). I even tried to use earlier incarnations of the cask that previously worked for me and they now do not.

I guess for some reason it just disappeared from the [HockeyApp](https://www.hockeyapp.net/) API.  I have no idea why that would happen. Not really brew's fault, I know. But am I correct in my understanding that the HockeyApp account being used is something you all control as infrastructure? Never used it before, but that's what I gather from their docs and I see it used in multiple casks.

The newest version of [Paste](http://pasteapp.me/) is "Version 2.2.1 (34)".

#### Debugging info

<details><summary>Output of the command with `--verbose --debug`</summary>

```sh
sholladay$ brew cask install paste --verbose --debug
==> Hbc::Installer#install
==> Printing caveats
==> Hbc::Installer#fetch
==> Downloading
==> Downloading https://rink.hockeyapp.net/api/2/apps/ee24d1a939cd4ff8b2861eb8c788a995/app_versions/6?format=zip
==> Calling curl with args ["https://rink.hockeyapp.net/api/2/apps/ee24d1a939cd4ff8b2861eb8c788a995/app_versions/6?format=zip", "-C", "0", "-o", "#<Pathname:/Users/sholladay/Library/Caches/Homebrew/Cask/paste--2.2.1,6.incomplete>"]
/usr/bin/curl --remote-time --location --user-agent Homebrew/1.2.1-92-ge931fee7 (Macintosh; Intel Mac OS X 10.12.4) curl/7.51.0 --fail https://rink.hockeyapp.net/api/2/apps/ee24d1a939cd4ff8b2861eb8c788a995/app_versions/6?format=zip -C 0 -o /Users/sholladay/Library/Caches/Homebrew/Cask/paste--2.2.1,6.incomplete
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'paste' with message: Download failed: https://rink.hockeyapp.net/api/2/apps/ee24d1a939cd4ff8b2861eb8c788a995/app_versions/6?format=zip
The incomplete download is cached at /Users/sholladay/Library/Caches/Homebrew/Cask/paste--2.2.1,6.incomplete
Error: nothing to install/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:17:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:149:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:154:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:154:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:140:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```
</details>

<details><summary>Output of `brew doctor`</summary>

```
Your system is ready to brew.
```
</details>

<details><summary>Output of `brew cask doctor`</summary>

```sh
==> Homebrew-Cask Version
Homebrew-Cask 1.2.1
caskroom/homebrew-cask (git revision 33118; last commit 2017-05-24)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (13 files, 663.4MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3617 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services (0 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Environment Variables
LANG="en_US.UTF-8"
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/usr/local/bin/bash"
```
</details>

**Comment by miccal** [comment]
I cannot seem to find a `url` for `paste.rb` using the current formatting - I can only find
```
https://cdn.hockeyapp.net/production/app/builds/016/122/272/original/3ab3bf9b674e06571448e75f59ca10e5/Paste.app.zip
```

**Comment by vitorgalvao** [comment]
> But am I correct in my understanding that the HockeyApp account being used is something you all control as infrastructure?

You are not. We don’t control any source from where we install (unless you count maintainer-made apps, but that’s a different matter).

**Comment by vitorgalvao** [comment]
Best I could find: https://github.com/caskroom/homebrew-cask/pull/34970.
