### ISSUE TITLE
Error: Operation not permitted - (/usr/local/Caskroom/android-ndk/15, /usr/local/opt/android-ndk/15)

### ISSUE THREAD

**Issue by ghazel** [caskroom/homebrew-cask#35606]
#### General troubleshooting steps

- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Cannot install `android-ndk`.

#### Output of your command with `--verbose --debug`

```
$ brew cask install android-ndk --verbose --debug
==> Hbc::Installer#install
==> Printing caveats
==> Caveats
You may want to add to your profile:
   'export ANDROID_NDK_HOME="/usr/local/opt/android-ndk"'

==> Hbc::Installer#fetch
==> Downloading
==> Downloading https://dl.google.com/android/repository/android-ndk-r15-darwin-x86_64.zip
Already downloaded: /Users/ghazel/Library/Caches/Homebrew/Cask/android-ndk--15.zip
==> Downloaded to -> /Users/ghazel/Library/Caches/Homebrew/Cask/android-ndk--15.zip
==> Verifying download
==> Determining which verifications to run for Cask android-ndk
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask android-ndk
==> SHA256 checksums match
==> Installing Cask android-ndk
==> Hbc::Installer#stage
==> Extracting primary container
==> Determining which containers to use based on filetype
==> Checking container class Hbc::Container::Pkg
==> Checking container class Hbc::Container::Ttf
==> Checking container class Hbc::Container::Otf
==> Checking container class Hbc::Container::Air
==> Checking container class Hbc::Container::Cab
==> Checking container class Hbc::Container::Dmg
==> Executing: ["/usr/bin/hdiutil", "imageinfo", "/Users/ghazel/Library/Caches/Homebrew/Cask/android-ndk--15.zip"]
==> Checking container class Hbc::Container::SevenZip
==> Checking container class Hbc::Container::Sit
==> Checking container class Hbc::Container::Rar
==> Checking container class Hbc::Container::Zip
==> Using container class Hbc::Container::Zip for /Users/ghazel/Library/Caches/Homebrew/Cask/android-ndk--15.zip
==> Executing: ["/usr/bin/ditto", "-x", "-k", "--", "/Users/ghazel/Library/Caches/Homebrew/Cask/android-ndk--15.zip", "/var/folders/j2/dd5yz7192zscrkpt4hlqyj_40000gn/T/d20170616-5371-1qcbw24"]
==> Creating metadata directory /usr/local/Caskroom/android-ndk/.metadata/15/20170616080339.969.
==> Creating metadata subdirectory /usr/local/Caskroom/android-ndk/.metadata/15/20170616080339.969/Casks.
==> Installing artifacts
==> Determining which artifacts are present in Cask android-ndk
==> 2 artifact/s defined
#<Hbc::Artifact::PreflightBlock:0x007ff2d3942f00>
#<Hbc::Artifact::Binary:0x007ff2d3942dc0>
==> Installing artifact of class Hbc::Artifact::PreflightBlock
==> Purging files for version 15 of Cask android-ndk
Error: Operation not permitted - (/usr/local/Caskroom/android-ndk/15, /usr/local/opt/android-ndk/15)
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask#reporting-bugs
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:310:in `link'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:310:in `block in ln'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1572:in `fu_each_src_dest0'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:308:in `ln'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:23:in `block (2 levels) in load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_flight_block.rb:35:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_flight_block.rb:35:in `block in abstract_phase'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/set.rb:232:in `each_key'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/set.rb:232:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_flight_block.rb:34:in `abstract_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_flight_block.rb:24:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:185:in `block in install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:177:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:177:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:106:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:23:in `block in install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:68:in `block in casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:66:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:66:in `casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:17:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:17:in `install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:13:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:179:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:179:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```

#### Output of `brew cask doctor`

```
$ brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask >1.2.0 (no git repository)
caskroom/homebrew-cask (git revision ebe05; last commit 2017-06-16)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (5 files, 1.6GB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3637 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Environment Variables
LANG="en_US.UTF-8"
PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

**Comment by commitay** [comment]
What's the output of `ls -lah /usr/local/opt/android-ndk`?

**Comment by ghazel** [comment]
```
$ ls -lah /usr/local/opt/android-ndk
total 0
drwxr-xr-x   2 ghazel  admin    68B Jun 16 03:04 .
drwxrwxr-x  28 ghazel  admin   952B Jun 16 01:53 ..
```

**Comment by commitay** [comment]
Run `rm -rf /usr/local/opt/android-ndk/` then try installing again.

**Comment by ghazel** [comment]
I did not make that directory manually. This seems to be reproducible if you do:

```
brew cask install android-sdk
brew cask uninstall android-sdk
brew cask install android-sdk
```

I tried removing the directory, but that results in what appears to be an incorrect installation:

```
$ ls -lah /usr/local/opt/android-ndk/
total 8
drwxr-xr-x   4 ghazel  admin   136B Jun 16 03:07 .
drwxrwxr-x  28 ghazel  admin   952B Jun 16 03:07 ..
drwxr-xr-x  20 ghazel  staff   680B Jun  7 02:00 android-ndk-r15
-rwxr-xr-x@  1 ghazel  admin   157B Jun 16 03:07 ndk_exec.sh
```

This is different from previous installations I had, where `/usr/local/opt/android-ndk` was a symlink to the current android-ndk version.

**Comment by ghazel** [comment]
(although `android-sdk` seems to symlink to `/usr/local/share/android-sdk` now, so if the ndk moved to `/usr/local/share/android-ndk` that would be consistent)

**Comment by commitay** [comment]
I was able to reproduce this error with:
```
brew cask install android-ndk
brew cask uninstall android-ndk
```
but `rm -rf /usr/local/opt/android-ndk/` fixes it for me.
```
brew cask install android-ndk --verbose --debug
==> Hbc::Installer#install
==> Printing caveats
==> Caveats
You may want to add to your profile:
   'export ANDROID_NDK_HOME="/usr/local/opt/android-ndk"'

==> Hbc::Installer#fetch
==> Downloading
==> Downloading https://dl.google.com/android/repository/android-ndk-r15-darwin-x86_64.zip
Already downloaded: /Users/commitay/Library/Caches/Homebrew/Cask/android-ndk--15.zip
==> Downloaded to -> /Users/commitay/Library/Caches/Homebrew/Cask/android-ndk--15.zip
==> Verifying download
==> Determining which verifications to run for Cask android-ndk
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask android-ndk
==> SHA256 checksums match
==> Installing Cask android-ndk
==> Hbc::Installer#stage
==> Extracting primary container
==> Determining which containers to use based on filetype
==> Checking container class Hbc::Container::Pkg
==> Checking container class Hbc::Container::Ttf
==> Checking container class Hbc::Container::Otf
==> Checking container class Hbc::Container::Air
==> Checking container class Hbc::Container::Cab
==> Checking container class Hbc::Container::Dmg
==> Executing: ["/usr/bin/hdiutil", "imageinfo", "/Users/commitay/Library/Caches/Homebrew/Cask/android-ndk--15.zip"]
==> Checking container class Hbc::Container::SevenZip
==> Checking container class Hbc::Container::Sit
==> Checking container class Hbc::Container::Rar
==> Checking container class Hbc::Container::Zip
==> Using container class Hbc::Container::Zip for /Users/commitay/Library/Caches/Homebrew/Cask/android-ndk--15.zip
==> Executing: ["/usr/bin/ditto", "-x", "-k", "--", "/Users/commitay/Library/Caches/Homebrew/Cask/android-ndk--15.zip", "/var/folders/t3/9rpghbf50b59xf2z1fb0d8b40000gn/T/d20170616-3104-1kcabok"]
==> Creating metadata directory /usr/local/Caskroom/android-ndk/.metadata/15/20170616100152.803.
==> Creating metadata subdirectory /usr/local/Caskroom/android-ndk/.metadata/15/20170616100152.803/Casks.
==> Installing artifacts
==> Determining which artifacts are present in Cask android-ndk
==> 2 artifact/s defined
#<Hbc::Artifact::PreflightBlock:0x007fc03a141d18>
#<Hbc::Artifact::Binary:0x007fc03a141c50>
==> Installing artifact of class Hbc::Artifact::PreflightBlock
==> Installing artifact of class Hbc::Artifact::Binary
==> Linking Binary 'ndk_exec.sh' to '/usr/local/bin/ndk-build'.
==> Executing: ["/bin/ln", "-h", "-f", "-s", "--", "/usr/local/Caskroom/android-ndk/15/ndk_exec.sh", "/usr/local/bin/ndk-build"]
==> Adding com.apple.metadata:kMDItemAlternateNames metadata
==> Executing: ["/usr/bin/xattr", "-p", "com.apple.metadata:kMDItemAlternateNames", "/usr/local/Caskroom/android-ndk/15/ndk_exec.sh"]
==> Existing metadata is: ''
==> Executing: ["/bin/chmod", "--", "u+rw", "/usr/local/Caskroom/android-ndk/15/ndk_exec.sh", "/usr/local/Caskroom/android-ndk/15/ndk_exec.sh"]
==> Executing: ["/usr/bin/xattr", "-w", "com.apple.metadata:kMDItemAlternateNames", "(\\\"ndk-build\\\")", "/usr/local/Caskroom/android-ndk/15/ndk_exec.sh"]
==> Linking Binary 'ndk_exec.sh' to '/usr/local/bin/ndk-depends'.
==> Executing: ["/bin/ln", "-h", "-f", "-s", "--", "/usr/local/Caskroom/android-ndk/15/ndk_exec.sh", "/usr/local/bin/ndk-depends"]
==> Adding com.apple.metadata:kMDItemAlternateNames metadata
==> Executing: ["/usr/bin/xattr", "-p", "com.apple.metadata:kMDItemAlternateNames", "/usr/local/Caskroom/android-ndk/15/ndk_exec.sh"]
==> Existing metadata is: '"ndk-build"
'
==> Executing: ["/bin/chmod", "--", "u+rw", "/usr/local/Caskroom/android-ndk/15/ndk_exec.sh", "/usr/local/Caskroom/android-ndk/15/ndk_exec.sh"]
==> Executing: ["/usr/bin/xattr", "-w", "com.apple.metadata:kMDItemAlternateNames", "(\\\"ndk-build\\\"\\n, \\\"ndk-depends\\\")", "/usr/local/Caskroom/android-ndk/15/ndk_exec.sh"]
==> Linking Binary 'ndk_exec.sh' to '/usr/local/bin/ndk-gdb'.
==> Executing: ["/bin/ln", "-h", "-f", "-s", "--", "/usr/local/Caskroom/android-ndk/15/ndk_exec.sh", "/usr/local/bin/ndk-gdb"]
==> Adding com.apple.metadata:kMDItemAlternateNames metadata
==> Executing: ["/usr/bin/xattr", "-p", "com.apple.metadata:kMDItemAlternateNames", "/usr/local/Caskroom/android-ndk/15/ndk_exec.sh"]
==> Existing metadata is: '("ndk-build"
, "ndk-depends")
'
==> Executing: ["/bin/chmod", "--", "u+rw", "/usr/local/Caskroom/android-ndk/15/ndk_exec.sh", "/usr/local/Caskroom/android-ndk/15/ndk_exec.sh"]
==> Executing: ["/usr/bin/xattr", "-w", "com.apple.metadata:kMDItemAlternateNames", "((\\\"ndk-build\\\"\\n, \\\"ndk-depends\\\")\\n, \\\"ndk-gdb\\\")", "/usr/local/Caskroom/android-ndk/15/ndk_exec.sh"]
==> Linking Binary 'ndk_exec.sh' to '/usr/local/bin/ndk-stack'.
==> Executing: ["/bin/ln", "-h", "-f", "-s", "--", "/usr/local/Caskroom/android-ndk/15/ndk_exec.sh", "/usr/local/bin/ndk-stack"]
==> Adding com.apple.metadata:kMDItemAlternateNames metadata
==> Executing: ["/usr/bin/xattr", "-p", "com.apple.metadata:kMDItemAlternateNames", "/usr/local/Caskroom/android-ndk/15/ndk_exec.sh"]
==> Existing metadata is: '(("ndk-build"
, "ndk-depends")
, "ndk-gdb")
'
==> Executing: ["/bin/chmod", "--", "u+rw", "/usr/local/Caskroom/android-ndk/15/ndk_exec.sh", "/usr/local/Caskroom/android-ndk/15/ndk_exec.sh"]
==> Executing: ["/usr/bin/xattr", "-w", "com.apple.metadata:kMDItemAlternateNames", "(((\\\"ndk-build\\\"\\n, \\\"ndk-depends\\\")\\n, \\\"ndk-gdb\\\")\\n, \\\"ndk-stack\\\")", "/usr/local/Caskroom/android-ndk/15/ndk_exec.sh"]
==> Linking Binary 'ndk_exec.sh' to '/usr/local/bin/ndk-which'.
==> Executing: ["/bin/ln", "-h", "-f", "-s", "--", "/usr/local/Caskroom/android-ndk/15/ndk_exec.sh", "/usr/local/bin/ndk-which"]
==> Adding com.apple.metadata:kMDItemAlternateNames metadata
==> Executing: ["/usr/bin/xattr", "-p", "com.apple.metadata:kMDItemAlternateNames", "/usr/local/Caskroom/android-ndk/15/ndk_exec.sh"]
==> Existing metadata is: '((("ndk-build"
, "ndk-depends")
, "ndk-gdb")
, "ndk-stack")
'
==> Executing: ["/bin/chmod", "--", "u+rw", "/usr/local/Caskroom/android-ndk/15/ndk_exec.sh", "/usr/local/Caskroom/android-ndk/15/ndk_exec.sh"]
==> Executing: ["/usr/bin/xattr", "-w", "com.apple.metadata:kMDItemAlternateNames", "((((\\\"ndk-build\\\"\\n, \\\"ndk-depends\\\")\\n, \\\"ndk-gdb\\\")\\n, \\\"ndk-stack\\\")\\n, \\\"ndk-which\\\")", "/usr/local/Caskroom/android-ndk/15/ndk_exec.sh"]
🍺  android-ndk was successfully installed!
```

**Comment by ghazel** [comment]
After `rm` It installs, yes, but `/usr/local/opt/android-ndk` looks wrong. I would expect it to be a symlink to `../Caskroom/android-ndk/15/`, instead it appears to be a hardlink to `/usr/local/Caskroom/android-ndk/15` which has `android-ndk-r15` as a subdirectory.

**Comment by commitay** [comment]
Try this: 
> https://raw.githubusercontent.com/commitay/homebrew-cask/03c79bb9b18850c1d042434f07c6095e9612d368/Casks/android-ndk.rb

```
brew cask install https://raw.githubusercontent.com/commitay/homebrew-cask/03c79bb9b18850c1d042434f07c6095e9612d368/Casks/android-ndk.rb
```

**Comment by ghazel** [comment]
Works great!

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/35609
