### ISSUE TITLE
Uninstall java cask failing

### ISSUE THREAD

**Issue by dojoteef** [caskroom/homebrew-cask#35665]
#### General troubleshooting steps

- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Trying to uninstall java, but it fails. It says it may require elevated privileges, but never actually asks for my password. Tried all of the above troubleshooting steps. Even restarted the computer (after trying `sudo -k`) to ensure there could be no credential caching issue.

#### Output of your command with `--verbose --debug`

```
brew cask uninstall java --verbose --debug
==> Uninstalling Cask java
==> Uninstalling Cask java
==> Un-installing artifacts
==> Determining which artifacts are present in Cask java
==> 4 artifact/s defined
#<Hbc::Artifact::Uninstall:0x007fc1af5f7df0>
#<Hbc::Artifact::Pkg:0x007fc1af5f7da0>
#<Hbc::Artifact::PostflightBlock:0x007fc1af5f7d28>
#<Hbc::Artifact::Zap:0x007fc1af5f7cd8>
==> Un-installing artifact of class Hbc::Artifact::Uninstall
==> Running uninstall process for java; your password may be necessary
==> Removing launchctl service com.oracle.java.Helper-Tool
==> Executing: ["/bin/launchctl", "list", "com.oracle.java.Helper-Tool"]
==> Executing: ["/bin/launchctl", "remove", "com.oracle.java.Helper-Tool"]
==> Not privileged to remove service.
Error: Command failed to execute!

==> Failed command:
/bin/launchctl remove com.oracle.java.Helper-Tool

==> Standard Output of failed command:


==> Standard Error of failed command:
Not privileged to remove service.


==> Exit status of failed command:
#<Process::Status: pid 2524 exit 1>
Error: Uninstall incomplete.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:12:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```

#### Output of `brew cask doctor`

```
brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.2.3-25-gb05545a3b
caskroom/homebrew-cask (git revision 857b7; last commit 2017-06-18)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (9 files, 646.6MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3639 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-fonts (1106 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Environment Variables
LANG="en_US.UTF-8"
PATH="/usr/local/bin:~/.dotfiles/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:~/.fzf/bin:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/cmd:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/usr/local/bin/bash"
```

**Comment by commitay** [comment]
This looks like it is already running as privileged:
```
==> Executing: ["/bin/launchctl", "list", "com.oracle.java.Helper-Tool"]
==> Executing: ["/bin/launchctl", "remove", "com.oracle.java.Helper-Tool"]
```
Should be:
```
==> Executing: ["/usr/bin/sudo", "-E", "--", "/bin/launchctl", "list", "com.oracle.java.Helper-Tool"]
==> Executing: ["/usr/bin/sudo", "-E", "--", "/bin/launchctl", "remove", "com.oracle.java.Helper-Tool"]
```
____
Can you please try:
```
brew cask uninstall java --force --verbose --debug
```

And if that doesn't work:
```
brew cask install java --force

brew cask uninstall java --verbose --debug
```

Both `install` and `uninstall` should prompt you for a password. If they don't I suspect that it is an issue with you setup.

**Comment by dojoteef** [comment]
Note I executed the commands in the order you provided in one login session of the bash shell.

Output of `brew cask uninstall java --force --verbose --debug` (which **did not** ask for password):

```
brew cask uninstall java --force --verbose --debug
==> Uninstalling Cask java
==> Uninstalling Cask java
==> Un-installing artifacts
==> Determining which artifacts are present in Cask java
==> 4 artifact/s defined
#<Hbc::Artifact::Uninstall:0x007f9099dc4598>
#<Hbc::Artifact::Pkg:0x007f9099dc4548>
#<Hbc::Artifact::PostflightBlock:0x007f9099dc44f8>
#<Hbc::Artifact::Zap:0x007f9099dc44a8>
==> Un-installing artifact of class Hbc::Artifact::Uninstall
==> Running uninstall process for java; your password may be necessary
==> Removing launchctl service com.oracle.java.Helper-Tool
==> Executing: ["/bin/launchctl", "list", "com.oracle.java.Helper-Tool"]
==> Executing: ["/bin/launchctl", "remove", "com.oracle.java.Helper-Tool"]
==> Not privileged to remove service.
Error: Command failed to execute!

==> Failed command:
/bin/launchctl remove com.oracle.java.Helper-Tool

==> Standard Output of failed command:


==> Standard Error of failed command:
Not privileged to remove service.


==> Exit status of failed command:
#<Process::Status: pid 5285 exit 1>
Error: Uninstall incomplete.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:12:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```

Output of `brew cask install java --force` (which **did** ask for password):
```
brew cask install java --force
==> Caveats
This Cask makes minor modifications to the JRE to prevent issues with
packaged applications, as discussed here:

  https://bugs.eclipse.org/bugs/show_bug.cgi?id=411361

If your Java application still asks for JRE installation, you might need
to reboot or logout/login.

Installing this Cask means you have AGREED to the Oracle Binary Code
License Agreement for Java SE at

  https://www.oracle.com/technetwork/java/javase/terms/license/index.html

==> Downloading http://download.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jdk-8u131-macosx-x64.dmg
Already downloaded: /Users/nsa/Library/Caches/Homebrew/Cask/java--1.8.0_131-b11,d54c1d3a095b4ff2b6607d096fa80163.dmg
==> Verifying checksum for Cask java
==> Installing Cask java
==> Running installer for java; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
Password:
==> installer: Package name is JDK 8 Update 131
==> installer: Upgrading at base path /
==> installer: The upgrade was successful.
🍺  java was successfully installed!
```

Finally output of `brew cask uninstall java --verbose --debug` (which **did not** ask for a password):
```
rew cask uninstall java --verbose --debug
==> Uninstalling Cask java
==> Uninstalling Cask java
==> Un-installing artifacts
==> Determining which artifacts are present in Cask java
==> 4 artifact/s defined
#<Hbc::Artifact::Uninstall:0x007f8bf7dabe18>
#<Hbc::Artifact::Pkg:0x007f8bf7dabdc8>
#<Hbc::Artifact::PostflightBlock:0x007f8bf7dabd50>
#<Hbc::Artifact::Zap:0x007f8bf7dabd00>
==> Un-installing artifact of class Hbc::Artifact::Uninstall
==> Running uninstall process for java; your password may be necessary
==> Removing launchctl service com.oracle.java.Helper-Tool
==> Executing: ["/bin/launchctl", "list", "com.oracle.java.Helper-Tool"]
==> Executing: ["/bin/launchctl", "remove", "com.oracle.java.Helper-Tool"]
==> Not privileged to remove service.
Error: Command failed to execute!

==> Failed command:
/bin/launchctl remove com.oracle.java.Helper-Tool

==> Standard Output of failed command:


==> Standard Error of failed command:
Not privileged to remove service.


==> Exit status of failed command:
#<Process::Status: pid 5847 exit 1>
Error: Uninstall incomplete.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:12:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```

**Comment by commitay** [comment]
What happen if you run the command manually?
```
sudo launchctl remove com.oracle.java.Helper-Tool
```

**Comment by dojoteef** [comment]
It seems to succeed without error:

```
> sudo launchctl remove com.oracle.java.Helper-Tool
Password:
```

Subsequently, if I try to uninstall java again it fails, but at least it sees that some commands need sudo:

```
> brew cask uninstall java --verbose --debug
==> Uninstalling Cask java
==> Uninstalling Cask java
==> Un-installing artifacts
==> Determining which artifacts are present in Cask java
==> 4 artifact/s defined
#<Hbc::Artifact::Uninstall:0x007fee40cdbd98>
#<Hbc::Artifact::Pkg:0x007fee40cdbd48>
#<Hbc::Artifact::PostflightBlock:0x007fee40cdbcd0>
#<Hbc::Artifact::Zap:0x007fee40cdbc58>
==> Un-installing artifact of class Hbc::Artifact::Uninstall
==> Running uninstall process for java; your password may be necessary
==> Removing launchctl service com.oracle.java.Helper-Tool
==> Executing: ["/bin/launchctl", "list", "com.oracle.java.Helper-Tool"]
==> Executing: ["/usr/bin/sudo", "-E", "--", "/bin/launchctl", "list", "com.oracle.java.Helper-Tool"]
==> Executing: ["/usr/bin/sudo", "-E", "--", "/bin/rm", "-f", "--", "/Library/LaunchDaemons/com.oracle.java.Helper-Tool.plist"]
==> Removing launchctl service com.oracle.java.Java-Updater
==> Executing: ["/bin/launchctl", "list", "com.oracle.java.Java-Updater"]
==> Executing: ["/bin/launchctl", "remove", "com.oracle.java.Java-Updater"]
==> Not privileged to remove service.
Error: Command failed to execute!

==> Failed command:
/bin/launchctl remove com.oracle.java.Java-Updater

==> Standard Output of failed command:


==> Standard Error of failed command:
Not privileged to remove service.


==> Exit status of failed command:
#<Process::Status: pid 8664 exit 1>
Error: Uninstall incomplete.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:12:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```

**Comment by commitay** [comment]
Do the same for the next one (`java` only has two), I'd like to see if the uninstall if successful after it gets past `launchctl`.
```
sudo launchctl remove com.oracle.java.Java-Updater
```

**Comment by dojoteef** [comment]
It is successful after running `sudo launchctl remove com.oracle.java.Java-Updater`. The output is quite verbose; I'm happy to add it if that will help diagnose the issue.

**Comment by commitay** [comment]
> The output is quite verbose; I'm happy to add it if that will help diagnose the issue.

Thank you for offering but it is not needed.

**Comment by commitay** [comment]
Would you mind posting the output of `brew config`, I'm curious as to if this was something specific to your setup?

**Comment by dojoteef** [comment]
```
> brew config
HOMEBREW_VERSION: 1.2.3-25-gb05545a3b
ORIGIN: https://github.com/Homebrew/brew
HEAD: b05545a3bf5e22bcf845d0c2f58cae745431c98c
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c680634dae71484bce0a4fe9972b54521682cddd
Core tap last commit: 3 days ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.11.0 => /usr/local/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.24.0_1/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.0/bin/ruby
Java: N/A
macOS: 10.12.5-x86_64
Xcode: N/A
CLT: 8.3.2.0.1.1492020469
X11: 2.7.11 => /opt/X11
```

**Comment by commitay** [comment]
Thank you.
