### ISSUE TITLE
audit for free-telly: fails

### ISSUE THREAD

**Issue by jprokos** [caskroom/homebrew-cask#35929]
#### Description of issue

running brew cask audit free-telly results in a failed response.

```
audit for free-telly: failed
 - exception while auditing free-telly: undefined method `[]' for nil:NilClass
Error: audit failed for casks: free-telly
```

#### Output of your command with `--verbose --debug`

```
$ brew cask audit free-telly --verbose
Warning: Calling `brew cask` with the `--caskroom` flag is deprecated and will be disabled on 2017-10-31!
There is no replacement.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/options.rb:53:in `call'

audit for free-telly: failed
 - exception while auditing free-telly: undefined method `[]' for nil:NilClass
Error: audit failed for casks: free-telly
Error: Kernel.exit
```

```
$ brew cask audit free-telly --debug
Warning: Calling `brew cask` with the `--caskroom` flag is deprecated and will be disabled on 2017-10-31!
There is no replacement.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/options.rb:53:in `call'

==> Auditing Cask free-telly
==> Auditing required stanzas
==> Verifying version :latest does not appear as a string ('latest')
==> Verifying version does not contain '/'
==> Verifying sha256 :no_check with version :latest
==> Verifying sha256 string is a legal SHA-256 digest
==> Verifying sha256 is not a known invalid value
==> Auditing URL format
==> undefined method `[]' for nil:NilClass
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:24:in `block (2 levels) in load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/url.rb:14:in `call'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/url.rb:14:in `block in from'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/dsl/stanza_proxy.rb:8:in `block in once'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/dsl/stanza_proxy.rb:21:in `call'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/dsl/stanza_proxy.rb:21:in `to_s'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/audit.rb:188:in `bad_url_format?'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/audit.rb:193:in `bad_sourceforge_url?'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/audit.rb:180:in `check_download_url_format'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/audit.rb:175:in `check_url'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/audit.rb:30:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/auditor.rb:56:in `audit_cask_instance'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/auditor.rb:28:in `audit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/auditor.rb:4:in `audit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/audit.rb:21:in `audit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/audit.rb:13:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:68:in `block in casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:66:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:66:in `casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/audit.rb:13:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/audit.rb:13:in `reject'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/audit.rb:13:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
audit for free-telly: failed
 - exception while auditing free-telly: undefined method `[]' for nil:NilClass
Error: audit failed for casks: free-telly
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/audit.rb:16:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'

```

#### Output of `brew cask doctor`

```
$ brew cask doctor
Warning: Calling `brew cask` with the `--caskroom` flag is deprecated and will be disabled on 2017-10-31!
There is no replacement.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/options.rb:53:in `call'

==> Homebrew-Cask Version
Homebrew-Cask >1.2.0 (no git repository)
caskroom/homebrew-cask (git revision 111a1; last commit 2017-06-27)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3648 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Environment Variables
LANG="en_US.UTF-8"
PATH="/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/homebrew/bin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"

```

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/35933
