### ISSUE TITLE
caskroom/cask/android-sdk fails to install behind a proxy

### ISSUE THREAD

**Issue by kwv** [caskroom/homebrew-cask#35960]
#### General troubleshooting steps

- [*] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [*] None of the templates was appropriate for my issue, or I’m not sure.
- [*] I ran `brew update-reset && brew update` and retried my command.
- [*] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [*] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

https://github.com/caskroom/homebrew-cask/blob/master/Casks/android-sdk.rb#L60

#### Description of issue

caskroom/cask/android-sdk fails to install behind a proxy.  sdkmanager does not respect environment variables and requires them inline
https://developer.android.com/studio/command-line/sdkmanager.html#options

#### Output of your command with `--verbose --debug`

```
$ brew install --verbose --debug caskroom/cask/android-sdk
==> brew cask install caskroom/cask/android-sdk --debug --verbose
/usr/local/bin/brew cask install caskroom/cask/android-sdk --debug --verbose
==> Hbc::Installer#install
==> Printing caveats
==> Caveats
We will install android-sdk-tools, platform-tools, and build-tools for you.
You can control android sdk packages via the sdkmanager command.
You may want to add to your profile:
  'export ANDROID_SDK_ROOT=/usr/local/share/android-sdk'

This operation may take up to 10 minutes depending on your internet connection.
Please, be patient.

==> Hbc::Installer#fetch
==> Downloading
==> Downloading https://dl.google.com/android/repository/sdk-tools-darwin-3859397.zip
Already downloaded: /Users/uspsbuilduser/Library/Caches/Homebrew/Cask/android-sdk--3859397.zip
==> Downloaded to -> /Users/uspsbuilduser/Library/Caches/Homebrew/Cask/android-sdk--3859397.zip
==> Verifying download
==> Determining which verifications to run for Cask android-sdk
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask android-sdk
==> SHA256 checksums match
==> Installing Cask android-sdk
==> Hbc::Installer#stage
==> Extracting primary container
==> Determining which containers to use based on filetype
==> Checking container class Hbc::Container::Pkg
==> Checking container class Hbc::Container::Ttf
==> Checking container class Hbc::Container::Otf
==> Checking container class Hbc::Container::Air
==> Checking container class Hbc::Container::Cab
==> Checking container class Hbc::Container::Dmg
==> Executing: ["/usr/bin/hdiutil", "imageinfo", "/Users/uspsbuilduser/Library/Caches/Homebrew/Cask/android-sdk--3859397.zip"]
==> Checking container class Hbc::Container::SevenZip
==> Checking container class Hbc::Container::Sit
==> Checking container class Hbc::Container::Rar
==> Checking container class Hbc::Container::Zip
==> Using container class Hbc::Container::Zip for /Users/uspsbuilduser/Library/Caches/Homebrew/Cask/android-sdk--3859397.zip
==> Executing: ["/usr/bin/ditto", "-x", "-k", "--", "/Users/uspsbuilduser/Library/Caches/Homebrew/Cask/android-sdk--3859397.zip", "/var/folders/x8/cpj1_sfx60g462dqkyw_h3_00000gn/T/d20170628-2192-10093lg"]
==> Creating metadata directory /usr/local/Caskroom/android-sdk/.metadata/3859397/20170628202646.791.
==> Creating metadata subdirectory /usr/local/Caskroom/android-sdk/.metadata/3859397/20170628202646.791/Casks.
==> Installing artifacts
==> Determining which artifacts are present in Cask android-sdk
==> 3 artifact/s defined
#<Hbc::Artifact::PreflightBlock:0x007fb81590d650>
#<Hbc::Artifact::Binary:0x007fb81590d588>
#<Hbc::Artifact::PostflightBlock:0x007fb81590d510>
==> Installing artifact of class Hbc::Artifact::PreflightBlock
==> Executing: ["/usr/local/Caskroom/android-sdk/3859397/tools/bin/sdkmanager", "tools", "platform-tools", "build-tools;26.0.0"]
==> Warning: java.net.ConnectException: Connection refused
==> Warning: Failed to download any source lists!
==> Warning: Failed to find package tools
==> Purging files for version 3859397 of Cask android-sdk
Error: Command failed to execute!

==> Failed command:
/usr/local/Caskroom/android-sdk/3859397/tools/bin/sdkmanager tools platform-tools build-tools;26.0.0

==> Standard Output of failed command:


==> Standard Error of failed command:
Warning: java.net.ConnectException: Connection refused
Warning: Failed to download any source lists!
Warning: Failed to find package tools


==> Exit status of failed command:
#<Process::Status: pid 2347 exit 1>
Error: nothing to install
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:16:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:101:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:101:in `<main>'
```

#### Output of `brew cask doctor`

```
$ brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.2.3
caskroom/homebrew-cask (git revision 17d80; last commit 2017-06-28)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (1 files, 82.2MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3648 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Server.app/Contents/ServerRoot/usr/bin:/Applications/Server.app/Contents/ServerRoot/usr/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

**Comment by commitay** [comment]
> sdkmanager does not respect environment variables and requires them inline

Unfortunately I don't think there is anything we can do to fix this. We can't add proxy options to `system_command "#{staged_path}/tools/bin/sdkmanager"` and we don't support install flags.

**Comment by kwv** [comment]
I've never dug in before.   Is it possible to skip the preflight step ?  Or create a new recipe that omits it? For proxied users, at least then there would be a work around to manually install the SDK components.  

I hate having to install Android Studio to get the SDK on my build server.

**Comment by commitay** [comment]
> Is it possible to skip the preflight step ?

No.

> Or create a new recipe that omits it? 

Removing the `preflight` means all the `binary` stanzas need to be removed and the build tools are not downloaded. Basically we would just be downloading and extracting the `zip`.

I would suggest [creating your own tap](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md) for `android-sdk` which would allow to you add proxy options to the cask.

**Comment by silkimen** [comment]
Hi guys,

I had the same problem, so I wrote my own cask definition, which is respecting the env variable "http_proxy".

You can install it by running `brew cask install silkimen/caskroom/android-sdk`

And maybe someone can check my [source code](https://github.com/silkimen/homebrew-caskroom/commit/c921fe675c8de70a98a70a9aadb0c86c81c2d078)? It's the first time I'm writing ruby code.

**Comment by schiller256** [comment]
It is possible to merge the fix from silkimen?

**Comment by phaniteja** [comment]
@silkimen Thanks for the solution. I had to fix the **## javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target** issue by adding the certificate to Java home using the below command.

keytool -import -v -trustcacerts -alias XXX -file YYY.crt -keystore $JAVA_HOME/jre/lib/security/cacerts -keypass changeit -storepass changeit
