### ISSUE TITLE
Skype fails to install

### ISSUE THREAD

**Issue by marktopper** [caskroom/homebrew-cask#35975]
#### General troubleshooting steps

- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Cannot install Skype using `brew cask install skype`.

#### Output of your command with `--verbose --debug`

```
$ brew cask install skype --verbose --debug
==> Hbc::Installer#install
==> Printing caveats
==> Hbc::Installer#fetch
==> Downloading
==> Downloading https://www.skype.com/go/getskype-macosx.dmg
==> Calling curl with args ["https://www.skype.com/go/getskype-macosx.dmg", "-C", "0", "-o", "#<Pathname:/Users/mark/Library/Caches/Homebrew/Cask/skype--latest.dmg.incomplete>"]
/usr/bin/curl --remote-time --location --user-agent Homebrew/1.2.3 (Macintosh; Intel Mac OS X 10.12.5) curl/7.51.0 --fail https://www.skype.com/go/getskype-macosx.dmg -C 0 -o /Users/mark/Library/Caches/Homebrew/Cask/skype--latest.dmg.incomplete
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: www.skype.com
Error: Download failed on Cask 'skype' with message: Download failed: https://www.skype.com/go/getskype-macosx.dmg
Error: nothing to install
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:16:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:101:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:101:in `<main>'
```

#### Output of `brew cask doctor`

```
$ brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.2.3
caskroom/homebrew-cask (git revision 6e03; last commit 2017-06-29)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (4 files, 131.9MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3651 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (161 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Environment Variables
LANG="da_DK.UTF-8"
PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

**Comment by commitay** [comment]
Please fill out the template.

**Comment by marktopper** [comment]
I clicked enter too soon, my bad. I have filled it out.

**Comment by commitay** [comment]
The checklist is missing.

**Comment by commitay** [comment]
Thank you.

**Comment by commitay** [comment]
Cannot reproduce.
```
$ brew cask install skype
==> Downloading https://www.skype.com/go/getskype-macosx.dmg
######################################################################## 100.0%
==> No checksum defined for Cask skype, skipping verification
==> Installing Cask skype
==> Moving App 'Skype.app' to '/Applications/Skype.app'.
🍺  skype was successfully installed!
```

> 0curl: (6) Could not resolve host: www.skype.com

Can you connect to www.skype.com ?

**Comment by marktopper** [comment]
That was the problem, thanks @commitay.
