### ISSUE TITLE
Installation of wd-my-cloud fails

### ISSUE THREAD

**Issue by marktopper** [caskroom/homebrew-cask#35981]
#### General troubleshooting steps

- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

When I try to install `wd-my-cloud`, it fails because their certificate is not trusted.
It however says `Certificate used to sign package is not trusted. Use -allowUntrusted to override.`, but when I try adding running `brew cask install wd-my-cloud -allowUntrusted`, I get the following error:
```
$ brew cask install wd-my-cloud -allowUntrusted
Error: invalid option: -allowUntrusted
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/options.rb:60:in `process_arguments'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:42:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:8:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `new'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```

#### Output of your command with `--verbose --debug`

```
$ brew cask install wd-my-cloud --verbose --debug
==> Hbc::Installer#install
==> Printing caveats
==> Hbc::Installer#fetch
==> Downloading
==> Downloading http://download.wdc.com/nas/WDMyCloud_mac.dmg
==> Calling curl with args ["http://download.wdc.com/nas/WDMyCloud_mac.dmg", "-C", "0", "-o", "#<Pathname:/Users/mark/Library/Caches/Homebrew/Cask/wd-my-cloud--latest.dmg.incomplete>"]
/usr/bin/curl --remote-time --location --user-agent Homebrew/1.X.Y (Macintosh; Intel Mac OS X 10.12.5) curl/7.51.0 --fail http://download.wdc.com/nas/WDMyCloud_mac.dmg -C 0 -o /Users/mark/Library/Caches/Homebrew/Cask/wd-my-cloud--latest.dmg.incomplete
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 37.8M  100 37.8M    0     0  2181k      0  0:00:17  0:00:17 --:--:-- 3083k
==> Downloaded to -> /Users/mark/Library/Caches/Homebrew/Cask/wd-my-cloud--latest.dmg
==> Verifying download
==> Determining which verifications to run for Cask wd-my-cloud
==> Checking for verification class Hbc::Verify::Checksum
==> No checksum defined for Cask wd-my-cloud, skipping verification
==> 0 verifications defined
==> Installing Cask wd-my-cloud
==> Hbc::Installer#stage
==> Extracting primary container
==> Determining which containers to use based on filetype
==> Checking container class Hbc::Container::Pkg
==> Checking container class Hbc::Container::Ttf
==> Checking container class Hbc::Container::Otf
==> Checking container class Hbc::Container::Air
==> Checking container class Hbc::Container::Cab
==> Checking container class Hbc::Container::Dmg
==> Executing: ["/usr/bin/hdiutil", "imageinfo", "/Users/mark/Library/Caches/Homebrew/Cask/wd-my-cloud--latest.dmg"]
==> Using container class Hbc::Container::Dmg for /Users/mark/Library/Caches/Homebrew/Cask/wd-my-cloud--latest.dmg
==> Executing: ["/usr/bin/hdiutil", "mount", "-plist", "-nobrowse", "-readonly", "-noidme", "-mountrandom", "/tmp", "/Users/mark/Library/Caches/Homebrew/Cask/wd-my-cloud--latest.dmg"]
==> Executing: ["/usr/bin/mkbom", "-s", "-i", "/var/folders/hv/thh85pgn7416t8gtvx26ptz00000gn/T/20170629-28807-gduhp3.list", "--", "/var/folders/hv/thh85pgn7416t8gtvx26ptz00000gn/T/20170629-28807-iz6onb.bom"]
==> Executing: ["/usr/bin/ditto", "--bom", "/var/folders/hv/thh85pgn7416t8gtvx26ptz00000gn/T/20170629-28807-iz6onb.bom", "--", "/private/tmp/dmg.Nyq37X", "/usr/local/Caskroom/wd-my-cloud/latest"]
==> Executing: ["/usr/sbin/diskutil", "eject", "/private/tmp/dmg.Nyq37X"]
==> Creating metadata directory /usr/local/Caskroom/wd-my-cloud/.metadata/latest/20170629094335.519.
==> Creating metadata subdirectory /usr/local/Caskroom/wd-my-cloud/.metadata/latest/20170629094335.519/Casks.
==> Installing artifacts
==> Determining which artifacts are present in Cask wd-my-cloud
==> 2 artifact/s defined
#<Hbc::Artifact::Uninstall:0x007fdf8e09ad38>
#<Hbc::Artifact::Pkg:0x007fdf8e09ab80>
==> Installing artifact of class Hbc::Artifact::Pkg
==> Running installer for wd-my-cloud; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
==> Executing: ["/usr/bin/sudo", "-E", "--", "/usr/sbin/installer", "-pkg", "/usr/local/Caskroom/wd-my-cloud/latest/Install WD My Cloud.pkg", "-target", "/", "-verboseR"]
Password:
==> installer: Package name is WD My Cloud
==> installer: Certificate used to sign package is not trusted. Use -allowUntrusted to override.
==> Purging files for version latest of Cask wd-my-cloud
Error: Command failed to execute!

==> Failed command:
/usr/bin/sudo -E -- /usr/sbin/installer -pkg #<Pathname:/usr/local/Caskroom/wd-my-cloud/latest/Install WD My Cloud.pkg> -target / -verboseR

==> Standard Output of failed command:
installer: Package name is WD My Cloud
installer: Certificate used to sign package is not trusted. Use -allowUntrusted to override.


==> Standard Error of failed command:


==> Exit status of failed command:
#<Process::Status: pid 28962 exit 1>
Error: Install incomplete.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:13:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```

#### Output of `brew cask doctor`

```
$ brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask >1.2.0 (no git repository)
caskroom/homebrew-cask (git revision 453d1; last commit 2017-06-29)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (1 files, 37.9MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3651 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-drivers (99 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-fonts (1106 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (161 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Environment Variables
LANG="da_DK.UTF-8"
PATH="~/.composer/vendor/bin:~/bin:/bin:/opt/local/lib/postgresql83/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-drivers/pull/84
