### ISSUE TITLE
The download url of visual-paradigm-ce  is outdated

### ISSUE THREAD

**Issue by johncming** [caskroom/homebrew-cask#36042]
#### General troubleshooting steps

- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [ ] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

when brew cask install visual-paradigm-ce:

Error: Download failed on Cask 'visual-paradigm-ce' with message: Download failed: https://usa6.visual-paradigm.com/visual-paradigm/vpce14.1/20170601/Visual_Paradigm_CE_14_1_20170601_OSX_WithJRE.dmg

The download URL may be outdated.

The new URL is 

```
https://ca1.visual-paradigm.com/visual-paradigm/vpce14.1/20170606/Visual_Paradigm_CE_14_1_20170606_OSX_WithJRE.dmg
```

#### Output of your command with `--verbose --debug`

```
==> Hbc::Installer#install
==> Printing caveats
==> Hbc::Installer#fetch
==> Downloading
==> Downloading https://usa6.visual-paradigm.com/visual-paradigm/vpce14.1/20170601/Visual_Paradigm_CE_14_1_20170601_OSX_WithJRE.dmg
==> Calling curl with args ["https://usa6.visual-paradigm.com/visual-paradigm/vpce14.1/20170601/Visual_Paradigm_CE_14_1_20170601_OSX_WithJRE.dmg", "-C", "0", "-o", "#<Pathname:/Users/ming/Library/Caches/Homebrew/Cask/visual-paradigm-ce--14.1,20170601.dmg.incomplete>"]
/usr/bin/curl --remote-time --location --user-agent Homebrew/1.2.3-99-g0a5052141 (Macintosh; Intel Mac OS X 10.12.5) curl/7.51.0 --fail https://usa6.visual-paradigm.com/visual-paradigm/vpce14.1/20170601/Visual_Paradigm_CE_14_1_20170601_OSX_WithJRE.dmg -C 0 -o /Users/ming/Library/Caches/Homebrew/Cask/visual-paradigm-ce--14.1,20170601.dmg.incomplete
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'visual-paradigm-ce' with message: Download failed: https://usa6.visual-paradigm.com/visual-paradigm/vpce14.1/20170601/Visual_Paradigm_CE_14_1_20170601_OSX_WithJRE.dmg
Error: Install incomplete.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:13:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew-Cask Version
Homebrew-Cask 1.2.3-99-g0a5052141
caskroom/homebrew-cask (git revision f4454; last commit 2017-06-30)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (12 files, 919.5MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3651 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (161 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Environment Variables
LC_CTYPE="UTF-8"
PATH="~/.go/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/zsh"
```

**Comment by commitay** [comment]
> [Updating a Cask](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask)
```
# install and setup script - only needed once
brew install vitorgalvao/tiny-scripts/cask-repair
cask-repair --help

# use to update <outdated_cask>
cask-repair <outdated_cask>
```

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/36043
