### ISSUE TITLE
intel-power-gadget--3.0.7,553992 fails to install

### ISSUE THREAD

**Issue by BenjaminHCCarr** [caskroom/homebrew-cask#36156]
#### General troubleshooting steps

- [X] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [X] None of the templates was appropriate for my issue, or I’m not sure.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

intel-power-gadget--3.0.7,553992 fails to install
This was merged a few hours ago as caskroom/homebrew-cask#36139

#### Output of your command with `--verbose --debug`

```
tyr:~ benc$ brew cask reinstall intel-power-gadget --verbose --debug
==> Hbc::Installer#reinstall
==> Hbc::Installer#install
==> Printing caveats
==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://software.intel.com/file/553992/download
==> Calling curl with args ["https://software.intel.com/file/553992/download", "-C", 0, "-o", #<Pathname:/Users/benc/Library/Caches/Homebrew/Cask/intel-power-gadget--3.0.7,553992.incomplete>]
/usr/bin/curl --remote-time --location --user-agent Homebrew/1.2.4 (Macintosh; Intel Mac OS X 10.11.6) curl/7.43.0 --fail https://software.intel.com/file/553992/download -C 0 -o /Users/benc/Library/Caches/Homebrew/Cask/intel-power-gadget--3.0.7,553992.incomplete
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
100 5120k  100 5120k    0     0   674k      0  0:00:07  0:00:07 --:--:-- 1052k
==> Downloaded to -> /Users/benc/Library/Caches/Homebrew/Cask/intel-power-gadget--3.0.7,553992
==> Verifying download
==> Determining which verifications to run for Cask intel-power-gadget
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask intel-power-gadget
==> SHA256 checksums match
==> Installing Cask intel-power-gadget
==> Hbc::Installer#stage
==> Extracting primary container
==> Determining which containers to use based on filetype
==> Checking container class Hbc::Container::Pkg
==> Checking container class Hbc::Container::Ttf
==> Checking container class Hbc::Container::Otf
==> Checking container class Hbc::Container::Air
==> Checking container class Hbc::Container::Cab
==> Checking container class Hbc::Container::Dmg
==> Executing: ["/usr/bin/hdiutil", "imageinfo", "/Users/benc/Library/Caches/Homebrew/Cask/intel-power-gadget--3.0.7,553992"]
==> Checking container class Hbc::Container::SevenZip
==> Checking container class Hbc::Container::Sit
==> Checking container class Hbc::Container::Rar
==> Checking container class Hbc::Container::Zip
==> Checking container class Hbc::Container::Xar
==> Checking container class Hbc::Container::Tar
==> Checking container class Hbc::Container::Bzip2
==> Checking container class Hbc::Container::Gzip
==> Checking container class Hbc::Container::Lzma
==> Checking container class Hbc::Container::Xz
==> Checking container class Hbc::Container::Gpg
==> Checking container class Hbc::Container::Executable
==> Purging files for version 3.0.7,553992 of Cask intel-power-gadget
Error: Uh oh, could not figure out how to unpack '/Users/benc/Library/Caches/Homebrew/Cask/intel-power-gadget--3.0.7,553992'
Error: Install incomplete.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:13:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```

#### Output of `brew cask doctor`

```
tyr:~ benc$ brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.2.4
caskroom/homebrew-cask (git revision 7214f; last commit 2017-07-04)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (1 files, 5MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3654 casks)
/usr/local/Homebrew/Library/Taps/alehouse/homebrew-unofficial (40 casks)
/usr/local/Homebrew/Library/Taps/benjaminhccarr/homebrew-cask (8 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-drivers (100 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-fonts (1106 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (161 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin15
/Library/Ruby/Site/2.0.0/universal-darwin15
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15
==> Environment Variables
LANG="en_US.UTF-8"
PATH="/usr/local/opt/gettext/bin:/usr/local/opt/curl/bin:/usr/local/opt/qt/bin:/usr/local/bin:/usr/local/sbin:~/bin:/usr/local/opt/ccache/libexec:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Applications/Server.app/Contents/ServerRoot/usr/bin:/Applications/Server.app/Contents/ServerRoot/usr/sbin:/usr/local/m-cli:/usr/local/MacGPG2/bin:/Library/TeX/texbin:/Applications/Wireshark.app/Contents/MacOS:~/Documents/Projects/CAMEO/bin:~/Code/github/m-cli:/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask/developer/bin:/opt/metasploit-framework/bin:/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd:/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/cmd:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-aliases/cmd:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-command-not-found/cmd:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-dev-tools/cmd:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```
---
### File info:
```
tyr:~/Library/Caches/Homebrew/Cask benc$ file intel-power-gadget--3.0.7,553992 
intel-power-gadget--3.0.7,553992: x86 boot sector; partition 1: ID=0xee, starthead 254, startsector 1, 10239 sectors, extended partition table (last)	, code offset 0x0
```

**Comment by commitay** [comment]
Still has been an issue previously. https://github.com/caskroom/homebrew-cask/issues/3791

Forcing `container type` or `container nested` don't seems to work.

**Comment by commitay** [comment]
Please try:

> https://raw.githubusercontent.com/commitay/homebrew-cask/955375a288c3e65fd935d247d150286e9255639c/Casks/intel-power-gadget.rb

```
brew cask install https://raw.githubusercontent.com/commitay/homebrew-cask/955375a288c3e65fd935d247d150286e9255639c/Casks/intel-power-gadget.rb
```

**Comment by BenjaminHCCarr** [comment]
Thanks @commitay for the background, the registration mark seems superfluous in a package name, but hey "Intel." Thank you for the updated formula: caskroom/homebrew-cask#36161
