### ISSUE TITLE
brew cask zap - trash error 

### ISSUE THREAD

**Issue by commitay** [caskroom/homebrew-cask#36162]
#### General troubleshooting steps

- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

`brew cask zap` errors when trashing. Repeating the same `zap` succeeds.

#### Output of your command with `--verbose --debug`

```
brew cask zap musicbrainz-picard --verbose --debug
==> Zapping Cask musicbrainz-picard
==> Implied "brew cask uninstall musicbrainz-picard"
==> Un-installing artifacts
==> Determining which artifacts are present in Cask musicbrainz-picard
==> 2 artifact/s defined
#<Hbc::Artifact::App:0x007fcbec8260d0>
#<Hbc::Artifact::Zap:0x007fcbec825fb8>
==> Un-installing artifact of class Hbc::Artifact::App
==> Removing App '/Applications/MusicBrainz Picard.app'.
==> Dispatching zap stanza
==> Running zap process for musicbrainz-picard; your password may be necessary
==> Removing files:
~/Library/Caches/MusicBrainz
==> Executing: ["/usr/bin/sudo", "-E", "--", "/usr/bin/xargs", "-0", "--", "/bin/rm", "-r", "-f", "--"]
==> Trashing files:
~/.config/MusicBrainz
==> Executing: ["/usr/bin/osascript", "-e", "on run argv\n  repeat with i from 1 to (count argv)\n    set item i of argv to (item i of argv as POSIX file)\n  end repeat\n\n  tell application \"Finder\"\n    set trashedItems to (move argv to trash)\n    set output to \"\"\n\n    repeat with i from 1 to (count trashedItems)\n      set item i of trashedItems to POSIX path of (item i of trashedItems as string)\n      set output to output & (item i of trashedItems) & (do shell script \"printf \\\"\\\\0\\\"\")\n    end repeat\n\n    return output\n  end tell\nend run\n", "/Users/commitay/.config/MusicBrainz"]
==> 272:350: 
==> execution error: Finder got an error: Can’t set item 1 of folder "MusicBrainz" of folder ".Trash" of folder "commitay" of folder "Users" of startup disk to "/Users/commitay/.Trash/MusicBrainz/Picard/". (-10006)
Error: Command failed to execute!

==> Failed command:
/usr/bin/osascript -e on run argv
  repeat with i from 1 to (count argv)
    set item i of argv to (item i of argv as POSIX file)
  end repeat

  tell application "Finder"
    set trashedItems to (move argv to trash)
    set output to ""

    repeat with i from 1 to (count trashedItems)
      set item i of trashedItems to POSIX path of (item i of trashedItems as string)
      set output to output & (item i of trashedItems) & (do shell script "printf \"\\0\"")
    end repeat

    return output
  end tell
end run
 /Users/commitay/.config/MusicBrainz

==> Standard Output of failed command:


==> Standard Error of failed command:
272:350: execution error: Finder got an error: Can’t set item 1 of folder "MusicBrainz" of folder ".Trash" of folder "commitay" of folder "Users" of startup disk to "/Users/commitay/.Trash/MusicBrainz/Picard/". (-10006)


==> Exit status of failed command:
#<Process::Status: pid 3309 exit 1>
Error: Zap incomplete.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/zap.rb:10:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```
```
brew cask zap vox --verbose --debug
==> Zapping Cask vox
==> Implied "brew cask uninstall vox"
==> Un-installing artifacts
==> Determining which artifacts are present in Cask vox
==> 2 artifact/s defined
#<Hbc::Artifact::App:0x007f9188826e48>
#<Hbc::Artifact::Zap:0x007f9188826df8>
==> Un-installing artifact of class Hbc::Artifact::App
==> Removing App '/Applications/VOX.app'.
==> Dispatching zap stanza
==> Running zap process for vox; your password may be necessary
==> Trashing files:
~/Library/Containers/com.coppertino.Vox
~/Library/Preferences/com.coppertino.Vox.plist
==> Executing: ["/usr/bin/osascript", "-e", "on run argv\n  repeat with i from 1 to (count argv)\n    set item i of argv to (item i of argv as POSIX file)\n  end repeat\n\n  tell application \"Finder\"\n    set trashedItems to (move argv to trash)\n    set output to \"\"\n\n    repeat with i from 1 to (count trashedItems)\n      set item i of trashedItems to POSIX path of (item i of trashedItems as string)\n      set output to output & (item i of trashedItems) & (do shell script \"printf \\\"\\\\0\\\"\")\n    end repeat\n\n    return output\n  end tell\nend run\n", "/Users/commitay/Library/Containers/com.coppertino.Vox"]
==> 272:350: 
==> execution error: Finder got an error: Can’t set item 1 of folder "com.coppertino.Vox" of folder ".Trash" of folder "commitay" of folder "Users" of startup disk to "/Users/commitay/.Trash/com.coppertino.Vox/Container.plist". (-10006)
Error: Command failed to execute!

==> Failed command:
/usr/bin/osascript -e on run argv
  repeat with i from 1 to (count argv)
    set item i of argv to (item i of argv as POSIX file)
  end repeat

  tell application "Finder"
    set trashedItems to (move argv to trash)
    set output to ""

    repeat with i from 1 to (count trashedItems)
      set item i of trashedItems to POSIX path of (item i of trashedItems as string)
      set output to output & (item i of trashedItems) & (do shell script "printf \"\\0\"")
    end repeat

    return output
  end tell
end run
 /Users/commitay/Library/Containers/com.coppertino.Vox

==> Standard Output of failed command:


==> Standard Error of failed command:
272:350: execution error: Finder got an error: Can’t set item 1 of folder "com.coppertino.Vox" of folder ".Trash" of folder "commitay" of folder "Users" of startup disk to "/Users/commitay/.Trash/com.coppertino.Vox/Container.plist". (-10006)


==> Exit status of failed command:
#<Process::Status: pid 3865 exit 1>
Error: Zap incomplete.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/zap.rb:10:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew-Cask Version
Homebrew-Cask 1.2.4
caskroom/homebrew-cask (git revision 76c1; last commit 2017-07-04)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (4 files, 90.3MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3652 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Environment Variables
LANG="en_AU.UTF-8"
PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

**Comment by vitorgalvao** [comment]
@reitermarkus Haven’t tested, but I’m betting Finder is failing while trying to delete a non-existing file. We need to check if they exist before trying to trash.

**Comment by vitorgalvao** [comment]
Got this far for now (skips non-existing files, but does not work for directories):

```applescript
#!/usr/bin/osascript

on run argv
  set trashPaths to {}

  repeat with i from 1 to (count argv)
    tell application "System Events"
      if exists file (item i of argv) then
        set end of trashPaths to (item i of argv as POSIX file)
      end if
    end tell
  end repeat

  tell application "Finder"
    set trashedItems to (move trashPaths to trash)
    set output to ""

    repeat with i from 1 to (count trashedItems)
      set item i of trashedItems to POSIX path of (item i of trashedItems as string)
      set output to output & (item i of trashedItems) & (do shell script "printf \"\\0\"")
    end repeat

    return output
  end tell
end run
```

I stopped because I’m a bit more doubtful of the error. In my tests, a non-existing file with the original code gave a different one (`execution error: Finder got an error: Handler can’t handle objects of this class. (-10010)`)

**Comment by reitermarkus** [comment]
Non-existing files are already skipped because `Pathname.glob` is used on all paths, so this can't be the problem. I.e. zapping a cask multiple times works as expected.

**Comment by commitay** [comment]
Not directly related to this issue but something I found while testing. Not sure if it is intentional.

`zap` fails if the `uninstall script` does not exist. `uninstall --force` skips the script but `zap` doesn't recognise the `--force` flag.
```
brew cask zap speedify
==> Implied "brew cask uninstall speedify"
==> Running uninstall process for speedify; your password may be necessary
==> Removing launchctl service me.connectify.SMJobBlessHelper
==> Removing launchctl service SwitchboardService
==> Removing launchctl service SpeedifyService
==> Running uninstall script /Applications/Speedify.app/Contents/Resources/unins
Error: uninstall script /Applications/Speedify.app/Contents/Resources/uninstall-speedify-service.sh does not exist.
Error: Zap incomplete.
```

**Comment by giannitm** [comment]
Building on your previous point @commitay, I think it would be very useful if the `zap` command recognised the `--force` flag. There have been many occasions where I couldn't use the `zap` command on a cask at all, simply because its `uninstall script` was missing.

**Comment by reitermarkus** [comment]
Should be fixed.

**Comment by commitay** [comment]
Both are working for me, thanks @reitermarkus! 🎉
