### ISSUE TITLE
Error when running brew cask list

### ISSUE THREAD

**Issue by hanxue** [caskroom/homebrew-cask#36164]
I have been having `brew cask list` error for a couple of months now - I suspect after moving the applications to `/usr/local/Caskroom` 

### brew cask list error

```
$ brew cask list 
Warning: Calling "cask :v1 => 'token'" is deprecated!
Use "cask 'token'" instead.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:11:in `load'

Warning: Calling "cask :v1 => 'token'" is deprecated!
Use "cask 'token'" instead.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:11:in `load'

Warning: Calling "cask :v1 => 'token'" is deprecated!
Use "cask 'token'" instead.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:11:in `load'

Warning: Unexpected method 'tags' called on Cask flash.
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask#reporting-bugs
Warning: Calling MacOS.release is deprecated!
Use MacOS.version instead.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:14:in `block in load'

Error: Cask 'keyremap4macbook' is unavailable: No Cask with this name exists.
```
Note, in this case `keyremap4macbook` is either a cask that is really old, or a cask that I authored myself. I have deleted about a dozen of those casks manually, but there are still many more. 

Is there any way to allow those outdated/custom cask to remain in place?

### Steps taken
I ran `brew cask update` multiple times, and also executed

```
$ brew untap caskroom/cask
$ brew tap caskroom/cask
```

### brew cask doctor

```
$ brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.2.4
caskroom/homebrew-cask (git revision 76c1; last commit 2017-07-04)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (3 files, 15.4MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3652 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-drivers (100 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-fonts (1106 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (160 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin14
/Library/Ruby/Site/2.0.0/universal-darwin14
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin14
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin14
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin14
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin14
==> Environment Variables
LANG="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
LC_CTYPE="UTF-8"
PATH="/usr/local/opt/mozjpeg/bin:~/.jenv/shims:~/.cabal/bin:/usr/local/var/rbenv/shims:/usr/local/bin:/usr/local/sbin:/opt/local/bin:/opt/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/MacGPG2/bin:~/Github/depot_tools:~/Source/google-cloud-sdk/bin:~/Code/Go/bin:~/.composer/vendor/bin:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd:/usr/local/Homebrew/Library/Taps/telemachus/homebrew-desc/cmd:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

**Comment by reitermarkus** [comment]
https://github.com/caskroom/homebrew-cask/issues/36060

**Comment by hanxue** [comment]
@reitermarkus thanks! 
@vitorgalvao no where in the instruction is anything said about deleting directories for Casks that are not found. I have a few dozen Casks I wrote myself in the past. How can I continue using them?

Do I re-write Casks put a copy in `/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask/` ? Or can I just reinstall it with `brew cask install /my/custom/location/cask-file.rb`?

Apologies, the title of the issue should rather be "Allowing custom Casks to be used".

**Comment by vitorgalvao** [comment]
> no where in the instruction is anything said about deleting directories for Casks that are not found.

The instructions have a “force fix” command. It’s not your decision to make which points to ignore, especially when there’s a point regarding precisely that.

If those are custom casks, then you need to fix them yourself. The error is self-explanatory. Look at the first line of the casks we have and your custom casks. Make them follow the same pattern.
