### ISSUE TITLE
Brew cask pipe to head causes broken pipe error

### ISSUE THREAD

**Issue by chingc** [caskroom/homebrew-cask#36218]
#### General troubleshooting steps

- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

To find out the version of a cask and what the latest available version is, I use `brew cask info <CASK> | head -n 3`.  Today, in addition to the top 3 lines, I'm also getting the following:

```bash
Error: Broken pipe - <STDOUT>
```

#### Output of your command with `--verbose --debug`

```bash
brew cask info vagrant --verbose --debug | head -n 3
==> Getting info for Cask vagrant
vagrant: 1.9.6
https://www.vagrantup.com/
Error: Broken pipe - <STDOUT>
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/info.rb:39:in `write'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/info.rb:39:in `puts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/info.rb:39:in `puts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/info.rb:39:in `block in installation_info'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/info.rb:36:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/info.rb:36:in `installation_info'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/info.rb:23:in `info'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/info.rb:12:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:68:in `block in casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:66:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:66:in `casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/info.rb:10:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/info.rb:10:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:179:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:179:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```

#### Output of `brew cask doctor`

```bash
$ brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.2.4
caskroom/homebrew-cask (git revision 25ec69; last commit 2017-07-05)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3652 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Gems/2.0.0/gems/json-1.8.3/lib
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Environment Variables
LANG="en_US.UTF-8"
PATH="~/Applications/jruby/bin:/usr/local/opt/mysql@5.6/bin:/usr/local/heroku/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

#### Additional Info

One interesting thing to note is if I use `--verbose --debug` the last line from `head` isn't echoed.

```bash
$ brew cask info vagrant | head -n 3
vagrant: 1.9.6
https://www.vagrantup.com/
/usr/local/Caskroom/vagrant/1.9.6 (3 files, 72.4MB)  # this line not in --verbose --debug
Error: Broken pipe - <STDOUT>
# stacktrace
```

```bash
brew cask info vagrant --verbose --debug | head -n 3
==> Getting info for Cask vagrant
vagrant: 1.9.6
https://www.vagrantup.com/
Error: Broken pipe - <STDOUT>
# stacktrace
```

Also, non-cask brews work just fine:

```bash
$ brew info python3 | head -n 4
python3: stable 3.6.1 (bottled), devel 3.6.2rc1, HEAD
Interpreted, interactive, object-oriented programming language
https://www.python.org/
/usr/local/Cellar/python3/3.6.1 (3,600 files, 55.8MB) *
$
```

**Comment by vitorgalvao** [comment]
I can reproduce.

But apart from that, why don’t you just `brew cask outdated`? Or are you trying to see something else?

Also, you don’t need `-n` with `head` and `tail` on macOS. `head -3` works the same.

**Comment by chingc** [comment]
@vitorgalvao Thanks for that shortcut.  As for `brew cask outdated`, it doesn't seem to work on every cask for me.

For example, I know I haven't updated intellij yet:

```bash
$ brew cask info intellij-idea
intellij-idea: 2017.1.5,171.4694.70
https://www.jetbrains.com/idea/
/usr/local/Caskroom/intellij-idea/2017.1.3,171.4424.56 (68B)
# broken pipe error

$ brew cask outdated

$

**Comment by vitorgalvao** [comment]
@chingc `outdated` by default does not show casks for apps that auto-update themselves. If you want to see those, add the `--greedy` flag.

**Comment by chingc** [comment]
Oh nice! Thanks! I like seeing it all.  :)

**Comment by jhcsu** [comment]
I am getting the broken pipe error as well.  It may be useful to note that the error caused by

    brew cask info CASK | head -n 3

can be circumvented with:

    brew cask info CASK | tail -n +1 | head -n 3

I reference this [superuser](https://superuser.com/questions/554855/how-can-i-fix-a-broken-pipe-error) post.  Did something change recently in the way information is output from ```brew cask info``` to cause the broken pipe error?

**Comment by commitay** [comment]
Doesn't seem to happen with `1.3.5` @vitorgalvao Can you still reproduce this?

```
brew cask info vagrant | head -3
vagrant: 2.0.0
https://www.vagrantup.com/
Not installed
```
```
brew cask info intellij-idea | head -3
intellij-idea: 2017.2.5,172.4343.14
https://www.jetbrains.com/idea/
Not installed
```

**Comment by reitermarkus** [comment]
For what it's worth, I could never reproduce this.

**Comment by vitorgalvao** [comment]
Can no longer reproduce. Seems to be fixed.
