### ISSUE TITLE
dymo-label fails to install completely

### ISSUE THREAD

**Issue by boneskull** [caskroom/homebrew-cask#36883]
#### General troubleshooting steps

- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Cask `dymo-label` fails to install completely.  `/Applications/DYMO Label.app` *is* installed correctly, and runs fine.

The following command was run against my fork, but the same thing happens with version 8.6 of the cask.  My PR to upgrade to version 8.6.2 was merged before I could file this ticket. 😉 

**I don't think this is a homebrew-cask-specific issue**, because I can easily reproduce the problem by running `/usr/sbin/installer` directly.

Please let me know if I can provide any more information.

#### Output of your command with `--verbose --debug`

```
> $ brew cask reinstall https://raw.githubusercontent.com/boneskull/homebrew-cask/cask_repair_update-dymo-label/Casks/dymo-label.rb --verbose --debug
==> Downloading https://raw.githubusercontent.com/boneskull/homebrew-cask/cask_repair_update-dymo-label/Casks/dymo-label.rb.
/usr/bin/curl --remote-time --location --user-agent Homebrew/1.2.4 (Macintosh; Intel Mac OS X 10.12.5) curl/7.51.0 --fail https://raw.githubusercontent.com/boneskull/homebrew-cask/cask_repair_update-dymo-label/Casks/dymo-label.rb -o /Users/boneskull/Library/Caches/Homebrew/Cask/dymo-label.rb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1033  100  1033    0     0   2793      0 --:--:-- --:--:-- --:--:--  2799
==> Hbc::Installer#reinstall
==> Hbc::Installer#install
==> Printing caveats
==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading http://download.dymo.com/dymo/Software/Mac/DLS8Setup.8.6.2.dmg
Already downloaded: /Users/boneskull/Library/Caches/Homebrew/Cask/dymo-label--8.6.2.dmg
==> Downloaded to -> /Users/boneskull/Library/Caches/Homebrew/Cask/dymo-label--8.6.2.dmg
==> Verifying download
==> Determining which verifications to run for Cask dymo-label
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask dymo-label
==> SHA256 checksums match
==> Installing Cask dymo-label
==> Hbc::Installer#stage
==> Extracting primary container
==> Determining which containers to use based on filetype
==> Checking container class Hbc::Container::Pkg
==> Checking container class Hbc::Container::Ttf
==> Checking container class Hbc::Container::Otf
==> Checking container class Hbc::Container::Air
==> Checking container class Hbc::Container::Cab
==> Checking container class Hbc::Container::Dmg
==> Executing: ["/usr/bin/hdiutil", "imageinfo", "/Users/boneskull/Library/Caches/Homebrew/Cask/dymo-label--8.6.2.dmg"]
==> Using container class Hbc::Container::Dmg for /Users/boneskull/Library/Caches/Homebrew/Cask/dymo-label--8.6.2.dmg
==> Executing: ["/usr/bin/hdiutil", "attach", "-plist", "-nobrowse", "-readonly", "-noidme", "-mountrandom", "/var/folders/74/p0gxrmy93fq88nm66cs7z42h0000gn/T/d20170722-81836-1qfbykf", "/Users/boneskull/Library/Caches/Homebrew/Cask/dymo-label--8.6.2.dmg"]
==> Executing: ["/usr/bin/mkbom", "-s", "-i", "/var/folders/74/p0gxrmy93fq88nm66cs7z42h0000gn/T/20170722-81836-ariud0.list", "--", "/var/folders/74/p0gxrmy93fq88nm66cs7z42h0000gn/T/20170722-81836-ix3lus.bom"]
==> Executing: ["/usr/bin/ditto", "--bom", "/var/folders/74/p0gxrmy93fq88nm66cs7z42h0000gn/T/20170722-81836-ix3lus.bom", "--", "/private/var/folders/74/p0gxrmy93fq88nm66cs7z42h0000gn/T/d20170722-81836-1qfbykf/dmg.I3qH0D", "/usr/local/Caskroom/dymo-label/8.6.2"]
==> Executing: ["/usr/sbin/diskutil", "eject", "/private/var/folders/74/p0gxrmy93fq88nm66cs7z42h0000gn/T/d20170722-81836-1qfbykf/dmg.I3qH0D"]
==> Creating metadata directory /usr/local/Caskroom/dymo-label/.metadata/8.6.2/20170723043016.508.
==> Creating metadata subdirectory /usr/local/Caskroom/dymo-label/.metadata/8.6.2/20170723043016.508/Casks.
==> Installing artifacts
==> Determining which artifacts are present in Cask dymo-label
==> 3 artifact/s defined
#<Hbc::Artifact::Uninstall:0x007f86d8234bd0>
#<Hbc::Artifact::Pkg:0x007f86d8234b30>
#<Hbc::Artifact::Zap:0x007f86d8234a68>
==> Installing artifact of class Hbc::Artifact::Pkg
==> Running installer for dymo-label; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
==> Executing: ["/usr/bin/sudo", "-E", "--", "/usr/sbin/installer", "-pkg", "/usr/local/Caskroom/dymo-label/8.6.2/DYMO Label v.8.pkg", "-target", "/", "-verboseR"]
==> installer: Package name is DYMO Label v.8
==> installer: Upgrading at base path /
==> installer:PHASE:Preparing for installation…
==> installer:PHASE:Preparing the disk…
==> installer:PHASE:Preparing DYMO Label v.8…
==> installer:PHASE:Waiting for other installations to complete…
==> installer:PHASE:Configuring the installation…
==> installer:STATUS:
==> installer:%4.527400
==> installer:PHASE:Writing files…
==> installer:%8.410800
==> installer:PHASE:Writing files…
==> installer:%11.115600
==> installer:PHASE:Writing files…
==> installer:%13.820400
==> installer:PHASE:Writing files…
==> installer:%16.525199
==> installer:PHASE:Writing files…
==> installer:%31.401598
==> installer:PHASE:Writing files…
==> installer:%53.473386
==> installer:PHASE:Moving items into place…
==> installer:%54.149411
==> installer:PHASE:Moving items into place…
==> installer:%54.824199
==> installer:PHASE:Moving items into place…
==> installer:%55.501652
==> installer:PHASE:Moving items into place…
==> installer:%66.841249
==> installer:PHASE:Registering updated components…
==> installer:%67.520643
==> installer:PHASE:Registering updated components…
==> installer:%68.193230
==> installer:PHASE:Registering updated components…
==> installer:%68.867341
==> installer:PHASE:Registering updated components…
==> installer:%69.543151
==> installer:PHASE:Registering updated components…
==> installer:%70.220790
==> installer:PHASE:Registering updated components…
==> installer:%70.896018
==> installer:PHASE:Registering updated components…
==> installer:%71.573560
==> installer:PHASE:Registering updated components…
==> installer:%72.253590
==> installer:PHASE:Registering updated components…
==> installer:%72.924219
==> installer:PHASE:Registering updated components…
==> installer:%73.600234
==> installer:PHASE:Registering updated components…
==> installer:%74.276588
==> installer:PHASE:Registering updated components…
==> installer:%74.953290
==> installer:PHASE:Registering updated components…
==> installer:%75.629433
==> installer:PHASE:Registering updated components…
==> installer:%76.308803
==> installer:PHASE:Registering updated components…
==> installer:%76.985552
==> installer:PHASE:Registering updated components…
==> installer:%77.661913
==> installer:PHASE:Registering updated components…
==> installer:%78.335171
==> installer:PHASE:Registering updated components…
==> installer:%79.010994
==> installer:PHASE:Registering updated components…
==> installer:%79.691566
==> installer:PHASE:Registering updated components…
==> installer:%80.087995
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:%80.484519
==> installer:PHASE:Running package scripts…
==> installer:%81.158143
==> installer:PHASE:Running package scripts…
==> installer:%81.881664
==> installer:PHASE:Running package scripts…
==> installer:%82.513784
==> installer:PHASE:Running package scripts…
==> installer:%83.190962
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Validating packages…
==> installer:%97.750000
==> installer: The upgrade failed (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.)
==> Purging files for version 8.6.2 of Cask dymo-label
Error: Command failed to execute!

==> Failed command:
/usr/bin/sudo -E -- /usr/sbin/installer -pkg /usr/local/Caskroom/dymo-label/8.6.2/DYMO Label v.8.pkg -target / -verboseR

==> Standard Output of failed command:
installer: Package name is DYMO Label v.8
installer: Upgrading at base path /
installer:PHASE:Preparing for installation…
installer:PHASE:Preparing the disk…
installer:PHASE:Preparing DYMO Label v.8…
installer:PHASE:Waiting for other installations to complete…
installer:PHASE:Configuring the installation…
installer:STATUS:
installer:%4.527400
installer:PHASE:Writing files…
installer:%8.410800
installer:PHASE:Writing files…
installer:%11.115600
installer:PHASE:Writing files…
installer:%13.820400
installer:PHASE:Writing files…
installer:%16.525199
installer:PHASE:Writing files…
installer:%31.401598
installer:PHASE:Writing files…
installer:%53.473386
installer:PHASE:Moving items into place…
installer:%54.149411
installer:PHASE:Moving items into place…
installer:%54.824199
installer:PHASE:Moving items into place…
installer:%55.501652
installer:PHASE:Moving items into place…
installer:%66.841249
installer:PHASE:Registering updated components…
installer:%67.520643
installer:PHASE:Registering updated components…
installer:%68.193230
installer:PHASE:Registering updated components…
installer:%68.867341
installer:PHASE:Registering updated components…
installer:%69.543151
installer:PHASE:Registering updated components…
installer:%70.220790
installer:PHASE:Registering updated components…
installer:%70.896018
installer:PHASE:Registering updated components…
installer:%71.573560
installer:PHASE:Registering updated components…
installer:%72.253590
installer:PHASE:Registering updated components…
installer:%72.924219
installer:PHASE:Registering updated components…
installer:%73.600234
installer:PHASE:Registering updated components…
installer:%74.276588
installer:PHASE:Registering updated components…
installer:%74.953290
installer:PHASE:Registering updated components…
installer:%75.629433
installer:PHASE:Registering updated components…
installer:%76.308803
installer:PHASE:Registering updated components…
installer:%76.985552
installer:PHASE:Registering updated components…
installer:%77.661913
installer:PHASE:Registering updated components…
installer:%78.335171
installer:PHASE:Registering updated components…
installer:%79.010994
installer:PHASE:Registering updated components…
installer:%79.691566
installer:PHASE:Registering updated components…
installer:%80.087995
installer:PHASE:Registering updated components…
installer:PHASE:Registering updated components…
installer:PHASE:Registering updated components…
installer:PHASE:Registering updated components…
installer:PHASE:Registering updated components…
installer:PHASE:Registering updated components…
installer:PHASE:Registering updated components…
installer:PHASE:Registering updated components…
installer:PHASE:Registering updated components…
installer:PHASE:Registering updated components…
installer:PHASE:Registering updated components…
installer:PHASE:Registering updated components…
installer:PHASE:Registering updated components…
installer:PHASE:Registering updated components…
installer:PHASE:Registering updated components…
installer:PHASE:Registering updated components…
installer:PHASE:Registering updated components…
installer:PHASE:Registering updated components…
installer:PHASE:Registering updated components…
installer:%80.484519
installer:PHASE:Running package scripts…
installer:%81.158143
installer:PHASE:Running package scripts…
installer:%81.881664
installer:PHASE:Running package scripts…
installer:%82.513784
installer:PHASE:Running package scripts…
installer:%83.190962
installer:PHASE:Running package scripts…
installer:PHASE:Validating packages…
installer:%97.750000
installer: The upgrade failed (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.)


==> Standard Error of failed command:


==> Exit status of failed command:
#<Process::Status: pid 82005 exit 1>
Error: Install incomplete.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:13:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew-Cask Version
Homebrew-Cask 1.2.4
caskroom/homebrew-cask (git revision c6773; last commit 2017-07-23)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (13 files, 346.9MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3657 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-drivers (104 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-eid (6 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-fonts (1107 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (158 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Environment Variables
LANG="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
PATH="~/bin:~/.config/yarn/global/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin:/usr/local/MacGPG2/bin:~/.antigen/bundles/robbyrussell/oh-my-zsh/lib:~/.antigen/bundles/zsh-users/zsh-syntax-highlighting:~/.antigen/bundles/zsh-users/zsh-history-substring-search:~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/git:~/.antigen/bundles/smallhadroncollider/antigen-git-rebase:~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/git-extras:~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/gitignore:~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/github:~/.antigen/bundles/denolfe/zsh-travis:~/.antigen/bundles/mollifier/cd-gitroot:~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/node:~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/nvm:~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/pip:~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/python:~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/npm:~/.antigen/bundles/tomsquest/nvm-auto-use.zsh:~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/sudo:~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/vagrant:~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/history:~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/jsontools:~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/wd:~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/bundler:~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/aws:~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/osx:~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/brew:~/.antigen/bundles/unixorn/tumult.plugin.zsh:~/.antigen/bundles/unixorn/tumult.plugin.zsh/bin:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/usr/local/bin/zsh"
```

**Comment by commitay** [comment]
I can reproduce this, however GUI install is successful. 

> Cask dymo-label fails to install completely. /Applications/DYMO Label.app is installed correctly, and runs fine.

Because the install fails `dymo-label` cannot be uninstalled using Cask.

`dymo-label` and dependant cask `dymo-stamps` will have to be removed from HBC. https://github.com/caskroom/homebrew-cask/pull/36884
