### ISSUE TITLE
jce-unlimited-strength-policy gets broken after java update/reinstall

### ISSUE THREAD

**Issue by koral--** [caskroom/homebrew-cask#36933]
#### General troubleshooting steps

- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

`jce-unlimited-strength-policy` uses the same jar files as `java` and after the latter is updated there are 2 issues:

- `jce-unlimited-strength-policy` becomes effectively uninstalled because jars are overwritten by standard (non-unlimited) ones
- `jce-unlimited-strength-policy` installation becomes broken because homebrew fails when trying to move non-existent files

It seems that ideal solution is that `java` detects that `jce-unlimited-strength-policy` is installed and reinstall it automatically additionally `jce-unlimited-strength-policy` (re)installation should not fail when it encounter non-existent jar backup file but continue (it may only print the error message).

#### Output of your command with `--verbose --debug`

```
$ brew cask reinstall --verbose --debug jce-unlimited-strength-policy
==> Hbc::Installer#reinstall
==> Hbc::Installer#install
==> Printing caveats
==> Caveats
Installing this Cask means you have AGREED to the Oracle Binary Code License Agreement for Java SE at
  https://www.oracle.com/technetwork/java/javase/terms/license/index.html

==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading http://download.oracle.com/otn-pub/java/jce/8/jce_policy-8.zip
Already downloaded: /Users/koral/Library/Caches/Homebrew/Cask/jce-unlimited-strength-policy--1.8.zip
==> Downloaded to -> /Users/koral/Library/Caches/Homebrew/Cask/jce-unlimited-strength-policy--1.8.zip
==> Verifying download
==> Determining which verifications to run for Cask jce-unlimited-strength-policy
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask jce-unlimited-strength-policy
==> SHA256 checksums match
==> Uninstalling Cask jce-unlimited-strength-policy
==> Un-installing artifacts
==> Determining which artifacts are present in Cask jce-unlimited-strength-policy
==> 1 artifact/s defined
#<Hbc::Artifact::PostflightBlock:0x007faed5076468>
==> Un-installing artifact of class Hbc::Artifact::PostflightBlock
==> Executing: ["/usr/bin/sudo", "-E", "--", "/bin/mv", "-f", "/Library/Java/JavaVirtualMachines/jdk1.8.0_141.jdk/Contents/Home/jre/lib/security/US_export_policy.jar.bak", "/Library/Java/JavaVirtualMachines/jdk1.8.0_141.jdk/Contents/Home/jre/lib/security/US_export_policy.jar"]
==> mv: rename /Library/Java/JavaVirtualMachines/jdk1.8.0_141.jdk/Contents/Home/jre/lib/security/US_export_policy.jar.bak to /Library/Java/JavaVirtualMachines/jdk1.8.0_141.jdk/Contents/Home/jre/lib/security/US_export_policy.jar: No such file or directory
Error: Command failed to execute!

==> Failed command:
/usr/bin/sudo -E -- /bin/mv -f /Library/Java/JavaVirtualMachines/jdk1.8.0_141.jdk/Contents/Home/jre/lib/security/US_export_policy.jar.bak /Library/Java/JavaVirtualMachines/jdk1.8.0_141.jdk/Contents/Home/jre/lib/security/US_export_policy.jar

==> Standard Output of failed command:


==> Standard Error of failed command:
mv: rename /Library/Java/JavaVirtualMachines/jdk1.8.0_141.jdk/Contents/Home/jre/lib/security/US_export_policy.jar.bak to /Library/Java/JavaVirtualMachines/jdk1.8.0_141.jdk/Contents/Home/jre/lib/security/US_export_policy.jar: No such file or directory


==> Exit status of failed command:
#<Process::Status: pid 71685 exit 1>
Error: Install incomplete.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:13:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'

```

#### Output of `brew cask doctor`

```
$ brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.2.4
caskroom/homebrew-cask (git revision 73cbd; last commit 2017-07-24)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (17 files, 2GB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3658 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (158 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Environment Variables
LANG="C"
LC_ALL="pl_PL.UTF-8"
PATH="/opt/local/bin:/opt/local/sbin:~/Library/Android/sdk/platform-tools:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:~/go/bin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/usr/local/bin/bash"
```

**Comment by commitay** [comment]
> It seems that ideal solution is that java detects that jce-unlimited-strength-policy is installed and reinstall it automatically additionally jce-unlimited-strength-policy (re)installation should not fail when it encounter non-existent jar backup file but continue (it may only print the error message).

Currently we don't have a way of detecting dependant casks.

`uninstall` / `reinstall` won't in this case as the files no long exist.

Please use:
```
brew cask install --force jce-unlimited-strength-policy
```

**Comment by commitay** [comment]
No response, closing.

**Comment by koral--** [comment]
Sorry, but I haven't noticed there is something to reply to. You added the label a few hours after commenting and there is no notification about that. Will try `install --force` on next java update.
Do you plan any long-term solution so un/reinstall will just work without workarounds like `--force`?

**Comment by commitay** [comment]
> Do you plan any long-term solution so un/reinstall will just work without workarounds like --force?

It has been mentioned a couple of times but no plans currently. Only a very small number of casks have issues similar to this. 
____

Workaround to prevent a broken reinstall/uninstall: https://github.com/caskroom/homebrew-cask/pull/37323/commits/5a5678b8edebb531547eb026a3ae3443be4a55d0

**Comment by koral--** [comment]
OK, thanks.
Maybe there should be just 2 casks: `java` without jce and `java-jce` or something like that with jce? If so, no additional actions are needed and after updating `java-jce` it will just work with unlimited strength.
