### ISSUE TITLE
Android-sdk

### ISSUE THREAD

**Issue by stoneman1** [caskroom/homebrew-cask#36951]
#### General troubleshooting steps

- [ X ] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  -  [ X ] None of the templates was appropriate for my issue, or I’m not sure.
- [ X ] I ran `brew update-reset && brew update` and retried my command.
- [ X ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [ X ] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Can't install android-sdk. It fails with no finding build-tools.

#### Output of your command with `--verbose --debug`

```
==> Hbc::Installer#install
==> Printing caveats
==> Caveats
We will install android-sdk-tools, platform-tools, and build-tools for you.
You can control android sdk packages via the sdkmanager command.
You may want to add to your profile:
  'export ANDROID_SDK_ROOT=/usr/local/share/android-sdk'

This operation may take up to 10 minutes depending on your internet connection.
Please, be patient.

==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://dl.google.com/android/repository/sdk-tools-darwin-3859397.zip
Already downloaded: /Users/aleksipousar/Library/Caches/Homebrew/Cask/android-sdk--3859397.zip
==> Downloaded to -> /Users/aleksipousar/Library/Caches/Homebrew/Cask/android-sdk--3859397.zip
==> Verifying download
==> Determining which verifications to run for Cask android-sdk
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask android-sdk
==> SHA256 checksums match
==> Installing Cask android-sdk
==> Hbc::Installer#stage
==> Extracting primary container
==> Determining which containers to use based on filetype
==> Checking container class Hbc::Container::Pkg
==> Checking container class Hbc::Container::Ttf
==> Checking container class Hbc::Container::Otf
==> Checking container class Hbc::Container::Air
==> Checking container class Hbc::Container::Cab
==> Checking container class Hbc::Container::Dmg
==> Executing: ["/usr/bin/hdiutil", "imageinfo", "/Users/aleksipousar/Library/Caches/Homebrew/Cask/android-sdk--3859397.zip"]
==> Checking container class Hbc::Container::SevenZip
==> Checking container class Hbc::Container::Sit
==> Checking container class Hbc::Container::Rar
==> Checking container class Hbc::Container::Zip
==> Using container class Hbc::Container::Zip for /Users/aleksipousar/Library/Caches/Homebrew/Cask/android-sdk--3859397.zip
==> Executing: ["/usr/bin/ditto", "-x", "-k", "--", "/Users/aleksipousar/Library/Caches/Homebrew/Cask/android-sdk--3859397.zip", "/var/folders/mz/ddv1y5p10nn_g_1z28g8bsb80000gn/T/d20170725-36174-anuuve"]
==> Creating metadata directory /usr/local/Caskroom/android-sdk/.metadata/3859397/20170725092859.715.
==> Creating metadata subdirectory /usr/local/Caskroom/android-sdk/.metadata/3859397/20170725092859.715/Casks.
==> Installing artifacts
==> Determining which artifacts are present in Cask android-sdk
==> 3 artifact/s defined
#<Hbc::Artifact::PreflightBlock:0x007fd05a8c2dc8>
#<Hbc::Artifact::Binary:0x007fd05a8c2d50>
#<Hbc::Artifact::PostflightBlock:0x007fd05a8c2b20>
==> Installing artifact of class Hbc::Artifact::PreflightBlock
==> Executing: ["/usr/local/Caskroom/android-sdk/3859397/tools/bin/sdkmanager", "tools", "platform-tools", "build-tools;26.0.0"]
==> Warning: Failed to find package build-tools;26.0.0
==> Purging files for version 3859397 of Cask android-sdk
Error: Command failed to execute!

==> Failed command:
/usr/local/Caskroom/android-sdk/3859397/tools/bin/sdkmanager tools platform-tools build-tools;26.0.0

==> Standard Output of failed command:


==> Standard Error of failed command:
Warning: Failed to find package build-tools;26.0.0


==> Exit status of failed command:
#<Process::Status: pid 36299 exit 1>
Error: Install incomplete.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:13:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew-Cask Version
Homebrew-Cask 1.2.4-107-gaa8eb21
caskroom/homebrew-cask (git revision 91387; last commit 2017-07-25)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (6 files, 307MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3663 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Environment Variables
LC_CTYPE="UTF-8"
PATH="~/.fastlane/bin:~/.nvm/versions/node/v7.7.2/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:~/Library/Android/sdk/tools:~/Library/Android/sdk/platform-tools:/usr/local/Cellar/node/7.7.2/bin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

**Comment by stoneman1** [comment]
related to #36949 I think

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/36949 is merged, please `brew update` and try again.

**Comment by stoneman1** [comment]
It works now thanks.
