### ISSUE TITLE
Checksum mismatch: imazing

### ISSUE THREAD

**Issue by vickio** [caskroom/homebrew-cask#36977]
[`imazing`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/imazing.rb) 2.3.2 is failing to install with a checksum mismatch. I did try deleting and re-downloading the installation file, but it was the same. https://imazing.com/download shows 2.3.2 as the current version.

```
⋊> ~ brew cask install imazing --verbose --debug
==> Hbc::Installer#install
==> Printing caveats
==> Caveats
Performing a zap on this cask removes files pertaining to both imazing
and imazing-mini, so it should not be done if you only want to uninstall one of them.

==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://dl.devmate.com/com.DigiDNA.iMazing2Mac/iMazing2forMac.dmg
==> Calling curl with args ["https://dl.devmate.com/com.DigiDNA.iMazing2Mac/iMazing2forMac.dmg", "-C", 0, "-o", #<Pathname:/Users/vickio/Library/Caches/Homebrew/Cask/imazing--2.3.2.dmg.incomplete>]
/usr/bin/curl --remote-time --location --user-agent Homebrew/1.2.5-14-g88b762f (Macintosh; Intel Mac OS X 10.12.6) curl/7.54.0 --fail https://dl.devmate.com/com.DigiDNA.iMazing2Mac/iMazing2forMac.dmg -C 0 -o /Users/vickio/Library/Caches/Homebrew/Cask/imazing--2.3.2.dmg.incomplete
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 68.7M  100 68.7M    0     0  3333k      0  0:00:21  0:00:21 --:--:-- 3508k
==> Downloaded to -> /Users/vickio/Library/Caches/Homebrew/Cask/imazing--2.3.2.dmg
==> Verifying download
==> Determining which verifications to run for Cask imazing
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask imazing
==> Note: running "brew update" may fix sha256 checksum errors
Error: Checksum for Cask 'imazing' does not match.

Expected: 69d3d1656ad7c434ada1f744bdd2d43a4e559d8d69101635f31efa8a7bf5f530
Actual:   603bb52c2ce07ece36229384248bccc4e9e9dc06f30b83e2ae9bd15b3dabd11b
File:     /Users/vickio/Library/Caches/Homebrew/Cask/imazing--2.3.2.dmg

To retry an incomplete download, remove the file above.
Error: Install incomplete.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:13:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
```

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/36988
