### ISSUE TITLE
Recent java cask download link appears to be broken

### ISSUE THREAD

**Issue by thomasbarone** [caskroom/homebrew-cask#37235]
#### General troubleshooting steps

- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

There appears to be a broken download link when trying to install the java cask. I believe commit https://github.com/caskroom/homebrew-cask/commit/4a0f29a4e51355106dc0264360d9779cf59991e3 isn't constructing the oracle download link correctly on [this line](https://github.com/caskroom/homebrew-cask/blob/4a0f29a4e51355106dc0264360d9779cf59991e3/Casks/java.rb#L6).

#### Output of your command with `--verbose --debug`

```
$ brew cask install java --verbose --debug
==> Creating directories
==> Loading Cask definitions
==> Translating 'java' into a valid Cask source
==> Testing source class Hbc::Source::URI
==> Testing source class Hbc::Source::PathSlashRequired
==> Testing source class Hbc::Source::TappedQualified
==> Testing source class Hbc::Source::UntappedQualified
==> Testing source class Hbc::Source::Tapped
==> Success! Using source class Hbc::Source::Tapped
==> Resolved Cask URI or file source to '/usr/local/Library/Taps/caskroom/homebrew-cask/Casks/java.rb'
==> Cask instance dumps in YAML:
==> Cask instance toplevel:
--- !ruby/object:Hbc::Cask
token: java
sourcefile_path: !ruby/object:Pathname
  path: /usr/local/Library/Taps/caskroom/homebrew-cask/Casks/java.rb
dsl: !ruby/object:Hbc::DSL
  token: java
  version: !ruby/string:Hbc::DSL::Version
    str: !binary |-
      MS44LjBfMTAyLWIxNA==
    raw_version: 1.8.0_102-b14
  sha256: 9f53b71af203502da4ff416b5ab1a217a655006786bcbb8f8d8ad501debda748
  url: !ruby/object:Hbc::URL
    uri: !ruby/object:URI::HTTP
      scheme: http
      user: 
      password: 
      host: download.oracle.com
      port: 80
      path: /otn-pub/java/jdk/8u102-b14/jdk-8u102-macosx-x64.dmg
      query: 
      opaque: 
      registry: 
      fragment: 
      parser: 
    user_agent: 
    cookies:
      oraclelicense: accept-securebackup-cookie
    referer: 
    using: 
    revision: 
    trust_cert: 
    data: 
  name:
  - Java Standard Edition Development Kit
  homepage: http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html
  license: !ruby/object:Hbc::DSL::License
    value: :gratis
  artifacts:
    :pkg: !ruby/object:Set
      hash:
        ? - JDK 8 Update 102.pkg
        : true
    :postflight: !ruby/object:Set
      hash:
        !ruby/object:Proc {}: true
    :uninstall: !ruby/object:Set
      hash:
        ? :pkgutil:
          - com.oracle.jdk8u102
          - com.oracle.jre
          :launchctl:
          - com.oracle.java.Helper-Tool
          - com.oracle.java.Java-Updater
          :quit:
          - com.oracle.java.Java-Updater
          - net.java.openjdk.cmd
          :delete:
          - /Library/Internet Plug-Ins/JavaAppletPlugin.plugin
          - /Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents
          - /Library/PreferencePanes/JavaControlPanel.prefPane
          - /Library/Java/Home
        : true
    :zap: !ruby/object:Set
      hash:
        ? :delete:
          - ~/Library/Application Support/Oracle/Java
          - ~/Library/Caches/com.oracle.java.Java-Updater
          - ~/Library/Caches/net.java.openjdk.cmd
          :rmdir: ~/Library/Application Support/Oracle/
        : true
  caveats:
  - - |+
      This Cask makes minor modifications to the JRE to prevent issues with
      packaged applications, as discussed here:

        https://bugs.eclipse.org/bugs/show_bug.cgi?id=411361

      If your Java application still asks for JRE installation, you might need
      to reboot or logout/login.

      Installing this Cask means you have AGREED to the Oracle Binary Code
      License Agreement for Java SE at

        http://www.oracle.com/technetwork/java/javase/terms/license/index.html

==> Cask instance method 'name':
---
- Java Standard Edition Development Kit
==> Cask instance method 'homepage':
--- http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html
...
==> Cask instance method 'url':
--- !ruby/object:Hbc::URL
uri: !ruby/object:URI::HTTP
  scheme: http
  user: 
  password: 
  host: download.oracle.com
  port: 80
  path: /otn-pub/java/jdk/8u102-b14/jdk-8u102-macosx-x64.dmg
  query: 
  opaque: 
  registry: 
  fragment: 
  parser: 
user_agent: 
cookies:
  oraclelicense: accept-securebackup-cookie
referer: 
using: 
revision: 
trust_cert: 
data: 
==> Cask instance method 'appcast':
--- 
...
==> Cask instance method 'version':
--- !ruby/string:Hbc::DSL::Version
str: !binary |-
  MS44LjBfMTAyLWIxNA==
raw_version: 1.8.0_102-b14
==> Cask instance method 'license':
--- !ruby/object:Hbc::DSL::License
value: :gratis
==> Cask instance method 'sha256':
--- 9f53b71af203502da4ff416b5ab1a217a655006786bcbb8f8d8ad501debda748
...
==> Cask instance method 'artifacts':
---
:pkg: !ruby/object:Set
  hash:
    ? - JDK 8 Update 102.pkg
    : true
:postflight: !ruby/object:Set
  hash:
    !ruby/object:Proc {}: true
:uninstall: !ruby/object:Set
  hash:
    ? :pkgutil:
      - com.oracle.jdk8u102
      - com.oracle.jre
      :launchctl:
      - com.oracle.java.Helper-Tool
      - com.oracle.java.Java-Updater
      :quit:
      - com.oracle.java.Java-Updater
      - net.java.openjdk.cmd
      :delete:
      - /Library/Internet Plug-Ins/JavaAppletPlugin.plugin
      - /Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents
      - /Library/PreferencePanes/JavaControlPanel.prefPane
      - /Library/Java/Home
    : true
:zap: !ruby/object:Set
  hash:
    ? :delete:
      - ~/Library/Application Support/Oracle/Java
      - ~/Library/Caches/com.oracle.java.Java-Updater
      - ~/Library/Caches/net.java.openjdk.cmd
      :rmdir: ~/Library/Application Support/Oracle/
    : true
==> Cask instance method 'caveats':
---
- - |+
    This Cask makes minor modifications to the JRE to prevent issues with
    packaged applications, as discussed here:

      https://bugs.eclipse.org/bugs/show_bug.cgi?id=411361

    If your Java application still asks for JRE installation, you might need
    to reboot or logout/login.

    Installing this Cask means you have AGREED to the Oracle Binary Code
    License Agreement for Java SE at

      http://www.oracle.com/technetwork/java/javase/terms/license/index.html

==> Cask instance method 'depends_on':
--- 
...
==> Cask instance method 'conflicts_with':
--- 
...
==> Cask instance method 'container':
--- 
...
==> Cask instance method 'gpg':
--- 
...
==> Cask instance method 'accessibility_access':
--- 
...
==> Cask instance method 'auto_updates':
--- 
...
==> Hbc::Installer.install
==> Printing caveats
==> Caveats
This Cask makes minor modifications to the JRE to prevent issues with
packaged applications, as discussed here:

  https://bugs.eclipse.org/bugs/show_bug.cgi?id=411361

If your Java application still asks for JRE installation, you might need
to reboot or logout/login.

Installing this Cask means you have AGREED to the Oracle Binary Code
License Agreement for Java SE at

  http://www.oracle.com/technetwork/java/javase/terms/license/index.html

==> Downloading
==> Downloading http://download.oracle.com/otn-pub/java/jdk/8u102-b14/jdk-8u102-macosx-x64.dmg
==> Calling curl with args ["http://download.oracle.com/otn-pub/java/jdk/8u102-b14/jdk-8u102-macosx-x64.dmg", "-C", "0", "-o", "#<Pathname:/Users/tbone/Library/Caches/Homebrew/Cask/java--1.8.0_102-b14.dmg.incomplete>", "-b", "oraclelicense=accept-securebackup-cookie"]
/usr/bin/curl --fail --remote-time --location --user-agent Homebrew/0.9.9 (Macintosh; Intel Mac OS X 10.12.6) curl/7.54.0 http://download.oracle.com/otn-pub/java/jdk/8u102-b14/jdk-8u102-macosx-x64.dmg -C 0 -o /Users/tbone/Library/Caches/Homebrew/Cask/java--1.8.0_102-b14.dmg.incomplete -b oraclelicense=accept-securebackup-cookie
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   461  100   461    0     0   1141      0 --:--:-- --:--:-- --:--:--  2695
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
==> Purging files for version 1.8.0_102-b14 of Cask java
Error: Download failed on Cask 'java' with message: Download failed: http://download.oracle.com/otn-pub/java/jdk/8u102-b14/jdk-8u102-macosx-x64.dmg
The incomplete download is cached at /Users/tbone/Library/Caches/Homebrew/Cask/java--1.8.0_102-b14.dmg.incomplete/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/download.rb:41:in `rescue in fetch'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/download.rb:39:in `fetch'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/download.rb:14:in `perform'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/installer.rb:97:in `download'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/installer.rb:71:in `install'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/install.rb:23:in `block in install_casks'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/install.rb:17:in `each'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/install.rb:17:in `install_casks'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli/install.rb:8:in `run'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli.rb:108:in `run_command'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli.rb:146:in `process'
/usr/local/Library/Taps/caskroom/homebrew-cask/cmd/brew-cask.rb:23:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/Homebrew/brew.rb:22:in `require?'
/usr/local/Library/Homebrew/brew.rb:93:in `<main>'
Error: Kernel.exit
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli.rb:151:in `exit'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli.rb:151:in `rescue in process'
/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/cli.rb:142:in `process'
/usr/local/Library/Taps/caskroom/homebrew-cask/cmd/brew-cask.rb:23:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/Homebrew/brew.rb:22:in `require?'
/usr/local/Library/Homebrew/brew.rb:93:in `<main>'
```

#### Output of `brew cask doctor`

```
$ brew cask doctor
==> macOS Release:
10.12.6
==> Hardware Architecture:
intel-64
==> Ruby Version:
2.0.0-p648
==> Ruby Path:
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
==> Homebrew Version:
Homebrew 0.9.9 (git revision 06fe3; last commit 2016-08-10)
Homebrew/homebrew-core (git revision b163b; last commit 2016-08-10)
==> Homebrew Executable Path:
/usr/local/bin/brew
==> Homebrew Cellar Path:
/usr/local/Cellar
==> Homebrew Repository Path:
/usr/local
==> Homebrew Origin:
https://github.com/Homebrew/brew.git
==> Homebrew-Cask Version:
0.60.0 (git revision fd8bd; last commit 12 months ago)
==> Homebrew-Cask Install Location:
<NONE>
==> Homebrew-Cask Staging Location:
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads:
/Users/tbone/Library/Caches/Homebrew/Cask
2 files, 226.6M (warning: run "brew cask cleanup")
==> Homebrew-Cask Default Tap Path:
/usr/local/Library/Taps/caskroom/homebrew-cask
==> Homebrew-Cask Alternate Cask Taps:
<NONE>
==> Homebrew-Cask Default Tap Cask Count:
3259
==> Contents of $LOAD_PATH:
/usr/local/Library/Taps/caskroom/homebrew-cask/lib
/usr/local/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Contents of $RUBYLIB Environment Variable:
<NONE>
==> Contents of $RUBYOPT Environment Variable:
<NONE>
==> Contents of $RUBYPATH Environment Variable:
<NONE>
==> Contents of $RBENV_VERSION Environment Variable:
<NONE>
==> Contents of $CHRUBY_VERSION Environment Variable:
<NONE>
==> Contents of $GEM_HOME Environment Variable:
<NONE>
==> Contents of $GEM_PATH Environment Variable:
<NONE>
==> Contents of $BUNDLE_PATH Environment Variable:
<NONE>
==> Contents of $PATH Environment Variable:
PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/TeX/texbin:/usr/local/Library/Taps/caskroom/homebrew-cask/cmd:/usr/local/Library/Homebrew/shims/scm"
==> Contents of $SHELL Environment Variable:
SHELL="/bin/bash"
==> Contents of Locale Environment Variables:
LANG="en_AU.UTF-8"
==> Running As Privileged User:
No
```

**Comment by commitay** [comment]
@thomasbarone Your Homebrew is very outdated (`0.9.9`, current is `1.2.6`) and is downloading an outdated version of `java` (`8u102-b14`, current is `8u144-b01`).

Please do the step that you marked in the checklist.

> - [x] I ran `brew update-reset && brew update` and retried my command.

**Comment by thomasbarone** [comment]
Oh wow! Turns out I had another issue that was causing my Homebrew to not update properly. 

Works now thanks.
