### ISSUE TITLE
Failed to download citric-receiver; download in Safari works fine

### ISSUE THREAD

**Issue by lunaryorn** [caskroom/homebrew-cask#37252]
#### General troubleshooting steps

- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

`brew cask` can't download `citric-receiver` from; says download from <http://downloadplugins.citrix.com.edgesuite.net/Mac/CitrixReceiverWeb.dmg> failed.

~~**However the same URL works fine in Safari**; I can literally `Cmd+Click` on the URL in iTerm2 to download the file.~~. I just noticed that the downloaded file contains the ASCII text "File not found." 😕 

#### Output of your command with `--verbose --debug`

```
$ brew cask fetch --debug --verbose citrix-receiver
==> Downloading external files for Cask citrix-receiver
==> Downloading http://downloadplugins.citrix.com.edgesuite.net/Mac/CitrixReceiverWeb.dmg
==> Calling curl with args ["http://downloadplugins.citrix.com.edgesuite.net/Mac/CitrixReceiverWeb.dmg", "-C", 0, "-o", #<Pathname:/Users/swiesner/Library/Caches/Homebrew/Cask/citrix-receiver--latest.dmg.incomplete>]
/usr/bin/curl --remote-time --location --user-agent Homebrew/1.X.Y (Macintosh; Intel Mac OS X 10.12.6) curl/7.54.0 --fail http://downloadplugins.citrix.com.edgesuite.net/Mac/CitrixReceiverWeb.dmg -C 0 -o /Users/swiesner/Library/Caches/Homebrew/Cask/citrix-receiver--latest.dmg.incomplete
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'citrix-receiver' with message: Download failed: http://downloadplugins.citrix.com.edgesuite.net/Mac/CitrixReceiverWeb.dmg
Error: Fetch incomplete.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/fetch.rb:12:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew-Cask Version
Homebrew-Cask >1.2.0 (no git repository)
caskroom/homebrew-cask (git revision 5867a; last commit 2017-07-31)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3670 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-eid (6 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (159 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Environment Variables
LANG="de_DE.UTF-8"
PATH="~/.local/bin:~/.cargo/bin:~/.gem/ruby/2.4.0/bin:~/Library/Python/3.6/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/usr/local/bin/fish"
```

**Comment by lunaryorn** [comment]
I guess the download moved, or is currently down.  I'm sorry for the noise.
