### ISSUE TITLE
Error: Failed executing

### ISSUE THREAD

**Issue by jlass192** [caskroom/homebrew-cask#37308]
#### General troubleshooting steps

- [X ] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [ X] None of the templates was appropriate for my issue, or I’m not sure.
- [ X] I ran `brew update-reset && brew update` and retried my command.
- [X ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [ X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

In Terminal tried the command "brew cask install golem". The command completed a few tasks before giving the following error:
==> **sudo chown root:wheel /usr/local opt/docker-machine-driver/xhyve/bin/docker-machine-driver-xhyve**
Failed to execute: sudo chown root:wheel /usr/local/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve
Error: Failed executing: sudo chown root:wheel /usr/local/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve
Follow the instructions here:
https://github.com/caskroom/homebrew-cask#reporting-bugs

#### Output of your command with `--verbose --debug`

```
Admins-MacBook-Air:~ admin$ brew cask install golem --verbose
==> Satisfying dependencies
==> Installing Formula dependencies: golem
==> Installing golemfactory/golem/golem
==> Using the sandbox
==> Downloading https://github.com/golemfactory/golem/releases/download/0.7.1/golem-macos-0.7.1.tar.gz
Already downloaded: /Users/admin/Library/Caches/Homebrew/golem-0.7.1.tar.gz
==> Verifying golem-0.7.1.tar.gz checksum
tar xzf /Users/admin/Library/Caches/Homebrew/golem-0.7.1.tar.gz
==> echo docker-machine-driver-xhyve need root owner and uid
docker-machine-driver-xhyve need root owner and uid
==> sudo chown root:wheel /usr/local/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve
Failed to execute: sudo chown root:wheel /usr/local/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve
Error: Failed executing: sudo chown root:wheel /usr/local/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve 
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/formula.rb:1804:in `block in system'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1742:in `open'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1742:in `system'
/usr/local/Homebrew/Library/Taps/golemfactory/homebrew-golem/golem.rb:26:in `install'
/usr/local/Homebrew/Library/Homebrew/build.rb:139:in `block (2 levels) in install'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1093:in `block in brew'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1905:in `block in stage'
/usr/local/Homebrew/Library/Homebrew/resource.rb:97:in `block in unpack'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `block in run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `chdir'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/resource.rb:93:in `unpack'
/usr/local/Homebrew/Library/Homebrew/resource.rb:85:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1884:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1088:in `brew'
/usr/local/Homebrew/Library/Homebrew/build.rb:114:in `block in install'
/usr/local/Homebrew/Library/Homebrew/utils.rb:554:in `with_env'
/usr/local/Homebrew/Library/Homebrew/build.rb:111:in `install'
/usr/local/Homebrew/Library/Homebrew/build.rb:188:in `<main>'
Error: Kernel.exit

Admins-MacBook-Air:~ admin$ brew cask install golem --debug
==> Hbc::Installer#install
==> Printing caveats
==> Hbc::Installer#fetch
==> Satisfying dependencies
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/golemfactory/homebrew-golem/golem.rb
==> Installing Formula dependencies: golem
==> Installing golemfactory/golem/golem
==> Using the sandbox
==> Downloading https://github.com/golemfactory/golem/releases/download/0.7.1/golem-macos-0.7.1.tar.gz
Already downloaded: /Users/admin/Library/Caches/Homebrew/golem-0.7.1.tar.gz
==> echo docker-machine-driver-xhyve need root owner and uid
==> sudo chown root:wheel /usr/local/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve
Last 15 lines from /Users/admin/Library/Logs/Homebrew/golem/02.docker-machine-driver-xhyve:
2017-08-02 10:23:43 -0500

sudo chown root:wheel /usr/local/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve

Error: Failed executing: sudo chown root:wheel /usr/local/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve 
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/formula.rb:1804:in `block in system'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1742:in `open'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1742:in `system'
/usr/local/Homebrew/Library/Taps/golemfactory/homebrew-golem/golem.rb:26:in `install'
/usr/local/Homebrew/Library/Homebrew/build.rb:139:in `block (2 levels) in install'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1093:in `block in brew'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1905:in `block in stage'
/usr/local/Homebrew/Library/Homebrew/resource.rb:97:in `block in unpack'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `block in run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `chdir'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/resource.rb:93:in `unpack'
/usr/local/Homebrew/Library/Homebrew/resource.rb:85:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1884:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1088:in `brew'
/usr/local/Homebrew/Library/Homebrew/build.rb:114:in `block in install'
/usr/local/Homebrew/Library/Homebrew/utils.rb:554:in `with_env'
/usr/local/Homebrew/Library/Homebrew/build.rb:111:in `install'
/usr/local/Homebrew/Library/Homebrew/build.rb:188:in `<main>'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:179:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:179:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
Admins-MacBook-Air:~ admin$ 

```

#### Output of `brew cask doctor`

```
Admins-MacBook-Air:~ admin$ brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.3.0
caskroom/homebrew-cask (git revision c367; last commit 2017-08-02)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3670 casks)
/usr/local/Homebrew/Library/Taps/golemfactory/homebrew-golem (1 cask)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Environment Variables
LANG="en_US.UTF-8"
PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
Admins-MacBook-Air:~ admin$ 
```

**Comment by vitorgalvao** [comment]
We don’t have any cask by that name. You’ll need to open an issue in whatever tap you’re getting it from.

**Comment by arviantodwi** [comment]
I face the same issue, but I do it manually and successfully install the golem.app

Edit your `golem.rb` file in your Homebrew installation dir. Mine was **/usr/local/Homebrew/Library/Taps/golemfactory/homebrew-golem/golem.rb**

Comment out on line 26 and 27, save it, then do it manually from your terminal as root using sudo:
`sudo chown root:wheel #{HOMEBREW_PREFIX}/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve`
`sudo chmod u+s #{HOMEBREW_PREFIX}/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve`

After that just install again the golem:
`brew cask install golem`

Your golem.app will be there at your Application dir. Good luck.
