### ISSUE TITLE
brew cask info dies if STDOUT is closed early

### ISSUE THREAD

**Issue by kstarsinic** [caskroom/homebrew-cask#37722]
#### General troubleshooting steps

- [X] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [X] None of the templates was appropriate for my issue, or I’m not sure.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

I've got a script that shows me info on installed casks. One of them broke recently on this command, which used to work:
% brew cask info libreoffice | head -1
("libreoffice" just for specificity; any valid cask name will do)
I am working around this issue for now by redirecting STDERR to /dev/null, but I generally want to see errors from these scripts.

#### Output of your command with `--verbose --debug`
```
% brew cask info libreoffice --verbose --debug
==> Getting info for Cask libreoffice
libreoffice: 5.4.0
https://www.libreoffice.org/
/usr/local/Caskroom/libreoffice/5.4.0 (3 files, 589.4KB)
==> [user, repo, token] might be [caskroom, cask, libreoffice]
From: https://github.com/caskroom/homebrew-cask/blob/master/Casks/libreoffice.rb
==> Name
LibreOffice
==> Artifacts
LibreOffice.app (app)
/Applications/LibreOffice.app/Contents/MacOS/gengal (binary)
/Applications/LibreOffice.app/Contents/MacOS/regmerge (binary)
/Applications/LibreOffice.app/Contents/MacOS/regview (binary)
/Applications/LibreOffice.app/Contents/MacOS/senddoc (binary)
/Applications/LibreOffice.app/Contents/MacOS/ui-previewer (binary)
/Applications/LibreOffice.app/Contents/MacOS/uno (binary)
/Applications/LibreOffice.app/Contents/MacOS/unopkg (binary)
/Applications/LibreOffice.app/Contents/MacOS/urelibs (binary)
/Applications/LibreOffice.app/Contents/MacOS/uri-encode (binary)
/Applications/LibreOffice.app/Contents/MacOS/xpdfimport (binary)
/usr/local/Caskroom/libreoffice/5.4.0/soffice.wrapper.sh (binary)
==> Printing caveats

% brew cask info libreoffice --verbose --debug | head -1
==> Getting info for Cask libreoffice
Error: Broken pipe - <STDOUT>
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/info.rb:39:in `write'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/info.rb:39:in `puts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/info.rb:39:in `puts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/info.rb:39:in `block in installation_info'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/info.rb:36:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/info.rb:36:in `installation_info'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/info.rb:23:in `info'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/info.rb:12:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:68:in `block in casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:66:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:66:in `casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/info.rb:10:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/info.rb:10:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:97:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:167:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:178:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:178:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew-Cask Version
Homebrew-Cask 1.3.1-49-gdaa0ea4
caskroom/homebrew-cask (git revision 4de77; last commit 2017-08-16)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3693 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin13
/Library/Ruby/Site/2.0.0/universal-darwin13
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin13
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin13
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin13
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin13
==> Environment Variables
LANG="en_US.UTF-8"
LC_COLLATE="C"
PATH="~/perl5/perlbrew/bin:~/perl5/perlbrew/perls/perl-5.24.1/bin:~/Dropbox/bin:~/bin:/usr/local/bin:/usr/local/sbin:/usr/sbin:/usr/bin:/bin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/usr/local/bin/bash"
```

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/issues/36218
