### ISSUE TITLE
error trying to install golem

### ISSUE THREAD

**Issue by jpita** [caskroom/homebrew-cask#37727]
#### General troubleshooting steps

- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

I get this  error

```Error: Failed executing: sudo chown root:wheel /usr/local/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve ```

 after running this command: 
```brew cask install golem```

#### Output of your command with `--verbose --debug`

```
| => brew cask install golem --verbose --debug
==> Hbc::Installer#install
==> Printing caveats
==> Hbc::Installer#fetch
==> Satisfying dependencies
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/golemfactory/homebrew-golem/golem.rb
==> Installing Formula dependencies: golem
==> Installing golemfactory/golem/golem
==> Downloading https://github.com/golemfactory/golem/releases/download/0.7.1/golem-macos-0.7.1.tar.gz
Already downloaded: /Users/josepita/Library/Caches/Homebrew/golem-0.7.1.tar.gz
==> Verifying golem-0.7.1.tar.gz checksum
tar xzf /Users/josepita/Library/Caches/Homebrew/golem-0.7.1.tar.gz
==> echo docker-machine-driver-xhyve need root owner and uid
docker-machine-driver-xhyve need root owner and uid
==> sudo chown root:wheel /usr/local/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve
Failed to execute: sudo chown root:wheel /usr/local/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve
Error: Failed executing: sudo chown root:wheel /usr/local/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve 
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/formula.rb:1804:in `block in system'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1742:in `open'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1742:in `system'
/usr/local/Homebrew/Library/Taps/golemfactory/homebrew-golem/golem.rb:26:in `install'
/usr/local/Homebrew/Library/Homebrew/build.rb:139:in `block (2 levels) in install'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1093:in `block in brew'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1905:in `block in stage'
/usr/local/Homebrew/Library/Homebrew/resource.rb:97:in `block in unpack'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `block in run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `chdir'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/resource.rb:93:in `unpack'
/usr/local/Homebrew/Library/Homebrew/resource.rb:85:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1884:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1088:in `brew'
/usr/local/Homebrew/Library/Homebrew/build.rb:114:in `block in install'
/usr/local/Homebrew/Library/Homebrew/utils.rb:554:in `with_env'
/usr/local/Homebrew/Library/Homebrew/build.rb:111:in `install'
/usr/local/Homebrew/Library/Homebrew/build.rb:188:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:178:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:178:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
```

#### Output of `brew cask doctor`

```
| => brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.3.1-49-gdaa0ea4
caskroom/homebrew-cask (git revision 289a9; last commit 2017-08-16)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3694 casks)
/usr/local/Homebrew/Library/Taps/golemfactory/homebrew-golem (1 cask)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Environment Variables
LC_CTYPE="UTF-8"
PATH="~/.rvm/gems/ruby-2.3.0/bin:~/.rvm/gems/ruby-2.3.0@global/bin:~/.rvm/rubies/ruby-2.3.0/bin:/usr/local/git/bin:/sw/bin:/usr/local/bin:/usr/local:/usr/local/sbin:/usr/local/mysql/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/ImageMagick/bin:~/Documents/android-sdk-macosx:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home:~/Documents/android-sdk-macosx/tools:~/Documents/android-sdk-macosx/platform-tools:~/Documents/android-sdk-macosx/build-tools:~/.rvm/bin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

**Comment by commitay** [comment]
We don't provide support for casks that are external to Homebrew-Cask.
