### ISSUE TITLE
brew cask search fails with "undefined method `map' for nil:NilClass"

### ISSUE THREAD

**Issue by fsouza** [caskroom/homebrew-cask#37793]
This _just_ start happening (like I ran `brew cask search <something>`, the ran it again two minutes later and it started failing - I _think_ I ran ``brew update`` in that interval).

#### General troubleshooting steps

- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

```
% brew cask search whatever
Error: undefined method `map' for nil:NilClass
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/search.rb:20:in `search_remote'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/search.rb:44:in `search'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/search.rb:5:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:97:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:167:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
```

#### Output of your command with `--verbose --debug`

```
% brew cask search whatever --verbose --debug
Error: undefined method `map' for nil:NilClass
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/search.rb:20:in `search_remote'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/search.rb:44:in `search'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/search.rb:5:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:97:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:167:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:178:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:178:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
```

#### Output of `brew cask doctor`

```
% brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.3.1-62-g3b92f69
caskroom/homebrew-cask (git revision a152a; last commit 2017-08-19)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (3 files, 127.4MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3699 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-fonts (1110 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (164 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Environment Variables
LANG="en_US.UTF-8"
PATH="~/.gimme/versions/go/bin:~/opt/src/chapel-code/chapel-basic/bin/darwin:~/opt/src/chapel-code/chapel-basic/util:~/bin:~/.rbenv/shims:~/.dotfiles/bin:~/.cargo/bin:/usr/local/bin:/usr/local/sbin:~/.config/yarn/global/node_modules/.bin:/usr/local/share/npm/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/cmd:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/usr/local/bin/bash"
```

**Comment by commitay** [comment]
@reitermarkus This looks like an issue with https://github.com/Homebrew/brew/pull/3054?

**Comment by vitorgalvao** [comment]
I can’t reproduce this and I’m on the same version as the OP.

**Comment by fsouza** [comment]
@vitorgalvao the issue is that I have ``HOMEBREW_NO_GITHUB_API`` defined and in this case [GitHub.open returns nil](https://github.com/Homebrew/brew/blob/3b92f69869f0bc88c2f99854392535d4d522902c/Library/Homebrew/utils/github.rb#L136).

**Comment by vitorgalvao** [comment]
That is an issue for that repo, not here. Please report it there.

**Comment by fsouza** [comment]
Returning ``nil`` is a clear intent of ``GitHub.search_code`` API. homebrew-cask should be able to handle it.

In the homebrew code base, the [code that calls ``search_code`` handles the absence of ``HOMEBREW_NO_GITHUB_API``](https://github.com/Homebrew/brew/blob/3b92f69869f0bc88c2f99854392535d4d522902c/Library/Homebrew/cmd/search.rb#L106). That is bad, as the logic to handle the environment variable is replicated.

I'd suggest a nil-check before invoking ``map``, I'm happy to send a PR if that's acceptable.

**Comment by fsouza** [comment]
Ah nevermind I didn't realize the "cask" part that calls search_code is in the brew repo. My bad x)
