### ISSUE TITLE
cask istat-menus sha256 mismatch

### ISSUE THREAD

**Issue by DrachovDmytro** [caskroom/homebrew-cask#37914]
#### General troubleshooting steps

- [ x ] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [ x ] None of the templates was appropriate for my issue, or I’m not sure.
- [ x ] I ran `brew update-reset && brew update` and retried my command.
- [ x ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [ x ] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Сan not install istat-menus via brew cask reason of sha256 mismatch.

#### Output of your command with `--verbose --debug`

```
brew cask install --verbose --debug istat-menus
==> Hbc::Installer#install
==> Printing caveats
==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://s3.amazonaws.com/bjango/files/istatmenus5/istatmenus5.32.zip
/usr/bin/curl --show-error --user-agent Homebrew/1.3.1-77-g97c75bf (Macintosh; Intel Mac OS X 10.12.6) curl/7.54.0 --fail --location --remote-time --continue-at - --output /Users/dmytro.drachov/Library/Caches/Homebrew/Cask/istat-menus--5.32.zip.incomplete https://s3.amazonaws.com/bjango/files/istatmenus5/istatmenus5.32.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 29.5M  100 29.5M    0     0  1670k      0  0:00:18  0:00:18 --:--:-- 2216k
==> Downloaded to -> /Users/dmytro.drachov/Library/Caches/Homebrew/Cask/istat-menus--5.32.zip
==> Verifying download
==> Determining which verifications to run for Cask istat-menus
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask istat-menus
==> Note: running "brew update" may fix sha256 checksum errors
Error: Checksum for Cask 'istat-menus' does not match.

Expected: 208bc52e8ae6e04e6b001f9f3da7bfd57e919625f10f582ba078ff7032609401
Actual:   ff7e9f1e315ce00c71af6365f5a829bf499589809c574879b05e2d3045020ac5
File:     /Users/dmytro.drachov/Library/Caches/Homebrew/Cask/istat-menus--5.32.zip

To retry an incomplete download, remove the file above.
Error: Install incomplete.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:13:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:97:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:167:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:172:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:172:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew-Cask Version
Homebrew-Cask 1.3.1-77-g97c75bf
caskroom/homebrew-cask (git revision bcf0e; last commit 2017-08-23)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (1 files, 29.5MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3704 casks)
/usr/local/Homebrew/Library/Taps/sbdchd/homebrew-sleep-restart-shutdown (3 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Gems/2.0.0/gems/json-1.8.3/lib
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Environment Variables
LANG="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
LC_CTYPE="UTF-8"
PATH="~/.rvm/gems/ruby-2.0.0-p648/bin:~/.rvm/gems/ruby-2.0.0-p648@global/bin:~/.rvm/rubies/ruby-2.0.0-p648/bin:~/.nvm/versions/node/v4.8.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:~/.antigen/bundles/robbyrussell/oh-my-zsh/lib:~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/git:~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/docker:~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/brew:~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/nvm:~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/node:~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/npm:~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/grunt:~/.antigen/bundles/djui/alias-tips:~/.antigen/bundles/zsh-users/zsh-completions/src:~/.antigen/bundles/zsh-users/zsh-syntax-highlighting:~/.rvm/bin:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/zsh"
```

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/37915
