### ISSUE TITLE
`curl` errors when downloading a Cask file via a URL

### ISSUE THREAD

**Issue by keyurp1987** [caskroom/homebrew-cask#38331]
#### General troubleshooting steps

- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [ ] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

USAGE.md file explains an option to download version specific cask formulae by specifying the exact commit hash in the URL like an example below. 

A curl-retrievable URI to a Cask file, eg: https://raw.githubusercontent.com/caskroom/homebrew-cask/f25b6babcd398abf48e33af3d887b2d00de1d661/Casks/google-chrome.rb

With cask version 1.3.2 this is not possible and only works with prior versions of cask. 

#### Output of your command with `--verbose --debug`
```
/usr/local/bin/brew cask install https://raw.githubusercontent.com/caskroom/homebrew-cask/b8fecc9d20d120658e1330d61886b623195d10e4/Casks/java.rb --verbose --debug
==> Downloading https://raw.githubusercontent.com/caskroom/homebrew-cask/b8fecc9d20d120658e1330d61886b623195d10e4/Casks/java.rb.
/usr/bin/curl --show-error --user-agent Homebrew/1.3.2 (Macintosh; Intel Mac OS X 10.12.6) curl/7.54.0 --fail --location --remote-time --continue-at - --output /Users/bambooagent/Library/Caches/Homebrew/Cask/java.rb https://raw.githubusercontent.com/caskroom/homebrew-cask/b8fecc9d20d120658e1330d61886b623195d10e4/Casks/java.rb
** Resuming transfer from byte position 5301
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 416
Error: Cask 'java' is unavailable: Failed to download https://raw.githubusercontent.com/caskroom/homebrew-cask/b8fecc9d20d120658e1330d61886b623195d10e4/Casks/java.rb.
Error: Install incomplete.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:13:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:97:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:167:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:172:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:172:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
```
#### Output of `brew cask doctor`
```
brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.3.2-13-g5b04152
caskroom/homebrew-cask (git revision 8f5fc; last commit 2017-09-07)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (5 files, 565.3MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3721 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Environment Variables
LANG="en_US.UTF-8"
PATH="~/.nvm/versions/node/v6.10.3/bin:~/.rbenv/shims:~/.rbenv/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

**Comment by commitay** [comment]
@keyurp1987 Complete the other steps on the checklist and post the output of `brew cask doctor`.

**Comment by keyurp1987** [comment]
Updated the comment above with required details.

**Comment by keyurp1987** [comment]
USAGE.md specifies "Other Ways to Specify a Cask" which was working fine until 1.3.1 and started failing after we upgraded to cask version 1.3.2

**Comment by commitay** [comment]
Run `brew cask cleanup` and retry the command.

**Comment by keyurp1987** [comment]
Looks like cleanup helped. I can run command successfully after cleanup. Thanks!!

**Comment by commitay** [comment]
`1.3.2`
```
brew cask install -vd https://raw.githubusercontent.com/commitay/homebrew-faucet/master/Casks/autodmg-beta.rb
==> Downloading https://raw.githubusercontent.com/commitay/homebrew-faucet/master/Casks/autodmg-beta.rb.
/usr/bin/curl --show-error --user-agent Homebrew/1.3.2 (Macintosh; Intel Mac OS X 10.12.6) curl/7.54.0 --fail --location --remote-time --continue-at - --output /Users/commitay/Library/Caches/Homebrew/Cask/autodmg-beta.rb https://raw.githubusercontent.com/commitay/homebrew-faucet/master/Casks/autodmg-beta.rb
** Resuming transfer from byte position 39369
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 416
Error: Cask 'autodmg-beta' is unavailable: Failed to download https://raw.githubusercontent.com/commitay/homebrew-faucet/master/Casks/autodmg-beta.rb.
```
___
`1.3.1`
```
brew cask install -vd https://raw.githubusercontent.com/commitay/homebrew-faucet/master/Casks/autodmg-beta.rb
==> Downloading https://raw.githubusercontent.com/commitay/homebrew-faucet/master/Casks/autodmg-beta.rb.
/usr/bin/curl --remote-time --location --user-agent Homebrew/1.3.1 (Macintosh; Intel Mac OS X 10.12.6) curl/7.54.0 --fail https://raw.githubusercontent.com/commitay/homebrew-faucet/master/Casks/autodmg-beta.rb -o /Users/commitay/Library/Caches/Homebrew/Cask/autodmg-beta.rb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   553  100   553    0     0    173      0  0:00:03  0:00:03 --:--:--   173
==> Hbc::Installer#install
==> Printing caveats
==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://github.com/MagerValp/AutoDMG/releases/download/v1.8b537/AutoDMG-1.8b537.dmg
==> Calling curl with args ["https://github.com/MagerValp/AutoDMG/releases/download/v1.8b537/AutoDMG-1.8b537.dmg", "-C", 0, "-o", #<Pathname:/Users/commitay/Library/Caches/Homebrew/Cask/autodmg-beta--1.8b537.dmg.incomplete>]
/usr/bin/curl --remote-time --location --user-agent Homebrew/1.3.1 (Macintosh; Intel Mac OS X 10.12.6) curl/7.54.0 --fail https://github.com/MagerValp/AutoDMG/releases/download/v1.8b537/AutoDMG-1.8b537.dmg -C 0 -o /Users/commitay/Library/Caches/Homebrew/Cask/autodmg-beta--1.8b537.dmg.incomplete
```

**Comment by commitay** [comment]
Ping @reitermarkus
