### ISSUE TITLE
Uninstalling GPGTools fails

### ISSUE THREAD

**Issue by boboldehampsink** [caskroom/homebrew-cask#38413]
#### General troubleshooting steps

- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Running `brew cask uninstall gpgtools` results in an error and fails

#### Output of your command with `--verbose --debug`

```
brew cask uninstall gpgtools --verbose --debug
==> Uninstalling Cask gpgtools
==> Uninstalling Cask gpgtools
==> Un-installing artifacts
==> Determining which artifacts are present in Cask gpgtools
==> 4 artifact/s defined
#<Hbc::Artifact::Uninstall:0x007fbca89dc828>
#<Hbc::Artifact::Pkg:0x007fbca89dc738>
#<Hbc::Artifact::PostflightBlock:0x007fbca89dc6c0>
#<Hbc::Artifact::Zap:0x007fbca89dc670>
==> Un-installing artifact of class Hbc::Artifact::Uninstall
==> Running uninstall process for gpgtools; your password may be necessary
==> Removing launchctl service org.gpgtools.macgpg2.shutdown-gpg-agent
==> Executing: ["/bin/launchctl", "list", "org.gpgtools.macgpg2.shutdown-gpg-agent"]
==> Executing: ["/usr/bin/sudo", "-E", "--", "/bin/launchctl", "list", "org.gpgtools.macgpg2.shutdown-gpg-agent"]
Password:
==> Removing launchctl service org.gpgtools.Libmacgpg.xpc
==> Executing: ["/bin/launchctl", "list", "org.gpgtools.Libmacgpg.xpc"]
==> Executing: ["/usr/bin/sudo", "-E", "--", "/bin/launchctl", "list", "org.gpgtools.Libmacgpg.xpc"]
==> Removing launchctl service org.gpgtools.gpgmail.enable-bundles
==> Executing: ["/bin/launchctl", "list", "org.gpgtools.gpgmail.enable-bundles"]
==> Executing: ["/usr/bin/sudo", "-E", "--", "/bin/launchctl", "list", "org.gpgtools.gpgmail.enable-bundles"]
==> Removing launchctl service org.gpgtools.gpgmail.user-uuid-patcher
==> Executing: ["/bin/launchctl", "list", "org.gpgtools.gpgmail.user-uuid-patcher"]
==> Executing: ["/usr/bin/sudo", "-E", "--", "/bin/launchctl", "list", "org.gpgtools.gpgmail.user-uuid-patcher"]
==> Removing launchctl service org.gpgtools.gpgmail.uuid-patcher
==> Executing: ["/bin/launchctl", "list", "org.gpgtools.gpgmail.uuid-patcher"]
==> Executing: ["/usr/bin/sudo", "-E", "--", "/bin/launchctl", "list", "org.gpgtools.gpgmail.uuid-patcher"]
==> Removing launchctl service org.gpgtools.macgpg2.fix
==> Executing: ["/bin/launchctl", "list", "org.gpgtools.macgpg2.fix"]
==> Executing: ["/usr/bin/sudo", "-E", "--", "/bin/launchctl", "list", "org.gpgtools.macgpg2.fix"]
==> Removing launchctl service org.gpgtools.macgpg2.updater
==> Executing: ["/bin/launchctl", "list", "org.gpgtools.macgpg2.updater"]
==> Executing: ["/usr/bin/sudo", "-E", "--", "/bin/launchctl", "list", "org.gpgtools.macgpg2.updater"]
==> Quitting application ID com.apple.mail
==> Executing: ["/bin/launchctl", "list"]
==> Quitting application ID org.gpgtools.gpgkeychainaccess
==> Executing: ["/bin/launchctl", "list"]
==> Quitting application ID org.gpgtools.gpgservices
==> Executing: ["/bin/launchctl", "list"]
==> Uninstalling packages:
==> Executing: ["/usr/sbin/pkgutil", "--pkgs=org.gpgtools.*"]
==> Removing files:
/Applications/GPG Keychain Access.app
==> Executing: ["/usr/bin/sudo", "-E", "--", "/usr/bin/xargs", "-0", "--", "/bin/rm", "-r", "-f", "--"]
/Applications/GPG Keychain.app
==> Executing: ["/usr/bin/sudo", "-E", "--", "/usr/bin/xargs", "-0", "--", "/bin/rm", "-r", "-f", "--"]
/usr/local/MacGPG2
==> Executing: ["/usr/bin/sudo", "-E", "--", "/usr/bin/xargs", "-0", "--", "/bin/rm", "-r", "-f", "--"]
/Library/Services/GPGServices.service
==> Executing: ["/usr/bin/sudo", "-E", "--", "/usr/bin/xargs", "-0", "--", "/bin/rm", "-r", "-f", "--"]
/Library/Mail/Bundles/GPGMail.mailbundle
==> Executing: ["/usr/bin/sudo", "-E", "--", "/usr/bin/xargs", "-0", "--", "/bin/rm", "-r", "-f", "--"]
/Library/PreferencePanes/GPGPreferences.prefPane
==> Executing: ["/usr/bin/sudo", "-E", "--", "/usr/bin/xargs", "-0", "--", "/bin/rm", "-r", "-f", "--"]
==> Un-installing artifact of class Hbc::Artifact::PostflightBlock
==> Executing: ["/bin/bash", "-c", "[[ \"$(/usr/bin/readlink /usr/local/bin/gpg2)\"      =~ MacGPG2 ]] && /bin/rm -- /usr/local/bin/gpg2"]
Error: Command failed to execute!

==> Failed command:
/bin/bash -c [[ "$(/usr/bin/readlink /usr/local/bin/gpg2)"      =~ MacGPG2 ]] && /bin/rm -- /usr/local/bin/gpg2

==> Standard Output of failed command:


==> Standard Error of failed command:


==> Exit status of failed command:
#<Process::Status: pid 96206 exit 1>
Error: Uninstall incomplete.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:12:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:97:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:167:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:172:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:172:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
```

#### Output of `brew cask doctor`

```
brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.3.2
caskroom/homebrew-cask (git revision 02ee3; last commit 2017-09-09)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (1 files, 21.6MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3724 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-drivers (116 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-eid (7 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-fonts (1113 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (166 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Gems/2.0.0/gems/json-1.8.2/lib
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Environment Variables
LANG="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
PATH="~/.rvm/gems/ruby-2.4.1/bin:~/.rvm/gems/ruby-2.4.1@global/bin:~/.rvm/rubies/ruby-2.4.1/bin:/usr/local/opt/node@6/bin:~/.nvm/versions/node/v6.11.2/bin:/usr/local/sbin:~/.fastlane/bin:~/.npm-packages/bin:~/google-cloud-sdk/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin:/usr/local/opt/ruby/bin:~/Library/Android/sdk:~/Library/Android/sdk/tools:~/Library/Android/sdk/platform-tools:~/.composer/vendor/bin:/Applications/Wireshark.app/Contents/MacOS:~/.rvm/bin:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/zsh"
```

**Comment by commitay** [comment]
This is an old issue that has already been fixed. https://github.com/caskroom/homebrew-cask/issues/28911

Simplest solution would be `brew cask install --force gpgtools` and then try `brew cask uninstall gpgtools` again.

**Comment by boboldehampsink** [comment]
That worked! Thanks
