### ISSUE TITLE
Package `logitech-harmony` fails with `Certificate used to sign package is not trusted`

### ISSUE THREAD

**Issue by christianharke** [caskroom/homebrew-cask#38445]
#### General troubleshooting steps

- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Installation of package `logitech-harmony` fails. (located in tap "caskroom/drivers")

#### Output of your command with `--verbose --debug`

```
> brew cask install logitech-harmony --verbose --debug
==> Hbc::Installer#install
==> Printing caveats
==> Caveats
logitech-harmony requires Java 6. You can install it with

  brew cask install caskroom/versions/java6

==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://cdn-cx-images.dynamite.myharmony.com/software/LogitechHarmonyRemoteSoftware7.8.1-OSX.dmg
Already downloaded: /Users/christian/Library/Caches/Homebrew/Cask/logitech-harmony--7.8.1.dmg
==> Downloaded to -> /Users/christian/Library/Caches/Homebrew/Cask/logitech-harmony--7.8.1.dmg
==> Verifying download
==> Determining which verifications to run for Cask logitech-harmony
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask logitech-harmony
==> SHA256 checksums match
==> Installing Cask logitech-harmony
==> Hbc::Installer#stage
==> Extracting primary container
==> Determining which containers to use based on filetype
==> Checking container class Hbc::Container::Pkg
==> Checking container class Hbc::Container::Ttf
==> Checking container class Hbc::Container::Otf
==> Checking container class Hbc::Container::Air
==> Checking container class Hbc::Container::Cab
==> Checking container class Hbc::Container::Dmg
==> Executing: ["/usr/bin/hdiutil", "imageinfo", "/Users/christian/Library/Caches/Homebrew/Cask/logitech-harmony--7.8.1.dmg"]
==> Using container class Hbc::Container::Dmg for /Users/christian/Library/Caches/Homebrew/Cask/logitech-harmony--7.8.1.dmg
==> Executing: ["/usr/bin/hdiutil", "attach", "-plist", "-nobrowse", "-readonly", "-noidme", "-mountrandom", "/var/folders/d2/38yx7krn75x6cmwp34l1ft1h0000gn/T/d20170910-31269-1h81aik", "/Users/christian/Library/Caches/Homebrew/Cask/logitech-harmony--7.8.1.dmg"]
==> Executing: ["/usr/bin/mkbom", "-s", "-i", "/var/folders/d2/38yx7krn75x6cmwp34l1ft1h0000gn/T/20170910-31269-18gj0rn.list", "--", "/var/folders/d2/38yx7krn75x6cmwp34l1ft1h0000gn/T/20170910-31269-1jdom2q.bom"]
==> Executing: ["/usr/bin/ditto", "--bom", "/var/folders/d2/38yx7krn75x6cmwp34l1ft1h0000gn/T/20170910-31269-1jdom2q.bom", "--", "/private/var/folders/d2/38yx7krn75x6cmwp34l1ft1h0000gn/T/d20170910-31269-1h81aik/dmg.QJPG9k", "/usr/local/Caskroom/logitech-harmony/7.8.1"]
==> Executing: ["/usr/sbin/diskutil", "eject", "/private/var/folders/d2/38yx7krn75x6cmwp34l1ft1h0000gn/T/d20170910-31269-1h81aik/dmg.QJPG9k"]
==> Creating metadata directory /usr/local/Caskroom/logitech-harmony/.metadata/7.8.1/20170910094130.458.
==> Creating metadata subdirectory /usr/local/Caskroom/logitech-harmony/.metadata/7.8.1/20170910094130.458/Casks.
==> Installing artifacts
==> Determining which artifacts are present in Cask logitech-harmony
==> 3 artifact/s defined
#<Hbc::Artifact::Uninstall:0x007fa227a4ca10>
#<Hbc::Artifact::Pkg:0x007fa227a4c8a8>
#<Hbc::Artifact::PostflightBlock:0x007fa227a4c790>
==> Installing artifact of class Hbc::Artifact::Pkg
==> Running installer for logitech-harmony; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
==> Executing: ["/usr/bin/sudo", "-E", "--", "/usr/sbin/installer", "-pkg", "/usr/local/Caskroom/logitech-harmony/7.8.1/LogitechRemoteSoftware.pkg", "-target", "/", "-verboseR"]
==> installer: Package name is Logitech Remote Software
==> installer: Certificate used to sign package is not trusted. Use -allowUntrusted to override.
==> Purging files for version 7.8.1 of Cask logitech-harmony
Error: Command failed to execute!

==> Failed command:
/usr/bin/sudo -E -- /usr/sbin/installer -pkg /usr/local/Caskroom/logitech-harmony/7.8.1/LogitechRemoteSoftware.pkg -target / -verboseR

==> Standard Output of failed command:
installer: Package name is Logitech Remote Software
installer: Certificate used to sign package is not trusted. Use -allowUntrusted to override.


==> Standard Error of failed command:


==> Exit status of failed command:
#<Process::Status: pid 31416 exit 1>
Error: Install incomplete.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:13:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:97:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:167:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:172:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:172:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
```

#### Output of `brew cask doctor`

```
> brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask >1.2.0 (no git repository)
caskroom/homebrew-cask (git revision 1cfa78; last commit 2017-09-10)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (51 files, 4.6GB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3726 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-drivers (116 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (166 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Environment Variables
LANG="de_CH.UTF-8"
LC_CTYPE="de_CH.UTF-8"
PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/cmd:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/zsh"
```

**Comment by commitay** [comment]
The certificate has expired. @christianharke Please contact Logitech so they can fix this. 

```
Package "LogitechRemoteSoftware.pkg":
   Status: signed by a certificate that has since expired
   Certificate Chain:
    1. Developer ID Installer: Logitech Inc.
       SHA1 fingerprint: 60 64 63 9A 8F 60 A4 AA 1A B6 E3 C6 43 CD 3E 64 5F 56 0C 30
       -----------------------------------------------------------------------------
    2. Developer ID Certification Authority
       SHA1 fingerprint: 3B 16 6C 3B 7D C4 B7 51 C9 FE 2A FA B9 13 56 41 E3 88 E1 86
       -----------------------------------------------------------------------------
    3. Apple Root CA
       SHA1 fingerprint: 61 1E 5B 66 2C 59 3A 08 FF 58 D1 4A E2 24 52 D1 98 DF 6C 60
```

**Comment by commitay** [comment]
@christianharke Any news on this?

**Comment by christianharke** [comment]
I created a support request on Logitech's community page:
https://community.logitech.com/s/question/0D55A000074YfJQ/harmony-remote-software-certificate-expired?s1oid=00Di0000000j2Ck&OpenCommentForEdit=1&s1nid=0DB31000000Go9U&emkind=chatterCommentNotification&s1uid=0055A000007yHCq&emtm=1505218588926&fromEmail=1&s1ext=0

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-drivers/pull/180.
