### ISSUE TITLE
_appcast_checkpoint fails

### ISSUE THREAD

**Issue by shoichiaizawa** [caskroom/homebrew-cask#38514]
#### General troubleshooting steps

- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

`cask-repair caskname` doesn't fetch the appcast checkpoint of an app.

I was trying to update a cask ([Now Desktop](https://github.com/zeit/now-desktop)) to the latest version using the `cask-repair` command. While the script successfully downloaded the zipped file of the requested app version, it failed to fetch the appcast checkpoint of it; here is the message printed out:

```
$ cask-repair -i now
Updating taps… Updated 1 tap (homebrew/core).
==> New Formulae
pony-stable
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
cask 'now' do
  version '2.5.0'
  sha256 '32089bde0497058db369984dd001efa60ccc290f5690f93e6cf2ba337637cca1'

  # github.com/zeit/now-desktop was verified as official when first introduced to the cask
  url "https://github.com/zeit/now-desktop/releases/download/#{version}/now-desktop-#{version}-mac.zip"
  appcast 'https://github.com/zeit/now-desktop/releases.atom',
          checkpoint: '2b012db5fee403c24704bdc95676f62bb6977f39ea6c55bf1dab78c2a13da980'
  name 'Now'
  homepage 'https://zeit.co/now'

  app 'Now.app'

  uninstall delete:     '/usr/local/bin/now',
            login_item: 'Now',
            signal:     ['TERM', 'co.zeit.now']

  zap delete: [
                '~/Library/Caches/co.zeit.now',
                '~/Library/Caches/co.zeit.now.ShipIt',
              ],
      trash:  [
                '~/.now.json',
                '~/Library/Application Support/Now',
                '~/Library/Preferences/co.zeit.now.plist',
                '~/Library/Preferences/co.zeit.now.helper.plist',
              ]
end
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Type the new version (or leave blank to use current one, or use `s` to skip)
> 2.5.2
==> Downloading external files for Cask now
==> Downloading https://github.com/zeit/now-desktop/releases/download/2.5.2/now-desktop-2.5.2-mac.zip
######################################################################## 100.0%
==> No checksum defined for Cask now, skipping verification
==> Success! Downloaded to -> /Users/sho/Library/Caches/Homebrew/Cask/now--2.5.2.zip
Error: undefined local variable or method `load_casks' for #<Hbc::CLI::InternalAppcastCheckpoint:0x007fbc6107e110>
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/internal_appcast_checkpoint.rb:15:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:97:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:167:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
diff --git a/Casks/now.rb b/Casks/now.rb
index 33986b11eb..2fbcf92390 100644
--- a/Casks/now.rb
+++ b/Casks/now.rb
@@ -1,11 +1,11 @@
 cask 'now' do
-  version '2.5.0'
-  sha256 '32089bde0497058db369984dd001efa60ccc290f5690f93e6cf2ba337637cca1'
+  version '2.5.2'
+  sha256 '6fd3dcd13a521c17e31fd7e708a71aa544633f0c5dc5ac4b9c50715c9c97259b'

   # github.com/zeit/now-desktop was verified as official when first introduced to the cask
   url "https://github.com/zeit/now-desktop/releases/download/#{version}/now-desktop-#{version}-mac.zip"
   appcast 'https://github.com/zeit/now-desktop/releases.atom',
-          checkpoint: '2b012db5fee403c24704bdc95676f62bb6977f39ea6c55bf1dab78c2a13da980'
+          checkpoint: ''
   name 'Now'
   homepage 'https://zeit.co/now'

-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
• audit for now: failed
 - appcast :checkpoint string must be of 64 hexadecimal characters
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Is everything correct? ([y]es / [n]o / [e]dit) n
error: Cannot delete branch 'master' checked out at '/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask'

You decided to abort.
```

The message above was printed when I tried to update the cask for "[Now Desktop](https://github.com/zeit/now-desktop)".

I also performed `cask-repair atom` and entered a random existing version number in order to see if the appcast checkpoint of the Atom app is fetchable but the very same thing happened to it.

I'm not certain if this error is caused by `brew cask` or `cask-repair` but I created this issue in this repository. Please direct me if this is not a right place to raise an issue.

#### Output of your command with `--verbose --debug`

```
This command is not performed.
```

#### Output of `brew cask doctor`

```
$ brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.3.2-52-gbecd8d8
caskroom/homebrew-cask (git revision 2c046; last commit 2017-09-12)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (4 files, 303.9MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3727 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-drivers (116 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-eid (7 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-fonts (1112 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (166 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Environment Variables
LANG="en_GB.UTF-8"
PATH="/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:~/.composer/vendor/bin:/usr/local/opt/android-sdk/tools:/usr/local/opt/android-sdk/platform-tools:/usr/local/share/git-core/contrib/diff-highlight:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/usr/local/bin/bash"
```

**Comment by commitay** [comment]
```
brew cask _appcast_checkpoint --calculate now
Error: undefined local variable or method `load_casks' for #<Hbc::CLI::InternalAppcastCheckpoint:0x007fd4820556a0>
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/internal_appcast_checkpoint.rb:15:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:97:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:167:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:178:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:178:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
```
