### ISSUE TITLE
brew cask audit -> Error: undefined method `call' for nil:NilClass

### ISSUE THREAD

**Issue by jgte** [caskroom/homebrew-cask#38593]
#### General troubleshooting steps

- [ x ] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [ x ] None of the templates was appropriate for my issue, or I’m not sure.
- [ x ] I ran `brew update-reset && brew update` and retried my command.
- [ x ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [ x ] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

While trying to figure out why `brew upgrade brew-cask` gives the error `Error: No available formula with the name "brew-cask"`, i tried `brew cask audit ` and got the error below. No errors from `brew doctor`.

#### Output of your command with `--verbose --debug`

```
$ brew cask audit --verbose --debug
Error: undefined method `call' for nil:NilClass
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/dsl.rb:139:in `language_eval'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/dsl.rb:120:in `language'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:123:in `block in load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask.rb:22:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask.rb:22:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:17:in `new'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:17:in `cask'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:53:in `cask'
/usr/local/Homebrew/Library/Homebrew/compat/hbc/cask_loader.rb:10:in `cask'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:98:in `cask'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:11:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:11:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:11:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:43:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:115:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:163:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/scopes.rb:9:in `map'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/scopes.rb:9:in `all'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/audit.rb:12:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:49:in `call'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:49:in `casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/audit.rb:12:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:97:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:167:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:178:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:178:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew-Cask Version
Homebrew-Cask 1.3.2-60-gaeab091
caskroom/homebrew-cask (git revision 1d58d; last commit 2017-09-14)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3731 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin15
/Library/Ruby/Site/2.0.0/universal-darwin15
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin15
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15
==> Environment Variables
LANG="en_US.UTF-8"
LANGUAGE="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
PATH="~/perl5/bin:~/.rbenv/shims:/Library/TeX/Distributions/Programs/texbin:/usr/local/bin:/usr/local/sbin:~/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/TeX/texbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

**Comment by miccal** [comment]
You most likely have something installed via `brew cask` that has been removed - please check what you have installed via Cask and check if they are still available.

**Comment by jgte** [comment]
```
$ brew cask list
basictex
$ tlmgr --version
tlmgr revision 45190 (2017-09-01 10:01:01 +0200)
tlmgr using installation: /usr/local/texlive/2017basic
TeX Live (http://tug.org/texlive) version 2017
$ ll /usr/local/texlive/2017basic
total 296
-rw-r--r--   1 root  wheel   2.0K Nov 25  2016 LICENSE.CTAN
-rw-r--r--   1 root  wheel   5.0K Nov 25  2016 LICENSE.TL
drwxr-xr-x   3 root  wheel   102B Jun  7 11:07 bin/
-rwxr-xr-x   1 root  wheel    96K May 18 16:25 install-tl*
-rw-r--r--   1 root  wheel    25K Jun  7 11:07 install-tl.log
-rw-r--r--   1 root  wheel   349B Apr 13 12:59 release-texlive.txt
drwxr-xr-x   7 root  wheel   238B Sep 13 14:54 texmf-config/
drwxr-xr-x  18 root  wheel   612B Sep 13 14:54 texmf-dist/
drwxr-xr-x   7 root  wheel   238B Sep 13 14:54 texmf-var/
-rw-r--r--   1 root  wheel   628B Jun  7 11:07 texmf.cnf
-rw-r--r--   1 root  wheel   733B Jun  7 11:07 texmfcnf.lua
drwxr-xr-x  19 root  wheel   646B Sep 13 14:54 tlpkg/
```

**Comment by miccal** [comment]
What is the output of `ls /usr/local/Caskroom`?

**Comment by jgte** [comment]
```
$ tree /usr/local/Caskroom
/usr/local/Caskroom
└── basictex
    └── 2017.0607
        └── mactex-basictex-20170607.pkg

2 directories, 1 file
```

**Comment by miccal** [comment]
Do you get the following output of `brew cask audit --verbose --debug basictex`:
```
-bash-4.4.12- /Users/miccal [> brew cask audit --verbose --debug basictex
==> Auditing Cask basictex
==> Auditing required stanzas
==> Verifying version :latest does not appear as a string ('latest')
==> Verifying version does not contain '/'
==> Verifying sha256 :no_check with version :latest
==> Verifying sha256 string is a legal SHA-256 digest
==> Verifying sha256 is not a known invalid value
==> Auditing URL format
audit for basictex: passed
```

**Comment by jgte** [comment]
Yes:
```
$ brew cask audit --verbose --debug basictex
==> Auditing Cask basictex
==> Auditing required stanzas
==> Verifying version :latest does not appear as a string ('latest')
==> Verifying version does not contain '/'
==> Verifying sha256 :no_check with version :latest
==> Verifying sha256 string is a legal SHA-256 digest
==> Verifying sha256 is not a known invalid value
==> Auditing URL format
audit for basictex: passed
```

**Comment by vitorgalvao** [comment]
Looks to me like you might have a bad cask in some tap. What’s the output of `brew tap`?

**Comment by jgte** [comment]
Good call but still got the same problem:

```
$ brew tap-info --installed
caskroom/cask: unpinned, no formulae/commands
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (4,624 files, 76.7MB)
From: https://github.com/caskroom/homebrew-cask

homebrew/boneyard: unpinned, no formulae/commands
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-boneyard (409 files, 1.2MB)
From: https://github.com/Homebrew/homebrew-boneyard

homebrew/core: unpinned, 4354 formulae
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core (4,638 files, 104.6MB)
From: https://github.com/Homebrew/homebrew-core

homebrew/dupes: unpinned, no formulae/commands
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-dupes (317 files, 281.0KB)
From: https://github.com/Homebrew/homebrew-dupes

homebrew/fuse: unpinned, no formulae/commands
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-fuse (208 files, 142.9KB)
From: https://github.com/Homebrew/homebrew-fuse

homebrew/science: unpinned, 625 formulae
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-science (7,003 files, 49.5MB)
From: https://github.com/Homebrew/homebrew-science

homebrew/x11: unpinned, no formulae/commands
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-x11 (309 files, 308.9KB)
From: https://github.com/Homebrew/homebrew-x11
$ brew untap homebrew/x11 homebrew/fuse homebrew/dupes homebrew/boneyard
Untapping homebrew/x11... (309 files, 308.9KB)
Untapped 0 formulae
Untapping homebrew/fuse... (208 files, 142.9KB)
Untapped 0 formulae
Untapping homebrew/dupes... (317 files, 281.0KB)
Untapped 0 formulae
Untapping homebrew/boneyard... (409 files, 1.2MB)
Untapped 0 formulae
$ brew tap
caskroom/cask
homebrew/core
homebrew/science
$ brew cask audit --verbose --debug
Error: undefined method `call' for nil:NilClass
[...]
```

Does this make sense?

```
$ tree -d /usr/local/Homebrew/Library/Taps
/usr/local/Homebrew/Library/Taps
├── caskroom
│   └── homebrew-cask
│       ├── Casks
│       ├── ci
│       │   └── travis
│       ├── developer
│       │   └── bin
│       └── doc
│           ├── cask_language_reference
│           │   └── stanzas
│           ├── development
│           ├── faq
│           ├── issue_templates
│           └── reporting_bugs
└── homebrew
    ├── homebrew-core
    │   ├── Aliases
    │   └── Formula
    └── homebrew-science
        ├── Aliases
        └── Requirements

21 directories
```

**Comment by miccal** [comment]
@vitorgalvao I am out of ideas, and cannot reproduce the error.

**Comment by jgte** [comment]
Thank you anyway Vitor.

**Comment by miccal** [comment]
@jgte just to be thorough, can you please post the output of `brew config`.

**Comment by jgte** [comment]
Sure, thank you.
```
$ brew config
HOMEBREW_VERSION: 1.3.2-60-gaeab091
ORIGIN: https://github.com/Homebrew/brew
HEAD: aeab09169fea05c3c5cfcde600694c45d40dd413
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 9c45b73419bc72143d85bc7ef90fc93fa4550466
Core tap last commit: 47 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.10.1 => /Library/Developer/CommandLineTools/usr/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.26.0/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/teixeira/.rbenv/shims/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
macOS: 10.11.6-x86_64
Xcode: N/A
CLT: 8.2.0.0.1.1480973914
X11: 2.7.11 => /opt/X11
```

**Comment by reitermarkus** [comment]
I think I found the bug.
