### ISSUE TITLE
android-sdk install fails: `staged_path.to_s`

### ISSUE THREAD

**Issue by nathansgreen** [caskroom/homebrew-cask#38606]
#### General troubleshooting steps

- [X] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

I attempted to install `android-sdk` and had some transient wifi problems. I stopped the install process, restarted my network, and continued the install, which appeared to complete successfully. I am now in a position where the SDK appears to be installed but `/usr/local/share/android-sdk` does not exist. I can't uninstall or reinstall because the uninstall process fails repeatedly.

#### Output of your command with `--verbose --debug`

```
==> Uninstalling Cask android-sdk
==> Uninstalling Cask android-sdk
==> Un-installing artifacts
==> Determining which artifacts are present in Cask android-sdk
==> 47 artifact/s defined
Error: undefined local variable or method `summarize' for #<Hbc::Artifact::PreflightBlock:0x007ff054219160>
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_artifact.rb:67:in `to_s'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/utils.rb:23:in `puts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/utils.rb:23:in `puts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/utils.rb:23:in `odebug'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:379:in `uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:370:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:22:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:12:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:12:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:97:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:167:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:178:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:178:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew-Cask Version
Homebrew-Cask 1.3.2-60-gaeab091
caskroom/homebrew-cask (git revision d45ec; last commit 2017-09-15)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (1 files, 49.3MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3731 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (166 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Environment Variables
LANG="en_US.UTF-8"
PATH="~/.sdkman/candidates/gradle/current/bin:~/bin:/usr/local/opt/mysql51/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/usr/local/bin/fish"
```

**Comment by commitay** [comment]
Delete `/usr/local/Caskroom/android-sdk` and try installing again.

**Comment by nathansgreen** [comment]
Now I see the following:

```
==> Downloaded to -> /Users/user/Library/Caches/Homebrew/Cask/android-sdk--3859397,26.0.1.zip
==> Verifying download
==> Determining which verifications to run for Cask android-sdk
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask android-sdk
==> SHA256 checksums match
==> Installing Cask android-sdk
==> Hbc::Installer#stage
==> Extracting primary container
==> Determining which containers to use based on filetype
==> Checking container class Hbc::Container::Pkg
==> Checking container class Hbc::Container::Ttf
==> Checking container class Hbc::Container::Otf
==> Checking container class Hbc::Container::Air
==> Checking container class Hbc::Container::Cab
==> Checking container class Hbc::Container::Dmg
==> Executing: ["/usr/bin/hdiutil", "imageinfo", "/Users/user/Library/Caches/Homebrew/Cask/android-sdk--3859397,26.0.1.zip"]
==> Checking container class Hbc::Container::SevenZip
==> Checking container class Hbc::Container::Sit
==> Checking container class Hbc::Container::Rar
==> Checking container class Hbc::Container::Zip
==> Using container class Hbc::Container::Zip for /Users/user/Library/Caches/Homebrew/Cask/android-sdk--3859397,26.0.1.zip
==> Executing: ["/usr/bin/ditto", "-x", "-k", "--", "/Users/user/Library/Caches/Homebrew/Cask/android-sdk--3859397,26.0.1.zip", "/var/folders/c2/myc2ny4n1t5bt6811_hhzttm0000gp/T/d20170914-63648-1ryynxp"]
==> Creating metadata directory /usr/local/Caskroom/android-sdk/.metadata/3859397,26.0.1/20170915032915.084.
==> Creating metadata subdirectory /usr/local/Caskroom/android-sdk/.metadata/3859397,26.0.1/20170915032915.084/Casks.
==> Installing artifacts
==> Determining which artifacts are present in Cask android-sdk
==> 47 artifact/s defined
==> Purging files for version 3859397,26.0.1 of Cask android-sdk
Error: undefined local variable or method `summarize' for #<Hbc::Artifact::PreflightBlock:0x007f9c19132b28>
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_artifact.rb:67:in `to_s'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/utils.rb:23:in `puts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/utils.rb:23:in `puts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/utils.rb:23:in `odebug'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:181:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:97:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:19:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:13:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:13:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:97:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:167:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:178:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:178:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
```

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/blob/9faf764d311cb2fc84dfda47d0ac5a6ab89ee96d/Casks/android-sdk.rb#L62

**Comment by flo-sch** [comment]
Just runned into the same issue here, using OS X 10.11.6 :

```
$ brew cask reinstall android-sdk --verbose --debug
==> Hbc::Installer#reinstall
==> Hbc::Installer#install
==> Printing caveats
==> Caveats
We will install android-sdk-tools, platform-tools, and build-tools for you.
You can control android sdk packages via the sdkmanager command.
You may want to add to your profile:
  'export ANDROID_SDK_ROOT=/usr/local/share/android-sdk'

This operation may take up to 10 minutes depending on your internet connection.
Please, be patient.

==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://dl.google.com/android/repository/sdk-tools-darwin-3859397.zip
/usr/bin/curl --show-error --user-agent Homebrew/1.3.2-65-gc0063bb (Macintosh; Intel Mac OS X 10.11.6) curl/7.43.0 --fail --location --remote-time --continue-at - --output /Users/{my-username}Library/Caches/Homebrew/Cask/android-sdk--3859397,26.0.1.zip.incomplete https://dl.google.com/android/repository/sdk-tools-darwin-3859397.zip
==> Downloaded to -> /Users/{my-username}Library/Caches/Homebrew/Cask/android-sdk--3859397,26.0.1.zip
==> Verifying download
==> Determining which verifications to run for Cask android-sdk
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask android-sdk
==> SHA256 checksums match
==> Uninstalling Cask android-sdk
==> Un-installing artifacts
==> Determining which artifacts are present in Cask android-sdk
==> 47 artifact/s defined
Error: undefined local variable or method `summarize' for #<Hbc::Artifact::PreflightBlock:0x007fbded1c5a68>
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_artifact.rb:67:in `to_s'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/utils.rb:23:in `puts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/utils.rb:23:in `puts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/utils.rb:23:in `odebug'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:379:in `uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:370:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:132:in `uninstall_existing_cask'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:93:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:121:in `reinstall'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/reinstall.rb:10:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/reinstall.rb:5:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/reinstall.rb:5:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:97:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:167:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:178:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:178:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
```

NB : Not sure if this is relevant, but here's my ruby version (I do not work with ruby in general, and it might be outdated)

```
$ ruby -v
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
```

**Comment by commitay** [comment]
Ping @reitermarkus
