### ISSUE TITLE
Application 'SmoothMouse' installation errors with brew cask

### ISSUE THREAD

**Issue by Kiehls** [caskroom/homebrew-cask#38662]
#### General troubleshooting steps

- [V] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
- [V] None of the templates was appropriate for my issue, or I’m not sure.
- [V] I ran `brew update-reset && brew update` and retried my command.
- [V] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [V] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue
Trying to install "SmoothMouse" application through brew. 
Installation was stopped and get some errors.
Just expected not install the application but, I found that this 'SmoothMouse' application was appeared in my 'System Preferences'. Also I tried to find the app in 'Finder' but, there wasn't.

#### Output of your command with `--verbose --debug`

```
installer: Package name is SmoothMouse
installer: Installing at base path /
installer:PHASE:설치 준비 중...
installer:PHASE:디스크 준비 중...
installer:PHASE:SmoothMouse 준비 중…
installer:PHASE:다른 설치가 완료되기를 기다리는 중...
installer:PHASE:설치 구성 중...
installer:STATUS:
installer:%57.517844
installer:PHASE:업데이트된 구성요소를 등록하는 중...
installer:%58.860312
installer:PHASE:업데이트된 구성요소를 등록하는 중...
installer:%60.199826
installer:PHASE:업데이트된 구성요소를 등록하는 중...
installer:%61.542643
installer:PHASE:업데이트된 구성요소를 등록하는 중...
installer:%62.886379
installer:PHASE:업데이트된 구성요소를 등록하는 중...
installer:%64.227111
installer:PHASE:업데이트된 구성요소를 등록하는 중...
installer:%65.568699
installer:PHASE:업데이트된 구성요소를 등록하는 중...
installer:%66.909644
installer:PHASE:업데이트된 구성요소를 등록하는 중...
installer:%68.251401
installer:PHASE:업데이트된 구성요소를 등록하는 중...
installer:%69.596413
installer:PHASE:업데이트된 구성요소를 등록하는 중...
installer:%70.947165
installer:PHASE:업데이트된 구성요소를 등록하는 중...
installer:%72.278602
installer:PHASE:업데이트된 구성요소를 등록하는 중...
installer:%73.618184
installer:PHASE:업데이트된 구성요소를 등록하는 중...
installer:%74.959944
installer:PHASE:업데이트된 구성요소를 등록하는 중...
installer:%76.301792
installer:PHASE:업데이트된 구성요소를 등록하는 중...
installer:%77.643571
installer:PHASE:업데이트된 구성요소를 등록하는 중...
installer:%78.985205
installer:PHASE:업데이트된 구성요소를 등록하는 중...
installer:%80.326984
installer:PHASE:업데이트된 구성요소를 등록하는 중...
installer:%81.668604
installer:PHASE:업데이트된 구성요소를 등록하는 중...
installer:%83.009380
installer:PHASE:업데이트된 구성요소를 등록하는 중...
installer:%84.186907
installer:PHASE:업데이트된 구성요소를 등록하는 중...
installer:PHASE:업데이트된 구성요소를 등록하는 중...
installer:PHASE:업데이트된 구성요소를 등록하는 중...
installer:PHASE:업데이트된 구성요소를 등록하는 중...
installer:PHASE:업데이트된 구성요소를 등록하는 중...
installer:PHASE:업데이트된 구성요소를 등록하는 중...
installer:PHASE:업데이트된 구성요소를 등록하는 중...
installer:PHASE:업데이트된 구성요소를 등록하는 중...
installer:PHASE:업데이트된 구성요소를 등록하는 중...
installer:PHASE:업데이트된 구성요소를 등록하는 중...
installer:PHASE:업데이트된 구성요소를 등록하는 중...
installer:PHASE:업데이트된 구성요소를 등록하는 중...
installer:PHASE:업데이트된 구성요소를 등록하는 중...
installer:PHASE:업데이트된 구성요소를 등록하는 중...
installer:PHASE:업데이트된 구성요소를 등록하는 중...
installer:PHASE:업데이트된 구성요소를 등록하는 중...
installer:%84.304173
installer:PHASE:패키지 스크립트 실행 중...
installer:PHASE:패키지 유효성 확인 중...
installer:%97.750000
installer: The install failed (설치 프로그램에서 오류가 발생하여 설치에 실패했습니다. 소프트웨어 제조업체에 지원을 문의하십시오.)


==> Standard Error of failed command:


==> Exit status of failed command:
#<Process::Status: pid 5225 exit 1>
Error: Install incomplete.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:13:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:97:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:167:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:172:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:172:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
```

#### Output of `brew cask doctor`
```
==> Homebrew-Cask Version
Homebrew-Cask 1.3.2
caskroom/homebrew-cask (git revision 34949; last commit 2017-09-16)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (16 files, 3.3GB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3732 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Environment Variables
LANG="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/usr/local/bin/zsh"

```

#### Problem short

> Suggesting the problem that I encountered.
> In short, I wanted to install "smoothmouse" with brew. But, brew stoped with some errors. However, In my System Preference, 'SmoothMouse' was installed. In addition, Launchpad has no 'SmoothMouse' icon.

**Comment by commitay** [comment]
`smoothmouse` doesn't work on sierra. http://smoothmouse.com/

https://github.com/caskroom/homebrew-cask/pull/38664
