### ISSUE TITLE
Wireshark is failing to install with outdated URL

### ISSUE THREAD

**Issue by robertoandrade** [caskroom/homebrew-cask#38719]
#### Description of issue

Wireshark URL is outdated, it seems to be downloaded from https://1.na.dl.wireshark.org/osx/Wireshark%202.4.1%20Intel%2064.dmg now as per the recipe defined in `homebrew-core`.

#### Output of your command with `--verbose --debug`

```
$ brew cask install wireshark --verbose --debug
==> Hbc::Installer#install
==> Printing caveats
==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://www.wireshark.org/download/osx/Wireshark%202.4.1%20Intel%2064.dmg
/usr/bin/curl --show-error --user-agent Homebrew/1.3.2 (Macintosh; Intel Mac OS X 10.12.6) curl/7.54.0 --fail --location --remote-time --continue-at - --output /Users/randrade/Library/Caches/Homebrew/Cask/wireshark--2.4.1.dmg.incomplete https://www.wireshark.org/download/osx/Wireshark%202.4.1%20Intel%2064.dmg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 503 Service Temporarily Unavailable
Error: Download failed on Cask 'wireshark' with message: Download failed: https://www.wireshark.org/download/osx/Wireshark%202.4.1%20Intel%2064.dmg
Error: Install incomplete.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:13:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:97:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:167:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:172:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:172:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew-Cask Version
Homebrew-Cask 1.3.2
caskroom/homebrew-cask (git revision 780ac; last commit 2017-09-19)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (15 files, 1GB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3736 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Environment Variables
LANG="en_US.UTF-8"
PATH="~/.nvm/versions/node/v6.11.2/bin:~/go/bin:/usr/local/Cellar/go/1.8.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Cellar/php70/7.0.22_14/bin:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

**Comment by commitay** [comment]
```
brew cask audit --download wireshark
==> Downloading https://www.wireshark.org/download/osx/Wireshark%202.4.1%20Intel
######################################################################## 100.0%
==> Verifying checksum for Cask wireshark
audit for wireshark: passed
```

**Comment by eliezio** [comment]
Still not working for me.

At wireshark.org/#download, the macOS download link is now https://1.na.dl.wireshark.org/osx/Wireshark%202.4.2%20Intel%2064.dmg
Maybe the cask should use this new/alternative download link.

$ **brew cask audit --download wireshark**
11:41:26
==> Downloading https://www.wireshark.org/download/osx/Wireshark%202.4.2%20Intel%2064.dmg

curl: (22) The requested URL returned error: 503 Service Temporarily Unavailable
audit for wireshark: failed
 - download not possible: Download failed on Cask 'wireshark' with message: Download failed: https://www.wireshark.org/download/osx/Wireshark%202.4.2%20Intel%2064.dmg
 - error retrieving appcast:
curl: (22) The requested URL returned error: 503 Service Temporarily Unavailable

 - error retrieving appcast:
curl: (22) The requested URL returned error: 503 Service Temporarily Unavailable
Error: audit failed for casks: wireshark
