### ISSUE TITLE
Cask mysteriously fails to uninstall Wireshark

### ISSUE THREAD

**Issue by alexchandel** [caskroom/homebrew-cask#38720]
#### General troubleshooting steps

- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Uninstalling Wireshark is apparently impossible:

```
➜  ~ brew cask install wireshark
Warning: Cask 'wireshark' is already installed.

To re-install wireshark, run:
  brew cask reinstall wireshark
➜  ~ brew cask uninstall wireshark
==> Uninstalling Cask wireshark
==> Running uninstall process for wireshark; your password may be necessary
==> Running uninstall script /usr/sbin/dseditgroup
==> Username and password must be provided.
Error: Command failed to execute!

==> Failed command:
/usr/sbin/dseditgroup -o delete access_bpf

==> Standard Output of failed command:


==> Standard Error of failed command:
Username and password must be provided.


==> Exit status of failed command:
#<Process::Status: pid 3716 exit 64>
➜  ~ sudo brew cask uninstall wireshark
Password:
Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.
```

The Wireshark app exists, but Homebrew-Cask can't remove it (even with sudo), or install a new version if it's manually removed.

#### Output of your command with `--verbose --debug`

```
➜  ~ brew cask uninstall wireshark --verbose --debug
==> Uninstalling Cask wireshark
==> Uninstalling Cask wireshark
==> Un-installing artifacts
==> Determining which artifacts are present in Cask wireshark
==> 3 artifact/s defined
:script => [:executable, "/usr/sbin/dseditgroup"], :script => [:args, ["-o", "delete", "access_bpf"]], :pkgutil => "org.wireshark.*", :delete => "/usr/local/bin/capinfos", :delete => "/usr/local/bin/dftest", :delete => "/usr/local/bin/dumpcap", :delete => "/usr/local/bin/editcap", :delete => "/usr/local/bin/mergecap", :delete => "/usr/local/bin/randpkt", :delete => "/usr/local/bin/rawshark", :delete => "/usr/local/bin/text2pcap", :delete => "/usr/local/bin/tshark", :delete => "/usr/local/bin/wireshark",  (Uninstall)
Wireshark 2.2.3 Intel 64.pkg (Pkg)
postflight (Postflight Block)
==> Un-installing artifact of class Hbc::Artifact::Uninstall
==> Running uninstall process for wireshark; your password may be necessary
==> Running uninstall script /usr/sbin/dseditgroup
==> Executing: ["/bin/chmod", "--", "+x", "/usr/sbin/dseditgroup"]
==> Executing: ["/usr/sbin/dseditgroup", "-o", "delete", "access_bpf"]
==> Username and password must be provided.
Error: Command failed to execute!

==> Failed command:
/usr/sbin/dseditgroup -o delete access_bpf

==> Standard Output of failed command:


==> Standard Error of failed command:
Username and password must be provided.


==> Exit status of failed command:
#<Process::Status: pid 4477 exit 64>

/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:65:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:36:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb:199:in `uninstall_script'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb:53:in `block in dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb:50:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb:50:in `dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall.rb:7:in `uninstall_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:384:in `block in uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:381:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:381:in `uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:370:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:22:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:12:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:12:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:97:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:167:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:172:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:172:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
```

#### Output of `brew cask doctor`

```
➜  ~ brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.3.2-80-g81d9f71
caskroom/homebrew-cask (git revision 780ac; last commit 2017-09-19)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (1 files, 33.6MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3736 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (167 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Environment Variables
LANG="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
PATH="~/bin:~/Cape/bin:~/.cargo/bin:~/.cabal/bin:/usr/local/share/npm/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Wireshark.app/Contents/MacOS:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/zsh"
```

**Comment by commitay** [comment]
Please try:

```
$ brew cask install --force wireshark

$ brew cask uninstall wireshark
```

**Comment by optix2000** [comment]
+1 on the same issue.

@commitay's steps works around the issue.

IMHO, the `uninstall_preflight` probably shouldn't be run (or shouldn't fail, a la `|| true`) if the `access_bpf` group doesn't exist, such as during a failed install.

This issue is reproducible by attempting to install wireshark through `brew cask install wireshark`, and then bailing out of the install when the password prompt comes up with Ctrl+C (such that the group is never created)

**Comment by commitay** [comment]
No response from OP, closing.
___
@optix2000 In this case it is an older install of `wireshark` failing because `dseditgroup` wasn't run with `sudo`.

> ==> Standard Error of failed command:
Username and password must be provided.
____
> `uninstall_preflight` probably shouldn't be run (or shouldn't fail

https://github.com/caskroom/homebrew-cask/pull/39110

https://github.com/caskroom/homebrew-cask/blob/4221499638215a2922e0d09f1800ed9d645c33d2/Casks/wireshark.rb#L47-L52
