### ISSUE TITLE
brew cask install little-snitch: Operation not permitted

### ISSUE THREAD

**Issue by fnkr** [caskroom/homebrew-cask#38901]
#### General troubleshooting steps

- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Installation of `little-snitch` fails on MacOS 10.12.6.

#### Output of your command with `--verbose --debug`

```
$ brew cask install --verbose --debug little-snitch
==> Hbc::Installer#install
==> Printing caveats
==> Caveats
You must reboot for the installation of little-snitch to take effect.

==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://www.obdev.at/downloads/littlesnitch/LittleSnitch-4.0.3.dmg
Already downloaded: /Users/fnkr/Library/Caches/Homebrew/Cask/little-snitch--4.0.3.dmg
==> Downloaded to -> /Users/fnkr/Library/Caches/Homebrew/Cask/little-snitch--4.0.3.dmg
==> Verifying download
==> Determining which verifications to run for Cask little-snitch
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask little-snitch
==> SHA256 checksums match
==> Installing Cask little-snitch
==> Hbc::Installer#stage
==> Extracting primary container
==> Determining which containers to use based on filetype
==> Checking container class Hbc::Container::Pkg
==> Checking container class Hbc::Container::Ttf
==> Checking container class Hbc::Container::Otf
==> Checking container class Hbc::Container::Air
==> Checking container class Hbc::Container::Cab
==> Checking container class Hbc::Container::Dmg
==> Executing: ["/usr/bin/hdiutil", "imageinfo", "/Users/fnkr/Library/Caches/Homebrew/Cask/little-snitch--4.0.3.dmg"]
==> Using container class Hbc::Container::Dmg for /Users/fnkr/Library/Caches/Homebrew/Cask/little-snitch--4.0.3.dmg
==> Executing: ["/usr/bin/hdiutil", "attach", "-plist", "-nobrowse", "-readonly", "-noidme", "-mountrandom", "/var/folders/l2/g6wnzp8148dfhvws1k3b1w9h0000gn/T/d20170924-10492-ceyt3r", "/Users/fnkr/Library/Caches/Homebrew/Cask/little-snitch--4.0.3.dmg"]
==> Executing: ["/usr/bin/mkbom", "-s", "-i", "/var/folders/l2/g6wnzp8148dfhvws1k3b1w9h0000gn/T/20170924-10492-1p6od3u.list", "--", "/var/folders/l2/g6wnzp8148dfhvws1k3b1w9h0000gn/T/20170924-10492-zrqyt8.bom"]
==> Executing: ["/usr/bin/ditto", "--bom", "/var/folders/l2/g6wnzp8148dfhvws1k3b1w9h0000gn/T/20170924-10492-zrqyt8.bom", "--", "/private/var/folders/l2/g6wnzp8148dfhvws1k3b1w9h0000gn/T/d20170924-10492-ceyt3r/dmg.iXv5A9", "/usr/local/Caskroom/little-snitch/4.0.3"]
==> ditto: /usr/local/Caskroom/little-snitch/4.0.3/Little Snitch Installer.app/Contents/Resources/Little Snitch Agent.app/Contents/PkgInfo: Operation not permitted
==> ditto: /usr/local/Caskroom/little-snitch/4.0.3/Little Snitch Installer.app/Contents/Resources/Little Snitch Configuration.app/Contents/PkgInfo: Operation not permitted
==> ditto: /usr/local/Caskroom/little-snitch/4.0.3/Little Snitch Installer.app/Contents/Resources/Little Snitch Helper.app/Contents/PkgInfo: Operation not permitted
==> ditto: /usr/local/Caskroom/little-snitch/4.0.3/Little Snitch Installer.app/Contents/Resources/Little Snitch Network Monitor.app/Contents/PkgInfo: Operation not permitted
==> ditto: /usr/local/Caskroom/little-snitch/4.0.3/Little Snitch Installer.app/Contents/Resources/Little Snitch Software Update.app/Contents/PkgInfo: Operation not permitted
==> ditto: /usr/local/Caskroom/little-snitch/4.0.3/Little Snitch Installer.app/Contents/Resources/Little Snitch Uninstaller.app/Contents/PkgInfo: Operation not permitted
==> ditto: /usr/local/Caskroom/little-snitch/4.0.3/Little Snitch Uninstaller.app/Contents/PkgInfo: Operation not permitted
==> Executing: ["/usr/sbin/diskutil", "eject", "/private/var/folders/l2/g6wnzp8148dfhvws1k3b1w9h0000gn/T/d20170924-10492-ceyt3r/dmg.iXv5A9"]
==> Purging files for version 4.0.3 of Cask little-snitch
Error: Command failed to execute!

==> Failed command:
/usr/bin/ditto --bom /var/folders/l2/g6wnzp8148dfhvws1k3b1w9h0000gn/T/20170924-10492-zrqyt8.bom -- /private/var/folders/l2/g6wnzp8148dfhvws1k3b1w9h0000gn/T/d20170924-10492-ceyt3r/dmg.iXv5A9 /usr/local/Caskroom/little-snitch/4.0.3

==> Standard Output of failed command:


==> Standard Error of failed command:
ditto: /usr/local/Caskroom/little-snitch/4.0.3/Little Snitch Installer.app/Contents/Resources/Little Snitch Agent.app/Contents/PkgInfo: Operation not permitted
ditto: /usr/local/Caskroom/little-snitch/4.0.3/Little Snitch Installer.app/Contents/Resources/Little Snitch Configuration.app/Contents/PkgInfo: Operation not permitted
ditto: /usr/local/Caskroom/little-snitch/4.0.3/Little Snitch Installer.app/Contents/Resources/Little Snitch Helper.app/Contents/PkgInfo: Operation not permitted
ditto: /usr/local/Caskroom/little-snitch/4.0.3/Little Snitch Installer.app/Contents/Resources/Little Snitch Network Monitor.app/Contents/PkgInfo: Operation not permitted
ditto: /usr/local/Caskroom/little-snitch/4.0.3/Little Snitch Installer.app/Contents/Resources/Little Snitch Software Update.app/Contents/PkgInfo: Operation not permitted
ditto: /usr/local/Caskroom/little-snitch/4.0.3/Little Snitch Installer.app/Contents/Resources/Little Snitch Uninstaller.app/Contents/PkgInfo: Operation not permitted
ditto: /usr/local/Caskroom/little-snitch/4.0.3/Little Snitch Uninstaller.app/Contents/PkgInfo: Operation not permitted


==> Exit status of failed command:
#<Process::Status: pid 10636 exit 1>

/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:65:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:36:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:18:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/container/dmg.rb:95:in `block (2 levels) in extract_mount'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/tempfile.rb:295:in `open'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/container/dmg.rb:90:in `block in extract_mount'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/tempfile.rb:295:in `open'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/container/dmg.rb:87:in `extract_mount'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/container/dmg.rb:20:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/container/dmg.rb:20:in `block in extract'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/container/dmg.rb:56:in `block in mount'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/container/dmg.rb:31:in `mount'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/container/dmg.rb:17:in `extract'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:173:in `extract_primary_container'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:75:in `stage'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:96:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:19:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:13:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:13:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:97:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:167:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:172:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:172:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
```

```
$ sudo brew cask install little-snitch
Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.
```

#### Output of `brew cask doctor`

```
$ brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.3.3-32-gcd1cb70
caskroom/homebrew-cask (git revision ecd7f; last commit 2017-09-24)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (39 files, 1.5GB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3742 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-drivers (116 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-fonts (1114 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (169 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/universal-darwin9.0
==> Environment Variables
LANG="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
PATH="~/bin:~/.local/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/zsh"
```

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/38905
