### ISSUE TITLE
Travis CI

### ISSUE THREAD

**Issue by commitay** [caskroom/homebrew-cask#38950]
https://github.com/Homebrew/brew/pull/3183 is causing Travis to fail.

```
Running before_script.sh...
>>> export BRANCH_COMMIT=f99f5406a19871fe109a032dacfc77daa003dcd4
>>> export TARGET_COMMIT=4b4391d28161b94dc59f82b3cb2058ccda35de10
>>> MERGE_BASE="$(git merge-base "${BRANCH_COMMIT}" "${TARGET_COMMIT}")"
>>> export MERGE_BASE=4b4391d28161b94dc59f82b3cb2058ccda35de10
>>> export TRAVIS_COMMIT_RANGE=4b4391d28161b94dc59f82b3cb2058ccda35de10...f99f5406a19871fe109a032dacfc77daa003dcd4
>>> export SYSTEM_RUBY_HOME=/System/Library/Frameworks/Ruby.framework/Versions/Current
>>> export SYSTEM_RUBY_BINDIR=/System/Library/Frameworks/Ruby.framework/Versions/Current/usr/bin
>>> export SYSTEM_GEM_HOME=/System/Library/Frameworks/Ruby.framework/Versions/Current/usr/lib/ruby/gems/2.0.0
>>> export SYSTEM_GEM_BINDIR=/System/Library/Frameworks/Ruby.framework/Versions/Current/usr/lib/ruby/gems/2.0.0/bin
>>> export GEM_HOME=/Users/travis/.gem/ruby/2.0.0
>>> export GEM_BINDIR=/Users/travis/.gem/ruby/2.0.0/bin
>>> export GEM_PATH=/Users/travis/.gem/ruby/2.0.0:/System/Library/Frameworks/Ruby.framework/Versions/Current/usr/lib/ruby/gems/2.0.0
>>> export PATH=/Users/travis/.gem/ruby/2.0.0/bin:/System/Library/Frameworks/Ruby.framework/Versions/Current/usr/lib/ruby/gems/2.0.0/bin:/System/Library/Frameworks/Ruby.framework/Versions/Current/usr/bin:/Users/travis/bin:/Users/travis/.local/bin:/Users/travis/.nvm/versions/node/v6.9.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/travis/.rvm/bin
>>> export HOMEBREW_RUBY_PATH=/System/Library/Frameworks/Ruby.framework/Versions/Current/usr/bin/ruby
>>> export HOMEBREW_DEVELOPER=1
>>> brew update
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': /usr/local/Homebrew/Library/Homebrew/os/mac.rb:107: syntax error, unexpected '.' (SyntaxError)
      s&.path
         ^
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Homebrew/Library/Homebrew/os.rb:17:in `<module:OS>'
	from /usr/local/Homebrew/Library/Homebrew/os.rb:3:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Homebrew/Library/Homebrew/extend/os/emoji.rb:1:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Homebrew/Library/Homebrew/emoji.rb:14:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Homebrew/Library/Homebrew/utils.rb:2:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:4:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Homebrew/Library/Homebrew/global.rb:5:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:17:in `<main>'
/Users/travis/build/caskroom/homebrew-cask/ci/travis/helpers.sh: line 57: shell_session_update: command not found
```

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/38951

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/38968
