### ISSUE TITLE
Skim app fails to install with sha256 error, without reporting underlying cause

### ISSUE THREAD

**Issue by meling** [caskroom/homebrew-cask#39059]
#### General troubleshooting steps

- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

I get a SHA256 checksum error on Skim version 1.4.29, which is apparently the same version as the latest one released and available on this page: https://sourceforge.net/projects/skim-app/files/

Turns out that looking into what was actually downloaded, reveals the cause of the problem (see below). It would be nice, if instead of simply reporting a SHA256 error, which immediately makes me suspicious, the brew tool could suggest to the user that perhaps checking the content of the downloaded file for possible error messages, especially if the file length is shorter than say 2000 bytes or something. 

On another note, and probably related to the below error message, it seems that the sourceforge page of the Skim app is unavailable.

```
% cat /Users/meling/Library/Caches/Homebrew/Cask/skim--1.4.29.dmg
<html><head>
<title>SourceForge</title>
<!-- <script src="/js/jquery.com/jquery-1.11.0.min.js"></script> -->
<script src="https://code.jquery.com/jquery-1.11.0.min.js"></script>
<script src="https://sourceforge.net/js/mirrors.js"></script>
<script src="/js/sf.js"></script>
<script>
var DR_loc = DR_parse_hash_url();
if (DR_loc) {
    DR_sf_main(DR_loc);
} else {
    window.location.href = 'https://sourceforge.net/home.html';
}
</script>
</head><body>
<noscript>
We're sorry -- the Sourceforge site is currently in Disaster Recovery mode, and currently requires
the use of javascript to function.  Please check back later.
</noscript>
</body></html>
```

#### Output of your command with `--verbose --debug`

```
==> Hbc::Installer#install
==> Printing caveats
==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://downloads.sourceforge.net/skim-app/Skim/Skim-1.4.29/Skim-1.4.29.dmg
Already downloaded: /Users/meling/Library/Caches/Homebrew/Cask/skim--1.4.29.dmg
==> Downloaded to -> /Users/meling/Library/Caches/Homebrew/Cask/skim--1.4.29.dmg
==> Verifying download
==> Determining which verifications to run for Cask skim
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask skim
==> Note: running "brew update" may fix sha256 checksum errors
Error: Checksum for Cask 'skim' does not match.

Expected: 64c00d39a0f39ab5cc616bdf3b45e63c39d0d0becdbadd4ee6edd9263766e051
Actual:   7a07d3f7cca5c0b38ca811984ef8da536da32932d68c1a6cce33ec2462b930bf
File:     /Users/meling/Library/Caches/Homebrew/Cask/skim--1.4.29.dmg

To retry an incomplete download, remove the file above.

/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/verify/checksum.rb:42:in `verify_checksum'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/verify/checksum.rb:22:in `verify'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/verify.rb:21:in `block in all'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/verify.rb:19:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/verify.rb:19:in `all'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:155:in `verify'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:69:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:92:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:19:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:13:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:13:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:97:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:167:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:172:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:172:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
```

#### Output of `brew cask doctor`

```
Warning: Python is installed at /Library/Frameworks/Python.framework

Homebrew only supports building against the System-provided Python or a
brewed Python. In particular, Pythons installed to /Library can interfere
with other software installs.
```

**Comment by reitermarkus** [comment]
Does the server return an HTTP error status?

**Comment by miccal** [comment]
Sourceforge is having issues at the moment - give it a few days and it should hopefully all return to normal.

**Comment by adidalal** [comment]
Looks okay now

```
[~] > cask audit skim --download
==> Downloading https://downloads.sourceforge.net/skim-app/Skim/Skim-1.4.29/Skim
######################################################################## 100.0%
==> Verifying checksum for Cask skim
audit for skim: passed
```
