### ISSUE TITLE
Run into error when installing "presentation"

### ISSUE THREAD

**Issue by chuanconggao** [caskroom/homebrew-cask#39155]
#### General troubleshooting steps

- [X] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [X] None of the templates was appropriate for my issue, or I’m not sure.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Cannot install `presentation`. Not sure whether it is because of the French character in app name `Présentation.app`. All other formulas work fine.

#### Output of your command with `--verbose --debug`

```
==> Hbc::Installer#install
==> Printing caveats
==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading http://iihm.imag.fr/blanch/software/osx-presentation/releases/osx-presentation-1.7.dmg
Already downloaded: /Users/chuancong/Library/Caches/Homebrew/Cask/presentation--1.7.dmg
==> Downloaded to -> /Users/chuancong/Library/Caches/Homebrew/Cask/presentation--1.7.dmg
==> Verifying download
==> Determining which verifications to run for Cask presentation
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask presentation
==> SHA256 checksums match
==> Installing Cask presentation
==> Hbc::Installer#stage
==> Extracting primary container
==> Determining which containers to use based on filetype
==> Checking container class Hbc::Container::Pkg
==> Checking container class Hbc::Container::Ttf
==> Checking container class Hbc::Container::Otf
==> Checking container class Hbc::Container::Air
==> Checking container class Hbc::Container::Cab
==> Checking container class Hbc::Container::Dmg
==> Executing: ["/usr/bin/hdiutil", "imageinfo", "/Users/chuancong/Library/Caches/Homebrew/Cask/presentation--1.7.dmg"]
==> Using container class Hbc::Container::Dmg for /Users/chuancong/Library/Caches/Homebrew/Cask/presentation--1.7.dmg
==> Executing: ["/usr/bin/hdiutil", "attach", "-plist", "-nobrowse", "-readonly", "-noidme", "-mountrandom", "/var/folders/m9/g8b5vs4n6xgdkhkltjh88f040000gn/T/d20170930-96313-9ip3rp", "/Users/chuancong/Library/Caches/Homebrew/Cask/presentation--1.7.dmg"]
==> Executing: ["/usr/bin/mkbom", "-s", "-i", "/var/folders/m9/g8b5vs4n6xgdkhkltjh88f040000gn/T/20170930-96313-1744k0.list", "--", "/var/folders/m9/g8b5vs4n6xgdkhkltjh88f040000gn/T/20170930-96313-1w2tvk7.bom"]
==> Executing: ["/usr/bin/ditto", "--bom", "/var/folders/m9/g8b5vs4n6xgdkhkltjh88f040000gn/T/20170930-96313-1w2tvk7.bom", "--", "/private/var/folders/m9/g8b5vs4n6xgdkhkltjh88f040000gn/T/d20170930-96313-9ip3rp/dmg.TDUJpW", "/usr/local/Caskroom/presentation/1.7"]
==> Executing: ["/usr/sbin/diskutil", "eject", "/private/var/folders/m9/g8b5vs4n6xgdkhkltjh88f040000gn/T/d20170930-96313-9ip3rp/dmg.TDUJpW"]
==> Creating metadata directory /usr/local/Caskroom/presentation/.metadata/1.7/20171001005008.282.
==> Creating metadata subdirectory /usr/local/Caskroom/presentation/.metadata/1.7/20171001005008.282/Casks.
==> Installing artifacts
==> Determining which artifacts are present in Cask presentation
==> 1 artifact/s defined
Présentation.app (App)
==> Installing artifact of class Hbc::Artifact::App
==> Purging files for version 1.7 of Cask presentation
Error: It seems the App source '/usr/local/Caskroom/presentation/1.7/Présentation.app' is not there.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/moved.rb:37:in `move'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/moved.rb:11:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:191:in `block in install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:183:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:183:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:97:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:19:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:13:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:13:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:97:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:167:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:172:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:172:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew-Cask Version
Homebrew-Cask 1.3.4
caskroom/homebrew-cask (git revision 6353e; last commit 2017-10-01)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (1 files, 86.8KB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3753 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (175 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin17
/Library/Ruby/Site/2.3.0/universal-darwin17
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin17
==> Environment Variables
LANG="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
PATH="~/.go/bin:/usr/local/opt/python/libexec/bin:/usr/local/opt/coreutils/libexec/gnubin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/share/dotnet:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-command-not-found/cmd:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/usr/local/bin/zsh"
```

**Comment by commitay** [comment]
This is strange, it seems the `app` isn't copied from the `dmg` to `/usr/local/Caskroom`.

The `dmg`  contains the `app` but `/usr/local/Caskroom/presentation/1.7` is an empty folder.

**Comment by chuanconggao** [comment]
I confirmed the same issue on another Mac with freshly installed Homebrew Cask.

**Comment by miccal** [comment]
```
-bash-4.4.12- /Users/miccal [> brew cask install --verbose presentation
==> Satisfying dependencies
==> Downloading http://iihm.imag.fr/blanch/software/osx-presentation/releases/osx-presentation-1.7.dmg
/usr/bin/curl --show-error --user-agent Homebrew/1.3.4-53-ge7cf509 (Macintosh; Intel Mac OS X 10.12.6) curl/7.54.0 --fail --location --remote-time --continue-at - --output /Users/miccal/Library/Caches/Homebrew/Cask/presentation--1.7.dmg.incomplete http://iihm.imag.fr/blanch/software/osx-presentation/releases/osx-presentation-1.7.dmg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 88904  100 88904    0     0  34784      0  0:00:02  0:00:02 --:--:-- 34796
==> Verifying checksum for Cask presentation
==> Installing Cask presentation
Error: It seems the App source '/usr/local/Caskroom/presentation/1.7/Présentation.app' is not there.
Error: Kernel.exit
-bash-4.4.12- /Users/miccal [> open /Users/miccal/Library/Caches/Homebrew/Cask/presentation--1.7.dmg
-bash-4.4.12- /Users/miccal [> cd /Volumes
-bash-4.4.12- /Volumes [> ls
arreis			osx-presentation-1.7
-bash-4.4.12- /Volumes [> cd osx-presentation-1.7
-bash-4.4.12- /Volumes/osx-presentation-1.7 [> ls
Applications		Présentation.app
```

**Comment by commitay** [comment]
> Very weird - it must have something to do with the French character in app name?

I've tried this with `stage_only true` and still get an empty folder.

**Comment by vitorgalvao** [comment]
This is a core bug. It happens on `Homebrew-Cask 1.3.4` but not on `Homebrew-Cask 1.3.2` (my VM was still on `1.3.2`).

Ping @reitermarkus.

**Comment by commitay** [comment]
Possibly related: https://github.com/caskroom/homebrew-cask/commit/2c27db310955c564ea7fad2dbd031516926c238e, doesn't occur if I switch to `1.3.2`.

**Comment by reitermarkus** [comment]
Doesn't work for me on neither 1.3.4 nor on 1.3.2.

**Comment by reitermarkus** [comment]
```
$ echo 'é' > /tmp/a
$ echo 'é' > /tmp/b
$ diff /tmp/a /tmp/b
```
