### ISSUE TITLE
paragon-extfs and paragon-ntfs license manager problem at run time

### ISSUE THREAD

**Issue by ydesgagn** [caskroom/homebrew-cask#39176]
#### General troubleshooting steps
- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
- [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

brew cask install paragon-extfs paragon-ntfs

Both will install fine without any issue. When you open the icon in the system preference to add you license code you get an error that the application cannot fin the license manger and that it must be re-installed.

Failed to connect to licensing tool. Please re-install the software!

Not sure what package are used for the installation but when I use the packages from the Paragon website I don't have this error.

#### Output of your command with `--verbose --debug`

```
Command run well without --debug

brew cask install --verbose paragon-extfs paragon-ntfs
==> Satisfying dependencies
==> Downloading http://dl.paragon-software.com/demo/trial_extfs11.dmg
Already downloaded: /Users/yves/Library/Caches/Homebrew/Cask/paragon-extfs--11.dmg
==> No checksum defined for Cask paragon-extfs, skipping verification
==> Installing Cask paragon-extfs
==> Extracting nested container FSInstaller.app/Contents/Resources/product.zip
==> Running installer for paragon-extfs; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
==> installer: Package name is product
==> installer: Installing at base path /
==> installer:PHASE:Preparing for installation…
==> installer:PHASE:Preparing the disk…
==> installer:PHASE:Preparing product…
==> installer:PHASE:Waiting for other installations to complete…
==> installer:PHASE:Configuring the installation…
==> installer:STATUS:
==> installer:%7.240679
==> installer:PHASE:Writing files…
==> installer:%12.110306
==> installer:PHASE:Writing files…
==> installer:PHASE:Writing files…
==> installer:%31.661025
==> installer:PHASE:Running package scripts…
==> installer:%61.634387
==> installer:PHASE:Running package scripts…
==> installer:%62.853878
==> installer:PHASE:Running package scripts…
==> installer:%63.241389
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:%63.558462
==> installer:PHASE:Registering updated components…
==> installer:%64.775879
==> installer:PHASE:Registering updated components…
==> installer:%65.994978
==> installer:PHASE:Registering updated components…
==> installer:%67.214408
==> installer:PHASE:Registering updated components…
==> installer:%68.433626
==> installer:PHASE:Registering updated components…
==> installer:%69.653528
==> installer:PHASE:Registering updated components…
==> installer:%70.872471
==> installer:PHASE:Registering updated components…
==> installer:%72.080368
==> installer:PHASE:Registering updated components…
==> installer:%73.305980
==> installer:PHASE:Registering updated components…
==> installer:%74.515315
==> installer:PHASE:Registering updated components…
==> installer:%75.732437
==> installer:PHASE:Registering updated components…
==> installer:%76.951521
==> installer:PHASE:Registering updated components…
==> installer:%78.177012
==> installer:PHASE:Registering updated components…
==> installer:%79.385804
==> installer:PHASE:Registering updated components…
==> installer:%80.605760
==> installer:PHASE:Registering updated components…
==> installer:%81.825071
==> installer:PHASE:Registering updated components…
==> installer:%83.044287
==> installer:PHASE:Registering updated components…
==> installer:%84.263420
==> installer:PHASE:Registering updated components…
==> installer:%85.472093
==> installer:PHASE:Registering updated components…
==> installer:%86.692034
==> installer:PHASE:Registering updated components…
==> installer:%87.589523
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:%92.880373
==> installer:PHASE:Updating preboot volume…
==> installer:PHASE:Updating preboot volume…
==> installer:PHASE:Updating preboot volume…
==> installer:PHASE:Updating preboot volume…
==> installer:PHASE:Updating preboot volume…
==> installer:PHASE:Updating preboot volume…
==> installer:PHASE:Validating packages…
==> installer:%97.750000
==> installer:STATUS:
==> installer:PHASE:Finishing the Installation…
==> installer:STATUS:
==> installer:%100.000000
==> installer:PHASE:The software was successfully installed.
==> installer: The install was successful.
🍺  paragon-extfs was successfully installed!
==> Satisfying dependencies
==> Downloading http://dl.paragon-software.com/demo/ntfsmac15_trial.dmg
Already downloaded: /Users/yves/Library/Caches/Homebrew/Cask/paragon-ntfs--15.dmg
==> No checksum defined for Cask paragon-ntfs, skipping verification
==> Installing Cask paragon-ntfs
==> Extracting nested container FSInstaller.app/Contents/Resources/product.zip
==> Running installer for paragon-ntfs; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
==> installer: Package name is product
==> installer: Upgrading at base path /
==> installer:PHASE:Preparing for installation…
==> installer:PHASE:Preparing the disk…
==> installer:PHASE:Preparing product…
==> installer:PHASE:Waiting for other installations to complete…
==> installer:PHASE:Configuring the installation…
==> installer:STATUS:
==> installer:%9.609715
==> installer:PHASE:Writing files…
==> installer:%12.045018
==> installer:PHASE:Writing files…
==> installer:PHASE:Writing files…
==> installer:PHASE:Writing files…
==> installer:PHASE:Writing files…
==> installer:%14.480320
==> installer:PHASE:Writing files…
==> installer:%24.237407
==> installer:PHASE:Moving items into place…
==> installer:%61.521799
==> installer:PHASE:Running package scripts…
==> installer:%62.739803
==> installer:PHASE:Running package scripts…
==> installer:%63.478732
==> installer:PHASE:Registering updated components…
==> installer:%64.698823
==> installer:PHASE:Registering updated components…
==> installer:%65.919436
==> installer:PHASE:Registering updated components…
==> installer:%67.131710
==> installer:PHASE:Registering updated components…
==> installer:%68.350632
==> installer:PHASE:Registering updated components…
==> installer:%69.569988
==> installer:PHASE:Registering updated components…
==> installer:%70.790934
==> installer:PHASE:Registering updated components…
==> installer:%71.997378
==> installer:PHASE:Registering updated components…
==> installer:%73.223078
==> installer:PHASE:Registering updated components…
==> installer:%74.443486
==> installer:PHASE:Registering updated components…
==> installer:%75.651600
==> installer:PHASE:Registering updated components…
==> installer:%76.870155
==> installer:PHASE:Registering updated components…
==> installer:%78.090567
==> installer:PHASE:Registering updated components…
==> installer:%79.310727
==> installer:PHASE:Registering updated components…
==> installer:%80.530387
==> installer:PHASE:Registering updated components…
==> installer:%81.743460
==> installer:PHASE:Registering updated components…
==> installer:%82.965312
==> installer:PHASE:Registering updated components…
==> installer:%84.174934
==> installer:PHASE:Registering updated components…
==> installer:%85.392441
==> installer:PHASE:Registering updated components…
==> installer:%86.614305
==> installer:PHASE:Registering updated components…
==> installer:%87.539387
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:PHASE:Registering updated components…
==> installer:%92.879396
==> installer:PHASE:Updating preboot volume…
==> installer:PHASE:Updating preboot volume…
==> installer:PHASE:Updating preboot volume…
==> installer:PHASE:Updating preboot volume…
==> installer:PHASE:Updating preboot volume…
==> installer:PHASE:Updating preboot volume…
==> installer:PHASE:Validating packages…
==> installer:%97.750000
==> installer:STATUS:
==> installer:PHASE:Finishing the Installation…
==> installer:STATUS:
==> installer:%100.000000
==> installer:PHASE:The software was successfully installed.
==> installer: The upgrade was successful.
🍺  paragon-ntfs was successfully installed!

With --debug I get the following error

brew cask install --verbose --debug paragon-extfs paragon-ntfs
==> Hbc::Installer#install
==> Printing caveats
==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading http://dl.paragon-software.com/demo/trial_extfs11.dmg
Already downloaded: /Users/yves/Library/Caches/Homebrew/Cask/paragon-extfs--11.dmg
==> Downloaded to -> /Users/yves/Library/Caches/Homebrew/Cask/paragon-extfs--11.dmg
==> Verifying download
==> Determining which verifications to run for Cask paragon-extfs
==> Checking for verification class Hbc::Verify::Checksum
==> No checksum defined for Cask paragon-extfs, skipping verification
==> 0 verifications defined
==> Installing Cask paragon-extfs
==> Hbc::Installer#stage
==> Extracting primary container
==> Determining which containers to use based on filetype
==> Checking container class Hbc::Container::Pkg
==> Checking container class Hbc::Container::Ttf
==> Checking container class Hbc::Container::Otf
==> Checking container class Hbc::Container::Air
==> Checking container class Hbc::Container::Cab
==> Checking container class Hbc::Container::Dmg
==> Executing: ["/usr/bin/hdiutil", "imageinfo", "/Users/yves/Library/Caches/Homebrew/Cask/paragon-extfs--11.dmg"]
==> Using container class Hbc::Container::Dmg for /Users/yves/Library/Caches/Homebrew/Cask/paragon-extfs--11.dmg
==> Executing: ["/usr/bin/hdiutil", "attach", "-plist", "-nobrowse", "-readonly", "-noidme", "-mountrandom", "/var/folders/x1/75j814094ss9fx30js8rqqv40000gn/T/d20171001-15911-vbpcah", "/Users/yves/Library/Caches/Homebrew/Cask/paragon-extfs--11.dmg"]
==> Executing: ["/usr/bin/mkbom", "-s", "-i", "/var/folders/x1/75j814094ss9fx30js8rqqv40000gn/T/20171001-15911-ehjfki.list", "--", "/var/folders/x1/75j814094ss9fx30js8rqqv40000gn/T/20171001-15911-i68ihm.bom"]
==> Executing: ["/usr/bin/ditto", "--bom", "/var/folders/x1/75j814094ss9fx30js8rqqv40000gn/T/20171001-15911-i68ihm.bom", "--", "/private/var/folders/x1/75j814094ss9fx30js8rqqv40000gn/T/d20171001-15911-vbpcah/dmg.V0wyvP", "/usr/local/Caskroom/paragon-extfs/11"]
==> Executing: ["/usr/sbin/diskutil", "eject", "/private/var/folders/x1/75j814094ss9fx30js8rqqv40000gn/T/d20171001-15911-vbpcah/dmg.V0wyvP"]
==> Creating metadata directory /usr/local/Caskroom/paragon-extfs/.metadata/11/20171001135155.110.
==> Creating metadata subdirectory /usr/local/Caskroom/paragon-extfs/.metadata/11/20171001135155.110/Casks.
==> Installing artifacts
==> Determining which artifacts are present in Cask paragon-extfs
==> 4 artifact/s defined
:kext => "com.paragon-software.filesystems.extfs", :launchctl => "com.paragon-software.extfs*", :pkgutil => "com.paragon-software.pkg.extfs", :quit => "com.paragon-software.extfs*", :signal => ["KILL", "com.paragon-software.extfs.FSMenuApp"], :signal => ["KILL", "com.paragon-software.extfs.notification-agent"] (Uninstall)
==> Purging files for version 11 of Cask paragon-extfs
Error: undefined local variable or method `summarize' for #<Hbc::Artifact::NestedContainer:0x007fc2620dc920>
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_artifact.rb:67:in `to_s'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/utils.rb:23:in `puts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/utils.rb:23:in `puts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/utils.rb:23:in `odebug'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:181:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:97:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:19:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:13:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:13:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:97:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:167:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:178:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:178:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
```

#### Output of `brew cask doctor`

```
brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.3.4
caskroom/homebrew-cask (git revision a691; last commit 2017-10-01)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (4 files, 483.8MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3752 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-fonts (1117 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (175 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin17
/Library/Ruby/Site/2.3.0/universal-darwin17
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin17
==> Environment Variables
LANG="en_CA.UTF-8"
PATH="/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/libexec:/Applications/VMware Fusion.app/Contents/Public:/usr/local/MacGPG2/bin:/opt/X11/bin:/Applications/Server.app/Contents/ServerRoot/usr/bin:/Applications/Server.app/Contents/ServerRoot/usr/sbin:/Applications/Wireshark.app/Contents/MacOS:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-command-not-found/cmd:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

**Comment by commitay** [comment]
This was working fine a couple of months ago but I can reproduce the same error now. It seems that the installer `app` now runs the licensing component so these will have to be changed to `installer manual`
