### ISSUE TITLE
brew cask install android-sdk fails

### ISSUE THREAD

**Issue by julienschmidt** [caskroom/homebrew-cask#39238]
#### General troubleshooting steps

- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [X] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

The installation of the SDK fails with `java.lang.NoClassDefFoundError`
I'm on macOS 10.13.

#### Output of your command with `--verbose --debug`

```
$ brew cask install android-sdk --verbose --debug
==> Hbc::Installer#install
==> Printing caveats
==> Caveats
We will install android-sdk-tools, platform-tools, and build-tools for you.
You can control android sdk packages via the sdkmanager command.
You may want to add to your profile:
  'export ANDROID_SDK_ROOT=/usr/local/share/android-sdk'

This operation may take up to 10 minutes depending on your internet connection.
Please, be patient.

==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://dl.google.com/android/repository/sdk-tools-darwin-3859397.zip
Already downloaded: /Users/julienschmidt/Library/Caches/Homebrew/Cask/android-sdk--3859397,26.0.2.zip
==> Downloaded to -> /Users/julienschmidt/Library/Caches/Homebrew/Cask/android-sdk--3859397,26.0.2.zip
==> Verifying download
==> Determining which verifications to run for Cask android-sdk
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask android-sdk
==> SHA256 checksums match
==> Installing Cask android-sdk
==> Hbc::Installer#stage
==> Extracting primary container
==> Determining which containers to use based on filetype
==> Checking container class Hbc::Container::Pkg
==> Checking container class Hbc::Container::Ttf
==> Checking container class Hbc::Container::Otf
==> Checking container class Hbc::Container::Air
==> Checking container class Hbc::Container::Cab
==> Checking container class Hbc::Container::Dmg
==> Executing: ["/usr/bin/hdiutil", "imageinfo", "/Users/julienschmidt/Library/Caches/Homebrew/Cask/android-sdk--3859397,26.0.2.zip"]
==> Checking container class Hbc::Container::SevenZip
==> Checking container class Hbc::Container::Sit
==> Checking container class Hbc::Container::Rar
==> Checking container class Hbc::Container::Zip
==> Using container class Hbc::Container::Zip for /Users/julienschmidt/Library/Caches/Homebrew/Cask/android-sdk--3859397,26.0.2.zip
==> Executing: ["/usr/bin/ditto", "-x", "-k", "--", "/Users/julienschmidt/Library/Caches/Homebrew/Cask/android-sdk--3859397,26.0.2.zip", "/var/folders/rl/px24cl7d5jv9y1hhyhnfnjsh0000gn/T/d20171003-31227-ci9ovi"]
==> Creating metadata directory /usr/local/Caskroom/android-sdk/.metadata/3859397,26.0.2/20171003111249.616.
==> Creating metadata subdirectory /usr/local/Caskroom/android-sdk/.metadata/3859397,26.0.2/20171003111249.616/Casks.
==> Installing artifacts
==> Determining which artifacts are present in Cask android-sdk
==> 47 artifact/s defined
preflight (Preflight Block)
/usr/local/Caskroom/android-sdk/3859397,26.0.2/build-tools/26.0.2/aapt (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.2/build-tools/26.0.2/aapt2 (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.2/build-tools/26.0.2/aarch64-linux-android-ld (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.2/build-tools/26.0.2/aidl (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.2/build-tools/26.0.2/arm-linux-androideabi-ld (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.2/build-tools/26.0.2/bcc_compat (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.2/build-tools/26.0.2/dexdump (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.2/build-tools/26.0.2/dx (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.2/build-tools/26.0.2/i686-linux-android-ld (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.2/build-tools/26.0.2/llvm-rs-cc (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.2/build-tools/26.0.2/mainDexClasses (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.2/build-tools/26.0.2/mipsel-linux-android-ld (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.2/build-tools/26.0.2/split-select (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.2/build-tools/26.0.2/x86_64-linux-android-ld (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.2/build-tools/26.0.2/zipalign (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.2/emulator/bin64/e2fsck (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.2/emulator/bin64/fsck.ext4 (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.2/emulator/bin64/mkfs.ext4 (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.2/emulator/bin64/resize2fs (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.2/emulator/bin64/tune2fs (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.2/emulator/emulator (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.2/emulator/emulator-check (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.2/emulator/emulator64-arm (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.2/emulator/emulator64-crash-service (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.2/emulator/emulator64-mips (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.2/emulator/emulator64-x86 (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.2/emulator/mksdcard (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.2/platform-tools/adb (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.2/platform-tools/dmtracedump (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.2/platform-tools/etc1tool (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.2/platform-tools/fastboot (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.2/platform-tools/hprof-conv (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.2/platform-tools/systrace/systrace.py (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.2/tools/android (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.2/tools/bin/archquery (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.2/tools/bin/avdmanager (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.2/tools/bin/jobb (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.2/tools/bin/lint (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.2/tools/bin/monkeyrunner (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.2/tools/bin/screenshot2 (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.2/tools/bin/sdkmanager (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.2/tools/bin/uiautomatorviewer (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.2/tools/mksdcard (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.2/tools/monitor (Binary)
postflight (Postflight Block)
uninstall_postflight (Postflight Block)
==> Installing artifact of class Hbc::Artifact::PreflightBlock
==> Executing: ["/usr/local/Caskroom/android-sdk/3859397,26.0.2/tools/bin/sdkmanager", "tools", "platform-tools", "build-tools;26.0.2"]
==> Exception in thread "main"
==> java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
==> 	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
==> 	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
==> 	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
==> 	at com.android.sdklib.tool.SdkManagerCli.main(SdkManagerCli.java:117)
==> 	at com.android.sdklib.tool.SdkManagerCli.main(SdkManagerCli.java:93)
==> Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
==> 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
==> 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
==> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
==> 	... 5 more
==> Purging files for version 3859397,26.0.2 of Cask android-sdk
Error: Command failed to execute!

==> Failed command:
/usr/local/Caskroom/android-sdk/3859397,26.0.2/tools/bin/sdkmanager tools platform-tools build-tools;26.0.2

==> Standard Output of failed command:


==> Standard Error of failed command:
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.SdkManagerCli.main(SdkManagerCli.java:117)
	at com.android.sdklib.tool.SdkManagerCli.main(SdkManagerCli.java:93)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 5 more


==> Exit status of failed command:
#<Process::Status: pid 31293 exit 1>

/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:65:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:36:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:18:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/dsl/base.rb:14:in `system_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:68:in `block (2 levels) in load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_flight_block.rb:44:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_flight_block.rb:44:in `abstract_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_flight_block.rb:28:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:191:in `block in install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:183:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:183:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:97:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:19:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:13:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:13:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:97:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:167:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:99:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:172:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:172:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:99:in `<main>'
```

#### Output of `brew cask doctor`

```
$ brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.3.4-61-gec0d8fa
caskroom/homebrew-cask (git revision 7cddb; last commit 2017-10-03)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (4 files, 645.9MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3756 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (176 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin17
/Library/Ruby/Site/2.3.0/universal-darwin17
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin17
==> Environment Variables
LANG="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
PATH="/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/bin:/sbin:/usr/local/go/bin:~/Development/go/bin:~/Development/android-sdk-macosx/tools:~/Development/android-sdk-macosx/platform-tools:/Library/TeX/Distributions/.DefaultTeX/Contents/Programs/texbin:~/.cargo/bin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/zsh"
```

**Comment by commitay** [comment]
I'm assuming from https://github.com/caskroom/homebrew-cask/issues/39213 that you have Java 9 installed, please retry with Java 8.

**Comment by julienschmidt** [comment]
That might be it. This issue seems to be a duplicate anyway. Sorry!

**Comment by Alhadis** [comment]
Is it necessary to leave Java 9 uninstalled, then? If so, for how long?

Just concerned about possible security risks brought about by old versions (especially from Java, of all things).
