### ISSUE TITLE
cask uninstall google-photos-backup fails, breaks other parts of cask

### ISSUE THREAD

**Issue by BenjaminHCCarr** [caskroom/homebrew-cask#39245]
#### General troubleshooting steps

- [X] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [X] None of the templates was appropriate for my issue, or I’m not sure.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

```
brew cask uninstall google-photos-backup
Error: Cask 'google-photos-backup' is unavailable: No Cask with this name exists.
```

As Google moved to `Photos and Backup Sync` and away from separate packages I am left with a "stub" cask that I can't uninstall and is breaking other things:

```
benc$ brew cask list
Error: Cask 'google-photos-backup' is unavailable: No Cask with this name exists.
```

homebrew-core added a search function to `.git` to be able to remove old poackage or add to your own repo. Possibly need to `fork` that into caskroom. Or provide a `google-photos-backup` stub cask with no install and a *GIANT* caveat about the migration, to facilitate an upgrade path to `google-photos-backup-and-sync` or at least a means to uninstall  `google-photos-backup` as it's causing me all kinds of headaches, which means it's likely to cause problems for users as well.

#### Output of your command with `--verbose --debug`

```
benc$ brew cask --verbose --debug uninstall google-photos-backup 
Error: Cask 'google-photos-backup' is unavailable: No Cask with this name exists. Did you mean “google-photos-backup-and-sync”?
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:53:in `rescue in casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:48:in `casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:12:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:97:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:167:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:99:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:172:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:172:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:99:in `<main>'
```

#### Output of `brew cask doctor`

```
benc$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Python is installed at /Library/Frameworks/Python.framework

Homebrew only supports building against the System-provided Python or a
brewed Python. In particular, Pythons installed to /Library can interfere
with other software installs.

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  docker
  docker-compose

Warning: Some installed formula are missing dependencies.
You should `brew install` the missing dependencies:
  brew install mysql

Run `brew missing` for more details.
```

**Comment by commitay** [comment]
Should be `brew cask doctor` not `brew doctor`
____

Try removing `/usr/local/Caskroom/google-photos-backup`

**Comment by BenjaminHCCarr** [comment]
bah, sorry:

```
 benc$ brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.3.4-63-g7ee86cf
caskroom/homebrew-cask (git revision 6a0db0; last commit 2017-10-04)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3756 casks)
/usr/local/Homebrew/Library/Taps/alehouse/homebrew-unofficial (41 casks)
/usr/local/Homebrew/Library/Taps/benjaminhccarr/homebrew-cask (9 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-drivers (117 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-eid (9 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-fonts (1117 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (176 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/universal-darwin9.0
==> Environment Variables
LANG="en_US.UTF-8"
PATH="/usr/local/opt/gettext/bin:/usr/local/opt/curl/bin:/usr/local/opt/qt/bin:/usr/local/bin:/usr/local/sbin:~/bin:/usr/local/opt/ccache/libexec:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Applications/Server.app/Contents/ServerRoot/usr/bin:/Applications/Server.app/Contents/ServerRoot/usr/sbin:/usr/local/m-cli:/usr/local/MacGPG2/bin:/Library/TeX/texbin:/Applications/Wireshark.app/Contents/MacOS:~/Documents/Projects/CAMEO/bin:~/Code/github/m-cli:/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask/developer/bin:/opt/metasploit-framework/bin:/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd:/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/cmd:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-aliases/cmd:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-command-not-found/cmd:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-dev-tools/cmd:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-livecheck/cmd:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

**Comment by BenjaminHCCarr** [comment]
Removing `/usr/local/Caskroom/google-photos-backup` worked.

Still I think a `stub` for `google-photos-backup.rb` with that as a CAVEAT might be useful. I didn't know the move out of Caskroom trick, so I doubt people using and not PR'ing will.

**Comment by commitay** [comment]
There are several previous discussion of this error but I can't find the right one to link to.

Basically this is a low priority to fix because it only happens occasionally. The correct solution would be to improve how `brew cask [list|outdated|{etc}] handles deleted Casks.

**Comment by miccal** [comment]
@commitay @vitorgalvao it might be advisable to add this to the [Reporting bugs](https://github.com/caskroom/homebrew-cask/blob/master/README.md#reporting-bugs) section of the `README.md`?

**Comment by vitorgalvao** [comment]
I’d say this issue is a cousin of https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/uninstall_wrongly_reports_cask_as_not_installed.md#uninstall-wrongly-reports-cask-as-not-installed. But yes, we can add it to the reporting bugs section.
