### ISSUE TITLE
Unable to install the grads cask

### ISSUE THREAD

**Issue by OmenWild** [caskroom/homebrew-cask#39506]
#### General troubleshooting steps

- [X] I have retried my command with `--force` and the issue is still present.
- [X] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [X] None of the templates was appropriate for my issue, or I’m not sure.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

I am unable to install the grads cask: 

> Error: It seems the symlink source '/usr/local/Caskroom/grads/2.1.0/bin/bufrscan' is not there.

I get the exact same error on two different machines. One brand new laptop running Sierra and a freshly installed brew, and one older one, but upgraded to High Sierra.

None of the above debug steps fixed the issue.

#### Output of your command with `--verbose --debug`

```
0 > brew cask install --verbose --debug grads
==> Hbc::Installer#install
==> Printing caveats
==> Caveats
In order to use the GrADS tools, you will need
the GrADS fonts and maps data sets, and may need
to set some environmental variables.

See the documentation at:

  /usr/local/Caskroom/grads/2.1.0/bin/INSTALL

==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading ftp://cola.gmu.edu/grads/2.1/grads-2.1.0-bin-darwin13.4.tar.gz
/usr/bin/curl --show-error --user-agent Homebrew/1.3.5-4-g56458f0 (Macintosh; Intel Mac OS X 10.13) curl/7.54.0 --fail --location --remote-time --continue-at - --output /Users/omen/Library/Caches/Homebrew/Cask/grads--2.1.0.tar.gz.incomplete ftp://cola.gmu.edu/grads/2.1/grads-2.1.0-bin-darwin13.4.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 5674k  100 5674k    0     0  1108k      0  0:00:05  0:00:05 --:--:-- 1174k
==> Downloaded to -> /Users/omen/Library/Caches/Homebrew/Cask/grads--2.1.0.tar.gz
==> Verifying download
==> Determining which verifications to run for Cask grads
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask grads
==> SHA256 checksums match
==> Installing Cask grads
==> Hbc::Installer#stage
==> Extracting primary container
==> Determining which containers to use based on filetype
==> Checking container class Hbc::Container::Pkg
==> Checking container class Hbc::Container::Ttf
==> Checking container class Hbc::Container::Otf
==> Checking container class Hbc::Container::Air
==> Checking container class Hbc::Container::Cab
==> Checking container class Hbc::Container::Dmg
==> Executing: ["/usr/bin/hdiutil", "imageinfo", "/Users/omen/Library/Caches/Homebrew/Cask/grads--2.1.0.tar.gz"]
==> Checking container class Hbc::Container::SevenZip
==> Checking container class Hbc::Container::Sit
==> Checking container class Hbc::Container::Rar
==> Checking container class Hbc::Container::Zip
==> Checking container class Hbc::Container::Xar
==> Checking container class Hbc::Container::Tar
==> Using container class Hbc::Container::Tar for /Users/omen/Library/Caches/Homebrew/Cask/grads--2.1.0.tar.gz
==> Executing: ["/usr/bin/tar", "-x", "-f", "/Users/omen/Library/Caches/Homebrew/Cask/grads--2.1.0.tar.gz", "-C", "/Users/omen/tmp/d20171010-7700-1my2713"]
==> Executing: ["/usr/bin/ditto", "--", "/Users/omen/tmp/d20171010-7700-1my2713", "/usr/local/Caskroom/grads/2.1.0"]
==> Creating metadata directory /usr/local/Caskroom/grads/.metadata/2.1.0/20171010203418.467.
==> Creating metadata subdirectory /usr/local/Caskroom/grads/.metadata/2.1.0/20171010203418.467/Casks.
==> Installing artifacts
==> 7 artifact/s defined
#<SortedSet:0x007f920d39c758>
==> Installing artifact of class Hbc::Artifact::Binary
==> Purging files for version 2.1.0 of Cask grads
Error: It seems the symlink source '/usr/local/Caskroom/grads/2.1.0/bin/bufrscan' is not there.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/symlinked.rb:40:in `link'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/binary.rb:7:in `link'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/symlinked.rb:15:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:191:in `block in install_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:183:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:97:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:19:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:13:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:13:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:97:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:167:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:99:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:172:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:172:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:99:in `<main>'
```

#### Output of `brew cask doctor`

```
0 > brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.3.5-4-g56458f0
caskroom/homebrew-cask (git revision b520f; last commit 2017-10-11)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (1 files, 5.5MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3762 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin17
/Library/Ruby/Site/2.3.0/universal-darwin17
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin17
==> Environment Variables
LANG="en_US.UTF-8"
PATH="/usr/local/opt/coreutils/libexec/gnubin:~/bin:~/bin/zsh:/usr/local/bin:/sbin:/usr/sbin:/usr/bin:/bin:/usr/X11R6/bin:.:/Library/Frameworks/Mono.framework/Versions/Current/bin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/usr/local/bin/zsh"
```

Thanks,
   Omen

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/39511
