### ISSUE TITLE
Outdated cask: wondershare-video-converter-ultimate

### ISSUE THREAD

**Issue by balazs630** [caskroom/homebrew-cask#39640]
[wondershare-video-converter-ultimate](https://videoconverter.wondershare.com)

On `brew cask install wondershare-video-converter-ultimate` it downloads the latest version (5.7.2,735), but it fails to install due to checksum mismatch: brew update didn't fix the issue for me.

**Error**: Checksum for Cask 'wondershare-video-converter-ultimate' does not match.
**Expected**: d8e5d2359d89d53f917d8722d9f9fb3e6c40d1d9fd44431b121d192b0fd404d6
**Actual**:   a7b9e39bdb7022014a36f10b4257f78c4b52a6636988895cc6caa846d713d617
**File**:     /Users/balazs630/Library/Caches/Homebrew/Cask/wondershare-video-converter-ultimate--5.7.2,735.dmg
To retry an incomplete download, remove the file above.

**Comment by vitorgalvao** [comment]
> [If you ignore this guide, your issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

Also note from that document:

> If the maintainer was wrong in closing your issue, please do reply stating why! Closing an issue does not mean the conversation is over. If the guides themselves were unclear, help us improve them! Open *first* an issue or pull request stating what you found confusing *and only then* your other issue.

**Comment by ppo** [comment]
**Error:** `Checksum for Cask 'wondershare-video-converter-ultimate' does not match.`  
**Command:** `brew cask install wondershare-video-converter-ultimate`  
**Output of command:**

```
==> Hbc::Installer#install
==> Printing caveats
==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading http://download.wondershare.com/cbs_down/video-converter-ultimate-mac_full735.dmg
/usr/bin/curl -q --show-error --user-agent Homebrew/1.6.1-16-g7166289 (Macintosh; Intel Mac OS X 10.13.4) curl/7.54.0 --fail --location --remote-time --continue-at - --output ~/Library/Caches/Homebrew/Cask/wondershare-video-converter-ultimate--5.7.2,735.dmg.incomplete http://download.wondershare.com/cbs_down/video-converter-ultimate-mac_full735.dmg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 91.4M  100 91.4M    0     0  6585k      0  0:00:14  0:00:14 --:--:-- 6015k
==> Downloaded to -> ~/Library/Caches/Homebrew/Cask/wondershare-video-converter-ultimate--5.7.2,735.dmg
==> Verifying download
==> Determining which verifications to run for Cask wondershare-video-converter-ultimate
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask wondershare-video-converter-ultimate
==> Note: running "brew update" may fix sha256 checksum errors
Error: Checksum for Cask 'wondershare-video-converter-ultimate' does not match.

Expected: a7b9e39bdb7022014a36f10b4257f78c4b52a6636988895cc6caa846d713d617
Actual:   71afe2815bd00791113c8e9cdb09cc10eecdd1c1681565bd0a59ca64299a9b00
File:     ~/Library/Caches/Homebrew/Cask/wondershare-video-converter-ultimate--5.7.2,735.dmg

To retry an incomplete download, remove the file above.

/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/verify/checksum.rb:42:in `verify_checksum'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/verify/checksum.rb:22:in `verify'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/verify.rb:21:in `block in all'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/verify.rb:19:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/verify.rb:19:in `all'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:138:in `verify'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:52:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:75:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:20:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:101:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:101:in `<main>'
```
