### ISSUE TITLE
Virtual box install is broken for me 

### ISSUE THREAD

**Issue by fxfactorial** [caskroom/homebrew-cask#39856]
Brew doctor is fine, 
(This is preventing my desire of getting genymotion)
here is output of `brew cask install virtualbox --force --verbose --debug`

```
brew cask install virtualbox --force --verbose --debug                                                                                    ⏎
==> Hbc::Installer#install
==> Printing caveats
==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading http://download.virtualbox.org/virtualbox/5.2.0/VirtualBox-5.2.0-118431-OSX.dmg
Already downloaded: /Users/Edgar/Library/Caches/Homebrew/Cask/virtualbox--5.2.0-118431.dmg
==> Downloaded to -> /Users/Edgar/Library/Caches/Homebrew/Cask/virtualbox--5.2.0-118431.dmg
==> Verifying download
==> Determining which verifications to run for Cask virtualbox
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask virtualbox
==> SHA256 checksums match
==> Installing Cask virtualbox
==> Hbc::Installer#stage
==> Extracting primary container
==> Determining which containers to use based on filetype
==> Checking container class Hbc::Container::Pkg
==> Checking container class Hbc::Container::Ttf
==> Checking container class Hbc::Container::Otf
==> Checking container class Hbc::Container::Air
==> Checking container class Hbc::Container::Cab
==> Checking container class Hbc::Container::Dmg
==> Executing: ["/usr/bin/hdiutil", "imageinfo", "/Users/Edgar/Library/Caches/Homebrew/Cask/virtualbox--5.2.0-118431.dmg"]
==> Using container class Hbc::Container::Dmg for /Users/Edgar/Library/Caches/Homebrew/Cask/virtualbox--5.2.0-118431.dmg
==> Executing: ["/usr/bin/hdiutil", "attach", "-plist", "-nobrowse", "-readonly", "-noidme", "-mountrandom", "/var/folders/31/fdpzgydn611cp5mly2p9hv3c0000gn/T/d20171020-6978-11pm27t", "/Users/Edgar/Library/Caches/Homebrew/Cask/virtualbox--5.2.0-118431.dmg"]
==> Executing: ["/usr/bin/find", ".", "-print0"]
==> Executing: ["/usr/bin/mkbom", "-s", "-i", "/var/folders/31/fdpzgydn611cp5mly2p9hv3c0000gn/T/20171020-6978-1sljuet.list", "--", "/var/folders/31/fdpzgydn611cp5mly2p9hv3c0000gn/T/20171020-6978-bs3e9f.bom"]
==> Executing: ["/usr/bin/ditto", "--bom", "/var/folders/31/fdpzgydn611cp5mly2p9hv3c0000gn/T/20171020-6978-bs3e9f.bom", "--", "/private/var/folders/31/fdpzgydn611cp5mly2p9hv3c0000gn/T/d20171020-6978-11pm27t/dmg.GFZd3n", "/usr/local/Caskroom/virtualbox/5.2.0-118431"]
==> Executing: ["/usr/sbin/diskutil", "eject", "/private/var/folders/31/fdpzgydn611cp5mly2p9hv3c0000gn/T/d20171020-6978-11pm27t/dmg.GFZd3n"]
==> Creating metadata directory /usr/local/Caskroom/virtualbox/.metadata/5.2.0-118431/20171020180915.030.
==> Creating metadata subdirectory /usr/local/Caskroom/virtualbox/.metadata/5.2.0-118431/20171020180915.030/Casks.
==> Installing artifacts
==> 4 artifact/s defined
#<SortedSet:0x00000101a0b5e8>
==> Installing artifact of class Hbc::Artifact::PreflightBlock
==> Installing artifact of class Hbc::Artifact::Pkg
==> Running installer for virtualbox; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
==> Executing: ["/usr/bin/sudo", "-E", "--", "/usr/sbin/installer", "-pkg", "/usr/local/Caskroom/virtualbox/5.2.0-118431/VirtualBox.pkg", "-target", "/", "-verboseR"]
==> installer: Package name is Oracle VM VirtualBox
==> installer: Installing at base path /
==> installer:PHASE:Preparing for installation…
==> installer:PHASE:Preparing the disk…
==> installer:PHASE:Preparing Oracle VM VirtualBox…
==> installer:PHASE:Waiting for other installations to complete…
==> installer:PHASE:Configuring the installation…
==> installer:STATUS:
==> installer:%14.488431
==> installer:PHASE:Writing files…
==> installer:%37.607304
==> installer:PHASE:Writing files…
==> installer:%86.159668
==> installer:PHASE:Running package scripts…
==> installer:%87.205371
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Validating packages…
==> installer:%97.750000
==> installer: The install failed (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.)
==> Reverting installation of artifact of class Hbc::Artifact::PreflightBlock
==> Purging files for version 5.2.0-118431 of Cask virtualbox
Error: Command failed to execute!

==> Failed command:
/usr/bin/sudo -E -- /usr/sbin/installer -pkg /usr/local/Caskroom/virtualbox/5.2.0-118431/VirtualBox.pkg -target / -verboseR

==> Standard Output of failed command:
installer: Package name is Oracle VM VirtualBox
installer: Installing at base path /
installer:PHASE:Preparing for installation…
installer:PHASE:Preparing the disk…
installer:PHASE:Preparing Oracle VM VirtualBox…
installer:PHASE:Waiting for other installations to complete…
installer:PHASE:Configuring the installation…
installer:STATUS:
installer:%14.488431
installer:PHASE:Writing files…
installer:%37.607304
installer:PHASE:Writing files…
installer:%86.159668
installer:PHASE:Running package scripts…
installer:%87.205371
installer:PHASE:Running package scripts…
installer:PHASE:Validating packages…
installer:%97.750000
installer: The install failed (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.)


==> Standard Error of failed command:


==> Exit status of failed command:
#<Process::Status: pid 7104 exit 1>

/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:76:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:36:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:18:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/pkg.rb:53:in `block in run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/pkg.rb:59:in `with_choices_file'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/pkg.rb:51:in `run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/pkg.rb:32:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:191:in `block in install_artifacts'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:183:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:97:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:19:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:13:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:13:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:97:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:167:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:99:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:172:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:172:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:99:in `<main>'
```

**Comment by commitay** [comment]
You haven't provided `brew cask doctor` (which was requested in the issue template) but I'm assuming that you are on 10.13.

See https://github.com/caskroom/homebrew-cask/issues/39369#issuecomment-334744335

- [ ] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

**Comment by fxfactorial** [comment]
@commitay sorry, I thought saying `Brew doctor is fine,` was enough: 

```
brew cask doctor                                                                                                                  ⏎
==> Homebrew-Cask Version
Homebrew-Cask 1.3.6-26-g6fe7c5f
caskroom/homebrew-cask (git revision 8ef8a; last commit 2017-10-20)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (1 files, 92MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3758 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (173 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/universal-darwin9.0
==> Environment Variables
LANG="en_US.UTF-8"
PATH="~/.opam/latest/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/lib/ruby/gems/2.2.0/bin:/usr/local/opt/ruby@2.2/bin:~/.yarn/bin:~/.fastlane/bin:~/.local/bin:~/.cabal/bin:/Applications/ghc-7.10.2.app/Contents/bin:/usr/local/Cellar/curl/7.46.0/bin:~/.opam/4.02.3+32bit/lib/android-ndk/toolchains/arm-linux-androideabi-4.8/prebuilt/darwin-x86/bin:/opt/theos/bin:~/Library/Android/sdk/tools:~/Library/Android/sdk/tools/bin:~/Library/Android/sdk/platform-tools:/opt/android-ndk-r10e/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin:/opt/android-ndk-r10e/toolchains/x86-4.9/prebuilt/darwin-x86_64/bin:~/Library/Android/sdk/build-tools/26.0.1/:/Applications/Eclipse Java.app/Contents/Eclipse/plugins/org.eclim_2.7.0/bin:~/go/bin:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/zsh"
```

**Comment by driesvints** [comment]
@fxfactorial how did you get it to work? I still can't install it even with the suggestions posted above...

**Comment by driesvints** [comment]
Link to stackoverflow issue: https://stackoverflow.com/questions/46832838/virtualbox-install-failed-in-a-clean-osx-10-13

@commitay can this issue be re-opened?

**Comment by vitorgalvao** [comment]
@driesvints That issue has nothing to do with Homebrew-Cask. You need to ask in the Virtualbox forums instead.

**Comment by driesvints** [comment]
@vitorgalvao I'm actually referring to the issue above.

**Comment by vitorgalvao** [comment]
@driesvints Either way (though that didn’t clarify which issue you were talking about; all of them are above).

This is not an HBC issue, it is an issue with VirtualBox and macOS.

**Comment by driesvints** [comment]
Ok I'll try, thanks.

**Comment by janpio** [comment]
Solution for the original issue probably was:

``` 
==> Caveats
To install and/or use virtualbox you may need to enable their kernel extension in

  System Preferences → Security & Privacy → General

For more information refer to vendor documentation or the Apple Technical Note:

  https://developer.apple.com/library/content/technotes/tn2459/_index.html

```

Was output for me during the install process, missed it at first.
