### ISSUE TITLE
removing cask android-sdk fails

### ISSUE THREAD

**Issue by olivererxleben** [caskroom/homebrew-cask#39891]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

I try to remove the cask android-sdk but it fails with output below. 

#### Output of your command with `--verbose --debug`

```
$ brew cask rm android-sdk --verbose --debug
==> Uninstalling Cask android-sdk
==> Uninstalling Cask android-sdk
==> Un-installing artifacts
==> 47 artifact/s defined
#<SortedSet:0x007fade78fcec8>
==> Un-installing artifact of class Hbc::Artifact::PreflightBlock
==> Un-installing artifact of class Hbc::Artifact::Binary
==> Un-installing artifact of class Hbc::Artifact::Binary
==> Un-installing artifact of class Hbc::Artifact::Binary
==> Un-installing artifact of class Hbc::Artifact::Binary
==> Un-installing artifact of class Hbc::Artifact::Binary
==> Un-installing artifact of class Hbc::Artifact::Binary
==> Un-installing artifact of class Hbc::Artifact::Binary
==> Un-installing artifact of class Hbc::Artifact::Binary
==> Un-installing artifact of class Hbc::Artifact::Binary
==> Un-installing artifact of class Hbc::Artifact::Binary
==> Un-installing artifact of class Hbc::Artifact::Binary
==> Un-installing artifact of class Hbc::Artifact::Binary
==> Un-installing artifact of class Hbc::Artifact::Binary
==> Un-installing artifact of class Hbc::Artifact::Binary
==> Un-installing artifact of class Hbc::Artifact::Binary
==> Un-installing artifact of class Hbc::Artifact::Binary
==> Un-installing artifact of class Hbc::Artifact::Binary
==> Un-installing artifact of class Hbc::Artifact::Binary
==> Un-installing artifact of class Hbc::Artifact::Binary
==> Un-installing artifact of class Hbc::Artifact::Binary
==> Un-installing artifact of class Hbc::Artifact::Binary
==> Un-installing artifact of class Hbc::Artifact::Binary
==> Un-installing artifact of class Hbc::Artifact::Binary
==> Un-installing artifact of class Hbc::Artifact::Binary
==> Un-installing artifact of class Hbc::Artifact::Binary
==> Un-installing artifact of class Hbc::Artifact::Binary
==> Un-installing artifact of class Hbc::Artifact::Binary
==> Un-installing artifact of class Hbc::Artifact::Binary
==> Un-installing artifact of class Hbc::Artifact::Binary
==> Un-installing artifact of class Hbc::Artifact::Binary
==> Un-installing artifact of class Hbc::Artifact::Binary
==> Un-installing artifact of class Hbc::Artifact::Binary
==> Un-installing artifact of class Hbc::Artifact::Binary
==> Un-installing artifact of class Hbc::Artifact::Binary
==> Un-installing artifact of class Hbc::Artifact::Binary
==> Un-installing artifact of class Hbc::Artifact::Binary
==> Un-installing artifact of class Hbc::Artifact::Binary
==> Un-installing artifact of class Hbc::Artifact::Binary
==> Un-installing artifact of class Hbc::Artifact::Binary
==> Un-installing artifact of class Hbc::Artifact::Binary
==> Un-installing artifact of class Hbc::Artifact::Binary
==> Un-installing artifact of class Hbc::Artifact::Binary
==> Un-installing artifact of class Hbc::Artifact::Binary
==> Un-installing artifact of class Hbc::Artifact::Binary
==> Un-installing artifact of class Hbc::Artifact::PostflightBlock
==> Un-installing artifact of class Hbc::Artifact::PostflightBlock
Error: No such file or directory @ unlink_internal - /usr/local/share/android-sdk
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask#reporting-bugs
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:1451:in `unlink'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:1451:in `block in remove_file'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:1456:in `platform_support'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:1450:in `remove_file'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:794:in `remove_file'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:572:in `block in rm'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:571:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:571:in `rm'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:88:in `block (2 levels) in load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_flight_block.rb:38:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_flight_block.rb:38:in `abstract_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_flight_block.rb:26:in `uninstall_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:384:in `block in uninstall_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:381:in `uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:370:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:22:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:12:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:12:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:97:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:167:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:99:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:178:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:178:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:99:in `<main>'
```

#### Output of `brew cask doctor`

```
 $ brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.3.6-30-gce0e96c
caskroom/homebrew-cask (git revision 2b744e; last commit 2017-10-21)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (10 files, 834.8MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3761 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (171 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin17
/Library/Ruby/Site/2.3.0/universal-darwin17
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin17
==> Environment Variables
LANG="de_DE.UTF-8"
PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"

```

**Comment by commitay** [comment]
`brew cask doctor`?

**Comment by olivererxleben** [comment]
ups. updated.

**Comment by commitay** [comment]
Does `/usr/local/share/android-sdk` exist?

**Comment by olivererxleben** [comment]
sure 

```
 $ brew cask ls
android-sdk                 firefoxdeveloperedition     kap                         slack
dash                        gitter                      marvel                      spotify
discord                     google-chrome               microsoft-office            virtualbox
docker                      google-chrome-canary        postman                     visual-studio-code
eclipse-ide                 java                        sketch
firefox                     kaleidoscope                skitch

```

**Comment by commitay** [comment]
I asked if `/usr/local/share/android-sdk` exists?

Post the output of `/usr/local/share`

**Comment by olivererxleben** [comment]
```
ls /usr/local/share
aclocal                 gitprompt.fish          gitstatus_pre-1.7.10.sh systemtap
doc                     gitprompt.sh            info                    themes
emacs                   gitstatus.py            man                     zsh
git-prompt-help.sh      gitstatus.sh            prompt-colors.sh
```

**Comment by commitay** [comment]
Run `touch /usr/local/share/android-sdk && brew cask uninstall android-sdk`

**Comment by olivererxleben** [comment]
thx.
