### ISSUE TITLE
Intel® Power Gadget not installing

### ISSUE THREAD

**Issue by mrvkino** [caskroom/homebrew-cask#40755]
Intel Power Gadget is not installing on MacOS High Sierra 10.13.1.

I have filed a bug report to Intel on their forum. I am also trying here so others can know about it and in case a work around can be found.

#### General troubleshooting steps

- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I have retried my command with `--force` and the issue is still present.
- [x] I ran `brew update-reset && brew update` and retried my command.
I am up-to-date, no warning or error
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
Nothing to report
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

running the command "brew cask install intel-power-gadget" fails at the install

#### Output of your command with `--verbose --debug`

```
❯brew cask install intel-power-gadget --verbose --debug
==> Hbc::Installer#install
==> Printing caveats
==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://software.intel.com/file/553992/download?#.dmg
Already downloaded: /Users/mrogersvallee/Library/Caches/Homebrew/Cask/intel-power-gadget--3.0.7,553992.dmg
==> Downloaded to -> /Users/mrogersvallee/Library/Caches/Homebrew/Cask/intel-power-gadget--3.0.7,553992.dmg
==> Verifying download
==> Determining which verifications to run for Cask intel-power-gadget
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask intel-power-gadget
==> SHA256 checksums match
==> Installing Cask intel-power-gadget
==> Hbc::Installer#stage
==> Extracting primary container
==> Determining which containers to use based on filetype
==> Checking container class Hbc::Container::Pkg
==> Checking container class Hbc::Container::Ttf
==> Checking container class Hbc::Container::Otf
==> Checking container class Hbc::Container::Air
==> Checking container class Hbc::Container::Cab
==> Checking container class Hbc::Container::Dmg
==> Executing: ["/usr/bin/hdiutil", "imageinfo", "/Users/mrogersvallee/Library/Caches/Homebrew/Cask/intel-power-gadget--3.0.7,553992.dmg"]
==> Using container class Hbc::Container::Dmg for /Users/mrogersvallee/Library/Caches/Homebrew/Cask/intel-power-gadget--3.0.7,553992.dmg
==> Executing: ["/usr/bin/hdiutil", "attach", "-plist", "-nobrowse", "-readonly", "-noidme", "-mountrandom", "/var/folders/1q/w6hbt74n447_y0hzfscvqj3m0000gn/T/d20171114-74526-psr22y", "/Users/mrogersvallee/Library/Caches/Homebrew/Cask/intel-power-gadget--3.0.7,553992.dmg"]
==> Executing: ["/usr/bin/find", ".", "-print0"]
==> Executing: ["/usr/bin/mkbom", "-s", "-i", "/var/folders/1q/w6hbt74n447_y0hzfscvqj3m0000gn/T/20171114-74526-1r7bub9.list", "--", "/var/folders/1q/w6hbt74n447_y0hzfscvqj3m0000gn/T/20171114-74526-5xr2gf.bom"]
==> Executing: ["/usr/bin/ditto", "--bom", "/var/folders/1q/w6hbt74n447_y0hzfscvqj3m0000gn/T/20171114-74526-5xr2gf.bom", "--", "/private/var/folders/1q/w6hbt74n447_y0hzfscvqj3m0000gn/T/d20171114-74526-psr22y/dmg.X0IwZw", "/usr/local/Caskroom/intel-power-gadget/3.0.7,553992"]
==> Executing: ["/usr/sbin/diskutil", "eject", "/private/var/folders/1q/w6hbt74n447_y0hzfscvqj3m0000gn/T/d20171114-74526-psr22y/dmg.X0IwZw"]
==> Creating metadata directory /usr/local/Caskroom/intel-power-gadget/.metadata/3.0.7,553992/20171114142705.552.
==> Creating metadata subdirectory /usr/local/Caskroom/intel-power-gadget/.metadata/3.0.7,553992/20171114142705.552/Casks.
==> Installing artifacts
==> 2 artifact/s defined
#<SortedSet:0x007fbd6b411088>
==> Installing artifact of class Hbc::Artifact::Pkg
==> Running installer for intel-power-gadget; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
==> Executing: ["/usr/bin/sudo", "-E", "--", "/usr/sbin/installer", "-pkg", "/usr/local/Caskroom/intel-power-gadget/3.0.7,553992/Install Intel Power Gadget.pkg", "-target", "/", "-verboseR"]
Password:
==> installer: Package name is Intel® Power Gadget
==> installer: Installing at base path /
==> installer:PHASE:Preparing for installation…
==> installer:PHASE:Preparing the disk…
==> installer:PHASE:Preparing Intel® Power Gadget…
==> installer:PHASE:Waiting for other installations to complete…
==> installer:PHASE:Configuring the installation…
==> installer:STATUS:
==> installer:%56.846737
==> installer:PHASE:Running package scripts…
==> installer:%58.053143
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Validating packages…
==> installer:%97.750000
==> installer: The install failed (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.)
==> Purging files for version 3.0.7,553992 of Cask intel-power-gadget
Error: Command failed to execute!

==> Failed command:
/usr/bin/sudo -E -- /usr/sbin/installer -pkg /usr/local/Caskroom/intel-power-gadget/3.0.7,553992/Install Intel Power Gadget.pkg -target / -verboseR

==> Standard Output of failed command:
installer: Package name is Intel® Power Gadget
installer: Installing at base path /
installer:PHASE:Preparing for installation…
installer:PHASE:Preparing the disk…
installer:PHASE:Preparing Intel® Power Gadget…
installer:PHASE:Waiting for other installations to complete…
installer:PHASE:Configuring the installation…
installer:STATUS:
installer:%56.846737
installer:PHASE:Running package scripts…
installer:%58.053143
installer:PHASE:Running package scripts…
installer:PHASE:Validating packages…
installer:%97.750000
installer: The install failed (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.)


==> Standard Error of failed command:


==> Exit status of failed command:
#<Process::Status: pid 74673 exit 1>

/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:73:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:35:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:13:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:17:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/pkg.rb:53:in `block in run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/pkg.rb:59:in `with_choices_file'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/pkg.rb:51:in `run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/pkg.rb:32:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:191:in `block in install_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:183:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:97:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:19:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:13:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:13:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:97:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:167:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:172:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:172:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew-Cask Version
Homebrew-Cask 1.3.7-2-g2225feb
caskroom/homebrew-cask (git revision dd65b5; last commit 2017-11-14)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (4 files, 86.8MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3819 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin17
/Library/Ruby/Site/2.3.0/universal-darwin17
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin17
==> Environment Variables
LANG="en_CA.UTF-8"
PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:~/hardent_tools/bin:~/bin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/usr/local/bin/fish"
```

**Comment by commitay** [comment]
> I have filed a bug report to Intel on their forum.

Can you post a link please?

> in case a work around can be found

A fix would have to come from upstream, there isn't anything we can do to work around `pkg` installers.

**Comment by mrvkino** [comment]
No problem, I had to try!

here is the link: [intel forum](https://software.intel.com/en-us/forums/software-tuning-performance-optimization-platform-monitoring/topic/748437)

**Comment by mrvkino** [comment]
Ok, found the solution. I had the same issue when installing virtualbox with brew cask. I found the solution when filing for a bug and I stumbled on this: [virtualbox unblock install](https://apple.stackexchange.com/questions/301303/virtualbox-5-1-28-fails-to-install-on-macos-10-13-due-to-kext-security)

Here is the process that allowed me to install the cask:

1. Install the app a first time
2. Open the Security&Privacy Preference panel and on the General Tab I found a message telling me that the Intel Power Gadget was blocked from loading. Click allow.
3. Homebrew failed since I could not click allow fast enough
4. Perform a second install (homebrew told me the app was not installed)
5. Get a pass.

<details>
<summary>Install Log</summary>
<pre>
❯brew cask install intel-power-gadget
==> Satisfying dependencies
==> Downloading https://software.intel.com/file/553992/download?#.dmg
Already downloaded: /Users/mrogersvallee/Library/Caches/Homebrew/Cask/intel-power-gadget--3.0.7,553992.dmg
==> Verifying checksum for Cask intel-power-gadget
==> Installing Cask intel-power-gadget
==> Running installer for intel-power-gadget; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
==> installer: Package name is Intel® Power Gadget
==> installer: Installing at base path /
==> installer: The install failed (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.)
Error: Command failed to execute!

==> Failed command:
/usr/bin/sudo -E -- /usr/sbin/installer -pkg /usr/local/Caskroom/intel-power-gadget/3.0.7,553992/Install Intel Power Gadget.pkg -target /

==> Standard Output of failed command:
installer: Package name is Intel® Power Gadget
installer: Installing at base path /
installer: The install failed (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.)

==> Standard Error of failed command:

==> Exit status of failed command:
#<Process::Status: pid 71235 exit 1>
❯brew cask uninstall intel-power-gadget
Error: Cask 'intel-power-gadget' is not installed.
❯brew cask install intel-power-gadget
==> Satisfying dependencies
==> Downloading https://software.intel.com/file/553992/download?#.dmg
Already downloaded: /Users/mrogersvallee/Library/Caches/Homebrew/Cask/intel-power-gadget--3.0.7,553992.dmg
==> Verifying checksum for Cask intel-power-gadget
==> Installing Cask intel-power-gadget
==> Running installer for intel-power-gadget; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
==> installer: Package name is Intel® Power Gadget
==> installer: Installing at base path /
==> installer: The install was successful.
</pre>
</details>
