### ISSUE TITLE
[brew cask install java] sudo: sorry, you are not allowed to preserve the environment

### ISSUE THREAD

**Issue by RyanBard** [caskroom/homebrew-cask#40867]
#### General troubleshooting steps

- [Y] I have retried my command with `--force` and the issue is still present.
- [Y] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [Y] None of the templates was appropriate for my issue, or I’m not sure.
- [Y] I ran `brew update-reset && brew update` and retried my command.
- [Y] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [Y] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

When trying to install java, I get a sudo error like this closed (without review) ticket: https://github.com/caskroom/homebrew-cask/issues/9886

(I did not try to modify the `/private/etc/sudoers` file as a workaround.)

#### Output of your command with `--verbose --debug`

```
$ brew cask install --force --verbose --debug java
==> Hbc::Installer#install
==> Printing caveats
==> Caveats
This Cask makes minor modifications to the JRE to prevent issues with
packaged applications, as discussed here:

  https://bugs.eclipse.org/bugs/show_bug.cgi?id=411361

If your Java application still asks for JRE installation, you might need
to reboot or logout/login.

Installing this Cask means you have AGREED to the Oracle Binary Code
License Agreement for Java SE at

  https://www.oracle.com/technetwork/java/javase/terms/license/index.html

==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading http://download.oracle.com/otn-pub/java/jdk/9.0.1+11/jdk-9.0.1_osx-x64_bin.dmg
Already downloaded: /Users/jbard/Library/Caches/Homebrew/Cask/java--9.0.1,11.dmg
==> Downloaded to -> /Users/jbard/Library/Caches/Homebrew/Cask/java--9.0.1,11.dmg
==> Verifying download
==> Determining which verifications to run for Cask java
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask java
==> SHA256 checksums match
==> Installing Cask java
==> Hbc::Installer#stage
==> Extracting primary container
==> Determining which containers to use based on filetype
==> Checking container class Hbc::Container::Pkg
==> Checking container class Hbc::Container::Ttf
==> Checking container class Hbc::Container::Otf
==> Checking container class Hbc::Container::Air
==> Checking container class Hbc::Container::Cab
==> Checking container class Hbc::Container::Dmg
==> Executing: ["/usr/bin/hdiutil", "imageinfo", "/Users/jbard/Library/Caches/Homebrew/Cask/java--9.0.1,11.dmg"]
==> Using container class Hbc::Container::Dmg for /Users/jbard/Library/Caches/Homebrew/Cask/java--9.0.1,11.dmg
==> Executing: ["/usr/bin/hdiutil", "attach", "-plist", "-nobrowse", "-readonly", "-noidme", "-mountrandom", "/var/folders/4r/ch0_6t6d2pjf0rrwrf9kw2q400bb5y/T/d20171116-91837-acx2kr", "/Users/jbard/Library/Caches/Homebrew/Cask/java--9.0.1,11.dmg"]
==> Executing: ["/usr/bin/find", ".", "-print0"]
==> Executing: ["/usr/bin/mkbom", "-s", "-i", "/var/folders/4r/ch0_6t6d2pjf0rrwrf9kw2q400bb5y/T/20171116-91837-1v3nnq6.list", "--", "/var/folders/4r/ch0_6t6d2pjf0rrwrf9kw2q400bb5y/T/20171116-91837-qfxep3.bom"]
==> Executing: ["/usr/bin/ditto", "--bom", "/var/folders/4r/ch0_6t6d2pjf0rrwrf9kw2q400bb5y/T/20171116-91837-qfxep3.bom", "--", "/private/var/folders/4r/ch0_6t6d2pjf0rrwrf9kw2q400bb5y/T/d20171116-91837-acx2kr/dmg.DmidfV", "/usr/local/Caskroom/java/9.0.1,11"]
==> Executing: ["/usr/sbin/diskutil", "eject", "/private/var/folders/4r/ch0_6t6d2pjf0rrwrf9kw2q400bb5y/T/d20171116-91837-acx2kr/dmg.DmidfV"]
==> Creating metadata directory /usr/local/Caskroom/java/.metadata/9.0.1,11/20171116155747.335.
==> Creating metadata subdirectory /usr/local/Caskroom/java/.metadata/9.0.1,11/20171116155747.335/Casks.
==> Installing artifacts
==> 5 artifact/s defined
#<SortedSet:0x00000105a193d8>
==> Installing artifact of class Hbc::Artifact::PreflightBlock
==> Installing artifact of class Hbc::Artifact::Pkg
==> Running installer for java; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
==> Executing: ["/usr/bin/sudo", "-E", "--", "/usr/sbin/installer", "-pkg", "/usr/local/Caskroom/java/9.0.1,11/JDK 9.0.1.pkg", "-target", "/", "-verboseR"]
==> sudo: sorry, you are not allowed to preserve the environment
==> Reverting installation of artifact of class Hbc::Artifact::PreflightBlock
==> Purging files for version 9.0.1,11 of Cask java
Error: Command failed to execute!

==> Failed command:
/usr/bin/sudo -E -- /usr/sbin/installer -pkg /usr/local/Caskroom/java/9.0.1,11/JDK 9.0.1.pkg -target / -verboseR

==> Standard Output of failed command:


==> Standard Error of failed command:
sudo: sorry, you are not allowed to preserve the environment


==> Exit status of failed command:
#<Process::Status: pid 91992 exit 1>

/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:73:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:35:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:13:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:17:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/pkg.rb:53:in `block in run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/pkg.rb:59:in `with_choices_file'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/pkg.rb:51:in `run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/pkg.rb:32:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:191:in `block in install_artifacts'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:183:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:97:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:19:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:13:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:13:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:97:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:167:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:172:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:172:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
$ 
```

#### Output of `brew cask doctor`

```
$ brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.3.7-4-g2953493
caskroom/homebrew-cask (git revision de23c6; last commit 2017-11-16)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (1 files, 382.1MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3819 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/universal-darwin9.0
==> Environment Variables
LANG="en_US.UTF-8"
PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Wireshark.app/Contents/MacOS:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
$ 
```

#### Additional info

macOS Sierra Version 10.12.6:

```
$ uname -a
Darwin ***.***.com 16.7.0 Darwin Kernel Version 16.7.0: Wed Oct  4 00:17:00 PDT 2017; root:xnu-3789.71.6~1/RELEASE_X86_64 x86_64
$ 
```

Relevant parts of my `/private/etc/sudoers`:

```
%admin		ALL = (ALL) ALL
%admin ALL=(root) NOPASSWD: /usr/sbin/installer *
%admin ALL=(root) NOPASSWD: /usr/bin/gem *
```

**Comment by commitay** [comment]
Add `SETENV`

https://superuser.com/questions/636283/how-to-allow-user-to-preserve-environment-with-sudo
