### ISSUE TITLE
`brew cask upgrade` fails for `latest` Casks.

### ISSUE THREAD

**Issue by reitermarkus** [caskroom/homebrew-cask#41373]
`brew cask upgrade --greedy` fails on `latest` Casks, because they are staged into the same directory, overwriting old version.

The old version directory should be renamed before staging the new version.

cc @amyspark

**Comment by amyspark** [comment]
I completely forgot to include `version: latest` Casks in the tests 🤦‍♀️ Fix coming right away!

**Comment by commitay** [comment]
Posting this here rather than a separate issue, may as well keep `brew cask upgrade` related in one place.

Noticed this in https://github.com/caskroom/homebrew-cask/pull/41392

```
brew cask uninstall --verbose --debug visual-paradigm-ce.rb
==> Uninstalling Cask visual-paradigm-ce
==> Uninstalling Cask visual-paradigm-ce
==> Un-installing artifacts
==> 1 artifact/s defined
#<SortedSet:0x007fd8f0f4cdd0>
==> Un-installing artifact of class Hbc::Artifact::App
Error: It seems there is already an App at '/usr/local/Caskroom/visual-paradigm-ce/14.2,20171107/Visual Paradigm.app'.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/moved.rb:55:in `move_back'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/moved.rb:15:in `uninstall_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:386:in `block in uninstall_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:383:in `uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:353:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:22:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:12:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:12:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

**Comment by amyspark** [comment]
@commitay, the Travis log in #41392 shows an ENOENT when moving the app back to the staging area. I'm adding a fix for that in my pull request.
As for the log above, I think that it is caused by that comma in the version field.  I'm trying to figure out how that field is processed.

**Comment by amyspark** [comment]
@commitay: I've finished checking that weird version field, and can confirm it isn't related.
Judging from this line:
```
Error: It seems there is already an App at '/usr/local/Caskroom/visual-paradigm-ce/14.2,20171107/Visual Paradigm.app'.
```
The only way this could happen if it was stopped after `move_back` and before `purge_versioned_files`. Did you terminate (as in Ctrl-C) the uninstall previously?
In any case, you can use `--force` to forcibly clean whatever is in the staging area.

**Comment by commitay** [comment]
Sorry, copy paste fail 😴 . The log was from local testing with `git bisect`.
