### ISSUE TITLE
install failed (wireshark, synergy) with same reason.(curl: (56) LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54)

### ISSUE THREAD

**Issue by star114** [caskroom/homebrew-cask#41608]
#### General troubleshooting steps

- [o] I have retried my command with `--force` and the issue is still present.
- [o] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [o] None of the templates was appropriate for my issue, or I’m not sure.
- [o] I ran `brew update-reset && brew update` and retried my command.
- [o] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [o] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

curl: (56) LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54

#### Output of your command with `--verbose --debug`

```
star114@Heesiks-MBP ~ $ brew cask install synergy --verbose --debug
==> Hbc::Installer#install
==> Printing caveats
==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://binaries.symless.com/v2.0.2/Synergy_v2.0.2-stable_b1153-665fa610.dmg
/usr/bin/curl --show-error --user-agent Homebrew/1.3.8 (Macintosh; Intel Mac OS X 10.13.1) curl/7.54.0 --fail --location --remote-time --continue-at - --output /Users/star114/Library/Caches/Homebrew/Cask/synergy--2.0.2,b1153-665fa610.dmg.incomplete https://binaries.symless.com/v2.0.2/Synergy_v2.0.2-stable_b1153-665fa610.dmg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  1 28.8M    1  303k    0     0   2459      0  3:25:06  0:02:06  3:23:00     0
curl: (56) LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54
Error: Download failed on Cask 'synergy' with message: Download failed: https://binaries.symless.com/v2.0.2/Synergy_v2.0.2-stable_b1153-665fa610.dmg
The incomplete download is cached at /Users/star114/Library/Caches/Homebrew/Cask/synergy--2.0.2,b1153-665fa610.dmg.incomplete
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/download.rb:42:in `rescue in fetch'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/download.rb:40:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/download.rb:15:in `perform'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:143:in `download'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:68:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:92:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:19:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:13:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:13:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:97:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:167:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:172:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:172:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew-Cask Version
Homebrew-Cask 1.3.8
caskroom/homebrew-cask (git revision 533a6; last commit 2017-12-03)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (2 files, 623.6KB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3851 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-drivers (137 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-fonts (1113 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (173 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-eid (10 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin17
/Library/Ruby/Site/2.3.0/universal-darwin17
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin17
==> Environment Variables
LC_CTYPE="UTF-8"
PATH="/usr/local/opt/coreutils/libexec/gnubin:/usr/local/opt/qt/bin:/usr/local/opt/curl/bin:/usr/local/opt/sqlite/bin:/usr/local/opt/go/libexec/bin:/usr/local/Cellar/pyenv-virtualenv/1.1.1/shims:/usr/local/var/pyenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Applications/Wireshark.app/Contents/MacOS:/usr/local/opt/fzf/bin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/usr/local/bin/bash"
```

**Comment by star114** [comment]
Do you have any ideas about this?
I tried to fix it, but failed and couldn't find any related issues.

**Comment by commitay** [comment]
Have you tried running `curl` manually?

**Comment by star114** [comment]
curl failed as same reason :(
It looks High Sierra problem
Let me close this issue.
