### ISSUE TITLE
CleanMyMac fails to zap with Finder/AppleScript error

### ISSUE THREAD

**Issue by numbermaniac** [caskroom/homebrew-cask#41786]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

`brew cask zap cleanmymac` fails with an AppleScript error. If I then try `brew cask zap cleanmymac --force`, since the app has already been moved to Caskroom's area, I get `Error: It seems the App source '/Applications/CleanMyMac 3.app' is not there.` I then can't install it because it thinks it is already installed - and it seems that it is (in `/usr/local/Caskroom`). If I `reinstall` and then `zap --force`, the same AppleScript error (as shown below) appears.

#### Output of `brew cask zap cleanmymac --force --verbose --debug`
```
==> Zapping Cask cleanmymac
==> Implied "brew cask uninstall cleanmymac"
==> Un-installing artifacts
==> 3 artifact/s defined
#<SortedSet:0x007f87432be8d8>
==> Un-installing artifact of class Hbc::Artifact::Uninstall
==> Running uninstall process for cleanmymac; your password may be necessary
==> Removing launchctl service com.macpaw.CleanMyMac3.Agent
==> Executing: ["/bin/launchctl", "list", "com.macpaw.CleanMyMac3.Agent"]
==> Executing: ["/usr/bin/sudo", "-E", "--", "/bin/launchctl", "list", "com.macpaw.CleanMyMac3.Agent"]
==> Removing launchctl service com.macpaw.CleanMyMac3.Scheduler
==> Executing: ["/bin/launchctl", "list", "com.macpaw.CleanMyMac3.Scheduler"]
==> Executing: ["/usr/bin/sudo", "-E", "--", "/bin/launchctl", "list", "com.macpaw.CleanMyMac3.Scheduler"]
==> Quitting application ID com.macpaw.CleanMyMac3
==> Executing: ["/bin/launchctl", "list"]
==> Quitting application ID com.macpaw.CleanMyMac3.Menu
==> Executing: ["/bin/launchctl", "list"]
==> Removing login item CleanMyMac 3 Menu
==> Executing: ["/usr/bin/osascript", "-e", "tell application \"System Events\" to delete every login item whose name is \"CleanMyMac 3 Menu\""]
==> Removing files:
/Library/PrivilegedHelperTools/com.macpaw.CleanMyMac3.Agent
==> Executing: ["/usr/bin/sudo", "-E", "--", "/usr/bin/xargs", "-0", "--", "/bin/rm", "-r", "-f", "--"]
==> Un-installing artifact of class Hbc::Artifact::App
==> Moving App 'CleanMyMac 3.app' back to '/usr/local/Caskroom/cleanmymac/3.9.2,1511452115/CleanMyMac 3.app'.
==> Dispatching zap stanza
==> Running zap process for cleanmymac; your password may be necessary
==> Trashing files:
/private/var/run/com.macpaw.CleanMyMac3.Agent.socket
/Users/Shared/CleanMyMac 3
/Users/Shared/CleanMyMac 3 Menu
~/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.macpaw.cleanmymac3.sfl*
~/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.macpaw.cleanmymac3.scheduler.sfl*
~/Library/Application Support/CleanMyMac 3
~/Library/Application Support/CleanMyMac 3 Menu
~/Library/Caches/CleanMyMac 3
~/Library/Caches/com.apple.helpd/SDMHelpData/Other/English/HelpSDMIndexFile/com.macpaw.CleanMyMac3.help*
~/Library/Caches/com.macpaw.CleanMyMac3
~/Library/Caches/com.macpaw.CleanMyMac3.KnowledgeBase
~/Library/Caches/com.macpaw.CleanMyMac3.Menu
~/Library/Caches/com.macpaw.CleanMyMac3.Scheduler
~/Library/Logs/CleanMyMac 3.log
~/Library/Logs/com.macpaw.CleanMyMac3
~/Library/Preferences/com.macpaw.CleanMyMac-3-Helper.plist
~/Library/Preferences/com.macpaw.CleanMyMac3.KnowledgeBase.plist
~/Library/Preferences/com.macpaw.cleanmymac3.menu.plist
~/Library/Preferences/com.macpaw.CleanMyMac3.Scheduler.plist
~/Library/Preferences/com.macpaw.CleanMyMac3.plist
~/Pictures/Photos Library.photoslibrary/private/com.macpaw.CleanMyMac3
==> Executing: ["/usr/bin/osascript", "-e", "on run argv\n  repeat with i from 1 to (count argv)\n    set item i of argv to (item i of argv as POSIX file)\n  end repeat\n\n  tell application \"Finder\"\n    set trashedItems to (move argv to trash)\n    set output to \"\"\n\n    repeat with i from 1 to (count trashedItems)\n      set trashedItem to POSIX path of (item i of trashedItems as string)\n      set output to output & trashedItem\n      if i < count trashedItems then\n        set output to output & character id 0\n      end if\n    end repeat\n\n    return output\n  end tell\nend run\n", "/private/var/run/com.macpaw.CleanMyMac3.Agent.socket", "/Users/Shared/CleanMyMac 3", "/Users/Shared/CleanMyMac 3 Menu", "~/Library/Application Support/CleanMyMac 3", "~/Library/Application Support/CleanMyMac 3 Menu", "~/Library/Caches/com.macpaw.CleanMyMac3", "~/Library/Caches/com.macpaw.CleanMyMac3.KnowledgeBase", "~/Library/Caches/com.macpaw.CleanMyMac3.Menu", "~/Library/Logs/com.macpaw.CleanMyMac3", "~/Library/Preferences/com.macpaw.CleanMyMac3.KnowledgeBase.plist", "~/Library/Preferences/com.macpaw.CleanMyMac3.Menu.plist", "~/Library/Preferences/com.macpaw.CleanMyMac3.Scheduler.plist", "~/Library/Preferences/com.macpaw.CleanMyMac3.plist"]
==> 175:193: 
==> execution error: Finder got an error: Handler can’t handle objects of this class. (-10010)
Error: Command failed to execute!

==> Failed command:
/usr/bin/osascript -e on run argv
  repeat with i from 1 to (count argv)
    set item i of argv to (item i of argv as POSIX file)
  end repeat

  tell application "Finder"
    set trashedItems to (move argv to trash)
    set output to ""

    repeat with i from 1 to (count trashedItems)
      set trashedItem to POSIX path of (item i of trashedItems as string)
      set output to output & trashedItem
      if i < count trashedItems then
        set output to output & character id 0
      end if
    end repeat

    return output
  end tell
end run
 /private/var/run/com.macpaw.CleanMyMac3.Agent.socket /Users/Shared/CleanMyMac 3 /Users/Shared/CleanMyMac 3 Menu ~/Library/Application Support/CleanMyMac 3 ~/Library/Application Support/CleanMyMac 3 Menu ~/Library/Caches/com.macpaw.CleanMyMac3 ~/Library/Caches/com.macpaw.CleanMyMac3.KnowledgeBase ~/Library/Caches/com.macpaw.CleanMyMac3.Menu ~/Library/Logs/com.macpaw.CleanMyMac3 ~/Library/Preferences/com.macpaw.CleanMyMac3.KnowledgeBase.plist ~/Library/Preferences/com.macpaw.CleanMyMac3.Menu.plist ~/Library/Preferences/com.macpaw.CleanMyMac3.Scheduler.plist ~/Library/Preferences/com.macpaw.CleanMyMac3.plist

==> Standard Output of failed command:


==> Standard Error of failed command:
175:193: execution error: Finder got an error: Handler can’t handle objects of this class. (-10010)


==> Exit status of failed command:
#<Process::Status: pid 7600 exit 1>

/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:70:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:36:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:18:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb:262:in `trash_paths'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb:258:in `uninstall_trash'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb:59:in `block in dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb:56:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb:56:in `dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/zap.rb:7:in `zap_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:415:in `block in zap'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:414:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:414:in `zap'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/zap.rb:14:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/zap.rb:12:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/zap.rb:12:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew-Cask Version
Homebrew-Cask 1.3.9-38-ge5e91f0
caskroom/homebrew-cask (git revision 48e9d; last commit 2017-12-10)
==> macOS
10.13.2
==> Java
1.8.0_102
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (2 files, 130.4MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3855 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-drivers (137 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (175 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin17
/Library/Ruby/Site/2.3.0/universal-darwin17
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin17
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

**Comment by commitay** [comment]
Please try:

`brew cask install --force cleanmymac`

```
brew cask zap https://raw.githubusercontent.com/commitay/homebrew-cask/f5297cbd00716b46443a9ea04382222292da9f08/Casks/cleanmymac.rb
```

https://github.com/caskroom/homebrew-cask/pull/41787

**Comment by numbermaniac** [comment]
@commitay Yep, it looks like it fixes the uninstallation error.

**Comment by commitay** [comment]
This was an oversight on my part when all `zap` stanzas were changed to use `zap trash`.

https://github.com/caskroom/homebrew-cask/commit/e1d4ab9e7b3490a904fc52dd3077cecb971a0534#diff-5cb49e783073209ee7b41c5a18ec9a89L26

Sorry for the trouble.
