### ISSUE TITLE
Checksum mismatch 4f4b4c12921242c61e9c9bf12414a4bbb550bd1539973adbc93c5c60fb6181bb

### ISSUE THREAD

**Issue by aramark-pivotal** [caskroom/homebrew-cask#41993]
#### General troubleshooting steps

- [ x ] I have retried my command with `--force` and the issue is still present.
- [ x ] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [ x ] None of the templates was appropriate for my issue, or I’m not sure.
- [ x ] I ran `brew update-reset && brew update` and retried my command.
- [ x ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [ x ] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

We noticed our Circle CI environment began to fail on `brew cask install hockey` we attempted all of the above trouble shooting steps and tested the same command across multiple machines and environments with consistently the same sha mismatch error

#### Output of your command with `--verbose --debug`

```
→ brew cask install hockey --verbose --debug
==> Hbc::Installer#install
==> Printing caveats
==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://rink.hockeyapp.net/api/2/apps/67503a7926431872c4b6c1549f5bd6b1/app_versions/503?format=zip
Already downloaded: /Users/development1/Library/Caches/Homebrew/Cask/hockey--2.0.19,503
==> Downloaded to -> /Users/development1/Library/Caches/Homebrew/Cask/hockey--2.0.19,503
==> Verifying download
==> Determining which verifications to run for Cask hockey
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask hockey
==> Note: running "brew update" may fix sha256 checksum errors
Error: Checksum for Cask 'hockey' does not match.

Expected: 4f4b4c12921242c61e9c9bf12414a4bbb550bd1539973adbc93c5c60fb6181bb
Actual:   3ba93e54752891bc808a162c6426f006db07ab795123ad563bcfb403a99a935b
File:     /Users/development1/Library/Caches/Homebrew/Cask/hockey--2.0.19,503

To retry an incomplete download, remove the file above.

/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/verify/checksum.rb:42:in `verify_checksum'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/verify/checksum.rb:22:in `verify'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/verify.rb:21:in `block in all'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/verify.rb:19:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/verify.rb:19:in `all'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:138:in `verify'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:52:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:75:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:20:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'

{{replace this}}
```

#### Output of `brew cask doctor`

```
→ brew cask doctor --debug --verbose
==> Homebrew-Cask Version
Homebrew-Cask 1.4.0-27-g67c4402
caskroom/homebrew-cask (git revision 3c6c9e; last commit 2017-12-15)
==> macOS
10.12.6
==> Java
1.8.0_131
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (1 files, 12.1MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3857 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/universal-darwin9.0
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/pull/41994

**Comment by aramark-pivotal** [comment]
We've followed the checksum instructions outlined, and attempted a solutions:

```
→ brew cask audit --download hockey
==> Downloading https://rink.hockeyapp.net/api/2/apps/67503a7926431872c4b6c1549f5bd6b1/app_versions/503?format=zip
Already downloaded: /Users/development1/Library/Caches/Homebrew/Cask/hockey--2.0.19,503
==> Verifying checksum for Cask hockey
==> Note: running "brew update" may fix sha256 checksum errors
audit for hockey: failed
 - download not possible: Checksum for Cask 'hockey' does not match.

Expected: 4f4b4c12921242c61e9c9bf12414a4bbb550bd1539973adbc93c5c60fb6181bb
Actual:   3ba93e54752891bc808a162c6426f006db07ab795123ad563bcfb403a99a935b
File:     /Users/development1/Library/Caches/Homebrew/Cask/hockey--2.0.19,503

To retry an incomplete download, remove the file above.

 - appcast checkpoint mismatch
Expected: a9d73e714a0199766bf9860903ab810b84e5f4c03c4606a970660108cf2e1346
Actual: fc6e44d563a04341b074b8d8fc438058851de68f24ce7d021028554e0dbd7575
Error: audit failed for casks: hockey

  |2.3.1| development1s-iMac in ~/workspace/PattyMelt/patty-melt-ios
± mk |master ?:8 ✗| → brew cask style --fix hockey
==> Installing or updating 'rubocop-cask' gem
Fetching: public_suffix-3.0.1.gem (100%)
Successfully installed public_suffix-3.0.1
Fetching: parallel-1.12.0.gem (100%)
Successfully installed parallel-1.12.0
Fetching: ast-2.3.0.gem (100%)
Successfully installed ast-2.3.0
Fetching: parser-2.4.0.2.gem (100%)
Successfully installed parser-2.4.0.2
Fetching: powerpack-0.1.1.gem (100%)
Successfully installed powerpack-0.1.1
Fetching: rainbow-2.2.2.gem (100%)
Building native extensions.  This could take a while...
Successfully installed rainbow-2.2.2
Fetching: ruby-progressbar-1.9.0.gem (100%)
Successfully installed ruby-progressbar-1.9.0
Fetching: unicode-display_width-1.3.0.gem (100%)
Successfully installed unicode-display_width-1.3.0
Fetching: rubocop-0.51.0.gem (100%)
Successfully installed rubocop-0.51.0
Fetching: rubocop-cask-0.15.1.gem (100%)
Successfully installed rubocop-cask-0.15.1
10 gems installed

1 file inspected, no offenses detected

  |2.3.1| development1s-iMac in ~/workspace/PattyMelt/patty-melt-ios
± mk |master ?:8 ✗| → brew cask install hockey
==> Satisfying dependencies
==> Downloading https://rink.hockeyapp.net/api/2/apps/67503a7926431872c4b6c1549f5bd6b1/app_versions/503?format=zip
Already downloaded: /Users/development1/Library/Caches/Homebrew/Cask/hockey--2.0.19,503
==> Verifying checksum for Cask hockey
==> Note: running "brew update" may fix sha256 checksum errors
Error: Checksum for Cask 'hockey' does not match.

Expected: 4f4b4c12921242c61e9c9bf12414a4bbb550bd1539973adbc93c5c60fb6181bb
Actual:   3ba93e54752891bc808a162c6426f006db07ab795123ad563bcfb403a99a935b
File:     /Users/development1/Library/Caches/Homebrew/Cask/hockey--2.0.19,503

To retry an incomplete download, remove the file above.
```

**Comment by vitorgalvao** [comment]
@aramark-pivotal I don’t see your point. You opened an issue. Presumably you followed the instructions before checking the checkboxes saying you followed them.

One of said instructions leads you to a list of common issues *that has the issue you are mentioning and tells you how to fix it*.

I linked you to said instructions *and* fixed it *and* linked you to the result of such fix. What you posted after has no bearing whatsoever to the matter.
