### ISSUE TITLE
Prey cask fails to install due to API_KEY being filtered out

### ISSUE THREAD

**Issue by aw1621107** [caskroom/homebrew-cask#42142]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

The prey cask fails to install, even when `API_KEY` is set. I believe this is due to brew's environment variable filtering.

I was considering adding a PR to add `HOMEBREW_NO_ENV_FILTERING=1` to the Prey installation instructions, but I wasn't sure if a different solution like whitelisting `API_KEY` would be preferable.

#### Output of your command with `--verbose --debug`

```
rp:Caskroom awang$ API_KEY="<redacted>" brew cask install prey --verbose --debug
==> Hbc::Installer#install
==> Printing caveats
==> Caveats
Prey requires your API key, found in the bottom-left corner of
the Prey web account Settings page, to complete installation.
The API key may be set as an environment variable as follows:

  API_KEY="abcdef123456" brew cask install prey

==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://downloads.preyproject.com/prey-client-releases/node-client/1.7.2/prey-mac-1.7.2-x64.pkg
Already downloaded: /Users/awang/Library/Caches/Homebrew/Cask/prey--1.7.2.pkg
==> Downloaded to -> /Users/awang/Library/Caches/Homebrew/Cask/prey--1.7.2.pkg
==> Verifying download
==> Determining which verifications to run for Cask prey
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask prey
==> SHA256 checksums match
==> Installing Cask prey
==> Hbc::Installer#stage
==> Extracting primary container
==> Determining which containers to use based on filetype
==> Checking container class Hbc::Container::Pkg
==> Using container class Hbc::Container::Pkg for /Users/awang/Library/Caches/Homebrew/Cask/prey--1.7.2.pkg
==> Executing: ["/usr/bin/ditto", "--", "/Users/awang/Library/Caches/Homebrew/Cask/prey--1.7.2.pkg", "/usr/local/Caskroom/prey/1.7.2/prey-mac-1.7.2-x64.pkg"]
==> Creating metadata directory /usr/local/Caskroom/prey/.metadata/1.7.2/20171220165926.963.
==> Creating metadata subdirectory /usr/local/Caskroom/prey/.metadata/1.7.2/20171220165926.963/Casks.
==> Installing artifacts
==> 2 artifact/s defined
#<SortedSet:0x007fa688985478>
==> Installing artifact of class Hbc::Artifact::Pkg
==> Running installer for prey; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
==> Executing: ["/usr/bin/sudo", "-E", "--", "/usr/sbin/installer", "-pkg", "/usr/local/Caskroom/prey/1.7.2/prey-mac-1.7.2-x64.pkg", "-target", "/", "-verboseR"]
==> No API Key provided. Stopping here.
==> installer: Error -  Pre install check failed. Try again.
==> Purging files for version 1.7.2 of Cask prey
Error: Command failed to execute!

==> Failed command:
/usr/bin/sudo -E -- /usr/sbin/installer -pkg /usr/local/Caskroom/prey/1.7.2/prey-mac-1.7.2-x64.pkg -target / -verboseR

==> Standard Output of failed command:
No API Key provided. Stopping here.


==> Standard Error of failed command:
installer: Error -  Pre install check failed. Try again.


==> Exit status of failed command:
#<Process::Status: pid 48059 exit 1>

/Users/awang/code/brew/Library/Homebrew/cask/lib/hbc/system_command.rb:70:in `assert_success'
/Users/awang/code/brew/Library/Homebrew/cask/lib/hbc/system_command.rb:36:in `run!'
/Users/awang/code/brew/Library/Homebrew/cask/lib/hbc/system_command.rb:14:in `run'
/Users/awang/code/brew/Library/Homebrew/cask/lib/hbc/system_command.rb:18:in `run!'
/Users/awang/code/brew/Library/Homebrew/cask/lib/hbc/artifact/pkg.rb:53:in `block in run_installer'
/Users/awang/code/brew/Library/Homebrew/cask/lib/hbc/artifact/pkg.rb:59:in `with_choices_file'
/Users/awang/code/brew/Library/Homebrew/cask/lib/hbc/artifact/pkg.rb:51:in `run_installer'
/Users/awang/code/brew/Library/Homebrew/cask/lib/hbc/artifact/pkg.rb:32:in `install_phase'
/Users/awang/code/brew/Library/Homebrew/cask/lib/hbc/installer.rb:174:in `block in install_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/Users/awang/code/brew/Library/Homebrew/cask/lib/hbc/installer.rb:166:in `install_artifacts'
/Users/awang/code/brew/Library/Homebrew/cask/lib/hbc/installer.rb:80:in `install'
/Users/awang/code/brew/Library/Homebrew/cask/lib/hbc/cli/install.rb:20:in `block in run'
/Users/awang/code/brew/Library/Homebrew/cask/lib/hbc/cli/install.rb:14:in `each'
/Users/awang/code/brew/Library/Homebrew/cask/lib/hbc/cli/install.rb:14:in `run'
/Users/awang/code/brew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/Users/awang/code/brew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
/Users/awang/code/brew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `run'
/Users/awang/code/brew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/Users/awang/code/brew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/Users/awang/code/brew/Library/Homebrew/brew.rb:100:in `<main>'
Error: Kernel.exit
/Users/awang/code/brew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `exit'
/Users/awang/code/brew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `rescue in run'
/Users/awang/code/brew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/Users/awang/code/brew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/Users/awang/code/brew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/Users/awang/code/brew/Library/Homebrew/brew.rb:100:in `<main>'
```

#### Output of `brew cask doctor`

```
rp:Caskroom awang$ brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.4.1-3-g426c998
caskroom/homebrew-cask (git revision 0b412a; last commit 2017-12-20)
==> macOS
10.13.2
==> Java
9.0.1
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (40 files, 6GB)
==> Homebrew-Cask Taps:
/Users/awang/code/brew/Library/Taps/caskroom/homebrew-cask (3865 casks)
/Users/awang/code/brew/Library/Taps/caskroom/homebrew-versions (175 casks)
==> Contents of $LOAD_PATH
/Users/awang/code/brew/Library/Homebrew/cask/lib
/Users/awang/code/brew/Library/Homebrew
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin17
/Library/Ruby/Site/2.3.0/universal-darwin17
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin17
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:~/code/brew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

**Comment by vitorgalvao** [comment]
Your solution is fine. It’s a single cask, so not worth it to add an exception in the core. You may submit the PR.

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/42148
