### ISSUE TITLE
Permission error when trying to uninstall KeePassX with "brew cask remove"

### ISSUE THREAD

**Issue by jeremyjohnreeder** [caskroom/homebrew-cask#42219]
#### General troubleshooting steps

- [X] I have retried my command with `--force` and the issue is still present.
- [X] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [X] None of the templates was appropriate for my issue, or I’m not sure.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

I can't uninstall KeePassX.

#### Output of your command with `--verbose --debug`

```
> brew cask remove keepassx --verbose --debug
==> Uninstalling Cask keepassx
==> Uninstalling Cask keepassx
==> Un-installing artifacts
==> 2 artifact/s defined
#<SortedSet:0x0000010332cb58>
==> Un-installing artifact of class Hbc::Artifact::App
==> Moving App 'KeePassX.app' back to '/usr/local/Caskroom/keepassx/2.0.3/KeePassX.app'.
Error: Permission denied @ rb_file_s_rename - (/Applications/KeePassX.app, /usr/local/Caskroom/keepassx/2.0.3/KeePassX.app)
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/fileutils.rb:528:in `rename'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/fileutils.rb:528:in `block in mv'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/fileutils.rb:1571:in `block in fu_each_src_dest'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/fileutils.rb:1587:in `fu_each_src_dest0'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/fileutils.rb:1569:in `fu_each_src_dest'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/fileutils.rb:517:in `mv'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/moved.rb:69:in `move_back'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/moved.rb:15:in `uninstall_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:403:in `block in uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:400:in `uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:353:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:22:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:12:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:12:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:179:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:179:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

#### Output of `brew cask doctor`

```
> brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.4.1-11-g583b61f
caskroom/homebrew-cask (git revision 023da; last commit 2017-12-22)
==> macOS
10.13.2
==> Java
1.8.0_121, 1.8.0_112, 1.8.0_111
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (2 files, 18.4MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3865 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/universal-darwin9.0
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/usr/local/bin/fish"
```

**Comment by vitorgalvao** [comment]
> Moving App 'KeePassX.app' back to '/usr/local/Caskroom/keepassx/2.0.3/KeePassX.app'.

Wait, what? Why are we doing that?

> Error: Permission denied @ rb_file_s_rename - (/Applications/KeePassX.app, /usr/local/Caskroom/keepassx/2.0.3/KeePassX.app)

Seems like there’s a permissions error. Could you check the permissions on both the app and the Caskroom?

**Comment by joh-klein** [comment]
I have a similar problem with the KeeWeb cask:
```
➜  ~ brew cask reinstall keeweb
==> Satisfying dependencies
==> Downloading https://github.com/keeweb/keeweb/releases/download/v1.6.3/KeeWeb-1.6.3.mac.dmg
Already downloaded: /Users/[…]/Library/Caches/Homebrew/Cask/keeweb--1.6.3.dmg
==> Verifying checksum for Cask keeweb
==> Uninstalling Cask keeweb
==> Moving App 'KeeWeb.app' back to '/usr/local/Caskroom/keeweb/1.6.1/KeeWeb.app'.
Error: Permission denied @ rb_file_s_rename - (/Applications/KeeWeb.app, /usr/local/Caskroom/keeweb/1.6.1/KeeWeb.app)
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/fileutils.rb:528:in `rename'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/fileutils.rb:528:in `block in mv'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/fileutils.rb:1571:in `block in fu_each_src_dest'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/fileutils.rb:1587:in `fu_each_src_dest0'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/fileutils.rb:1569:in `fu_each_src_dest'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/fileutils.rb:517:in `mv'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/moved.rb:69:in `move_back'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/moved.rb:15:in `uninstall_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:403:in `block in uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:400:in `uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:353:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:115:in `uninstall_existing_cask'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:76:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:104:in `reinstall'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/reinstall.rb:10:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/reinstall.rb:5:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/reinstall.rb:5:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

How do I check the permissions on app and Caskroom?

**Comment by vitorgalvao** [comment]
@joh-klein 

```
ls -ld /Applications/KeeWeb.app
ls -ld "$(brew --prefix)/Caskroom"
ls -ld "$(brew --prefix)/Caskroom/keeweb"
```

**Comment by joh-klein** [comment]
Thanks for that! I can see, that `/Applications/KeeWeb.app` has `root staff` permissions set and the others have only `user admin` permissions. No idea how that happened.
After a good old `chown user:admin /Applications/KeeWeb.app` I finally got somewhere:

```
==> Verifying checksum for Cask keeweb
==> Uninstalling Cask keeweb
==> Moving App 'KeeWeb.app' back to '/usr/local/Caskroom/keeweb/1.6.1/KeeWeb.app
==> Purging files for version 1.6.1 of Cask keeweb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> chmod: Unable to change file mode on /usr/local/Caskroom/keeweb/1.6.1/KeeWeb
==> Using sudo to gain ownership of path '/usr/local/Caskroom/keeweb/1.6.1'
Password:
==> Installing Cask keeweb
==> Moving App 'KeeWeb.app' to '/Applications/KeeWeb.app'.
🍺  keeweb was successfully installed!
```

It looks better now. Thanks all.

**Comment by joh-klein** [comment]
Alright, I found the culprit. The first time I start KeeWeb, it opens with the message:

> Your KeeWeb app is currently not guarded against unauthorized changes. We're asking you for permissions to make the app writable only for administrators.
Don't want to give permissions? You can do it yourself in Terminal:
sudo chown -R root /Applications/KeeWeb.app

And of course, after that, the permissions are back to were they were …

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/pull/42368

**Comment by joh-klein** [comment]
Cool. Nice! That doesn't solve the problem with KeeWeb though … :) I'll see, what I can do PR wise, but wouldn't mind, if someone else did it first.

**Comment by joh-klein** [comment]
@vitorgalvao `uninstall_preflight` didn't fix it for me. At least in the keeweb cask when I try `brew cask reinstall keeweb` the preflight is not run (even though it says ` Uninstalling Cask keeweb` in the logs). What to do?

**Comment by vitorgalvao** [comment]
@joh-klein When you install a cask, we keep a copy of it at the time of installation. When you uninstall, it uses that copy. This is to avoid conflicts between installed versions.

So in this case you’ll need to fix the permissions yourself before uninstalling the first time. Use [the same command you mentioned previously](https://github.com/caskroom/homebrew-cask/issues/42219#issuecomment-354383817) to give yourself permissions.

**Comment by joh-klein** [comment]
OK. I assumed that
```
  uninstall_preflight do
    set_ownership "#{appdir}/KeeWeb.app"
  end
```

would set the ownership of that specific director (to whatever).

So there is no way to fix this problem automatically? Which would mean that your fix to the Keepassx.rb didn't help either …

**Comment by vitorgalvao** [comment]
It does fix it, but only for people that install it starting from the time the fix was added. So if you change permissions manually now and uninstall, after you install again, it’ll work correctly.

**Comment by joh-klein** [comment]
Ah, thats the part I was missing. Great! Now that I have done the old reinstall, the "new" works as expected. Thank you for your patience.
