### ISSUE TITLE
adb can't be installed

### ISSUE THREAD

**Issue by passsy** [caskroom/homebrew-cask#42372]
### Description

After https://github.com/caskroom/homebrew-cask/pull/42094 got merged `adb` doesn't get installed automatically. Installing `android-platform-tools` could fix it but it's still marked as conflicted with `android-sdk`. 

**The conflict can now be removed as they aren't conflicting anymore.**

Right now it is not possible to have `android-sdk` installed and a working `adb` without manual linking after installing the platform-tools with the sdkmanager.

### Example

```
> brew cask install android-sdk  
> adb                          
zsh: command not found: adb

> brew cask install android-platform-tools --verbose --debug --force
==> Hbc::Installer#install
Error: Cask 'android-platform-tools' conflicts with 'android-sdk'.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:93:in `block in check_conflicts'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/set.rb:306:in `each_key'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/set.rb:306:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:89:in `check_conflicts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:72:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:20:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/42374
