### ISSUE TITLE
virtualbox download error

### ISSUE THREAD

**Issue by mbroomfield-r7** [caskroom/homebrew-cask#42485]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

I run `brew cask upgrade` and vagrant fails to upgrade.

#### Output of your command with `--verbose --debug`

```
bos-mbp-4353:~ mbroomfield$ brew cask upgrade --verbose --debug
==> Upgrading 1 outdated package, with result:
virtualbox 5.2.4-119785
==> Started upgrade process for Cask virtualbox
==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading http://download.virtualbox.org/virtualbox/5.2.4/VirtualBox-5.2.4-119785-OSX.dmg
/usr/bin/curl --show-error --user-agent Homebrew/1.4.2 (Macintosh; Intel Mac OS X 10.13.2) curl/7.54.0 --fail --location --remote-time --continue-at - --output /Users/mbroomfield/Library/Caches/Homebrew/Cask/virtualbox--5.2.4-119785.dmg.incomplete http://download.virtualbox.org/virtualbox/5.2.4/VirtualBox-5.2.4-119785-OSX.dmg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to create the file 
Warning: /Users/mbroomfield/Library/Caches/Homebrew/Cask/virtualbox--5.2.4-1197
Warning: 85.dmg.incomplete: No such file or directory
  0 91.1M    0  1354    0     0  14220      0  1:52:04 --:--:--  1:52:04 14252
curl: (23) Failed writing body (0 != 1354)
==> Purging files for version 5.2.4-119785 of Cask virtualbox
Error: Download failed on Cask 'virtualbox' with message: Download failed: http://download.virtualbox.org/virtualbox/5.2.4/VirtualBox-5.2.4-119785-OSX.dmg
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/download.rb:42:in `rescue in fetch'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/download.rb:40:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/download.rb:15:in `perform'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:126:in `download'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:51:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/upgrade.rb:56:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/upgrade.rb:29:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/upgrade.rb:29:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
bos-mbp-4353:~ mbroomfield$ 
```

#### Output of `brew cask doctor`

```
bos-mbp-4353:~ mbroomfield$ brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.4.2
caskroom/homebrew-cask (git revision 0b395; last commit 2018-01-03)
==> macOS
10.13.2
==> Java
9, 1.8.0_131
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3880 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (176 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/universal-darwin9.0
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/usr/local/bin/bash"
bos-mbp-4353:~ mbroomfield$ 
```

**Comment by commitay** [comment]
```
==> Upgrading 1 outdated package, with result:
virtualbox 5.2.4-119785
```
```
Error: Download failed on Cask 'virtualbox'
```
Please try: 
```
$ brew cask cleanup

$ brew cask fetch --verbose --debug virtualbox

$ brew cask upgrade
```

**Comment by mbroomfield-r7** [comment]
That did the tick, thank you :)

```
bos-mbp-4353:~ mbroomfield$ brew cask cleanup                                                                                                                   [83/83]
==> Removing cached downloads                                                                                                                                          
Nothing to do                                                                                                                                                          
bos-mbp-4353:~ mbroomfield$ brew cask fetch --verbose --debug virtualbox                                                                                               
==> Downloading external files for Cask virtualbox                                                                                                                     
==> Downloading http://download.virtualbox.org/virtualbox/5.2.4/VirtualBox-5.2.4-119785-OSX.dmg                                                                        
/usr/bin/curl --show-error --user-agent Homebrew/1.4.2 (Macintosh; Intel Mac OS X 10.13.2) curl/7.54.0 --fail --location --remote-time --continue-at - --output /Users/
mbroomfield/Library/Caches/Homebrew/Cask/virtualbox--5.2.4-119785.dmg.incomplete http://download.virtualbox.org/virtualbox/5.2.4/VirtualBox-5.2.4-119785-OSX.dmg       
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current                                                                                        
                                 Dload  Upload   Total   Spent    Left  Speed                                                                                          
100 91.1M  100 91.1M    0     0   570k      0  0:02:43  0:02:43 --:--:-- 1005k                                                                                         
==> Verifying download                                                                                                                                                 
==> Determining which verifications to run for Cask virtualbox                                                                                                         
==> Checking for verification class Hbc::Verify::Checksum                                                                                                              
==> 1 verifications defined                                                                                                                                            
Hbc::Verify::Checksum                                                                                                                                                  
==> Running verification of class Hbc::Verify::Checksum                                                                                                                
==> Verifying checksum for Cask virtualbox                                                                                                                             
==> SHA256 checksums match                                                                                                                                             
==> Success! Downloaded to -> /Users/mbroomfield/Library/Caches/Homebrew/Cask/virtualbox--5.2.4-119785.dmg                                                             
bos-mbp-4353:~ mbroomfield$ brew cask upgrade                                                                                                                          
==> Upgrading 1 outdated package, with result:                                                                                                                         
virtualbox 5.2.4-119785                                                                                                                                                
==> Satisfying dependencies                                                                                                                                            
==> Downloading http://download.virtualbox.org/virtualbox/5.2.4/VirtualBox-5.2.4-119785-OSX.dmg                                                                        
Already downloaded: /Users/mbroomfield/Library/Caches/Homebrew/Cask/virtualbox--5.2.4-119785.dmg                                                                       
==> Verifying checksum for Cask virtualbox                                                                                                                             
==> Starting upgrade for Cask virtualbox                                                                                                                               
==> Running uninstall process for virtualbox; your password may be necessary                                                                                           
==> Running uninstall script VirtualBox_Uninstall.tool                                                                                                                 
Password:
==>                                                                                                                                                             [52/83]
==> Welcome to the VirtualBox uninstaller script.                                                                                                                      
==>                                                                                                                                                                    
==> The following files and directories (bundles) will be removed:                                                                                                     
==>     /Users/mbroomfield/Library/LaunchAgents/org.virtualbox.vboxwebsrv.plist                                                                                        
==>     /usr/local/bin/VirtualBox                                                                                                                                      
==>     /usr/local/bin/VBoxManage                                                                                                                                      
==>     /usr/local/bin/VBoxVRDP                                                                                                                                        
==>     /usr/local/bin/VBoxHeadless                                                                                                                                    
==>     /usr/local/bin/vboxwebsrv                                                                                                                                      
==>     /usr/local/bin/VBoxBugReport                                                                                                                                   
==>     /usr/local/bin/VBoxBalloonCtrl                                                                                                                                 
==>     /usr/local/bin/VBoxAutostart                                                                                                                                   
==>     /usr/local/bin/VBoxDTrace                                                                                                                                      
==>     /usr/local/bin/vbox-img                                                                                                                                        
==>     /Library/LaunchDaemons/org.virtualbox.startup.plist
==>     /Library/Python/2.6/site-packages/vboxapi/VirtualBox_constants.py
==>     /Library/Python/2.6/site-packages/vboxapi/VirtualBox_constants.pyc
==>     /Library/Python/2.6/site-packages/vboxapi/__init__.py
==>     /Library/Python/2.6/site-packages/vboxapi/__init__.pyc
==>     /Library/Python/2.6/site-packages/vboxapi-1.0-py2.6.egg-info
==>     /Library/Python/2.7/site-packages/vboxapi/VirtualBox_constants.py
==>     /Library/Python/2.7/site-packages/vboxapi/VirtualBox_constants.pyc
==>     /Library/Python/2.7/site-packages/vboxapi/__init__.py
==>     /Library/Python/2.7/site-packages/vboxapi/__init__.pyc
==>     /Library/Python/2.7/site-packages/vboxapi-1.0-py2.7.egg-info
==>     /Library/Application Support/VirtualBox/LaunchDaemons/
==>     /Library/Application Support/VirtualBox/VBoxDrv.kext/
==>     /Library/Application Support/VirtualBox/VBoxUSB.kext/
==>     /Library/Application Support/VirtualBox/VBoxNetFlt.kext/
==>     /Library/Application Support/VirtualBox/VBoxNetAdp.kext/
==>     /Applications/VirtualBox.app/
==>     /Library/Python/2.6/site-packages/vboxapi/
==>     /Library/Python/2.7/site-packages/vboxapi/
==>
==> And the following KEXTs will be unloaded:
==>     org.virtualbox.kext.VBoxUSB
==>     org.virtualbox.kext.VBoxNetFlt
==>     org.virtualbox.kext.VBoxNetAdp
==>     org.virtualbox.kext.VBoxDrv
==>
==> And the traces of following packages will be removed:
==>     org.virtualbox.pkg.vboxkexts
==>     org.virtualbox.pkg.virtualbox
==>     org.virtualbox.pkg.virtualboxcli
==>                                                                                                                                                                    
==> The uninstallation processes requires administrative privileges                                                                                                    
==> because some of the installed files cannot be removed by a normal                                                                                                  
==> user. You may be prompted for your password now...                                                                                                                 
==>                                                                                                                                                                    
==> unloading org.virtualbox.kext.VBoxUSB                                                                                                                              
==> unloading org.virtualbox.kext.VBoxNetFlt                                                                                                                           
==> unloading org.virtualbox.kext.VBoxNetAdp                                                                                                                           
==> unloading org.virtualbox.kext.VBoxDrv
==> Successfully unloaded VirtualBox kernel extensions.
==> Forgot package 'org.virtualbox.pkg.vboxkexts' on '/'.
==> Forgot package 'org.virtualbox.pkg.virtualbox' on '/'.
==> Forgot package 'org.virtualbox.pkg.virtualboxcli' on '/'.
==> Done.
==> Uninstalling packages:
==> Running installer for virtualbox; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
==> installer: Package name is Oracle VM VirtualBox
==> installer: Installing at base path /
==> installer:PHASE:Preparing for installation…
==> installer:PHASE:Preparing the disk…
==> installer:PHASE:Preparing Oracle VM VirtualBox…
==> installer:PHASE:Waiting for other installations to complete…
==> installer:PHASE:Configuring the installation…
==> installer:STATUS:
==> installer:%14.192186
==> installer:PHASE:Writing files…
==> installer:%45.866634
==> installer:PHASE:Optimizing system for installed software…
==> installer:%86.660533
==> installer:PHASE:Running package scripts…
==> installer:%87.714459
==> installer:PHASE:Running package scripts…
==> installer:%88.763017
==> installer:PHASE:Running package scripts…
==> installer:%89.818335
==> installer:PHASE:Running package scripts…
==> installer:%90.870804
==> installer:PHASE:Running package scripts…
==> installer:%91.177753
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Validating packages…
==> installer:%97.750000
==> installer:STATUS:Running installer actions…
==> installer:STATUS:
==> installer:PHASE:Finishing the Installation…
==> installer:STATUS:
==> installer:%100.000000
==> installer:PHASE:The software was successfully installed.
==> installer: The install was successful.
==> Purging files for version 5.2.0-118431 of Cask virtualbox
🍺  virtualbox was successfully upgraded!
bos-mbp-4353:~ mbroomfield$
```
