### ISSUE TITLE
`brew cask list` fails if previously installed but now unavailable cask

### ISSUE THREAD

**Issue by mrkev** [caskroom/homebrew-cask#42527]
#### Description of issue

1. I run `brew cask list`
2. I get output with a few warnings (usual, outdated casks), and also this:

```
Error: Cask 'utorrent' is unavailable: No Cask with this name exists.
```

3. `brew cask list` exits with status code 1, and never prints the casks I have installed

`brew cask uninstall | install | zap` also print `Error: Cask 'utorrent' is unavailable: No Cask with this name exists.` and exit with status code 1. I'm unsure how to fix this so `brew cask` forgets about utorrent and I can list my casks again.

#### Output of your command with `--verbose --debug`

Note, I don't think the warnings are consequential, but including them for for the sake of full information.

```
$ brew cask list --verbose --debug
Warning: Calling "cask :v1 => 'token'" is deprecated!
Use "cask 'token'" instead.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:23:in `load'

Warning: Calling Hbc::DSL#license is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:31:in `block in load'

Warning: Unexpected method 'tags' called on Cask flash.
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask#reporting-bugs
Warning: Calling Hbc::DSL#license is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:30:in `block in load'

Warning: Calling Hbc::DSL#license is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:31:in `block in load'

Warning: Calling Hbc::DSL#license is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:32:in `block in load'

Warning: Calling "cask :v1 => 'token'" is deprecated!
Use "cask 'token'" instead.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:23:in `load'

Warning: Calling Hbc::DSL#license is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:30:in `block in load'

Error: Cask 'utorrent' is unavailable: No Cask with this name exists.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:159:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:168:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/scopes.rb:41:in `block in installed'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/scopes.rb:31:in `map'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/scopes.rb:31:in `installed'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/list.rb:40:in `list_installed'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/list.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'

```

#### Output of `brew cask doctor`

```
$ brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.4.2-4-g069b610
caskroom/homebrew-cask (git revision 9a9bf; last commit 2018-01-05)
==> macOS
10.13.2
==> Java
1.8.0, 1.7.0_51, 1.6.0_65-b14-468
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3881 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (176 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin17
/Library/Ruby/Site/2.3.0/universal-darwin17
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin17
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

**Comment by commitay** [comment]
Removing the `utorrent` folder from `/usr/local/Caskroom` should fix this.

**Comment by mrkev** [comment]
That did it. Thanks! 👍
