### ISSUE TITLE
brew cask style failing

### ISSUE THREAD

**Issue by mackoz** [caskroom/homebrew-cask#42592]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

My `brew cask style` command is failing. First encountered this while trying to update a cask and reported it to https://github.com/vitorgalvao/tiny-scripts/issues/116. I thought the issue was fixed because previously when I called `brew cask style`, it would return a different error message than my current one.

#### Output of your command with `--verbose --debug`

```
➜ brew cask style --verbose --debug
Error: style check failed
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/style.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

#### Output of `brew cask doctor`

```
➜ brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.4.2-14-g3e99504
caskroom/homebrew-cask (git revision dd0d0; last commit 2018-01-08)
==> macOS
10.12.6
==> Java
9.0.1, 1.8.0_92-zulu-8.15.0.3, 1.7.0_161-zulu-7.21.0.3, 1.7.0_75
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (1 files, 60.5MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3887 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-drivers (139 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-eid (10 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-fonts (1120 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (175 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/universal-darwin9.0
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/usr/local/bin/zsh"
```

**Comment by commitay** [comment]
Please post the output of `gem env` and `du -hd3 ~/.gem/ruby`

**Comment by mackoz** [comment]
```
➜ gem env

RubyGems Environment:
  - RUBYGEMS VERSION: 2.7.4
  - RUBY VERSION: 2.5.0 (2017-12-25 patchlevel 0) [x86_64-darwin16]
  - INSTALLATION DIRECTORY: /usr/local/lib/ruby/gems/2.5.0
  - USER INSTALLATION DIRECTORY: /Users/william.lu/.gem/ruby/2.5.0
  - RUBY EXECUTABLE: /usr/local/opt/ruby/bin/ruby
  - EXECUTABLE DIRECTORY: /usr/local/bin
  - SPEC CACHE DIRECTORY: /Users/william.lu/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /usr/local/Cellar/ruby/2.5.0/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-16
  - GEM PATHS:
     - /usr/local/lib/ruby/gems/2.5.0
     - /Users/william.lu/.gem/ruby/2.5.0
     - /usr/local/Cellar/ruby/2.5.0/lib/ruby/gems/2.5.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /usr/local/Cellar/rbenv/1.1.1/libexec
     - /usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin
     - /Users/william.lu/.rbenv/shims
     - /Users/william.lu/.jenv/shims
     - /Users/william.lu/.rbenv/shims
     - /usr/local/Cellar/zplug/2.4.2/repos/zplug/zplug/bin
     - /Users/william.lu/.jenv/bin
     - /Users/william.lu/go/bin
     - /Users/william.lu/bin
     - /usr/local/bin
     - /usr/local/sbin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
```
```
➜ du -hd3 ~/.gem/ruby
8.0K	/Users/william.lu/.gem/ruby/2.0.0/bin
  0B	/Users/william.lu/.gem/ruby/2.0.0/build_info
708K	/Users/william.lu/.gem/ruby/2.0.0/cache
  0B	/Users/william.lu/.gem/ruby/2.0.0/doc
 84K	/Users/william.lu/.gem/ruby/2.0.0/gems/ast-2.3.0
 28K	/Users/william.lu/.gem/ruby/2.0.0/gems/parallel-1.11.2
4.3M	/Users/william.lu/.gem/ruby/2.0.0/gems/parser-2.4.0.0
264K	/Users/william.lu/.gem/ruby/2.0.0/gems/powerpack-0.1.1
360K	/Users/william.lu/.gem/ruby/2.0.0/gems/public_suffix-2.0.5
232K	/Users/william.lu/.gem/ruby/2.0.0/gems/ruby-progressbar-1.8.1
 52K	/Users/william.lu/.gem/ruby/2.0.0/gems/unicode-display_width-1.1.3
5.3M	/Users/william.lu/.gem/ruby/2.0.0/gems
 28K	/Users/william.lu/.gem/ruby/2.0.0/specifications
6.0M	/Users/william.lu/.gem/ruby/2.0.0
 12K	/Users/william.lu/.gem/ruby/2.3.0/bin
  0B	/Users/william.lu/.gem/ruby/2.3.0/build_info
1.4M	/Users/william.lu/.gem/ruby/2.3.0/cache
  0B	/Users/william.lu/.gem/ruby/2.3.0/doc
4.0K	/Users/william.lu/.gem/ruby/2.3.0/extensions/universal-darwin-9
4.0K	/Users/william.lu/.gem/ruby/2.3.0/extensions
 84K	/Users/william.lu/.gem/ruby/2.3.0/gems/ast-2.3.0
 28K	/Users/william.lu/.gem/ruby/2.3.0/gems/parallel-1.12.0
4.3M	/Users/william.lu/.gem/ruby/2.3.0/gems/parser-2.4.0.0
264K	/Users/william.lu/.gem/ruby/2.3.0/gems/powerpack-0.1.1
408K	/Users/william.lu/.gem/ruby/2.3.0/gems/public_suffix-3.0.0
152K	/Users/william.lu/.gem/ruby/2.3.0/gems/rainbow-2.2.2
2.6M	/Users/william.lu/.gem/ruby/2.3.0/gems/rubocop-0.50.0
2.7M	/Users/william.lu/.gem/ruby/2.3.0/gems/rubocop-0.51.0
124K	/Users/william.lu/.gem/ruby/2.3.0/gems/rubocop-cask-0.14.2
124K	/Users/william.lu/.gem/ruby/2.3.0/gems/rubocop-cask-0.14.4
120K	/Users/william.lu/.gem/ruby/2.3.0/gems/rubocop-cask-0.15.1
120K	/Users/william.lu/.gem/ruby/2.3.0/gems/ruby-progressbar-1.9.0
 52K	/Users/william.lu/.gem/ruby/2.3.0/gems/unicode-display_width-1.3.0
 11M	/Users/william.lu/.gem/ruby/2.3.0/gems
 52K	/Users/william.lu/.gem/ruby/2.3.0/specifications
 13M	/Users/william.lu/.gem/ruby/2.3.0
 19M	/Users/william.lu/.gem/ruby
```

**Comment by commitay** [comment]
Please run `gem uninstall --all --executables rubocop rubocop-cask` and confirm that they have been removed from `~/.gem/ruby/2.3.0/gems/`

**Comment by mackoz** [comment]
```
➜ gem uninstall --all --executables rubocop rubocop-cask
Gem 'rubocop' is not installed
Gem 'rubocop-cask' is not installed
```
Should I just remove it manually?

**Comment by mackoz** [comment]
Got it working, reinstalled ruby 2.3.0 and it uninstalled successfully, thanks for the help
