### ISSUE TITLE
VLC Install Failed Command

### ISSUE THREAD

**Issue by maxexcloo** [caskroom/homebrew-cask#42631]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [X] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [X] None of the templates was appropriate for my issue, or I’m not sure.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

When attempting to install VLC, a command fails.

#### Output of your command with `--verbose --debug`

```
MacBook-Pro:~ max.schaefer$ brew cask install --verbose --debug vlc
==> Hbc::Installer#install
==> Printing caveats
==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://get.videolan.org/vlc/2.2.8/macosx/vlc-2.2.8.dmg
Already downloaded: /Users/max.schaefer/Library/Caches/Homebrew/Cask/vlc--2.2.8.dmg
==> Downloaded to -> /Users/max.schaefer/Library/Caches/Homebrew/Cask/vlc--2.2.8.dmg
==> Verifying download
==> Determining which verifications to run for Cask vlc
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask vlc
==> SHA256 checksums match
==> Installing Cask vlc
==> Hbc::Installer#stage
==> Extracting primary container
==> Determining which containers to use based on filetype
==> Checking container class Hbc::Container::Pkg
==> Checking container class Hbc::Container::Ttf
==> Checking container class Hbc::Container::Otf
==> Checking container class Hbc::Container::Air
==> Checking container class Hbc::Container::Cab
==> Checking container class Hbc::Container::Dmg
==> Executing: ["/usr/bin/hdiutil", "imageinfo", "/Users/max.schaefer/Library/Caches/Homebrew/Cask/vlc--2.2.8.dmg"]
==> Using container class Hbc::Container::Dmg for /Users/max.schaefer/Library/Caches/Homebrew/Cask/vlc--2.2.8.dmg
==> Executing: ["/usr/bin/hdiutil", "attach", "-plist", "-nobrowse", "-readonly", "-noidme", "-mountrandom", "/var/folders/qt/m073xcf17fx_8x19w50nnknh0000gn/T/d20180109-13167-xol0xh", "/Users/max.schaefer/Library/Caches/Homebrew/Cask/vlc--2.2.8.dmg"]
==> Executing: ["/usr/bin/find", ".", "-print0"]
==> Executing: ["/usr/bin/mkbom", "-s", "-i", "/var/folders/qt/m073xcf17fx_8x19w50nnknh0000gn/T/20180109-13167-1s9gwuu.list", "--", "/var/folders/qt/m073xcf17fx_8x19w50nnknh0000gn/T/20180109-13167-n3xgj9.bom"]
==> Executing: ["/usr/bin/ditto", "--bom", "/var/folders/qt/m073xcf17fx_8x19w50nnknh0000gn/T/20180109-13167-n3xgj9.bom", "--", "/private/var/folders/qt/m073xcf17fx_8x19w50nnknh0000gn/T/d20180109-13167-xol0xh/dmg.AyBe61", "/usr/local/Caskroom/vlc/2.2.8"]
==> Executing: ["/usr/sbin/diskutil", "eject", "/private/var/folders/qt/m073xcf17fx_8x19w50nnknh0000gn/T/d20180109-13167-xol0xh/dmg.AyBe61"]
==> Creating metadata directory /usr/local/Caskroom/vlc/.metadata/2.2.8/20180109040317.527.
==> Creating metadata subdirectory /usr/local/Caskroom/vlc/.metadata/2.2.8/20180109040317.527/Casks.
==> Installing artifacts
==> 4 artifact/s defined
#<SortedSet:0x007fd549033c40>
==> Installing artifact of class Hbc::Artifact::PreflightBlock
==> Installing artifact of class Hbc::Artifact::App
==> Moving App 'VLC.app' to '/Applications/VLC.app'.
==> Installing artifact of class Hbc::Artifact::Binary
==> Linking Binary 'vlc.wrapper.sh' to '/usr/local/bin/vlc'.
==> Executing: ["/bin/ln", "-h", "-f", "-s", "--", "/usr/local/Caskroom/vlc/2.2.8/vlc.wrapper.sh", "/usr/local/bin/vlc"]
==> Adding com.apple.metadata:kMDItemAlternateNames metadata
==> Executing: ["/usr/bin/xattr", "-p", "com.apple.metadata:kMDItemAlternateNames", "/usr/local/Caskroom/vlc/2.2.8/vlc.wrapper.sh"]
==> Existing metadata is: ''
==> Executing: ["/bin/chmod", "--", "u+rw", "/usr/local/Caskroom/vlc/2.2.8/vlc.wrapper.sh", "/usr/local/Caskroom/vlc/2.2.8/vlc.wrapper.sh"]
==> Executing: ["/usr/bin/xattr", "-w", "com.apple.metadata:kMDItemAlternateNames", "(\"vlc\")", "/usr/local/Caskroom/vlc/2.2.8/vlc.wrapper.sh"]
==> Reverting installation of artifact of class Hbc::Artifact::App
==> Moving App 'VLC.app' back to '/usr/local/Caskroom/vlc/2.2.8/VLC.app'.
==> Reverting installation of artifact of class Hbc::Artifact::PreflightBlock
==> Purging files for version 2.2.8 of Cask vlc
Error: Command failed to execute!

==> Failed command:
/usr/bin/xattr -w com.apple.metadata:kMDItemAlternateNames ("vlc") /usr/local/Caskroom/vlc/2.2.8/vlc.wrapper.sh

==> Standard Output of failed command:


==> Standard Error of failed command:
Traceback (most recent call last):
  File "/usr/bin/xattr-2.7", line 7, in <module>
    from pkg_resources import load_entry_point
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 3095, in <module>
    @_call_aside
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 3081, in _call_aside
    f(*args, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 3108, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 658, in _build_master
    ws.require(__requires__)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 959, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 846, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'xattr==0.6.4' distribution was not found and is required by the application


==> Exit status of failed command:
#<Process::Status: pid 13309 exit 1>

/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:70:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:36:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:18:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/relocated.rb:70:in `add_altname_metadata'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/symlinked.rb:60:in `create_filesystem_link'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/symlinked.rb:48:in `link'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/binary.rb:7:in `link'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/symlinked.rb:15:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:174:in `block in install_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:166:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:80:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:20:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

#### Output of `brew cask doctor`

```
MacBook-Pro:~ max.schaefer$ brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.4.3
caskroom/homebrew-cask (git revision dd5e7; last commit 2018-01-09)
==> macOS
10.13.2
==> Java
N/A
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (1 files, 35.1MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3888 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (175 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin17
/Library/Ruby/Site/2.3.0/universal-darwin17
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin17
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/usr/local/bin/bash"
```

**Comment by commitay** [comment]
Please post the output of `brew doctor` and `which -a xattr`

**Comment by maxexcloo** [comment]
```
MacBook-Pro:~ max.schaefer$ brew doctor
Your system is ready to brew.
```

```
MacBook-Pro:~ max.schaefer$ which -a xattr
/usr/bin/xattr
```

**Comment by commitay** [comment]
Have you ever installed a non-Homebrew python framework?

**Comment by maxexcloo** [comment]
I have not.

**Comment by commitay** [comment]
We've had a few `xattr` errors reported previously but we haven't been able to find a solution.

Usually it seems to occur as a result of another python (non-homebrew) being installed, as that isn't the case I'm not sure what the cause of this is.

`/usr/bin/xattr` and `/System/Library/Frameworks/Python.framework` should both be protected by SIP so in theory it shouldn't be possible to modify them.

**Comment by maxexcloo** [comment]
I do have SIP disabled currently, is there any way to reset these to default? As far as I'm aware I haven't installed anything that would break these.

**Comment by commitay** [comment]
AKAIK there is a way to reset them but I can't really provide any instructions as to how to do so.

**Comment by vitorgalvao** [comment]
This is not really something we want to support. We try to support a system with the default security features enabled. If your SIP is disabled and system tools `xattr` were modified as a result (either with your knowledge or not), that is not something we intend to support.

**Comment by commitay** [comment]
@vitorgalvao Adding SIP to `doctor` might be a good idea.

```diff
diff --git a/Library/Homebrew/cask/lib/hbc/cli/doctor.rb b/Library/Homebrew/cask/lib/hbc/cli/doctor.rb
index d7bcf1537..00806b42e 100644
--- a/Library/Homebrew/cask/lib/hbc/cli/doctor.rb
+++ b/Library/Homebrew/cask/lib/hbc/cli/doctor.rb
@@ -12,6 +12,7 @@ module Hbc
       def run
         ohai "Homebrew-Cask Version", Hbc.full_version
         ohai "macOS", MacOS.full_version
+        ohai "SIP", self.class.csrutil
         ohai "Java", SystemConfig.describe_java
         ohai "Homebrew-Cask Install Location", self.class.render_install_location
         ohai "Homebrew-Cask Staging Location", self.class.render_staging_location(Hbc.caskroom)
@@ -37,6 +38,10 @@ module Hbc
         (self.class.locale_variables + environment_variables).sort.each(&self.class.method(:render_env_var))
       end

+      def self.csrutil
+        Open3.capture2("/usr/bin/csrutil", "status")[0].split[4].chomp(".").capitalize
+      end
+
       def self.locale_variables
         ENV.keys.grep(/^(?:LC_\S+|LANG|LANGUAGE)\Z/).sort
       end
```

```
$ brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.4.3-2-ge268a9f
caskroom/homebrew-cask (git revision a68a; last commit 2018-01-09)
==> macOS
10.13.2
==> SIP
Enabled
==> Java
N/A
```

**Comment by vitorgalvao** [comment]
@commitay Agreed.

**Comment by commitay** [comment]
Updated post, output can vary on older OS.
