### ISSUE TITLE
Uninstall\Reinstall Photoshop CS6, CleanMyMac fail.

### ISSUE THREAD

**Issue by hxueh** [caskroom/homebrew-cask#42796]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

I have changed my Mac username few days ago (I don't know whether it will have some impact or not). I have uninstalled Adobe PS CS6 using adobe's tool, but now I can't remove it from brew cask list. Also, uninstalling Clean My Mac doesn't works.

#### Output of your command with `--verbose --debug`

brew cask uninstall adobe-photoshop-cs6 --verbose --debug
```
==> Uninstalling Cask adobe-photoshop-cs6
==> Uninstalling Cask adobe-photoshop-cs6
==> Un-installing artifacts
==> 4 artifact/s defined
#<SortedSet:0x007f81853fd938>
==> Un-installing artifact of class Hbc::Artifact::PreflightBlock
==> Un-installing artifact of class Hbc::Artifact::PreflightBlock
==> Un-installing artifact of class Hbc::Artifact::Uninstall
==> Running uninstall process for adobe-photoshop-cs6; your password may be necessary
==> Signalling 'KILL' to application ID 'SafariNotificationAgent'
==> Executing: ["/bin/launchctl", "list"]
==> Running uninstall script Adobe Photoshop CS6/Install.app/Contents/MacOS/Install
==> Executing: ["/bin/chmod", "--", "+x", "/usr/local/Caskroom/adobe-photoshop-cs6/13.0/Adobe Photoshop CS6/Install.app/Contents/MacOS/Install"]
==> Executing: ["/usr/bin/sudo", "-E", "--", "/usr/local/Caskroom/adobe-photoshop-cs6/13.0/Adobe Photoshop CS6/Install.app/Contents/MacOS/Install", "--mode=silent", "--deploymentFile=/usr/local/Caskroom/adobe-photoshop-cs6/13.0/Adobe Photoshop CS6/Deployment/en_US_Uninstall.xml"]
==> Starting Installer...
==> In Silent mode.
==> Begin Adobe Setup
==> UI mode: Silent
2.00%
==> Error : The product is not installed, cannot uninstall.
==> Exit Code: 33
==> Exiting Installer with Code: 33
Error: Command failed to execute!

==> Failed command:
/usr/bin/sudo -E -- /usr/local/Caskroom/adobe-photoshop-cs6/13.0/Adobe Photoshop CS6/Install.app/Contents/MacOS/Install --mode=silent --deploymentFile=/usr/local/Caskroom/adobe-photoshop-cs6/13.0/Adobe Photoshop CS6/Deployment/en_US_Uninstall.xml

==> Standard Output of failed command:
Begin Adobe Setup
UI mode: Silent
2.00%
Error : The product is not installed, cannot uninstall.
Exit Code: 33


==> Standard Error of failed command:
Starting Installer...
In Silent mode.
Exiting Installer with Code: 33


==> Exit status of failed command:
#<Process::Status: pid 31464 exit 33>

/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:70:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:36:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb:205:in `uninstall_script'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb:59:in `block in dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb:56:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb:56:in `dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall.rb:7:in `uninstall_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:403:in `block in uninstall_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:400:in `uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:353:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:22:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:12:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:12:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

brew cask uninstall cleanmymac --verbose --debug
```
==> Uninstalling Cask cleanmymac
==> Uninstalling Cask cleanmymac
==> Un-installing artifacts
==> 3 artifact/s defined
#<SortedSet:0x007ff15e380c00>
==> Un-installing artifact of class Hbc::Artifact::Uninstall
==> Running uninstall process for cleanmymac; your password may be necessary
==> Removing launchctl service com.macpaw.CleanMyMac3.Agent
==> Executing: ["/bin/launchctl", "list", "com.macpaw.CleanMyMac3.Agent"]
==> Executing: ["/usr/bin/sudo", "-E", "--", "/bin/launchctl", "list", "com.macpaw.CleanMyMac3.Agent"]
==> Removing launchctl service com.macpaw.CleanMyMac3.Scheduler
==> Executing: ["/bin/launchctl", "list", "com.macpaw.CleanMyMac3.Scheduler"]
==> Executing: ["/usr/bin/sudo", "-E", "--", "/bin/launchctl", "list", "com.macpaw.CleanMyMac3.Scheduler"]
==> Quitting application ID com.macpaw.CleanMyMac3
==> Executing: ["/bin/launchctl", "list"]
==> Executing: ["/usr/bin/sudo", "-E", "--", "/usr/bin/osascript", "-e", "tell application id \"com.macpaw.CleanMyMac3\" to quit"]
==> osascript: can't open default scripting component.
Error: Command failed to execute!

==> Failed command:
/usr/bin/sudo -E -- /usr/bin/osascript -e tell application id "com.macpaw.CleanMyMac3" to quit

==> Standard Output of failed command:


==> Standard Error of failed command:
osascript: can't open default scripting component.


==> Exit status of failed command:
#<Process::Status: pid 31935 exit 1>

/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:70:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:36:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:18:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb:121:in `block in uninstall_quit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb:118:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb:118:in `uninstall_quit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb:59:in `block in dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb:56:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb:56:in `dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall.rb:7:in `uninstall_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:403:in `block in uninstall_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:400:in `uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:353:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:22:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:12:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:12:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew-Cask Version
Homebrew-Cask 1.4.3-41-g42be54e
caskroom/homebrew-cask (git revision 7f25a2; last commit 2018-01-14)
==> macOS
10.13.2
==> SIP
Enabled
==> Java
1.8.0_151
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3900 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-fonts (1137 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (175 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin17
/Library/Ruby/Site/2.3.0/universal-darwin17
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin17
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/usr/local/bin/zsh"
```

**Comment by commitay** [comment]
> I have uninstalled Adobe PS CS6 using adobe's tool, but now I can't remove it from brew cask list.

Remove the `adobe-photoshop-cs6` folder from `/usr/local/Caskroom`

>  uninstalling Clean My Mac doesn't works

Please run this to confirm that AppleScript is working.
```
osascript -e 'tell app "Finder" to display dialog "AppleScript works"'
```

**Comment by hxueh** [comment]
@commitay Thanks. It seems that AppleScript doesn't work.
```
osascript: can't open default scripting component.
```

**Comment by commitay** [comment]
`osascript` has issues running remotely over ssh or on a multi-user system.

I'm afraid we are can't really provide any support for resolving this this as `osascript` is a system tool.

**Comment by hxueh** [comment]
I just reboot and it's fixed.

**Comment by commitay** [comment]
I'll make sure to suggest rebooting for future issues relating to `osascript`, thanks for letting us know!
