### ISSUE TITLE
Installing IINA fails

### ISSUE THREAD

**Issue by Samuel3008** [caskroom/homebrew-cask#42818]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

The cask `iina` fails to install. (I ran `brew cask install iina --verbose --debug`)

#### Output of your command with `--verbose --debug`

```
==> Hbc::Installer#install
==> Printing caveats
==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://dl-portal.iina.io/IINA.v0.0.15-build63.dmg
Already downloaded: /Users/samuel/Library/Caches/Homebrew/Cask/iina--0.0.15-build63.dmg
==> Downloaded to -> /Users/samuel/Library/Caches/Homebrew/Cask/iina--0.0.15-build63.dmg
==> Verifying download
==> Determining which verifications to run for Cask iina
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask iina
==> SHA256 checksums match
==> Installing Cask iina
==> Hbc::Installer#stage
==> Extracting primary container
==> Determining which containers to use based on filetype
==> Checking container class Hbc::Container::Pkg
==> Checking container class Hbc::Container::Ttf
==> Checking container class Hbc::Container::Otf
==> Checking container class Hbc::Container::Air
==> Checking container class Hbc::Container::Cab
==> Checking container class Hbc::Container::Dmg
==> Executing: ["/usr/bin/hdiutil", "imageinfo", "/Users/samuel/Library/Caches/Homebrew/Cask/iina--0.0.15-build63.dmg"]
==> Using container class Hbc::Container::Dmg for /Users/samuel/Library/Caches/Homebrew/Cask/iina--0.0.15-build63.dmg
==> Executing: ["/usr/bin/hdiutil", "attach", "-plist", "-nobrowse", "-readonly", "-noidme", "-mountrandom", "/var/folders/dn/dc1dq66n1vz9gzxdhzlhhx8r0000gn/T/d20180114-24101-1uzlf3o", "/Users/samuel/Library/Caches/Homebrew/Cask/iina--0.0.15-build63.dmg"]
==> Executing: ["/usr/bin/find", ".", "-print0"]
==> Executing: ["/usr/bin/mkbom", "-s", "-i", "/var/folders/dn/dc1dq66n1vz9gzxdhzlhhx8r0000gn/T/20180114-24101-kbmi2c.list", "--", "/var/folders/dn/dc1dq66n1vz9gzxdhzlhhx8r0000gn/T/20180114-24101-3ln0s.bom"]
==> Executing: ["/usr/bin/ditto", "--bom", "/var/folders/dn/dc1dq66n1vz9gzxdhzlhhx8r0000gn/T/20180114-24101-3ln0s.bom", "--", "/private/var/folders/dn/dc1dq66n1vz9gzxdhzlhhx8r0000gn/T/d20180114-24101-1uzlf3o/dmg.HdjSuZ", "/usr/local/Caskroom/iina/0.0.15-build63"]
==> Executing: ["/usr/sbin/diskutil", "eject", "/private/var/folders/dn/dc1dq66n1vz9gzxdhzlhhx8r0000gn/T/d20180114-24101-1uzlf3o/dmg.HdjSuZ"]
==> Creating metadata directory /usr/local/Caskroom/iina/.metadata/0.0.15-build63/20180114193144.625.
==> Creating metadata subdirectory /usr/local/Caskroom/iina/.metadata/0.0.15-build63/20180114193144.625/Casks.
==> Installing artifacts
==> 3 artifact/s defined
#<SortedSet:0x007fce819a0e50>
==> Installing artifact of class Hbc::Artifact::App
==> Moving App 'IINA.app' to '/Applications/IINA.app'.
==> Installing artifact of class Hbc::Artifact::Binary
==> Linking Binary 'iina-cli' to '/usr/local/bin/iina'.
==> Executing: ["/bin/ln", "-h", "-f", "-s", "--", "/Applications/IINA.app/Contents/MacOS/iina-cli", "/usr/local/bin/iina"]
==> Adding com.apple.metadata:kMDItemAlternateNames metadata
==> Executing: ["/usr/bin/xattr", "-p", "com.apple.metadata:kMDItemAlternateNames", "/Applications/IINA.app/Contents/MacOS/iina-cli"]
==> Existing metadata is: ''
==> Executing: ["/bin/chmod", "--", "u+rw", "/Applications/IINA.app/Contents/MacOS/iina-cli", "/Applications/IINA.app/Contents/MacOS/iina-cli"]
==> Executing: ["/usr/bin/xattr", "-w", "com.apple.metadata:kMDItemAlternateNames", "(\"iina\")", "/Applications/IINA.app/Contents/MacOS/iina-cli"]
==> Reverting installation of artifact of class Hbc::Artifact::App
==> Moving App 'IINA.app' back to '/usr/local/Caskroom/iina/0.0.15-build63/IINA.app'.
==> Purging files for version 0.0.15-build63 of Cask iina
Error: Command failed to execute!

==> Failed command:
/usr/bin/xattr -w com.apple.metadata:kMDItemAlternateNames ("iina") /Applications/IINA.app/Contents/MacOS/iina-cli

==> Standard Output of failed command:


==> Standard Error of failed command:
Traceback (most recent call last):
  File "/usr/bin/xattr-2.7", line 7, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 72, in <module>
    import packaging.requirements
  File "/usr/local/lib/python2.7/site-packages/packaging/requirements.py", line 59, in <module>
    MARKER_EXPR = originalTextFor(MARKER_EXPR())("marker")
TypeError: __call__() takes exactly 2 arguments (1 given)


==> Exit status of failed command:
#<Process::Status: pid 24256 exit 1>

/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:70:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:36:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:18:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/relocated.rb:70:in `add_altname_metadata'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/symlinked.rb:60:in `create_filesystem_link'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/symlinked.rb:48:in `link'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/binary.rb:7:in `link'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/symlinked.rb:15:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:174:in `block in install_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:166:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:80:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:20:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew-Cask Version
Homebrew-Cask 1.4.3-45-g253a41f
caskroom/homebrew-cask (git revision b1071; last commit 2018-01-14)
==> macOS
10.13.3
==> SIP
Disabled
==> Java
1.8.0_25
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (1 files, 35MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3902 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-drivers (140 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-fonts (1137 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (175 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-eid (10 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin17
/Library/Ruby/Site/2.3.0/universal-darwin17
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin17
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/zsh"
```

**Comment by commitay** [comment]
`/usr/bin/xattr` is a tool provided by the OS, disabling SIP may have allowed for it to be modified.

This is an issue with your system, not Cask. I'm afraid we are unable to provide support for errors with system tools.
