### ISSUE TITLE
Error on uninstall of CleanMyMac 3.9.3

### ISSUE THREAD

**Issue by hoefling** [caskroom/homebrew-cask#42901]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Uninstalling CleanMyMac 3.9.3 ends in a timeout when trying to execute `osascript -e 'tell application "System Events" to delete every login item whose name is "CleanMyMac 3 Menu"'`

##### `update-reset && update`

```
$ brew update-reset && brew update
...
$ echo $?
0
```

##### `cask info`

```
$ brew cask info cleanmymac
cleanmymac: 3.9.3,1514387919
https://macpaw.com/cleanmymac
/usr/local/Caskroom/cleanmymac/3.9.3,1514387919 (64B)
From: https://github.com/caskroom/homebrew-cask/blob/master/Casks/cleanmymac.rb
==> Name
CleanMyMac
==> Artifacts
CleanMyMac 3.app (App)
```

#### Output of your command with `--verbose --debug`

```
$ brew cask uninstall --force --verbose --debug cleanmymac
==> Uninstalling Cask cleanmymac
==> Uninstalling Cask cleanmymac
==> Un-installing artifacts
==> 3 artifact/s defined
#<SortedSet:0x000001013ad700>
==> Un-installing artifact of class Hbc::Artifact::Uninstall
==> Running uninstall process for cleanmymac; your password may be necessary
==> Removing launchctl service com.macpaw.CleanMyMac3.Agent
==> Executing: ["/bin/launchctl", "list", "com.macpaw.CleanMyMac3.Agent"]
==> Executing: ["/usr/bin/sudo", "-E", "--", "/bin/launchctl", "list", "com.macpaw.CleanMyMac3.Agent"]
==> Removing launchctl service com.macpaw.CleanMyMac3.Scheduler
==> Executing: ["/bin/launchctl", "list", "com.macpaw.CleanMyMac3.Scheduler"]
==> Executing: ["/usr/bin/sudo", "-E", "--", "/bin/launchctl", "list", "com.macpaw.CleanMyMac3.Scheduler"]
==> Quitting application ID com.macpaw.CleanMyMac3
==> Executing: ["/bin/launchctl", "list"]
==> Quitting application ID com.macpaw.CleanMyMac3.Menu
==> Executing: ["/bin/launchctl", "list"]
==> Removing login item CleanMyMac 3 Menu
==> Executing: ["/usr/bin/osascript", "-e", "tell application \"System Events\" to delete every login item whose name is \"CleanMyMac 3 Menu\""]
==> 36:93:
==> execution error: System Events got an error: AppleEvent timed out. (-1712)
Error: Command failed to execute!

==> Failed command:
/usr/bin/osascript -e tell application "System Events" to delete every login item whose name is "CleanMyMac 3 Menu"

==> Standard Output of failed command:


==> Standard Error of failed command:
36:93: execution error: System Events got an error: AppleEvent timed out. (-1712)


==> Exit status of failed command:
#<Process::Status: pid 38404 exit 1>

/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:70:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:36:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:18:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb:161:in `block in uninstall_login_item'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb:159:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb:159:in `uninstall_login_item'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb:59:in `block in dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb:56:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb:56:in `dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall.rb:7:in `uninstall_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:403:in `block in uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:400:in `uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:353:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:22:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:12:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:12:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

##### reboot and retry

```
$ sudo reboot
Password:
...
$ brew cask uninstall --force --verbose --debug cleanmymac
==> Uninstalling Cask cleanmymac
==> Uninstalling Cask cleanmymac
==> Un-installing artifacts
==> 3 artifact/s defined
#<SortedSet:0x000001021af128>
==> Un-installing artifact of class Hbc::Artifact::Uninstall
==> Running uninstall process for cleanmymac; your password may be necessary
==> Removing launchctl service com.macpaw.CleanMyMac3.Agent
==> Executing: ["/bin/launchctl", "list", "com.macpaw.CleanMyMac3.Agent"]
==> Executing: ["/usr/bin/sudo", "-E", "--", "/bin/launchctl", "list", "com.macpaw.CleanMyMac3.Agent"]
Password:
==> Removing launchctl service com.macpaw.CleanMyMac3.Scheduler
==> Executing: ["/bin/launchctl", "list", "com.macpaw.CleanMyMac3.Scheduler"]
==> Executing: ["/usr/bin/sudo", "-E", "--", "/bin/launchctl", "list", "com.macpaw.CleanMyMac3.Scheduler"]
==> Quitting application ID com.macpaw.CleanMyMac3
==> Executing: ["/bin/launchctl", "list"]
==> Quitting application ID com.macpaw.CleanMyMac3.Menu
==> Executing: ["/bin/launchctl", "list"]
==> Removing login item CleanMyMac 3 Menu
==> Executing: ["/usr/bin/osascript", "-e", "tell application \"System Events\" to delete every login item whose name is \"CleanMyMac 3 Menu\""]
==> 36:93:
==> execution error: System Events got an error: AppleEvent timed out. (-1712)
Error: Command failed to execute!

==> Failed command:
/usr/bin/osascript -e tell application "System Events" to delete every login item whose name is "CleanMyMac 3 Menu"

==> Standard Output of failed command:


==> Standard Error of failed command:
36:93: execution error: System Events got an error: AppleEvent timed out. (-1712)


==> Exit status of failed command:
#<Process::Status: pid 1840 exit 1>

/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:70:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:36:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:18:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb:161:in `block in uninstall_login_item'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb:159:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb:159:in `uninstall_login_item'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb:59:in `block in dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb:56:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb:56:in `dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall.rb:7:in `uninstall_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:403:in `block in uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:400:in `uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:353:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:22:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:12:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:12:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

#### Output of `brew cask doctor`

```
$ brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.4.3-51-g3e8b057
caskroom/homebrew-cask (git revision a5c83; last commit 2018-01-17)
==> macOS
10.13.2
==> SIP
Enabled
==> Java
1.8.0_152
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (1 files, 38.1MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3899 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-fonts (1137 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (175 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/universal-darwin9.0
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

I have also found a similar issue #42796, although with a different script failure. Nevertheless, I can confirm Applescript working:

```
$ osascript -e 'tell app "Finder" to display dialog "AppleScript works"'
button returned:OK
```
fires up the desired dialog in Finder.

**Comment by commitay** [comment]
Are you running these commands via SSH and/or on a multi-user machine?

**Comment by hoefling** [comment]
> Are you running these commands via SSH

Nope, no SSH, entering the commands on my Macbook in the terminal.

> and/or on a multi-user machine?

Indeed, I have a separate `admin` account for installing, maintenance and other admin stuff:
```
$ dscl . list /Users | grep -v '_'
admin
daemon
hoefling
nobody
root
```

**Comment by commitay** [comment]
We've had a previous report of this (https://github.com/caskroom/homebrew-cask/issues/27116) and it looks like multi-user was also an issue there.

Multi-user is also part of an open issue on AppleScript. https://github.com/caskroom/homebrew-cask/issues/19076

**Comment by commitay** [comment]
Closing in favour of https://github.com/caskroom/homebrew-cask/issues/19076
