### ISSUE TITLE
Cask doesn't follow redirects?

### ISSUE THREAD

**Issue by holms** [caskroom/homebrew-cask#43175]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Tried to create a cask and it fails (and I've did all the steps above)

```
cask 'mkvtoolnix' do
  version '20.0.0'
  sha256 'e3e80d9661be212f64c8581cd7dedebbba75bc99ba75453773cf1abfe13a37db'

  url 'https://mkvtoolnix.download/macos/MKVToolNix-20.0.0.dmg'
  name 'MKVToolNix'
  homepage 'https://mkvtoolnix.download'

  app 'MKVToolNix-20.0.0.app'
end
```

From output bellow you can clearly see that it doesn't follow redirects. I don't have ~/.curlrc, also I can download it with a CURL:

```
curl -O -J -L https://mkvtoolnix.download/macos/MKVToolNix-20.0.0.dmg
```

The sha256 hash which brew proposes of downloaded file is incorrect, also as file it self.

How can this be solved? 

#### Output of your command with `--verbose --debug`

```
Romans-iMac:~ holms$ brew cask --verbose --debug install mkvtoolnix
==> Hbc::Installer#install
==> Printing caveats
==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://mkvtoolnix.download/macos/MKVToolNix-20.0.0.dmg
Already downloaded: /Users/holms/Library/Caches/Homebrew/Cask/mkvtoolnix--20.0.0.dmg
==> Downloaded to -> /Users/holms/Library/Caches/Homebrew/Cask/mkvtoolnix--20.0.0.dmg
==> Verifying download
==> Determining which verifications to run for Cask mkvtoolnix
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask mkvtoolnix
==> SHA256 checksums match
==> Installing Cask mkvtoolnix
==> Hbc::Installer#stage
==> Extracting primary container
==> Determining which containers to use based on filetype
==> Checking container class Hbc::Container::Pkg
==> Checking container class Hbc::Container::Ttf
==> Checking container class Hbc::Container::Otf
==> Checking container class Hbc::Container::Air
==> Checking container class Hbc::Container::Cab
==> Checking container class Hbc::Container::Dmg
==> Executing: ["/usr/bin/hdiutil", "imageinfo", "/Users/holms/Library/Caches/Homebrew/Cask/mkvtoolnix--20.0.0.dmg"]
==> Checking container class Hbc::Container::SevenZip
==> Checking container class Hbc::Container::Sit
==> Checking container class Hbc::Container::Rar
==> Checking container class Hbc::Container::Zip
==> Checking container class Hbc::Container::Xar
==> Checking container class Hbc::Container::Tar
==> Checking container class Hbc::Container::Bzip2
==> Checking container class Hbc::Container::Gzip
==> Checking container class Hbc::Container::Lzma
==> Checking container class Hbc::Container::Xz
==> Checking container class Hbc::Container::Gpg
==> Checking container class Hbc::Container::Executable
==> Checking container class Hbc::Container::SvnRepository
==> Purging files for version 20.0.0 of Cask mkvtoolnix
Error: Uh oh, could not figure out how to unpack '/Users/holms/Library/Caches/Homebrew/Cask/mkvtoolnix--20.0.0.dmg'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:152:in `extract_primary_container'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:58:in `stage'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:79:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:20:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

#### Output of `brew cask doctor`

```
Romans-iMac:~ holms$ brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.5.2-3-g0f44937
caskroom/homebrew-cask (git revision 269cd; last commit 2018-01-25)
==> macOS
10.13.2
==> SIP
Enabled
==> Java
N/A
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (12 files, 806.6MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3899 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin17
/Library/Ruby/Site/2.3.0/universal-darwin17
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin17
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

**Comment by commitay** [comment]
```
$ brew cask install mkvtoolnix.rb
==> Satisfying dependencies
==> Downloading https://mkvtoolnix.download/macos/MKVToolNix-20.0.0.dmg
######################################################################## 100.0%
==> Verifying checksum for Cask mkvtoolnix
==> Note: running "brew update" may fix sha256 checksum errors
Error: Checksum for Cask 'mkvtoolnix' does not match.

Expected: e3e80d9661be212f64c8581cd7dedebbba75bc99ba75453773cf1abfe13a37db
Actual:   b80ddda826fb3cb9dd1addff3fb48308fc98a18037a276c76e42bbc1b9e8b4cb
File:     /Users/commitay/Library/Caches/Homebrew/Cask/mkvtoolnix--20.0.0.dmg

To retry an incomplete download, remove the file above.
```
Changed `sha256`:
```
$ brew cask install mkvtoolnix.rb
==> Satisfying dependencies
==> Downloading https://mkvtoolnix.download/macos/MKVToolNix-20.0.0.dmg
Already downloaded: /Users/commitay/Library/Caches/Homebrew/Cask/mkvtoolnix--20.0.0.dmg
==> Verifying checksum for Cask mkvtoolnix
==> Installing Cask mkvtoolnix
==> Moving App 'MKVToolNix-20.0.0.app' to '/Applications/MKVToolNix-20.0.0.app'.
🍺  mkvtoolnix was successfully installed!
```

**Comment by holms** [comment]
Thanks for validating this, although I have no idea what's happens on my side sadly.
