### ISSUE TITLE
Fail cask uninstall/remove with --force

### ISSUE THREAD

**Issue by n00d1e5** [caskroom/homebrew-cask#43610]
#### Description of issue

This happened with uninstall bartender.

I wanna easily update my applications with brew, but for bartender, the update always comes much later.

Even I update it manually, brew will roll back to the least version in brew, that's why I do the UNINSTALL, I wanna remove bartender from the brew cask ls.

But the failure came with: `brew cask --force --verbose --debug uninstall bartender`

#### Output of your command with `--verbose --debug`

```
==> Uninstalling Cask bartender
==> Uninstalling Cask bartender
==> Un-installing artifacts
==> 3 artifact/s defined
#<SortedSet:0x0000010382f420>
==> Un-installing artifact of class Hbc::Artifact::Uninstall
==> Running uninstall process for bartender; your password may be necessary
==> Removing launchctl service com.surteesstudios.Bartender.BartenderInstallHelper
==> Executing: ["/bin/launchctl", "list", "com.surteesstudios.Bartender.BartenderInstallHelper"]
==> Executing: ["/usr/bin/sudo", "-E", "--", "/bin/launchctl", "list", "com.surteesstudios.Bartender.BartenderInstallHelper"]
==> Quitting application ID com.surteesstudios.Bartender
==> Executing: ["/bin/launchctl", "list"]
==> Removing login item Bartender 3
==> Executing: ["/usr/bin/osascript", "-e", "tell application \"System Events\" to delete every login item whose name is \"Bartender 3\""]
==> Removing files:
/Library/Audio/Plug-Ins/HAL/BartenderAudioPlugIn.plugin
==> Executing: ["/usr/bin/sudo", "-E", "--", "/usr/bin/xargs", "-0", "--", "/bin/rm", "-r", "-f", "--"]
/Library/PrivilegedHelperTools/com.surteesstudios.Bartender.BartenderInstallHelper
==> Executing: ["/usr/bin/sudo", "-E", "--", "/usr/bin/xargs", "-0", "--", "/bin/rm", "-r", "-f", "--"]
/Library/ScriptingAdditions/BartenderHelper.osax
==> Executing: ["/usr/bin/sudo", "-E", "--", "/usr/bin/xargs", "-0", "--", "/bin/rm", "-r", "-f", "--"]
/System/Library/ScriptingAdditions/BartenderSystemHelper.osax
==> Executing: ["/usr/bin/sudo", "-E", "--", "/usr/bin/xargs", "-0", "--", "/bin/rm", "-r", "-f", "--"]
==> rm: /System/Library/ScriptingAdditions/BartenderSystemHelper.osax/Contents/_CodeSignature/CodeResources: Operation not permitted
==> rm: /System/Library/ScriptingAdditions/BartenderSystemHelper.osax/Contents/_CodeSignature: Operation not permitted
==> rm: /System/Library/ScriptingAdditions/BartenderSystemHelper.osax/Contents/Info.plist: Operation not permitted
==> rm: /System/Library/ScriptingAdditions/BartenderSystemHelper.osax/Contents/MacOS/BartenderSystemHelper: Operation not permitted
==> rm: /System/Library/ScriptingAdditions/BartenderSystemHelper.osax/Contents/MacOS: Operation not permitted
==> rm: /System/Library/ScriptingAdditions/BartenderSystemHelper.osax/Contents/PlugIns/BartenderHelperTwoOneThree.bundle/Contents/_CodeSignature/CodeResources: Operation not permitted
==> rm: /System/Library/ScriptingAdditions/BartenderSystemHelper.osax/Contents/PlugIns/BartenderHelperTwoOneThree.bundle/Contents/_CodeSignature: Operation not permitted
==> rm: /System/Library/ScriptingAdditions/BartenderSystemHelper.osax/Contents/PlugIns/BartenderHelperTwoOneThree.bundle/Contents/Info.plist: Operation not permitted
==> rm: /System/Library/ScriptingAdditions/BartenderSystemHelper.osax/Contents/PlugIns/BartenderHelperTwoOneThree.bundle/Contents/MacOS/BartenderHelperTwoOneThree: Operation not permitted
==> rm: /System/Library/ScriptingAdditions/BartenderSystemHelper.osax/Contents/PlugIns/BartenderHelperTwoOneThree.bundle/Contents/MacOS: Operation not permitted
==> rm: /System/Library/ScriptingAdditions/BartenderSystemHelper.osax/Contents/PlugIns/BartenderHelperTwoOneThree.bundle/Contents: Operation not permitted
==> rm: /System/Library/ScriptingAdditions/BartenderSystemHelper.osax/Contents/PlugIns/BartenderHelperTwoOneThree.bundle: Operation not permitted
==> rm: /System/Library/ScriptingAdditions/BartenderSystemHelper.osax/Contents/PlugIns: Operation not permitted
==> rm: /System/Library/ScriptingAdditions/BartenderSystemHelper.osax/Contents/Resources/BartenderHelper.sdef: Operation not permitted
==> rm: /System/Library/ScriptingAdditions/BartenderSystemHelper.osax/Contents/Resources/BartenderHelperTwoOneThree.bundle/Contents/_CodeSignature/CodeResources: Operation not permitted
==> rm: /System/Library/ScriptingAdditions/BartenderSystemHelper.osax/Contents/Resources/BartenderHelperTwoOneThree.bundle/Contents/_CodeSignature: Operation not permitted
==> rm: /System/Library/ScriptingAdditions/BartenderSystemHelper.osax/Contents/Resources/BartenderHelperTwoOneThree.bundle/Contents/Info.plist: Operation not permitted
==> rm: /System/Library/ScriptingAdditions/BartenderSystemHelper.osax/Contents/Resources/BartenderHelperTwoOneThree.bundle/Contents/MacOS/BartenderHelperTwoOneThree: Operation not permitted
==> rm: /System/Library/ScriptingAdditions/BartenderSystemHelper.osax/Contents/Resources/BartenderHelperTwoOneThree.bundle/Contents/MacOS: Operation not permitted
==> rm: /System/Library/ScriptingAdditions/BartenderSystemHelper.osax/Contents/Resources/BartenderHelperTwoOneThree.bundle/Contents: Operation not permitted
==> rm: /System/Library/ScriptingAdditions/BartenderSystemHelper.osax/Contents/Resources/BartenderHelperTwoOneThree.bundle: Operation not permitted
==> rm: /System/Library/ScriptingAdditions/BartenderSystemHelper.osax/Contents/Resources/BartenderSystemHelper-Info.plist: Operation not permitted
==> rm: /System/Library/ScriptingAdditions/BartenderSystemHelper.osax/Contents/Resources/BartenderSystemHelper.sdef: Operation not permitted
==> rm: /System/Library/ScriptingAdditions/BartenderSystemHelper.osax/Contents/Resources: Operation not permitted
==> rm: /System/Library/ScriptingAdditions/BartenderSystemHelper.osax/Contents: Operation not permitted
==> rm: /System/Library/ScriptingAdditions/BartenderSystemHelper.osax: Operation not permitted
Error: Command failed to execute!

==> Failed command:
/usr/bin/sudo -E -- /usr/bin/xargs -0 -- /bin/rm -r -f --

==> Standard Output of failed command:


==> Standard Error of failed command:
rm: /System/Library/ScriptingAdditions/BartenderSystemHelper.osax/Contents/_CodeSignature/CodeResources: Operation not permitted
rm: /System/Library/ScriptingAdditions/BartenderSystemHelper.osax/Contents/_CodeSignature: Operation not permitted
rm: /System/Library/ScriptingAdditions/BartenderSystemHelper.osax/Contents/Info.plist: Operation not permitted
rm: /System/Library/ScriptingAdditions/BartenderSystemHelper.osax/Contents/MacOS/BartenderSystemHelper: Operation not permitted
rm: /System/Library/ScriptingAdditions/BartenderSystemHelper.osax/Contents/MacOS: Operation not permitted
rm: /System/Library/ScriptingAdditions/BartenderSystemHelper.osax/Contents/PlugIns/BartenderHelperTwoOneThree.bundle/Contents/_CodeSignature/CodeResources: Operation not permitted
rm: /System/Library/ScriptingAdditions/BartenderSystemHelper.osax/Contents/PlugIns/BartenderHelperTwoOneThree.bundle/Contents/_CodeSignature: Operation not permitted
rm: /System/Library/ScriptingAdditions/BartenderSystemHelper.osax/Contents/PlugIns/BartenderHelperTwoOneThree.bundle/Contents/Info.plist: Operation not permitted
rm: /System/Library/ScriptingAdditions/BartenderSystemHelper.osax/Contents/PlugIns/BartenderHelperTwoOneThree.bundle/Contents/MacOS/BartenderHelperTwoOneThree: Operation not permitted
rm: /System/Library/ScriptingAdditions/BartenderSystemHelper.osax/Contents/PlugIns/BartenderHelperTwoOneThree.bundle/Contents/MacOS: Operation not permitted
rm: /System/Library/ScriptingAdditions/BartenderSystemHelper.osax/Contents/PlugIns/BartenderHelperTwoOneThree.bundle/Contents: Operation not permitted
rm: /System/Library/ScriptingAdditions/BartenderSystemHelper.osax/Contents/PlugIns/BartenderHelperTwoOneThree.bundle: Operation not permitted
rm: /System/Library/ScriptingAdditions/BartenderSystemHelper.osax/Contents/PlugIns: Operation not permitted
rm: /System/Library/ScriptingAdditions/BartenderSystemHelper.osax/Contents/Resources/BartenderHelper.sdef: Operation not permitted
rm: /System/Library/ScriptingAdditions/BartenderSystemHelper.osax/Contents/Resources/BartenderHelperTwoOneThree.bundle/Contents/_CodeSignature/CodeResources: Operation not permitted
rm: /System/Library/ScriptingAdditions/BartenderSystemHelper.osax/Contents/Resources/BartenderHelperTwoOneThree.bundle/Contents/_CodeSignature: Operation not permitted
rm: /System/Library/ScriptingAdditions/BartenderSystemHelper.osax/Contents/Resources/BartenderHelperTwoOneThree.bundle/Contents/Info.plist: Operation not permitted
rm: /System/Library/ScriptingAdditions/BartenderSystemHelper.osax/Contents/Resources/BartenderHelperTwoOneThree.bundle/Contents/MacOS/BartenderHelperTwoOneThree: Operation not permitted
rm: /System/Library/ScriptingAdditions/BartenderSystemHelper.osax/Contents/Resources/BartenderHelperTwoOneThree.bundle/Contents/MacOS: Operation not permitted
rm: /System/Library/ScriptingAdditions/BartenderSystemHelper.osax/Contents/Resources/BartenderHelperTwoOneThree.bundle/Contents: Operation not permitted
rm: /System/Library/ScriptingAdditions/BartenderSystemHelper.osax/Contents/Resources/BartenderHelperTwoOneThree.bundle: Operation not permitted
rm: /System/Library/ScriptingAdditions/BartenderSystemHelper.osax/Contents/Resources/BartenderSystemHelper-Info.plist: Operation not permitted
rm: /System/Library/ScriptingAdditions/BartenderSystemHelper.osax/Contents/Resources/BartenderSystemHelper.sdef: Operation not permitted
rm: /System/Library/ScriptingAdditions/BartenderSystemHelper.osax/Contents/Resources: Operation not permitted
rm: /System/Library/ScriptingAdditions/BartenderSystemHelper.osax/Contents: Operation not permitted
rm: /System/Library/ScriptingAdditions/BartenderSystemHelper.osax: Operation not permitted


==> Exit status of failed command:
#<Process::Status: pid 2825 exit 1>

/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:70:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:36:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:18:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb:247:in `block in uninstall_delete'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb:237:in `block in each_resolved_path'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb:222:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb:222:in `each_resolved_path'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb:245:in `uninstall_delete'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb:59:in `block in dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb:56:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb:56:in `dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall.rb:7:in `uninstall_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:403:in `block in uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:400:in `uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:353:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:22:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:12:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:12:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew-Cask Version
Homebrew-Cask 1.5.2
caskroom/homebrew-cask (git revision 54c1b; last commit 2018-02-03)
==> macOS
10.12.6
==> SIP
Enabled
==> Java
1.8.0_162, 1.8.0_40, 1.7.0_75
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3904 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (177 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/universal-darwin9.0
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/zsh"
```

**Comment by commitay** [comment]
> I wanna remove bartender from the brew cask ls

`rm -rf /usr/local/Caskroom/bartender`
