### ISSUE TITLE
mamp.rb certificate used to sign package not trusted

### ISSUE THREAD

**Issue by lead0r** [caskroom/homebrew-cask#43859]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

I recently committed a pull request on a wrong sha256 checksum for the current MAMP 4.4 package ( https://github.com/caskroom/homebrew-cask/commit/3835cff4973606935f0fb09254353e24d988eb3e ). The checksum was verified from the official website and the pull request merged. Now the checksum error I had before disappeared, but I get a "certificate used to sign package was not trusted" error.

#### Output of your command with `--verbose --debug`

```
==> Hbc::Installer#install
==> Printing caveats
==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://downloads.mamp.info/MAMP-PRO/releases/4.4/MAMP_MAMP_PRO_4.4.pkg
Already downloaded: /Users/xxxx/Library/Caches/Homebrew/Cask/mamp--4.4.pkg
==> Downloaded to -> /Users/xxxx/Library/Caches/Homebrew/Cask/mamp--4.4.pkg
==> Verifying download
==> Determining which verifications to run for Cask mamp
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask mamp
==> SHA256 checksums match
==> Installing Cask mamp
==> Hbc::Installer#stage
==> Extracting primary container
==> Determining which containers to use based on filetype
==> Checking container class Hbc::Container::Pkg
==> Using container class Hbc::Container::Pkg for /Users/xxxx/Library/Caches/Homebrew/Cask/mamp--4.4.pkg
==> Executing: ["/usr/bin/ditto", "--", "/Users/xxxx/Library/Caches/Homebrew/Cask/mamp--4.4.pkg", "/usr/local/Caskroom/mamp/4.4/MAMP_MAMP_PRO_4.4.pkg"]
==> Creating metadata directory /usr/local/Caskroom/mamp/.metadata/4.4/20180209212224.495.
==> Creating metadata subdirectory /usr/local/Caskroom/mamp/.metadata/4.4/20180209212224.495/Casks.
==> Installing artifacts
==> 3 artifact/s defined
#<SortedSet:0x007f957a2d1420>
==> Installing artifact of class Hbc::Artifact::Pkg
==> Running installer for mamp; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
==> Executing: ["/usr/bin/sudo", "-E", "--", "/usr/sbin/installer", "-pkg", "/usr/local/Caskroom/mamp/4.4/MAMP_MAMP_PRO_4.4.pkg", "-target", "/", "-verboseR"]
==> installer: Package name is MAMP & MAMP PRO 4.4
==> installer: Certificate used to sign package is not trusted. Use -allowUntrusted to override.
==> Purging files for version 4.4 of Cask mamp
Error: Command failed to execute!

==> Failed command:
/usr/bin/sudo -E -- /usr/sbin/installer -pkg /usr/local/Caskroom/mamp/4.4/MAMP_MAMP_PRO_4.4.pkg -target / -verboseR

==> Standard Output of failed command:
installer: Package name is MAMP & MAMP PRO 4.4
installer: Certificate used to sign package is not trusted. Use -allowUntrusted to override.


==> Standard Error of failed command:


==> Exit status of failed command:
#<Process::Status: pid 98677 exit 1>

/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:70:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:36:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:18:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/pkg.rb:53:in `block in run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/pkg.rb:59:in `with_choices_file'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/pkg.rb:51:in `run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/pkg.rb:32:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:174:in `block in install_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:166:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:80:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:20:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```
#### Output of `brew cask doctor`

```
==> Homebrew-Cask Version
Homebrew-Cask 1.5.3-6-g646d696
caskroom/homebrew-cask (git revision 0ce92; last commit 2018-02-10)
==> macOS
10.13.3
==> SIP
Enabled
==> Java
9.0.4, 1.8.0_121
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (24 files, 1.9GB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3909 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-drivers (141 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-eid (10 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-fonts (1159 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (178 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin17
/Library/Ruby/Site/2.3.0/universal-darwin17
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin17
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/zsh"
```

**Comment by commitay** [comment]
You will need to report this to upstream.

**Comment by daften** [comment]
Same issue. This is the third release in a row where there's something wrong with the package itself or the SHA ...

**Comment by lead0r** [comment]
I opened an issue on http://bugs.mamp.info/view.php?id=6132 but I am not sure if this will lead to anything. Any ideas?

**Comment by dpardes** [comment]
This new checksum is failing for me as well. If I manually check:
```
> openssl dgst -sha256 ~/Downloads/MAMP_MAMP_PRO_4.4.1.pkg 
SHA256(/Users/dpardes/Downloads/MAMP_MAMP_PRO_4.4.1.pkg)= 
5eab5e3bcca0e7c9641d4cf21c7ee4a5698fa0c2ed7980cdb6a728de7857084b
```

I think this should be reopened.

**Comment by lead0r** [comment]
On the day when 4.4.1 was published, I could install without any checksum error. Maybe they changed the file again?
