### ISSUE TITLE
brew cask reinstal: `Error: No such file or directory - brew`

### ISSUE THREAD

**Issue by ftc2** [caskroom/homebrew-cask#44270]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

failure with `brew cask reinstall`
`Error: No such file or directory - brew`

i've tested with two casks.
it works `coconutbattery` but fails with `virtualbox`
might just be some issue in the virtualbox cask, not sure.

i've tried at least the following things:

- `--force`
- `brew doctor`
- `brew update-reset && brew update`
- `cd $(brew --repo); git fetch; git reset --hard origin/master; brew update`

thanks for looking

#### Output of your command with `--verbose --debug`

```
$ brew cask reinstall virtualbox --verbose --debug                                                                                       
==> Hbc::Installer#reinstall
==> Hbc::Installer#install
==> Printing caveats
==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading http://download.virtualbox.org/virtualbox/5.2.6/VirtualBox-5.2.6-120293-OSX.dmg
Already downloaded: /Users/ftc2/Library/Caches/Homebrew/Cask/virtualbox--5.2.6-120293.dmg
==> Downloaded to -> /Users/ftc2/Library/Caches/Homebrew/Cask/virtualbox--5.2.6-120293.dmg
==> Verifying download
==> Determining which verifications to run for Cask virtualbox
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask virtualbox
==> SHA256 checksums match
==> Uninstalling Cask virtualbox
==> Un-installing artifacts
==> 4 artifact/s defined
#<SortedSet:0x00000102056768>
==> Un-installing artifact of class Hbc::Artifact::PreflightBlock
==> Executing: ["brew", "cask", "uninstall", "virtualbox-extension-pack"]
Error: No such file or directory - brew
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/open3.rb:199:in `spawn'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/open3.rb:199:in `popen_run'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/open3.rb:95:in `popen3'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:88:in `each_output_line'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:25:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:18:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/dsl/base.rb:14:in `system_command'
/usr/local/Caskroom/virtualbox/.metadata/5.2.0-118431/20171105181403.163/Casks/virtualbox.rb:15:in `block (2 levels) in load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_flight_block.rb:38:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_flight_block.rb:38:in `abstract_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_flight_block.rb:26:in `uninstall_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:403:in `block in uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:400:in `uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:353:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:115:in `uninstall_existing_cask'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:76:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:104:in `reinstall'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/reinstall.rb:10:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/reinstall.rb:5:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/reinstall.rb:5:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:179:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:179:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

#### Output of `brew cask doctor`

```
$ brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.5.4-88-g650d6db
caskroom/homebrew-cask (git revision 58514; last commit 2018-02-24)
==> macOS
10.12.6
==> SIP
Enabled
==> Java
N/A
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (16 files, 613.0MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3921 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-drivers (144 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-eid (10 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-fonts (1159 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (172 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/universal-darwin9.0
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/usr/local/bin/zsh"
```

**Comment by commitay** [comment]
`brew cask install --force virtualbox`

**Comment by ftc2** [comment]
thanks
please close issue (unless `reinstall` is expected to work here)

**Comment by commitay** [comment]
This was an `uninstall` issue with the old version of the Cask, it won't occur again.
