### ISSUE TITLE
Brew cask - Installing android-sdk fail with CheckSum check

### ISSUE THREAD

**Issue by Dhanielk** [caskroom/homebrew-cask#44340]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue
Tried to run:
$brew cask install android-sdk

It fails with error `Error: Checksum for Cask 'android-sdk' does not match.`. I've tried this couple of times also deleting downloaded file from caches.

Side note: brew doctor is without issue.

#### Output of your command with `--verbose --debug`

```
$ brew cask install --verbose --debug android-sdk
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
No changes to formulae.

==> Hbc::Installer#install
==> Printing caveats
==> Caveats
You can control android sdk packages via the sdkmanager command.
You may want to add to your profile:

  'export ANDROID_SDK_ROOT="/usr/local/share/android-sdk"'

android-sdk requires Java 8. You can install it with

  brew cask install caskroom/versions/java8

==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://dl.google.com/android/repository/sdk-tools-darwin-3859397.zip
/usr/bin/curl --show-error --user-agent Homebrew/1.5.4-88-g650d6db (Macintosh; Intel Mac OS X 10.12.6) curl/7.54.0 --fail --location --remote-time --continue-at - --output /Users/dhorky/Library/Caches/Homebrew/Cask/android-sdk--3859397.zip.incomplete https://dl.google.com/android/repository/sdk-tools-darwin-3859397.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 82.2M    0 82.2M    0     0  3922k      0 --:--:--  0:00:21 --:--:-- 4422k
==> Downloaded to -> /Users/dhorky/Library/Caches/Homebrew/Cask/android-sdk--3859397.zip
==> Verifying download
==> Determining which verifications to run for Cask android-sdk
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask android-sdk
==> Note: running "brew update" may fix sha256 checksum errors
Error: Checksum for Cask 'android-sdk' does not match.

Expected: 4a81754a760fce88cba74d69c364b05b31c53d57b26f9f82355c61d5fe4b9df9
Actual:   4317409cfb6c939f0272393b89ee0e9a7a0a9b187673aa6bd88eb4ff22961c78
File:     /Users/dhorky/Library/Caches/Homebrew/Cask/android-sdk--3859397.zip

To retry an incomplete download, remove the file above.

/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/verify/checksum.rb:42:in `verify_checksum'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/verify/checksum.rb:22:in `verify'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/verify.rb:21:in `block in all'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/verify.rb:19:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/verify.rb:19:in `all'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:138:in `verify'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:52:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:75:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:20:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

#### Output of `brew cask doctor`

```
$ brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.5.4-88-g650d6db
caskroom/homebrew-cask (git revision 72a1a; last commit 2018-02-26)
==> macOS
10.12.6
==> SIP
Enabled
==> Java
1.8.0_162
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (29 files, 2GB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3920 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (172 casks)
/usr/local/Homebrew/Library/Taps/pasonatquila/homebrew-salesforce (3 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/universal-darwin9.0
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

**Comment by commitay** [comment]
The current checksum is correct.
```
$ brew cask audit --download android-sdk
==> Downloading https://dl.google.com/android/repository/sdk-tools-darwin-385939
######################################################################## 100.0%
==> Verifying checksum for Cask android-sdk
audit for android-sdk: passed
```
If `brew cask cleanup && brew cask install android-sdk` doesn't work it's probably a network issue.

**Comment by Dhanielk** [comment]
Hi @commitay. Thanks for the input. Cleanup and install didn't help and I've tried it on various networks. Even on LTE using my phone. I'll try it at home once again and close this issue if that work.

Can I do anything else at the moment to test?

Thanks!

**Comment by commitay** [comment]
Just checked again and the current checksum is still correct.

**Comment by Dhanielk** [comment]
Hi @commitay. You were right. At home it went smoothly.

Thanks for help!

Log below:

```brew cask install android-sdk
==> Caveats
You can control android sdk packages via the sdkmanager command.
You may want to add to your profile:

  'export ANDROID_SDK_ROOT="/usr/local/share/android-sdk"'

android-sdk requires Java 8. You can install it with

  brew cask install caskroom/versions/java8

==> Satisfying dependencies
==> Downloading https://dl.google.com/android/repository/sdk-tools-darwin-385939
######################################################################## 100.0%
==> Verifying checksum for Cask android-sdk
==> Installing Cask android-sdk
==> Linking Binary 'android' to '/usr/local/bin/android'.
==> Linking Binary 'archquery' to '/usr/local/bin/archquery'.
==> Linking Binary 'avdmanager' to '/usr/local/bin/avdmanager'.
==> Linking Binary 'jobb' to '/usr/local/bin/jobb'.
==> Linking Binary 'lint' to '/usr/local/bin/lint'.
==> Linking Binary 'monkeyrunner' to '/usr/local/bin/monkeyrunner'.
==> Linking Binary 'screenshot2' to '/usr/local/bin/screenshot2'.
==> Linking Binary 'sdkmanager' to '/usr/local/bin/sdkmanager'.
==> Linking Binary 'uiautomatorviewer' to '/usr/local/bin/uiautomatorviewer'.
==> Linking Binary 'mksdcard' to '/usr/local/bin/mksdcard'.
==> Linking Binary 'monitor' to '/usr/local/bin/monitor'.
🍺  android-sdk was successfully installed!```
