### ISSUE TITLE
Kubernetes-cli fails with go1.10, requires go1.9.1 or greater.

### ISSUE THREAD

**Issue by blirp** [caskroom/homebrew-cask#44896]
#### General troubleshooting steps

- [ x ] I have retried my command with `--force` and the issue is still present.
- [ x ] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [ x ] None of the templates was appropriate for my issue, or I’m not sure.
- [ x ] I ran `brew update-reset && brew update` and retried my command.
- [ x ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [ x ] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Trying to install minikube gives:

Detected go version: go version go1.10 darwin/amd64.
Kubernetes requires go1.9.1 or greater.
Please install go1.9.1 or later.

Seems to be a rather simple string-based comparison instead of version-comparison. 

#### Output of your command with `--verbose --debug`

```
$ brew cask install minikube --verbose --debug
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (caskroom/cask).
No changes to formulae.

==> Determining which containers to use based on 'container :type'
==> Hbc::Installer#install
==> Printing caveats
==> Hbc::Installer#fetch
==> Satisfying dependencies
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/kubernetes-cli.rb
==> Installing Formula dependencies: kubernetes-cli
==> Installing kubernetes-cli
==> Cloning https://github.com/kubernetes/kubernetes.git
Updating /Users/martin/Library/Caches/Homebrew/kubernetes-cli--git
git config remote.origin.url https://github.com/kubernetes/kubernetes.git
git config remote.origin.fetch +refs/tags/v1.9.3:refs/tags/v1.9.3
==> Checking out tag v1.9.3
git checkout -f v1.9.3 --
HEAD is now at d2835416 Merge pull request #59385 from hzxuzhonghu/automated-cherry-pick-of-#58438-#58914-origin-release-1.9
git reset --hard v1.9.3
HEAD is now at d2835416 Merge pull request #59385 from hzxuzhonghu/automated-cherry-pick-of-#58438-#58914-origin-release-1.9
==> make generated_files

Detected go version: go version go1.10 darwin/amd64.
Kubernetes requires go1.9.1 or greater.
Please install go1.9.1 or later.

!!! [0315 22:27:43] Call tree:
!!! [0315 22:27:43]  1: ./hack/run-in-gopath.sh:30 kube::golang::setup_env(...)

Detected go version: go version go1.10 darwin/amd64.
Kubernetes requires go1.9.1 or greater.
Please install go1.9.1 or later.

!!! [0315 22:27:44] Call tree:
!!! [0315 22:27:44]  1: ./hack/run-in-gopath.sh:30 kube::golang::setup_env(...)

Detected go version: go version go1.10 darwin/amd64.
Kubernetes requires go1.9.1 or greater.
Please install go1.9.1 or later.

!!! [0315 22:27:44] Call tree:
!!! [0315 22:27:44]  1: ./hack/run-in-gopath.sh:30 kube::golang::setup_env(...)

Detected go version: go version go1.10 darwin/amd64.
Kubernetes requires go1.9.1 or greater.
Please install go1.9.1 or later.

!!! [0315 22:27:44] Call tree:
!!! [0315 22:27:44]  1: ./hack/run-in-gopath.sh:30 kube::golang::setup_env(...)

Detected go version: go version go1.10 darwin/amd64.
Kubernetes requires go1.9.1 or greater.
Please install go1.9.1 or later.

!!! [0315 22:28:06] Call tree:
!!! [0315 22:28:06]  1: ./hack/run-in-gopath.sh:30 kube::golang::setup_env(...)

Detected go version: go version go1.10 darwin/amd64.
Kubernetes requires go1.9.1 or greater.
Please install go1.9.1 or later.

!!! [0315 22:28:06] Call tree:
!!! [0315 22:28:06]  1: ./hack/run-in-gopath.sh:30 kube::golang::setup_env(...)

Detected go version: go version go1.10 darwin/amd64.
Kubernetes requires go1.9.1 or greater.
Please install go1.9.1 or later.

!!! [0315 22:28:07] Call tree:
!!! [0315 22:28:07]  1: ./hack/run-in-gopath.sh:30 kube::golang::setup_env(...)

Detected go version: go version go1.10 darwin/amd64.
Kubernetes requires go1.9.1 or greater.
Please install go1.9.1 or later.

!!! [0315 22:28:07] Call tree:
!!! [0315 22:28:07]  1: ./hack/run-in-gopath.sh:30 kube::golang::setup_env(...)

Detected go version: go version go1.10 darwin/amd64.
Kubernetes requires go1.9.1 or greater.
Please install go1.9.1 or later.

!!! [0315 22:28:07] Call tree:
!!! [0315 22:28:07]  1: /private/tmp/kubernetes-cli-20180315-19677-1kxr5fz/src/k8s.io/kubernetes/hack/lib/golang.sh:616 kube::golang::setup_env(...)
!!! [0315 22:28:07]  2: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
make[1]: *** [_output/bin/deepcopy-gen] Error 1
make: *** [generated_files] Error 2
Error: Failed executing: make generated_files
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/formula.rb:1792:in `block in system'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1730:in `open'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1730:in `system'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/kubernetes-cli.rb:27:in `block (2 levels) in install'
/usr/local/Homebrew/Library/Homebrew/extend/ENV/super.rb:267:in `deparallelize'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/kubernetes-cli.rb:27:in `block in install'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/fileutils.rb:128:in `chdir'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/fileutils.rb:128:in `cd'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/kubernetes-cli.rb:24:in `install'
/usr/local/Homebrew/Library/Homebrew/build.rb:138:in `block (2 levels) in install'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1095:in `block in brew'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1895:in `block (2 levels) in stage'
/usr/local/Homebrew/Library/Homebrew/utils.rb:554:in `with_env'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1894:in `block in stage'
/usr/local/Homebrew/Library/Homebrew/resource.rb:119:in `block in unpack'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `block in run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `chdir'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/resource.rb:114:in `unpack'
/usr/local/Homebrew/Library/Homebrew/resource.rb:92:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1872:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1090:in `brew'
/usr/local/Homebrew/Library/Homebrew/build.rb:109:in `block in install'
/usr/local/Homebrew/Library/Homebrew/utils.rb:554:in `with_env'
/usr/local/Homebrew/Library/Homebrew/build.rb:106:in `install'
/usr/local/Homebrew/Library/Homebrew/build.rb:187:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:179:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:179:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

#### Output of `brew cask doctor`

```
$ brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.5.10-22-gcb6828d
caskroom/homebrew-cask (git revision a47598; last commit 2018-03-16)
==> macOS
10.10.5
==> SIP
N/A
==> Java
1.8.0_102, 1.8.0_73, 1.8.0_71, 1.8.0_40, 1.7.0_80, 1.7.0_71
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (10 files, 879.9MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3932 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/universal-darwin9.0
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/usr/local/bin/bash"
```

**Comment by vitorgalvao** [comment]
That’s not on us and we can’t fix it. You’ll have to report that to the kubernetes developers.
