### ISSUE TITLE
dwarf-fortress fails to upgrade/reinstall: error about /tmp/dwarf-fortress-save not existing

### ISSUE THREAD

**Issue by me-and** [caskroom/homebrew-cask#44898]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

I have the dwarf-fortress cask installed. Running `brew upgrade` today appears to have picked up a new version of that cask and attempted to install it, but failed with an error about copying the save directory. The relevant error is clearly visible in the debug output below.

Running `brew upgrade` again appears to have no effect -- there's a zero return code and no output printed, I assume because it doesn't retry the previously failed cask upgrade -- but running `brew cask reinstall dwarf-fortress` does produce the same error.

I suspect the problem here is that I have the cask installed but have never actually run the program, and as a result the save directory doesn't exist. Assuming that's what's going on, I suspect the fix is to just test whether the directory exists before attempting to copy it around.

#### Output of your command with `--verbose --debug`

```
$ brew cask reinstall --force --verbose --debug dwarf-fortress
==> Hbc::Installer#reinstall
==> Hbc::Installer#install
==> Printing caveats
==> Caveats
During uninstall, your save data will be copied to /tmp/dwarf-fortress-save

==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading http://www.bay12games.com/dwarves/df_44_06_osx.tar.bz2
Already downloaded: /Users/adam/Library/Caches/Homebrew/Cask/dwarf-fortress--0.44.06.tar.bz2
==> Downloaded to -> /Users/adam/Library/Caches/Homebrew/Cask/dwarf-fortress--0.44.06.tar.bz2
==> Verifying download
==> Determining which verifications to run for Cask dwarf-fortress
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask dwarf-fortress
==> SHA256 checksums match
==> Uninstalling Cask dwarf-fortress
==> Un-installing artifacts
==> 4 artifact/s defined
#<SortedSet:0x00000102c4e548>
==> Un-installing artifact of class Hbc::Artifact::PreflightBlock
==> Un-installing artifact of class Hbc::Artifact::PreflightBlock
==> Executing: ["/bin/cp", "-rf", "/usr/local/Caskroom/dwarf-fortress/0.43.05/df_osx/data/save", "/tmp/dwarf-fortress-save/"]
==> cp: directory /tmp/dwarf-fortress-save does not exist
Error: Command failed to execute!

==> Failed command:
/bin/cp -rf /usr/local/Caskroom/dwarf-fortress/0.43.05/df_osx/data/save /tmp/dwarf-fortress-save/

==> Standard Output of failed command:


==> Standard Error of failed command:
cp: directory /tmp/dwarf-fortress-save does not exist


==> Exit status of failed command:
#<Process::Status: pid 68995 exit 1>

/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:71:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:36:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:18:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/dsl/base.rb:14:in `system_command'
/usr/local/Caskroom/dwarf-fortress/.metadata/0.43.05/20161127194750.004/Casks/dwarf-fortress.rb:38:in `block (2 levels) in load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_flight_block.rb:38:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_flight_block.rb:38:in `abstract_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_flight_block.rb:26:in `uninstall_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:403:in `block in uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:400:in `uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:353:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:115:in `uninstall_existing_cask'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:76:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:104:in `reinstall'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/reinstall.rb:10:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/reinstall.rb:5:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/reinstall.rb:5:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew-Cask Version
Homebrew-Cask 1.5.10-22-gcb6828d
caskroom/homebrew-cask (git revision 1b1fe; last commit 2018-03-16)
==> macOS
10.13.3
==> SIP
Enabled
==> Java
N/A
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (11 files, 2.4GB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3932 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (173 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/universal-darwin9.0
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/usr/local/bin/bash"
```

**Comment by commitay** [comment]
This is fixed in the current version of the Cask, `brew cask install --force dwarf-fortress` should work.

**Comment by me-and** [comment]
My problem was not with `install` but with `reinstall`. I've just run a successful `install --force`, though, and now re-running `reinstall` succeeds as well. It feels like there is a bug here, still, but now I don't have a means to reproduce it, I suspect there's not much more that can be done.

**Comment by commitay** [comment]
> My problem was not with `install` but with `reinstall`.

Yes, I realise that.

> It feels like there is a bug here, still

There was a bug in the previous version of the Cask.

There was two ways it could have been fixed:

1) Edit the saved copy of the Cask file in `/usr/local/Caskroom/dwarf-fortress/*/*/Casks/dwarf-fortress.rb` manually to apply the same fix that exists in the current version of the Cask.

2) Run `brew cask install --force` to overwrite the existing install.

**Comment by me-and** [comment]
Ah, okay, I think I'd misunderstood how casks work in this scenario; I'd expected the reinstallation of the new version of dwarf-fortress to use the latest version of `dwarf-fortress.rb`, but I think you're saying it uses the version from when I initially installed the cask.

**Comment by commitay** [comment]
Reinstall will install the latest version but it will run the uninstall of the old version first.

**Comment by me-and** [comment]
Ah! Yes, of course it does. That makes perfect sense. Thank you for the explanation!
