### ISSUE TITLE
Uninstalling karabiner-elements fails

### ISSUE THREAD

**Issue by joh-klein** [caskroom/homebrew-cask#46073]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Uninstalling karabiner-elements fails

#### Command that failed

```
brew cask reinstall karabiner-elements
```

#### Output of command with `--force --verbose --debug`

```
==> Hbc::Installer#reinstall
==> Hbc::Installer#install
==> Printing caveats
==> Caveats
To install and/or use karabiner-elements you may need to enable their kernel extension in

  System Preferences → Security & Privacy → General

For more information refer to vendor documentation or the Apple Technical Note:

  https://developer.apple.com/library/content/technotes/tn2459/_index.html

==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://pqrs.org/osx/karabiner/files/Karabiner-Elements-12.0.0.dmg
Already downloaded: /Users/jklein/Library/Caches/Homebrew/Cask/karabiner-elements--12.0.0.dmg
==> Downloaded to -> /Users/jklein/Library/Caches/Homebrew/Cask/karabiner-elements--12.0.0.dmg
==> Verifying download
==> Determining which verifications to run for Cask karabiner-elements
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask karabiner-elements
==> SHA256 checksums match
==> Uninstalling Cask karabiner-elements
==> Un-installing artifacts
==> 3 artifact/s defined
#<SortedSet:0x00000102942728>
==> Un-installing artifact of class Hbc::Artifact::Uninstall
==> Running uninstall process for karabiner-elements; your password may be necessary
==> Signalling 'TERM' to application ID 'org.pqrs.Karabiner-Elements'
==> Executing: ["/bin/launchctl", "list"]
==> Signalling 'TERM' to application ID 'karabiner_grabber'
==> Executing: ["/bin/launchctl", "list"]
==> Signalling 'TERM' to application ID 'karabiner_console_user_server'
==> Executing: ["/bin/launchctl", "list"]
==> Unloading kernel extension org.pqrs.driver.Karabiner.VirtualHIDDevice.v050000
==> Executing: ["/usr/bin/sudo", "-E", "--", "/usr/sbin/kextstat", "-l", "-b", "org.pqrs.driver.Karabiner.VirtualHIDDevice.v050000"]
==> Executing: ["/usr/bin/sudo", "-E", "--", "/sbin/kextunload", "-b", "org.pqrs.driver.Karabiner.VirtualHIDDevice.v050000"]
==> (kernel) Can't unload kext org.pqrs.driver.Karabiner.VirtualHIDDevice.v050000; classes have instances:
==> (kernel)     Kext org.pqrs.driver.Karabiner.VirtualHIDDevice.v050000 class org_pqrs_driver_Karabiner_VirtualHIDDevice_VirtualHIDKeyboard_v050000 has 1 instance.
==> (kernel)     Kext org.pqrs.driver.Karabiner.VirtualHIDDevice.v050000 class org_pqrs_driver_Karabiner_VirtualHIDDevice_VirtualHIDEventService_v050000 has 1 instance.
==> (kernel)     Kext org.pqrs.driver.Karabiner.VirtualHIDDevice.v050000 class org_pqrs_driver_Karabiner_VirtualHIDDevice_VirtualHIDRoot_UserClient_v050000 has 1 instance.
==> Failed to unload org.pqrs.driver.Karabiner.VirtualHIDDevice.v050000 - (libkern/kext) kext is in use or retained (cannot unload).
Error: Command failed to execute!

==> Failed command:
/usr/bin/sudo -E -- /sbin/kextunload -b org.pqrs.driver.Karabiner.VirtualHIDDevice.v050000

==> Standard Output of failed command:


==> Standard Error of failed command:
(kernel) Can't unload kext org.pqrs.driver.Karabiner.VirtualHIDDevice.v050000; classes have instances:
(kernel)     Kext org.pqrs.driver.Karabiner.VirtualHIDDevice.v050000 class org_pqrs_driver_Karabiner_VirtualHIDDevice_VirtualHIDKeyboard_v050000 has 1 instance.
(kernel)     Kext org.pqrs.driver.Karabiner.VirtualHIDDevice.v050000 class org_pqrs_driver_Karabiner_VirtualHIDDevice_VirtualHIDEventService_v050000 has 1 instance.
(kernel)     Kext org.pqrs.driver.Karabiner.VirtualHIDDevice.v050000 class org_pqrs_driver_Karabiner_VirtualHIDDevice_VirtualHIDRoot_UserClient_v050000 has 1 instance.
Failed to unload org.pqrs.driver.Karabiner.VirtualHIDDevice.v050000 - (libkern/kext) kext is in use or retained (cannot unload).


==> Exit status of failed command:
#<Process::Status: pid 98614 exit 3>

/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:71:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:36:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:18:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb:173:in `block in uninstall_kext'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb:169:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb:169:in `uninstall_kext'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb:58:in `block in dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb:55:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb:55:in `dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall.rb:7:in `uninstall_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:403:in `block in uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:400:in `uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:353:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:115:in `uninstall_existing_cask'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:76:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:104:in `reinstall'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/reinstall.rb:10:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/reinstall.rb:5:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/reinstall.rb:5:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:101:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:101:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew-Cask Version
Homebrew-Cask 1.6.1-18-g714bf51
caskroom/homebrew-cask (git revision f6561e; last commit 2018-04-18)
==> macOS
10.13.4
==> SIP
Enabled
==> Java
1.8.0_172
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (6 files, 540.4MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3958 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-drivers (143 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-fonts (1159 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (176 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/universal-darwin9.0
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/zsh"
```

#### Output of `brew tap`

```
caskroom/cask
caskroom/drivers
caskroom/fonts
caskroom/versions
homebrew/core
moul/moul
```

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/46075

`brew update && brew cask install --force karabiner-elements`

**Comment by joh-klein** [comment]
Works. Thanks!
