### ISSUE TITLE
Error in installing No-IP DUC

### ISSUE THREAD

**Issue by derwentx** [caskroom/homebrew-cask#46322]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [ ] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Install fails on no-ip-duc cask

#### Command that failed

```
brew cask install no-ip-duc
```

#### Output of command with `--force --verbose --debug`

```
==> Hbc::Installer#install
==> Printing caveats
==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://www.noip.com/client/mac/noip3.2.1.dmg
Already downloaded: /Users/derwent/Library/Caches/Homebrew/Cask/no-ip-duc--3.2.1.dmg
==> Downloaded to -> /Users/derwent/Library/Caches/Homebrew/Cask/no-ip-duc--3.2.1.dmg
==> Verifying download
==> Determining which verifications to run for Cask no-ip-duc
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask no-ip-duc
==> SHA256 checksums match
==> Installing Cask no-ip-duc
==> Hbc::Installer#stage
==> Extracting primary container
==> Determining which containers to use based on filetype
==> Checking container class Hbc::Container::Pkg
==> Checking container class Hbc::Container::Ttf
==> Checking container class Hbc::Container::Otf
==> Checking container class Hbc::Container::Air
==> Checking container class Hbc::Container::Cab
==> Checking container class Hbc::Container::Dmg
==> Executing: ["/usr/bin/hdiutil", "imageinfo", "/Users/derwent/Library/Caches/Homebrew/Cask/no-ip-duc--3.2.1.dmg"]
==> Using container class Hbc::Container::Dmg for /Users/derwent/Library/Caches/Homebrew/Cask/no-ip-duc--3.2.1.dmg
==> Executing: ["/usr/bin/hdiutil", "attach", "-plist", "-nobrowse", "-readonly", "-noidme", "-mountrandom", "/var/folders/sx/43gc_nmj43dcwbw15n3pwm440000gn/T/d20180425-87817-1h0h049", "/Users/derwent/Library/Caches/Homebrew/Cask/no-ip-duc--3.2.1.dmg"]
==> Executing: ["/usr/bin/hdiutil", "convert", "-quiet", "-format", "UDTO", "-o", "/var/folders/sx/43gc_nmj43dcwbw15n3pwm440000gn/T/d20180425-87817-1h0h049/no-ip-duc--3.2.1.cdr", "/Users/derwent/Library/Caches/Homebrew/Cask/no-ip-duc--3.2.1.dmg"]
==> Executing: ["/usr/bin/hdiutil", "attach", "-plist", "-nobrowse", "-readonly", "-noidme", "-mountrandom", "/var/folders/sx/43gc_nmj43dcwbw15n3pwm440000gn/T/d20180425-87817-1h0h049", "/var/folders/sx/43gc_nmj43dcwbw15n3pwm440000gn/T/d20180425-87817-1h0h049/no-ip-duc--3.2.1.cdr"]
==> Software License Agreement for '/Users/derwent/Library/Caches/Homebrew/Cask/no-ip-duc--3.2.1.dmg':
END-USER LICENSE AGREEMENT FOR No-IP Mac Dynamic Update Client

IMPORTANT PLEASE READ THE TERMS AND CONDITIONS OF THIS LICENSE
AGREEMENT CAREFULLY BEFORE CONTINUING WITH THIS PROGRAM INSTALL:
Vitalwerks Internet Solutions, LLC End-User License Agreement
("EULA") is a legal agreement between you (either an individual or
a single entity) and Vitalwerks Internet Solutions, LLC. for the
Vitalwerks Internet Solutions, LLC software product(s) identified
above which may include associated software components, media,
printed materials, and "online" or electronic documentation ("SOFTWARE
PRODUCT"). By installing, copying, or otherwise using the SOFTWARE
PRODUCT, you agree to be bound by the terms of this EULA. This
license agreement represents the entire agreement concerning the
program between you and Vitalwerks Internet Solutions, LLC, (referred
to as "licenser"), and it supersedes any prior proposal, representation,
or understanding between the parties. If you do not agree to the
terms of this EULA, do not install or use the SOFTWARE PRODUCT.

The SOFTWARE PRODUCT is protected by copyright laws and international
copyright treaties, as well as other intellectual property laws and
treaties. The SOFTWARE PRODUCT is licensed, not sold.

1. GRANT OF LICENSE.  The SOFTWARE PRODUCT is licensed as follows:
(a) Installation and Use.  Vitalwerks Internet Solutions, LLC grants
you the right to install and use copies of the SOFTWARE PRODUCT on
your computer running a validly licensed copy of the Mac OS X for
which the SOFTWARE PRODUCT was designed.  (b) Backup Copies.  You
may also make copies of the SOFTWARE PRODUCT as may be necessary
for backup and archival purposes.

2. DESCRIPTION OF OTHER RIGHTS AND LIMITATIONS.  (a) Maintenance
of Copyright Notices.  You must not remove or alter any copyright
notices on any and all copies of the SOFTWARE PRODUCT.  (b)
Distribution.  You may not distribute registered copies of the
SOFTWARE PRODUCT to third parties. Evaluation versions available
for download from Vitalwerks Internet Solutions, LLC's websites may
be freely distributed.  (c) Prohibition on Reverse Engineering,
Decompilation, and Disassembly.  You may not reverse engineer,
decompile, or disassemble the SOFTWARE PRODUCT, except and only to
the extent that such activity is expressly permitted by applicable
law notwithstanding this limitation.  (d) Rental.  You may not rent,
lease, or lend the SOFTWARE PRODUCT.  (e) Support Services.  Vitalwerks
Internet Solutions, LLC may provide you with support services related
to the SOFTWARE PRODUCT ("Support Services"). Any supplemental
software code provided to you as part of the Support Services shall
be considered part of the SOFTWARE PRODUCT and subject to the terms
and conditions of this EULA.  (f) Compliance with Applicable Laws.
You must comply with all applicable laws regarding use of the
SOFTWARE PRODUCT.

3. TERMINATION Without prejudice to any other rights, Vitalwerks
Internet Solutions, LLC may terminate this EULA if you fail to
comply with the terms and conditions of this EULA. In such event,
you must destroy all copies of the SOFTWARE PRODUCT in your possession.

4. COPYRIGHT All title, including but not limited to copyrights,
in and to the SOFTWARE PRODUCT and any copies thereof are owned by
Vitalwerks Internet Solutions, LLC or its suppliers. All title and
intellectual property rights in and to the content which may be
accessed through use of the SOFTWARE PRODUCT is the property of the
respective content owner and may be protected by applicable copyright
or other intellectual property laws and treaties. This EULA grants
you no rights to use such content. All rights not expressly granted
are reserved by Vitalwerks Internet Solutions, LLC.

5. NO WARRANTIES Vitalwerks Internet Solutions, LLC expressly
disclaims any warranty for the SOFTWARE PRODUCT. The SOFTWARE PRODUCT
is provided 'As Is' without any express or implied warranty of any
kind, including but not limited to any warranties of merchantability,
noninfringement, or fitness of a particular purpose. Vitalwerks
Internet Solutions, LLC does not warrant or assume responsibility
for the accuracy or completeness of any information, text, graphics,
links or other items contained within the SOFTWARE PRODUCT. Vitalwerks
Internet Solutions, LLC makes no warranties respecting any harm
that may be caused by the transmission of a computer virus, worm,
time bomb, logic bomb, or other such computer program. Vitalwerks
Internet Solutions, LLC further expressly disclaims any warranty
or representation to Authorized Users or to any third party.

6. LIMITATION OF LIABILITY In no event shall Vitalwerks Internet
Solutions, LLC be liable for any damages (including, without
limitation, lost profits, business interruption, or lost information)
rising out of 'Authorized Users' use of or inability to use the
SOFTWARE PRODUCT, even if Vitalwerks Internet Solutions, LLC has
been advised of the possibility of such damages. In no event will
Vitalwerks Internet Solutions, LLC be liable for loss of data or
for indirect, special, incidental, consequential (including lost
profit), or other damages based in contract, tort or otherwise.
Vitalwerks Internet Solutions, LLC shall have no liability with
respect to the content of the SOFTWARE PRODUCT or any part thereof,
including but not limited to errors or omissions contained therein,
libel, infringements of rights of publicity, privacy, trademark
rights, business interruption, personal injury, loss of privacy,
moral rights or the disclosure of confidential information.
==> Executing: ["/usr/bin/find", ".", "-print0"]
==> Executing: ["/usr/bin/mkbom", "-s", "-i", "/var/folders/sx/43gc_nmj43dcwbw15n3pwm440000gn/T/20180425-87817-18tvb59.list", "--", "/var/folders/sx/43gc_nmj43dcwbw15n3pwm440000gn/T/20180425-87817-nimtih.bom"]
==> /usr/bin/mkbom: illegal option -- s
==> Executing: ["/usr/sbin/diskutil", "eject", "/private/var/folders/sx/43gc_nmj43dcwbw15n3pwm440000gn/T/d20180425-87817-1h0h049/dmg.wK6HcL"]
==> Purging files for version 3.2.1 of Cask no-ip-duc
Error: Command failed to execute!

==> Failed command:
/usr/bin/mkbom -s -i /var/folders/sx/43gc_nmj43dcwbw15n3pwm440000gn/T/20180425-87817-18tvb59.list -- /var/folders/sx/43gc_nmj43dcwbw15n3pwm440000gn/T/20180425-87817-nimtih.bom

==> Standard Output of failed command:
Usage: mkbom [i] [-u uid] [-g gid] source target-bom-file

	-i	Treat source as a file in the format generated by ls4mkbom and lsbom
	-u	Force user ID to the specified value (incompatible with -i)
	-g	Force group ID to the specified value (incompatible with -i)


==> Standard Error of failed command:
/usr/bin/mkbom: illegal option -- s


==> Exit status of failed command:
#<Process::Status: pid 88373 exit 1>

/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:71:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:36:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:18:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/container/dmg.rb:93:in `block (2 levels) in extract_mount'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/tempfile.rb:295:in `open'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/container/dmg.rb:89:in `block in extract_mount'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/tempfile.rb:295:in `open'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/container/dmg.rb:86:in `extract_mount'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/container/dmg.rb:19:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/container/dmg.rb:19:in `block in extract'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/container/dmg.rb:55:in `block in mount'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/container/dmg.rb:30:in `mount'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/container/dmg.rb:16:in `extract'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:156:in `extract_primary_container'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:58:in `stage'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:79:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:20:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:101:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:101:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew-Cask Version
Homebrew-Cask 1.6.2-4-g5195e72
caskroom/homebrew-cask (git revision 20e1e; last commit 2018-04-25)
==> macOS
10.12.6
==> SIP
Disabled
==> Java
1.8.0_144
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (2 files, 55.7MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3954 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (176 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/universal-darwin9.0
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/zsh"
```

#### Output of `brew tap`

```
cartr/qt4
caskroom/cask
caskroom/versions
derwentx/sudolikeaboss
homebrew/core
homebrew/dupes
homebrew/fuse
homebrew/php
homebrew/services
```

#### Output of `ls -al /usr/bin/mkbom`
```
.rwxr-xr-x 72k root 17 Apr 17:50 /usr/bin/mkbom
```

**Comment by commitay** [comment]
`/usr/bin/mkbom: illegal option -- s`

This is a valid option on `10.12.6`

Can you try installing something else that uses a `dmg` e.g `google-chrome`, `firefox`, `opera`?

**Comment by derwentx** [comment]
Hi @commitay , thanks for the reply.

`brew cask uninstall opera`
```
==> Uninstalling Cask opera
==> Backing App 'Opera.app' up to '/usr/local/Caskroom/opera/46.0.2597.26/Opera.app'.
==> Removing App '/Applications/Opera.app'.
==> Purging files for version 46.0.2597.26 of Cask opera
```
`brew cask install opera`
```
==> Verifying checksum for Cask opera
==> Installing Cask opera
==> /usr/bin/mkbom: illegal option -- s
==> Purging files for version 52.0.2871.40 of Cask opera
Error: Command failed to execute!

==> Failed command:
/usr/bin/mkbom -s -i /var/folders/sx/43gc_nmj43dcwbw15n3pwm440000gn/T/20180425-90347-c08i63.list -- /var/folders/sx/43gc_nmj43dcwbw15n3pwm440000gn/T/20180425-90347-6chror.bom

==> Standard Output of failed command:
Usage: mkbom [i] [-u uid] [-g gid] source target-bom-file

	-i	Treat source as a file in the format generated by ls4mkbom and lsbom
	-u	Force user ID to the specified value (incompatible with -i)
	-g	Force group ID to the specified value (incompatible with -i)


==> Standard Error of failed command:
/usr/bin/mkbom: illegal option -- s


==> Exit status of failed command:
#<Process::Status: pid 90973 exit 1>
```
oh dear, looks like it's something wrong with my system.

I've been using brew for years and never had any trouble.

Any idea what I can do to try and fix this?

`brew doctor`
```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Users/derwent/.pyenv/shims/python-config
  /Users/derwent/.pyenv/shims/python2-config
  /Users/derwent/.pyenv/shims/python2.6-config
  /Users/derwent/.pyenv/shims/python2.7-config
  /Users/derwent/.pyenv/shims/python3-config
  /Users/derwent/.pyenv/shims/python3.2-config
  /Users/derwent/.pyenv/shims/python3.2m-config
  /Users/derwent/.pyenv/shims/python3.3-config
  /Users/derwent/.pyenv/shims/python3.3m-config
  /Users/derwent/.pyenv/shims/python3.4-config
  /Users/derwent/.pyenv/shims/python3.4m-config
  /Users/derwent/.pyenv/shims/python3.6-config
  /Users/derwent/.pyenv/shims/python3.6m-config
```

`history | grep brew | tail -n 50`
```
 9650  2018-04-17 18:03  env LDFLAGS="-L$(brew --prefix openssl)/lib" \\nCFLAGS="-I$(brew --prefix openssl)/include" \\nSWIG_FEATURES="-cpperraswarn -includeall -I$(brew --prefix openssl)/include" \\npip install m2crypto
 9815  2018-04-22 12:02  brew cask update musescore
 9816  2018-04-22 12:02  brew update musescore
 9826  2018-04-24 11:40  brew install radare2
 9841  2018-04-24 13:27  brew reinstall pygobject3 --with-libffi
 9844  2018-04-24 13:29  brew test pygobject3
 9845  2018-04-24 13:29  brew install pygobject3 --with-python3
 9846  2018-04-24 13:30  brew reinstall pygobject3 --with-python3 -with-libffi
 9848  2018-04-24 13:31  brew info pygobject3
 9849  2018-04-24 13:32  brew info gtk+3
 9869  2018-04-24 13:50  brew install qmake
 9872  2018-04-24 13:52  brew search qmake
 9873  2018-04-24 13:53  brew help qmake
 9874  2018-04-24 13:53  brew help search
 9875  2018-04-24 13:53  brew search --desc qmake
 9881  2018-04-24 14:05  brew help
 9882  2018-04-24 14:05  brew commands
 9883  2018-04-24 14:05  brew info radare
 9884  2018-04-24 14:05  brew info radare2
 9885  2018-04-24 14:05  brew reinstall radare2 --with-code-signing
 9886  2018-04-24 14:08  brew search cutter
 9887  2018-04-24 14:08  brew info cutter
 9900  2018-04-24 14:23  brew install gdbserver
 9901  2018-04-24 14:23  brew search gdbserver
 9977  2018-04-24 18:16  brew install snowman
 9987  2018-04-24 18:20  brew install cartr/qt4/qt
 9988  2018-04-24 18:21  brew install boost
10036  2018-04-25 10:40  brew search noip
10037  2018-04-25 10:40  brew search no-ip
10038  2018-04-25 10:40  brew cask install no-ip-duc
10041  2018-04-25 10:46  brew cask install no-ip-duc --force
10044  2018-04-25 10:48  brew update-reset && brew update
10045  2018-04-25 10:49  brew cask install no-ip-duc --force
10046  2018-04-25 10:50  brew doctor
10047  2018-04-25 10:50  brew link swig
10048  2018-04-25 10:50  brew link --overwrite swig
10049  2018-04-25 10:50  brew link python@2
10050  2018-04-25 10:50  brew doctor
10051  2018-04-25 10:51  brew install no-ip-doc --force --verbose --debug
10052  2018-04-25 10:52  brew cask install no-ip-doc --force --verbose --debug
10053  2018-04-25 10:52  brew cask install no-ip-duc --force --verbose --debug
10054  2018-04-25 10:53  brew cask doctor
10055  2018-04-25 10:53  brew tap
10060  2018-04-25 11:07  brew cask uninstall opera
10061  2018-04-25 11:07  brew cask install opera
10062  2018-04-25 11:09  brew doctor
10064  2018-04-25 11:10  brew doctor
10065  2018-04-25 11:11  history | grep brew | tail 20
10068  2018-04-25 11:11  history | grep brew | tail 20
10069  2018-04-25 11:12  history | grep brew | tail -n 20
```

**Comment by derwentx** [comment]
Thanks @commitay 
I'll put some information in here for anyone who googles this problem since there wasn't much out there when I tried.

As far as i can tell it looks like the normal macOS mkbom binary has been replaced with [this mkbom](https://github.com/hogliux/bomutils) on 2018-04-17

`for i in $(echo $PATH | sed 's/:/\n/g' | sort | uniq); do; echo "=> $i"; find $i -type f -name mkbom -exec ls -al {} \; 2>/dev/null; done`
```
=> /Applications/Wireshark.app/Contents/MacOS
=> /Users/derwent/.local/bin
=> /Users/derwent/.pyenv
=> /Users/derwent/.pyenv/shims
=> /Users/derwent/.rbenv/shims
=> /Users/derwent/.vim/bin
=> /Users/derwent/Library/Android/sdk/platform-tools
=> /Users/derwent/esp/xtensa-esp32-elf/bin
=> /bin
=> /opt/X11/bin
=> /opt/gnu/bin
=> /opt/gnu/sbin
=> /opt/local/bin
=> /opt/local/sbin
=> /sbin
=> /usr/bin
-rwxr-xr-x  1 root  wheel  72724 17 Apr 17:50 /usr/bin/mkbom
=> /usr/local/Cellar/pyenv-virtualenv/1.1.1/shims
=> /usr/local/bin
-rwxr-xr-x  1 root  admin  72724 17 Apr 18:04 /usr/local/bin/mkbom
=> /usr/local/opt/php@5.6/bin
=> /usr/local/sbin
=> /usr/sbin
``` 

both of these mkboms are the hogliux versions.

This happened around the time I installed empire, and sure enough, `cat ~/GitHub/Empire/setup/install.sh | grep mkbom -n -C 5`

```
172-
173-# NIT: This fails on OSX. Leaving it only on Linux instances.
174-if uname | grep -q "Linux"; then
175-        (cd bomutils && make install)
176-fi
177:chmod 755 bomutils/build/bin/mkbom && sudo cp bomutils/build/bin/mkbom /usr/local/bin/.
178-
179-# set up the database schema
180-python ./setup_database.py
181-
182-# generate a cert
```

I'll follow up with [Empire](https://github.com/EmpireProject/Empire) .

**Comment by derwentx** [comment]
restoring `/usr/bin/mkbom` from a backup and removing `mkbom` from `/usr/local/bin` fixes this.
