### ISSUE TITLE
`brew cask upgrade` fails when cache directory is missing

### ISSUE THREAD

**Issue by jjeising** [caskroom/homebrew-cask#46403]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

`brew cask upgrade` fails downloading if `~Library/Caches/Homebrew/Cask` is missing. After manually creating the `Cask` folder it works fine again.

`brew doctor` or `--force` did not create the folder. It should be created before starting to download packages.

#### Command that failed

```
$ brew cask upgrade
==> Upgrading 11 outdated packages, with result:
…
==> Satisfying dependencies
==> Downloading …
Warning: Failed to create the file
Warning: ~/Library/Caches/Homebrew/Cask/….incomp
Warning: lete: No such file or directory

curl: (23) Failed writing body (0 != 16084)
==> Purging files for version … of Cask …
Error: Download failed on Cask '…' with message: Download failed: …
```

#### Output of command with `--force --verbose --debug`

```
==> Upgrading 11 outdated packages, with result:
…
==> Started upgrade process for Cask …
==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading …
/usr/bin/curl -q --show-error --user-agent Homebrew/1.6.2-33-g27ec9da (Macintosh; Intel Mac OS X 10.13.4) curl/7.54.0 --fail --location --remote-time --continue-at - --output ~/Library/Caches/Homebrew/Cask/….incomplete https://…
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to create the file
Warning: ~/Library/Caches/Homebrew/Cask/….incomp
Warning: lete: No such file or directory
  0 23.7M    0 16084    0     0  62688      0  0:06:37 --:--:--  0:06:37 62828
curl: (23) Failed writing body (0 != 16084)
==> Purging files for version … of Cask …
Error: Download failed on Cask '…' with message: Download failed: …
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/download.rb:42:in `rescue in fetch'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/download.rb:40:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/download.rb:15:in `perform'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:126:in `download'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:51:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/upgrade.rb:56:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/upgrade.rb:29:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/upgrade.rb:29:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:101:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:101:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew-Cask Version
Homebrew-Cask 1.6.2-33-g27ec9da
caskroom/homebrew-cask (git revision 85020; last commit 2018-04-26)
==> macOS
10.13.4
==> SIP
Enabled
==> Java
10.0.1
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3956 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-drivers (143 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-fonts (1160 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (176 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-eid (11 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/universal-darwin9.0
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

#### Output of `brew tap`

```
caskroom/cask
caskroom/drivers
caskroom/eid
caskroom/fonts
caskroom/versions
…
homebrew/bundle
homebrew/core
homebrew/dupes
homebrew/gui
homebrew/services
homebrew/versions
…
```

**Comment by commitay** [comment]
Please post `brew cask doctor`

**Comment by jjeising** [comment]
> Please post brew cask doctor

Sorry, missed that. Fixed above.

**Comment by commitay** [comment]
Reproducible. Only occurs with `upgrade`, not `fetch`, `install` or `reinstall`.

**Comment by jjeising** [comment]
I didn't manually delete the directory. I tried reproducing this `brew [cask] cleanup [-s]` but the directory did not disappear. So I'm not sure. I think this has happened before, but as `[re]install` seems to restore it the issue might have been not immediately visible for me.

**Comment by saagarjha** [comment]
I'm seeing this issue as well. For some reason Travis CI seems to not have a cache folder for Homebrew Cask, which causes all `brew upgrade`s to fail.
