### ISSUE TITLE
VirtualBox Package 5.2.10,122088 Not Installing Due to Oracle Developer Being Blocked by OS

### ISSUE THREAD

**Issue by rcuza** [caskroom/homebrew-cask#46435]
There is an error with a dependency for the virtualbox cask and OS X 10.13.4 download installer security. This issue request is for a more robust error message.

#### Description of issue

When running the virtualbox cask, I get a generic error: `The install failed (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.)`

After investigation, on my Mac, the installer package is failing to install because the developer "Oracle America, Inc." is blocked. This failure is not due to homebrew.

Request: As a user of homebrew, it would be helpful if the error could be specific about failures due to security permissions missing. When sudo is needed, `brew` will prompt for a password. If permission can be given to allow a package to be installed from the command line, that would be ideal. Otherwise, it would be great if the "Security & Privacy" panel was opened when doing interactive runs.

#### Command that failed

```
brew cask install virtualbox
```

#### Output of command with `--force --verbose --debug`

```
$ brew cask install virtualbox --force --debug --verbose
==> Hbc::Installer#install
==> Printing caveats
==> Caveats
To install and/or use virtualbox you may need to enable their kernel extension in

  System Preferences → Security & Privacy → General

For more information refer to vendor documentation or the Apple Technical Note:

  https://developer.apple.com/library/content/technotes/tn2459/_index.html

==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://download.virtualbox.org/virtualbox/5.2.10/VirtualBox-5.2.10-122088-OSX.dmg
Already downloaded: /Users/rcuza/Library/Caches/Homebrew/Cask/virtualbox--5.2.10,122088.dmg
==> Downloaded to -> /Users/rcuza/Library/Caches/Homebrew/Cask/virtualbox--5.2.10,122088.dmg
==> Verifying download
==> Determining which verifications to run for Cask virtualbox
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask virtualbox
==> SHA256 checksums match
==> Installing Cask virtualbox
==> Hbc::Installer#stage
==> Extracting primary container
==> Determining which containers to use based on filetype
==> Checking container class Hbc::Container::Pkg
==> Checking container class Hbc::Container::Ttf
==> Checking container class Hbc::Container::Otf
==> Checking container class Hbc::Container::Air
==> Checking container class Hbc::Container::Cab
==> Checking container class Hbc::Container::Dmg
==> Executing: ["/usr/bin/hdiutil", "imageinfo", "/Users/rcuza/Library/Caches/Homebrew/Cask/virtualbox--5.2.10,122088.dmg"]
==> Using container class Hbc::Container::Dmg for /Users/rcuza/Library/Caches/Homebrew/Cask/virtualbox--5.2.10,122088.dmg
==> Executing: ["/usr/bin/hdiutil", "attach", "-plist", "-nobrowse", "-readonly", "-noidme", "-mountrandom", "/var/folders/bz/n64vbppn0rq4ck9njbgq70dw52f4fj/T/d20180427-29994-8mrgog", "/Users/rcuza/Library/Caches/Homebrew/Cask/virtualbox--5.2.10,122088.dmg"]
==> Executing: ["/usr/bin/find", ".", "-print0"]
==> Executing: ["/usr/bin/mkbom", "-s", "-i", "/var/folders/bz/n64vbppn0rq4ck9njbgq70dw52f4fj/T/20180427-29994-1umq80s.list", "--", "/var/folders/bz/n64vbppn0rq4ck9njbgq70dw52f4fj/T/20180427-29994-1k5qvha.bom"]
==> Executing: ["/usr/bin/ditto", "--bom", "/var/folders/bz/n64vbppn0rq4ck9njbgq70dw52f4fj/T/20180427-29994-1k5qvha.bom", "--", "/private/var/folders/bz/n64vbppn0rq4ck9njbgq70dw52f4fj/T/d20180427-29994-8mrgog/dmg.qNCycT", "/usr/local/Caskroom/virtualbox/5.2.10,122088"]
==> Executing: ["/usr/sbin/diskutil", "eject", "/private/var/folders/bz/n64vbppn0rq4ck9njbgq70dw52f4fj/T/d20180427-29994-8mrgog/dmg.qNCycT"]
==> Creating metadata directory /usr/local/Caskroom/virtualbox/.metadata/5.2.10,122088/20180427131354.586.
==> Creating metadata subdirectory /usr/local/Caskroom/virtualbox/.metadata/5.2.10,122088/20180427131354.586/Casks.
==> Installing artifacts
==> 3 artifact/s defined
#<SortedSet:0x007fc4dfeae358>
==> Installing artifact of class Hbc::Artifact::Pkg
==> Running installer for virtualbox; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
==> Executing: ["/usr/bin/sudo", "-E", "--", "/usr/sbin/installer", "-pkg", "/usr/local/Caskroom/virtualbox/5.2.10,122088/VirtualBox.pkg", "-target", "/", "-verboseR"]
==> installer: Package name is Oracle VM VirtualBox
==> installer: Installing at base path /
==> installer:PHASE:Preparing for installation…
==> installer:PHASE:Preparing the disk…
==> installer:PHASE:Preparing Oracle VM VirtualBox…
==> installer:PHASE:Waiting for other installations to complete…
==> installer:PHASE:Configuring the installation…
==> installer:STATUS:
==> installer:%14.182657
==> installer:PHASE:Writing files…
==> installer:%64.851152
==> installer:PHASE:Moving items into place…
==> installer:PHASE:Validating packages…
==> installer:%97.750000
==> installer: The install failed (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.)
==> Purging files for version 5.2.10,122088 of Cask virtualbox
Error: Command failed to execute!

==> Failed command:
/usr/bin/sudo -E -- /usr/sbin/installer -pkg /usr/local/Caskroom/virtualbox/5.2.10,122088/VirtualBox.pkg -target / -verboseR

==> Standard Output of failed command:
installer: Package name is Oracle VM VirtualBox
installer: Installing at base path /
installer:PHASE:Preparing for installation…
installer:PHASE:Preparing the disk…
installer:PHASE:Preparing Oracle VM VirtualBox…
installer:PHASE:Waiting for other installations to complete…
installer:PHASE:Configuring the installation…
installer:STATUS:
installer:%14.182657
installer:PHASE:Writing files…
installer:%64.851152
installer:PHASE:Moving items into place…
installer:PHASE:Validating packages…
installer:%97.750000
installer: The install failed (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.)


==> Standard Error of failed command:


==> Exit status of failed command:
#<Process::Status: pid 30472 exit 1>

/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:71:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:36:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:18:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/pkg.rb:53:in `block in run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/pkg.rb:59:in `with_choices_file'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/pkg.rb:51:in `run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/pkg.rb:32:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:174:in `block in install_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:166:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:80:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:20:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:101:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:101:in `<main>'
```

#### Output of `brew cask doctor`

```
 brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.6.2
caskroom/homebrew-cask (git revision e9611; last commit 2018-04-27)
==> macOS
10.13.4
==> SIP
Enabled
==> Java
N/A
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (36 files, 5.2GB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3957 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin17
/Library/Ruby/Site/2.3.0/universal-darwin17
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin17
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

#### Output of `brew tap`

```
$ brew tap
caskroom/cask
homebrew/core
wallix/awless
```

**Comment by commitay** [comment]
>  it would be helpful if the error could be specific about failures due to security permissions missing. 

The error itself isn't specific to kext permissions. Any failures during a `pkg` install will produce a similar error.

> If permission can be given to allow a package to be installed from the command line, that would be ideal.

It cannot be approved via CLI.

> Otherwise, it would be great if the "Security & Privacy" panel was opened when doing interactive runs.

macOS already prompts the user to open the "Security & Privacy" panel during install.

![kext](https://user-images.githubusercontent.com/26216252/39365277-04bf0804-4a74-11e8-80fc-fe93bf9433cc.png)

**Comment by rcuza** [comment]
I do not get the "System Extension Blocked" pop up when I troubleshoot this.

I will reluctantly assume a layer 8 error here. Sorry for the bother.

For others with a similar problem, installing an older version (v5.2.8) did not help. (ref: https://devforgalaxy.github.io/en/2016/11/05/use-homebrew-cask-to-downgrad-or-install-en.html )

**Comment by vitorgalvao** [comment]
> https://devforgalaxy.github.io/en/2016/11/05/use-homebrew-cask-to-downgrad-or-install-en.html

I would advise absolutely no one to follow that approach.

> installing an older version (v5.2.8) did not help

Because this blocking is related to your macOS version, not your VirtualBox version.

**Comment by christophrumpel** [comment]
@commitay Hey, do you meant that it should be possible to allow it through the GUI and then the script should work and install VirtualBox? Because when the script fails, the preferences window pops up and I allow it, but the installation has already failed and other programs are installed.

**Comment by commitay** [comment]
Depends on how quickly the popup appears, sometimes if it happens fast enough and it's clicked quickly the installation will be successful. If not, after it's approved just run `brew cask install virtualbox --force`.

**Comment by christophrumpel** [comment]
Thanks @commitay  and I guess there is no other solution right now to make it work without the popup?

**Comment by commitay** [comment]
No.
