### ISSUE TITLE
Cann’t install lyx as ftp.lyx.org is unavailable

### ISSUE THREAD

**Issue by ldeck** [caskroom/homebrew-cask#46567]
#### Description of issue

ftp.lyx.org appears to be an unresolved hostname.
The issue has persisted for a while, which I tried to fix [previously](https://github.com/caskroom/homebrew-cask/pull/42443).

Now, attempting to upgrade lyx fails. Is there a way to do a `brew upgrade lyx —with-mirror=foo`?

curl: (7) Failed to connect to ftp.lyx.org port 21: Connection refused
==> Purging files for version 2.3.0 of Cask lyx
Error: Download failed on Cask 'lyx' with message: Download failed: ftp://ftp.lyx.org/pub/lyx/bin/2.3.0/LyX-2.3.0+qt5-x86_64-cocoa.dmg

#### Command that failed

```
brew upgrade lyx
```

#### Output of command with `--force --verbose --debug`

```
==> Upgrading 1 outdated package, with result:
lyx 2.3.0
==> Started upgrade process for Cask lyx
==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading ftp://ftp.lyx.org/pub/lyx/bin/2.3.0/LyX-2.3.0+qt5-x86_64-cocoa.dmg
/usr/bin/curl -q --show-error --user-agent Homebrew/1.6.2 (Macintosh; Intel Mac OS X 10.13.4) curl/7.54.0 --fail --location --remote-time --continue-at - --output /Users/ldeck/Library/Caches/Homebrew/Cask/lyx--2.3.0.dmg.incomplete ftp://ftp.lyx.org/pub/lyx/bin/2.3.0/LyX-2.3.0+qt5-x86_64-cocoa.dmg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to ftp.lyx.org port 21: Connection refused
==> Purging files for version 2.3.0 of Cask lyx
Error: Download failed on Cask 'lyx' with message: Download failed: ftp://ftp.lyx.org/pub/lyx/bin/2.3.0/LyX-2.3.0+qt5-x86_64-cocoa.dmg
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/download.rb:42:in `rescue in fetch'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/download.rb:40:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/download.rb:15:in `perform'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:126:in `download'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:51:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/upgrade.rb:56:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/upgrade.rb:29:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/upgrade.rb:29:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:101:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:101:in `<main>'
 ldeck  ⓔ 2.5.0  ~  1   
```

#### Output of `brew cask doctor`

```
==> Homebrew-Cask Version
Homebrew-Cask 1.6.2
caskroom/homebrew-cask (git revision 0ae69; last commit 2018-05-01)
==> macOS
10.13.4
==> SIP
Enabled
==> Java
10.0.1, 1.8.0_172
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (32 files, 9.7GB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3959 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-drivers (145 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-fonts (1160 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (176 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-eid (11 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin17
/Library/Ruby/Site/2.3.0/universal-darwin17
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin17
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

#### Output of `brew tap`

```
caskroom/cask
caskroom/drivers
caskroom/eid
caskroom/fonts
caskroom/versions
homebrew/core
homebrew/services
kryptco/tap
vitorgalvao/tiny-scripts
```

**Comment by ldeck** [comment]
Thanks @commitay. Yeah looks like my corporate network’s mucking this up as it’s fine at home.
