### ISSUE TITLE
When execute brew cask list Error: no implicit conversion of nil into String 

### ISSUE THREAD

**Issue by yangyaofei** [caskroom/homebrew-cask#46609]
#### General troubleshooting steps

- [ ❎] I have retried my command with `--force` and the issue is still present.
- [ ✅] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
- [ ✅] None of the templates was appropriate for my issue, or I’m not sure.
- [ ✅] I ran `brew update-reset && brew update` and retried my command.
- [ ✅] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [ ✅] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue
When I execute `brew cask list` it shows  a error
```
Error: no implicit conversion of nil into String
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:44:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:44:in `Pathname'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:44:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/caskroom.rb:27:in `new'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/caskroom.rb:27:in `block in casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/caskroom.rb:20:in `map'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/caskroom.rb:20:in `casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/list.rb:40:in `list_installed'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/list.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:101:in `<main>'
```

#### Command that failed
```
brew cask list
```

#### Output of command with `--force --verbose --debug`

```
$ brew cask list --verbose
Error: no implicit conversion of nil into String
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:44:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:44:in `Pathname'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:44:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/caskroom.rb:27:in `new'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/caskroom.rb:27:in `block in casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/caskroom.rb:20:in `map'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/caskroom.rb:20:in `casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/list.rb:40:in `list_installed'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/list.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:101:in `<main>'
Error: Kernel.exit
$ brew cask list --debug
Error: no implicit conversion of nil into String
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:44:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:44:in `Pathname'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:44:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/caskroom.rb:27:in `new'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/caskroom.rb:27:in `block in casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/caskroom.rb:20:in `map'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/caskroom.rb:20:in `casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/list.rb:40:in `list_installed'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/list.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:101:in `<main>'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:179:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:179:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:101:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew-Cask Version
Homebrew-Cask 1.1.11-2875-g05fc930
caskroom/homebrew-cask (git revision 2953c; last commit 2018-05-02)
==> macOS
10.13.4
==> SIP
Enabled
==> Java
1.8.0_172, 1.8.0_162, 1.8.0_152, 1.8.0_144, 1.8.0_141, 1.8.0_131, 1.8.0_112
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (3 files, 1.4GB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3963 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (176 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_1/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_1/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_1/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_1/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_1/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_1/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_1/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_1/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_1/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_1/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_1/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_1/lib/ruby/2.3.0/universal-darwin9.0
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

#### Output of `brew tap`

```
buo/cask-upgrade
caskroom/cask
caskroom/versions
homebrew/core
homebrew/services
```

#### Output of `brew config`

```
yangyaofeideRMBP:Homebrew yangyaofei$ brew config
HOMEBREW_VERSION: 1.1.11-2875-g05fc930
ORIGIN: https://git.coding.net/homebrew/homebrew.git
HEAD: 05fc9307acb0ed8a6d403ef7d3be20dc853c55f6
Last commit: 84 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core.git
Core tap HEAD: f70c1ecf85ff025f28afa6316fb3a7bdee6950b9
Core tap last commit: 24 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_BOTTLE_DOMAIN: https://mirrors.ustc.edu.cn/homebrew-bottles
HOMEBREW_DEV_CMD_RUN: 1
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_1/bin/ruby
Clang: 9.1 build 902
Git: 2.17.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_172, 1.8.0_162, 1.8.0_152, 1.8.0_144, 1.8.0_141, 1.8.0_131, 1.8.0_112
macOS: 10.13.4-x86_64
CLT: N/A
Xcode: 9.3
XQuartz: N/A
```

**Comment by commitay** [comment]
Closing in favour of https://github.com/caskroom/homebrew-cask/issues/46407
