### ISSUE TITLE
Cannot update scratch.rb

### ISSUE THREAD

**Issue by ahousseini** [caskroom/homebrew-cask#46830]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs).
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Cannot run upgrade properly because of scratch.

#### Command that failed

```
brew cask upgrade
```

#### Output of command with `--force --verbose --debug`

```
$ brew cask upgrade scratch --verbose --debug
==> Upgrading 1 outdated package, with result:
scratch 2.0,460
==> Started upgrade process for Cask scratch
==> Hbc::Installer#fetch
==> Satisfying dependencies
All Cask dependencies satisfied.
==> Downloading
==> Downloading https://scratch.mit.edu/scratchr2/static/sa/Scratch-460.dmg
Already downloaded: /Users/admin/Library/Caches/Homebrew/Cask/scratch--2.0,460.dmg
==> Downloaded to -> /Users/admin/Library/Caches/Homebrew/Cask/scratch--2.0,460.dmg
==> Verifying download
==> Determining which verifications to run for Cask scratch
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask scratch
==> SHA256 checksums match
==> Starting upgrade for Cask scratch
==> Un-installing artifacts
==> 2 artifact/s defined
#<SortedSet:0x000001030bbcc0>
==> Un-installing artifact of class Hbc::Artifact::Uninstall
==> Running uninstall process for scratch; your password may be necessary
==> Running uninstall script /Applications/Utilities/Adobe AIR Application Installer.app/Contents/MacOS/Adobe AIR Application Installer
==> Executing: ["/bin/chmod", "--", "+x", "/Applications/Utilities/Adobe AIR Application Installer.app/Contents/MacOS/Adobe AIR Application Installer"]
==> Executing: ["/usr/bin/sudo", "-E", "--", "/Applications/Utilities/Adobe AIR Application Installer.app/Contents/MacOS/Adobe AIR Application Installer", "-uninstall", "-silent", "/Applications/Scratch 2.app"]
==> unexpected error: Error: Missing necessary file META-INF/AIR/application.xml
==> Purging files for version 2.0,460 of Cask scratch
Error: Command failed to execute!

==> Failed command:
/usr/bin/sudo -E -- /Applications/Utilities/Adobe AIR Application Installer.app/Contents/MacOS/Adobe AIR Application Installer -uninstall -silent /Applications/Scratch 2.app

==> Standard Output of failed command:
unexpected error: Error: Missing necessary file META-INF/AIR/application.xml


==> Standard Error of failed command:


==> Exit status of failed command:
#<Process::Status: pid 84012 exit 5>

/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:71:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:36:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb:204:in `uninstall_script'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb:58:in `block in dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb:55:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb:55:in `dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall.rb:7:in `uninstall_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:403:in `block in uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:400:in `uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:362:in `start_upgrade'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/upgrade.rb:59:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/upgrade.rb:29:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/upgrade.rb:29:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:101:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:101:in `<main>'
```

#### Output of `brew cask doctor`

```
$ brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.6.3-11-g9c3043c
caskroom/homebrew-cask (git revision 54bf7; last commit 2018-05-08)
==> macOS
10.13.4
==> SIP
Enabled
==> Java
1.8.0_144
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (4 files, 115MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3961 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-drivers (145 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-fonts (1161 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (176 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-eid (11 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/2.3.0/universal-darwin9.0
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

#### Output of `brew tap`

```
$ brew tap
buo/cask-upgrade
busterc/tap
caskroom/cask
caskroom/drivers
caskroom/eid
caskroom/fonts
caskroom/versions
domt4/autoupdate
homebrew/bundle
homebrew/command-not-found
homebrew/core
homebrew/services
kitsuyui/myip
timsutton/formulae
vitorgalvao/tiny-scripts
```

**Comment by vitorgalvao** [comment]
```
brew cask uninstall --force scratch || rm -rf "$(brew --prefix)/Caskroom/scratch"
brew install --force scratch
```

**Comment by ahousseini** [comment]
Still the same error:

```$ brew cask uninstall --force scratch || rm -rf "$(brew --prefix)/Caskroom/scratch"
brew install --force scratch
==> Uninstalling Cask scratch
==> Running uninstall process for scratch; your password may be necessary
==> Running uninstall script /Applications/Utilities/Adobe AIR Application Installer.app/Contents/MacOS/Adobe AIR Application Installer
==> unexpected error: Error: Missing necessary file META-INF/AIR/applicati
Error: Command failed to execute!

==> Failed command:
/usr/bin/sudo -E -- /Applications/Utilities/Adobe AIR Application Installer.app/Contents/MacOS/Adobe AIR Application Installer -uninstall -silent /Applications/Scratch 2.app

==> Standard Output of failed command:
unexpected error: Error: Missing necessary file META-INF/AIR/application.xml


==> Standard Error of failed command:


==> Exit status of failed command:
#<Process::Status: pid 52657 exit 5>
$ brew install --force scratch
Error: Another active Homebrew update process is already in progress.
Please wait for it to finish or terminate it to continue.
Error: No available formula with the name "scratch" 
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching for similarly named formulae...
==> Searching local taps...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
This formula was found in a tap:
caskroom/cask/scratch
To install it, run:
  brew install caskroom/cask/scratch

**Comment by ahousseini** [comment]
After running `brew install caskroom/cask/scratch` the issue was solved.
