### ISSUE TITLE
The outdated/upgrade commands are not reliable

### ISSUE THREAD

**Issue by robotvert** [caskroom/homebrew-cask#46916]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs).
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

I ran `brew cask outdated` and it showed that "makemkv" was outdated. 
Running `brew cask upgrade` updated it. 
Everything's fine.
But then, other installed apps are out of date and none of them show as outdated or get upgraded:

```sh
brew cask info docker
docker: 18.03.1-ce-mac65,24312
https://www.docker.com/community-edition
/usr/local/Caskroom/docker/18.03.1-ce-mac64,24245 (64B)
From: https://github.com/caskroom/homebrew-cask/blob/master/Casks/docker.rb
# (...)

brew cask info handbrake
handbrake: 1.1.0
https://handbrake.fr/
/usr/local/Caskroom/handbrake/1.0.7 (6 files, 81.3KB)
From: https://github.com/caskroom/homebrew-cask/blob/master/Casks/handbrake.rb
# (...)

brew cask outdated
# (no output)

brew cask upgrade
==> No Casks to upgrade
```

#### Command that failed

```
brew cask outdated
```

```
brew cask upgrade
```

#### Output of command with `--force --verbose --debug`

```
brew cask outdated --force --verbose --debug
Error: invalid option: --force
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/options.rb:60:in `process_arguments'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:42:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/outdated.rb:8:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `new'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:101:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:101:in `<main>'
```

```
brew cask upgrade --force --verbose --debug
==> No Casks to upgrade
```

#### Output of `brew cask doctor`

```
brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.6.3-13-gaf578f5
caskroom/homebrew-cask (git revision 445399; last commit 2018-05-10)
==> macOS
10.13.4
==> SIP
Enabled
==> Java
10.0.1
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (2 files, 220MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3960 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (177 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin17
/Library/Ruby/Site/2.3.0/universal-darwin17
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin17
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/usr/local/bin/zsh"
```

#### Output of `brew tap`

```
brew tap
caskroom/cask
caskroom/versions
ethereum/ethereum
homebrew/core
homebrew/dupes
homebrew/services
homebrew/versions
robotvert/mini-formulae
```

**Comment by commitay** [comment]
Both `docker` and `handbrake` have `auto_updates true`

`man brew-cask`
```
outdated [−−greedy] [−−verbose|−−quiet] [ token ... ]
Without token arguments, display all the installed Casks that have newer versions available in the tap; otherwise check only the tokens given in the command line. If −−greedy is given then also include in the output the Casks having auto_updates true or version :latest. Otherwise they are skipped because there is no reliable way to know when updates are available for them.
−−verbose forces the display of the outdated and latest version.
−−quiet suppresses the display of versions.
```

```
upgrade [−−force] [−−greedy] token [ token ... ]
Without token arguments, upgrade all the installed Casks that have newer versions available in the tap; otherwise update the tokens given in the command line. If −−greedy is given then also upgrade the Casks having auto_updates true or version :latest.
```

**Comment by robotvert** [comment]
Thanks for the swift reply. 

I had just stumbled on https://github.com/caskroom/homebrew-cask/pull/46417 and was about to close. I notice that documentation change has been reverted after being merged, do you know why? It seems to be a soon-to-become-a-classic issue 😅

**Comment by commitay** [comment]
It hasn't been reverted: 
https://github.com/caskroom/homebrew-cask/blob/master/USAGE.md#updatingupgrading-casks

**Comment by robotvert** [comment]
🙈 

Sorry, I was looking at a fork... Need to get some sleep I guess, thanks for everything!
