### ISSUE TITLE
Cask `whatsyoursign` fails to uninstall

### ISSUE THREAD

**Issue by SConaway** [caskroom/homebrew-cask#46986]
Pretty self-explanatory here - Cask `whatsyoursign` fails to uninstall.

````brew cask remove whatsyoursign --debug
==> Uninstalling Cask whatsyoursign
==> Uninstalling Cask whatsyoursign
==> Un-installing artifacts
==> 3 artifact/s defined
#<SortedSet:0x007fe154238ad8>
==> Un-installing artifact of class Hbc::Artifact::PreflightBlock
==> Executing: ["/usr/bin/pluginkit", "-r", "/Applications/WhatsYourSign.app/Contents/PlugIns/WhatsYourSign.appex"]
==> remove: no plugin at /Applications/WhatsYourSign.app/Contents/PlugIns/WhatsY
Error: Command failed to execute!

==> Failed command:
/usr/bin/pluginkit -r /Applications/WhatsYourSign.app/Contents/PlugIns/WhatsYourSign.appex

==> Standard Output of failed command:


==> Standard Error of failed command:
remove: no plugin at /Applications/WhatsYourSign.app/Contents/PlugIns/WhatsYourSign.appex


==> Exit status of failed command:
#<Process::Status: pid 29073 exit 1>

/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:71:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:36:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:18:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/dsl/base.rb:14:in `system_command'
/usr/local/Caskroom/whatsyoursign/.metadata/1.4.1/20180228044433.477/Casks/whatsyoursign.rb:17:in `block (2 levels) in load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_flight_block.rb:38:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_flight_block.rb:38:in `abstract_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_flight_block.rb:26:in `uninstall_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:403:in `block in uninstall_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:400:in `uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:353:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:22:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:12:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:12:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:101:in `<main>'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:101:in `<main>'````

**Comment by commitay** [comment]
Does `/Applications/WhatsYourSign.app/Contents/PlugIns/WhatsYourSign.appex` exist?

Also, please always fill out the template.

**Comment by SConaway** [comment]
There wasn't a template for me, sorry. I didn't realize that I uninstalled WhatsYourSign before.

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/46988

**Comment by SConaway** [comment]
Is that needed?

**Comment by commitay** [comment]
Yes, it's installer manual.

`brew cask install whatsyoursign && brew cask uninstall whatsyoursign`

errors because the app does't exist in `/Applications`

**Comment by commitay** [comment]
> There wasn't a template for me

Our template have changed recently, did you use "Open a regular issue" when you opened a new issue?
