### ISSUE TITLE
brew cask uninstall r-app fails with Error: key not found: "install-location"

### ISSUE THREAD

**Issue by jkseppan** [caskroom/homebrew-cask#47093]
#### General troubleshooting steps

- [X] I have retried my command with `--force` and the issue is still present.
- [X] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs).
  - [X] None of the templates was appropriate for my issue, or I’m not sure.
    - ...I'm not sure what that means, as I did pick this bug report template
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

When I try to uninstall `r-app`, or reinstall it to get the latest version, the command fails. Reinstalling other casks such as `rstudio` or `alfred` works:

```
==> Satisfying dependencies
==> Downloading https://cachefly.alfredapp.com/Alfred_3.6.1_910.dmg
######################################################################## 100.0%
==> Verifying checksum for Cask alfred
==> Uninstalling Cask alfred
Warning: Accessibility access cannot be disabled automatically on this version of macOS.
See System Preferences to disable it manually.
==> Running uninstall process for alfred; your password may be necessary
==> Quitting application ID com.runningwithcrayons.Alfred-3
Password:
==> Removing login item Alfred 3
==> Backing App 'Alfred 3.app' up to '/opt/homebrew/Caskroom/alfred/3.6.1_910/Alfred 3.app'.
==> Removing App '/Applications/Alfred 3.app'.
==> Purging files for version 3.6.1_910 of Cask alfred
==> Installing Cask alfred
==> Moving App 'Alfred 3.app' to '/Applications/Alfred 3.app'.
==> Enabling accessibility access
Warning: Accessibility access cannot be enabled automatically on this version of macOS.
See System Preferences to enable it manually.
🍺  alfred was successfully installed!
```

#### Command that failed

```
brew cask uninstall r-app
```

#### Output of command with `--force --verbose --debug`

```
==> Uninstalling Cask r-app
==> Uninstalling Cask r-app
==> Un-installing artifacts
==> 3 artifact/s defined
#<SortedSet:0x000001015f10c0>
==> Un-installing artifact of class Hbc::Artifact::Uninstall
==> Running uninstall process for r-app; your password may be necessary
==> Uninstalling packages:
==> Executing: ["/usr/sbin/pkgutil", "--pkgs=org.r-project*"]
org.r-project.R
==> Executing: ["/usr/sbin/pkgutil", "--files", "org.r-project.R"]
==> Executing: ["/usr/sbin/pkgutil", "--pkg-info-plist", "org.r-project.R"]
Error: key not found: "install-location"
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask#reporting-bugs
/opt/homebrew/Library/Homebrew/cask/lib/hbc/pkg.rb:72:in `fetch'
/opt/homebrew/Library/Homebrew/cask/lib/hbc/pkg.rb:72:in `root'
/opt/homebrew/Library/Homebrew/cask/lib/hbc/pkg.rb:67:in `block in pkgutil_bom_all'
/opt/homebrew/Library/Homebrew/cask/lib/hbc/pkg.rb:67:in `map'
/opt/homebrew/Library/Homebrew/cask/lib/hbc/pkg.rb:67:in `pkgutil_bom_all'
/opt/homebrew/Library/Homebrew/cask/lib/hbc/pkg.rb:52:in `pkgutil_bom_files'
/opt/homebrew/Library/Homebrew/cask/lib/hbc/pkg.rb:17:in `uninstall'
/opt/homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb:213:in `block (2 levels) in uninstall_pkgutil'
/opt/homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb:211:in `each'
/opt/homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb:211:in `block in uninstall_pkgutil'
/opt/homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb:210:in `each'
/opt/homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb:210:in `uninstall_pkgutil'
/opt/homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb:58:in `block in dispatch_uninstall_directives'
/opt/homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb:55:in `each'
/opt/homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_uninstall.rb:55:in `dispatch_uninstall_directives'
/opt/homebrew/Library/Homebrew/cask/lib/hbc/artifact/uninstall.rb:7:in `uninstall_phase'
/opt/homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:403:in `block in uninstall_artifacts'
/opt/homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/2.3.0/set.rb:674:in `each'
/opt/homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/2.3.0/set.rb:674:in `each'
/opt/homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:400:in `uninstall_artifacts'
/opt/homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:353:in `uninstall'
/opt/homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:22:in `block in run'
/opt/homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:12:in `each'
/opt/homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:12:in `run'
/opt/homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/opt/homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
/opt/homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `run'
/opt/homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/opt/homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/opt/homebrew/Library/Homebrew/brew.rb:101:in `<main>'
Error: Kernel.exit
/opt/homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:179:in `exit'
/opt/homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:179:in `rescue in run'
/opt/homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/opt/homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/opt/homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/opt/homebrew/Library/Homebrew/brew.rb:101:in `<main>'
```

When I run the `pkgutil` command in the log just before the error message, I get

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>install-time</key>
	<integer>1252406887</integer>
	<key>pkg-version</key>
	<string>1.29.5464</string>
	<key>pkgid</key>
	<string>org.r-project.R</string>
	<key>receipt-plist-version</key>
	<real>1</real>
	<key>volume</key>
	<string>/</string>
</dict>
</plist>
```

#### Output of `brew cask doctor`

```
==> Homebrew-Cask Version
Homebrew-Cask 1.6.3-26-ga3d639d
caskroom/homebrew-cask (git revision 42313; last commit 2018-05-13)
==> macOS
10.13.4
==> SIP
Enabled (custom configuration)

configuration:
apple internal: disabled
kext signing: enabled
filesystem protections: enabled
debugging restrictions: enabled
dtrace restrictions: disabled
nvram protections: enabled
basesystem verification: enabled
==> Java
1.8.0_112, 1.7.0_45
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/opt/homebrew/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask
==> Homebrew-Cask Taps:
/opt/homebrew/Library/Taps/caskroom/homebrew-cask (3958 casks)
==> Contents of $LOAD_PATH
/opt/homebrew/Library/Homebrew/cask/lib
/opt/homebrew/Library/Homebrew
/opt/homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/opt/homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/site_ruby/2.3.0
/opt/homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/opt/homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/opt/homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/site_ruby
/opt/homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/vendor_ruby/2.3.0
/opt/homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/opt/homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/opt/homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/vendor_ruby
/opt/homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/2.3.0
/opt/homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/2.3.0/x86_64-darwin9.0
/opt/homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/2.3.0/universal-darwin9.0
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/opt/homebrew/Library/Homebrew/shims/scm"
SHELL="/opt/homebrew/bin/zsh"
```

#### Output of `brew tap`

```
burntsushi/ripgrep
caskroom/cask
homebrew/core
homebrew/games
homebrew/php
homebrew/python
homebrew/science
justwatchcom/gopass
```

**Comment by commitay** [comment]
> Error: key not found: "install-location"

Not sure what's causing this but it is likely to be an issue with that version of `r-app` and not something we can fix in the Cask. Versions >= 3.4.2 uninstall correctly on our CI.

`brew cask install --force r-app` will install the current version.

**Comment by commitay** [comment]
`uninstall` is still trying to remove the old `pkgid`

`pkgutil --forget org.r-project.R`

**Comment by jkseppan** [comment]
Still no luck. The `pkgutil` command reports an error but still claims to have forgotten the package:

```
% pkgutil --force --forget org.r-project.R
Unknown error Error Domain=NSCocoaErrorDomain Code=4 "“org.r-project.R.bom” couldn’t be removed." UserInfo={NSFilePath=/var/db/receipts/org.r-project.R.bom, NSUserStringVariant=(
    Remove
), NSUnderlyingError=0x7fc7020214b0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}.
Forgot package 'org.r-project.R' on '/'.
```

The `brew cask reinstall` command still reports the same error.

If the "install-time" value of 1252406887 in the pkgutil command output is a Unix timestamp, it's a date in 2009, which is older than this laptop. It may have been the time I first installed R on my previous laptop, which would then have been inherited through Apple's migration wizard.

**Comment by commitay** [comment]
Unfortunately I don't really have any suggestions for how to fix this.

We've encountered similar issues with Casks that install pkgs provided by Apple (`safari-technology-preview` and a couple of others)
