### ISSUE TITLE
brew cask style fails with new cask

### ISSUE THREAD

**Issue by onlynone** [caskroom/homebrew-cask#47210]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs).
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Running `brew cask style Casks/rale.rb` [as instructed for a new cask](https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#testing-your-new-cask) results in the following error:

```
Error: Cask 'rale' is unavailable: No Cask with this name exists. Did you mean “rale”?
```

#### Command that failed

```
brew cask style Casks/rale.rb
```

#### Output of command with `--force --verbose --debug`

```
Error: invalid option: --force
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/options.rb:60:in `process_arguments'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:42:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `new'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:101:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:101:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew-Cask Version
Homebrew-Cask 1.6.3-30-g5616dca
caskroom/homebrew-cask (git revision da05e; last commit 2018-05-14)
==> macOS
10.12.6
==> SIP
Disabled
==> Java
1.8.0_131
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (41 files, 3.5GB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3960 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (177 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
~/.gem/ruby/2.3.0/gems/json-1.8.6/lib
~/.gem/ruby/2.3.0/extensions/universal-darwin-9/2.3.0-static/json-1.8.6
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/2.3.0/universal-darwin9.0
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/usr/local/bin/bash"
```

#### Output of `brew tap`

```
caskroom/cask
caskroom/versions
codekitchen/dinghy
go-delve/delve
homebrew/core
homebrew/services
johanhaleby/kubetail
onlynone/custom
```

#### Context

For completeness, these are the full commands and output that lead to the error:

```
$ brew cask create rale
Editing /usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask/Casks/rale.rb

[1]+  Stopped                 brew cask create rale
$ brew cask audit rale --download
==> Downloading https://devtools.web.roku.com/roku-advanced-layout-editor/app/roku-advanced-layout-editor-mac.zip
######################################################################## 100.0%
==> No checksum defined for Cask rale, skipping verification
audit for rale: passed
$ brew cask style Casks/rale.rb
==> Installing or updating 'rubocop-cask' gem
Fetching: public_suffix-3.0.2.gem (100%)
Successfully installed public_suffix-3.0.2
Fetching: parallel-1.12.1.gem (100%)
Successfully installed parallel-1.12.1
Fetching: ast-2.4.0.gem (100%)
Successfully installed ast-2.4.0
Fetching: parser-2.5.1.0.gem (100%)
Successfully installed parser-2.5.1.0
Fetching: powerpack-0.1.1.gem (100%)
Successfully installed powerpack-0.1.1
Fetching: rainbow-3.0.0.gem (100%)
Successfully installed rainbow-3.0.0
Fetching: ruby-progressbar-1.9.0.gem (100%)
Successfully installed ruby-progressbar-1.9.0
Fetching: unicode-display_width-1.3.2.gem (100%)
Successfully installed unicode-display_width-1.3.2
Fetching: rubocop-0.55.0.gem (100%)
Successfully installed rubocop-0.55.0
Fetching: rubocop-cask-0.19.0.gem (100%)
Successfully installed rubocop-cask-0.19.0
10 gems installed
Error: Cask 'rale' is unavailable: No Cask with this name exists. Did you mean “rale”?
```

**Comment by onlynone** [comment]
Nevermind, missed the part of `cd`-ing to the homebrew-cask directory.
