### ISSUE TITLE
uninstall of nix cask failing

### ISSUE THREAD

**Issue by stephengroat** [caskroom/homebrew-cask#47342]
#### General troubleshooting steps

- [X] I have retried my command with `--force` and the issue is still present.
- [X] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs).
  - [X] None of the templates was appropriate for my issue, or I’m not sure.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

`uninstall` of `nix` cask currently failing. Also prevents `reinstall` and `upgrade` from succeeding

#### Command that failed

```
brew cask install nix && brew cask reinstall nix
```

#### Output of command with `--force --verbose --debug`

```
$ brew cask install --force --verbose --debug nix
==> Hbc::Installer#install
==> Printing caveats
==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://nixos.org/releases/nix/nix-2.0.2/nix-2.0.2-x86_64-darwin.tar.bz2
Already downloaded: /Users/stephengroat/Library/Caches/Homebrew/Cask/nix--2.0.2.tar.bz2
==> Downloaded to -> /Users/stephengroat/Library/Caches/Homebrew/Cask/nix--2.0.2.tar.bz2
==> Verifying download
==> Determining which verifications to run for Cask nix
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask nix
==> SHA256 checksums match
==> Installing Cask nix
==> Hbc::Installer#stage
==> Extracting primary container
==> Determining which containers to use based on filetype
==> Checking container class Hbc::Container::Pkg
==> Checking container class Hbc::Container::Ttf
==> Checking container class Hbc::Container::Otf
==> Checking container class Hbc::Container::Air
==> Checking container class Hbc::Container::Cab
==> Checking container class Hbc::Container::Dmg
==> Executing: ["/usr/bin/hdiutil", "imageinfo", "/Users/stephengroat/Library/Caches/Homebrew/Cask/nix--2.0.2.tar.bz2"]
==> Checking container class Hbc::Container::SevenZip
==> Checking container class Hbc::Container::Sit
==> Checking container class Hbc::Container::Rar
==> Checking container class Hbc::Container::Zip
==> Checking container class Hbc::Container::Xar
==> Checking container class Hbc::Container::Tar
==> Using container class Hbc::Container::Tar for /Users/stephengroat/Library/Caches/Homebrew/Cask/nix--2.0.2.tar.bz2
==> Executing: ["/usr/bin/tar", "-x", "-f", "/Users/stephengroat/Library/Caches/Homebrew/Cask/nix--2.0.2.tar.bz2", "-C", "/var/folders/px/s36yhxx96838n77vj3bpn6fh0000gn/T/d20180517-43376-1lxjnjm"]
==> Executing: ["/usr/bin/ditto", "--", "/var/folders/px/s36yhxx96838n77vj3bpn6fh0000gn/T/d20180517-43376-1lxjnjm", "/usr/local/Caskroom/nix/2.0.2"]
==> Creating metadata directory /usr/local/Caskroom/nix/.metadata/2.0.2/20180517200710.244.
==> Creating metadata subdirectory /usr/local/Caskroom/nix/.metadata/2.0.2/20180517200710.244/Casks.
==> Installing artifacts
==> 4 artifact/s defined
#<SortedSet:0x0000010348ebb8>
==> Installing artifact of class Hbc::Artifact::Installer
==> Running installer script 'nix-2.0.2-x86_64-darwin/install'
==> Executing: ["/usr/local/Caskroom/nix/2.0.2/nix-2.0.2-x86_64-darwin/install"]
==> Switching to the Daemon-based Installer
==> Welcome to the Multi-User Nix Installation
==>
==>
==> This installation tool will set up your computer with the Nix package
==> manager. This will happen in a few stages:
==>
==> 1. Make sure your computer doesn't already have Nix. If it does, I
==>    will show you instructions on how to clean up your old one.
==>
==> 2. Show you what we are going to install and where. Then we will ask
==>    if you are ready to continue.
==>
==> 3. Create the system users and groups that the Nix daemon uses to run
==>    builds.
==>
==> 4. Perform the basic installation of the Nix files daemon.
==>
==> 5. Configure your shell to import special Nix Profile files, so you
==>    can use Nix.
==>
==> 6. Start the Nix daemon.
==>
==> Would you like to see a more detailed list of what we will do?
==> No TTY, assuming you would say yes :)
==>
==> We will:
==>
==>  - make sure your computer doesn't already have Nix files
==>    (if it does, I  will tell you how to clean them up.)
==>  - create local users (see the list above for the users we'll make)
==>  - create a local group (nixbld)
==>  - install Nix in to /nix
==>  - create a configuration file in /etc/nix
==>  - set up the "default profile" by creating some Nix-related files in
==>    /var/root
==>  - back up /etc/bashrc to /etc/bashrc.backup-before-nix
==>  - update /etc/bashrc to include some Nix configuration
==>  - back up /etc/zshrc to /etc/zshrc.backup-before-nix
==>  - update /etc/zshrc to include some Nix configuration
==>  - load and start a LaunchDaemon (at /Library/LaunchDaemons/org.nixos.nix-daemon.plist) for nix-daemon
==>
==> Ready to continue?
==> No TTY, assuming you would say yes :)
==>
==> ---- let's talk about sudo -----------------------------------------------------
==>
==> This script is going to call sudo a lot. Normally, it would show you
==> exactly what commands it is running and why. However, the script is
==> run in a headless fashion, like this:
==>
==>   $ curl https://nixos.org/nix/install | sh
==>
==> or maybe in a CI pipeline. Because of that, we're going to skip the
==> verbose output in the interest of brevity.
==>
==> If you would like to
==> see the output, try like this:
==>
==>   $ curl -o install-nix https://nixos.org/nix/install
==>   $ sh ./install-nix
==>
==>
==> ---- oh no! --------------------------------------------------------------------
==>
==> There are some relics of a previous installation of Nix at /etc/nix, and
==> this scripts assumes Nix is _not_ yet installed. Please delete the old
==> Nix installation and start again.
==>
==>
==> Uninstalling nix:
==> 1. Restore /etc/bashrc.backup-before-nix back to /etc/bashrc
==>
==>   sudo mv /etc/bashrc.backup-before-nix /etc/bashrc
==>
==> (after this one, you may need to re-open any terminals that were
==> opened while it existed.)
==>
==> 2. Restore /etc/zshrc.backup-before-nix back to /etc/zshrc
==>
==>   sudo mv /etc/zshrc.backup-before-nix /etc/zshrc
==>
==> (after this one, you may need to re-open any terminals that were
==> opened while it existed.)
==>
==> 3. Delete the files Nix added to your system:
==>
==>   sudo rm -rf /etc/nix /nix /var/root/.nix-profile /var/root/.nix-defexpr /var/root/.nix-channels /Users/stephengroat/.nix-profile /Users/stephengroat/.nix-defexpr /Users/stephengroat/.nix-channels
==>
==> and that is it.
==>
==> We'd love to help if you need it.
==>
==> If you can, open an issue at https://github.com/nixos/nix/issues
==>
==> Or feel free to contact the team,
==>  - on IRC #nixos on irc.freenode.net
==>  - on twitter @nixos_org
==>
==> Purging files for version 2.0.2 of Cask nix
Error: Command failed to execute!

==> Failed command:
/usr/local/Caskroom/nix/2.0.2/nix-2.0.2-x86_64-darwin/install

==> Standard Output of failed command:
Switching to the Daemon-based Installer
Welcome to the Multi-User Nix Installation

This installation tool will set up your computer with the Nix package
manager. This will happen in a few stages:

1. Make sure your computer doesn't already have Nix. If it does, I
   will show you instructions on how to clean up your old one.

2. Show you what we are going to install and where. Then we will ask
   if you are ready to continue.

3. Create the system users and groups that the Nix daemon uses to run
   builds.

4. Perform the basic installation of the Nix files daemon.

5. Configure your shell to import special Nix Profile files, so you
   can use Nix.

6. Start the Nix daemon.

Would you like to see a more detailed list of what we will do?
No TTY, assuming you would say yes :)

We will:

 - make sure your computer doesn't already have Nix files
   (if it does, I  will tell you how to clean them up.)
 - create local users (see the list above for the users we'll make)
 - create a local group (nixbld)
 - install Nix in to /nix
 - create a configuration file in /etc/nix
 - set up the "default profile" by creating some Nix-related files in
   /var/root
 - back up /etc/bashrc to /etc/bashrc.backup-before-nix
 - update /etc/bashrc to include some Nix configuration
 - back up /etc/zshrc to /etc/zshrc.backup-before-nix
 - update /etc/zshrc to include some Nix configuration
 - load and start a LaunchDaemon (at /Library/LaunchDaemons/org.nixos.nix-daemon.plist) for nix-daemon

Ready to continue?
No TTY, assuming you would say yes :)

---- let's talk about sudo -----------------------------------------------------
This script is going to call sudo a lot. Normally, it would show you
exactly what commands it is running and why. However, the script is
run in a headless fashion, like this:

  $ curl https://nixos.org/nix/install | sh

or maybe in a CI pipeline. Because of that, we're going to skip the
verbose output in the interest of brevity.

If you would like to
see the output, try like this:

  $ curl -o install-nix https://nixos.org/nix/install
  $ sh ./install-nix


---- oh no! --------------------------------------------------------------------
There are some relics of a previous installation of Nix at /etc/nix, and
this scripts assumes Nix is _not_ yet installed. Please delete the old
Nix installation and start again.


Uninstalling nix:
1. Restore /etc/bashrc.backup-before-nix back to /etc/bashrc

  sudo mv /etc/bashrc.backup-before-nix /etc/bashrc

(after this one, you may need to re-open any terminals that were
opened while it existed.)

2. Restore /etc/zshrc.backup-before-nix back to /etc/zshrc

  sudo mv /etc/zshrc.backup-before-nix /etc/zshrc

(after this one, you may need to re-open any terminals that were
opened while it existed.)

3. Delete the files Nix added to your system:

  sudo rm -rf /etc/nix /nix /var/root/.nix-profile /var/root/.nix-defexpr /var/root/.nix-channels /Users/stephengroat/.nix-profile /Users/stephengroat/.nix-defexpr /Users/stephengroat/.nix-channels

and that is it.

We'd love to help if you need it.

If you can, open an issue at https://github.com/nixos/nix/issues

Or feel free to contact the team,
 - on IRC #nixos on irc.freenode.net
 - on twitter @nixos_org


==> Standard Error of failed command:


==> Exit status of failed command:
#<Process::Status: pid 43789 exit 1>

/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:71:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:36:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/installer.rb:26:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:174:in `block in install_artifacts'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:166:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:80:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:20:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:101:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:101:in `<main>'
```

#### Output of `brew cask doctor`

```
$ brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.6.3-49-gc28f56b
caskroom/homebrew-cask (git revision a42f3; last commit 2018-05-17)
==> macOS
10.13.4
==> SIP
Enabled
==> Java
10.0.1, 1.8.0_172, 1.6.0_65-b14-468
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (1 files, 25.3MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3964 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (178 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/2.3.0/universal-darwin9.0
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

#### Output of `brew tap`

```
$ brew tap
caskroom/cask
caskroom/versions
homebrew/bundle
homebrew/core
homebrew/services
```

**Comment by commitay** [comment]
@vitorgalvao I'm leaning towards removing this Cask as this should all be handled by an uninstall script provided by upstream rather than us playing whack a mole with user config.

> ==> Uninstalling nix:
==> 1. Restore /etc/bashrc.backup-before-nix back to /etc/bashrc
==>
==>   sudo mv /etc/bashrc.backup-before-nix /etc/bashrc
==>
==> (after this one, you may need to re-open any terminals that were
==> opened while it existed.)
==>
==> 2. Restore /etc/zshrc.backup-before-nix back to /etc/zshrc
==>
==>   sudo mv /etc/zshrc.backup-before-nix /etc/zshrc
==>
==> (after this one, you may need to re-open any terminals that were
==> opened while it existed.)
==>
==> 3. Delete the files Nix added to your system:
==>
==>   sudo rm -rf /etc/nix /nix /var/root/.nix-profile /var/root/.nix-defexpr /var/root/.nix-channels /Users/stephengroat/.nix-profile /Users/stephengroat/.nix-defexpr /Users/stephengroat/.nix-channels
==>

**Comment by vitorgalvao** [comment]
@commitay I agree. This cask will definitely be more trouble than it is worth.

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/pull/47423
