### ISSUE TITLE
brew cask style fails with "Unable to resolve dependency: user requested 'did_you_mean (= 1.0.0)'"

### ISSUE THREAD

**Issue by csi-adziahel** [caskroom/homebrew-cask#47502]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs).
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

`brew cask style` fails with `Error: Unable to resolve dependency: user requested 'did_you_mean (= 1.0.0)'` message producing following output:

```
==> Installing or updating 'rubocop-cask' gem
Error: Unable to resolve dependency: user requested 'did_you_mean (= 1.0.0)'
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask#reporting-bugs
/Library/Ruby/Site/2.3.0/rubygems/resolver.rb:231:in `search_for'
/Library/Ruby/Site/2.3.0/rubygems/resolver.rb:283:in `block in sort_dependencies'
/Library/Ruby/Site/2.3.0/rubygems/resolver.rb:277:in `each'
/Library/Ruby/Site/2.3.0/rubygems/resolver.rb:277:in `sort_by'
/Library/Ruby/Site/2.3.0/rubygems/resolver.rb:277:in `with_index'
/Library/Ruby/Site/2.3.0/rubygems/resolver.rb:277:in `sort_dependencies'
/Library/Ruby/Site/2.3.0/rubygems/resolver/molinillo/lib/molinillo/delegates/specification_provider.rb:52:in `block in sort_dependencies'
/Library/Ruby/Site/2.3.0/rubygems/resolver/molinillo/lib/molinillo/delegates/specification_provider.rb:69:in `with_no_such_dependency_error_handling'
/Library/Ruby/Site/2.3.0/rubygems/resolver/molinillo/lib/molinillo/delegates/specification_provider.rb:51:in `sort_dependencies'
/Library/Ruby/Site/2.3.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:165:in `initial_state'
/Library/Ruby/Site/2.3.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:106:in `start_resolution'
/Library/Ruby/Site/2.3.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:64:in `resolve'
/Library/Ruby/Site/2.3.0/rubygems/resolver/molinillo/lib/molinillo/resolver.rb:42:in `resolve'
/Library/Ruby/Site/2.3.0/rubygems/resolver.rb:188:in `resolve'
/Library/Ruby/Site/2.3.0/rubygems/request_set.rb:385:in `resolve'
/Library/Ruby/Site/2.3.0/rubygems/request_set.rb:397:in `resolve_current'
/Library/Ruby/Site/2.3.0/rubygems.rb:243:in `finish_resolve'
/Library/Ruby/Site/2.3.0/rubygems/rdoc.rb:15:in `<top (required)>'
/Library/Ruby/Site/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/Library/Ruby/Site/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/Library/Ruby/Site/2.3.0/rubygems/commands/install_command.rb:280:in `load_hooks'
/Library/Ruby/Site/2.3.0/rubygems/commands/install_command.rb:156:in `execute'
/usr/local/Homebrew/Library/Homebrew/utils.rb:228:in `install_gem!'
/usr/local/Homebrew/Library/Homebrew/utils.rb:236:in `install_gem_setup_path!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/style.rb:21:in `block in install_rubocop'
/usr/local/Homebrew/Library/Homebrew/utils.rb:404:in `capture_stderr'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/style.rb:19:in `install_rubocop'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/style.rb:11:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
```

#### Command that failed

```
brew cask style
```

#### Output of command with `--force --verbose --debug`

```
Error: invalid option: --force
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/options.rb:60:in `process_arguments'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:42:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `new'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew-Cask Version
Homebrew-Cask 1.6.4-24-g24025a3
caskroom/homebrew-cask (git revision eff9; last commit 2018-05-23)
==> macOS
10.13.4
==> SIP
Enabled
==> Java
1.8.0_172
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (29 files, 2.2GB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3960 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-drivers (147 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-fonts (1161 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (179 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-eid (11 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin17
/Library/Ruby/Site/2.3.0/universal-darwin17
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin17
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

#### Output of `brew tap`

```
buo/cask-upgrade
caskroom/cask
caskroom/drivers
caskroom/eid
caskroom/fonts
caskroom/versions
homebrew/core
homebrew/services
samritchie/forge
sportngin/homebrew
[REDACTED, was private formulas tap]
vitorgalvao/tiny-scripts
```

**Comment by csi-adziahel** [comment]
It seems to belong https://github.com/Homebrew/homebrew-core or https://discourse.brew.sh even
