### ISSUE TITLE
'checklinks' error: undefined method `split' for nil:NilClass

### ISSUE THREAD

**Issue by junxy** [caskroom/homebrew-cask#5973]
```bash
$ brew cask checklinks
Error: undefined method `split' for nil:NilClass
Please report this bug:
    https://github.com/caskroom/homebrew-cask/issues
/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/underscore_supporting_uri.rb:20:in `simple_parse'
/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/underscore_supporting_uri.rb:8:in `rescue in parse'
/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/underscore_supporting_uri.rb:5:in `parse'
/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/url.rb:12:in `initialize'
/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/dsl.rb:58:in `new'
/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/dsl.rb:58:in `url'
<main>:4:in `<class:Test>'
<main>:in `<main>'
/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/source/path_base.rb:55:in `eval'
/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/source/path_base.rb:55:in `rescue in load'
/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/source/path_base.rb:52:in `load'
/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/source/tapped.rb:28:in `load'
/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask.rb:127:in `load'
/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/scopes.rb:8:in `block in all'
/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/scopes.rb:8:in `map'
/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/scopes.rb:8:in `all'
/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/cli/checklinks.rb:3:in `run'
/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/cli.rb:80:in `run_command'
/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/cli.rb:120:in `process'
/usr/local/bin/brew-cask.rb:42:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:59:in `require?'
/usr/local/Library/brew.rb:137:in `<main>'
```

```bash
$ brew cask doctor
==> OS X Version:
10.9.4
==> Hardware Architecture:
intel-64
==> Ruby Version:
2.0.0-p451
==> Ruby Path:
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
==> Homebrew Version:
0.9.5
==> Homebrew Executable Path:
/usr/local/bin/brew
==> Homebrew Cellar Path:
/usr/local/Cellar
==> Homebrew Repository Path:
/usr/local
==> Homebrew Origin:
https://github.com/Homebrew/homebrew
==> Homebrew-cask Version:
0.39.3
==> Homebrew-cask Install Location:
/usr/local/Cellar/brew-cask/0.39.3
==> Homebrew-cask Cached Downloads:
/Library/Caches/Homebrew
/Library/Caches/Homebrew/Casks
10 files (warning: run "brew cask cleanup")
971.30 megs (warning: run "brew cask cleanup")
==> Homebrew-cask Default Tap Path:
/usr/local/Library/Taps/caskroom/homebrew-cask
==> Homebrew-cask Alternate Cask Taps:
/usr/local/Library/Taps/caskroom/homebrew-fonts
/usr/local/Library/Taps/caskroom/homebrew-versions
==> Homebrew-cask Default Tap Cask Count:
1842
==> Contents of $LOAD_PATH:
/usr/local/Cellar/brew-cask/0.39.3/rubylib
/usr/local/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin13
/Library/Ruby/Site/2.0.0/universal-darwin13
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin13
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin13
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin13
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin13
==> Contents of $RUBYLIB Environment Variable:
<NONE>
==> Contents of $RUBYOPT Environment Variable:
<NONE>
==> Contents of $RUBYPATH Environment Variable:
<NONE>
==> Contents of $RBENV_VERSION Environment Variable:
<NONE>
==> Contents of $CHRUBY_VERSION Environment Variable:
<NONE>
==> Contents of $GEM_HOME Environment Variable:
<NONE>
==> Contents of $GEM_PATH Environment Variable:
<NONE>
==> Contents of $BUNDLE_PATH Environment Variable:
<NONE>
==> Contents of $PATH Environment Variable:
PATH="/usr/local/sbin:/Users/name/.rvm/gems/ruby-2.0.0-p481/bin:/Users/name/.rvm/gems/ruby-2.0.0-p481@global/bin:/Users/name/.rvm/rubies/ruby-2.0.0-p481/bin:/Library/Java/JavaVirtualMachines/jdk1.7.0_67.jdk/Contents/Home/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Users/name/.rvm/bin:/usr/local/Library/Contributions/cmd"
==> Contents of $SHELL Environment Variable:
SHELL="/bin/bash"
==> Contents of Locale Environment Variables:
LC_CTYPE="UTF-8"
==> Running As Privileged User:
No
```

**Comment by junxy** [comment]
`checklinks` is removed on `0.53.0`
```
$ brew cask checklinks
brew-cask provides a friendly homebrew-style CLI workflow for the
administration of Mac applications distributed as binaries.

!!
!! no command verb: checklinks
!!

Commands:

    audit      verifies installability of Casks
    cat        dump raw source of the given Cask to the standard output
    cleanup    cleans up cached downloads and tracker symlinks
    create     creates the given Cask and opens it in an editor
    doctor     checks for configuration issues
    edit       edits the given Cask
    fetch      downloads Cask resources to local cache
    home       opens the homepage of the given Cask
    info       displays information about the given Cask
    install    installs the given Cask
    list       with no args, lists installed Casks; given installed Casks, lists staged files
    search     searches all known Casks
    uninstall  uninstalls the given Cask
    update     a synonym for 'brew update'
    zap        zaps all files associated with the given Cask

See also "man brew-cask"
```
