### ISSUE TITLE
invalid byte sequence in UTF-8

### ISSUE THREAD

**Issue by cola1129** [caskroom/homebrew-cask#7303]
error as below while `brew cask install baiducloud`:

```
Error: invalid byte sequence in UTF-8
Please report this bug:
    https://github.com/caskroom/homebrew-cask/issues
/usr/local/Cellar/brew-cask/0.47.0/rubylib/cask/system_command.rb:96:in `_parse_plist'
/usr/local/Cellar/brew-cask/0.47.0/rubylib/cask/system_command.rb:71:in `plist'
/usr/local/Cellar/brew-cask/0.47.0/rubylib/cask/container/dmg.rb:38:in `mount!'
/usr/local/Cellar/brew-cask/0.47.0/rubylib/cask/container/dmg.rb:13:in `extract'
/usr/local/Cellar/brew-cask/0.47.0/rubylib/cask/installer.rb:89:in `extract_primary_container'
/usr/local/Cellar/brew-cask/0.47.0/rubylib/cask/installer.rb:50:in `install'
/usr/local/Cellar/brew-cask/0.47.0/rubylib/cask/cli/install.rb:20:in `block in install_casks'
/usr/local/Cellar/brew-cask/0.47.0/rubylib/cask/cli/install.rb:17:in `each'
/usr/local/Cellar/brew-cask/0.47.0/rubylib/cask/cli/install.rb:17:in `install_casks'
/usr/local/Cellar/brew-cask/0.47.0/rubylib/cask/cli/install.rb:6:in `run'
/usr/local/Cellar/brew-cask/0.47.0/rubylib/cask/cli.rb:81:in `run_command'
/usr/local/Cellar/brew-cask/0.47.0/rubylib/cask/cli.rb:121:in `process'
/usr/local/bin/brew-cask.rb:42:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:59:in `require?'
/usr/local/Library/brew.rb:142:in `<main>'
```

`brew cask doctor` as below:

```
==> OS X Version:
10.9.5
==> Hardware Architecture:
intel-64
==> Ruby Version:
2.0.0-p481
==> Ruby Path:
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
==> Homebrew Version:
0.9.5
==> Homebrew Executable Path:
/usr/local/bin/brew
==> Homebrew Cellar Path:
/usr/local/Cellar
==> Homebrew Repository Path:
/usr/local
==> Homebrew Origin:
https://github.com/Homebrew/homebrew.git
==> Homebrew-cask Version:
0.47.0
==> Homebrew-cask Install Location:
/usr/local/Cellar/brew-cask/0.47.0
/usr/local/Cellar/brew-cask/0.46.0 (error: old version. Run "brew cleanup".)
==> Homebrew-cask Staging Location:
/opt/homebrew-cask/Caskroom
==> Homebrew-cask Cached Downloads:
/Library/Caches/Homebrew
/Library/Caches/Homebrew/Casks
10 files (warning: run "brew cask cleanup")
311.76 megs (warning: run "brew cask cleanup")
==> Homebrew-cask Default Tap Path:
/usr/local/Library/Taps/caskroom/homebrew-cask
==> Homebrew-cask Alternate Cask Taps:
<NONE>
==> Homebrew-cask Default Tap Cask Count:
2064
==> Contents of $LOAD_PATH:
/usr/local/Cellar/brew-cask/0.47.0/rubylib
/usr/local/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin13
/Library/Ruby/Site/2.0.0/universal-darwin13
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin13
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin13
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin13
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin13
==> Contents of $RUBYLIB Environment Variable:
<NONE>
==> Contents of $RUBYOPT Environment Variable:
<NONE>
==> Contents of $RUBYPATH Environment Variable:
<NONE>
==> Contents of $RBENV_VERSION Environment Variable:
<NONE>
==> Contents of $CHRUBY_VERSION Environment Variable:
<NONE>
==> Contents of $GEM_HOME Environment Variable:
<NONE>
==> Contents of $GEM_PATH Environment Variable:
<NONE>
==> Contents of $BUNDLE_PATH Environment Variable:
<NONE>
==> Contents of $PATH Environment Variable:
PATH="/Users/yhwu/local/PyEnvs/versions/work@pypy-2.3.1/bin:/Users/yhwu/local/PyEnvs/shims:/usr/local/opt/pyenv/shims:/usr/local/opt/pyenv/bin:/Users/yhwu/bin:/Users/yhwu/local/bin:/usr/local/opt/coreutils/libexec/gnubin:/data0/apps/bin:/Users/yhwu/.rbenv/bin:/data0/apps/redis/bin:/data0/apps/python/bin:/data0/apps/nginx/sbin:/data0/apps/php/bin:/data0/apps/php/sbin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/Developer/Tools/Panda3D:/usr/local/Cellar/go/1.2.1/libexec/bin:/Users/yhwu/.composer/vendor/bin:/usr/local/Library/ENV/scm"
==> Contents of $SHELL Environment Variable:
SHELL="/bin/zsh"
==> Contents of Locale Environment Variables:
LC_ALL="zh_CN.UTF-8"
LC_CTYPE=""
==> Running As Privileged User:
No
```

**Comment by fritznoff** [comment]
I get the same error message when trying to install `vivaldi`:
```
$ brew cask install --debug vivaldi
==> Creating directories
==> Loading Cask definitions
==> Translating 'vivaldi' into a valid Cask source
==> Testing source class Hbc::Source::URI
==> Testing source class Hbc::Source::PathSlashRequired
==> Testing source class Hbc::Source::TappedQualified
==> Testing source class Hbc::Source::UntappedQualified
==> Testing source class Hbc::Source::Tapped
==> Success! Using source class Hbc::Source::Tapped
==> Resolved Cask URI or file source to '/usr/local/Library/Taps/caskroom/homebrew-cask/Casks/vivaldi.rb'
==> Cask instance dumps in YAML:
==> Cask instance toplevel:
--- !ruby/object:KlassPrefixVivaldi
sourcefile_path: !ruby/object:Pathname
  path: /usr/local/Library/Taps/caskroom/homebrew-cask/Casks/vivaldi.rb
token: vivaldi
==> Cask instance method 'name':
---
- Vivaldi
==> Cask instance method 'homepage':
--- https://vivaldi.com
...
==> Cask instance method 'url':
--- !ruby/object:Hbc::URL
uri: !ruby/object:URI::HTTPS
  scheme: https
  user: 
  password: 
  host: vivaldi.com
  port: 443
  path: /download/Vivaldi_TP2.1.0.118.19.dmg
  query: 
  opaque: 
  registry: 
  fragment: 
  parser: 
user_agent: 
cookies: 
referer: 
using: 
revision: 
trust_cert: 
data: 
==> Cask instance method 'appcast':
--- 
...
==> Cask instance method 'version':
--- 1.0.118.19
...
==> Cask instance method 'license':
--- !ruby/object:Hbc::DSL::License
value: :gratis
==> Cask instance method 'tags':
--- 
...
==> Cask instance method 'sha256':
--- :no_check
...
==> Cask instance method 'artifacts':
---
:app: !ruby/object:Set
  hash:
    ? - Vivaldi.app
    : true
==> Cask instance method 'caveats':
--- []
==> Cask instance method 'depends_on':
--- 
...
==> Cask instance method 'conflicts_with':
--- 
...
==> Cask instance method 'container':
--- 
...
==> Cask instance method 'gpg':
--- 
...
==> Cask instance method 'accessibility_access':
--- 
...
==> Hbc::Installer.install
==> Printing caveats
==> Downloading
==> Downloading https://vivaldi.com/download/Vivaldi_TP2.1.0.118.19.dmg
==> Calling curl with args ["https://vivaldi.com/download/Vivaldi_TP2.1.0.118.19.dmg", "-C", "1769472", "-o", "#<Pathname:/Library/Caches/Homebrew/vivaldi-1.0.118.19.dmg.incomplete>"]
==> Downloaded to -> /Library/Caches/Homebrew/vivaldi-1.0.118.19.dmg
==> Extracting primary container
==> Determining which containers to use based on filetype
==> Checking container class Hbc::Container::Pkg
==> Checking container class Hbc::Container::Ttf
==> Checking container class Hbc::Container::Otf
==> Checking container class Hbc::Container::Air
==> Checking container class Hbc::Container::Cab
==> Executing: ["/usr/bin/file", "-Izb", "--", "#<Pathname:/Library/Caches/Homebrew/vivaldi-1.0.118.19.dmg>"]
==> Checking container class Hbc::Container::Dmg
==> Executing: ["/usr/bin/hdiutil", "imageinfo", "#<Pathname:/Library/Caches/Homebrew/vivaldi-1.0.118.19.dmg>"]
==> Using container class Hbc::Container::Dmg for /Library/Caches/Homebrew/vivaldi-1.0.118.19.dmg
==> Executing: ["/usr/bin/hdiutil", "mount", "-plist", "-nobrowse", "-readonly", "-noidme", "-mountrandom", "/tmp", "#<Pathname:/Library/Caches/Homebrew/vivaldi-1.0.118.19.dmg>"]
Error: invalid byte sequence in UTF-8
==> Purging files for version 1.0.118.19 of Cask vivaldi

  Most likely, this means you have an outdated version of homebrew-cask. Please run:

      brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup

  If this doesn’t fix the problem, please report this bug:

      https://github.com/caskroom/homebrew-cask/issues

/usr/local/Cellar/brew-cask/0.53.3/rubylib/hbc/system_command.rb:98:in `_parse_plist'
/usr/local/Cellar/brew-cask/0.53.3/rubylib/hbc/system_command.rb:73:in `plist'
/usr/local/Cellar/brew-cask/0.53.3/rubylib/hbc/container/dmg.rb:38:in `mount!'
/usr/local/Cellar/brew-cask/0.53.3/rubylib/hbc/container/dmg.rb:13:in `extract'
/usr/local/Cellar/brew-cask/0.53.3/rubylib/hbc/installer.rb:110:in `extract_primary_container'
/usr/local/Cellar/brew-cask/0.53.3/rubylib/hbc/installer.rb:65:in `install'
/usr/local/Cellar/brew-cask/0.53.3/rubylib/hbc/cli/install.rb:20:in `block in install_casks'
/usr/local/Cellar/brew-cask/0.53.3/rubylib/hbc/cli/install.rb:17:in `each'
/usr/local/Cellar/brew-cask/0.53.3/rubylib/hbc/cli/install.rb:17:in `install_casks'
/usr/local/Cellar/brew-cask/0.53.3/rubylib/hbc/cli/install.rb:6:in `run'
/usr/local/Cellar/brew-cask/0.53.3/rubylib/hbc/cli.rb:79:in `run_command'
/usr/local/Cellar/brew-cask/0.53.3/rubylib/hbc/cli.rb:119:in `process'
/usr/local/Cellar/brew-cask/0.53.3/rubylib/brew-cask-cmd.rb:18:in `<main>'
```
The output of `brew cask doctor` looks clean:
```
$ brew cask doctor
==> OS X Release:
10.10
==> OS X Release with Patchlevel:
10.10.2
==> Hardware Architecture:
intel-64
==> Ruby Version:
2.0.0-p481
==> Ruby Path:
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
==> Homebrew Version:
0.9.5
==> Homebrew Executable Path:
/usr/local/bin/brew
==> Homebrew Cellar Path:
/usr/local/Cellar
==> Homebrew Repository Path:
/usr/local
==> Homebrew Origin:
https://github.com/Homebrew/homebrew
==> Homebrew-cask Version:
0.53.3
==> Homebrew-cask Install Location:
/usr/local/Cellar/brew-cask/0.53.3
==> Homebrew-cask Staging Location:
/opt/homebrew-cask/Caskroom
==> Homebrew-cask Cached Downloads:
/Library/Caches/Homebrew
/Library/Caches/Homebrew/Casks
0 files
0.00 megs
==> Homebrew-cask Default Tap Path:
/usr/local/Library/Taps/caskroom/homebrew-cask
==> Homebrew-cask Alternate Cask Taps:
<NONE>
==> Homebrew-cask Default Tap Cask Count:
2347
==> Contents of $LOAD_PATH:
/usr/local/Cellar/brew-cask/0.53.3/rubylib
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin14
/Library/Ruby/Site/2.0.0/universal-darwin14
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin14
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin14
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin14
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin14
==> Contents of $RUBYLIB Environment Variable:
<NONE>
==> Contents of $RUBYOPT Environment Variable:
<NONE>
==> Contents of $RUBYPATH Environment Variable:
<NONE>
==> Contents of $RBENV_VERSION Environment Variable:
<NONE>
==> Contents of $CHRUBY_VERSION Environment Variable:
<NONE>
==> Contents of $GEM_HOME Environment Variable:
<NONE>
==> Contents of $GEM_PATH Environment Variable:
<NONE>
==> Contents of $BUNDLE_PATH Environment Variable:
<NONE>
==> Contents of $PATH Environment Variable:
PATH="/Users/fritznoff/.rvm/gems/ruby-2.1.5/bin:/Users/fritznoff/.rvm/gems/ruby-2.1.5@global/bin:/Users/fritznoff/.rvm/rubies/ruby-2.1.5/bin:/Users/fritznoff/.perl5/perlbrew/bin:/Users/fritznoff/.perl5/perlbrew/perls/perl-5.18.2/bin:/Users/fritznoff/.pyenv/shims:/usr/local/sbin:/usr/local/bin:/usr/local/opt/coreutils/libexec/gnubin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/fritznoff/.rvm/bin:/usr/local/Library/Taps/homebrew/homebrew-boneyard/cmd:/usr/local/Library/ENV/scm"
==> Contents of $SHELL Environment Variable:
SHELL="/usr/local/bin/bash"
==> Contents of Locale Environment Variables:
LANG="de_DE.UTF-8"
==> Running As Privileged User:
No
```

**Comment by vitorgalvao** [comment]
If this is still an issue, please open a new one with any new information (trying to get rid of old irrelevant ones).
