### ISSUE TITLE
xquartz cask is broken

### ISSUE THREAD

**Issue by jasonhemann** [caskroom/homebrew-cask#8164]
The following is the output of `$ brew cask install xquartz`

```bash
==> installer: Package name is XQuartz 2.7.7
==> installer: Installing at base path /
==> installer: The install was successful.
==> Sorry, try again.
```

The 'Sorry' message aside, the installation seems to have worked. However, when I 

```bash
$ ssh -X <somewhere>
<enter password>
$ xeyes
Error: Can't open display: 
$
```

Not sure what the cause of this is.

**Comment by ssbarnea** [comment]
Still broken due to other reasons:
```
sorins@oMac ~ $ brew cask install xquartz
==> Downloading https://xquartz.macosforge.org/downloads/SL/XQuartz-2.7.7.dmg

curl: (60) SSL certificate problem: Invalid certificate chain
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
Error: Download failed on Cask 'xquartz' with message: Download failed: https://xquartz.macosforge.org/downloads/SL/XQuartz-2.7.7.dmg
```

**Comment by vitorgalvao** [comment]
@ssbarnea Can’t reproduce. Likely temporary.

**Comment by ssbarnea** [comment]
@vitorgalvao I agree, now it works so I guess it was a temporary issue. Thanks

BTW, I am using brew and cask more than usually now because I just switched to a new computer. For some reason it seems that the downloading is very slow, slower than my normal download experience. If you know any reason why curl could be considerably slower than the browser on downloading stuff let me know. Is weird because this is the first time when I encounter this and this is a new MBP, same network,...

**Comment by vitorgalvao** [comment]
It may be something on your curl’s configuration (do you have a custom `.curlrc`)? Either way, please don’t derail the issue and open a new one. This is a different matter, and we shouldn’t be mixing them.

**Comment by arvindraghavan** [comment]
Still broken I think. This is what I get:

```
arvindraghavan@Arvinds-MacBook-Pro:~$ brew cask install xquartz
Error: undefined method `cask' for main:Object
Please report this bug:
    https://github.com/caskroom/homebrew-cask/issues
/usr/local/Library/Taps/caskroom/homebrew-cask/Casks/xquartz.rb:1:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Cellar/brew-cask/0.35.0/rubylib/cask/source/path.rb:13:in `load'
/usr/local/Cellar/brew-cask/0.35.0/rubylib/cask/source/tapped.rb:24:in `load'
/usr/local/Cellar/brew-cask/0.35.0/rubylib/cask.rb:118:in `load'
/usr/local/Cellar/brew-cask/0.35.0/rubylib/cask/cli/install.rb:9:in `block in run'
/usr/local/Cellar/brew-cask/0.35.0/rubylib/cask/cli/install.rb:6:in `each'
/usr/local/Cellar/brew-cask/0.35.0/rubylib/cask/cli/install.rb:6:in `run'
/usr/local/Cellar/brew-cask/0.35.0/rubylib/cask/cli.rb:57:in `run_command'
/usr/local/Cellar/brew-cask/0.35.0/rubylib/cask/cli.rb:72:in `process'
/usr/local/bin/brew-cask.rb:6:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:58:in `require?'
/usr/local/Library/brew.rb:141:in `<main>'
```

**Comment by vitorgalvao** [comment]
@arvindraghavan Your problem is unrelated. You’re using an old version of homebrew-cask. Please `brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup` and try again.

**Comment by arvindraghavan** [comment]
@vitorgalvao, thanks a lot! I did try to update cask first, but simply tried `brew update`, which doesn't update cask. I was able to install xquartz correctly.

**Comment by vitorgalvao** [comment]
Problem seems to be gone (you might need to restart to get `xeyes` working, though, so that should also fix other things). If that doesn’t work, please report back @jasonhemann.

**Comment by OutsourcedGuru** [comment]
I thought I might kill some time today to work on the code behind phonegap-app-desktop and their installation instructions had me run a series of commands such as:  brew cask install Caskroom/cask/xquartz

...which then failed the first time with "Error: Cask 'xquartz' definition is invalid: Bad header line: parse failed".  I wouldn't call this a great error message but at least Google brought me here.  So I then ran "brew uninstall --force brew-cask; brew update" and repeated the first command above.  After entering my password it seemed to hang for more than five minutes so I eventually did a Ctrl-C.  Tried to repeat the install command only to find that it thinks that I need to run a "--force" version this time, which I did.  Again, it's taking longer then ten minutes.

Pointing at your README.md, all this is supposed to be easier than dragging the DMG file sideways, right?

So, reading the logs I see that the DMG for quartz is already downloaded so I use Finder to double-click it, then run the PKG to perform the standard installation.  It just finished and all that came with a progress meter which advanced throughout the install so that I didn't lose confidence in the script or process.

Guys, I'd suggest a progress meter or spinning (- | / \) character for those of us who think by default that if our computer hasn't said anything in ten minutes then a script must therefore be broken.

**Comment by dsifford** [comment]
^This guy get's it. Progress indicator is sorely needed for this

**Comment by powerwlsl** [comment]
^ i just did the same thing. cancelled `brew cask install` twice and ended up installing via the dmg manually. can someone confirm it actually completes if you wait it out?

**Comment by commitay** [comment]
```
$ brew cask fetch xquartz
==> Downloading external files for Cask xquartz
==> Downloading https://dl.bintray.com/xquartz/downloads/XQuartz-2.7.11.dmg
######################################################################## 100.0%
==> Verifying checksum for Cask xquartz
==> Success! Downloaded to -> /Users/commitay/Library/Caches/Homebrew/Cask/xquartz--2.7.11.dmg
$ time brew cask install --verbose xquartz
==> Satisfying dependencies
==> Downloading https://dl.bintray.com/xquartz/downloads/XQuartz-2.7.11.dmg
Already downloaded: /Users/commitay/Library/Caches/Homebrew/Cask/xquartz--2.7.11.dmg
==> Verifying checksum for Cask xquartz
==> Installing Cask xquartz
==> Running installer for xquartz; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
Password:
==> installer: Package name is XQuartz 2.7.11
==> installer: Installing at base path /
==> installer:PHASE:Preparing for installation…
==> installer:PHASE:Preparing the disk…
==> installer:PHASE:Preparing XQuartz 2.7.11…
==> installer:PHASE:Waiting for other installations to complete…
==> installer:PHASE:Configuring the installation…
==> installer:STATUS:
==> installer:%5.233398
==> installer:PHASE:Writing files…
==> installer:%11.541199
==> installer:PHASE:Writing files…
==> installer:%15.657996
==> installer:PHASE:Writing files…
==> installer:%21.833190
==> installer:PHASE:Writing files…
==> installer:%28.008384
==> installer:PHASE:Writing files…
==> installer:PHASE:Writing files…
==> installer:PHASE:Writing files…
==> installer:%30.066782
==> installer:PHASE:Writing files…
==> installer:PHASE:Writing files…
==> installer:PHASE:Writing files…
==> installer:%32.125181
==> installer:PHASE:Writing files…
==> installer:PHASE:Writing files…
==> installer:%34.183579
==> installer:PHASE:Writing files…
==> installer:%36.241977
==> installer:PHASE:Writing files…
==> installer:PHASE:Writing files…
==> installer:%38.300375
==> installer:PHASE:Writing files…
==> installer:PHASE:Writing files…
==> installer:PHASE:Writing files…
==> installer:PHASE:Writing files…
==> installer:PHASE:Writing files…
==> installer:PHASE:Writing files…
==> installer:PHASE:Writing files…
==> installer:%84.090028
==> installer:PHASE:Running package scripts…
==> installer:%85.112759
==> installer:PHASE:Running package scripts…
==> installer:%85.643531
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:PHASE:Running package scripts…
==> installer:%85.988484
==> installer:PHASE:Writing package receipts…
==> installer:%95.833852
==> installer:PHASE:Cleaning up…
==> installer:PHASE:Validating packages…
==> installer:%97.750000
==> installer:STATUS:Running installer actions…
==> installer:STATUS:
==> installer:PHASE:Finishing the Installation…
==> installer:STATUS:
==> installer:%100.000000
==> installer:PHASE:The software was successfully installed.
==> installer: The install was successful.
🍺  xquartz was successfully installed!

real	2m52.458s
user	0m14.470s
sys	0m1.584s

```
