### ISSUE TITLE
"Error: no implicit conversion of nil into String" from "brew cask install launchy"

### ISSUE THREAD

**Issue by msabramo** [caskroom/homebrew-cask#8629]
```
$ brew cask install launchy
==> Downloading http://www.launchy.net/downloads/mac/Launchy2.5.dmg
Already downloaded: /Library/Caches/Homebrew/launchy-2.5.dmg
Error: no implicit conversion of nil into String
Please report this bug:
    https://github.com/caskroom/homebrew-cask/issues
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/digest.rb:44:in `initialize'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/digest.rb:44:in `open'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/digest.rb:44:in `file'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/digest.rb:29:in `file'
/usr/local/Cellar/brew-cask/0.43.1/rubylib/cask/download.rb:41:in `block in _check_sums'
/usr/local/Cellar/brew-cask/0.43.1/rubylib/cask/download.rb:39:in `each'
/usr/local/Cellar/brew-cask/0.43.1/rubylib/cask/download.rb:39:in `_check_sums'
/usr/local/Cellar/brew-cask/0.43.1/rubylib/cask/download.rb:32:in `perform'
/usr/local/Cellar/brew-cask/0.43.1/rubylib/cask/installer.rb:72:in `download'
/usr/local/Cellar/brew-cask/0.43.1/rubylib/cask/installer.rb:49:in `install'
/usr/local/Cellar/brew-cask/0.43.1/rubylib/cask/cli/install.rb:20:in `block in install_casks'
/usr/local/Cellar/brew-cask/0.43.1/rubylib/cask/cli/install.rb:17:in `each'
/usr/local/Cellar/brew-cask/0.43.1/rubylib/cask/cli/install.rb:17:in `install_casks'
/usr/local/Cellar/brew-cask/0.43.1/rubylib/cask/cli/install.rb:6:in `run'
/usr/local/Cellar/brew-cask/0.43.1/rubylib/cask/cli.rb:81:in `run_command'
/usr/local/Cellar/brew-cask/0.43.1/rubylib/cask/cli.rb:121:in `process'
/usr/local/bin/brew-cask.rb:42:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:58:in `require?'
/usr/local/Library/brew.rb:141:in `<main>'
```

**Comment by ndr-qef** [comment]
Hello @msabramo. You are encountering #7946, which is known to affect old versions of `brew cask`. Upgrading should fix the issue:

```
brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup
```

**Comment by msabramo** [comment]
That worked great! Thanks!!!
