### ISSUE TITLE
Uninitialized constant Hbc::Utils (NameError)

### ISSUE THREAD

**Issue by MalcolmK** [caskroom/homebrew-cask#8645]
This morning I updated my homebrew packages, but when I try to use the brew-cask package, I get this error:

```
/usr/local/Cellar/brew-cask/0.52.0/rubylib/vendor/homebrew-fork/global.rb:31:in `<top (required)>': uninitialized constant Hbc::Utils (NameError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Cellar/brew-cask/0.52.0/rubylib/brew-cask-cmd.rb:14:in `<main>'
```

What can I do?

**Comment by muescha** [comment]
Can you explain how you solved this error?

**Comment by MalcolmK** [comment]
Yes sure, just by using `brew cask` instead of `brew-cask` ;-)

**Comment by rolandwalker** [comment]
Ah, but that's still a bug.  `brew-cask` should work.

**Comment by MalcolmK** [comment]
@rolandwalker That's true, but it seems to work again :) Thnx!
