### ISSUE TITLE
Error installing app after interrupting post download

### ISSUE THREAD

**Issue by matkam** [caskroom/homebrew-cask#8672]
Installation of an app seemed to be frozen after it was downloaded. After interrupting the the cask install and starting it again, I got an error:

```
➜  brew cask install liteide
==> Downloading http://downloads.sourceforge.net/project/liteide/X25.2/liteidex25.2.macosx.zip
######################################################################## 100.0%

^C
➜  brew cask install liteide
==> Downloading http://downloads.sourceforge.net/project/liteide/X25.2/liteidex25.2.macosx.zip
Already downloaded: /Library/Caches/Homebrew/liteide-25.2.zip
Error: no implicit conversion of nil into String
Please report this bug:
    https://github.com/caskroom/homebrew-cask/issues
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/digest.rb:44:in `initialize'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/digest.rb:44:in `open'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/digest.rb:44:in `file'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/digest.rb:29:in `file'
/usr/local/Cellar/brew-cask/0.47.0/rubylib/cask/download.rb:41:in `block in _check_sums'
/usr/local/Cellar/brew-cask/0.47.0/rubylib/cask/download.rb:39:in `each'
/usr/local/Cellar/brew-cask/0.47.0/rubylib/cask/download.rb:39:in `_check_sums'
/usr/local/Cellar/brew-cask/0.47.0/rubylib/cask/download.rb:32:in `perform'
/usr/local/Cellar/brew-cask/0.47.0/rubylib/cask/installer.rb:72:in `download'
/usr/local/Cellar/brew-cask/0.47.0/rubylib/cask/installer.rb:49:in `install'
/usr/local/Cellar/brew-cask/0.47.0/rubylib/cask/cli/install.rb:20:in `block in install_casks'
/usr/local/Cellar/brew-cask/0.47.0/rubylib/cask/cli/install.rb:17:in `each'
/usr/local/Cellar/brew-cask/0.47.0/rubylib/cask/cli/install.rb:17:in `install_casks'
/usr/local/Cellar/brew-cask/0.47.0/rubylib/cask/cli/install.rb:6:in `run'
/usr/local/Cellar/brew-cask/0.47.0/rubylib/cask/cli.rb:81:in `run_command'
/usr/local/Cellar/brew-cask/0.47.0/rubylib/cask/cli.rb:121:in `process'
/usr/local/bin/brew-cask.rb:42:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:58:in `require?'
/usr/local/Library/brew.rb:142:in `<main>'
```

**Comment by vitorgalvao** [comment]
You’re using an old version of homebrew-cask. Please `brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup` and try again.
