### ISSUE TITLE
Error: no implicit conversion of nil into String

### ISSUE THREAD

**Issue by bukzor** [caskroom/homebrew-cask#8673]
```
==> Downloading http://live.yworks.com/yed-downloads/yEd-3.14_with-JRE8.dmg
Already downloaded: /Library/Caches/Homebrew/yed-3.14.dmg
Error: no implicit conversion of nil into String
Please report this bug:
    https://github.com/caskroom/homebrew-cask/issues
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/digest.rb:44:in `initialize'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/digest.rb:44:in `open'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/digest.rb:44:in `file'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/digest.rb:29:in `file'
/Users/buck/prefices/brew/Cellar/brew-cask/0.46.0/rubylib/cask/download.rb:41:in `block in _check_sums'
/Users/buck/prefices/brew/Cellar/brew-cask/0.46.0/rubylib/cask/download.rb:39:in `each'
/Users/buck/prefices/brew/Cellar/brew-cask/0.46.0/rubylib/cask/download.rb:39:in `_check_sums'
/Users/buck/prefices/brew/Cellar/brew-cask/0.46.0/rubylib/cask/download.rb:32:in `perform'
/Users/buck/prefices/brew/Cellar/brew-cask/0.46.0/rubylib/cask/installer.rb:72:in `download'
/Users/buck/prefices/brew/Cellar/brew-cask/0.46.0/rubylib/cask/installer.rb:49:in `install'
/Users/buck/prefices/brew/Cellar/brew-cask/0.46.0/rubylib/cask/cli/install.rb:20:in `block in install_casks'
/Users/buck/prefices/brew/Cellar/brew-cask/0.46.0/rubylib/cask/cli/install.rb:17:in `each'
/Users/buck/prefices/brew/Cellar/brew-cask/0.46.0/rubylib/cask/cli/install.rb:17:in `install_casks'
/Users/buck/prefices/brew/Cellar/brew-cask/0.46.0/rubylib/cask/cli/install.rb:6:in `run'
/Users/buck/prefices/brew/Cellar/brew-cask/0.46.0/rubylib/cask/cli.rb:81:in `run_command'
/Users/buck/prefices/brew/Cellar/brew-cask/0.46.0/rubylib/cask/cli.rb:121:in `process'
/Users/buck/prefices/brew/bin/brew-cask.rb:42:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Users/buck/prefices/brew/Library/brew.rb:58:in `require?'
/Users/buck/prefices/brew/Library/brew.rb:142:in `<main>'
```

**Comment by vitorgalvao** [comment]
You’re using an old version of homebrew-cask. Please `brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup` and try again.
