### ISSUE TITLE
[Firefox] Error: undefined method `extname' for 0:Fixnum

### ISSUE THREAD

**Issue by gogotanaka** [caskroom/homebrew-cask#8697]
hi, it happened while I tried to install firefox.

    $ brew cask install firefox

```
==> Downloading https://download.mozilla.org/?product=firefox-latest&os=osx&lang=en-US
######################################################################## 100.0%
Error: undefined method `extname' for 0:Fixnum
Please report this bug:
    https://github.com/caskroom/homebrew-cask/issues
/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/container/criteria.rb:46:in `extension'
/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/container/pkg.rb:3:in `me?'
/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/container.rb:50:in `block in for_path'
/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/container.rb:48:in `each'
/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/container.rb:48:in `find'
/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/container.rb:48:in `for_path'
/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/installer.rb:65:in `extract_primary_container'
/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/installer.rb:32:in `install'
/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/cli/install.rb:20:in `block in install_casks'
/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/cli/install.rb:17:in `each'
/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/cli/install.rb:17:in `install_casks'
/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/cli/install.rb:6:in `run'
/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/cli.rb:80:in `run_command'
/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/cli.rb:120:in `process'
/usr/local/bin/brew-cask.rb:42:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:59:in `require?'
/usr/local/Library/brew.rb:142:in `<main>'
```

**Comment by iggyvolz** [comment]
You’re using an old version of homebrew-cask. Please brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup and try again.

See #8673.

**Comment by gogotanaka** [comment]
@iggyvolz thank you!
