### ISSUE TITLE
Error installing Skitch on Yosemite

### ISSUE THREAD

**Issue by al-the-x** [caskroom/homebrew-cask#8726]
Tried installing Skitch on Yosemite via `brew cask install skitch` without success. The archive file downloads successfully, but then the install just hangs indefinitely with no further feedback. Canceling the install and attempting the same command again produces an error:

```sh
$ cask install skitch                                                                                                      jobs:1
==> Downloading http://cdn1.evernote.com/skitch/mac/release/Skitch-2.7.6.zip
Already downloaded: /Library/Caches/Homebrew/skitch-2.7.6.zip
Error: no implicit conversion of nil into String
Please report this bug:
    https://github.com/caskroom/homebrew-cask/issues
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/digest.rb:44:in `initialize'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/digest.rb:44:in `open'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/digest.rb:44:in `file'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/digest.rb:29:in `file'
/usr/local/Cellar/brew-cask/0.48.0/rubylib/cask/download.rb:41:in `block in _check_sums'
/usr/local/Cellar/brew-cask/0.48.0/rubylib/cask/download.rb:39:in `each'
/usr/local/Cellar/brew-cask/0.48.0/rubylib/cask/download.rb:39:in `_check_sums'
/usr/local/Cellar/brew-cask/0.48.0/rubylib/cask/download.rb:32:in `perform'
/usr/local/Cellar/brew-cask/0.48.0/rubylib/cask/installer.rb:72:in `download'
/usr/local/Cellar/brew-cask/0.48.0/rubylib/cask/installer.rb:49:in `install'
/usr/local/Cellar/brew-cask/0.48.0/rubylib/cask/cli/install.rb:20:in `block in install_casks'
/usr/local/Cellar/brew-cask/0.48.0/rubylib/cask/cli/install.rb:17:in `each'
/usr/local/Cellar/brew-cask/0.48.0/rubylib/cask/cli/install.rb:17:in `install_casks'
/usr/local/Cellar/brew-cask/0.48.0/rubylib/cask/cli/install.rb:6:in `run'
/usr/local/Cellar/brew-cask/0.48.0/rubylib/cask/cli.rb:81:in `run_command'
/usr/local/Cellar/brew-cask/0.48.0/rubylib/cask/cli.rb:121:in `process'
/usr/local/bin/brew-cask.rb:42:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:59:in `require?'
/usr/local/Library/brew.rb:142:in `<main>'
```

I deleted the offending archive file and tried multiple times to install with repeatable results. Am I doin' it wrong? Regardless, the line: `Error: no implicit conversion of nil into String` on repeat installs seems like a bug. Something else going on here?

**Comment by vitorgalvao** [comment]
You’re using an old version of homebrew-cask. Please `brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup` and try again.

Please [always do this before opening new issues](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md#reporting-bugs).
