### ISSUE TITLE
Error when installing macdown 0.4.1

### ISSUE THREAD

**Issue by colindean** [caskroom/homebrew-cask#8731]
I'd previously installed one from the 2.x series, and it went in without a hitch. I realized it was out of date, as was my homebrew/cask stuff, so I removed it, updated, and now I'm stuck.

When I install it cleanly, it freezes after downloading:

```
± (master *%) $ brew cask install macdown
==> Downloading http://macdown.uranusjr.com/download/v0.4.1/
######################################################################## 100.0%
```

So I Ctrl+C to kill it, then run again:

```
± (master *%) $ brew cask install macdown
==> Downloading http://macdown.uranusjr.com/download/v0.4.1/
Already downloaded: /Library/Caches/Homebrew/macdown-0.4.1.1
Error: no implicit conversion of nil into String
Please report this bug:
    https://github.com/caskroom/homebrew-cask/issues
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/digest.rb:44:in `initialize'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/digest.rb:44:in `open'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/digest.rb:44:in `file'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/digest.rb:29:in `file'
/usr/local/Cellar/brew-cask/0.44.0/rubylib/cask/download.rb:41:in `block in _check_sums'
/usr/local/Cellar/brew-cask/0.44.0/rubylib/cask/download.rb:39:in `each'
/usr/local/Cellar/brew-cask/0.44.0/rubylib/cask/download.rb:39:in `_check_sums'
/usr/local/Cellar/brew-cask/0.44.0/rubylib/cask/download.rb:32:in `perform'
/usr/local/Cellar/brew-cask/0.44.0/rubylib/cask/installer.rb:72:in `download'
/usr/local/Cellar/brew-cask/0.44.0/rubylib/cask/installer.rb:49:in `install'
/usr/local/Cellar/brew-cask/0.44.0/rubylib/cask/cli/install.rb:20:in `block in install_casks'
/usr/local/Cellar/brew-cask/0.44.0/rubylib/cask/cli/install.rb:17:in `each'
/usr/local/Cellar/brew-cask/0.44.0/rubylib/cask/cli/install.rb:17:in `install_casks'
/usr/local/Cellar/brew-cask/0.44.0/rubylib/cask/cli/install.rb:6:in `run'
/usr/local/Cellar/brew-cask/0.44.0/rubylib/cask/cli.rb:81:in `run_command'
/usr/local/Cellar/brew-cask/0.44.0/rubylib/cask/cli.rb:121:in `process'
/usr/local/bin/brew-cask.rb:42:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:58:in `require?'
/usr/local/Library/brew.rb:142:in `<main>'
```

I restore normalcy with `rm -rf /Library/Caches/Homebrew/macdown-0.4.1.1` and try it again, same thing happens.

One thing I notice is that the cache directory is `macdown-0.4.1.1` instead of `macdown-0.4.1`, like how I'd expect given the version number in the [macdown cask](https://github.com/caskroom/homebrew-cask/blob/master/Casks/macdown.rb).

[Doctor output](http://pastebin.com/PKjiPmBe).

**Comment by vitorgalvao** [comment]
You’re using an old version of homebrew-cask. Please `brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup` and try again.

Please [always do this before opening new issues](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md#reporting-bugs).

**Comment by colindean** [comment]
Damn. I thought I'd done that, but looking through my history, I just updated the taps without upgrading :-/ Sorry.
