### ISSUE TITLE
private-internet-access fails

### ISSUE THREAD

**Issue by austinpray** [caskroom/homebrew-cask#8756]
```bash
➜  ~  brew doctor
Your system is ready to brew.
```

```
➜  ~  ruby -v
ruby 2.0.0p353 (2013-11-22 revision 43784) [x86_64-darwin13.0.0]
```

```bash
➜  ~  brew cask install private-internet-access
Error: wrong number of arguments (1 for 0) while loading '/usr/local/Library/Taps/caskroom/homebrew-cask/Casks/private-internet-access.rb'
Please report this bug:
    https://github.com/caskroom/homebrew-cask/issues
<main>:5:in `name'
<main>:5:in `<class:PrivateInternetAccess>'
<main>:in `<main>'
/usr/local/Cellar/brew-cask/0.45.0/rubylib/cask/source/path_base.rb:55:in `eval'
/usr/local/Cellar/brew-cask/0.45.0/rubylib/cask/source/path_base.rb:55:in `rescue in load'
/usr/local/Cellar/brew-cask/0.45.0/rubylib/cask/source/path_base.rb:52:in `load'
/usr/local/Cellar/brew-cask/0.45.0/rubylib/cask/source/tapped.rb:28:in `load'
/usr/local/Cellar/brew-cask/0.45.0/rubylib/cask.rb:124:in `load'
/usr/local/Cellar/brew-cask/0.45.0/rubylib/cask/cli/install.rb:19:in `block in install_casks'
/usr/local/Cellar/brew-cask/0.45.0/rubylib/cask/cli/install.rb:17:in `each'
/usr/local/Cellar/brew-cask/0.45.0/rubylib/cask/cli/install.rb:17:in `install_casks'
/usr/local/Cellar/brew-cask/0.45.0/rubylib/cask/cli/install.rb:6:in `run'
/usr/local/Cellar/brew-cask/0.45.0/rubylib/cask/cli.rb:81:in `run_command'
/usr/local/Cellar/brew-cask/0.45.0/rubylib/cask/cli.rb:121:in `process'
/usr/local/bin/brew-cask.rb:42:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:58:in `require?'
/usr/local/Library/brew.rb:142:in `<main>'
```

**Comment by vitorgalvao** [comment]
You’re using an old version of homebrew-cask. Please `brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup` and try again.

Please [always do this before opening new issues](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md#reporting-bugs).

**Comment by austinpray** [comment]
Haha oh man. I was running into this issue my desktop computer I never use. I did this:

```
brew update && brew cleanup && brew cask cleanup
```

Like 10 times before making the issue. I'm sure you see immediately why I was still having trouble.

Thanks :+1:

**Comment by tconroy** [comment]
Hm. I'm struggling to install PIA as well, have run all the commands posted above. Currently getting this:

```
$ brew cask install private-internet-access
==> Downloading https://www.privateinternetaccess.com/installer/installer_osx.dmg
######################################################################## 100.0%
==> No checksum defined for Cask private-internet-access, skipping verification
==> Running installer script Private Internet Access Installer.app/Contents/MacOS/runner.sh
Password:
==>
==> No matching processes were found
==> LSOpenURLsWithRole() failed with error -10810 for the file /Applications/Private Internet Access.app.
🍺  private-internet-access staged at '/opt/homebrew-cask/Caskroom/private-internet-access/latest' (74 files, 21M)
```

Any ideas?
