### ISSUE TITLE
Issue with subl (No such file or directory)

### ISSUE THREAD

**Issue by wickedsp1d3r** [caskroom/homebrew-cask#8788]
```
$ brew cask edit x

Error: No such file or directory - subl -w

  Most likely, this means you have an outdated version of homebrew-cask. Please run:

      brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup

  If this doesn’t fix the problem, please report this bug:

      https://github.com/caskroom/homebrew-cask/issues

/usr/local/Cellar/brew-cask/0.52.1/rubylib/hbc/utils.rb:138:in `exec'
/usr/local/Cellar/brew-cask/0.52.1/rubylib/hbc/utils.rb:138:in `exec_editor'
/usr/local/Cellar/brew-cask/0.52.1/rubylib/hbc/cli/edit.rb:18:in `exec_editor'
/usr/local/Cellar/brew-cask/0.52.1/rubylib/hbc/cli/edit.rb:12:in `run'
/usr/local/Cellar/brew-cask/0.52.1/rubylib/hbc/cli.rb:79:in `run_command'
/usr/local/Cellar/brew-cask/0.52.1/rubylib/hbc/cli.rb:119:in `process'
/usr/local/Cellar/brew-cask/0.52.1/rubylib/brew-cask-cmd.rb:18:in `<main>'
```

This has been present since upgrading to the latest version.

**Comment by vitorgalvao** [comment]
Isn’t `subl` a way to call Sublime Text from the command line? That shouldn’t give such an error. Have you reinstalled Sublime Text? Does `subl -w` work in other contexts?

**Comment by wickedsp1d3r** [comment]
Yes it is. I tried to reinstall Sublime Text (version 3 from homebrew-versions). No change.

It should be there.
```
$ which subl
/usr/local/bin/subl
```

For example when issuing `brew edit x`, it is working fine.

**Comment by vitorgalvao** [comment]
This is really weird. What does `brew cask doctor` give you?

**Comment by wickedsp1d3r** [comment]
```
$ brew cask doctor
==> OS X Release:
10.10
==> OS X Point Release:
10.10.1
==> Hardware Architecture:
intel-64
==> Ruby Version:
2.0.0-p481
==> Ruby Path:
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
==> Homebrew Version:
0.9.5
==> Homebrew Executable Path:
/usr/local/bin/brew
==> Homebrew Cellar Path:
/usr/local/Cellar
==> Homebrew Repository Path:
/usr/local
==> Homebrew Origin:
https://github.com/Homebrew/homebrew
==> Homebrew-cask Version:
0.52.1
==> Homebrew-cask Install Location:
/usr/local/Cellar/brew-cask/0.52.1
==> Homebrew-cask Staging Location:
/opt/homebrew-cask/Caskroom
==> Homebrew-cask Cached Downloads:
/Library/Caches/Homebrew
/Library/Caches/Homebrew/Casks
0 files
0.00 megs
==> Homebrew-cask Default Tap Path:
/usr/local/Library/Taps/caskroom/homebrew-cask
==> Homebrew-cask Alternate Cask Taps:
/usr/local/Library/Taps/caskroom/homebrew-versions
==> Homebrew-cask Default Tap Cask Count:
2218
==> Contents of $LOAD_PATH:
/usr/local/Cellar/brew-cask/0.52.1/rubylib
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin14
/Library/Ruby/Site/2.0.0/universal-darwin14
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin14
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin14
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin14
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin14
==> Contents of $RUBYLIB Environment Variable:
<NONE>
==> Contents of $RUBYOPT Environment Variable:
<NONE>
==> Contents of $RUBYPATH Environment Variable:
<NONE>
==> Contents of $RBENV_VERSION Environment Variable:
<NONE>
==> Contents of $CHRUBY_VERSION Environment Variable:
<NONE>
==> Contents of $GEM_HOME Environment Variable:
<NONE>
==> Contents of $GEM_PATH Environment Variable:
<NONE>
==> Contents of $BUNDLE_PATH Environment Variable:
<NONE>
==> Contents of $PATH Environment Variable:
PATH="/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/Library/ENV/scm"
==> Contents of $SHELL Environment Variable:
SHELL="/usr/local/bin/bash"
==> Contents of Locale Environment Variables:
LANG="fi_FI.UTF-8"
==> Running As Privileged User:
No
```

**Comment by ndr-qef** [comment]
We lost the ability to parse arguments from the editor variables in ENV when we merged #8611. The most immediate solution would be to reinstate Homebrew's `safe_exec`.

**Comment by phinze** [comment]
Good catch @ndr-qef - I think we just need to add `PATH` to the list of env variables we snag, no?

**Comment by phinze** [comment]
Oh nm I was misreading 774eae75a86e0393379b611e5d6aea612276bff6 ... standby for more more eyeball parsing... :grin:

**Comment by phinze** [comment]
Yeah I'm +1 for a straight revert for now to fix the issue and then we can re-evaluate the goal of the commit.

**Comment by rolandwalker** [comment]
The intent was to remove expansion of environment variables within the exec, but it seems I also removed the (dubious but standard) ability to split `$VISUAL` on whitespace.  Something like following should recover the split on whitespace without the `/bin/sh` contortion:
```ruby
exec(editor.split.concat(args))
```

The terms `%w{mate edit vim /usr/bin/vim}` were supposed to be mapped through the `which` method, but they aren't.  Looks like I was having a bad day.

**Comment by ndr-qef** [comment]
That should work as well. I will amend the open PR.
