### ISSUE TITLE
KiCad: "No implicit conversion of nil into String" in digest.rb

### ISSUE THREAD

**Issue by Crazor** [caskroom/homebrew-cask#8797]
I started installing KiCad, but the process hung up after downloading 100%. After a few minutes, I hit Ctrl+C and retried. Now I'm getting

```
 % brew cask install kicad                                                    ~
==> Downloading http://www.mdx4.org/uploads/kicad/Kicad-product-2014-02-26.zip
Already downloaded: /Library/Caches/Homebrew/kicad-2014-02-26.zip
Error: no implicit conversion of nil into String
Please report this bug:
    https://github.com/caskroom/homebrew-cask/issues
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/digest.rb:44:in `initialize'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/digest.rb:44:in `open'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/digest.rb:44:in `file'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/digest.rb:29:in `file'
/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/download.rb:41:in `block in _check_sums'
/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/download.rb:39:in `each'
/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/download.rb:39:in `_check_sums'
/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/download.rb:32:in `perform'
/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/installer.rb:54:in `download'
/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/installer.rb:31:in `install'
/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/cli/install.rb:20:in `block in install_casks'
/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/cli/install.rb:17:in `each'
/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/cli/install.rb:17:in `install_casks'
/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/cli/install.rb:6:in `run'
/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/cli.rb:80:in `run_command'
/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/cli.rb:120:in `process'
/usr/local/bin/brew-cask.rb:42:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:58:in `require?'
/usr/local/Library/brew.rb:142:in `<main>
```

After manually removing `/Library/Caches/Homebrew/kicad-2014-02-26.zip` (because brew cask cleanup didn't help), I could retry the installation, but the problem persists: Hangs at 100% download, same error upon retrying, and downloading again after removing the zip.

**Comment by ndr-qef** [comment]
Hello @Crazor. You are simply running a very old version of homebrew-cask, which is affected by #7946. Upgrading should fix the issue:

```shell
brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup
```
