### ISSUE TITLE
Error running brew cask list

### ISSUE THREAD

**Issue by unyouthnzadmin** [caskroom/homebrew-cask#8837]
I'm running Yosemite, have a couple things installed, (not entirely sure about the whole list for obvious reasons), Macbook Air. Not sure what changed, might have been Yosemite update, playing with rails, or something else. Let me know if you need anything.

```
Error: wrong number of arguments (1 for 0) while loading '/usr/local/Library/Taps/caskroom/homebrew-cask/Casks/dash.rb'
Please report this bug:
    https://github.com/caskroom/homebrew-cask/issues
<main>:6:in `name'
<main>:6:in `<class:Dash>'
<main>:in `<main>'
/usr/local/Cellar/brew-cask/0.45.0/rubylib/cask/source/path_base.rb:55:in `eval'
/usr/local/Cellar/brew-cask/0.45.0/rubylib/cask/source/path_base.rb:55:in `rescue in load'
/usr/local/Cellar/brew-cask/0.45.0/rubylib/cask/source/path_base.rb:52:in `load'
/usr/local/Cellar/brew-cask/0.45.0/rubylib/cask.rb:124:in `load'
/usr/local/Cellar/brew-cask/0.45.0/rubylib/cask/scopes.rb:55:in `block in installed'
/usr/local/Cellar/brew-cask/0.45.0/rubylib/cask/scopes.rb:49:in `map'
/usr/local/Cellar/brew-cask/0.45.0/rubylib/cask/scopes.rb:49:in `installed'
/usr/local/Cellar/brew-cask/0.45.0/rubylib/cask/cli/list.rb:52:in `list_installed'
/usr/local/Cellar/brew-cask/0.45.0/rubylib/cask/cli/list.rb:10:in `run'
/usr/local/Cellar/brew-cask/0.45.0/rubylib/cask/cli.rb:81:in `run_command'
/usr/local/Cellar/brew-cask/0.45.0/rubylib/cask/cli.rb:121:in `process'
/usr/local/bin/brew-cask.rb:42:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:58:in `require?'
/usr/local/Library/brew.rb:142:in `<main>'
[Exit 1 ]
```

bash --version

```
GNU bash, version 3.2.53(1)-release (x86_64-apple-darwin14)
Copyright (C) 2007 Free Software Foundation, Inc.
```

ruby --version
```
ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
```

**Comment by ndr-qef** [comment]
Switching to Yosemite can cause some Ruby woes, but considering that you are running an old version of homebrew-cask, we should first try to upgrade:

```shell
brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup
```

**Comment by unyouthnzadmin** [comment]
Fixed! Thank you, didn't realise cask didn't update with brew update!
