### ISSUE TITLE
Error: undefined method `homepage' for BrewCask:Class on install

### ISSUE THREAD

**Issue by olivergierke** [caskroom/homebrew-cask#8843]
I just tried to install Cask but couldn't get it to work:

```
$ brew tap caskroom/cask
Cloning into '/usr/local/Library/Taps/caskroom/homebrew-cask'...
remote: Counting objects: 118227, done.
remote: Compressing objects: 100% (44/44), done.
remote: Total 118227 (delta 25), reused 1 (delta 0)
Receiving objects: 100% (118227/118227), 32.82 MiB | 100.00 KiB/s, done.
Resolving deltas: 100% (78111/78111), done.
Checking connectivity... done.
Tapped 1 formula
$ brew install brew-cask
Error: undefined method `homepage' for BrewCask:Class
Please report this bug:
    https://github.com/Homebrew/homebrew/wiki/troubleshooting
/usr/local/Library/Taps/caskroom/homebrew-cask/brew-cask.rb:11:in `<class:BrewCask>'
/usr/local/Library/Taps/caskroom/homebrew-cask/brew-cask.rb:10:in `<main>'
$ ruby --version
ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
```

Anything I am missing?

**Comment by jawshooah** [comment]
Could you run `brew update && brew doctor && brew upgrade`, then try again?

**Comment by olivergierke** [comment]
That worked, thanks! :)
