### ISSUE TITLE
Error while installing java

### ISSUE THREAD

**Issue by lexsys27** [caskroom/homebrew-cask#8868]
```
$ cask install java                                                                                                                                                    
Error: wrong number of arguments (1 for 0) while loading '/usr/local/Library/Taps/caskroom/homebrew-cask/Casks/java.rb'
Please report this bug:
    https://github.com/caskroom/homebrew-cask/issues
<main>:8:in `name'
<main>:8:in `<class:Java>'
<main>:in `<main>'
/usr/local/Cellar/brew-cask/0.44.0/rubylib/cask/source/path_base.rb:55:in `eval'
/usr/local/Cellar/brew-cask/0.44.0/rubylib/cask/source/path_base.rb:55:in `rescue in load'
/usr/local/Cellar/brew-cask/0.44.0/rubylib/cask/source/path_base.rb:52:in `load'
/usr/local/Cellar/brew-cask/0.44.0/rubylib/cask/source/tapped.rb:28:in `load'
/usr/local/Cellar/brew-cask/0.44.0/rubylib/cask.rb:123:in `load'
/usr/local/Cellar/brew-cask/0.44.0/rubylib/cask/cli/install.rb:19:in `block in install_casks'
/usr/local/Cellar/brew-cask/0.44.0/rubylib/cask/cli/install.rb:17:in `each'
/usr/local/Cellar/brew-cask/0.44.0/rubylib/cask/cli/install.rb:17:in `install_casks'
/usr/local/Cellar/brew-cask/0.44.0/rubylib/cask/cli/install.rb:6:in `run'
/usr/local/Cellar/brew-cask/0.44.0/rubylib/cask/cli.rb:81:in `run_command'
/usr/local/Cellar/brew-cask/0.44.0/rubylib/cask/cli.rb:121:in `process'
/usr/local/bin/brew-cask.rb:42:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:58:in `require?'
/usr/local/Library/brew.rb:142:in `<main>'
```

Cask is an alias for `brew cask`. Cask version is 0.44.0. Mac OS X 10.10.1

```
$ alias cask                                                                                                                                                          
cask='brew cask'
```

**Comment by ndr-qef** [comment]
This is most likely due to #7946, which only affects outdated versions of homebrew-cask. Upgrading should solve the issue:

```shell
brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup
```

If the problem persists, please let me know.

**Comment by lexsys27** [comment]
Thank you for solution!
