### ISSUE TITLE
Cyberduck - Error: no implicit conversion of nil into String

### ISSUE THREAD

**Issue by echox** [caskroom/homebrew-cask#8874]
Since cask asks me to report this bug, here it is:

> simon@Simons-MBP ~ % brew cask install cyberduck
> ==> Downloading https://update.cyberduck.io/Cyberduck-4.6.1.zip
> Already downloaded: /Library/Caches/Homebrew/cyberduck-4.6.1.zip
> Error: no implicit conversion of nil into String
> Please report this bug:
>    https://github.com/caskroom/homebrew-cask/issues
> /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/digest.rb:44:in `initialize'
> /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/digest.rb:44:in `open'
> /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/digest.rb:44:in `file'
> /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/digest.rb:29:in `file'
> /usr/local/Cellar/brew-cask/0.49.0/rubylib/cask/download.rb:40:in `block in _check_sums'
> /usr/local/Cellar/brew-cask/0.49.0/rubylib/cask/download.rb:38:in `each'
> /usr/local/Cellar/brew-cask/0.49.0/rubylib/cask/download.rb:38:in `_check_sums'
> /usr/local/Cellar/brew-cask/0.49.0/rubylib/cask/download.rb:31:in `perform'
> /usr/local/Cellar/brew-cask/0.49.0/rubylib/cask/installer.rb:74:in `download'
> /usr/local/Cellar/brew-cask/0.49.0/rubylib/cask/installer.rb:51:in `install'
> /usr/local/Cellar/brew-cask/0.49.0/rubylib/cask/cli/install.rb:20:in `block in install_casks'
> /usr/local/Cellar/brew-cask/0.49.0/rubylib/cask/cli/install.rb:17:in `each'
> /usr/local/Cellar/brew-cask/0.49.0/rubylib/cask/cli/install.rb:17:in `install_casks'
> /usr/local/Cellar/brew-cask/0.49.0/rubylib/cask/cli/install.rb:6:in `run'
> /usr/local/Cellar/brew-cask/0.49.0/rubylib/cask/cli.rb:81:in `run_command'
> /usr/local/Cellar/brew-cask/0.49.0/rubylib/cask/cli.rb:121:in `process'
> /usr/local/bin/brew-cask.rb:42:in `<top (required)>'
> /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
> /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
> /usr/local/Library/brew.rb:58:in `require?'
> /usr/local/Library/brew.rb:142:in `<main>'

Please tell me if you need any more information...

**Comment by echox** [comment]
a magic upgrade fixed that, sorry for the noise :-)
