### ISSUE TITLE
syntax error, unexpected tCONSTANT, expecting :: or '[' or '.'

### ISSUE THREAD

**Issue by mattly** [caskroom/homebrew-cask#8876]
```
Error: <main>: syntax error, unexpected tCONSTANT, expecting :: or '[' or '.'
class 010Editor < Cask
               ^
<main>:12: syntax error, unexpected keyword_end, expecting end-of-input while loading '/usr/local/Library/Taps/caskroom/homebrew-cask/Casks/010-editor.rb'
Please report this bug:
    https://github.com/caskroom/homebrew-cask/issues
/usr/local/Cellar/brew-cask/0.45.0/rubylib/cask/source/path_base.rb:55:in `eval'
/usr/local/Cellar/brew-cask/0.45.0/rubylib/cask/source/path_base.rb:55:in `rescue in load'
/usr/local/Cellar/brew-cask/0.45.0/rubylib/cask/source/path_base.rb:52:in `load'
/usr/local/Cellar/brew-cask/0.45.0/rubylib/cask/source/tapped.rb:28:in `load'
/usr/local/Cellar/brew-cask/0.45.0/rubylib/cask.rb:124:in `load'
/usr/local/Cellar/brew-cask/0.45.0/rubylib/cask/scopes.rb:8:in `block in all'
/usr/local/Cellar/brew-cask/0.45.0/rubylib/cask/scopes.rb:8:in `map'
/usr/local/Cellar/brew-cask/0.45.0/rubylib/cask/scopes.rb:8:in `all'
/usr/local/Cellar/brew-cask/0.45.0/rubylib/cask/cli/audit.rb:40:in `casks_to_audit'
/usr/local/Cellar/brew-cask/0.45.0/rubylib/cask/cli/audit.rb:23:in `run'
/usr/local/Cellar/brew-cask/0.45.0/rubylib/cask/cli/audit.rb:7:in `run'
/usr/local/Cellar/brew-cask/0.45.0/rubylib/cask/cli.rb:81:in `run_command'
/usr/local/Cellar/brew-cask/0.45.0/rubylib/cask/cli.rb:121:in `process'
/usr/local/bin/brew-cask.rb:42:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:58:in `require?'
/usr/local/Library/brew.rb:142:in `<main>'
```

happening after a recent `brew update`

**Comment by vitorgalvao** [comment]
You’re using an old version of homebrew-cask. Please `brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup` and try again.

Please [always do this before opening new issues](https://github.com/caskroom/homebrew-cask#reporting-bugs).
