### ISSUE TITLE
Installation fails: brew cask install gdal-framework

### ISSUE THREAD

**Issue by glampr** [caskroom/homebrew-cask#9024]
Brew version is : 0.9.5
```
brew cask install gdal-framework matplotlib
==> Downloading http://www.kyngchaos.com/files/software/frameworks/GDAL_Complete-1.11.dmg
######################################################################## 100.0%
Error: undefined method `extname' for 0:Fixnum
Please report this bug:
    https://github.com/caskroom/homebrew-cask/issues
/usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/container/criteria.rb:43:in `extension'
/usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/container/pkg.rb:3:in `me?'
/usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/container.rb:50:in `block in for_path'
/usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/container.rb:48:in `each'
/usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/container.rb:48:in `find'
/usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/container.rb:48:in `for_path'
/usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/installer.rb:83:in `extract_primary_container'
/usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/installer.rb:50:in `install'
/usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/cli/install.rb:20:in `block in install_casks'
/usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/cli/install.rb:17:in `each'
/usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/cli/install.rb:17:in `install_casks'
/usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/cli/install.rb:6:in `run'
/usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/cli.rb:81:in `run_command'
/usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/cli.rb:121:in `process'
/usr/local/bin/brew-cask.rb:42:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:58:in `require?'
/usr/local/Library/brew.rb:141:in `<main>'
```

**Comment by vitorgalvao** [comment]
You’re using an old version of homebrew-cask. Please `brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup` and try again.

Please [always do this before opening new issues](https://github.com/caskroom/homebrew-cask#reporting-bugs).

**Comment by glampr** [comment]
Sorry, I had run ```brew update```, and then I thought about running ```brew cask update``` but read that it's just a synonym for 'brew update', so I thought I was covered. I should have done my research better.
Perhaps these command can be added in the exception message that reads
```
Please report this bug:
    https://github.com/caskroom/homebrew-cask/issues
```
Just a suggestion. Anyway after running the commands you suggested and trying again I experience the following issues:

```
brew cask install gdal-framework matplotlib
==> Downloading http://www.kyngchaos.com/files/software/frameworks/GDAL_Complete-1.11.dmg
######################################################################## 100.0%
==> Running installer for gdal-framework; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
Password:
==> installer: Package name is GDAL Complete
==> installer: Upgrading at base path /
==> installer: The upgrade was successful.
==> Running installer for gdal-framework; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
Error: pkg source file not found: '/opt/homebrew-cask/Caskroom/gdal-framework/1.11.1-1/Numpy.pkg'
```

and brew cask doctor output is:
```
brew cask doctor
==> OS X Release:
10.10
==> OS X Point Release:
10.10.1
==> Hardware Architecture:
intel-64
==> Ruby Version:
2.0.0-p481
==> Ruby Path:
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
==> Homebrew Version:
0.9.5
==> Homebrew Executable Path:
/usr/local/bin/brew
==> Homebrew Cellar Path:
/usr/local/Cellar
==> Homebrew Repository Path:
/usr/local
==> Homebrew Origin:
https://github.com/Homebrew/homebrew.git
==> Homebrew-cask Version:
0.52.1
==> Homebrew-cask Install Location:
/usr/local/Cellar/brew-cask/0.52.1
==> Homebrew-cask Staging Location:
/opt/homebrew-cask/Caskroom
==> Homebrew-cask Cached Downloads:
/Library/Caches/Homebrew
/Library/Caches/Homebrew/Casks
2 files (warning: run "brew cask cleanup")
78.07 megs (warning: run "brew cask cleanup")
==> Homebrew-cask Default Tap Path:
/usr/local/Library/Taps/caskroom/homebrew-cask
==> Homebrew-cask Alternate Cask Taps:
<NONE>
==> Homebrew-cask Default Tap Cask Count:
2232
==> Contents of $LOAD_PATH:
/usr/local/Cellar/brew-cask/0.52.1/rubylib
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin14
/Library/Ruby/Site/2.0.0/universal-darwin14
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin14
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin14
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin14
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin14
==> Contents of $RUBYLIB Environment Variable:
<NONE>
==> Contents of $RUBYOPT Environment Variable:
<NONE>
==> Contents of $RUBYPATH Environment Variable:
<NONE>
==> Contents of $RBENV_VERSION Environment Variable:
<NONE>
==> Contents of $CHRUBY_VERSION Environment Variable:
<NONE>
==> Contents of $GEM_HOME Environment Variable:
<NONE>
==> Contents of $GEM_PATH Environment Variable:
<NONE>
==> Contents of $BUNDLE_PATH Environment Variable:
<NONE>
==> Contents of $PATH Environment Variable:
PATH="/usr/local/rvm/gems/ruby-2.1.1/bin:/usr/local/rvm/gems/ruby-2.1.1@global/bin:/usr/local/rvm/rubies/ruby-2.1.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/texbin:/usr/local/git/bin:/usr/local/rvm/bin:/Volumes/OptiHD/george/Applications/google-cloud-sdk/bin:/usr/local/Library/ENV/scm"
==> Contents of $SHELL Environment Variable:
SHELL="/bin/bash"
==> Contents of Locale Environment Variables:
LC_CTYPE="UTF-8"
==> Running As Privileged User:
No
```

**Comment by vitorgalvao** [comment]
`brew cask update` is a synonym for `brew update`. That only updates the definitions, though, not the software itself.

Those commands are included in the error messages, but only in the newer versions.

This issue has already been closed as a duplicate. Since your problem now is different, please open a new issue so we can track it better.
