### ISSUE TITLE
Throw error when install kindle previewer via cask

### ISSUE THREAD

**Issue by y00rb** [caskroom/homebrew-cask#9031]
when I install kindle previewer by cask, as follow command:
```bash
brew cask install kindle-previewer
```
it was downloaded by cask, but can't install well. error as below:
```bash
Error: undefined method `extname' for nil:NilClass
Please report this bug:
    https://github.com/caskroom/homebrew-cask/issues
/usr/local/Cellar/brew-cask/0.42.0/rubylib/cask/container/criteria.rb:46:in `extension'
/usr/local/Cellar/brew-cask/0.42.0/rubylib/cask/container/pkg.rb:3:in `me?'
/usr/local/Cellar/brew-cask/0.42.0/rubylib/cask/container.rb:50:in `block in for_path'
/usr/local/Cellar/brew-cask/0.42.0/rubylib/cask/container.rb:48:in `each'
/usr/local/Cellar/brew-cask/0.42.0/rubylib/cask/container.rb:48:in `find'
/usr/local/Cellar/brew-cask/0.42.0/rubylib/cask/container.rb:48:in `for_path'
/usr/local/Cellar/brew-cask/0.42.0/rubylib/cask/installer.rb:83:in `extract_primary_container'
/usr/local/Cellar/brew-cask/0.42.0/rubylib/cask/installer.rb:50:in `install'
/usr/local/Cellar/brew-cask/0.42.0/rubylib/cask/cli/install.rb:20:in `block in install_casks'
/usr/local/Cellar/brew-cask/0.42.0/rubylib/cask/cli/install.rb:17:in `each'
/usr/local/Cellar/brew-cask/0.42.0/rubylib/cask/cli/install.rb:17:in `install_casks'
/usr/local/Cellar/brew-cask/0.42.0/rubylib/cask/cli/install.rb:6:in `run'
/usr/local/Cellar/brew-cask/0.42.0/rubylib/cask/cli.rb:81:in `run_command'
/usr/local/Cellar/brew-cask/0.42.0/rubylib/cask/cli.rb:121:in `process'
/usr/local/bin/brew-cask.rb:42:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:58:in `require?'
/usr/local/Library/brew.rb:141:in `<main>'
```

does anyone have idea to handle it?

**Comment by vitorgalvao** [comment]
You’re using an old version of homebrew-cask. Please `brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup` and try again.

Please [always do this before opening new issues](https://github.com/caskroom/homebrew-cask#reporting-bugs).

**Comment by y00rb** [comment]
thank you too much!

--  
Yang Bo
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)
