### ISSUE TITLE
omni-disk-sweeper un/installation issues

### ISSUE THREAD

**Issue by junkblocker** [caskroom/homebrew-cask#910]
First through a script:

```
% brew cask install omni-disk-sweeper
==> Downloading http://www.omnigroup.com/download/latest/omnidisksweeper
######################################################################## 100.0%
Agree Y/N? y
2013-08-12 11:45:50.568 hdiutil[85512:3303]   handleRequest request: An exception was caught while attempting to create a return message, and will be squashed: [NSMachPort sendBeforeDate:] destination port invalid
hdiutil: mount failed - No child processes
Error: Unimplemented element
```

Then on the command line:

```
% brew cask install omni-disk-sweeper
Error: Cask for omni-disk-sweeper is already installed. Use `--force` to install anyways.

% brew cask uninstall omni-disk-sweeper
Error: undefined method `basename' for nil:NilClass
Please report this bug:
    https://github.com/mxcl/homebrew/wiki/troubleshooting
/usr/brew/Cellar/brew-cask/0.15.0/rubylib/cask/app_linker.rb:16:in `unlink_app'
/usr/brew/Cellar/brew-cask/0.15.0/rubylib/cask/app_linker.rb:12:in `unlink'
/usr/brew/Cellar/brew-cask/0.15.0/rubylib/cask/app_linker.rb:12:in `each'
/usr/brew/Cellar/brew-cask/0.15.0/rubylib/cask/app_linker.rb:12:in `unlink'
/usr/brew/Cellar/brew-cask/0.15.0/rubylib/cask/cli/uninstall.rb:8:in `run'
/usr/brew/Cellar/brew-cask/0.15.0/rubylib/cask/cli/uninstall.rb:5:in `each'
/usr/brew/Cellar/brew-cask/0.15.0/rubylib/cask/cli/uninstall.rb:5:in `run'
/usr/brew/Cellar/brew-cask/0.15.0/rubylib/cask/cli.rb:21:in `process'
/usr/brew/bin/brew-cask.rb:6
/usr/brew/Library/brew.rb:51:in `require'
/usr/brew/Library/brew.rb:51:in `require?'
/usr/brew/Library/brew.rb:101

% brew cask install omni-disk-sweeper
Error: Cask for omni-disk-sweeper is already installed. Use `--force` to install anyways.

% rm -rf /opt/homebrew-cask/Caskroom/omni-disk-sweeper

% brew cask uninstall omni-disk-sweeper
Error: omni-disk-sweeper is not installed

% brew cask install omni-disk-sweeper
==> Downloading http://www.omnigroup.com/download/latest/omnidisksweeper
Already downloaded: /Library/Caches/Homebrew/omni-disk-sweeper-1.8
Agree Y/N? Y
Error: Unimplemented element
```

**Comment by vitorgalvao** [comment]
Can’t reproduce. If someone is still encountering this problem, feel free to reply with a comment.
