### ISSUE TITLE
Issue running edit and create commands.

### ISSUE THREAD

**Issue by fanquake** [caskroom/homebrew-cask#9148]
Reported by humby in IRC

Running the create and edit commands isn't working as expected.

```
Create Output

$ brew cask create test
Error: No such file or directory - mate

  Most likely, this means you have an outdated version of homebrew-cask. Please run:

      brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup

  If this doesn’t fix the problem, please report this bug:

      https://github.com/caskroom/homebrew-cask/issues

/usr/local/Cellar/brew-cask/0.52.1/rubylib/hbc/utils.rb:138:in `exec'
/usr/local/Cellar/brew-cask/0.52.1/rubylib/hbc/utils.rb:138:in `exec_editor'
/usr/local/Cellar/brew-cask/0.52.1/rubylib/hbc/cli/create.rb:23:in `exec_editor'
/usr/local/Cellar/brew-cask/0.52.1/rubylib/hbc/cli/create.rb:17:in `run'
/usr/local/Cellar/brew-cask/0.52.1/rubylib/hbc/cli.rb:79:in `run_command'
/usr/local/Cellar/brew-cask/0.52.1/rubylib/hbc/cli.rb:119:in `process'
/usr/local/Cellar/brew-cask/0.52.1/rubylib/brew-cask-cmd.rb:18:in `<main>'

$ brew cask create test
Error: A Cask for test already exists. Run "brew cask cat test" to see it.


Edit Output

$ brew cask edit test
Error: No such file or directory - mate

  Most likely, this means you have an outdated version of homebrew-cask. Please run:

      brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup

  If this doesn’t fix the problem, please report this bug:

      https://github.com/caskroom/homebrew-cask/issues

/usr/local/Cellar/brew-cask/0.52.1/rubylib/hbc/utils.rb:138:in `exec'
/usr/local/Cellar/brew-cask/0.52.1/rubylib/hbc/utils.rb:138:in `exec_editor'
/usr/local/Cellar/brew-cask/0.52.1/rubylib/hbc/cli/edit.rb:18:in `exec_editor'
/usr/local/Cellar/brew-cask/0.52.1/rubylib/hbc/cli/edit.rb:12:in `run'
/usr/local/Cellar/brew-cask/0.52.1/rubylib/hbc/cli.rb:79:in `run_command'
/usr/local/Cellar/brew-cask/0.52.1/rubylib/hbc/cli.rb:119:in `process'
/usr/local/Cellar/brew-cask/0.52.1/rubylib/brew-cask-cmd.rb:18:in `<main>'


Doctor Output

$ brew cask doctor
==> OS X Release:
10.9
==> OS X Point Release:
10.9.5
==> Hardware Architecture:
intel-64
==> Ruby Version:
2.0.0-p481
==> Ruby Path:
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
==> Homebrew Version:
0.9.5
==> Homebrew Executable Path:
/usr/local/bin/brew
==> Homebrew Cellar Path:
/usr/local/Cellar
==> Homebrew Repository Path:
/usr/local
==> Homebrew Origin:
https://github.com/Homebrew/homebrew
==> Homebrew-cask Version:
0.52.1
==> Homebrew-cask Install Location:
/usr/local/Cellar/brew-cask/0.52.1
==> Homebrew-cask Staging Location:
/opt/homebrew-cask/Caskroom
==> Homebrew-cask Cached Downloads:
/Library/Caches/Homebrew
/Library/Caches/Homebrew/Casks
0 files
0.00 megs
==> Homebrew-cask Default Tap Path:
/usr/local/Library/Taps/caskroom/homebrew-cask
==> Homebrew-cask Alternate Cask Taps:
<NONE>
==> Homebrew-cask Default Tap Cask Count:
2244
==> Contents of $LOAD_PATH:
/usr/local/Cellar/brew-cask/0.52.1/rubylib
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin13
/Library/Ruby/Site/2.0.0/universal-darwin13
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin13
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin13
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin13
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin13
==> Contents of $RUBYLIB Environment Variable:
<NONE>
==> Contents of $RUBYOPT Environment Variable:
<NONE>
==> Contents of $RUBYPATH Environment Variable:
<NONE>
==> Contents of $RBENV_VERSION Environment Variable:
<NONE>
==> Contents of $CHRUBY_VERSION Environment Variable:
<NONE>
==> Contents of $GEM_HOME Environment Variable:
<NONE>
==> Contents of $GEM_PATH Environment Variable:
<NONE>
==> Contents of $BUNDLE_PATH Environment Variable:
<NONE>
==> Contents of $PATH Environment Variable:
PATH="/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/usr/local/Library/Taps/telemachus/homebrew-desc/cmd:/usr/local/Library/ENV/scm"
==> Contents of $SHELL Environment Variable:
SHELL="/bin/bash"
==> Contents of Locale Environment Variables:
LANG="en_AU.UTF-8"
==> Running As Privileged User:
No
```

**Comment by ndr-qef** [comment]
Previously reported as #8788. We have a fix in master; perhaps we should cut a bugfix release.

Refer to https://github.com/caskroom/homebrew-cask/issues/8919#issuecomment-70021838 for details.
