### ISSUE TITLE
cask edit fails using EDITOR with params

### ISSUE THREAD

**Issue by jconley** [caskroom/homebrew-cask#9155]
i have `EDITOR='subl -w'` as specified [here](https://www.sublimetext.com/docs/2/osx_command_line.html)

cask fails as such:
```
$ brew cask edit caskname
Error: No such file or directory - subl -w
<redacted instructions>
/usr/local/Cellar/brew-cask/0.52.1/rubylib/hbc/utils.rb:138:in `exec'
/usr/local/Cellar/brew-cask/0.52.1/rubylib/hbc/utils.rb:138:in `exec_editor'
/usr/local/Cellar/brew-cask/0.52.1/rubylib/hbc/cli/edit.rb:18:in `exec_editor'
/usr/local/Cellar/brew-cask/0.52.1/rubylib/hbc/cli/edit.rb:12:in `run'
/usr/local/Cellar/brew-cask/0.52.1/rubylib/hbc/cli.rb:79:in `run_command'
/usr/local/Cellar/brew-cask/0.52.1/rubylib/hbc/cli.rb:119:in `process'
/usr/local/Cellar/brew-cask/0.52.1/rubylib/brew-cask-cmd.rb:18:in `<main>'
```

**Comment by vitorgalvao** [comment]
[Known issue](https://github.com/caskroom/homebrew-cask/issues/8788).
