### ISSUE TITLE
Error: no implicit conversion of nil into String

### ISSUE THREAD

**Issue by ecasilla** [caskroom/homebrew-cask#9238]
```ruby
Error: no implicit conversion of nil into String
Please report this bug:
    https://github.com/caskroom/homebrew-cask/issues
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/digest.rb:44:in `initialize'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/digest.rb:44:in `open'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/digest.rb:44:in `file'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/digest.rb:29:in `file'
/usr/local/Cellar/brew-cask/0.38.1/rubylib/cask/download.rb:39:in `block in _check_sums'
/usr/local/Cellar/brew-cask/0.38.1/rubylib/cask/download.rb:37:in `each'
/usr/local/Cellar/brew-cask/0.38.1/rubylib/cask/download.rb:37:in `_check_sums'
/usr/local/Cellar/brew-cask/0.38.1/rubylib/cask/download.rb:30:in `perform'
/usr/local/Cellar/brew-cask/0.38.1/rubylib/cask/installer.rb:56:in `download'
/usr/local/Cellar/brew-cask/0.38.1/rubylib/cask/installer.rb:33:in `install'
/usr/local/Cellar/brew-cask/0.38.1/rubylib/cask/cli/install.rb:20:in `block in install_casks'
/usr/local/Cellar/brew-cask/0.38.1/rubylib/cask/cli/install.rb:17:in `each'
/usr/local/Cellar/brew-cask/0.38.1/rubylib/cask/cli/install.rb:17:in `install_casks'
/usr/local/Cellar/brew-cask/0.38.1/rubylib/cask/cli/install.rb:6:in `run'
/usr/local/Cellar/brew-cask/0.38.1/rubylib/cask/cli.rb:80:in `run_command'
/usr/local/Cellar/brew-cask/0.38.1/rubylib/cask/cli.rb:120:in `process'
/usr/local/bin/brew-cask.rb:42:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:58:in `require?'
/usr/local/Library/brew.rb:141:in `<main>'
```

**Comment by ecasilla** [comment]
I ran audit and it spit this out 

Error: <main>: syntax error, unexpected tCONSTANT, expecting :: or '[' or '.'
class 010Editor < Cask
               ^
<main>:11: syntax error, unexpected keyword_end, expecting end-of-input while loading '/usr/local/Library/Taps/caskroom/homebrew-cask/Casks/010-editor.rb'

**Comment by jawshooah** [comment]
You have an outdated version of `brew-cask`. Run `brew update && brew
upgrade brew-cask  && brew cleanup && brew cask cleanup`, then try again.

**Comment by ecasilla** [comment]
Thanks @jawshooah it worked i saw the README to late
