### ISSUE TITLE
brew cask list - not working.

### ISSUE THREAD

**Issue by callerc1** [caskroom/homebrew-cask#9302]
Error: wrong number of arguments (1 for 0) while loading '/usr/local/Library/Taps/caskroom/homebrew-cask/Casks/all-the-gifs.rb'
Please report this bug:
    https://github.com/caskroom/homebrew-cask/issues
<main>:5:in `name'
<main>:5:in `<class:AllTheGifs>'
<main>:in `<main>'
/usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/source/path_base.rb:55:in `eval'
/usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/source/path_base.rb:55:in `rescue in load'
/usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/source/path_base.rb:52:in `load'
/usr/local/Cellar/brew-cask/0.46.0/rubylib/cask.rb:124:in `load'
/usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/scopes.rb:55:in `block in installed'
/usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/scopes.rb:49:in `map'
/usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/scopes.rb:49:in `installed'
/usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/cli/list.rb:52:in `list_installed'
/usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/cli/list.rb:10:in `run'
/usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/cli.rb:81:in `run_command'
/usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/cli.rb:121:in `process'
/usr/local/bin/brew-cask.rb:42:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:58:in `require?'
/usr/local/Library/brew.rb:141:in `<main>'

**Comment by callerc1** [comment]
sorry cask was outdated... Thanks guys.
