### ISSUE TITLE
Can't install Sublime Text formula

### ISSUE THREAD

**Issue by ypxu** [caskroom/homebrew-cask#9355]
I am new to Cask. So here might be something obvious to others. Please correct me if wrong.

I try to install Sublime Text through Cask and get these errors. I compare the format of this formula and it looks similar to others. I also try to update/pull the latest changes. And I try 'brew cask info sublime-text', 'brew cask list sublime-text'. The error is still showing up. 

So I end up 'brew tap caskroom/versions' to install Sublime Text 3.

```
$ brew cask install sublime-text
Error: wrong number of arguments (1 for 0) while loading '/usr/local/Library/Taps/caskroom/homebrew-cask/Casks/sublime-text.rb'
Please report this bug:
    https://github.com/caskroom/homebrew-cask/issues
<main>:8:in `name'
<main>:8:in `<class:SublimeText>'
<main>:in `<main>'
/usr/local/Cellar/brew-cask/0.49.0/rubylib/cask/source/path_base.rb:72:in `eval'
/usr/local/Cellar/brew-cask/0.49.0/rubylib/cask/source/path_base.rb:72:in `rescue in load'
/usr/local/Cellar/brew-cask/0.49.0/rubylib/cask/source/path_base.rb:69:in `load'
/usr/local/Cellar/brew-cask/0.49.0/rubylib/cask/source/tapped.rb:33:in `load'
/usr/local/Cellar/brew-cask/0.49.0/rubylib/cask.rb:78:in `load'
/usr/local/Cellar/brew-cask/0.49.0/rubylib/cask/cli/install.rb:19:in `block in install_casks'
/usr/local/Cellar/brew-cask/0.49.0/rubylib/cask/cli/install.rb:17:in `each'
/usr/local/Cellar/brew-cask/0.49.0/rubylib/cask/cli/install.rb:17:in `install_casks'
/usr/local/Cellar/brew-cask/0.49.0/rubylib/cask/cli/install.rb:6:in `run'
/usr/local/Cellar/brew-cask/0.49.0/rubylib/cask/cli.rb:81:in `run_command'
/usr/local/Cellar/brew-cask/0.49.0/rubylib/cask/cli.rb:121:in `process'
/usr/local/bin/brew-cask.rb:42:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:58:in `require?'
/usr/local/Library/brew.rb:141:in `<main>'
```

**Comment by phinze** [comment]
Hi there! Looks like you're running an old version of cask, you can upgrade with this command:

```
brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup
```

**Comment by ypxu** [comment]
@phinze Thanks for pointing it out. I rerun what you said. It works now.
