### ISSUE TITLE
Installing java through cask fails

### ISSUE THREAD

**Issue by trinityXmontoya** [caskroom/homebrew-cask#9428]
```
Error: wrong number of arguments (1 for 0) while loading '/usr/local/Library/Taps/caskroom/homebrew-cask/Casks/java.rb'
Please report this bug:
    https://github.com/caskroom/homebrew-cask/issues
<main>:8:in `name'
<main>:8:in `<class:Java>'
<main>:in `<main>'
/usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/source/path_base.rb:55:in `eval'
/usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/source/path_base.rb:55:in `rescue in load'
/usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/source/path_base.rb:52:in `load'
/usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/source/tapped.rb:28:in `load'
/usr/local/Cellar/brew-cask/0.46.0/rubylib/cask.rb:124:in `load'
/usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/cli/install.rb:19:in `block in install_casks'
/usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/cli/install.rb:17:in `each'
/usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/cli/install.rb:17:in `install_casks'
/usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/cli/install.rb:6:in `run'
/usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/cli.rb:81:in `run_command'
/usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/cli.rb:121:in `process'
/usr/local/bin/brew-cask.rb:42:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:58:in `require?'
/usr/local/Library/brew.rb:141:in `<main>'
```

**Comment by ndr-qef** [comment]
Quite sorry, there have been some significant changes which broke all homebrew-cask versions prior to 0.50.0. (For details: #7946.) Upgrading should fix the issue:

```
brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup
```

**Comment by crooner** [comment]
Upgrading does not fix this issue.

**Comment by jawshooah** [comment]
@crooner You'll have to be more specific than that. Are you getting the exact same error as @trinityXmontoya? If so, you're using an incredibly old version of `brew-cask` and certainly need to upgrade. If not, please open a new issue, following [these guidelines](https://github.com/caskroom/homebrew-cask/blob/e8ff79f03e3d0f00c016e7ba29ee06016b347f1a/README.md#reporting-bugs).
