### ISSUE TITLE
new cask "pd" - Permission denied - /var/folders....

### ISSUE THREAD

**Issue by megrimm** [caskroom/homebrew-cask#9440]
Hello,

I am not sure what I am doing wrong but I am trying to make a new cask and I am getting the following: 

```
megrimm$ brew cask install pd
==> Downloading http://msp.ucsd.edu/Software/pd-0.46-5-64bit.mac.tar.gz
Already downloaded: /Library/Caches/Homebrew/pd-0.46-5.gz
Error: Permission denied - /var/folders/zg/wwxl966x60g6_t5jbgty96n40000gn/T/d20150205-5418-1b5qe38/Pd-0.46-5-64bit.app/Contents

  Most likely, this means you have an outdated version of homebrew-cask. Please run:

      brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup

  If this doesn’t fix the problem, please report this bug:

      https://github.com/caskroom/homebrew-cask/issues

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1427:in `rmdir'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1427:in `block in remove_dir1'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1438:in `platform_support'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1426:in `remove_dir1'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1419:in `remove'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:770:in `block in remove_entry'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1471:in `block (2 levels) in postorder_traverse'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1471:in `block (2 levels) in postorder_traverse'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1475:in `postorder_traverse'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1470:in `block in postorder_traverse'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1469:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1469:in `postorder_traverse'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1470:in `block in postorder_traverse'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1469:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1469:in `postorder_traverse'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:768:in `remove_entry'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tmpdir.rb:94:in `mktmpdir'
/usr/local/Cellar/brew-cask/0.53.0/rubylib/hbc/container/tar.rb:9:in `extract'
/usr/local/Cellar/brew-cask/0.53.0/rubylib/hbc/installer.rb:103:in `extract_primary_container'
/usr/local/Cellar/brew-cask/0.53.0/rubylib/hbc/installer.rb:62:in `install'
/usr/local/Cellar/brew-cask/0.53.0/rubylib/hbc/cli/install.rb:20:in `block in install_casks'
/usr/local/Cellar/brew-cask/0.53.0/rubylib/hbc/cli/install.rb:17:in `each'
/usr/local/Cellar/brew-cask/0.53.0/rubylib/hbc/cli/install.rb:17:in `install_casks'
/usr/local/Cellar/brew-cask/0.53.0/rubylib/hbc/cli/install.rb:6:in `run'
/usr/local/Cellar/brew-cask/0.53.0/rubylib/hbc/cli.rb:78:in `run_command'
/usr/local/Cellar/brew-cask/0.53.0/rubylib/hbc/cli.rb:118:in `process'
/usr/local/Cellar/brew-cask/0.53.0/rubylib/brew-cask-cmd.rb:18:in `<main>'
```

I have done and get:
```
megrimm$ brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup
Already up-to-date.
Error: brew-cask 0.53.0 already installed
```

Here is:
```
megrimm$ brew cask doctor
==> OS X Release:
10.10
==> OS X Release with Patchlevel:
10.10.2
==> Hardware Architecture:
intel-64
==> Ruby Version:
2.0.0-p481
==> Ruby Path:
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
==> Homebrew Version:
0.9.5
==> Homebrew Executable Path:
/usr/local/bin/brew
==> Homebrew Cellar Path:
/usr/local/Cellar
==> Homebrew Repository Path:
/usr/local
==> Homebrew Origin:
https://github.com/Homebrew/homebrew
==> Homebrew-cask Version:
0.53.0
==> Homebrew-cask Install Location:
/usr/local/Cellar/brew-cask/0.53.0
==> Homebrew-cask Staging Location:
/opt/homebrew-cask/Caskroom
==> Homebrew-cask Cached Downloads:
/Library/Caches/Homebrew
/Library/Caches/Homebrew/Casks
2 files (warning: run "brew cask cleanup")
6.41 megs (warning: run "brew cask cleanup")
==> Homebrew-cask Default Tap Path:
/usr/local/Library/Taps/caskroom/homebrew-cask
==> Homebrew-cask Alternate Cask Taps:
<NONE>
==> Homebrew-cask Default Tap Cask Count:
2274
==> Contents of $LOAD_PATH:
/usr/local/Cellar/brew-cask/0.53.0/rubylib
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin14
/Library/Ruby/Site/2.0.0/universal-darwin14
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin14
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin14
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin14
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin14
==> Contents of $RUBYLIB Environment Variable:
<NONE>
==> Contents of $RUBYOPT Environment Variable:
<NONE>
==> Contents of $RUBYPATH Environment Variable:
<NONE>
==> Contents of $RBENV_VERSION Environment Variable:
<NONE>
==> Contents of $CHRUBY_VERSION Environment Variable:
<NONE>
==> Contents of $GEM_HOME Environment Variable:
<NONE>
==> Contents of $GEM_PATH Environment Variable:
<NONE>
==> Contents of $BUNDLE_PATH Environment Variable:
<NONE>
==> Contents of $PATH Environment Variable:
PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Library/ENV/scm"
==> Contents of $SHELL Environment Variable:
SHELL="/bin/bash"
==> Contents of Locale Environment Variables:
LANG="en_US.UTF-8"
==> Running As Privileged User:
No
Marks-MacBook-Pro:~ megrimm$ brew cask cleanup
==> Removing dead symlinks
Nothing to do
==> Removing cached downloads
/Library/Caches/Homebrew/pd-0.46-5.gz
/Library/Caches/Homebrew/Casks/pd-0.46-5.gz
Marks-MacBook-Pro:~ megrimm$ brew cask doctor
==> OS X Release:
10.10
==> OS X Release with Patchlevel:
10.10.2
==> Hardware Architecture:
intel-64
==> Ruby Version:
2.0.0-p481
==> Ruby Path:
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
==> Homebrew Version:
0.9.5
==> Homebrew Executable Path:
/usr/local/bin/brew
==> Homebrew Cellar Path:
/usr/local/Cellar
==> Homebrew Repository Path:
/usr/local
==> Homebrew Origin:
https://github.com/Homebrew/homebrew
==> Homebrew-cask Version:
0.53.0
==> Homebrew-cask Install Location:
/usr/local/Cellar/brew-cask/0.53.0
==> Homebrew-cask Staging Location:
/opt/homebrew-cask/Caskroom
==> Homebrew-cask Cached Downloads:
/Library/Caches/Homebrew
/Library/Caches/Homebrew/Casks
0 files
0.00 megs
==> Homebrew-cask Default Tap Path:
/usr/local/Library/Taps/caskroom/homebrew-cask
==> Homebrew-cask Alternate Cask Taps:
<NONE>
==> Homebrew-cask Default Tap Cask Count:
2274
==> Contents of $LOAD_PATH:
/usr/local/Cellar/brew-cask/0.53.0/rubylib
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin14
/Library/Ruby/Site/2.0.0/universal-darwin14
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin14
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin14
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin14
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin14
==> Contents of $RUBYLIB Environment Variable:
<NONE>
==> Contents of $RUBYOPT Environment Variable:
<NONE>
==> Contents of $RUBYPATH Environment Variable:
<NONE>
==> Contents of $RBENV_VERSION Environment Variable:
<NONE>
==> Contents of $CHRUBY_VERSION Environment Variable:
<NONE>
==> Contents of $GEM_HOME Environment Variable:
<NONE>
==> Contents of $GEM_PATH Environment Variable:
<NONE>
==> Contents of $BUNDLE_PATH Environment Variable:
<NONE>
==> Contents of $PATH Environment Variable:
PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Library/ENV/scm"
==> Contents of $SHELL Environment Variable:
SHELL="/bin/bash"
==> Contents of Locale Environment Variables:
LANG="en_US.UTF-8"
==> Running As Privileged User:
No
```

Here is my cask:

```
cask :v1 => 'pd' do
  version '0.46-5'
  sha256 'ba9fba46b783ac9f5a83e3bc19612241fe5577b2a38401fc08568dd2ca71d593'

  url "http://msp.ucsd.edu/Software/pd-#{version}-64bit.mac.tar.gz"
  name 'Pd'
  homepage 'http://msp.ucsd.edu/software.html'
  license :bsd

  app 'Pd-0.46-5-64bit.app'
  
  uninstall_preflight do
    system '/bin/chmod', '-R', '--', 'u+w', "#{staged_path}/Pd-0.46-5-64bit.app"
  end
end
```

thanks!
m

**Comment by phinze** [comment]
Hey there! This repros for me locally, looks like `Pd-0.46-5-64bit.app` comes out with permissions `555`

```
dr-xr-xr-x     3 phinze  staff   102B Jan 19 17:43 Pd-0.46-5-64bit.app
```

So the cleanup operation after extraction is failing to remove the temporary dir.

Would it be possible to work with the maintainers of `pd` to get them to repackage their tarball with proper permissions? If not we can look into seeing if Cask can proactively chmod all extracted tarballs, but that seems like overkill if we can just get the maintainers to help us out.

Let me know! :thought_balloon:

**Comment by megrimm** [comment]
hello! yeah I will see what I can do to get Miller (developer) to change permissions. I am assuming he is unaware of an issue.....

the pd.rb cask could also chmod the permissions im assuming thats what you are saying? how easy/hard is that?

thanks!
m

**Comment by phinze** [comment]
> the pd.rb cask could also chmod the permissions im assuming thats what you are saying? how easy/hard is that?

Conceptually easy, but we don't have a ready-made hook at that point in the lifecycle, which means we'd have to modify core code to support it.

**Comment by vitorgalvao** [comment]
@megrimm Any luck contacting the developers?

**Comment by megrimm** [comment]
oh yes... next release problem should be fixed.... hopefully.

On Sun, Mar 15, 2015 at 8:28 AM, Vítor Galvão <notifications@github.com>
wrote:

> @megrimm <https://github.com/megrimm> Any luck contacting the developers?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caskroom/homebrew-cask/issues/9440#issuecomment-80989504>
> .
>



-- 
____________________
m.e.grimm, m.f.a, ed.m.
syracuse u., tc3
megrimm.net
____________________
