### ISSUE TITLE
problem installing quicklook plugins. 

### ISSUE THREAD

**Issue by weaksauce** [caskroom/homebrew-cask#9552]
problem installing quicklook plugins.

```
~ ❯❯❯ brew cask install provisionql
==> Downloading https://github.com/ealeksandrov/ProvisionQL/releases/download/1.0.0/ProvisionQL.zip
Already downloaded: /Library/Caches/Homebrew/provisionql-1.0.0.zip
Error: no implicit conversion of nil into String
Please report this bug:
    https://github.com/caskroom/homebrew-cask/issues
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/digest.rb:44:in `initialize'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/digest.rb:44:in `open'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/digest.rb:44:in `file'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/digest.rb:29:in `file'
/usr/local/Cellar/brew-cask/0.45.0/rubylib/cask/download.rb:41:in `block in _check_sums'
/usr/local/Cellar/brew-cask/0.45.0/rubylib/cask/download.rb:39:in `each'
/usr/local/Cellar/brew-cask/0.45.0/rubylib/cask/download.rb:39:in `_check_sums'
/usr/local/Cellar/brew-cask/0.45.0/rubylib/cask/download.rb:32:in `perform'
/usr/local/Cellar/brew-cask/0.45.0/rubylib/cask/installer.rb:72:in `download'
/usr/local/Cellar/brew-cask/0.45.0/rubylib/cask/installer.rb:49:in `install'
/usr/local/Cellar/brew-cask/0.45.0/rubylib/cask/cli/install.rb:20:in `block in install_casks'
/usr/local/Cellar/brew-cask/0.45.0/rubylib/cask/cli/install.rb:17:in `each'
/usr/local/Cellar/brew-cask/0.45.0/rubylib/cask/cli/install.rb:17:in `install_casks'
/usr/local/Cellar/brew-cask/0.45.0/rubylib/cask/cli/install.rb:6:in `run'
/usr/local/Cellar/brew-cask/0.45.0/rubylib/cask/cli.rb:81:in `run_command'
/usr/local/Cellar/brew-cask/0.45.0/rubylib/cask/cli.rb:121:in `process'
/usr/local/bin/brew-cask.rb:42:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:58:in `require?'
/usr/local/Library/brew.rb:141:in `<main>'
```

running on Yosemite 10.10.2

output of brew --env

```
~ ❯❯❯ brew --env                                                                                                    ⏎
HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j8
CMAKE_PREFIX_PATH: /usr/local
CMAKE_INCLUDE_PATH: /usr/include/libxml2:/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Library/ENV/pkgconfig/10.10
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /usr/local/Library/ENV/4.3:/usr/bin:/bin:/usr/sbin:/sbin
```

output of brew config

```
~ ❯❯❯ brew config
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew.git
HEAD: 1e3503f41b5d16ab1b008c612f9995ed438c0c10
Last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: 8-core 64-bit sandybridge
OS X: 10.10.2-x86_64
Xcode: 6.1.1
CLT: 6.1.1.0.1.1416017670
Clang: 6.0 build 600
X11: 2.7.5 => /opt/X11
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /Users/redacted/anaconda/bin/python => /Users/pmurtha/anaconda/bin/python2.7
Ruby: /Users/redacted/.rubies/ruby-2.1.3/bin/ruby
Java: 1.8.0_20
```

**Comment by Amorymeltzer** [comment]
Hi there!  Your `homebrew-cask` installation is out of date, running the following should set you straight:
````
brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup
````

**Comment by weaksauce** [comment]
awesome thanks! I ran brew update but didn't know I had to update the casks as well.

running that sorted it out nicely.
