### ISSUE TITLE
Error: no implicit conversion of nil into String

### ISSUE THREAD

**Issue by dkelll** [caskroom/homebrew-cask#9559]
I am reporting this as it is asking me to report it. To reproduce: 
1. run `brew cask install quicksilver`
2. download is successful but it does not continue to install; `ctrl+c` to stop the process
3. run `brew cask install quicksilver` once more and receive the below error
NOTE: I tried removing the file and re-running the process but the same issue happened. I also tried running `brew cask doctor` and still the same issue happened.

```shell
myMac:~ dkelll$ brew cask install quicksilver
==> Downloading http://cdn.qsapp.com/plugins/files/com.blacktree.Quicksilver__16401.dmg
Already downloaded: /Library/Caches/Homebrew/quicksilver-1.2.2.dmg
Error: no implicit conversion of nil into String
Please report this bug:
    https://github.com/caskroom/homebrew-cask/issues
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/digest.rb:44:in `initialize'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/digest.rb:44:in `open'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/digest.rb:44:in `file'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/digest.rb:29:in `file'
/usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/download.rb:41:in `block in _check_sums'
/usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/download.rb:39:in `each'
/usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/download.rb:39:in `_check_sums'
/usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/download.rb:32:in `perform'
/usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/installer.rb:72:in `download'
/usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/installer.rb:49:in `install'
/usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/cli/install.rb:20:in `block in install_casks'
/usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/cli/install.rb:17:in `each'
/usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/cli/install.rb:17:in `install_casks'
/usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/cli/install.rb:6:in `run'
/usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/cli.rb:81:in `run_command'
/usr/local/Cellar/brew-cask/0.46.0/rubylib/cask/cli.rb:121:in `process'
/usr/local/bin/brew-cask.rb:42:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:58:in `require?'
/usr/local/Library/brew.rb:141:in `<main>'
```

**Comment by Amorymeltzer** [comment]
Hi there!  Your `homebrew-cask` installation is out of date, running the following should set you straight:
````
brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup
````

**Comment by dkelll** [comment]
Doh! I had updated brew but not cask.  Thanks for the help!

**Comment by Amorymeltzer** [comment]
:+1:
