### ISSUE TITLE
cask list crash when betterzipql installed

### ISSUE THREAD

**Issue by ainopara** [caskroom/homebrew-cask#9600]
```
~ brew cask list
Error: wrong number of arguments (1 for 0) while loading '/usr/local/Library/Taps/caskroom/homebrew-cask/Casks/betterzipql.rb'
Please report this bug:
    https://github.com/caskroom/homebrew-cask/issues
<main>:5:in `name'
<main>:5:in `<class:Betterzipql>'
<main>:in `<main>'
/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/source/path_base.rb:55:in `eval'
/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/source/path_base.rb:55:in `rescue in load'
/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/source/path_base.rb:52:in `load'
/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask.rb:127:in `load'
/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/scopes.rb:55:in `block in installed'
/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/scopes.rb:49:in `map'
/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/scopes.rb:49:in `installed'
/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/cli/list.rb:50:in `list_installed'
/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/cli/list.rb:8:in `run'
/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/cli.rb:80:in `run_command'
/usr/local/Cellar/brew-cask/0.39.3/rubylib/cask/cli.rb:120:in `process'
/usr/local/bin/brew-cask.rb:42:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:58:in `require?'
/usr/local/Library/brew.rb:141:in `<main>'
```

**Comment by Amorymeltzer** [comment]
Hi there!  Your `homebrew-cask` installation is out of date, running the following should set you straight:
````
brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup
````

**Comment by ainopara** [comment]
Thank you. 
After upgrade my brew-cask to latest version, that command works well.
