### ISSUE TITLE
weird problem with installing caffeine with brew cask install --debug caffeine

### ISSUE THREAD

**Issue by Drewshg312** [caskroom/homebrew-cask#9625]
Well now when running `brew cask install --debug caffeine` getting this msg:
```     
==> Downloading
==> Downloading http://download.lightheadsw.com/download.php?software=caffeine
==> Calling curl with args ["http://download.lightheadsw.com/download.php?software=caffeine", "-C", "0", "-o", "#<Pathname:/Library/Caches/Homebrew/caffeine-1.1.1.php.incomplete>"]

curl: (7) Failed to connect to download.lightheadsw.com port 80: Operation timed out
==> Purging files for version 1.1.1 of Cask caffeine
Error: Download failed on Cask 'caffeine' with message: Download failed: http://download.lightheadsw.com/download.php?software=caffeine
/usr/local/Cellar/brew-cask/0.53.3/rubylib/hbc/download.rb:25:in `rescue in perform'
/usr/local/Cellar/brew-cask/0.53.3/rubylib/hbc/download.rb:22:in `perform'
/usr/local/Cellar/brew-cask/0.53.3/rubylib/hbc/installer.rb:89:in `download'
/usr/local/Cellar/brew-cask/0.53.3/rubylib/hbc/installer.rb:63:in `install'
/usr/local/Cellar/brew-cask/0.53.3/rubylib/hbc/cli/install.rb:20:in `block in install_casks'
/usr/local/Cellar/brew-cask/0.53.3/rubylib/hbc/cli/install.rb:17:in `each'
/usr/local/Cellar/brew-cask/0.53.3/rubylib/hbc/cli/install.rb:17:in `install_casks'
/usr/local/Cellar/brew-cask/0.53.3/rubylib/hbc/cli/install.rb:6:in `run'
/usr/local/Cellar/brew-cask/0.53.3/rubylib/hbc/cli.rb:79:in `run_command'
/usr/local/Cellar/brew-cask/0.53.3/rubylib/hbc/cli.rb:119:in `process'
/usr/local/Cellar/brew-cask/0.53.3/rubylib/brew-cask-cmd.rb:18:in `<main>'    ```

**Comment by ndr-qef** [comment]
“Operation timed out” suggests a networking issue outside our control. Does `http://download.lightheadsw.com/download.php?software=caffeine` work from a browser?

**Comment by Drewshg312** [comment]
Oh ok! It doesn't work((( Sorry! Thank you very much... Next time I'll know what this error means..
