### ISSUE TITLE
Permissions error installing scribus

### ISSUE THREAD

**Issue by chazlarson** [caskroom/homebrew-cask#9663]
Received the error once, then ran the suggested commands and received it again.  Reporting as requested.

```bash
# chazlarson at Gerard.localdomain in /Library/Tomcat/bin on master! [20:46:44]
$ brew cask install scribus
==> Downloading http://downloads.sourceforge.net/project/scribus/scribus/1.4.5/scribus-1.4.5.dmg
######################################################################## 100.0%
Error: Permission denied - /opt/homebrew-cask/Caskroom/scribus

  Most likely, this means you have an outdated version of homebrew-cask. Please run:

      brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup

  If this doesn’t fix the problem, please report this bug:

      https://github.com/caskroom/homebrew-cask/issues

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:245:in `mkdir'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:245:in `fu_mkdir'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:219:in `block (2 levels) in mkdir_p'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:217:in `reverse_each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:217:in `block in mkdir_p'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:203:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:203:in `mkdir_p'
/usr/local/Cellar/brew-cask/0.53.3/rubylib/hbc/installer.rb:100:in `extract_primary_container'
/usr/local/Cellar/brew-cask/0.53.3/rubylib/hbc/installer.rb:65:in `install'
/usr/local/Cellar/brew-cask/0.53.3/rubylib/hbc/cli/install.rb:20:in `block in install_casks'
/usr/local/Cellar/brew-cask/0.53.3/rubylib/hbc/cli/install.rb:17:in `each'
/usr/local/Cellar/brew-cask/0.53.3/rubylib/hbc/cli/install.rb:17:in `install_casks'
/usr/local/Cellar/brew-cask/0.53.3/rubylib/hbc/cli/install.rb:6:in `run'
/usr/local/Cellar/brew-cask/0.53.3/rubylib/hbc/cli.rb:79:in `run_command'
/usr/local/Cellar/brew-cask/0.53.3/rubylib/hbc/cli.rb:119:in `process'
/usr/local/Cellar/brew-cask/0.53.3/rubylib/brew-cask-cmd.rb:18:in `<main>'
```

**Comment by rolandwalker** [comment]
Hi!

We recently broadened that error message to suggest upgrading for almost anything that goes wrong.  Perhaps we should remove the words "Most likely".

Here it appears that there is a simple permissions problem on your filesystem.  You can examine the files under `/opt/homebrew-cask/Caskroom/scribus` to see what is the matter.  Or, what is probably easier, simply

```bash
$ sudo rm -rf /opt/homebrew-cask/Caskroom/scribus/
```

after which you should be able to install again.

**Comment by vitorgalvao** [comment]
> Perhaps we should remove the words "Most likely".

“Most commonly”?

**Comment by chazlarson** [comment]
Should my user account have write access to /opt/homebrew-cask/Caskroom?  That seems to be the root of the issue.  I noticed that the scribus directory wasn't even present there after this error, so tried:

```
 chazlarson at Gerard.localdomain in ~ [15:18:37]
$ mkdir /opt/homebrew-cask/Caskroom/spork
mkdir: /opt/homebrew-cask/Caskroom/spork: Permission denied

# chazlarson at Gerard.localdomain in ~ [15:21:27]
$ ls -al /opt/homebrew-cask/
total 16
drwxr-xr-x   4 root  wheel   136 Jan 26  2014 .
drwxr-xr-x@  8 root  wheel   272 Aug 21  2014 ..
-rw-r--r--@  1 root  wheel  6148 Jan 26  2014 .DS_Store
drwxr-xr-x  10 root  wheel   340 Oct  4 13:48 Caskroom

# chazlarson at Gerard.localdomain in ~ [15:21:37]
$
```

**Comment by rolandwalker** [comment]
Yes, the user account must have read/write on `/opt/homebrew-cask/Caskroom`.

**Comment by chazlarson** [comment]
Curious.  I wonder why mine doesn't.  I don't recall doing anything weird with my Brew install.  Regardless, closing this up.  Thanks!
