### ISSUE TITLE
Issue when installing Fritzing

### ISSUE THREAD

**Issue by meadowstream** [caskroom/homebrew-cask#9717]
When I do `> brew cask install fritzing`

I receive the following:
```
Already downloaded: /Library/Caches/Homebrew/fritzing-0.9.1b.dmg
Error: no implicit conversion of nil into String
Please report this bug:
    https://github.com/caskroom/homebrew-cask/issues
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/digest.rb:44:in `initialize'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/digest.rb:44:in `open'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/digest.rb:44:in `file'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/digest.rb:29:in `file'
/usr/local/Cellar/brew-cask/0.38.1/rubylib/cask/download.rb:39:in `block in _check_sums'
/usr/local/Cellar/brew-cask/0.38.1/rubylib/cask/download.rb:37:in `each'
/usr/local/Cellar/brew-cask/0.38.1/rubylib/cask/download.rb:37:in `_check_sums'
/usr/local/Cellar/brew-cask/0.38.1/rubylib/cask/download.rb:30:in `perform'
/usr/local/Cellar/brew-cask/0.38.1/rubylib/cask/installer.rb:56:in `download'
/usr/local/Cellar/brew-cask/0.38.1/rubylib/cask/installer.rb:33:in `install'
/usr/local/Cellar/brew-cask/0.38.1/rubylib/cask/cli/install.rb:20:in `block in install_casks'
/usr/local/Cellar/brew-cask/0.38.1/rubylib/cask/cli/install.rb:17:in `each'
/usr/local/Cellar/brew-cask/0.38.1/rubylib/cask/cli/install.rb:17:in `install_casks'
/usr/local/Cellar/brew-cask/0.38.1/rubylib/cask/cli/install.rb:6:in `run'
/usr/local/Cellar/brew-cask/0.38.1/rubylib/cask/cli.rb:80:in `run_command'
/usr/local/Cellar/brew-cask/0.38.1/rubylib/cask/cli.rb:120:in `process'
/usr/local/bin/brew-cask.rb:42:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:58:in `require?'
/usr/local/Library/brew.rb:141:in `<main>'
```

Any suggestions as to what the problem here is?

**Comment by Amorymeltzer** [comment]
Hi there!  Your `homebrew-cask` installation is out of date, running the following should set you straight:
````
brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup
````

**Comment by meadowstream** [comment]
Thanks for helping! :) 

`brew upgrade brew-cask` returns `Error: No available formula for brew-cask` 

brew-cask is listed in when I do `brew list` - any ideas?

**Comment by Amorymeltzer** [comment]
If you run `brew doctor`, does it warn about broken symlinks?  Try running `brew prune` and see if that works.  If not, you can also try retapping and reinstalling.

```
brew uninstall brew-cask && brew untap caskroom/cask && brew install caskroom/cask/brew-cask
```

**Comment by meadowstream** [comment]
Thanks! :beers:
