### ISSUE TITLE
Cask command asked me to report an issue

### ISSUE THREAD

**Issue by lahwran** [caskroom/homebrew-cask#9760]
```
lahwran@lahwran:~$ brew cask uninstall clementine
Error: wrong number of arguments (1 for 0) while loading '/usr/local/Library/Taps/caskroom/homebrew-cask/Casks/clementine.rb'
Please report this bug:
    https://github.com/caskroom/homebrew-cask/issues
<main>:8:in `name'
<main>:8:in `<class:Clementine>'
<main>:in `<main>'
/usr/local/Cellar/brew-cask/0.45.0/rubylib/cask/source/path_base.rb:55:in `eval'
/usr/local/Cellar/brew-cask/0.45.0/rubylib/cask/source/path_base.rb:55:in `rescue in load'
/usr/local/Cellar/brew-cask/0.45.0/rubylib/cask/source/path_base.rb:52:in `load'
/usr/local/Cellar/brew-cask/0.45.0/rubylib/cask/source/tapped.rb:28:in `load'
/usr/local/Cellar/brew-cask/0.45.0/rubylib/cask.rb:124:in `load'
/usr/local/Cellar/brew-cask/0.45.0/rubylib/cask/cli/uninstall.rb:8:in `block in run'
/usr/local/Cellar/brew-cask/0.45.0/rubylib/cask/cli/uninstall.rb:6:in `each'
/usr/local/Cellar/brew-cask/0.45.0/rubylib/cask/cli/uninstall.rb:6:in `run'
/usr/local/Cellar/brew-cask/0.45.0/rubylib/cask/cli.rb:81:in `run_command'
/usr/local/Cellar/brew-cask/0.45.0/rubylib/cask/cli.rb:121:in `process'
/usr/local/bin/brew-cask.rb:42:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:58:in `require?'
/usr/local/Library/brew.rb:141:in `<main>'
lahwran@lahwran:~$ brew cask update
Updated Homebrew from 507aee20 to 2dc5c414.
==> New Formulae
aeskeyfind	  deisctl	    gcovr	      goolabs		kubernetes-cli	  libepoxy	    openhmd	      pdf-redact-tools	scalaenv	  sstp-client	    vegeta	      wifi-password	wslay
==> Updated Formulae
aacgain			ansible			cereal			dos2unix		fzf			googlecl		homebrew/x11/wmctrl	ipsumdump		libgadu			lsh			neon			pstoedit		scm-manager		terraform		vowpal-wabbit
abcl			aptly			cgal			dvorak7min		gauge			gradle			htop-osx		jetty			libmp3splt		mdr			neovim/neovim/neovim	pup			sipsak			the_platinum_searcher	wellington
abcmidi			asciinema		cheat			dynamodb-local		gh			groovy			httpie			jq			libmpc			memo			nettle			python			sntop			tomcat			wine
abduco			avian			chromedriver		elasticsearch		ghostscript		groovyserv		hub			juju			libmpdclient		mongo-c			newlisp			python3			spiped			tor			writerperfect
abook			berkeley-db		clang-format		enet			git-extras		gtk-gnutella		hugo			kakasi			libmusicbrainz		mp3info			newsbeuter		qt			spoof-mac		typesafe-activator	yacas
acpica			bind			couchdb-lucene		epstool			github-release		gvp			ice			keybase			libodfgen		mp3splt			nsq			qt5			ssdb			unittest		yara
activemq		bsdmake			css-crush		ffmpeg			gl2ps			h2o			icecream		kvazaar			libpointing		mpich2			orientdb		rakudo-star		sync_gateway		unittest-cpp		youtube-dl
activemq-cpp		capstone		cvs			fish			global			hamsterdb		iftop			latex2html		librevenge		mtr			osquery			redpen			sysbench		unrar			znc
adplug			carthage		datomic			fleetctl		gnupg2			hbase			iojs			libdvdcss		libxmp			mysql			peco			rocket			szip			uru
aespipe			cctools			direnv			flow			go			hg-flow			iozone			libdvdnav		logcheck		mysql-cluster		pinentry-mac		rust			task			vilistextum
afflib			center-im		docker			fsh			google-app-engine	homebrew/dupes/make	ipbt			libdvdread		lolcode			n			pngpaste		s-lang			tcptraceroute		vnu
==> Deleted Formulae
adobe-air-sdk  celt
lahwran@lahwran:~$ brew cask uninstall clementine
Error: wrong number of arguments (1 for 0) while loading '/usr/local/Library/Taps/caskroom/homebrew-cask/Casks/clementine.rb'
Please report this bug:
    https://github.com/caskroom/homebrew-cask/issues
<main>:8:in `name'
<main>:8:in `<class:Clementine>'
<main>:in `<main>'
/usr/local/Cellar/brew-cask/0.45.0/rubylib/cask/source/path_base.rb:55:in `eval'
/usr/local/Cellar/brew-cask/0.45.0/rubylib/cask/source/path_base.rb:55:in `rescue in load'
/usr/local/Cellar/brew-cask/0.45.0/rubylib/cask/source/path_base.rb:52:in `load'
/usr/local/Cellar/brew-cask/0.45.0/rubylib/cask/source/tapped.rb:28:in `load'
/usr/local/Cellar/brew-cask/0.45.0/rubylib/cask.rb:124:in `load'
/usr/local/Cellar/brew-cask/0.45.0/rubylib/cask/cli/uninstall.rb:8:in `block in run'
/usr/local/Cellar/brew-cask/0.45.0/rubylib/cask/cli/uninstall.rb:6:in `each'
/usr/local/Cellar/brew-cask/0.45.0/rubylib/cask/cli/uninstall.rb:6:in `run'
/usr/local/Cellar/brew-cask/0.45.0/rubylib/cask/cli.rb:81:in `run_command'
/usr/local/Cellar/brew-cask/0.45.0/rubylib/cask/cli.rb:121:in `process'
/usr/local/bin/brew-cask.rb:42:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:58:in `require?'
/usr/local/Library/brew.rb:141:in `<main>'
lahwran@lahwran:~$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in the App Store.

Warning: Putting non-prefixed coreutils in your path can cause gmp builds to fail.

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
    /usr/local/lib/libarena-4e7c5e5c.dylib
    /usr/local/lib/libflate-4e7c5e5c.dylib
    /usr/local/lib/libfmt_macros-4e7c5e5c.dylib
    /usr/local/lib/libgetopts-4e7c5e5c.dylib
    /usr/local/lib/libgraphviz-4e7c5e5c.dylib
    /usr/local/lib/liblog-4e7c5e5c.dylib
    /usr/local/lib/librbml-4e7c5e5c.dylib
    /usr/local/lib/librustc-4e7c5e5c.dylib
    /usr/local/lib/librustc_back-4e7c5e5c.dylib
    /usr/local/lib/librustc_borrowck-4e7c5e5c.dylib
    /usr/local/lib/librustc_driver-4e7c5e5c.dylib
    /usr/local/lib/librustc_llvm-4e7c5e5c.dylib
    /usr/local/lib/librustc_privacy-4e7c5e5c.dylib
    /usr/local/lib/librustc_resolve-4e7c5e5c.dylib
    /usr/local/lib/librustc_trans-4e7c5e5c.dylib
    /usr/local/lib/librustc_typeck-4e7c5e5c.dylib
    /usr/local/lib/librustdoc-4e7c5e5c.dylib
    /usr/local/lib/libserialize-4e7c5e5c.dylib
    /usr/local/lib/libstd-4e7c5e5c.dylib
    /usr/local/lib/libsyntax-4e7c5e5c.dylib
    /usr/local/lib/libterm-4e7c5e5c.dylib
    /usr/local/lib/libtest-4e7c5e5c.dylib

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:

    ceylon
    python

Warning: Some directories in your path end in a slash.
Directories in your path should not end in a slash. This can break other
doctor checks. The following directories should be edited:
    /Users/lahwran/adt/sdk/tools/    /Users/lahwran/katamari/operations/bin/    /Users/lahwran/winmonitor/frozen2/bin/

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so
    echo export PATH='/usr/local/sbin:$PATH' >> ~/.bash_profile
lahwran@lahwran:~$
```

**Comment by vitorgalvao** [comment]
You’re using an old version of homebrew-cask. Please `brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup` and try again.

Please [always do this before opening new issues](https://github.com/caskroom/homebrew-cask#reporting-bugs).

**Comment by lahwran** [comment]
It'd be cool if it actually said that in errors, instead of just "report this". I tried to update it, but the obvious thing didn't work, apparently.

**Comment by vitorgalvao** [comment]
It does say that, just not in the version you had (introduced in `0.50.0`).
