### ISSUE TITLE
undefined method `extname' for 0:Fixnum

### ISSUE THREAD

**Issue by grevolution** [caskroom/homebrew-cask#9777]
Hi Guys, 

I was installing slack using cask and got the following error:

```
Error: undefined method `extname' for 0:Fixnum
Please report this bug:
    https://github.com/caskroom/homebrew-cask/issues
/usr/local/Cellar/brew-cask/0.37.1/rubylib/cask/container/air.rb:3:in `me?'
/usr/local/Cellar/brew-cask/0.37.1/rubylib/cask/container.rb:38:in `block in for_path'
/usr/local/Cellar/brew-cask/0.37.1/rubylib/cask/container.rb:36:in `each'
/usr/local/Cellar/brew-cask/0.37.1/rubylib/cask/container.rb:36:in `find'
/usr/local/Cellar/brew-cask/0.37.1/rubylib/cask/container.rb:36:in `for_path'
/usr/local/Cellar/brew-cask/0.37.1/rubylib/cask/installer.rb:69:in `extract_primary_container'
/usr/local/Cellar/brew-cask/0.37.1/rubylib/cask/installer.rb:36:in `install'
/usr/local/Cellar/brew-cask/0.37.1/rubylib/cask/cli/install.rb:20:in `block in install_casks'
/usr/local/Cellar/brew-cask/0.37.1/rubylib/cask/cli/install.rb:17:in `each'
/usr/local/Cellar/brew-cask/0.37.1/rubylib/cask/cli/install.rb:17:in `install_casks'
/usr/local/Cellar/brew-cask/0.37.1/rubylib/cask/cli/install.rb:6:in `run'
/usr/local/Cellar/brew-cask/0.37.1/rubylib/cask/cli.rb:80:in `run_command'
/usr/local/Cellar/brew-cask/0.37.1/rubylib/cask/cli.rb:120:in `process'
/usr/local/bin/brew-cask.rb:42:in `<top (required)>'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:58:in `require?'
/usr/local/Library/brew.rb:142:in `<main>'
```

not sure what the issue is. anybody faced this issue before?

**Comment by Amorymeltzer** [comment]
Hi there, you're using an outdated version of homebrew-cask, upgrading via the following should set you straight:
`brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup`

**Comment by grevolution** [comment]
Tried that too, I already have the latest brew and latest brew-cask

**Comment by phinze** [comment]
Hi there!

Your path:

```
/usr/local/Cellar/brew-cask/0.37.1/rubylib/cask/container.rb
```

...suggests you have v0.37.1, while we are all the way up on v0.53.3. Is it possible that `brew update` is not picking up the latest updates for you?

**Comment by utkarshkukreti** [comment]
Try

```
brew rm caskroom/cask/brew-cask
brew install caskroom/cask/brew-cask
```

**Comment by dwbutler** [comment]
`brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup` worked for me. I was under the impression that `brew cask update` would do all this, but I guess I was wrong and should have RTFM.
